### ISSUE TITLE
[Suggestion] Compatibility with BetterNether

### ISSUE THREAD

**Issue by paulevsGitch** [CorgiTaco/BYG#10]
Good day. I am author of [BetterNether](https://www.curseforge.com/minecraft/mc-mods/betternether) mod and I want to make a small suggestion about compatibility. As I can see nylium blocks from BYG doesn't have "minecraft:nylium" block tag, could you add it? This will allow plants to grow on them and will correct bonemeal effect. Thank you in advance

**Comment by CorgiTaco** [comment]
Wanted to ask, does my mixin into the nether biome provider work with your mod? And yes I'll get this fixed!

**Comment by paulevsGitch** [comment]
Looks like all other things works fine. Probably because of my own biome provider (something may generate wrong, I don't know what changes you made). If you are interesting I'm trying to cooperate with Cinderscapes developers to integrate my code and their code into unified biome library. And at this time I have a small API for advanced biome generation (like sub-biomes or edges)

![2020-07-04_01 12 10](https://user-images.githubusercontent.com/17707380/86517361-fff25280-be30-11ea-82bc-3ef3c4fe1089.png)

![2020-07-04_20 02 11](https://user-images.githubusercontent.com/17707380/86517396-48aa0b80-be31-11ea-86e3-3669e0f011a4.png)

**Comment by CorgiTaco** [comment]
Should be patched here: 
https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go-fabric/files/2996610

LMK if it worked.

**Comment by paulevsGitch** [comment]
The last one tag is incorrect (must be "byg:nylium_soul_sand", with namespace)

![image](https://user-images.githubusercontent.com/17707380/86521928-52e2fe80-be5f-11ea-9077-b1c0d40db75a.png)

P.S.: BetterNether also has a tag "common:soul_ground" for soul-sand-soil like blocks, can you add "Nylium Soul Sand" and "Nylium Soul Soil" into it?

**Comment by paulevsGitch** [comment]
With manually corrected tag it works

![2020-07-05_01 40 32](https://user-images.githubusercontent.com/17707380/86522027-9ee27300-be60-11ea-93d8-d22348641c48.png)

**Comment by CorgiTaco** [comment]
oh my bad didnt realize my misspell

**Comment by CorgiTaco** [comment]
https://github.com/CorgiTaco/BYG/tree/Fabric-1.16.X/src/main/resources/data/common/tags/blocks
does this look correct? Im new to this whole common/tag system

**Comment by paulevsGitch** [comment]
Looks like it is correct

**Comment by CorgiTaco** [comment]
Should I add my nylium blocks that are literally netherrack but are a top block variant too the netherrack tag?

**Comment by paulevsGitch** [comment]
I think yes, this tag was created for all types of netherrack including nylium

**Comment by Brickboss-tech** [comment]
Is this still oen?

**Comment by paulevsGitch** [comment]
There is [an issue](https://github.com/paulevsGitch/BetterNether/issues/134) with biome generation. It appeared on latest version of BYG.

**Comment by paulevsGitch** [comment]
I think the best way to solve it is to add another condition with "betternether" [here](https://github.com/CorgiTaco/BYG/blob/Fabric-1.16.X/src/main/java/voronoiaoc/byg/mixin/common/MixinDimensionType.java#L19)

**Comment by CorgiTaco** [comment]
https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go-fabric/files/2997209

LMK if it worked. It worked for me at least.

**Comment by CorgiTaco** [comment]
Also My nether BP was pulling from fabric api's added nether biomes so thats odd.

**Comment by CorgiTaco** [comment]
Should be it. If i missed something comment on this issue. I'm closing

**Comment by paulevsGitch** [comment]
Now it works, thank you
