### ISSUE TITLE
Sub Biomes

### ISSUE THREAD

**Issue by AOCAWOL** [CorgiTaco/BYG#10]
The following biomes will be added by the full release of 1.14.4 update:
**(Subject To Change)**
-Cika Wooded Mountains
-Red Oak Forest Hills
-Giant Blue Spruce Tiaga
-Jacaranda Forest Hills
-Alpine Foothills
-Giant Seasonal Spruce Taiga
-Seasonal Forest Hills
-Maple Wooded Hills
-Coastal Redwood Tropic Cliffs
-Cherry Blossom Clearing
-Flowering Meadow
-Pine Taiga
-Mojave Joshua Tree Forest
-Infested Dead Sea
-Seasonal Birch Forest Hills
-Orchard Hills
-Blue Taiga Hills
-Seasonal Taiga Hills
-Boreal Forest Hills
-Great Lake Isles
-Aspen Wooded Hills
-Snowy Giant Blue Spruce Taiga
-Snowy Pine Tiaga

**Comment by CorgiTaco** [comment]
Sub biomes have been added in the 1.15 versions and are always subject to change rendering this list useless and invalid
