### ISSUE TITLE
[1.16.3-Forge] World doesn't generate/contain any BYG biomes.

### ISSUE THREAD

**Issue by Gbergz** [CorgiTaco/BYG#100]
Title^

Looks like no modded biomes are spawning at all, using the ``/locatebiome`` commands yields no results because it can't find anything under the ``byg:example`` tag.
Same for the ``Nature's Compass`` from the mod ``Nature's Compass`` while it does list the biomes there, no biomes are actually spawning.

**Modlist:** https://gist.github.com/Gbergz/a96ca71896f8de0c8304518ec260d3fb

**Minecraft:** 1.16.3
**Forge Version:** 34.1.0
**BYG Version:** 1.0.5

**-** Gbergz

**Comment by CorgiTaco** [comment]
Should be fixed, but lmk https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go/files/3064057

**Comment by Gbergz** [comment]
Now it's back to this issue #97 though it's happening without OptiFine.

**Comment by CorgiTaco** [comment]
Are you sure?

**Comment by Gbergz** [comment]
Yes, just tried with 1.0.7 and its happening with those mods in the list i linked.

Edit: 1.0.5 managed to generate the world, but no biomes are generated. Like i mentioned above. 1.0.7 is back to the "unknown biome id" spam.

**Comment by CorgiTaco** [comment]
BYG Works independently as I've just tested it. So this is suggesting a mod conflict so now it's your duty to report the mod causing this in #97

**Comment by Gbergz** [comment]
I'll get on that when I have more time, thanks for the answers!
**-** Gbergz
