### ISSUE TITLE
1.19.2 crash

### ISSUE THREAD

**Issue by Thisguyneedshelp** [CorgiTaco/BYG#1002]
### BYG Version

2.0.0.13

### Terrablender Version

2.0.1.128

### Mod Loader

Forge

### Mod Loader Version

43.1.47

### What happened?

server crash on startup but theres also a buncha other mods' issues in the log

### crash-log

https://mclo.gs/A2huxnw

### latest.log

[latest (41).log](https://github.com/AOCAWOL/BYG/files/9873847/latest.41.log)

### Did you isolate BYG?

I did not try BYG alone

**Comment by CorgiTaco** [comment]
Delete your configs folder and let it regen.
