### ISSUE TITLE
[1.19][Bug]: Empty sand tags making it impossible to craft sandstone

### ISSUE THREAD

**Issue by cc303** [CorgiTaco/BYG#1005]
### BYG Version

1.19.2-2.0.0.13

### Mod Loader

Forge

### Mod Loader Version

43.1.1

### Bug Severity

Minor

### What happened?

When crafting colored sand from BYO, the connection between sand turning into sandstone shows are [empty tag], making it impossible to craft the colored sandstone in survival mode. Every colored sand has empty tag so it cannot be converted into sandstone from sand.

### latest.log

[2022-10-27-2.log.gz](https://github.com/AOCAWOL/BYG/files/9882610/2022-10-27-2.log.gz)

### Did you isolate BYG?

I tried BYG alone

**Comment by CorgiTaco** [comment]
Fixed in: https://github.com/AOCAWOL/BYG/pull/1016
