### ISSUE TITLE
[1.19][Bug]: byg:tall_allium and byg:tall_pink_allium are tagged as minecraft:small_flowers 

### ISSUE THREAD

**Issue by TelepathicGrunt** [CorgiTaco/BYG#1006]
### BYG Version

2.0.0.13

### Terrablender Version

N/A

### Mod Loader

Forge

### Mod Loader Version

N/A

### Bug Severity

Minor

### What happened?

byg:tall_allium and byg:tall_pink_allium are tagged as minecraft:small_flowers when they are double block tall plants. As a result, my mod and probably a few others may be spawning half of this tall plant by mistake.

The tag to edit in BYG:
https://github.com/AOCAWOL/BYG/blob/c8183683fbb0f641e0e79675431557d384a4f456/Common/src/main/resources/data/minecraft/tags/blocks/small_flowers.json#L61-L62

![image](https://user-images.githubusercontent.com/40846040/198468076-6bcfd355-45bb-453b-bcf7-4599e2ad55b6.png)

### latest.log

no log

### Did you isolate BYG?

I tried BYG alone

**Comment by TelepathicGrunt** [comment]
Also, Pollen Block is put here as well. Which is going to cause some weird behaviors with mods checking for small flower tagged blocks. Like My pollen puff block tries to multiply flower tagged blocks as if it is pollinating flowers. I can try to blacklist this block from my behaviors but I can't say how other mods may react with this pollen block
https://github.com/AOCAWOL/BYG/blob/c8183683fbb0f641e0e79675431557d384a4f456/Common/src/main/resources/data/minecraft/tags/blocks/small_flowers.json#L60

**Comment by TelepathicGrunt** [comment]
byg:delphinium and byg:japanese_orchid appears to also be a double tall flower tagged as a small flower. Might be a good idea to go through this tag entirely to make sure it is small flowers and not double tall flowers
https://github.com/AOCAWOL/BYG/blob/c8183683fbb0f641e0e79675431557d384a4f456/Common/src/main/resources/data/minecraft/tags/blocks/small_flowers.json#L19

**Comment by CorgiTaco** [comment]
Fixed in: https://github.com/AOCAWOL/BYG/commit/60aaa3428ac5673b78a38d1c5fa86170ec685f9c
