### ISSUE TITLE
[1.18][Bug]: Can't seem to disable the Biomepedia from starting in your inventory

### ISSUE THREAD

**Issue by Filostorm** [CorgiTaco/BYG#1008]
### BYG Version

Oh_The_Biomes_You'll_Go-forge-1.18.2-1.4.7

### Terrablender Version

TerraBlender-forge-1.18.2-1.2.0.126

### Mod Loader

Forge

### Mod Loader Version

40.1.82

### Bug Severity

Minor

### What happened?

I've gone over all the configs I could fine, and the only thing I was able to do was disable the inventory button. I'd really like to disable spawning with the book if possible.

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/9892733/latest.log)

### Did you isolate BYG?

I tried BYG alone

**Comment by CorgiTaco** [comment]
[no_biomepedia.zip](https://github.com/AOCAWOL/BYG/files/9892739/no_biomepedia.zip) add this datapack

**Comment by Filostorm** [comment]
Sweet thanks! Is this information able to be found in the config files anywhere? Asking for future players
