### ISSUE TITLE
[1.19][Bug]: Can't find any lament vine in weeping mire biome

### ISSUE THREAD

**Issue by RedBeast1959** [CorgiTaco/BYG#1015]
### BYG Version

Oh_The_Biomes_You'll_Go-forge-1.19.2-2.0.0.13.jar

### Terrablender Version

TerraBlender-forge-1.19.2-2.0.1.129.jar

### Mod Loader

Forge

### Mod Loader Version

43.1.47

### Bug Severity

Minor

### What happened?

I heard lament vine can be found in weeping mire biome which lament trees are growing. But I can't find any lament vine in that biome. Personally I can't find any changelog about lament vine(or I just miss it), so I suspect missing lament vine is a bug during biome generation.

### latest.log

.

### Did you isolate BYG?

I tried BYG alone

**Comment by CorgiTaco** [comment]
Fixed in https://github.com/AOCAWOL/BYG/commit/855df54d4ffd05cea8cb6da3a362e4a6ffd54e6b
