### ISSUE TITLE
[1.19][Bug]: Biomepedia Cannot be removed from inventory

### ISSUE THREAD

**Issue by elblasy1986** [CorgiTaco/BYG#1017]
### BYG Version

2.0.0.13

### Terrablender Version

2.3.5

### Mod Loader

Forge

### Mod Loader Version

43.1.43

### Bug Severity

Major

### What happened?

I want to disable the Biomepedia from being with the player at the beginning of any world. I went to BYG config folder and changed the value "inventory_enabled" in the file "biomepedia.json5" to "false". I have also changed the value"visible" to "false" in the file "biomepedia_inventory.json5" from "client" folder.

But I always start any world with the Biomepedia.

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/9943169/latest.log)

### Did you isolate BYG?

I did not try BYG alone

**Comment by XAgent1990** [comment]
I don't think this is a bug.
Only thing you can disable in config is the button that is visible in the players inventory.
The book in the beginning isn't affected, but it's definitely something I think is unfortunate as well.

**Comment by CorgiTaco** [comment]
It's disabled via datapack bc the book item is an advancement, use this datapack:

[no_biomepedia.zip](https://github.com/AOCAWOL/BYG/files/9984016/no_biomepedia.zip)

**Comment by thimblebird** [comment]
add this to the wiki maybe?
