### ISSUE TITLE
[1.19][Bug]: Forager Table does not provide that profession to villager

### ISSUE THREAD

**Issue by VinceKezel** [CorgiTaco/BYG#1019]
### BYG Version

2.0.0.11

### Terrablender Version

2.0.1.127

### Mod Loader

Forge

### Mod Loader Version

43.1.32

### Bug Severity

Minor

### What happened?

_( already mentioned on Oct 22 and Oct 29 on Discord, but posted here for continuity )_

Placing a forager table near an unemployed villager does not provide them with a forager profession.

### latest.log

n/a

### Did you isolate BYG?

I did not try BYG alone

**Comment by XAgent1990** [comment]
Can confirm

**Comment by YaBoiChips** [comment]
update to fix
