### ISSUE TITLE
Leaves derived from BYGBloomingWitchhazelLeaves are missing attributes

### ISSUE THREAD

**Issue by ChloeDawn** [CorgiTaco/BYG#102]
**Mod version:** [1.0.11](https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go-fabric/files/3063903)

Leaves created using the `BYGBloomingWitchhazelLeaves` property implementation - namely Blue Enchanted Leaves, Green Enchanted Leaves, and Blooming Witch-hazel Leaves - are missing the `suffocates`, `allowsSpawning` and `blocksVision` attribute configurations of other leaves. While the block inherintly does not suffocate (presumably due to `noOcclusion()`, it still blocks vision when the camera is within the blockspace (possible in survival when a mod that disables leaf collision is present), and I suspect spawning will not be functioning correctly either (although I have no tested this).

![Recording of vision being blocked by leaves](https://thumbs.gfycat.com/AgonizingFarflungAsiaticlesserfreshwaterclam-size_restricted.gif)

**Comment by CorgiTaco** [comment]
Has been added and will be available OCT 31 in BYG 1.1
