### ISSUE TITLE
[1.19][Bug]: White Puffball Stew stackable - Eats whole stack

### ISSUE THREAD

**Issue by XAgent1990** [CorgiTaco/BYG#1020]
### BYG Version

2.0.0.13

### Terrablender Version

2.0.1.127

### Mod Loader

Fabric

### Mod Loader Version

0.66.0

### Bug Severity

Minor

### What happened?

White Puffball Stews are stackable.
I would love for this to be the case, but it's unusual behavior for bowl based foods/stews.
In the case that this is intended, if you for example have 10 white puffball stews and try to eat one, the whole slot/stack of stews is consumed and you are left with a single empty bowl.
Either way this is a bug, question is just what is the intended behavior 😄 

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/9979473/latest.log)

### Did you isolate BYG?

I tried BYG alone

**Comment by YaBoiChips** [comment]
puffball stew stacks only to 1 now :(
