### ISSUE TITLE
[1.19][Crash]: Possible problems with cleanup after remove mods with custom villagers

### ISSUE THREAD

**Issue by uhloin** [CorgiTaco/BYG#1021]
### BYG Version

Oh_The_Biomes_You'll_Go-forge-1.19.2-2.0.0.13.jar

### Terrablender Version

TerraBlender-forge-1.19.2-2.0.1.129.jar 

### Mod Loader

Forge

### Mod Loader Version

forge-1.19.2-43.1.52-installer.jar

### What happened?

I have some mods which add villager's professions: BYG, Applied Emergetics 2 and Blue Skies.
If I remove only BYG then no problems, 2 other mods can process it.
But if I keep BYG and remove AE2 then get crush in BYG and if I remove BS then get other crush.
I attached logs for the both cases.

### crash-log

[crash-2022-11-14_17.40.13-fml.txt](https://github.com/AOCAWOL/BYG/files/10003549/crash-2022-11-14_17.40.13-fml.txt)
[crash-2022-11-14_17.42.26-fml.txt](https://github.com/AOCAWOL/BYG/files/10003550/crash-2022-11-14_17.42.26-fml.txt)

### latest.log

-

### Did you isolate BYG?

I did not try BYG alone

**Comment by CorgiTaco** [comment]
You need to reset your config for trades, byg generates the trades file with all known villagers in the registry. This is not an issue with BYG bc the expectation is mods should not be removed.

**Comment by uhloin** [comment]
May be not issue but a weakness because your mod cannot do a thing other mods can do without problem.
Do you listen about other mod requires manually reset some config if OTHER mod changed? If you set such requirement then 99% people just forget about it.

**Comment by CorgiTaco** [comment]
We do this because the config should not have unused data. That is a design decision. All data in these files should be used.

**Comment by uhloin** [comment]
Then it is some flaw in design because crush by design sounds wrong. I do not insist, just think about it and compare your mod with others.
