### ISSUE TITLE
[1.19][Crash]: Game will not load

### ISSUE THREAD

**Issue by DayIsGone** [CorgiTaco/BYG#1022]
### BYG Version

2.0.0.13

### Terrablender Version

2.0.1.128

### Mod Loader

Fabric

### Mod Loader Version

0.14.10

### What happened?

While trying to load the game crashes. I have tried in both Multi Mc and the minecraft launcher. It does not spit out a crash log but the game loads fine when I remove oh the biomes you will go. The file on the crashlog space is what multimc says when the game crashes.

### crash-log

https://gist.github.com/DayIsGone/3a37b3cb3cb739ccf75586a2318fb6a7

### latest.log

https://gist.github.com/DayIsGone/fd550c3c81fac50ffaa7a4ecb7b41459

### Did you isolate BYG?

I tried BYG alone

**Comment by 1oglop1** [comment]
Can confirm the same problem, I tried multiple versions of Terrablender as well. The only fix was to downgrade BYG

There are 2 links to the same version, pointing to a different file

This one is broken: 
```
https://modrinth.com/mod/biomesyougo/version/2.0.0.13-1.19.2
https://cdn.modrinth.com/data/uE1WpIAk/versions/oFcbieSw/Oh_The_Biomes_You%27ll_Go-fabric-1.19.2-2.0.0.13.jar
```

this one works: 
```
https://modrinth.com/mod/biomesyougo/version/2.0.0.13-fabric
https://cdn.modrinth.com/data/uE1WpIAk/versions/B3LkZn0y/Oh_The_Biomes_You%27ll_Go-fabric-1.19.2-2.0.0.13.jar
```

@DayIsGone

**Comment by TheCosmicNebula** [comment]
Can confirm I am having the same issue with the Forge version(s):

1.19.2-2.0.0.13, 1.19.2-2.0.0.11, 1.19.2-2.0.0.9.

**Comment by DayIsGone** [comment]
> https://cdn.modrinth.com/data/uE1WpIAk/versions/B3LkZn0y/Oh_The_Biomes_You%27ll_Go-fabric-1.19.2-2.0.0.13.jar

Can confirm the second link lets the game load. I got the version from curseforge it is apparently broken

**Comment by milkev** [comment]
updating to the latest version of terrablender fixed this issue for me. https://www.curseforge.com/minecraft/mc-mods/terrablender-fabric/files/4095396

**Comment by milkev** [comment]
only sometimes though? ive atleast gotten it to work, but it still crashes sometimes.

**Comment by AlicoCat** [comment]
I'm having this issue too, tried both of the above things and still couldnt get it working. My buddy who has the exact same mod files as me isn't having any issue, so maybe it depends on what computer you have or something?

**Comment by DayIsGone** [comment]
> I'm having this issue too, tried both of the above things and still couldnt get it working. My buddy who has the exact same mod files as me isn't having any issue, so maybe it depends on what computer you have or something?

The way I got the second one to work is I went into the config and deleted the byg files. As soon as I did that it loaded right away for me when I opened the game again

**Comment by AlicoCat** [comment]
> > I'm having this issue too, tried both of the above things and still couldnt get it working. My buddy who has the exact same mod files as me isn't having any issue, so maybe it depends on what computer you have or something?
> 
> The way I got the second one to work is I went into the config and deleted the byg files. As soon as I did that it loaded right away for me when I opened the game again

Oh my god thank you SO much, I've been going nuts trying to get it to work and I didn't think to try that! I've got it working now!

**Comment by TheSinicanEmpire** [comment]
I'm just trying to use 1.19 alone, not 1.19.1 or 1.19.2 just 1.19 and it keeps crashing trying to load up, not sure what to do cause I want this mod in my fabric modpack and it's driving me insane man. I Isolated it and made sure that just that mod is the problem and it is. This thread is exactly what I'm experiencing, though people are giving solutions to 1.19.1 or 1.19.2. When I went to Modrinth and Downloaded it let me open the game up but loading in a world, the mod didn't even work, there was nothing. ;-;

**Comment by CorgiTaco** [comment]
Going by the crash report submitted at the beginning of this issues, seems like you removed mods that were being used in the Trades config, deleting the config and letting it regen fresh should work
