### ISSUE TITLE
[1.19][Bug?]: non-translated ids

### ISSUE THREAD

**Issue by notIkibo** [CorgiTaco/BYG#1025]
### BYG Version

2.0.0.13

### Terrablender Version

2.0.1.13

### Mod Loader

Fabric

### Mod Loader Version

0.66.0

### Bug Severity

Minor

### What happened?

I found this in the config when booting mc. I haven't seen any faulty textures, but I haven't also tested every block yet. Though I haven't seen something like this before

### latest.log

https://paste.gg/p/anonymous/b93a3199c39e42be8cd2f2f8b8c98e3d
relevant part

[latest.log](https://github.com/AOCAWOL/BYG/files/10074503/latest.log)

### Did you isolate BYG?

I did not try BYG alone

**Comment by CorgiTaco** [comment]
I am 95% sure whatever this issue is, it's not BYG at fault because whatever it is, is also blaming Better End. I'd say just ignore it

**Comment by notIkibo** [comment]
Alrighty then, thought should still post this, if there's anything that's potentially causing issues
