### ISSUE TITLE
[1.19][Crash]: 

### ISSUE THREAD

**Issue by JSmurf11** [CorgiTaco/BYG#1026]
### BYG Version

1.19.2-2.0.0.13

### Terrablender Version

1.19.2-2.0.1.130

### Mod Loader

Fabric

### Mod Loader Version

0.14.10-1.19.2

### What happened?

Being in the overworld is fine, but when I created my nether portal and tried to go to the nether it crashes my game. I got the Exit Code: 1

### crash-log

https://gist.github.com/JSmurf11/0488abcb351336e1bceaf50501a81f41

### latest.log

https://gist.github.com/JSmurf11/7887f1c1d9fb1d5e76b6057c9dbc548d

### Did you isolate BYG?

I tried BYG alone

**Comment by CorgiTaco** [comment]
Crash looks like you've ran out of memory, please assign more RAM to MC when playing modded
