### ISSUE TITLE
[1.19][Bug]: Using AmbientSounds5 - Canadian Shield biome acts as if you're always under a tree

### ISSUE THREAD

**Issue by 0DeltaWaves** [CorgiTaco/BYG#1028]
### BYG Version

2.0.0.13

### Terrablender Version

2.0.1.128

### Mod Loader

Forge

### Mod Loader Version

43.1.10

### Bug Severity

Minor

### What happened?

Hello, this is an issue I've been discussing over on AmbientSounds' end, and the cause remains a mystery so I am reporting the problem here in case it is something to do with BYG.

Basically, Ambient Sounds plays different sounds in response to the player's environment. I noticed that in the Canadian Shield biome in particular, the game thinks that the player is always under a tree. This makes it so that the ambient sound of rain is muffled whenever you are in a Canadian Shield biome, as it does when the player is standing under something in normal conditions. In the screenshot below, you can see that even with direct sky access, it detects a tree over the player's head.
![image](https://user-images.githubusercontent.com/82335536/204947827-2fa5952e-5b35-4046-bc7b-3924a81e6bf4.png)
 This happens even when flying above the trees in creative mode.
 
I've tested several other biomes in the same classification, and I haven't found any others that do this. I'm wondering if there's something different about the code for the Canadian Shield that might cause this?

### latest.log

https://paste.ee/p/loXPG

### Did you isolate BYG?

I tried BYG alone

**Comment by CorgiTaco** [comment]
Only thing I can imagijne causing this is there's an invisible block above you or the heightmap is corrupted. I'd suggest filling the entire top of the biome with some random block, then clearing those blocks to fix the heightmap.
