### ISSUE TITLE
[1.19][Bug]: BYG blocks not rendering on servers

### ISSUE THREAD

**Issue by Da-Spud** [CorgiTaco/BYG#1029]
### BYG Version

2.0.0.13

### Terrablender Version

2.0.1.128

### Mod Loader

Forge

### Mod Loader Version

43.1.52

### Bug Severity

Minor

### What happened?

So when a BYG tree grows with a player nearby is dosnt actually render all the BYG blocks (so minecraft vines on white mangrove will all be fine, just the white mangrove logs ect will mostly not render)

World generation in general is fine, tho when using a tree-chopper mod or similar to remove the whole tree some blocks will also stay visually there when there are not, and bug the player when trying to pass through said blocks

I have also made Create contraptions that just move a block left to right, and all blocks are fine except from BYG blocks will have this same render issue when being physically placed back into the world as a solid block

doing /spawn and then going back does render them back in,
doing F3+A to reload visual chunks does NOT fix this,
re-logging to the server also fixes it

https://imgur.com/TkX4jD9 Growing Tree
https://imgur.com/v82jFwY Chopping Tree

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/10128803/latest.log)

### Did you isolate BYG?

I did not try BYG alone

**Comment by YaBoiChips** [comment]
please isolate the mod, this is usually a bug caused by mods like optifine that change the default rendering system
