### ISSUE TITLE
Various blocks missing effective tools

### ISSUE THREAD

**Issue by ChloeDawn** [CorgiTaco/BYG#103]
**Mod version:** [1.0.11](https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go-fabric/files/3063903)

The following blocks are missing shovels as an effective tool

- Meadow Grass
- Meadow Dirt
- Black Sand
- White Sand
- Blue Sand
- Purple Sand
- Nylium Soul Sand

**Comment by CorgiTaco** [comment]
Has been added and will be available OCT 31 in BYG 1.1
