### ISSUE TITLE
[1.18][Feature]: Remove the Biomepedia from being given on new worlds

### ISSUE THREAD

**Issue by xhatz** [CorgiTaco/BYG#1030]
### BYG Version

1.4.7

### Terrablender Version

1.2.0.126

### Mod Loader

Forge

### Mod Loader Version

Latest for that version

### Bug Severity

Minor

### What happened?

Hello guys, ladies and dawgs, I was just wondering if a simple config option to remove the book from being given to every new player was planned, please? I can't find it anywhere in the configs, so I guess it's not in the mod yet quite surprisingly ^^'

### latest.log

You don't need that!

### Did you isolate BYG?

I did not try BYG alone

**Comment by thimblebird** [comment]
@xhatz see https://github.com/AOCAWOL/BYG/issues/1017#issuecomment-1310786346
