### ISSUE TITLE
[1.19.2][Crash]: Aternos server crashes when I try to load BYG in 1.19.2

### ISSUE THREAD

**Issue by Test2772** [CorgiTaco/BYG#1032]
### BYG Version

2.0.0.13

### Terrablender Version

2.0.1.130

### Mod Loader

Fabric

### Mod Loader Version

0.14.11

### What happened?

Tried multiple times to load BYG in a modpack using aternos server, but it gives a no data fixer registered error for boat and chest_boat entities, server promptly crashes before even starting

So I tried with a new server but it gave the same error and the server crashed

### crash-log

https://mclo.gs/1cXVL3L

### latest.log

https://mclo.gs/1cXVL3L

### Did you isolate BYG?

I tried BYG alone

**Comment by YaBoiChips** [comment]
you need geckolib installed with the version of BYG you are running
