### ISSUE TITLE
[1.18][Bug/Question]: Rocky Stone doesn't spawn in underground

### ISSUE THREAD

**Issue by Aleon4201** [CorgiTaco/BYG#1035]
### BYG Version

1.4.7

### Terrablender Version

1.2.0.126

### Mod Loader

Forge

### Mod Loader Version

40.1.86

### Bug Severity

Minor

### What happened?

Where does Rocky Stone spawn now?
I had played this mod on MC 1.16.5 too, it spawned at anywhere in underground of overworld same as Soap Stone.
However, only Soap Stone spawns now. I mined chunks of blocks until Y=-54.

On only BYG and TerraBlender environment, I run fill command several times, but no blocks were filled.
![2022-12-14_01 00 00](https://user-images.githubusercontent.com/104340803/207382904-c37082bd-39a5-40e1-b140-4c4d4afbeb97.png)

P.S. In my opinion, Soap Stone veins are too many. But I don't know where's its config although I saw config/byg folder.

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/10219806/latest.log)

### Did you isolate BYG?

I tried BYG alone

**Comment by YaBoiChips** [comment]
rocky stone does not spawn underground it spawns in boulders on mountain like biomes

**Comment by Aleon4201** [comment]
Oh, many rocks are on the mountains!!
I didn't know that, thank you very much!
