### ISSUE TITLE
[1.18][Bug]: When I opened the Curios interface, the BYG Biomepedia button disappeared.

### ISSUE THREAD

**Issue by Ginsway** [CorgiTaco/BYG#1036]
### BYG Version

1.4

### Terrablender Version

1.2.0.126

### Mod Loader

Forge

### Mod Loader Version

40.1.86

### Bug Severity

Minor

### What happened?

![image](https://user-images.githubusercontent.com/106016532/208239165-cccd95bb-73eb-4e7e-ab41-2ae6e0814ffe.png)
![image](https://user-images.githubusercontent.com/106016532/208239171-e63a8691-05b4-4664-b221-d97da79183ce.png)

### latest.log

[minecraft-exported-logs-2022-12-17T19-11-53.log](https://github.com/AOCAWOL/BYG/files/10251553/minecraft-exported-logs-2022-12-17T19-11-53.log)

### Did you isolate BYG?

I tried BYG alone

**Comment by CorgiTaco** [comment]
This is bound to happen when numerous mods are involved. there is unfortunately no way to guarantee every mod combo will work.
