### ISSUE TITLE
[1.18][Bug]: 

### ISSUE THREAD

**Issue by ExoSteall** [CorgiTaco/BYG#1038]
### BYG Version

1.4.4

### Terrablender Version

1.1.0.101

### Mod Loader

Forge

### Mod Loader Version

40.1.73

### Bug Severity

Major

### What happened?

Bonjour,
J'aimerais savoir si il est possible de supprimer les biomes du nether, mon jeu crash une fois sur deux et j'ai très peu de fps.
Serait-il possible de les supprimer de la génération du monde, et si oui comment faire ?

Cordialement,
ExoSteall

### latest.log

.

### Did you isolate BYG?

I tried BYG alone

**Comment by CorgiTaco** [comment]
You can disable nether biomes in the config. If an existing world follow the steps here: https://github.com/AOCAWOL/BYG/wiki/Nether-&-End-Biomes-FAQ
