### ISSUE TITLE
[1.19/1.18][Bug]: Modded shears won't correctly break leaves and bushes

### ISSUE THREAD

**Issue by JaisDK** [CorgiTaco/BYG#1043]
### BYG Version

2.0.0.13

### Terrablender Version

2.0.1.128

### Mod Loader

Forge

### Mod Loader Version

43.x

### Bug Severity

Minor

### What happened?

Modded shears > break BYG leaves -> drops nothing

advised to change the loot tables to match the changes Forge has for the vanilla leaves loot tables

### latest.log

no

### Did you isolate BYG?

I tried BYG alone

**Comment by JT122406** [comment]
What Modded Shears item are you referring to as BYG doesn't add any shears and you said you tested with BYG alone.  With Vanilla shears I am unable to reproduce the issue.

**Comment by JaisDK** [comment]
My on shears, but the point was for you to support any modded shears in the shears item tag. Take a look at how forge modifies the leaves loot tables for vanilla
https://github.com/MinecraftForge/MinecraftForge/blob/1.19.x/src/generated/resources/data/minecraft/loot_tables/blocks/birch_leaves.json
instead of the `match_tool` condition you should use the `shears_dig` action
https://github.com/AOCAWOL/BYG/blob/1.19.X/Common/src/generated/resources/data/byg/loot_tables/blocks/fir_leaves.json#L17
