### ISSUE TITLE
[1.19][Bug]: Some saplings not working

### ISSUE THREAD

**Issue by Crows-Parliament** [CorgiTaco/BYG#1046]
### BYG Version

2.0.0.13

### Terrablender Version

2.0.1.128

### Mod Loader

Forge

### Mod Loader Version

43.2.0

### Bug Severity

Minor

### What happened?

Aspen, Jacaranda, Indigo Jacaranda, Rainbow Eucalyptus(1*1), Zelkova and Brown Zelkova saplings cannot be bonemealed and possibly cannot grow (untested)

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/10271915/latest.log)

### Did you isolate BYG?

I tried BYG alone

**Comment by CorgiTaco** [comment]
I can confirm that on the latest version here on github, bonemealing does indeed work: https://i.imgur.com/2ZnkQfS.mp4
