### ISSUE TITLE
[1.19][Bug]: 

### ISSUE THREAD

**Issue by Halibut111** [CorgiTaco/BYG#1047]
### BYG Version

2.0.0.13

### Terrablender Version

2.0.1.136

### Mod Loader

Forge

### Mod Loader Version

43.1.42

### Bug Severity

Minor

### What happened?

none of the end biomes have any tree structures.
![image](https://user-images.githubusercontent.com/92272059/208959839-2d74773d-ce0f-4d8f-9541-476da80c4b0e.png)

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/10279647/latest.log)

### Did you isolate BYG?

I tried BYG alone

**Comment by Halibut111** [comment]
screenshots are coming out empty for some reason.

**Comment by Halibut111** [comment]
![image](https://user-images.githubusercontent.com/92272059/208961040-21bdd7e0-4256-4e02-adcd-bd8171834784.png)

**Comment by Halibut111** [comment]
![image](https://user-images.githubusercontent.com/92272059/208961180-a9d5f7de-0cf1-4c40-a29d-6149253f8894.png)

**Comment by CorgiTaco** [comment]
I cant recreate this issue myself, please join the discord so I can assist you further.
