### ISSUE TITLE
[1.18] [Bug]: Puffball Stew consumes an entire stack at once

### ISSUE THREAD

**Issue by vizthex123** [CorgiTaco/BYG#1049]
### BYG Version

1.4.7

### Terrablender Version

1.2.0.126

### Mod Loader

Forge

### Mod Loader Version

40.1.92

### Bug Severity

Minor

### What happened?

One of my players reported an issue where White Puffball Stew consumes an entire stack when eaten, instead of just a single item.2

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/10282269/latest.log)

### Did you isolate BYG?

I did not try BYG alone

**Comment by Angelyques** [comment]
That happened to me. As I was crafting the stew it stacked itself up to 64. Had the whole stack in my hotbar. When I ate one I ended up with a single bowl in that slot and no sign of the rest of the stew (or bowls for that matter)

**Comment by CorgiTaco** [comment]
It shouldnt be possible for the stew to stack? Not sure how yall did it but i cant get it to stack at all on the latest dev branch. 
Going to mark it as closed: 
https://user-images.githubusercontent.com/66983020/212503431-6e87c8c9-66e7-4f8e-b90c-1f92c3738b65.mp4
