### ISSUE TITLE
[1.19][Crash]: Crashes on load

### ISSUE THREAD

**Issue by SleepyCatten** [CorgiTaco/BYG#1053]
### BYG Version

2.0.0.13

### Terrablender Version

2.1.0.133

### Mod Loader

Fabric

### Mod Loader Version

0.14.12

### What happened?

Crashes on startup

### crash-log

https://gist.github.com/SleepyCatten/b4a75ac584ec02fe01e9551d13ec07fc

### latest.log

https://gist.github.com/SleepyCatten/b4a75ac584ec02fe01e9551d13ec07fc

### Did you isolate BYG?

I tried BYG alone

**Comment by achhandrian** [comment]
Seeing that to, tried different fabric mod loader version, different fabric api versions, different terrablender versions.
Minecraft simply closes for me without any error at all in 1.19.2 unable to get it running.

**Comment by SyntaxEG** [comment]
Experiencing the same issue.

### Versions
- MultiMC 0.6.16-3430
  - LWJGL 3.3.1
  - Minecraft 1.19.2
  - Intermediary Mappings 1.19.2
  - Fabric Loader 0.14.12
- Mods
  - Fabric API 0.71.0+1.19.2
  - Oh The Biomes You'll Go 2.0.0.13
  - TerraBlender 2.0.1.136

### My crash logs
MultiMC console:
https://paste.ee/p/t1CjA

logs/latest.log
https://paste.ee/p/DO4Wv

crash-reports/crash-2023-01-02-23.24.41-client.txt
https://paste.ee/p/aA2oc

**Comment by BHPirkle** [comment]
I had this issue as well, although adding GeckoLib along with all the other required mods seems to have fixed it.

**Comment by SyntaxEG** [comment]
Thanks @BHPirkle. I installed [this version](https://modrinth.com/mod/geckolib/version/3.1.38-fabric) of GeckoLib and everything worked.

GeckoLib is not listed as a dependency in the [readme](https://github.com/AOCAWOL/BYG/blob/1.19.X/README.md#dependencies)
