### ISSUE TITLE
[1.19][Bug]: Maple Biome leaf textures aren't loading in.  

### ISSUE THREAD

**Issue by bromodatchi** [CorgiTaco/BYG#1054]
### BYG Version

19.2-2.0.0.13

### Terrablender Version

1.19.2-2.0.1.136

### Mod Loader

Fabric

### Mod Loader Version

0.14.10

### Bug Severity

Minor

### What happened?

Maple textures are loading in as pink & black checkered boxes.  I've tried reloading my modpacks, the server, etc.

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/10304692/latest.log)

### Did you isolate BYG?

I did not try BYG alone

**Comment by CorgiTaco** [comment]
They work for me: 
![image](https://user-images.githubusercontent.com/66983020/212502263-f4e22529-855d-4735-8eb5-714612bbc570.png)
