### ISSUE TITLE
[1.19][Bug]: Withering Oak Logs are missing the #byg:logs item tag

### ISSUE THREAD

**Issue by ChristopherHaws** [CorgiTaco/BYG#1055]
### BYG Version

2.0.0.13

### Terrablender Version

2.0.1.136

### Mod Loader

Fabric

### Mod Loader Version

0.14.11

### Bug Severity

Minor

### What happened?

The `Withering Oak Log` blocks are missing the `byg:logs` item tag which the other logs contain.

### latest.log

N/A

### Did you isolate BYG?

I tried BYG alone

**Comment by CorgiTaco** [comment]
We don't add it to this tag bc the log would be flammable and due to it being in the nether that's not a good idea.
