### ISSUE TITLE
[1.16][Bug]: World Generation leaves weird waterlogged fences, walls etc around the world.

### ISSUE THREAD

**Issue by XCharmyX** [CorgiTaco/BYG#1058]
### BYG Version

1.3.5

### Mod Loader

Forge

### Mod Loader Version

36.2.39

### Bug Severity

Major

### What happened?

When generating the world, terrain will sometimes, more often than not, generate ore-structural veins of waterlogged walls, fences or logs, and sometimes trees will be replaced by walls.
Which breaks the world generation.

![2023-01-02_17 39 27](https://user-images.githubusercontent.com/60596287/210409647-e9358c0b-7583-4c87-9b3d-111386473cd1.png)
![2023-01-02_17 39 40](https://user-images.githubusercontent.com/60596287/210409650-a33e1fe0-105a-44e8-ba9a-590ca7dd6854.png)
![2023-01-02_17 42 04](https://user-images.githubusercontent.com/60596287/210409653-dfc7ed08-715e-41b3-99e6-1c3ead716166.png)
![2023-01-03_18 14 33](https://user-images.githubusercontent.com/60596287/210409654-41ca4658-464b-4525-86cd-476e6e3cd29b.png)

### latest.log

No latest log with anything Byg related found

### Did you isolate BYG?

I tried BYG alone

**Comment by CorgiTaco** [comment]
Looks to me like a registry mismatch but definitely not BYG at fault. Make sure mod versions are the same on the server as they are on your client.

**Comment by P3rf3ctXZer0** [comment]
So I have this issue and years of testing experience. I know its not a reg issue I think its the way BYG is assigning block ids. Ironically this issue only can occurs on a dedicated server and not on a SP world. My issue only started after adding BYG Macaw addons. The only difference is I am using BYG 1.3.6 not 1.3.5

I am willing to help debug @CorgiTaco as I know you work hard on your mods. Just inform me of what you would like me to try.
