### ISSUE TITLE
[1.19][Suggestion]: Sack of Berries Blocks

### ISSUE THREAD

**Issue by Cicopath** [CorgiTaco/BYG#1059]
### BYG Version

N/A

### Terrablender Version

N/A

### Mod Loader

Forge

### Mod Loader Version

N/A

### Bug Severity

Minor

### What happened?

I would have made this suggestion in the Discord server, but unfortunately, I do not have a phone number linked to my account, nor will I ever.

Anyway, with modern food mods, like Farmer's Delight and Thermal Cultivation, many food blocks have been added, including potatoes, golden apples, and such. Furthermore, Quark adds "Sack" blocks for Sweet Berries and Glow Berries, and Windswept for Wild Berries.

Why not do the same for all the berries in OTBYG? Just imagine all the sacks of blueberries you could have around your house; mmm...!

### latest.log

N/A

### Did you isolate BYG?

I tried BYG alone

**Comment by AOCAWOL** [comment]
Hi! thank you for the suggestion I will look into it!!

**Comment by CorgiTaco** [comment]
Moved to our discussion tab, issue tracker is now for issues only!

https://github.com/AOCAWOL/BYG/discussions/1178
