### ISSUE TITLE
[1.19][Bug]: Missing Nether Plants

### ISSUE THREAD

**Issue by SpiffyDragon13** [CorgiTaco/BYG#1061]
### BYG Version

Oh_The_Biomes_You'll_Go-fabric-1.19.2-2.0.0.13

### Terrablender Version

TerraBlender-fabric-1.19.2-2.0.1.127

### Mod Loader

Fabric

### Mod Loader Version

fabric-api-0.60.0+1.19.2

### Bug Severity

Minor

### What happened?

Explored the Nether Biomes in several generated worlds and cannot find the Lament Vines in the Weeping Mire, the Wailing Vines & Wailing Bell Blossom in the Wailing Garth, and the Weeping Roots in the Glowstone Gardens.

### latest.log

[2023-01-10-3.log.gz](https://github.com/AOCAWOL/BYG/files/10383282/2023-01-10-3.log.gz)

### Did you isolate BYG?

I did not try BYG alone

**Comment by Neorah619** [comment]
I had a similar issues but with the forge version where the end biomes are not showing up at all. All i see is the ground blocks of each biomes but never the trees, mushrooms or any structures of those biomes.

**Comment by NanoAi** [comment]
Same here on Forge structures don't seem to generate at all in The End on 1.19.2. Settings default world size, running Quark as well.
