### ISSUE TITLE
[1.19][Bug]: No data fixer registered for ...

### ISSUE THREAD

**Issue by TobiPeterG** [CorgiTaco/BYG#1063]
### BYG Version

2.0.0.13

### Terrablender Version

2.0.1.136

### Mod Loader

Forge

### Mod Loader Version

0.17.8

### Bug Severity

Major

### What happened?

When starting Minecraft, I get the following erros in the log:
[18:28:55] [Render thread/ERROR]: No data fixer registered for byg:boat
[18:28:55] [Render thread/ERROR]: No data fixer registered for byg:chest_boat

### latest.log

https://gist.github.com/TobiPeterG/a73796df5848de4dcc37623358d2deb1

### Did you isolate BYG?

I did not try BYG alone

**Comment by CorgiTaco** [comment]
This isnt an issue, just MC complaining we dont have datafixerupper for our mobs
