### ISSUE TITLE
[1.18][Bug]: UI problem with other mods (Nutritional Balance AND/OR Diet)

### ISSUE THREAD

**Issue by Hudumannaia** [CorgiTaco/BYG#1064]
### BYG Version

1.4

### Terrablender Version

1.2.0.126

### Mod Loader

Forge

### Mod Loader Version

40.2.0

### Bug Severity

Minor

### What happened?

BYG and some other (Nutrition) mods make UI conflicts. I tryed with "Diet (Forge)" and "Nutritional Balance". Both worked, but UI button cant reach well. Ugly and annoying.

### latest.log

Sorry but irrelevant, instead i show an image from the issue: https://imgbox.com/Ch7gqYwf

### Did you isolate BYG?

I did not try BYG alone

**Comment by CorgiTaco** [comment]
Use the `config/byg/client/biomepedia_inventory.json5` file to edit the position of the button or to disable it altogether
