### ISSUE TITLE
[1.19][Bug]: Chorus Fruit

### ISSUE THREAD

**Issue by ghost** [CorgiTaco/BYG#1065]
### BYG Version

Oh_The_Biomes_You'll_Go-forge-1.19.2-2.0.0.13

### Terrablender Version

TerraBlender-forge-1.19.2-2.0.1.136

### Mod Loader

Forge

### Mod Loader Version

forge43.2.3

### Bug Severity

Major

### What happened?

(The End) Chorus Fruit was not found.

### latest.log

no

### Did you isolate BYG?

I tried BYG alone

**Comment by ghost** [comment]
They should be generated in byg

**Comment by CorgiTaco** [comment]
Try Terrablender 2.0.1.130
