### ISSUE TITLE
[1.18][Bug]: Compatibility with Quark End features

### ISSUE THREAD

**Issue by JaboyKoral** [CorgiTaco/BYG#1066]
### BYG Version

1.18.2-1.4.7

### Terrablender Version

1.18.2-1.2.0.126

### Mod Loader

Forge

### Mod Loader Version

40.2.0

### Bug Severity

Minor

### What happened?

When both Quark and BYG are installed, Quark's end features (myalite deposits and chorus vegetation) do not generate in the vanilla End biomes. My best guess is something with the way BYG takes over End generation after Quark's features are registered 'resets' the vanilla biomes?

Is this something that can be fixed on BYG's side? Or is there information I can take back to the Quark team like different biome tags that would fix this?

This also occurs on 1.19.2 with the most recent versions, but I only have a log from 1.18.2.

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/10450236/latest.log)

### Did you isolate BYG?

I did not try BYG alone

**Comment by epilimic** [comment]
This is also happening to us in the ATM8 modpack mc version 1.19.2

**Comment by vizthex123** [comment]
same issue here in my 1.18.2 modpack. Seems like the only fix is to disable one of the mod's end stuff.
