### ISSUE TITLE
[1.19][Bug]: Compatibility issue with Citadel

### ISSUE THREAD

**Issue by aAndrew3030** [CorgiTaco/BYG#1067]
### Bug Severity

Major

### What happened?

Not sure if BYG is part of this issue, or if it is just a issue with Terrablender and Citadel, but it has been a issue for some time (not sure what versions it started). I have to routinely go in and manually fix this or my world stops generating new chunks and corrupts

https://github.com/Glitchfiend/TerraBlender/issues/107

https://github.com/AlexModGuy/Citadel/issues/101

https://github.com/AlexModGuy/AlexsMobs/issues/1475

**Comment by CorgiTaco** [comment]
Reading through the linked issues, seems to be an issue that stems from Citadel. If it wasn't please feel free to comment on this issue or create a new one!
