### ISSUE TITLE
[1.19][Bug]: Display error

### ISSUE THREAD

**Issue by ghost** [CorgiTaco/BYG#1068]
### BYG Version

Oh_The_Biomes_You'll_Go-forge-1.19.2-2.0.0.13

### Terrablender Version

TerraBlender-forge-1.19.2-2.0.1.136

### Mod Loader

Forge

### Mod Loader Version

43.2.3

### Bug Severity

Minor

### What happened?

![QQ截图20230121201815](https://user-images.githubusercontent.com/83486178/213866631-35060697-b4d5-41a5-b1ec-db663f8772d9.png)

### latest.log

no

### Did you isolate BYG?

I did not try BYG alone

**Comment by CorgiTaco** [comment]
Known and fixed internally
