### ISSUE TITLE
Embur Lily Cannot Be Placed Back On Lava[1.19][Bug]: 

### ISSUE THREAD

**Issue by SpiffyDragon13** [CorgiTaco/BYG#1069]
### BYG Version

Oh_The_Biomes_You'll_Go-fabric-1.19.2-2.0.0.13

### Terrablender Version

TerraBlender-fabric-1.19.2-2.0.1.127

### Mod Loader

Fabric

### Mod Loader Version

fabric-api-0.60.0+1.19.2

### Bug Severity

Minor

### What happened?

The Embur Lily block can be harvested but not placed back onto lava.

### latest.log

[2023-01-21-2.log.gz](https://github.com/AOCAWOL/BYG/files/10474212/2023-01-21-2.log.gz)

### Did you isolate BYG?

I did not try BYG alone

**Comment by YaBoiChips** [comment]
will be fixed in next update :)
