### ISSUE TITLE
[1.19][Bug]: End and Nether biomes not showing

### ISSUE THREAD

**Issue by BYgokK** [CorgiTaco/BYG#1070]
### BYG Version

2.0.0.13

### Terrablender Version

2.0.1.136

### Mod Loader

Forge

### Mod Loader Version

43.2.3

### Bug Severity

Major

### What happened?

Biomes in Nether and End are not rendering or showing up. It only shows the grass blocks and in F3 the custom biome name but, all the features of the mod are not showing up. No trees, no foliage and so. Visual information of the issue in the screenshots. (this happens in every world I load)

![aaa](https://user-images.githubusercontent.com/123311752/213922616-32f170ce-c123-4e81-b5fc-3b4b717a6e52.png)
![bbb](https://user-images.githubusercontent.com/123311752/213922680-182797a5-c254-4de1-b510-d5f8047a5799.png)
![ccc](https://user-images.githubusercontent.com/123311752/213922716-1d4d6405-0c3c-4e1e-81f3-a433bb2c3302.png)
![ddd](https://user-images.githubusercontent.com/123311752/213922731-0c3b8323-2a90-4f1a-81dc-334706902aed.png)

### latest.log

[debug-5.log](https://github.com/AOCAWOL/BYG/files/10474701/debug-5.log)

### Did you isolate BYG?

I tried BYG alone

**Comment by CorgiTaco** [comment]
Try terrablender 2.0.1.130
