### ISSUE TITLE
[1.19][Crash]: Crashes on loading

### ISSUE THREAD

**Issue by otternerd48** [CorgiTaco/BYG#1073]
### BYG Version

2.0.0.1.3

### Terrablender Version

2.0.1.136

### Mod Loader

Forge

### Mod Loader Version

43.2.3

### What happened?

I click play, and it loads as normal but instead of the main menu, it gives me an error page.

### crash-log

https://gist.github.com/otternerd48/b032ff279026c5c7555fdb167fba5199

### latest.log

https://gist.github.com/otternerd48/dcb6fbb3a810bf1bff0ed78725c41610

### Did you isolate BYG?

I tried BYG alone

**Comment by CorgiTaco** [comment]
delete configs and try again
