### ISSUE TITLE
[1.18][1.19][Bug]: Brimstone nether ores use wrong texture

### ISSUE THREAD

**Issue by lilium-orientalis** [CorgiTaco/BYG#1074]
### BYG Version

1.4

### Terrablender Version

1.2.0.126

### Mod Loader

Forge

### Mod Loader Version

40.2.0

### Bug Severity

Minor

### What happened?

Brimstone Nether Gold Ore and Brimstone Nether Quartz Ore use what I assume are outdated textures. They use `brimstone_nether_gold_ore` and `brimstone_nether_quartz_ore`, respectively, when the textures `brimstone_gold_ore` and `brimstone_quartz_ore` more closely match the Brimstone texture. 1.19 branch also appears to have this issue. Attached is a resource pack that uses the correct texture files. I'll get a quick PR made for this.

Edit: PRs at #1075 and #1076 

[brimstonefix.zip](https://github.com/AOCAWOL/BYG/files/10515023/brimstonefix.zip)

### latest.log

Log is irrelevant, see attached resource pack.

### Did you isolate BYG?

I did not try BYG alone

**Comment by CorgiTaco** [comment]
Fixed in the linked PRs
