### ISSUE TITLE
[1.18][Bug]: crash 

### ISSUE THREAD

**Issue by jochemoco** [CorgiTaco/BYG#1078]
### BYG Version

1.4.2

### Terrablender Version

1.2.0.126

### Mod Loader

Forge

### Mod Loader Version

40.2.0

### Bug Severity

Major

### What happened?

When I go to enter the game it crashes because of the mod

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/10539937/latest.log)

### Did you isolate BYG?

I tried BYG alone

**Comment by CorgiTaco** [comment]
Delete your configs and try again

**Comment by santiagoyoan** [comment]
it didnt work to me
