### ISSUE TITLE
[1.19][Crash]: 

### ISSUE THREAD

**Issue by OtterVaun** [CorgiTaco/BYG#1079]
### BYG Version

2.0.0.13

### Terrablender Version

2.0.1.128

### Mod Loader

Forge

### Mod Loader Version

43.2.4

### What happened?

Attempting to create a mod pack, and byg keeps crashing with villager errors. currently turned off while i troubleshoot the other mods as well.

### crash-log

[crash-2023-01-30_18.45.42-fml.txt](https://github.com/AOCAWOL/BYG/files/10541975/crash-2023-01-30_18.45.42-fml.txt)

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/10541960/latest.log)

### Did you isolate BYG?

I tried BYG alone

**Comment by CorgiTaco** [comment]
Delete configs and try again
