### ISSUE TITLE
[1.19][Crash]: Crash when generating new world

### ISSUE THREAD

**Issue by ChromaPIE** [CorgiTaco/BYG#1080]
### BYG Version

2.0.0.13

### Terrablender Version

2.0.1.136.

### Mod Loader

Fabric

### Mod Loader Version

0.14.13

### What happened?

Described as title

### crash-log

https://hastebin.com/share/ohebiruciy.yaml

### latest.log

https://hastebin.com/share/uwinicenus.makefile

### Did you isolate BYG?

I did not try BYG alone

**Comment by YaBoiChips** [comment]
delete your config and try again

**Comment by CorgiTaco** [comment]
Try w/ terrablender .130
