### ISSUE TITLE
[1.19][Fabric][Bug]: Sythian Stalk Becomes Sythian Shroom, Not Sapling

### ISSUE THREAD

**Issue by FlashOfAsh** [CorgiTaco/BYG#1081]
### BYG Version

2.0.0.7

### Terrablender Version

2.0.0.120

### Mod Loader

Fabric

### Mod Loader Version

0.14.13

### Bug Severity

Minor

### What happened?

Title Says It All tbh

when i try and place a sythian stalk block it ends up becoming a sythian shroom, when it should be a sythian sapling

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/10563901/latest.log)

### Did you isolate BYG?

I tried BYG alone

**Comment by AOCAWOL** [comment]
Unfortunately in-game we have not been able to reproduce this bug, when placing sythian stalk a sapling will appear and function normally. I am closing this for now and when our newest update launches, please try that build and let me know if the bug is still happening!
