### ISSUE TITLE
[1.19][Bug]: LevelBiomeTrackerPacket way too big

### ISSUE THREAD

**Issue by Fr0zka** [CorgiTaco/BYG#1082]
### BYG Version

2.0.0.13

### Terrablender Version

2.0.1.136

### Mod Loader

Forge

### Mod Loader Version

43.2.3

### Bug Severity

Major

### What happened?

I pretty much added mods that added bunch of biomes until i had this error reported with the help of connectivity :

_

> [02:50:25] [Server thread/WARN] [co.co.Connectivity/]: Trying to send too large packet LevelBiomeTrackerPacket with size: 1186026 bytes
> [02:50:25] [Server thread/ERROR] [minecraft/ServerLoginPacketListenerImpl]: Couldn't place player in world
> java.lang.IllegalArgumentException: Payload may not be larger than 1048576 bytes
>         at net.minecraft.network.protocol.game.ClientboundCustomPayloadPacket.<init>(ClientboundCustomPayloadPacket.java:35) ~[server-1.19.2-20220805.130853-srg.jar%23717!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}

_

in hope it can be fixed, or i'll just have to reduce how much biomes i want to add ahaha

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/10670838/latest.log)

### Did you isolate BYG?

I did not try BYG alone

**Comment by Fr0zka** [comment]
Is this something y'all planning to change or fix ? (but i think that's working as intended for you)
Or should i just reduce my expectation and remove BYG/Mods that adds too much biome on top of BYG ? thanks ^^

**Comment by CorgiTaco** [comment]
I'll see about splitting the packet

**Comment by Fr0zka** [comment]
Oooh, it was quick o: thanks a lot for the answer :p and sorry for that aha i'd gladly try to do it myself but i know nothing about java x: 

I let this issue open until fix ? ^^

**Comment by Fr0zka** [comment]
Okay got the beta release on curseforge and well... i guess the original issue might be fixed but.. all the previous working generation mod (like terralith, william weather and stuff..) BYG don't want them around aha, at least for me

`java.lang.IllegalStateException: Feature order cycle found, involved sources: [Reference{ResourceKey[minecraft:worldgen/biome / terralith:arid_highlands]=net.minecraft.world.level.biome.Biome@7c61e02e}, Reference{ResourceKey[minecraft:worldgen/biome / byg:maple_taiga]=net.minecraft.world.level.biome.Biome@719c2dbe}, Reference{ResourceKey[minecraft:worldgen/biome / byg:coniferous_forest]=net.minecraft.world.level.biome.Biome@5d5f4050}]`

its all gone without BYG obviously, should i wait for a new terrablender version (i think that's what used to make it more compatible or something)

[crash-2023-03-02_02.47.03-server.txt](https://github.com/AOCAWOL/BYG/files/10866909/crash-2023-03-02_02.47.03-server.txt)

**Comment by CorgiTaco** [comment]
Should be fixed in latest release. Was fixed here: https://github.com/AOCAWOL/BYG/commit/3c0a50d477b7e668b47a8fda6b1562d69c941a24
