### ISSUE TITLE
[1.18][Bug]: BYG causing massive worldgen lag

### ISSUE THREAD

**Issue by Catomax262** [CorgiTaco/BYG#1084]
### BYG Version

1.4.7

### Terrablender Version

1.2.0.126

### Mod Loader

Forge

### Mod Loader Version

40.2.0

### Bug Severity

Major

### What happened?

Whenever BYG is installed, it causes a tremendous amount of worldgen lag. It only happens when i install BYG.

### latest.log

-Latest log
https://gist.github.com/Catomax262/570855f3ba4063ab10bf8c648a551357
-Debug log
https://gist.github.com/Catomax262/cae6380eb72b7366184eaa3fff83c2d2

### Did you isolate BYG?

I did not try BYG alone

**Comment by CorgiTaco** [comment]
I would recommend pregenning in that case. BYG should not affect server-side performance once a world is generated. It can effect client-side FPS though since many of the biomes are shady.
