### ISSUE TITLE
[1.19][Bug]: Issue with sues shaders, some blocks will appear as water.

### ISSUE THREAD

**Issue by CreativeName13** [CorgiTaco/BYG#1085]
### BYG Version

2.0.0.13

### Terrablender Version

2.0.1.136

### Mod Loader

Fabric

### Mod Loader Version

0.73.2

### Bug Severity

Minor

### What happened?

When using sues shaders, specifically E12, HRR 2.1 and HRR 3, some blocks appear as water. Seus renewed has a similar issue except blocks appear as transparent but the colors can still be seen. 
The blocks I have found and not been able to fix are the aspen, skyris and maple doors and trapdoors. 
The blocks I have managed to fix are the therium glass block and pane, which I fixed by adding to the shaders' block.properties file, adding these 2 blocks as stained glass windows.
![2023-01-23_21 18 34](https://user-images.githubusercontent.com/125607071/219486011-4286eabb-81ed-423f-955d-28fec4b32949.png)
![2023-01-23_21 19 25](https://user-images.githubusercontent.com/125607071/219486090-9507e421-6a83-47bc-bac7-601ba7b08218.png)

The images show that I have other mods installed, but I have also tried without any other mods and the issue still persisted.

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/10760803/latest.log)

### Did you isolate BYG?

I tried BYG alone

**Comment by JT122406** [comment]
This seems like something more on the shaders side and not us from a dev side
