### ISSUE TITLE
[1.19][Bug]: Quilt, doesn't generate biomes in The End/The Nether if you dont restart the game

### ISSUE THREAD

**Issue by nebulazorua** [CorgiTaco/BYG#1086]
### BYG Version

Fabric

### Terrablender Version

Fabric

### Mod Loader

Quilt

### Mod Loader Version

0.17.11

### Bug Severity

Major

### What happened?

If you make a new world, biomes won't generate in other dimensions properly until you restart the game, then they will generate as normal. In The Nether, they will all generate as Nether Wastes, and in The End they'll generate with the correct grass, but without any decoration.
Once you restart the game, before or after going into a dimension, both dimensions will generate their biomes just fine. 

I am using Quilt Loader 0.17.11, QFAPI 5.0.0-beta.28 QSL-4.0.0-beta.29 ("qfapi-4.0.0-beta.28_qsl-3.0.0-beta.29_fapi-0.73.2_mc-1.19.2.jar"), Terrablender 2.0.1.136 ("TerraBlender-fabric-1.19.2-2.0.1.136.jar") and BYG 2.0.0.13 ("Oh_The_Biomes_You'll_Go-fabric-1.19.2-2.0.0.13.jar")

Broked Warped Desert:
![image](https://user-images.githubusercontent.com/12458328/219615171-eb1cfb75-60a0-4a3c-91b0-bfc0c7110bb7.png)

Half-Broken Ember Bog (Half of it was generated before restarting the game, rest of it was generated after)
![image](https://user-images.githubusercontent.com/12458328/219615424-441146b9-bb90-4047-b607-6a8811e6c0ad.png)

Same with this quartz desert
![image](https://user-images.githubusercontent.com/12458328/219615625-6afff349-25e0-42c4-850a-79669176834b.png)

Broken shulkren forest
![image](https://user-images.githubusercontent.com/12458328/219616997-973754d7-b145-44fe-bd33-4b86cdcbe9f9.png)

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/10765672/latest.log)

### Did you isolate BYG?

I tried BYG alone

**Comment by CorgiTaco** [comment]
Try terrablender .130

**Comment by nebulazorua** [comment]
> Try terrablender .130

Nope, here's a weeping mire
![image](https://user-images.githubusercontent.com/12458328/219621981-30225a0d-d674-40e5-9b97-92856de8b1bf.png)

![image](https://user-images.githubusercontent.com/12458328/219621905-0f2abe92-d996-4b16-a557-9eebd5e41d08.png)


Here is my latest.log:

[latest.log](https://github.com/AOCAWOL/BYG/files/10765855/latest.log)

**Comment by CorgiTaco** [comment]
No idea then, if quilt broke support somehow. You're out of luck for the time being
