### ISSUE TITLE
[1.19][Crash]: Payload may not be larger than 1048576 bytes

### ISSUE THREAD

**Issue by evhub** [CorgiTaco/BYG#1089]
### BYG Version

2.0.0.13

### Terrablender Version

2.0.1.128

### Mod Loader

Forge

### Mod Loader Version

43.2.3

### What happened?

Dedicated server crash occurs occasionally when a player attempts to enter a new RFToolsDimensions dimension. Previously reported at https://github.com/McJtyMods/RFToolsDimensions/issues/434, but the RFToolsDimensions author indicated it was likely a Oh the Biomes You'll Go issue instead.

### crash-log

https://gist.github.com/evhub/12a6d86993e8c6d3667b80c9866e06cf

### latest.log

Whole thing is too large to put in a gist, but here's the snippet from the crash: https://gist.github.com/evhub/b5929526db7e1c8217441fbd78695231 (and if you want anything else from the `latest.log`, I can get it for you)

### Did you isolate BYG?

I did not try BYG alone

**Comment by evhub** [comment]
I've now been able to replicate this completely without RFToolsDimensions being involved at all; this definitely looks like an independent BYG issue. Log: https://gist.github.com/evhub/ce74c2fcfa7ab495209bdf67771b39c6

**Comment by CorgiTaco** [comment]
This has been fixed internally as of: https://github.com/AOCAWOL/BYG/commit/3c0a50d477b7e668b47a8fda6b1562d69c941a24

**Comment by evhub** [comment]
Feel free to ignore this since it's not about a released version, but I wanted to get a build with the above bug fixed, so I built the most recent commit and it seems to mostly be working now, but sometimes I'm getting a `Feature order cycle found` crash that seems to involve BYG: https://gist.github.com/evhub/19d5a62849fc4ee1839b558da889b940
