### ISSUE TITLE
Maple Fence has no recipe, some BYG wooden Items not usable as fuel.

### ISSUE THREAD

**Issue by Werewing** [CorgiTaco/BYG#109]
Maple Fence (maple_fence) has no crafting table recipe.
BYG wood (such as Ebony and Maple) Fences, Buttons, and Gates can not be used as fuel, as vanilla wood counterparts do.

Listed as v1.0.12 in the in-game mod list, but I downloaded it as part of the All of Fabric 3 modpack, So I am not certain.

**Comment by AOCAWOL** [comment]
fixed in 1.1
