### ISSUE TITLE
[1.19][Bug][Fabric]: End Biomes dont generate things, only "grass" - no trees , etc ... 

### ISSUE THREAD

**Issue by xR4YM0ND** [CorgiTaco/BYG#1090]
### BYG Version

2.0.0.13

### Terrablender Version

2.0.1.136

### Mod Loader

Fabric 1.19.2

### Mod Loader Version

0.14.14

### Bug Severity

Major

### What happened?

![2023-02-21_21 23 18](https://user-images.githubusercontent.com/97298005/220451356-f848c35c-6297-4fcc-9f52-9f4652675142.png)
![2023-02-21_21 23 53](https://user-images.githubusercontent.com/97298005/220451366-c37546bd-8c97-43b6-8691-04d4f341d0fb.png)
![2023-02-21_21 23 07](https://user-images.githubusercontent.com/97298005/220451372-628117c5-bed7-451e-ade4-e268c515d10a.png)

### latest.log

https://gist.github.com/SpigotDE/6968c2c8849474531bbb1a018ad2bed2

### Did you isolate BYG?

I tried BYG alone

**Comment by CorgiTaco** [comment]
Use terrablender .130

**Comment by xR4YM0ND** [comment]
.130 works !
