### ISSUE TITLE
[1.19][Bug]: Black Sandstone recipe typo

### ISSUE THREAD

**Issue by 9Octopus** [CorgiTaco/BYG#1091]
### BYG Version

2.0.0.13

### Terrablender Version

2.0.1.136

### Mod Loader

Forge

### Mod Loader Version

43.2.3

### Bug Severity

Minor

### What happened?

There is a typo in the black sandstone recipe making it uncraftable.

### latest.log

Not relevant

### Did you isolate BYG?

I did not try BYG alone

**Comment by 9Octopus** [comment]
I just noticed this applies to all the sandstone variants

**Comment by CorgiTaco** [comment]
Fixed internally.
