### ISSUE TITLE
[1.19][Bug]: Can't use Sandstone Variants in Domum Ornamentum

### ISSUE THREAD

**Issue by RelativeProgramming** [CorgiTaco/BYG#1092]
### BYG Version

2.0.0.13

### Terrablender Version

2.0.1.136

### Mod Loader

Forge

### Mod Loader Version

43.2.3

### Bug Severity

Minor

### What happened?

I cannot use smooth black sandstone (or any other sandstone variant of BYG) in the Domum Ornamentum Architects cutter.
As I understand it Domum Ornamentum requires other mods to use certain tags on their blocks to allow them to be used in the cutter. (see [here](https://github.com/ldtteam/Domum-Ornamentum#vanilla-compatibility) for more info)

### latest.log

There is no crash-log.

### Did you isolate BYG?

I did not try BYG alone

**Comment by CorgiTaco** [comment]
Fixed internally.
