### ISSUE TITLE
[1.16][Bug]: Unable to locate specific biomes, possibly failing to spawn?

### ISSUE THREAD

**Issue by The-Crimson-V** [CorgiTaco/BYG#1094]
### BYG Version

1.3.5

### Mod Loader

Forge

### Mod Loader Version

36.2.34

### Bug Severity

Minor

### What happened?

Hello, I'm not exactly sure if this qualifies as a valid report or not, but I still wanted to make absolutely sure that this is indeed a bug occurring in the game, or if I'm just having unbearably bad luck. There are these 2 vanilla biomes that I'm unable to find in BYG worlds, specifically Shattered Savanna Plateau and Gravelly Mountains+. There may be others, but these are the only 2 I've found issues with so far. Maybe the sampling /locatebiome uses isn't accurate enough to find these biomes, but I assumed asking here would be best to make sure that there were no issues with the world generation. If you are able to test this for yourself and either manage to locate one of these biomes or if you discover that they definitely fail to spawn, I would greatly appreciate it. Have a good day!

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/10836133/latest.log)

### Did you isolate BYG?

I tried BYG alone

**Comment by CorgiTaco** [comment]
Gonna say that you're probably either in a large biomes world or very unlucky. The biomes you've tried searching for are rare in vanilla already. I'm going to close this. If you need more assistance please feel free to ask in our discord!
