### ISSUE TITLE
[1.19][Bug]:  cherry blossom textures

### ISSUE THREAD

**Issue by PeckingWater** [CorgiTaco/BYG#1095]
### BYG Version

1.19.2-2.0.0.13

### Terrablender Version

TerraBlender-forge-1.19.2-2.0.1.128

### Mod Loader

Forge

### Mod Loader Version

forge-1.19.2-43.1.52

### Bug Severity

Major

### What happened?

is there any way to get the older BYG cherry blossom leaves, like is there a datapack or something or like something in the config? im using 1.19.2 and the one im reffering to is from 1.16

### latest.log

no logs

### Did you isolate BYG?

I tried BYG alone

**Comment by PeckingWater** [comment]
![cherry](https://user-images.githubusercontent.com/109543939/222042745-fa6cfc15-a959-4998-8006-8460ac5696a4.png)
here is the image

**Comment by CorgiTaco** [comment]
you could make a texture pack and use that but dont redistribute it

**Comment by PeckingWater** [comment]
thanks for the advice, is there somewhere where  i can get the textures for the 1.16 leaves, :)

**Comment by CorgiTaco** [comment]
in the 1.16 jar file
