### ISSUE TITLE
[1.19][Bug]: No mobs spawning in Atacama and Windswept deserts

### ISSUE THREAD

**Issue by Maltshakes** [CorgiTaco/BYG#1098]
### BYG Version

2.0.1.0

### Terrablender Version

2.0.1.136

### Mod Loader

Forge

### Mod Loader Version

43.2.0

### Bug Severity

Major

### What happened?

No mobs spawn in the Atacama or Windswept deserts, not even hostile ones. The biomepedia also reflects this and states "This biome doesn't spawn any mobs". 

![image](https://user-images.githubusercontent.com/76584081/222215559-f6d98fb3-8d31-4244-bb77-afa58918b504.png)
![image](https://user-images.githubusercontent.com/76584081/222215586-a11881b3-fed7-4d2e-935f-1e2bea268347.png)

### latest.log

*

### Did you isolate BYG?

I tried BYG alone

**Comment by AOCAWOL** [comment]
Fixed and will be in our next patch/official release of Wilds and Wonders
