### ISSUE TITLE
[1.19][Bug]: 1.19.2 - Startup Crash with ``Oh_The_Biomes_You'll_Go-forge-1.19.2-2.0.1.0.jar`` 

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [CorgiTaco/BYG#1099]
### BYG Version

Oh_The_Biomes_You'll_Go-forge-1.19.2-2.0.1.0.jar

### Terrablender Version

 TerraBlender-forge-1.19.2-2.0.1.136.jar

### Mod Loader

Forge

### Mod Loader Version

43.2.6

### Bug Severity

Major

### What happened?

This report requires too much info ... at any rate latest BYG causes failure at startup Oh_The_Biomes_You'll_Go-forge-1.19.2-2.0.1.0.jar

### latest.log

Nope

### Did you isolate BYG?

I did not try BYG alone

**Comment by CorgiTaco** [comment]
without any sort of crash log or latest.log, we cannot help you unfortunately.
