### ISSUE TITLE
New Biomes

### ISSUE THREAD

**Issue by AOCAWOL** [CorgiTaco/BYG#11]
New Biomes will not be apart of initial release but here is a sneak peek of some New Biomes that could potentially make their way into updates down the line:

**_WARM Biomes:_**
-Wistering Woods
-Temperate Rainforest
-Stone Forest
-Valley of Flowers

**_COLD Biomes:_**
-Hemlock Taiga

**_DESERT Biomes:_**
-Scorched Forest
-Scrublands
-Atlas Mountains

**_ICY Biomes:_**
-Lush Tundra

**Comment by CorgiTaco** [comment]
Closing this as we are really not following any of these sub lists only #4 's list
