### ISSUE TITLE
Placing BYG flowers in the crafting table causes game to crash

### ISSUE THREAD

**Issue by A-a-ron717** [CorgiTaco/BYG#110]
Trying to put flowers from the mod in any of the crafting table slots will cause the game to crash

**Comment by CorgiTaco** [comment]
haha my name is also Aaron, Version and modloader please along with a crash report and latest.log

**Comment by CorgiTaco** [comment]
Any update on this or will I need to close this?

**Comment by A-a-ron717** [comment]
I am so sorry but I've been trying to recreate the issue and I can't make it happen again. It's acting normal now :( I'm sorry for wasting your time!
