### ISSUE TITLE
[1.19][Bug]: White mangrove sapling growing through non-dirt blocks

### ISSUE THREAD

**Issue by brianfreud** [CorgiTaco/BYG#1100]
### BYG Version

2.0.0.13

### Terrablender Version

2.0.1.136

### Mod Loader

Forge

### Mod Loader Version

43.2.0

### Bug Severity

Minor

### What happened?

White mangrove saplings are growing multiple blocks below the surface.  This is replacing not only dirt, but other blocks, such as shafts and bearings from Create.  The replaced blocks are destroyed.  The sapling should only replace dirt and dirt-variants.

### latest.log

N/A

### Did you isolate BYG?

I did not try BYG alone

**Comment by CorgiTaco** [comment]
does this issue occur on the latest version 2.0.1.0?

**Comment by brianfreud** [comment]
I just upgraded to the 2.0.1.0 (plus the new dependancies).  ~10 minutes of running the farm, and yes, it still has the same issue.  
![Screenshot from 2023-03-02 07-22-23](https://user-images.githubusercontent.com/49247/222428342-d910df36-9345-46b5-8b24-04b70ccbbee2.png)
![Screenshot from 2023-03-02 07-26-06](https://user-images.githubusercontent.com/49247/222428532-0ba883fa-41f4-405d-8886-cd73c2673dde.png)

You can see where a vertical gearbox and mechanical bearing have been replaced by white mangrove logs.  (Identical behaviour in 2.0.1.0 vs the prior version).  I've not upgraded anything else, including Forge.

**Comment by brianfreud** [comment]
I just found another instance where, with 2.0.1.0, a Redwood sapling had grown down through a dirt block, then another 4 stone blocks below that dirt block.

**Comment by CorgiTaco** [comment]
@brianfreud I cant reproduce this: https://i.imgur.com/GJ1okl0.mp4

**Comment by brianfreud** [comment]
I wonder if it is viewing Create bearings as empty space when they are in motion?  I think they have some sort of pseudo-entity status when active.  However, eEach time it hit me, the vertical gearbox block was below the bearing block, and the gearbox doesn't move (ie, should have been seen as a solid non-dirt block).

In the meantime, I've been working out the growth requirements for the white mangrove saplings, to try and harvest and plant them in a different manner which doesn't involve any bearings located within the growth area.  The saplings have a 5x3 placement grid, but it seems that that must be in N-S alignment; placing them in a E-W alignment results in no growth.
