### ISSUE TITLE
[1.19][Bug]: Blue nether brick stairs are too difficult to break, and break without dropping an item

### ISSUE THREAD

**Issue by brianfreud** [CorgiTaco/BYG#1107]
### BYG Version

2.0.0.13 and 2.0.1.0

### Terrablender Version

2.0.1.136

### Mod Loader

Forge

### Mod Loader Version

43.2.0

### Bug Severity

Minor

### What happened?

Using an iron pickaxe, blue nether brick stairs take about six times longer to break than blue nether brick blocks.  Also, blue nether brick blocks drop as items with an iron pickaxe, while blue nether brick stairs simply get destroyed with the same.  The effort to destroy the stairs should be the same as the block, and they should drop as items.

(Side note, there is an identically named set of items in Quark, with the same graphics, but a much more cyan color.  Personally, I prefer the color of the BYG ones; I only wish there were a recipe to also make a darker blue version, darker than the BYG ones, similar to Nether Bricks vs Red Nether Bricks).

### latest.log

N/A

### Did you isolate BYG?

I did not try BYG alone

**Comment by Viola-Siemens** [comment]
I tried byg and terrablender alone and it still happened. version 2.0.0.13. And same problem also occurs on blue nether brick slab.
I find "byg:blue_nether_brick_stairs" and "byg:blue_nether_brick_slab" are missing in data\minecraft\tags\blocks\mineable\pickaxe.json of "Oh_The_Biomes_You'll_Go-forge-1.19.2-2.0.0.13.jar", but i could find them [here](https://github.com/AOCAWOL/BYG/blob/1.19.X/Common/src/main/resources/data/minecraft/tags/blocks/mineable/pickaxe.json#L13).

**Comment by CorgiTaco** [comment]
I believe this is fixed in 2.0.1.1.
