### ISSUE TITLE
[1.19.2][Bug]: Unable to join open to lan worlds with mods listed below

### ISSUE THREAD

**Issue by KPaXz** [CorgiTaco/BYG#1108]
### BYG Version

Oh_The_Biomes_You'll_Go-forge-1.19.2-2.0.0.13

### Terrablender Version

TerraBlender-forge-1.19.2-2.0.1.136

### Mod Loader

Forge

### Mod Loader Version

forge-1.19.2-43.2.6-installer

### Bug Severity

Major

### What happened?

Mod list:

accelerated-decay-forge-1.0.0+mc1.19.2
alexsmobs-1.21.1
AmbientSounds_FORGE_v5.2.13_mc1.19.2
Aquaculture-1.19.2-2.4.8
architectury-6.5.69-forge
AutoRegLib-1.8.2-55
BambooEverything-forge-2.2.4-build.33+mc1.19.2
Better+Biscuits+1.5+for+Forge+1.19
betteranimalsplus-1.19.2-11.0.10-forge
BiomesOPlenty-1.19.2-17.1.2.492
Bookshelf-Forge-1.19.2-16.2.17
born_in_chaos_1.19_1.3
Botania-1.19.2-438-FORGE
bucketlib-1.19-1.0.3.2
buildersaddition-1.19.2-20220926a
caelus-forge-1.19.2-3.0.0.6
canary-mc1.19.2-0.1.9
carryon-forge-1.19.2-2.0.5.10
catalogue-1.7.0-1.19.2
chipped-forge-1.19.2-2.1.1
citadel-2.1.1-1.19
cloth-config-8.2.88-forge
cofh_core-1.19.2-10.2.1.40
collectorsreap-1.19-1.2
comforts-forge-6.0.3+1.19.2
configured-2.0.1-1.19.2
connectedglass-1.1.6-forge-mc1.19
CopperDrops-1.19-1.0
Copperized-1.19-2.5
CorgiLib-forge-1.19.2-1.0.0.32
create-1.19.2-0.5.0.i
createaddition-1.19.2-20230202b
createplus-1.19.2_v0.5.3-beta3
CreativeCore_FORGE_v2.9.3_mc1.19.2
crittersandcompanions-1.19.2-1.1.2
CTM-1.19.2-1.1.6+8
curios-forge-1.19.2-5.1.3.0
deeperdarker-forge-1.1.6-forge
Delightful-1.19.2-3.2.2
domum_ornamentum-1.19-1.0.83-ALPHA-universal
DynamicSurroundings-6.0.0.2
ecologics-forge-1.19.2-2.1.11
effective_fg-1.3.4
elevatorid-1.19.2-1.8.9
EnchantmentDescriptions-Forge-1.19.2-13.0.14
Enderite-1.5-1.19.2-Forge
Entity_Collision_FPS_Fix-forge-1.19-2.0.0.0
entityculling-forge-1.6.1-mc1.19.2
everycomp-1.19.2-2.2.3
FarmersDelight-1.19-1.2.0
ftb-industrial-contraptions-1900.1.7-build.221
ftb-library-forge-1902.3.14-build.184
geckolib-forge-1.19-3.1.40
getittogetherdrops-forge-1.19.2-1.3
handcrafted-forge-1.19.2-2.0.2
harvestwithease-1.19.2-4.0.0.3-forge
horse_colors-1.19.2-11.1
ImmersiveEngineering-1.19.2-9.2.0-162
industrial-foregoing-1.19.2-3.3.2.2-4
InventoryProfilesNext-forge-1.19-1.9.2
ironchest-1.19.2-14.2.7
Jade-1.19.1-forge-8.8.0
jei-1.19.2-forge-11.6.0.1011
kotlinforforge-3.10.0-all
libIPN-forge-1.19-2.0.2
loot_journal-2.1
Mekanism-1.19.2-10.3.8.477
MekanismAdditions-1.19.2-10.3.8.477
MekanismGenerators-1.19.2-10.3.8.477
MekanismTools-1.19.2-10.3.8.477
modnametooltip-1.19-1.19.0
moonlight-1.19.2-2.2.14-forge
MoreHorseArmor-1.19-1.2
myrtrees-forge-1.2.0-build.32
naturalist-forge-2.1.1-1.19.2
NethersDelight-1.19-3.0
Oh_The_Biomes_You'll_Go-forge-1.19.2-2.0.0.13
oresabovediamonds-9.0.2
Patchouli-1.19.2-77
polymorph-forge-0.46.1+1.19.2
PuzzlesLib-v4.3.12-1.19.2-Forge
Quark-3.4-393
rechiseled-1.0.12a-forge-mc1.19
resourcefullib-forge-1.19.2-1.1.22
saturn-mc1.19.2-0.0.1
SilentCompat-forge-1.19.2-1.1.1
silent-gear-1.19.2-3.2.5
silent-lib-1.19.2-7.0.3
SimpleCoreLib-1.19.2-5.1.0.2
SimpleOres2-1.19.2-5.1.1.8-all
simpletomb-1.19-1.0.15
smoothboot(reloaded)-mc1.19.2-0.0.2
sophisticatedbackpacks-1.19.2-3.18.40.779
sophisticatedcore-1.19.2-0.5.38.203
supermartijn642configlib-1.1.6b-forge-mc1.19
supermartijn642corelib-1.1.4-forge-mc1.19
tempad-forge-1.19.2-1.4.4
TerraBlender-forge-1.19.2-2.0.1.136
Terralith_v2.3.6
thermal_cultivation-1.19.2-10.2.0.17
thermal_expansion-1.19.2-10.2.0.21
thermal_foundation-1.19.2-10.2.0.47
thermal_innovation-1.19.2-10.2.0.18
thermal_integration-1.19.2-10.2.0.17
titanium-1.19.2-3.7.2-26
tools_complement-1.19.2-3.2.0.19
VisualWorkbench-v4.2.3-1.19.2-Forge
voicechat-forge-1.19.2-2.3.28
whisperwoods-1.19-2.1.1-forge
Xaeros_Minimap_23.2.0_Forge_1.19.1
XaerosWorldMap_1.29.1_Forge_1.19.1

After creating a single player world with the list of mods above, I open to lan and invite my relative to play. There is a short pause after clicking join server during Encrypting then we get this error.

Internal Exception: java.net.SocketException: Connection reset

Other times it might say: Disconnected

I ruled oh the biomes youll go being the conflict by using the thanos method, which implies splitting your mods into two groups, testing one group, if it works split the other half you didnt use and test one of the halfs and repeat till the mod causing the conflict happens. which in my results was oh the biomes youll go. so i tried all my mods without oh the biomes youll go, they were able to join my open to lan. then i tried with oh the biomes youll go and got that error everytime about connection reset.
We have tried resetting configs and updated to the latest release version of 1.19.2

latest-host is the computer running the world.

### latest.log

[latest-host.log](https://github.com/AOCAWOL/BYG/files/10905215/latest-host.log)
[latest.log](https://github.com/AOCAWOL/BYG/files/10905216/latest.log)

### Did you isolate BYG?

I did not try BYG alone

**Comment by CorgiTaco** [comment]
without a log from the host & the connecting client, we cant help, i'll reopen the issue when you provide those

**Comment by KPaXz** [comment]
alright ill get those to you in awhile

**Comment by KPaXz** [comment]
> without a log from the host & the connecting client, we cant help, i'll reopen the issue when you provide those

Alright I've uploaded both the latest logs
