### ISSUE TITLE
[1.16.3] Please add a way to Print Biomes to log

### ISSUE THREAD

**Issue by MokahTGS** [CorgiTaco/BYG#111]
Currently in 1.16.3 there is only the command that puts all the biomes in the datapack folder, which has it's uses, but can we please have a way to print all of the biome names into the log as a straight text file so that we can add them to other mods for compatibility?

Crafttweaker did that with a command and it would print all of the biomes in the forge registry.  Is there a way to do that in 1.16.3?

**Comment by CorgiTaco** [comment]
I'm gonna say no as this seems to be more of an issue unique to you and specific others but not everyone else. This doesn't mean I won't add it in the future.
