### ISSUE TITLE
You forgot to specify corgelib as required

### ISSUE THREAD

**Issue by uhloin** [CorgiTaco/BYG#1111]
### BYG Version

Oh_The_Biomes_You'll_Go-forge-1.19.2-2.0.1.1.jar

### Terrablender Version

TerraBlender-forge-1.19.2-2.0.1.136.jar

### Mod Loader

Forge

### Mod Loader Version

forge-1.19.2-43.2.3-installer.jar

### Bug Severity

Major

### What happened?

Last forge version for 1.19.2 can't start without corgelib. This should be specified explicitly on the main page and in Dependencies part.

### latest.log

-

### Did you isolate BYG?

I did not try BYG alone

**Comment by CorgiTaco** [comment]
Should be fixed now
