### ISSUE TITLE
Found weird recipe (1.19.2)

### ISSUE THREAD

**Issue by Gitcrafter** [CorgiTaco/BYG#1112]
### BYG Version

1.19.2 2.0.1.1

### Terrablender Version

1.19.2 2.0.1.136

### Mod Loader

Forge

### Mod Loader Version

1.19.2 43.2.4

### Bug Severity

Minor

### What happened?

I found a weird recipe, see the screenshot below:

![2023-03-07_16 36 35](https://user-images.githubusercontent.com/81863925/223473522-bb365371-5475-4063-a6e3-da2736f7bae8.png)

### latest.log

not needed

### Did you isolate BYG?

I did not try BYG alone

**Comment by CorgiTaco** [comment]
I can't find any references to `lignite` in the entire code base (only in lang files), so I'm going to guess this is either another mod or the modpack you are playing with an old tag.
