### ISSUE TITLE
[1.19.2][Bug]: No Trees spawning on dimensions like Nether or End.

### ISSUE THREAD

**Issue by Asgelion** [CorgiTaco/BYG#1114]
### BYG Version

2.0.1.1

### Terrablender Version

2.0.1.136

### Mod Loader

Forge

### Mod Loader Version

43.2.6

### Bug Severity

Major

### What happened?

Hey! i've tried everything i could to get this fixed but the Trees and every other type of nature is not spawning on The Nether and The End, pretty mutch the only thing i see is the colored nether or endstone blocks. i removed every mod in my mod pack and tried BYG by itself, anyway it didn't work. Appreciate your time if you do so.

### latest.log

![2023-03-08_06 38 45](https://user-images.githubusercontent.com/127281571/223628630-edffdb39-2898-4e83-82b3-1c2a9ebdd29b.png)

### Did you isolate BYG?

I tried BYG alone

**Comment by XDead07** [comment]
Exact same bug here

**Comment by Asgelion** [comment]
@XDead07 hey since i never got any response my team and i got a reliable way to fix it. you can download NBTExplorer with that app you just need to rename the dimension nether or end were it says BYG_nether.

I'll leave a link for you to have the entire way to fix it: https://github.com/EnigmaticaModpacks/Enigmatica6/issues/1075 (didn't find the original link) you can also watch a NBTEXPLORER guide. feel free to let me know if you got over it.

**Comment by Aleon4201** [comment]
I met the same issue, but it seems to be fixed.
Just install CorgiLib.
However, you may need to remove config/byg folder. (Btw, I updated byg from an older version too.)

**Comment by unmoving-javi** [comment]
Apparently this is a known error in BYG that comes from using a version of Terrablender greater than .130.
I have no idea why this isn't listed anywhere but their discord, but hey.

**Comment by CorgiTaco** [comment]
You'll need to use: https://www.curseforge.com/minecraft/mc-mods/terrablender/files/4095397
