### ISSUE TITLE
[1.19][Bug]: Certain saplings do not grow, naturally or bone mealed.

### ISSUE THREAD

**Issue by rckymtnrfc** [CorgiTaco/BYG#1115]
### BYG Version

2.0.1.1

### Terrablender Version

2.0.1.136

### Mod Loader

Forge

### Mod Loader Version

43.2.6

### Bug Severity

Minor

### What happened?

Blue Enchanting, Nightshade and Brown Zelcova saplings do not grow.  This might also be happening with the Shulkren Fungus, Imparius Mushroom and Fungal Imparius but I'm not sure if they **should** grow into a larger mushroom like the others.  I also could not get the 2 different Bulbis Oddities to grow but I'm not sure if they needed a special soil block.  I tried on Mycelium.  If saplings had different planting patterns listed in the tooltip, I tried all variants.  I attempted using bonemeal as well as waiting 20 real  world mins to see if they would grow naturally, none did.

Additionally, I occasionally get the following server log msg:

[19:52:38] [Server thread/ERROR] [po.by.BYG/]: Grower "byg:blue_enchanted_sapling" failed when attempting to spawn configured feature "Spawner[spawnerID=byg:blue_enchanted_tree1, spawnOffset=Vec3i{x=0, y=0, z=0}]" at position BlockPos{x=-129, y=69, z=493}. "Spawner[spawnerID=byg:blue_enchanted_tree1, spawnOffset=Vec3i{x=0, y=0, z=0}]" is not a valid configured feature ID in this world's datapack configured feature registry! Valid entries:
 0. "minecraft:seagrass_short"
1. "minecraft:seagrass_slightly_less_short"
2. "minecraft:seagrass_mid"

This list of valid entries goes on for 858 different items.

### latest.log

https://pastebin.com/rGLGFCBD

### Did you isolate BYG?

I tried BYG alone

**Comment by rckymtnrfc** [comment]
Oh I meant to mention, I did just delete my BYG configs on the client and server when I moved to 2.0.1.1.

**Comment by KaiseerKenopsia** [comment]
Happens on my server too, also, in the list of the valid entries the entry for green_enchanted_tree is misspelled
log: https://mclo.gs/khe4Cqm

important bits:
```
[27Mar2023 13:54:04.577] [Server thread/ERROR] [potionstudios.byg.BYG/]: Grower "byg:green_enchanted_sapling" failed when attempting to spawn configured feature "Spawner[spawnerID=byg:green_enchanted_tree3, spawnOffset=Vec3i{x=0, y=0, z=0}]" at position BlockPos{x=638, y=63, z=760}. "Spawner[spawnerID=byg:green_enchanted_tree3, spawnOffset=Vec3i{x=0, y=0, z=0}]" is not a valid configured feature ID in this world's datapack configured feature registry! Valid entries:
...
...
 503. "byg:green_echanted_tree1"
 504. "byg:green_echanted_tree2"
 505. "byg:green_echanted_tree3"
 506. "byg:green_echanted_tree4"
```
I'm running ATM8 1.0.14, not sure which version of byg and everything else is there, but can provide later if someone asks, working right now

**Comment by KaiseerKenopsia** [comment]
https://github.com/AOCAWOL/BYG/commit/ba9410fc4d5e61b781cebc9f0125b1cc204045b5
https://github.com/AOCAWOL/BYG/pull/1130
maybe this will fix some of it

**Comment by fillibar** [comment]
That fix may get the enchanted trees but that still leaves the brown zelkova at least. Here is the error and the related list items showing it is looking for zelkova_brown but the list is brown_zelkova:
[Server thread/ERROR] [po.by.BYG/]: Grower "byg:brown_zelkova_sapling" failed when attempting to spawn configured feature "Spawner[spawnerID=byg:zelkova_brown_tree2, spawnOffset=Vec3i{x=0, y=0, z=0}]" at position BlockPos{x=35, y=64, z=-7}. "Spawner[spawnerID=byg:zelkova_brown_tree2, spawnOffset=Vec3i{x=0, y=0, z=0}]" is not a valid configured feature ID in this world's datapack configured feature registry! Valid entries:
419. "byg:brown_zelkova_tree1"
420. "byg:brown_zelkova_tree2"
421. "byg:brown_zelkova_tree3"

**Comment by brianfreud** [comment]
I'm also getting this from the zelkova saplings.  Additionally, I'm getting it from:

Spawner[spawnerID=byg:zelkova_brown_tree1
Spawner[spawnerID=byg:zelkova_brown_tree2
Spawner[spawnerID=byg:zelkova_brown_tree3
Spawner[spawnerID=byg:deciduous_orange_tree1
Spawner[spawnerID=byg:deciduous_orange_tree2
Spawner[spawnerID=byg:deciduous_orange_tree3
Spawner[spawnerID=byg:deciduous_orange_tree4
Spawner[spawnerID=byg:deciduous_red_tree1
Spawner[spawnerID=byg:deciduous_red_tree2
Spawner[spawnerID=byg:deciduous_red_tree3
Spawner[spawnerID=byg:deciduous_red_tree4

**Comment by brianfreud** [comment]
Cypress trees are also affected.

**Comment by james58899** [comment]
```
deciduous_red_tree1
deciduous_red_tree2
deciduous_red_tree3
deciduous_red_tree4
deciduous_orange_tree1
deciduous_orange_tree2
deciduous_orange_tree3
deciduous_orange_tree4
deciduous_brown_tree1
deciduous_brown_tree2
deciduous_brown_tree3
deciduous_brown_tree4
```

These removed in https://github.com/AOCAWOL/BYG/commit/4ab1d5d501687d58d2172fe826b9b92d8c166d09

**Comment by ModKing58** [comment]
I'm a little new to this where do I find the config file to fix the typo for the enchanted trees?

**Comment by brianfreud** [comment]
> ```
> deciduous_red_tree1
> deciduous_red_tree2
> deciduous_red_tree3
> deciduous_red_tree4
> deciduous_orange_tree1
> deciduous_orange_tree2
> deciduous_orange_tree3
> deciduous_orange_tree4
> deciduous_brown_tree1
> deciduous_brown_tree2
> deciduous_brown_tree3
> deciduous_brown_tree4
> ```
> 
> These removed in [4ab1d5d](https://github.com/AOCAWOL/BYG/commit/4ab1d5d501687d58d2172fe826b9b92d8c166d09)

Good to see.  Hopefully an updated version soon that includes the tree fixes?  :)

**Comment by allanonmage** [comment]
I'm not clear on what happened.  Has this been fixed in a release?  Or do I need to modify a config file somewhere?

**Comment by rckymtnrfc** [comment]
I just updated to 2.0.1.3 and it does not appear to be fixed.

**Comment by allanonmage** [comment]
If we want to fix it ourselves, we modify the java files and then do we need to compile to bytecode?  Or just edit a file within the jar file?  When I took Java at school 20+ years ago, they taught us in a home grown text editor, and I'm sure some things have changed since then.

**Comment by allanonmage** [comment]
My player who wants to grow trees reminded me this is still a bug.  Is there an ETA for a fix?  Alternatively, to modify the java files I guess I would need to know the development toolchain so I could compile it.  What tools do most modders use anyways?  When I was taught Java, they had us use some University of Arizona homegrown IDE long before IDE was even really a common word.  It actually had less features than NotePad++ does nowadays.
