### ISSUE TITLE
[1.19.2][Crash]: Game crashes on entering end portal when BYG is installed alongside BetterEnd.

### ISSUE THREAD

**Issue by ambientNexus** [CorgiTaco/BYG#1116]
### BYG Version

2.0.1.1

### Terrablender Version

2.0.1.136

### Mod Loader

Fabric

### Mod Loader Version

0.14.17

### What happened?

Whenever I try to enter the end portal with both mods installed (and dependencies), the game will instantly crash. Game works perfectly fine with one mod or the other, it's specifically BYG and BetterEnd together that seems to cause this issue.

### crash-log

[crash-2023-03-11_23.17.23-server.txt](https://github.com/AOCAWOL/BYG/files/10950224/crash-2023-03-11_23.17.23-server.txt)

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/10950223/latest.log)

### Did you isolate BYG?

I tried BYG alone

**Comment by GhostIsBeHere** [comment]
I got a bit more info when using the Cyanide mod:

```
Description: Exception generating new chunk

com.alcatrazescapee.cyanide.codec.FeatureCycleDetector$FeatureCycleException: A feature cycle was found.

Cycle:
At step 9
Feature 'betterend:purple_polypore'
  must be before 'minecraft:chorus_plant' (defined in 'betterend:chorus_forest' at index 2, 3)
  must be before 'byg:mixed_color_bulbis_trees' (defined in 'byg:bulbis_gardens' at index 0, 1 and 1 others)
  must be before 'byg:bulbis_oddities' (defined in 'byg:bulbis_gardens' at index 1, 2 and 1 others)
  must be before 'byg:bulbis_sprouts' (defined in 'byg:bulbis_gardens' at index 2, 3 and 1 others)
  must be before 'byg:bulbis_anomalies' (defined in 'byg:bulbis_gardens' at index 3, 4 and 1 others)
  must be before 'betterend:purple_polypore' (defined in 'betterend:old_bulbis_gardens' at index 5, 6
 ```
Hope this helps!

**Comment by GhostIsBeHere** [comment]
Quick fix is to disable betterend:chorus_forest in both betterend and byg configs

**Comment by ambientNexus** [comment]
Ah, thank you. Seems the issue is on betterend's side then, hopefully it gets fixed soon.

**Comment by Greshtahu** [comment]
> Quick fix is to disable betterend:chorus_forest in both betterend and byg configs

I am having a similar issue but I don't see a biome.json file in my betterend config folder, only my bclib config folder. The bclib folders biome.json doesn't show any of that. Do you know where I might be able to find the file to disable the betterend:chorus_forest setting?
