### ISSUE TITLE
[1.19.2][Bug]: Bulbis logs unobtainable in survival

### ISSUE THREAD

**Issue by anarisis** [CorgiTaco/BYG#1117]
### BYG Version

2.0.0.13

### Terrablender Version

2.0.1.128

### Mod Loader

Forge

### Mod Loader Version

43.2.0

### Bug Severity

Minor

### What happened?

Bulbis trees consist only of Bulbis wood, even when grown manually, and wood can't be converted back into logs. Because of this, Bulbis logs can't be obtained in survival.

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/10962951/latest.log)

### Did you isolate BYG?

I tried BYG alone

**Comment by CorgiTaco** [comment]
https://github.com/AOCAWOL/BYG/assets/66983020/f5a93bd8-c590-4ac0-ae71-85a512b5d1a0

Works on my end on latest version.

**Comment by anarisis** [comment]
This is the exact opposite of the issue I described and does not demonstrate a fix. For clarity…

### Steps to reproduce:

1. Load into a world and navigate to a Bulbis Gardens biome.
2. Chop into a bulbis tree
3. Realize all of its blocks are Bulbis **Wood** and not Bulbis **Stem** (the item you used in your demonstration)
4. Place Bulbis Wood harvested from a tree into a crafting grid
5. Receive Bulbis **Planks**

It is not possible to obtain Bulbis Stem in Survival unless trees are made to generate with them again, or a craft-down recipe from wood is added.
