### ISSUE TITLE
[1.18][Bug]: A feature cycle was found. Feature '[Unknown minecraft:worldgen/placed_feature]'

### ISSUE THREAD

**Issue by border999** [CorgiTaco/BYG#1119]
### BYG Version

1.4.7

### Terrablender Version

1.2.0.126

### Mod Loader

Forge

### Mod Loader Version

40.2.0

### Bug Severity

Major

### What happened?

[crash-2023-03-14_19.20.47-server.txt](https://github.com/AOCAWOL/BYG/files/10984688/crash-2023-03-14_19.20.47-server.txt)
it broke my world as far as I'm aware. This appears to be an issue between multiple mods.

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/10984689/latest.log)

### Did you isolate BYG?

I did not try BYG alone

**Comment by CorgiTaco** [comment]
It's your duty to filter through your mods and figure out which mod in question is the culprit of the crash and possibly incompatibility.
