### ISSUE TITLE
[1.16][Bug]: Server TPS drop with regards to saplings(?)

### ISSUE THREAD

**Issue by SnowBlitzz** [CorgiTaco/BYG#1120]
### BYG Version

1.3.6

### Mod Loader

Forge

### Mod Loader Version

36.2.24

### Bug Severity

Major

### What happened?

![image](https://user-images.githubusercontent.com/7488382/225485833-ba168548-2413-4a94-b6c6-ebd23fe50d62.png)
Spark profiler report: https://spark.lucko.me/VMsky9TDB8

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/10985876/latest.log)

### Did you isolate BYG?

I did not try BYG alone

**Comment by JT122406** [comment]
1.16 isn't supported
