### ISSUE TITLE
[1.19.2][Bug]: Villages not spawning

### ISSUE THREAD

**Issue by Pyro213** [CorgiTaco/BYG#1121]
### BYG Version

2.0.0.13

### Terrablender Version

2.0.1.128

### Mod Loader

Forge

### Mod Loader Version

43.2.0

### Bug Severity

Major

### What happened?

Looks like villages either don't or are several reduced in chance in BYG biomes.  I've confirmed with a seed viewer that Villages in Vinalla don't spawn in BYG biomes.

Please advise

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/10988686/latest.log)
^ my mod packs log

[latest.log](https://github.com/AOCAWOL/BYG/files/10988691/latest.log)
^ isolated test of BYG

### Did you isolate BYG?

I tried BYG alone

**Comment by AOCAWOL** [comment]
Closing this as this is simply a feature/structure preference. You can actually via datapacks/tags determine where structures spawn. If you are unhappy with what biomes BYG places structures within please feel free to datapack the structure tags to include more biomes. We personally do not find all vanilla structures to fit theme wise within all BYG biomes however with a simple /locate command I am able to very quickly find villages from BYG & Vanilla.
