### ISSUE TITLE
[1.18][Bug]: Anomalous crash

### ISSUE THREAD

**Issue by Reshy** [CorgiTaco/BYG#1123]
### BYG Version

 Oh_The_Biomes_You'll_Go-forge-1.18.2-1.4.7.jar

### Terrablender Version

TerraBlender-forge-1.18.2-1.2.0.126.jar

### Mod Loader

Forge

### Mod Loader Version

40.2.1

### Bug Severity

Major

### What happened?

Not sure what happened, but attempting to load the modpack at one point produced this crash, probably some conflict with an updated mod?

### latest.log

Crash:  https://pastebin.com/JaDvzyNL

Latest:  https://pastebin.com/Dgg9PTqE

### Did you isolate BYG?

I tried BYG alone

**Comment by CorgiTaco** [comment]
Going to say this is a conflicting mod, could you please isolate the conflict and post back here please. 

FYI: No response in 30 days means this issue will be closed.

**Comment by CorgiTaco** [comment]
No response closing
