### ISSUE TITLE
[1.19][Crash]: 

### ISSUE THREAD

**Issue by KostromDan** [CorgiTaco/BYG#1126]
### BYG Version

2.0.1.1

### Terrablender Version

2.0.1.136

### Mod Loader

Forge

### Mod Loader Version

43.2.8

### What happened?

I disabled some biomes in cfg, restarted minecraft, tried to create world, but after 30 minutes, I realized that it would last forever and closed minecraft, restarted, but same, reseted byg config by deleting it. Tryed with only one biome, with very careful syntax control, but same.
Also is it any way to disable byg custom generator and use it only as standart biome mod as BOP? Cause i need large biomes work correctly.
I'm creator of M-Tech modpack, witch has ~1m downloads on curseforge. I want to add your mod ,but if i can't diable some biomes or haven't got large biomes option, it's impossible.

### crash-log

[crash-2023-03-23_05.07.55-server.txt](https://github.com/AOCAWOL/BYG/files/11064004/crash-2023-03-23_05.07.55-server.txt)

### latest.log

[crash-2023-03-23_05.07.55-server.txt](https://github.com/AOCAWOL/BYG/files/11064005/crash-2023-03-23_05.07.55-server.txt)

### Did you isolate BYG?

I did not try BYG alone

**Comment by CorgiTaco** [comment]
To disable biomes, you'll need to put another biome in the place of the biome you deleted, I can see here that you didn't do that.

```
java.lang.ArrayIndexOutOfBoundsException: Index 4 out of bounds for length 4.
```

Could you send the config file(s) you changed?

**Comment by CorgiTaco** [comment]
No response, closing.
