### ISSUE TITLE
[1.19][Crash]: Error during common_setup event phase

### ISSUE THREAD

**Issue by trigirl48** [CorgiTaco/BYG#1129]
### BYG Version

1.19.2-2.0.1.1

### Terrablender Version

1.19.2-2.0.1.136

### Mod Loader

Forge

### Mod Loader Version

0.220.1

### What happened?

Mod File: /C:/Users/trigi/curseforge/minecraft/Instances/Story Time Legends/mods/Oh_The_Biomes_You'll_Go-forge-1.19.2-2.0.1.1.jar
	Failure message: Oh The Biomes You'll Go (byg) encountered an error during the common_setup event phase
		java.lang.IllegalStateException: Config errors were found:
		
		Jankson file reading for "C:\Users\trigi\curseforge\minecraft\Instances\Story Time Legends\config\byg\overworld\byg-overworld-biomes.json5" failed due to the following error(s):
		java.lang.IllegalArgumentException: Jankson file reading for "C:\Users\trigi\curseforge\minecraft\Instances\Story Time Legends\config\byg\overworld\byg-overworld-biomes.json5" failed due to the following error(s):
		No key global_biome_swapper in MapLike[{ /* Global toggle to enable or disable BYG's overworld biomes. */ "overworld_enabled": true, /* A list of weighted regions containing a unique biome layout. */ /* Regions may be inlined or may call a file from "this_file_parent_directory/regions" */ "regions": [ "region_1", "region_2", "region_3", "rare_region_1" ] }]

### crash-log

[crash-2023-03-24_21.03.06-fml.txt](https://github.com/AOCAWOL/BYG/files/11069433/crash-2023-03-24_21.03.06-fml.txt)

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/11069435/latest.log)

### Did you isolate BYG?

I tried BYG alone

**Comment by trigirl48** [comment]
Accidently uploaded the wrong crash report, here is the correct one. 
[BYG error.txt](https://github.com/AOCAWOL/BYG/files/11069853/BYG.error.txt)

**Comment by Pablokiryu** [comment]
I am also facing the same issue, it happened after updating the mod. 

[Log](https://mclo.gs/fPP3MPA#L4417)

**Comment by KB-Q** [comment]
Same error:
[crash-2023-04-22_17.04.05-client.txt](https://github.com/AOCAWOL/BYG/files/11301196/crash-2023-04-22_17.04.05-client.txt)

**Comment by CorgiTaco** [comment]
Delete your config folder and let it regen
