### ISSUE TITLE
[Fabric 1.16.3] Multiple layers of nether overgrowth with Better Nether

### ISSUE THREAD

**Issue by Redd56** [CorgiTaco/BYG#113]
![image](https://user-images.githubusercontent.com/12189828/95692531-4519e380-0bdb-11eb-9bf8-f2265ea8ea22.png)
happens when you have better nether installed. should only be 1 layer

**Comment by Redd56** [comment]
![image](https://user-images.githubusercontent.com/12189828/95693178-e145e980-0bdf-11eb-8d08-f912bff99a84.png)
just ran into this as well, lmao

**Comment by Redd56** [comment]
just ran into this as well lmao
![image](https://user-images.githubusercontent.com/12189828/95693210-06d2f300-0be0-11eb-8993-7915c2a6a4de.png)

**Comment by CorgiTaco** [comment]
There's nothing wrong with that? Just better nether on our blue netherrack.....

**Comment by Redd56** [comment]
wait theres normaly areas without the embur nylium? huh didnt know that

**Comment by CorgiTaco** [comment]
Oh wait I'm dumb yeah that's wrong lol

**Comment by Redd56** [comment]
XD ROFL

**Comment by Redd56** [comment]
im guesing its also from the tags

**Comment by Redd56** [comment]
![image](https://user-images.githubusercontent.com/12189828/95693340-b314d980-0be0-11eb-95e7-62370dd68632.png)
found a big area,

**Comment by CorgiTaco** [comment]
If the issue persists comment back here but I believe I've fixed it
