### ISSUE TITLE
[1.19][Bug]: Enchanted saplings do not grow when bonemealed

### ISSUE THREAD

**Issue by championhestu** [CorgiTaco/BYG#1131]
### BYG Version

2.0.1.1

### Terrablender Version

2.0.1.136

### Mod Loader

Forge

### Mod Loader Version

43.2.5

### Bug Severity

Minor

### What happened?

Enchanted trees (both green and blue) do not grow when bonemealed, even when placed in the correct pattern.

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/11095193/latest.log)

### Did you isolate BYG?

I did not try BYG alone

**Comment by TheDrawingCoder-Gamer** [comment]
see #1115

**Comment by CorgiTaco** [comment]
Works on my end https://i.imgur.com/a0a8vA6.mp4

I'd say delete the growing patterns config and let it regen.
