### ISSUE TITLE
[1.16][Bug]: Missing Nether & End Dimension

### ISSUE THREAD

**Issue by RogueRrabbit** [CorgiTaco/BYG#1132]
### BYG Version

7.1.3

### Mod Loader

Fabric

### Mod Loader Version

1.14.14

### Bug Severity

Major

### What happened?

I am having an error in my server console where BYG is messing up the Better Nether and Better End mods. I've seen that this has been an issue with the newer releases and everything is fully updated. I'm wondering if there is a solution in the server console I can do? 

### latest.log

29.03 00:40:02 [Server] Server thread/ERROR Unable to find level stem/dimension "ResourceKey[minecraft:dimension / minecraft:the_nether]", this is most likely due to a world being moved across minecraft versions, Oh The Biomes You'll Go cannot support this operation.
29.03 00:40:02 [Server] INFO Not adding surface rules....
29.03 00:40:02 [Server] Server thread/ERROR Unable to find level stem/dimension "ResourceKey[minecraft:dimension / minecraft:the_end]", this is most likely due to a world being moved across minecraft versions, Oh The Biomes You'll Go cannot support this operation.

### Did you isolate BYG?

I did not try BYG alone

**Comment by Cornejvr03** [comment]
I have a crash issue possibly caused by BYG whenever I try to enter the Nether. The game crashes as soon as I enter the portal. Am on the same game version (1.16.5)

**Comment by CorgiTaco** [comment]
You'll need to edit the level.dat to re-add the nether and end dimension data.
