### ISSUE TITLE
[1.19][Crash]: Game crashes on start up anytime BYG is used

### ISSUE THREAD

**Issue by AndyKitty8** [CorgiTaco/BYG#1133]
### BYG Version

2.0.1.1

### Terrablender Version

2.0.1.128

### Mod Loader

Forge

### Mod Loader Version

43.2.8

### What happened?

When I try to load minecraft from the launcher using the latest 1.19.2 forge version, it does not load and instead says the game has crashed. I isolated BYG and terrablender and the same thing happens. I'm not very experienced with mods so it may be an issue with my setup and not the mod, but I don't know how else to fix this.

### crash-log

I looked in the crash report folder in the .minecraft folder on my computer (Windows 11) but there are no reports for the several times I've tested this. Maybe because it crashed on start up? I honestly have no idea, like I said, I'm very inexperienced with this, I'm so sorry.

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/11114896/latest.log)

### Did you isolate BYG?

I tried BYG alone

**Comment by AndyKitty8** [comment]
Just attempted with Forge version 43.2.0 with the save versions of BYG and Terraforge and the game still crashes on start up. Here is my latest log: 
[latest.log](https://github.com/AOCAWOL/BYG/files/11116759/latest.log)

**Comment by Calico-OS** [comment]
The crash is saying you're missing CorgiLib, which is not a listed dependency literally anywhere. However, even with the lib, it does not work anyway. It's nothing you're doing wrong, there's a deadly bug around somewhere.

**Comment by PearPlays** [comment]
have you got GeckoLib installed if not install it and you should be good to go

**Comment by jonask028** [comment]
Try deleting the overworld_enable.json5 config and the trades.json5 config. worked for me

**Comment by MC-Clutch** [comment]
I'm having the same issue on fabric 1.19.2 and I'm just using byg, fabric api, terrablender, and Gecko lib. This is affecting my new modpack a lot. Also, it was working before but now it crashes right when the Mojang loading screen comes up but there's no error in the Minecraft launcher, so something is wrong.

**Comment by UHQ-GAMES** [comment]
> I'm having the same issue on fabric 1.19.2 and I'm just using byg, fabric api, terrablender, and Gecko lib. This is affecting my new modpack a lot. Also, it was working before but now it crashes right when the Mojang loading screen comes up but there's no error in the Minecraft launcher, so something is wrong.

Make sure you have CorgiLib installed, newer versions of byg depend on it. If the crash persists open a separate issue with your crash log attached

**Comment by CorgiTaco** [comment]
You'll need Corgilib
