### ISSUE TITLE
[1.19][Bug]: white charry folliage doesnt always show 

### ISSUE THREAD

**Issue by xinsomniax** [CorgiTaco/BYG#1135]
### BYG Version

2.0.0.13

### Terrablender Version

2.0.1.136

### Mod Loader

Forge

### Mod Loader Version

43.2.6

### Bug Severity

Minor

### What happened?

when you place white carry foliage it is just invisible 

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/11174534/latest.log)

### Did you isolate BYG?

I did not try BYG alone

**Comment by CorgiTaco** [comment]
Works on my end. Probably an issue caused by another mod? Not sure: 



https://github.com/AOCAWOL/BYG/assets/66983020/d82761d3-1db2-4473-964e-15e69627a5ec
