### ISSUE TITLE
[1.19][Bug]: BYG registering woodtypes under Minecraft namespace

### ISSUE THREAD

**Issue by TelepathicGrunt** [CorgiTaco/BYG#1137]
### BYG Version

2.0.1

### Terrablender Version

2.0.1.136

### Mod Loader

Fabric

### Mod Loader Version

0.14.17

### Bug Severity

Major

### What happened?

When using BYG and Trails & Tails 1.20 mod together, the game gets stuck in a crash or bootloop and unable to actually start. The mod:
https://www.curseforge.com/minecraft/mc-mods/trails-and-tales-fabric

The issue in the logs states this:
`java.lang.IllegalArgumentException: Multiple entries with same key: minecraft:sign/cherry#main=net.minecraft.class_5607@65bb02e and minecraft:sign/cherry#main=net.minecraft.class_5607@65bb02e`
	
Which means both of these mods are trying to register their cherry woodtype under the Minecraft namespace instead of their own modid. In BYG, this line needs to change:
https://github.com/AOCAWOL/BYG/blob/d76dea49b5c9bef513addabed97f3ab2a0493262/Common/src/main/java/potionstudios/byg/common/block/BYGWoodTypes.java#L199

I notifying the other mod of this issue as well. Until either mod updates, the two mods are incompatible and cannot run together which is a big issue. Always register under your own modid to prevent this issue.

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/11185460/latest.log)

### Did you isolate BYG?

I tried BYG alone

**Comment by TelepathicGrunt** [comment]
Issue might also be present on Forge so double check there too that the modid is used for namespace instead of minecraft's

**Comment by CorgiTaco** [comment]
Needs to be fixed on 1.18 possibly... will leave open and labelled 1.18
