### ISSUE TITLE
[1.19][Crash]: Conflict with Geophillic

### ISSUE THREAD

**Issue by BrandonTheGod06** [CorgiTaco/BYG#1138]
### BYG Version

1.4.7

### Terrablender Version

2.0.1.136

### Mod Loader

Fabric

### Mod Loader Version

0.14.19

### What happened?

Game will crash whenever I try to load a new world or try to walk around in my already made world. Tried BYG standalone and it worked perfectly fine. Unsure of what mod is causing problems with BYG

### crash-log

https://gist.github.com/BrandonTheGod06/fe50e36833be6ad1f5882eec64d51258

### latest.log

https://gist.github.com/BrandonTheGod06/b32ce1a2bd53342d2e0b4fb27d788673

### Did you isolate BYG?

I tried BYG alone

**Comment by davidromrell** [comment]
#1151

**Comment by davidromrell** [comment]
#1165 seems a continuation but am unsure.

**Comment by CorgiTaco** [comment]
Fixed by Geophilic: https://www.curseforge.com/minecraft/mc-mods/geophilic/files/4526822
