### ISSUE TITLE
Rivers spawn in dead seas

### ISSUE THREAD

**Issue by DaddySpin** [CorgiTaco/BYG#114]
Rivers spawn in dead seas making them look very ugly.
![2020-10-12_10 54 52](https://user-images.githubusercontent.com/34575655/95766949-a2647200-0c79-11eb-859c-0afd36f1e715.png)

**Comment by CorgiTaco** [comment]
That's tough, and unfortunately out of our control.

**Comment by DaddySpin** [comment]
big rip

**Comment by DaddySpin** [comment]
would it be possible to make the dead sea act like a ocean? no biomes spawn in oceans.

**Comment by CorgiTaco** [comment]
Not possible as it is rn

**Comment by DaddySpin** [comment]
when do you think it will be possible, if ever?
