### ISSUE TITLE
[1.19][Crash]: Crash when generating a world 1.19.2 FABRIC

### ISSUE THREAD

**Issue by pokesmells** [CorgiTaco/BYG#1141]
### BYG Version

Oh_The_Biomes_You'll_Go-fabric-1.19.2-2.0.0.13

### Terrablender Version

TerraBlender-fabric-1.19.2-2.0.1.136

### Mod Loader

Fabric

### Mod Loader Version

0.14.19

### What happened?

Whilst generating a new world, I crashed.

### crash-log

[crash-2023-04-13_23.25.17-server.txt](https://github.com/AOCAWOL/BYG/files/11228799/crash-2023-04-13_23.25.17-server.txt)

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/11228801/latest.log)

### Did you isolate BYG?

Yes doing so works, but there are multiple mixins togo through

**Comment by PolyframeX** [comment]
Can reproduce on fabric port as well.

**Comment by CorgiTaco** [comment]
Fixed by Geophilic: https://www.curseforge.com/minecraft/mc-mods/geophilic/files/4526822
