### ISSUE TITLE
[1.19][Bug]: Crash related to sapling growth (I think) in 2.0.1.1 (CottageWitch modpack version 1.19-1.13.2)

### ISSUE THREAD

**Issue by riskable** [CorgiTaco/BYG#1142]
### BYG Version

2.0.1.1

### Terrablender Version

2.0.1.136

### Mod Loader

Forge

### Mod Loader Version

43.2.6

### Bug Severity

Major

### What happened?

Just chillin at my base and the server crashes.  No real rhyme or reason to it.  Not doing anything (staring at wall).

### latest.log

https://gist.github.com/riskable/cadce663d692a649b16b7c48b4e490b9

### Did you isolate BYG?

I tried BYG alone

**Comment by CorgiTaco** [comment]
Seems the block in question is unknown in the game registry as it cant retrieve the id for the block? Seems possible a block is registered without an id ie "minecraft:oak_sapling".... I'd recommend deleting the `growing-patterns.json5` config and restarting the game to have it regen.

**Comment by CorgiTaco** [comment]
Going to close this issue, please reopen this issue if the problem persists.
