### ISSUE TITLE
[1.19][Crash]: Game Crashes on Start when BYG and CorgiLib is used

### ISSUE THREAD

**Issue by deadgirl333** [CorgiTaco/BYG#1143]
### BYG Version

2.0.1.1

### Terrablender Version

2.0.1.136

### Mod Loader

Forge

### Mod Loader Version

43.2.0

### What happened?

Hi everytime I try to launch mc I get a instant crash report with this version of BYG. I also tried it with 1.4.7 version of BYG but instead of crashing on startup it would crash when joining/creating worlds. I have CorgiLib installed as well.

### crash-log

[biome crash.txt](https://github.com/AOCAWOL/BYG/files/11245226/biome.crash.txt)

### latest.log

[log.txt](https://github.com/AOCAWOL/BYG/files/11245239/log.txt)

### Did you isolate BYG?

I tried BYG alone

**Comment by deadgirl333** [comment]
I have corgilib, terrablender, and geckokib installed with it (edit: sorry didn't mean to close it, it's still open)

**Comment by Enderteck** [comment]
I got the same problem:

Forge 43.2.8. The version 2.0.1.1 doesn't work when installed with it's dependency with the mods shown in this log:

[latest.log](https://github.com/AOCAWOL/BYG/files/11260560/latest.log)

I have to use another version : Oh_The_Biomes_You'll_Go-forge-1.19.2-2.0.0.13.jar
https://legacy.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go/files/4027228

**Comment by MageKitty** [comment]
I am also having the exact same issue.

**Comment by davidromrell** [comment]
weird issue I keep having.

**Comment by shadow7483147** [comment]
Confirming too.

MC 19.2
Forge 43.2.8
BYG 2.0.1.1
CorgiLib 32
TerraBlender 2.0.1.136

[clipboard.txt](https://github.com/AOCAWOL/BYG/files/11278223/clipboard.txt)

**Comment by davidromrell** [comment]
A temp fix use:
BYG 2.0.0.13.jar

**Comment by darkequine** [comment]
I think I also had this same crash. Deleting my byg config folder and reloading fixed it for me.

**Comment by CorgiTaco** [comment]
You have configs that need to be deleted so the game can load properly, you can find instructions for how to do that for your game launcher here: https://github.com/AOCAWOL/BYG/wiki/Resetting-Configs
