### ISSUE TITLE
[1.18.2][Bug]: BYG tall grass types mesh incompatible with Shader effect wave

### ISSUE THREAD

**Issue by xFirefalconx** [CorgiTaco/BYG#1145]
### BYG Version

1.4.7

### Terrablender Version

1.2.0.126

### Mod Loader

Forge

### Mod Loader Version

40.2.0

### Bug Severity

Minor

### What happened?

I am adding blocks to a shader list to make them move in the wind and get extra lighting applied. They get distorted. Shader is called "Complementary Reimagined" and probably a bit known, applied using Oculus and Flywheel Compat, no, I cannot use Optifine, 40% of the other mods are incompatible with it. Let me know if you need links, it's not mine I just use it for my modpack.

I tested this with BYG:reed and BYG:tall_beach_grass now, and I am... frustrated. 

So a question: Do you have two separate meshes for the upper and the lower block? Can you fix this and make the meshes be... connected in some way, like the way they are in BOP, or with two block large plants in Untamed Wilds? They do work well with the shader so I believe it's a BYG problem in how the grass is created/the mesh is made.

The shader works like this (as far as I understand it, the devs might understand it better), it grabs the block type and then adds a block it is fixated on if there are two on top of each other. 
so I go byg:tall_beach_grass:half=lower - the shader then should go and pick the lower block, make it move and shade and apply the rest to the upper. 
For some reason, BYG grass doesn't do that. Not only one block, but at least two, at worst all tall grass type of blocks in the mod.

Look closely at this video. The upper and lower block act as if they're two different objects. 
This is ugly at best and frustrating at worst. 
https://user-images.githubusercontent.com/106652912/232937611-0b16cd83-e337-4a00-a707-9729da81de6e.mp4

I had to also set this to not pick a block at all because it would stop shading the other one and make it solid, as if the block was an other kind.

I picked minor but I strongly hope this gets fixed. Static tall grass with dull shading in a shader environment is just a sad sight to behold. 

If you don't understand, let me know. I am not good at describing sometimes. 

There is no relevant info in the latest.log so I cannot really provide anything useful here, but if you insist, here you go:

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/11267487/latest.log)

Since mods are needed to activate the shaders, it could be a dependency issue, but you hopefully understand what I mean. If it were impacting other mods, their grass would look like this everywhere, which is not the case. 

### Did you isolate BYG?

I tried BYG alone

**Comment by davidromrell** [comment]
I do not know if this is a mod-based situation, or a load-order situation. I would check load order.

**Comment by Sanriaa** [comment]
I use BSL shaders which has a similar wavy plant function. I can't speak for the shader you use, but for mine, tall plant blocks (ie any grass that has a lower and upper block attached to it) need 2 entries listed in the block configuration file. The first would be, in your example, byg:tall_beach_grass:half=lower. There's another section where you would write byg:tall_beach_grass:half=upper. That makes the blocks flow together, not like they're separate blocks. Hopefully this helps
