### ISSUE TITLE
Ukrainian Translation (100% translated)

### ISSUE THREAD

**Issue by Mark1ed** [CorgiTaco/BYG#1146]
### BYG Version

v2.0.1.1

### Terrablender Version

v2.0.1.136

### Mod Loader

Fabric

### Mod Loader Version

0.14.0

### Bug Severity

Major

### What happened?

The last 2 weeks i've been working on Ukrainian BYG Translation. Here's the file: [uk_ua.json (MediaFire)](https://www.mediafire.com/file/z1igrfhqrvv9kgt/uk_ua(remove+this).json/file). If possible, tag me as Markied in the mod description. Regarding the quality of the translation, everything is mostly fine. Since I am Ukrainian, the quality of the translations is perfect. But there were some problems with the quality of the fictional titles. I think that the translation turned out to be of high quality. If someone among Ukrainians finds a mistake in the translation, let me know! Contact me on one of these social networks: [LinkTree](https://linktr.ee/mark1ed)
![](https://user-images.githubusercontent.com/108518311/233003269-84fbb67a-8f7b-4e85-9df0-826db0b80ff4.png)
Due to the fact that I don't know how to use github, I don't know how to create a pull request, that's why I opened this issue, sorry. To translate all this I used a private project on Crowdin because it's more comfortable for me. And if you STILL don't know, there are no language files loaded on your [crowdin](https://crowdin.com/project/oh-the-biomes-youll-go) project. Just upload English file there. Because of this, translation of your mod through crowdin is impossible, so I created the project myself. And I also noticed some bugs (in fabric version): bucket of man o war isn't spawning man o war, man o war can't be taken from water to bucket, ores button in biomopedia is not working.

https://user-images.githubusercontent.com/108518311/233015064-aad156e0-5ebf-44a0-9a86-42eaf6fe29ef.mp4

### latest.log

.

### Did you isolate BYG?

I tried BYG alone

**Comment by Mark1ed** [comment]
@AOCAWOL please don't ignore

**Comment by Mark1ed** [comment]
@AOCAWOL hey???

**Comment by Mark1ed** [comment]
Is this project alive?

**Comment by CorgiTaco** [comment]
Added, ty for the contribution!
