### ISSUE TITLE
[1.19][Bug]: Crash on world startup

### ISSUE THREAD

**Issue by PolyframeX** [CorgiTaco/BYG#1147]
### BYG Version

2.0.1.1

### Terrablender Version

2.0.1.136

### Mod Loader

Fabric

### Mod Loader Version

0.14.19

### Bug Severity

Major

### What happened?

When loading a single player world, the game will get stuck and then crash. This is most likely a mod incompatibility.

### latest.log

https://pastebin.com/ZxHa37JC

### Did you isolate BYG?

I tried BYG alone

**Comment by PolyframeX** [comment]
Issue is duplicate, this is an incompatibility with CorgiLib

**Comment by PolyframeX** [comment]
May be a duplicate of #1141 but I am not sure.

**Comment by davidromrell** [comment]
https://github.com/AOCAWOL/BYG/issues/1151 same issue and same with #1141

**Comment by PolyframeX** [comment]
Mentioning all issues related to it here to keep track easily, specifically open issues.
#1141, #1138, #1152, and potentially #1119.

**Comment by D3SL** [comment]
I took a look and it seems like almost all of us are getting a feature cycle error with BYG's araucaria_savanna biome. The only common mods between all of us I believe are some of the abnormals mods, possibly Biome Makeover, and the Yung's set. There's also one involving some nether biomes.

**Comment by davidromrell** [comment]
Biome Makeover is one of the conflicts, from my experience Yung mods don't tend to conflict with other mods unless said other mods are badly coded. I have had mixed experiences on abnormals mods so it could be them.

**Comment by PolyframeX** [comment]
I tested byg and biome makeover together and the game did not crash, so I'm not sure if it is Biome makeover. Since there are no issues with them alone.

I even went to the bugged biome. No issues can be found.

**Comment by davidromrell** [comment]
apparently, it seems like a mod other than listed that effects generation, which is odd cause he seems to have put in time to find out.

**Comment by PvtSkittles34** [comment]
I deactivated all abnormals mods, seasons mod, biome makeover, yungs mods, and all mods that add new structures, dungeons, or buildings to the overworld (or otherwise "touch up" on biomes) and still get the same issue so it doesnt seem to be one of those. Havent tried ones that add new stuff to the End or Nether or other dimensions yet though.

Edit: I tried simply taking the BetterMinecraft (BMC3) prebuilt Modpack and editing it to add the tech mods I wanted and am having no problems despite it using almost all the exact same mods from my custom built pack. The biggest differences was I left out some of the lesser clientside cosmetic things like fancy menu and some of the mods that allow you to make teams and such as it would just be my girlfriend and I playing. not sure if any of those would affect worldgen...

**Comment by davidromrell** [comment]
> I deactivated all abnormals mods, seasons mod, biome makeover, yungs mods, and all mods that add new structures, dungeons, or buildings to the overworld (or otherwise "touch up" on biomes) and still get the same issue so it doesnt seem to be one of those. Havent tried ones that add new stuff to the End or Nether or other dimensions yet though.
> 
> Edit: I tried simply taking the BetterMinecraft (BMC3) prebuilt Modpack and editing it to add the tech mods I wanted and am having no problems despite it using almost all the exact same mods from my custom built pack. The biggest differences was I left out some of the lesser clientside cosmetic things like fancy menu and some of the mods that allow you to make teams and such as it would just be my girlfriend and I playing. not sure if any of those would affect worldgen...

In the case you have its likely geophilic.

**Comment by D3SL** [comment]
I took the logs from all the 1.19 feature order cycle crash issues (1138, 1139, 1141, 1147, 1152, 1155) and put together a table of every mod they all have as well as every biome involved.

Out of 6 tickets byg:araucaria_savanna shows up in 5 and minecraft:windswept_savanna in 4. 
For mods davidromrell seems to have nailed it. Only BYG itself, fastload, geckolib, and terrablender show up in all 6 logs. Of the things that show up in 5/6 logs the only ones that aren't libraries are Biome Makeover and Geophilic.

Alternatively one of us could've just read the comments on curseforge for geophilic and seen that somebody else figured this out a week ago and even posted about it in #1151. Geophilic's author is already working on a fix.

The one outlier is 1139 which already narrowed it down to an incompatibility between BYG and Better End.



[Table of the data](https://github.com/AOCAWOL/BYG/files/11358226/byg.feature.order.cycle.tables.ods)

**Comment by PolyframeX** [comment]
#1155 new issue, probally the same bug.

**Comment by davidromrell** [comment]
is same issue similar bug.

**Comment by PolyframeX** [comment]
(My bad, I realized the issue was already mentioned)

**Comment by Withevilintent** [comment]
Have you tried using an older version of geophilic? It fixed the issue for myself and it might be worth a try.

**Comment by PolyframeX** [comment]
I've tried and still had the issue, what version did you use?

**Comment by Withevilintent** [comment]
it was on the 1.19-2.0.0 from 4/9 and I just went to the one under it 1.19-1.2.2 from 3/6. But I failed to notice that you're using fabric and I'm running forge. My bad.

**Comment by PolyframeX** [comment]
Ah okay.

**Comment by CorgiTaco** [comment]
Fixed by Geophilic: https://www.curseforge.com/minecraft/mc-mods/geophilic/files/4526822
