### ISSUE TITLE
[1.19][Bug]: 1.19.2 Forge- Nether and End trees not generating

### ISSUE THREAD

**Issue by RechercheRaptor** [CorgiTaco/BYG#1148]
### BYG Version

1.19.2-2.0.1.0

### Terrablender Version

1.19.2-2.0.1.130

### Mod Loader

Forge

### Mod Loader Version

43.2.0

### Bug Severity

Major

### What happened?

I was trying to see if BYG's End biomes were compatible with Enlightend and Unusual End. I created a new Forge profile with these mods, and didn't see any Enlightend biomes, so I tried going into BYG's End biome config file to reduce the frequency of some BYG End biomes. In the next world I generated, none of BYG's End biomes had any trees. The nylium/phyliums were still generating and the biome tags were still visible in F3, but none of the tree types were generating. I restored the original config settings and tried again, but got the same error. I also checked the Nether at this time and didn't see any trees in the Embur Bog, Wailing Garth, Weeping Mire, Sythian Torrids, etc.

I then tried disabling Enlightend and Unusual End one at a time, and then both, but this didn't seem to change anything. I then went to another launcher that already had BYG installed (same versions) and made a new world, and still couldn't get BYG trees to generate in the End or Nether. Tree generation for BYG is normal in the Overworld. Eventually I made a new launcher with only BYG and Terrablender, with the versions listed above, but I still can't get Nether or End BYG trees to generate. Vanilla Nether trees (Crimson and Warped fungus) still generate. World type (Superflat or normal) doesn't make a difference (I'd made the first world that had both BYG and Enlightend in a normal world and done my other tests in Superflat, so I thought there might have been a bug there, but no dice). I'm really confused because I know I was getting BYG biomes generating properly just the other day, but now even when I delete and re-install the mod (and make sure the config files are all default), I keep getting this same error over and over.

### latest.log

/*
This file uses the ".json5" file extension which allows for comments like this in a json file!
Your text editor may show this file with invalid/no syntax, if so, we recommend you download:

VSCode: https://code.visualstudio.com/
JSON5 plugin(for VSCode): https://marketplace.visualstudio.com/items?itemName=mrmlnc.vscode-json5

to make editing this file much easier.

If your settings in this file seem to have to no effect on the generation of the end, it is more than likely that another mod(s) related to the end has taken control instead, and you should user their config.
*/
{
	// Does this config automatically fill with all biomes using the "the_end" biome category? Note: Vanilla at the time of writing does not have an end biomes tag.
	"addAllEndBiomeCategoryEntries": true,
	/* Is BYG's End Biome Source used?
	   BYG's end biome source will automatically add all known end biomes that specify their biome category as "the_end", see "addAllEndBiomeCategoryEntries" comment.
	*/
	"forceBYGEndBiomeSource": true,
	// Biomes that spawn where the large end islands/surface generate.
	"islandLayer": {
		"biomeSize": 4,
		/* Higher weight, means the biome in question is bound to spawn more frequently against all other biomes listed here.
		   Weight of 0 means the biome is disabled.
		   
		   "data" should be a valid biome ID from vanilla, mods, or datapacks.
		   If the biome in question is not in the biome registry, the biome is ignored & logged in the "latest.log".
		*/
		"biomeWeights": [
			{
				"data": "minecraft:end_midlands",
				"weight": 2
			},
			{
				"data": "minecraft:end_barrens",
				"weight": 2
			},
			{
				"data": "minecraft:end_highlands",
				"weight": 2
			},
			{
				"data": "byg:ivis_fields",
				"weight": 1
			},
			{
				"data": "byg:nightshade_forest",
				"weight": 3
			},
			{
				"data": "byg:ethereal_islands",
				"weight": 3
			},
			{
				"data": "byg:bulbis_gardens",
				"weight": 3
			},
			{
				"data": "byg:shulkren_forest",
				"weight": 3
			},
			{
				"data": "byg:cryptic_wastes",
				"weight": 1
			},
			{
				"data": "byg:imparius_grove",
				"weight": 3
			},
			{
				"data": "minecraft:small_end_islands",
				"weight": 0
			},
			{
				"data": "byg:viscal_isles",
				"weight": 0
			},
			{
				"data": "minecraft:the_end",
				"weight": 0
			}
		]
	},
	// Biomes that spawn in the Y range of "skyLayerStartY to Dimension Max Y.
	"skyLayer": {
		"biomeSize": 3,
		/* Higher weight, means the biome in question is bound to spawn more frequently against all other biomes listed here.
		   Weight of 0 means the biome is disabled.
		   
		   "data" should be a valid biome ID from vanilla, mods, or datapacks.
		   If the biome in question is not in the biome registry, the biome is ignored & logged in the "latest.log".
		*/
		"biomeWeights": [
			{
				"data": "byg:viscal_isles",
				"weight": 1
			},
			{
				"data": "minecraft:the_end",
				"weight": 9
			}
		]
	},
	"skyLayerStartY": 180,
	// Biomes that spawn where there is no ground aka void.
	"voidLayer": {
		"biomeSize": 3,
		/* Higher weight, means the biome in question is bound to spawn more frequently against all other biomes listed here.
		   Weight of 0 means the biome is disabled.
		   
		   "data" should be a valid biome ID from vanilla, mods, or datapacks.
		   If the biome in question is not in the biome registry, the biome is ignored & logged in the "latest.log".
		*/
		"biomeWeights": [
			{
				"data": "minecraft:small_end_islands",
				"weight": 2
			}
		]
	}
}

### Did you isolate BYG?

I tried BYG alone

**Comment by RechercheRaptor** [comment]
The issue persists even when I switch to BYG version 1.19.2-2.0.1.1 and Terrablender version 1.19.2-2.0.1.136

**Comment by RechercheRaptor** [comment]
Okay, been doing some more testing and it seems like it's actually a Terrablender problem and not a BYG problem. 

Terrablender beta 1.19.2-2.0.1.130 and Terrablender release 1.19.2-2.0.1.136 don't generate any of the BYG flora (or crystal clusters such as in the Subzero Hypogeal) in the Nether or End.

Terrablender beta 1.19.2-2.0.1.129 and Terrablender release 1.19.2-2.0.1.128 DO properly generate BYG flora. I haven't tested any earlier versions.

**Comment by Kiro-D-P1R4T3** [comment]
1.18.2 trees are also not generating in the nether and the end
tried every version of Terrablender for 1.18.2, nothing
