### ISSUE TITLE
Obsidian spires not spawning in Ivis Fields

### ISSUE THREAD

**Issue by DaddySpin** [CorgiTaco/BYG#115]
The obsidian spires are not spawning in the ivis fields.
![2020-10-12_12 46 40](https://user-images.githubusercontent.com/34575655/95776004-18bca080-0c89-11eb-88b5-d2286ee96167.png)

**Comment by AOCAWOL** [comment]
this is being fixed in our latest content update 1.1 which comes out October 31st :D along with fixing the spires, they've also been revamped along with the biome itself.
