### ISSUE TITLE
[1.19][Bug]: Biomes generating improperly.

### ISSUE THREAD

**Issue by Frutiger-AER0** [CorgiTaco/BYG#1150]
### BYG Version

1.4.7

### Terrablender Version

2.0.1.136

### Mod Loader

Forge

### Mod Loader Version

43.2.0

### Bug Severity

Major

### What happened?

I was troubleshooting issues with my world generation, as I had been having trouble before this, and after it loaded up I was met with Biomes with no Trees or anything else, just the grass color being changed and that's it. That being said I am using a lot of different mods, but I'm not sure if any of them should be impacting BYG like this or how it even would do this. Maybe this can help discover an incompatibility maybe?

I'm not even sure what would cause this. But I'd like to know, It's just very peculiar. I did check and every overworld biome was just like this, Not sure about Nether or End biomes.
![huh](https://user-images.githubusercontent.com/82814439/233638631-ef183e86-91fa-43b7-b78a-7c81d153fe89.png)

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/11295773/latest.log)

### Did you isolate BYG?

I did not try BYG alone

**Comment by Frutiger-AER0** [comment]
After looking down the issue tracker more for similar issues, I've seen that people have had this same issue with the Nether and End biomes as of late. I haven't seen anyone comment on their state of their overworld biomes, but it could be related.

**Comment by Frutiger-AER0** [comment]
Upon further discovery I've learned this is an issue with Terrablender.

**Comment by davidromrell** [comment]
#1151 if you still need help

**Comment by Frutiger-AER0** [comment]
It's a similar issue, though I wasn't experiencing any crashes. Thank you for notifying though.
