### ISSUE TITLE
[1.19][Bug]: java.lang.IllegalStateException: Feature order cycle found

### ISSUE THREAD

**Issue by Zarepheth** [CorgiTaco/BYG#1151]
### BYG Version

2.0.0.13

### Terrablender Version

2.0.1.136

### Mod Loader

Fabric

### Mod Loader Version

0.14.19

### Bug Severity

Major

### What happened?

Was exploring my single player world, in the overworld. The game hung and after telling Windows to close the game so I could review the logs and try again, the logs had the error in this report's title.

I am playing on a customized version of the "Medieval MC [FABRIC] - MMC1", v20.5 mod pack by SHXRKIE. I say customized because I've manually updated most outdated mods and added several mods of my own choosing while disabling one mod. And if I'm doing that, you can be sure I'm also adjusting the config files for my own preferences.

The first time the game crashed, I was riding a flying mount, "Mythic Mounts".
The second time the game crashed I was walking overland towards the same region as the first crash, but from another direction.
Both crashes has the same error.

Due to the nature of the error and what would happen to my world if I attempted BYG alone, I did not try it separately.

### latest.log

[Crash Log](https://gist.github.com/Zarepheth/b769977355e25d35143f3cdbfe5332bd)

[Full Log](https://gist.github.com/Zarepheth/c195d7bec9a1478a72abb9e4372d6cb5)

### Did you isolate BYG?

I did not try BYG alone

**Comment by Zarepheth** [comment]
This is likely a mod compatibility issue, so I've also posted this at https://github.com/TerraformersMC/Terrestria/issues/299

**Comment by Zarepheth** [comment]
This issue may be the same as https://github.com/AOCAWOL/BYG/issues/1119, but since that was for a different Minecraft version, I made a separate report.

**Comment by Zarepheth** [comment]
I made another test after letting BYG, Terrablender, and Terrestria recrate their config files. I approached the same area on land, from a third direction and thought maybe things are working, as Journey Map was expanding into previously dark areas. Shortly after mounting my griffon and heading north, the game hung and crashed. 😢 

1st crash, I was flying east toward an unexplored section of the world.
2nd crash, I walked west toward that same area.
3rd crash, I walked north toward that area, then suffered a crash one or two chunks north of the structure with multiple glass domes.

Most recent crash:
[crash-2023-04-22_16.32.28-server.txt](https://github.com/AOCAWOL/BYG/files/11302354/crash-2023-04-22_16.32.28-server.txt)

Although I was in different places for each crash, the crash reports all indicate that the same chunk was about to be generated when the crash occurred.

**Comment by davidromrell** [comment]
any biome modifying or generating mods such as geophilic will have soft or hard compat issues.

**Comment by Zarepheth** [comment]
I'm pretty sure that all the biome modifying/generated mods were part of the original modpack. Perhaps I need to downgrade the updated mods back to the modpack's original versions? Know of any tools that can quickly point out which mods in my customized profile are different from the modpack's mods?

And I just had the same crash happen a 4th time, but a different part of the world, so a different chunk is erring out.

**Comment by Zarepheth** [comment]
I downgraded Geophilic from 2.0.0 to 1.2.2.  This fixed the places where I was having a crash.

Looks like that mod's author should look into this issue...
