### ISSUE TITLE
[1.19][Crash]: Crash during worldgen "Exception generating new chunk"

### ISSUE THREAD

**Issue by PvtSkittles34** [CorgiTaco/BYG#1152]
### BYG Version

2.0.0.13

### Terrablender Version

2.0.1.136

### Mod Loader

Forge

### Mod Loader Version

43.2.8

### What happened?

Created a modpack based off BetterMinecraft+ (BMC3), but going to add in some tech mods into it

...working through the bugs and crashes. I have turned off all additional mods not in BMC3 that I added myself and fixed all other issues except with byg it seems. When running worldgen, the progress % stays at 0 as it creates the grey box on the screen then crashes. 

There is possibly a confliction with another mod but when I run the official BMC3 pack there's no issue... when I run byg alone there's no issue. But When I run my modpack it throws an error that is identical every time. I am not a programmer, but I tried sifting through the crash logs myself and cannot see an obvious other mod causing byg issues when it tries to generate the savanna biomes.

When I disable BYG and terrablender my modpack works fine now.

I am hoping a pair of more experienced eyes can help me figure it out... Because I always have loved byg in my past playthroughs of minecraft

### crash-log

[crashreport2.txt](https://github.com/AOCAWOL/BYG/files/11304030/crashreport2.txt)

### latest.log

[latest2.txt](https://github.com/AOCAWOL/BYG/files/11304031/latest2.txt)

### Did you isolate BYG?

I tried BYG alone

**Comment by PolyframeX** [comment]
Seems to be same issue as #1147, #1141, and #1138.

**Comment by Withevilintent** [comment]
If you have geophilic try going to an older version of it. Had this same problem and that seemed to fix it.

**Comment by CorgiTaco** [comment]
Fixed by Geophilic: https://www.curseforge.com/minecraft/mc-mods/geophilic/files/4526822
