### ISSUE TITLE
[1.16][Crash]: Client Crash when crouching and looking at overgrown stone blocks

### ISSUE THREAD

**Issue by asdfjkll2** [CorgiTaco/BYG#1154]
### BYG Version

1.3.6

### Mod Loader

Forge

### Mod Loader Version

36.2.34

### What happened?

When looking at any overgrown stone block and crouching (with the shift key), the game crashes in singleplayer worlds. In multiplayer worlds, the player is kicked from the server with internal server error but can rejoin, the server itself does not crash. I am not sure which mods are triggering the crash (which only seems to happen with overgrown blocks), as this crash does not occur with BYG on its own.

### crash-log

[crash-2023-04-24_15.00.20-server.txt](https://github.com/AOCAWOL/BYG/files/11314217/crash-2023-04-24_15.00.20-server.txt)

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/11314213/latest.log)

### Did you isolate BYG?

I tried BYG alone

**Comment by AOCAWOL** [comment]
Unfortunately, we are no longer supporting 1.16 issues at the moment so I am going to close this issue, please use latest builds for more stable experiences
