### ISSUE TITLE
[1.19][Crash]: Crash during world generation "Exception generating new chunk"

### ISSUE THREAD

**Issue by LegitGamer1017** [CorgiTaco/BYG#1155]
### BYG Version

2.0.0.13

### Terrablender Version

2.0.1.136

### Mod Loader

Forge

### Mod Loader Version

43.2.8

### What happened?

I have a personal server for me and my friends, and everything is fine until it's trying to generate the world, it freezes the server and I have to manually kill the server. I think this might be due to some mod incompatibility but looking at the logs doesn't really help narrow down which mod causes it. I don't think I have any mods that overhauls worldgen/biomes either. I've also resetted my configs for BYG, but the same issue still occurs. 

This looks like a similar issue to #1141, #1138, #1152 

### crash-log

[crash-2023-04-25_05.01.17-server.txt](https://github.com/AOCAWOL/BYG/files/11326732/crash-2023-04-25_05.01.17-server.txt)

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/11326551/latest.log)

### Did you isolate BYG?

I tried BYG alone

**Comment by davidromrell** [comment]
Biome makeover is the issue in this case. I expect, after you remove Biome makeover, geophilic to have an issue.

**Comment by CorgiTaco** [comment]
Fixed by Geophilic: https://www.curseforge.com/minecraft/mc-mods/geophilic/files/4526822
