### ISSUE TITLE
[1.19][Crash]: 

### ISSUE THREAD

**Issue by TopTrent** [CorgiTaco/BYG#1156]
### BYG Version

Oh_The_Biomes_You'll_Go-forge-1.19.2-2.0.1.1.jar

### Terrablender Version

TerraBlender-forge-1.19.2-2.0.1.136.jar

### Mod Loader

Forge

### Mod Loader Version

43.2.0

### What happened?

Game is crashing when loading up new single player world.

### crash-log

[crash-2023-04-25_17.52.23-server.txt](https://github.com/AOCAWOL/BYG/files/11327147/crash-2023-04-25_17.52.23-server.txt)

### latest.log

[2023-04-25-7.log.gz](https://github.com/AOCAWOL/BYG/files/11327152/2023-04-25-7.log.gz)

### Did you isolate BYG?

I did not try BYG alone

**Comment by AOCAWOL** [comment]
Please try resetting your configs, I will be closing this issue until BYG is attempted in an isolated environment with its required dependencies

**Comment by TopTrent** [comment]
> 

I did try resetting my configs before posting the issue. I just tried byg alone and it did work. However, once I added the other mods back into the pack, it crashed again on world creation. Here is the crash report.
[crash-2023-04-28_14.43.11-server.txt](https://github.com/AOCAWOL/BYG/files/11356466/crash-2023-04-28_14.43.11-server.txt)

**Comment by TopTrent** [comment]
Solution:
It is a problem with the mod Geophilic version 2.0.0
Previous version Geophilic 1.2.2 works.
