### ISSUE TITLE
[1.18][Bug]: Biome Overworld Config missing

### ISSUE THREAD

**Issue by TheStardustWitch** [CorgiTaco/BYG#1157]
### BYG Version

1.4.2

### Terrablender Version

1.2.0.126

### Mod Loader

Forge

### Mod Loader Version

40.2.0

### Bug Severity

Major

### What happened?

Missing config for overworld biomes. Byg.overworld.biomes.json5 just contains blank regions, there’s no way to disable individual biomes. 

### latest.log

N/a

### Did you isolate BYG?

I did not try BYG alone

**Comment by AOCAWOL** [comment]
Please update your BYG to a later 1.18.2 build 1.4.2 is outdated. Also make sure you have the required dependencies and try BYG alone with its dependencies and be sure to delete configs and let the regenerate when you use a later version
