### ISSUE TITLE
[1.19][Crash]: internal exception com.google.gson.jsonparseexception: don't know how  to turn {} into a component

### ISSUE THREAD

**Issue by akalazylord** [CorgiTaco/BYG#1158]
### BYG Version

2.0.0.7

### Terrablender Version

2.0.0.120

### Mod Loader

Forge

### Mod Loader Version

41.1.0

### What happened?

i playing last day i'll go fight with a zombie and suddenly a black screen when i wan't to relaunch my game i receive this error internal exception com.google.gson.jsonparseexception: don't know how  to turn {} into a component so try to see some people on forge tell me it's come frome more villagers mod i delete this mod and his config but same error i don't now why but i supposed a mod gave me an empty object from BYG and it's make my game crash

### crash-log

the first crash: https://pastebin.com/xsuWhYa5

and the last after i delete BYG and More villager: https://pastebin.com/CzEsDjWT

### latest.log

https://gist.github.com/akalazylord/80f48637a565f7433466717d34470bf9

### Did you isolate BYG?

I tried BYG alone

**Comment by davidromrell** [comment]
create a new minecraft instance with modlist except BYG and More villager. Then see if it happens again. If it does add new logs.

**Comment by CorgiTaco** [comment]
You have configs that need to be deleted so the game can load properly, you can find instructions for how to do that for your game launcher here: https://github.com/AOCAWOL/BYG/wiki/Resetting-Configs
