### ISSUE TITLE
[1.19][Bug]: New biomes are very rare and small

### ISSUE THREAD

**Issue by marybrown123** [CorgiTaco/BYG#1159]
### BYG Version

Latest

### Terrablender Version

Latest

### Mod Loader

Fabric

### Mod Loader Version

0.14.19

### Bug Severity

Minor

### What happened?

Biomes from the mod apears very rarely and they are smaller than minecraft biomes, when i explore world, there are only plains and forest :(

### latest.log

There is No log

### Did you isolate BYG?

I did not try BYG alone

**Comment by IdleSolution** [comment]
same problem on fabric on darkRPG modpack

**Comment by davidromrell** [comment]
I may be wrong but I dont think is directly from BYG. I believe newer versions of Minecraft have smaller biomes by default.

**Comment by CorgiTaco** [comment]
This is a side effect of 1.18+ world gen
