### ISSUE TITLE
[1.19][Bug]: 

### ISSUE THREAD

**Issue by raincloudfairy** [CorgiTaco/BYG#1160]
### BYG Version

2.0.1.1

### Terrablender Version

2.0.1.136

### Mod Loader

Forge

### Mod Loader Version

43.2.0

### Bug Severity

Major

### What happened?

Hi! I'm having issues trying to figure out how to disable specific BYG overworld biomes. I seem to be missing the biome weight part of the config, my BYG nether config file has it and I was able to disable what I wanted on that one, but the overworld config doesn't. 
I already tried resetting my config & BYG alone but no luck. 
![Screenshot 2023-05-02 102101](https://user-images.githubusercontent.com/132385169/235738701-0e6196bc-c8d4-46b8-b784-e004a0de3e94.png)
![Screenshot 2023-05-02 102207](https://user-images.githubusercontent.com/132385169/235738881-9f541eae-dd2d-4b8e-81b3-23c97cf12672.png)

### latest.log

N/A

### Did you isolate BYG?

I tried BYG alone

**Comment by CorgiTaco** [comment]
Please join the discord for questions regarding configs: https://discord.gg/zQA4eez2eS
