### ISSUE TITLE
[1.19][Bug]: Crash-Bug Overworld config and Terrablender error

### ISSUE THREAD

**Issue by notIkibo** [CorgiTaco/BYG#1161]
### BYG Version

1.19.2 2.0.1.1

### Terrablender Version

2.0.1.130 or 136 (Beta)

### Mod Loader

Fabric

### Mod Loader Version

0.14.19

### Bug Severity

Major

### What happened?

It crashes.

Somehow terrablender and byg config seem to be the problem though I don't know in what way this overworld config causes errors and how I should configurate it or why it's related on MC crashing.
Questions over questions.

### latest.log

https://paste.atlauncher.com/view/0dc0c645-f96a-4ec1-a84c-f8e029a11e5d

### Did you isolate BYG?

I did not try BYG alone

**Comment by CorgiTaco** [comment]
You have configs that need to be deleted so the game can load properly, you can find instructions for how to do that for your game launcher here: https://github.com/AOCAWOL/BYG/wiki/Resetting-Configs
