### ISSUE TITLE
[1.18][Bug]: Cherry Blossom Falling Leafs inside estructures

### ISSUE THREAD

**Issue by Ver1ne** [CorgiTaco/BYG#1162]
### BYG Version

1.4.7

### Terrablender Version

1.2.0.126

### Mod Loader

Forge

### Mod Loader Version

40.1.86

### Bug Severity

Minor

### What happened?

I started building a house in the cherry blossom biome, and as expected, falling leaf particles would get inside the house during construction. However, once the structure was completed and fully sealed, leaf particles continue to appear inside. I´ve tried restarting the game, uninstalling and reinstalling the mod, updating, but so far nothing has worked. I have a considerable amount of other mods loaded into the game, but this hadn't happened to me in other versions/worlds.
Even though it's a minor issue, it's annoying and illogical to have leaves flying inside the house hahaha. Any help would be appreciated!

### latest.log

https://gist.github.com/Ver1ne/3320d31d0cc7610c18861e4527f2120f

### Did you isolate BYG?

I did not try BYG alone

**Comment by CorgiTaco** [comment]
This is fixed on 1.19, will be back-ported to 1.18 soon. Fixed in 1.19: https://github.com/AOCAWOL/BYG/commit/9b92bfb5b76df4cdaa2b9ef7f1c7eebc92f53bce
