### ISSUE TITLE
[1.19][Crash]: Config Crash

### ISSUE THREAD

**Issue by Raiyna** [CorgiTaco/BYG#1164]
### BYG Version

1.19.2-2.0.1.0/2.0.1.1

### Terrablender Version

1.19.2-2.0.1.136

### Mod Loader

Fabric

### Mod Loader Version

0.76.0+1.19.2

### What happened?

Using ATLauncher, I updated mods that needed it via the mod list. BYG was one of them that I found after trial-and-error disable/enabling mods.  I kind of noticed in the crash log that BYG was mentioned, but I'm not very good at reading crash logs.  It should also be noted that after uninstalling and re-installing BYG to the 1.19.2-2.0.0.13 version and playing, my preexisting world was having trouble loading new chunks in conjunction with mods like Terrestria.  I will include that crash log as well.

After completely removing the ATLauncher instance of Better Minecraft (Fabric) and reinstalling it,  I started a new world and it runs fine.  The Better Minecraft (Fabric) modpack doesn't have any of the recent mod updates for some, which is why it runs fine.

### crash-log

1.19.2-2.0.1.1 (beta) crash log:  https://gist.github.com/Raiyna/c9f6594c6b6207165816f9922feb500b

1.19.2-2.0.0.13 crash log:  https://gist.github.com/Raiyna/d25399ba400780afcd1cf9fb2b144376

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/11416216/latest.log)

### Did you isolate BYG?

I did not try BYG alone

### Did you read and understand the above agreement?

- [X] I agree.

**Comment by CorgiTaco** [comment]
You have configs that need to be deleted so the game can load properly, you can find instructions for that here: https://github.com/AOCAWOL/BYG/wiki/Resetting-Configs
