### ISSUE TITLE
[1.19.2][Crash]: Game crashes on generation of a feature called minecraft:ruined_portal_mountain

### ISSUE THREAD

**Issue by WillouwCode** [CorgiTaco/BYG#1165]
### BYG Version

2.0.1.1 and 2.0.1.0 and 2.0.0.13

### Terrablender Version

1.19.2-2.0.1.136

### Mod Loader

Fabric

### Mod Loader Version

0.14.19

### What happened?

I was exploring a world and got to a giant mesa biome and then the game crashed. I tried rolling back to an earlier version of BYG 2 times thats why it is there for 3 versions. I also tried resetting the chunk and resetting the config files but nothing seems to help.

### crash-log

[crash-2023-05-07_21.32.53-server.txt](https://github.com/AOCAWOL/BYG/files/11430305/crash-2023-05-07_21.32.53-server.txt)

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/11430311/latest.log)

### Did you isolate BYG?

I did not try BYG alone

### Did you read and understand the above agreement?

- [X] I agree.

**Comment by WillouwCode** [comment]
[2023-05-07-7.log.gz](https://github.com/AOCAWOL/BYG/files/11430463/2023-05-07-7.log.gz)
just adding this log file as well since latest doesn't show the issue

**Comment by CorgiTaco** [comment]
I'd say try and figure out if this is a BYG exclusive issue or caused by some other mod. I highly doubt BYG is responsible for this crash tbh

**Comment by WillouwCode** [comment]
I will test with just BYG and let you know what i find :). If it makes a difference it is on a server and not locally.

**Comment by CorgiTaco** [comment]
@WillouwCode Any updates?

**Comment by WillouwCode** [comment]
I haven't had the chance to check it so ill close it as its not that big an issue for me anymore. It is possible that it could have been loot related and not the generation itself.
