### ISSUE TITLE
[1.19][Bug]: exit code 1

### ISSUE THREAD

**Issue by scooterwackyruler** [CorgiTaco/BYG#1166]
### BYG Version

1.19.2-2.0.1.1

### Terrablender Version

1.19.2-2.0.1.136

### Mod Loader

Forge

### Mod Loader Version

43.2.11

### Bug Severity

Major

### What happened?

i press play in the mc launcher, it loads, and gives me the exit code 1 screen before even opening the game. i have no idea why this is happening ive deleted just about everything in my configs folder, have tried it with only the mod+terrablender, deleted and redownloaded the mod files but nothing will even let me into the game

### latest.log

[launcher_log.txt](https://github.com/AOCAWOL/BYG/files/11445707/launcher_log.txt)

### Did you isolate BYG?

I tried BYG alone

### Did you read and understand the above agreement?

- [X] I agree.

**Comment by CorgiTaco** [comment]
I need the crash log not the launcher log

**Comment by scooterwackyruler** [comment]
o mb, but i checked and it doesnt seem to even create a crash log, it only gives me the "exit code 1" screen and nothing else

**Comment by scooterwackyruler** [comment]
oh wait hold on i looked at the github page theres like these two dependancies for 1.19.2 that i have never seen listed anywhere until now let me try adding these and see if that was it

**Comment by scooterwackyruler** [comment]
alright yeah that was it, sorry for creating this when it was only that but the dependancies should really be like somewhere more like obvious maybe on the curseforge page rather than only on the github that most people probably wont look at
