### ISSUE TITLE
[1.19][Bug]: The Ametrine and Pendorite tools are same/worse than Netherite on Fabric

### ISSUE THREAD

**Issue by ghost** [CorgiTaco/BYG#1168]
### BYG Version

2.0.1.1

### Terrablender Version

2.0.1.136

### Mod Loader

Fabric

### Mod Loader Version

0.14.19

### Bug Severity

Major

### The Ametrine Armor's protection level seems to be the same as Netherite, which makes the armor actually worse than Netherite because of the lack of Knockback Resistance. (only positive point is durability)
![image](https://github.com/AOCAWOL/BYG/assets/71410827/4717a068-f3e3-42ff-b938-348fbc1a0177)
![image](https://github.com/AOCAWOL/BYG/assets/71410827/7e37b143-7b62-4b65-8b74-c98df4b0ac9e)
*(Used the chestplate as example, but all other armors are also worse than netherite.)*

### The Pendorite Tools seem to follow the same problem, they break stone as fast as netherite tools and deal same damage as netherite, which makes the upgrade simply useless for the swords, only changing durability.
![image](https://github.com/AOCAWOL/BYG/assets/71410827/c09ffef2-c74c-47ff-a537-04b781f24516)
![image](https://github.com/AOCAWOL/BYG/assets/71410827/1227b6cd-b14d-45ac-a70c-3404aa2ce6c8)
*(Again, swords are the example, but other tools also are simply the same as netherite)*

*(This bug severely impacts the modded gameplay's armor progression by rendering upgrades **basically useless**, which makes players not need to explore biomes to find specific materials like Ametrine, Raw Pendorite or Emeraldite, which is the reason I marked it as a major severity bug.)*

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/11470088/latest.log)

### Did you isolate BYG?

I tried BYG alone

### Did you read and understand the above agreement?

- [X] I agree.

**Comment by CorgiTaco** [comment]
This is intentional design as of right now.
