### ISSUE TITLE
[1.19][Bug]: Missing mushrooms in mushroom tag

### ISSUE THREAD

**Issue by cech12** [CorgiTaco/BYG#1173]
### BYG Version

2.0.1.1

### Terrablender Version

2.0.1.136

### Mod Loader

Forge

### Mod Loader Version

43.2.10

### Bug Severity

Minor

### What happened?

Some mushrooms (Death Cap, Sythian Fungus, Soul Shroom) of your mod are not listed in the `forge:mushrooms` item tag. This causes an incomaptibility with the mod Extended Mushrooms, that they cannot be used to buildup a fairy ring.

Steps to reproduce the issue:

- Buildup a Fairy Ring (8 vanilla mushrooms in a circle) https://github.com/cech12/ExtendedMushrooms/wiki/fairy-ring
- Fairy Ring is detected (root network on the ground)
- replace one mushroom with one of the missing mushrooms of your mod (Death Cap, Sythian Fungus, Soul Shroom)
- Fairy Ring is not detected

Extended Mushrooms 1.19.2-3.0.1.4 https://www.curseforge.com/minecraft/mc-mods/extended-mushrooms/files/4159848

It would be great if your mushrooms could be listed in this tag to enhance the compatibility. 😄

Edit: I found this issue https://github.com/AOCAWOL/BYG/issues/346, that the Synthian Fungus should not be in this tag. But maybe the others should? :)

### latest.log

no logs

### Did you isolate BYG?

I tried BYG alone

### Did you read and understand the above agreement?

- [X] I agree.

**Comment by CorgiTaco** [comment]
So soul shrooms, death caps, and sythian fungus are nether fungi and more closely match the properties of vanilla's Warped & Crimson Fungi. And looking at Forge's tag provider, they do not add Nether Fungi from vanilla: 

https://github.com/MinecraftForge/MinecraftForge/blob/1.19.x/src/main/java/net/minecraftforge/common/data/ForgeItemTagsProvider.java#L95

So I am going to say this is *not* an issue.
