### ISSUE TITLE
[1.19][Bug]: Invalid Player Data

### ISSUE THREAD

**Issue by TinyMandalorian** [CorgiTaco/BYG#1176]
### BYG Version

1.19.2-2.0.1.1

### Terrablender Version

1.19.2-2.0.1.136

### Mod Loader

Forge

### Mod Loader Version

43.2.8

### Bug Severity

Major

### What happened?

When I try to enter my server I always get Invalid Player data im running a cobblemon server and this will be a issue if players actually want to play on it.

im running a ArcLight server which supports plugins/mods

the mods include
Cobblemon
and BYG
Yes I have all the dependencies

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/11559319/latest.log)

### Did you isolate BYG?

I tried BYG alone

### Did you read and understand the above agreement?

- [X] I agree.

**Comment by CorgiTaco** [comment]
@Gavins38 I see you're using bukkit, could you try the mod on just a forge server?

**Comment by TinyMandalorian** [comment]
I can try gimme a bit

**Comment by TinyMandalorian** [comment]
Ok I seemed to have solved it so I tested a forge server worked fine I than had a thought I disabled the plugins folder and it worked so I thought that it must be some plugin I narrow it down to the Citizens plugin remove it and it works I can login without invalid player data error idk why BYG and the Citizens plugin dont like each other but my issue is I guess fixed for now.

**Comment by CorgiTaco** [comment]
Yeah, keep in mind plugins and mods don't work well together and are more than likely to break, I'd suggest just sticking with Forge and finding mod alternatives for any plugins you have
