### ISSUE TITLE
[1.19][Crash]: 

### ISSUE THREAD

**Issue by Ryuushen** [CorgiTaco/BYG#1177]
### BYG Version

Oh_The_Biomes_You'll_Go-fabric-1.19.2-2.0.1.1.jar

### Terrablender Version

TerraBlender-fabric-1.19.2-2.0.1.136.jar

### Mod Loader

Fabric

### Mod Loader Version

0.14.20

### What happened?

Can't start BYG 

### crash-log

[crash-2023-05-25_01.01.58-client.txt](https://github.com/AOCAWOL/BYG/files/11562470/crash-2023-05-25_01.01.58-client.txt)

### latest.log

[crash-2023-05-25_01.01.58-client.txt](https://github.com/AOCAWOL/BYG/files/11562476/crash-2023-05-25_01.01.58-client.txt)

### Did you isolate BYG?

I tried BYG alone

### Did you read and understand the above agreement?

- [X] I agree.

**Comment by CorgiTaco** [comment]
Broken config,  delete config directory and let it regen. When submitting your next issue please follow the agreement's steps.
