### ISSUE TITLE
[1.16.3] Baobab saplings will not grow regardless of area

### ISSUE THREAD

**Issue by CorgiZero** [CorgiTaco/BYG#118]
The Baobab sapling will not grow into a full tree, even in completely flat conditions or on a superflat world. Bonemeal and other methods of speeding up growth do nothing as well. Mod version is 1.0.7, on the modpack TNP Limitless 3.

The same issue is also present on Ebony saplings, and I've tried both saplings with 1x1, 2x2 and 3x3 arrangements and none worked. There may be issues with other saplings as well.

**Comment by CorgiTaco** [comment]
Will be fixed on Oct 31
