### ISSUE TITLE
[1.19][Bug]: Bonemeal can cause wrong sapling to grow

### ISSUE THREAD

**Issue by supersaiyansubtlety** [CorgiTaco/BYG#1188]
### BYG Version

2.0.1.1

### Terrablender Version

2.0.1.136

### Mod Loader

Fabric

### Mod Loader Version

0.14.21

### Bug Severity

Minor

### What happened?

I used bone meal on an aspen sapling and a nearby sapling grew instead of the one I bone mealed.

Saplings up to two blocks away to the north and west will grow if the blocks at ground level are valid for the sapling in those directions.

<details>
<summary>Video</summary>

https://github.com/AOCAWOL/BYG/assets/618276/e8f5361d-b5df-45b7-9d37-13813b765f67

</summary>

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/11581061/latest.log)

### Did you isolate BYG?

I tried BYG alone

### Did you read and understand the above agreement?

- [X] I agree.

**Comment by JT122406** [comment]
What Mc version is this? And do you have any other mods besides BYG and terrablender? Also is the behavior reproducible in a new world?

**Comment by supersaiyansubtlety** [comment]
MC 1.19.2, no other mods, and the video is from a fresh world.
