### ISSUE TITLE
[1.19][Bug]: Empty tags `c:blue_sand`, `c:black_sand`, `c:white_sand`, and `c:purple_sand` causes their sandstone variants to be uncraftable.

### ISSUE THREAD

**Issue by khazenor** [CorgiTaco/BYG#1190]
### BYG Version

1.19.2-2.0.0.13

### Terrablender Version

1.19.2-2.0.1.136

### Mod Loader

Forge

### Mod Loader Version

43.2.8

### Bug Severity

Minor

### What happened?

Empty tags `c:blue_sand`, `c:black_sand`, `c:white_sand`, and `c:purple_sand` causes their sandstone variants to be uncraftable.
![image](https://github.com/AOCAWOL/BYG/assets/80185732/e05c4553-1459-4462-bd1b-401be1a6571f)

Also windswept sandstone doesn't have a recipe of crafting it from windswept sand.  I'm not sure if that's intentional or not.

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/11583344/latest.log)

### Did you isolate BYG?

I tried BYG alone

### Did you read and understand the above agreement?

- [X] I agree.

**Comment by Leafsong88** [comment]
@CorgiTaco i found a solution for this thing without creating a Datapack
I opened the jar folder with WinRAR and saw that inside the c Folder (Inside the Data folder) there is nothing.

![imagen_2023-07-01_233843851](https://github.com/AOCAWOL/BYG/assets/132001881/35886bd4-b034-46ec-99db-c915e80b6d53)

But inside the Fabric Version are the tags folder and inside that folder are blocks, entity_types, items and worldgen.

![imagen_2023-07-01_233913018](https://github.com/AOCAWOL/BYG/assets/132001881/f92df574-21cb-4086-9e3f-93726075b3be)
![imagen_2023-07-01_233922944](https://github.com/AOCAWOL/BYG/assets/132001881/2f319513-89ec-4a5e-9099-cf2511fef61e)

I added the tags folder from the Fabric version to the Forge version and now i can craft Black, White, Blue and Purple Sandstone.

The solution is add that folder to the Forge version will fix that for everyone
