### ISSUE TITLE
[1.19][Crash]: Crashes.

### ISSUE THREAD

**Issue by MagmaSlime123** [CorgiTaco/BYG#1191]
### BYG Version

Oh_The_Biomes_You'll_Go-forge-1.19.2-2.0.1.1

### Terrablender Version

TerraBlender-forge-1.19.2-2.0.1.136

### Mod Loader

Forge

### Mod Loader Version

43.2.11

### What happened?

Title. Game crashes on startup.

### crash-log

[debug.log](https://github.com/AOCAWOL/BYG/files/11585475/debug.log)
No crash file is provided, a debug.log file is all I can give.

### latest.log

See above. No crash info/errors (from what I cam see) is in here.
It's useless though.

[latest.log](https://github.com/AOCAWOL/BYG/files/11585480/latest.log)

### Did you isolate BYG?

I tried BYG alone

### Did you read and understand the above agreement?

- [X] I agree.

**Comment by ghost** [comment]
Hey. If you're using the launcher, does it provide an error code when the game closes? If so what is the code? 🙂

**Comment by MagmaSlime123** [comment]
It provides none. Again, the 2 log files are all I'm able to give. No crash file whatsoever.

**Comment by UHQ-GAMES** [comment]
the latest log says you are missing corgilib. which  is a required dependency for byg

**Comment by MagmaSlime123** [comment]
Curse says you only need TerraBlender. I didn't do anything to the files.

![image](https://github.com/AOCAWOL/BYG/assets/51277766/a5d18fae-af36-46ca-9cfc-a3b2e5311d67)

**Comment by UHQ-GAMES** [comment]
it used to be only therrablender. but newer versions require terrablender, geckolib, and corgilib 
![Untitled-2](https://github.com/AOCAWOL/BYG/assets/45263169/a4d30884-908e-4ed3-b16e-6fcacebadb03)

**Comment by MagmaSlime123** [comment]
Huh, didn't know that. Please update the Relations tab.

**Comment by UHQ-GAMES** [comment]
the relations tab takes from the latest release version, and since the latest "release" needs only Terrablender, that's what it shows. Once a version with the new dependencies is uploaded as a release, it should update with the new ones.
