### ISSUE TITLE
[1.18][Bug]: Floating Plants in Imparius Grove

### ISSUE THREAD

**Issue by Reshy** [CorgiTaco/BYG#1193]
### BYG Version

Oh_The_Biomes_You'll_Go-forge-1.18.2-1.4.7.jar

### Terrablender Version

TerraBlender-forge-1.18.2-1.2.0.126.jar

### Mod Loader

Forge

### Mod Loader Version

40.2.4

### Bug Severity

Minor

### What happened?

![2023-06-01_03 07 26](https://github.com/AOCAWOL/BYG/assets/2096384/2b070d30-21d4-4895-bd71-104b4ad343f6)
![2023-06-01_03 37 15](https://github.com/AOCAWOL/BYG/assets/2096384/675d29fd-9445-4338-bbf1-26750ba91ae8)

### latest.log

N/A

### Did you isolate BYG?

I did try BYG alone

### Did you read and understand the above agreement?

- [X] I agree.

**Comment by CorgiTaco** [comment]
This is fixed on 1.19, the fix will be backported to 1.18 soon.
