### ISSUE TITLE
No tool works on Overgrown Stone, Fabric 1.16.1

### ISSUE THREAD

**Issue by PatrolOfStroll** [CorgiTaco/BYG#12]
Overgrown Stone and the snowy version, as encountered in Bluff biomes, aren't mined more quickly using a pick or indeed any tool, unlike the ordinary stone around it. This might also be the case with other similar blocks in other biomes that I haven't yet encountered.

**Comment by AOCAWOL** [comment]
This is being looked into

**Comment by CorgiTaco** [comment]
Should be patched here:
https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go-fabric/files/2998033
Please comment on this issue if the issue still persists
