### ISSUE TITLE
HugeCypressTree.java Slows Performance

### ISSUE THREAD

**Issue by Voronoiii** [CorgiTaco/BYG#12]
The Huge Cypress Tree is incredibly slow and takes an incredible toll on performance, **Probably has to do with the amount of for loops contained within the class.** May need to switch to a manual placement method on the trunk to reduce the amount of lag.

**Comment by FoundSpore** [comment]
Turns out the for loops fire 40000+ times. Resulting in the insane lag

**Comment by FoundSpore** [comment]
Will try to use an || statement to fix the issue. Still unsure if it'll work

**Comment by CorgiTaco** [comment]
The Cypress tree is getting recoded. My java Knowledge is much better these days so this issue is invalid.
