### ISSUE TITLE
[Forge 1.16.3] Optifine + BYG break vanilla ore spawns

### ISSUE THREAD

**Issue by CephalonKian** [CorgiTaco/BYG#120]
I've been playing a small modpack I made and have been loving BYG and most of all with shaders. On the free server I have it works out just fine but single player has a major issue. With just Optifine and BYG installed caves become blank stone, lava, and obsidian completely breaking the game. I don't know where the incompatibility stems from but I do hope that you can find it as I truly prefer BYG over BOP as the biomes feel more colorful and diverse.

**Comment by CorgiTaco** [comment]
Duplicate of #97
