### ISSUE TITLE
[1.19][Bug]: Biome features are missing in the nether and in the end 

### ISSUE THREAD

**Issue by ghost** [CorgiTaco/BYG#1200]
### BYG Version

2.0.1.2      (i tried earlier versions as well) 

### Terrablender Version

2.0.1.136

### Mod Loader

Forge

### Mod Loader Version

43.2.8

### Bug Severity

Major

### What happened?

Any biome from byg in nether and in the end is generated without any features (trees, rocks, etc.) i checked config and everything seemed fine, i tried reseting the config as well, tried older versions of the mod (in 1.19.2). I also asked my friend to try the mod, he also had the same problem.

![image](https://github.com/AOCAWOL/BYG/assets/136236129/8a31ada6-825e-4d54-8bac-683401cc9ee8)
![image](https://github.com/AOCAWOL/BYG/assets/136236129/0c1ba34f-5b0a-4d47-b5ee-6bcbb95a41f3)

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/11714439/latest.log)

### Did you isolate BYG?

I tried BYG alone

### Did you read and understand the above agreement?

- [X] I agree.

**Comment by CorgiTaco** [comment]
Use terrablender .129
