### ISSUE TITLE
[1.19][Crash]: Exception generating new chunk, "ancient_sequoia"

### ISSUE THREAD

**Issue by jmadarg** [CorgiTaco/BYG#1207]
### BYG Version

2.0.1.3

### Terrablender Version

2.0.1.162

### Mod Loader

Fabric

### Mod Loader Version

0.14.21

### What happened?

World crashes when exploring and generating new chunks, crash log mentions `byg:features/trees/ancient/ancient_sequoia`.

When looking at the files, I noticed I was not able to to open `\data\byg\structures\features\trees\ancient\ancient_sequoia.nbt` from the 2.0.1.3 or 2.0.1.2 versions of the mod, but had no issues with the 2.0.1.1 version

### crash-log

https://gist.github.com/jmadarg/442fc0c18473168c4df9352bfba2e028

### latest.log

Could not retrieve them due to issues with the server

### Did you isolate BYG?

I did not try BYG alone

### Did you read and understand the above agreement?

- [X] I agree.

**Comment by Octall** [comment]
Faced the same issue within the AOF6 modpack, tried replacing the corrupt NBT file within 2.0.1.2 with the ``ancient_sequoia.nbt`` from BYG version 2.0.1.1 and it corrupted all newly loaded chunks.

**Comment by Crinfarr** [comment]
Same here, [here's my crash report](https://pastebin.com/F6Db0XD5)

ETA: Running BCG+ Modpack, but I don't think it's a compat issue

**Comment by Crinfarr** [comment]
Looking through source I think #1196 corrupted or broke several nbt structures

**Comment by Crinfarr** [comment]
Fixed on my pr #1212

**Comment by jmadarg** [comment]
Didn't notice the report said it was on forge, just edited it, because its on fabric (also running BCG Plus - glad the modpack got updated to use an older version of BYG). Could #1206 be related even tho that is on forge?

**Comment by CorgiTaco** [comment]
@jmadarg yeah #1206 is def related. NBTs got corrupted which is annoying lol

**Comment by antoni0C0des** [comment]
I was about to open an issue but I've seen people already wrote it. Will a fix be rolled for the corrupted NBT?

**Comment by Crinfarr** [comment]
@lil0programmer there's a lot of nbt to go through but I might make another pr in a few days fixing it; for now I just rolled back sequoias

**Comment by antoni0C0des** [comment]
Atm I have used Corgi's new NBT data that he uploaded in the repo to fix a biome issue with the mushroom canopy, I've checked all byg biomes & I'm pregenning a world with no issues.

**Comment by CorgiTaco** [comment]
Fixed in latest release
