### ISSUE TITLE
[1.19][Bug]: Missing entirety of BYG nether and end biomes

### ISSUE THREAD

**Issue by Rayray0011** [CorgiTaco/BYG#1209]
### BYG Version

4.0.0.1

### Terrablender Version

2.2.0.161

### Mod Loader

Fabric

### Mod Loader Version

0.14.21

### Bug Severity

Minor

### What happened?

I'm classifying this as minor, as I don't mind playing without the missing biomes, but I would love to experience the entirety of BYG's glory.
I do apologise if there is a common fix to this, I read through the closed issues and couldn't find anything pertaining to this, but I might have just missed something.

Upon creating a new world with only BYG and the other required mods (1.19.4 as a reminder), the overworld biomes work beautifully and function as intended. However, when entering the End and Nether dimensions, there are no structures or new blocks from BYG at all in the new biomes. To clarify, the biomes do show up on the f3 information screen, and the Embur Bog has the ember particles floating around, but there are never any structures or new blocks anywhere to be seen. Not even the ground blocks change. I noticed in other issue reports that players had the ground blocks for the biome, but there's just nothing for mine. There is nothing to indicate that the biome is any different from vanilla, besides the f3 information.

I did originally try to play BYG with a bunch of other mods, but I ended up removing them and deleting all mods and config files, and still cannot figure out what's going on. So, I'm not sure if the removed mods may have influenced something.

I apologise for how long the latest.log is as well, I ended up going through all the BYG biomes in the nether (to see if any of them worked) and having a look at some of the overworld's. 

I appreciate any help you guys can provide, and thank you for even taking the time to read this. I get you guys are busy.

### latest.log

https://gist.github.com/Rayray0011/be569bbd6c91899057d113502593c698

### Did you isolate BYG?

I tried BYG alone

### Did you read and understand the above agreement?

- [x] I agree.

**Comment by Rayray0011** [comment]
I attempted using the "Enabling BYG Nether & End Biomes in existing worlds" steps (even though I'm trying to make a new world), but it removes the existence of the End and Nether for me. New worlds have the same issue.

**Comment by Rayray0011** [comment]
I found a fix, I just needed to reload the world a few times. Sorry for this!

**Comment by allanonmage** [comment]
I wonder if this is related to the missing end biome issue that I'm having.
