### ISSUE TITLE
[1.16.3 Fabric] BYG Bookshelfs don't work with enchanting table.

### ISSUE THREAD

**Issue by DaddySpin** [CorgiTaco/BYG#121]
None of the bookshelfs from this mod work with the Enchanting Table.

**Comment by Cooliosity** [comment]
I am using Rainbow Eucalyptus bookshelves so this might actually be an incompatibility issue on your side.

**Comment by K0-RR** [comment]
They don't work for me too.

**Comment by CorgiTaco** [comment]
Patched here: https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go-fabric/files/3097518
