### ISSUE TITLE
[1.19][Crash]: Creating a new world with Lithium

### ISSUE THREAD

**Issue by GhostIsBeHere** [CorgiTaco/BYG#1213]
### BYG Version

4.0.0.1

### Terrablender Version

2.2.0.161

### Mod Loader

Fabric

### Mod Loader Version

0.14.21

### What happened?

When creating a new world, BYG crashes the game with `java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2680.method_26204()" because "$$10" is null`. This does not happen when Lithium is not present.

### crash-log

[crash-2023-06-19_20.47.00-client.txt](https://github.com/AOCAWOL/BYG/files/11795608/crash-2023-06-19_20.47.00-client.txt)

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/11795607/latest.log)

### Did you isolate BYG?

I tried BYG alone

### Did you read and understand the above agreement?

- [X] I agree.

**Comment by Biogene0** [comment]
I had the same issue but managed to get it working by installing a mod called "Polymer Bundled". This only fixes the crashing tho and there are still blocks that wont appear until clicked on in the game. The only fix I know of at the moment is not using lithium with BYG. Hope this helps.

**Comment by BeardedThorgi** [comment]
I've also been experiencing this and have tested every version combination of BYG and Lithium that are compatible with 1.19.3 and 1.19.4,  as nearly identical errors occur in all versions. Linked below is some information I shared on a Lithium Issue report, in case it's useful to the BYG folks for further troubleshooting:

https://github.com/CaffeineMC/lithium-fabric/issues/478#issuecomment-1627534187

Also wanted to note that Lithium 0.11.1 (the latest version) has had no major changes from 1.19.2 to 1.19.4 according to the current maintainer (2No2Name), and works without issue in BYG 2.0.1.4 in 1.19.2.

**Comment by Poopooracoocoo** [comment]
Setting https://github.com/CaffeineMC/lithium-fabric/blob/develop/lithium-mixin-config.md#mixinchunkentity_class_groups to false should fix it.

**Comment by JT122406** [comment]
Seems to be a mixin conflict
potionstudios.byg.mixin.access.client.ClientLevelAccess (byg.mixins.json)
		me.jellysquid.mods.lithium.mixin.chunk.entity_class_groups.ClientWorldMixin (lithium.mixins.json)
		net.fabricmc.fabric.mixin.event.lifecycle.client.ClientWorldMixin (fabric-lifecycle-events-v1.client.mixins.json)

**Comment by Timmilangschl0ng** [comment]
> I had the same issue but managed to get it working by installing a mod called "Polymer Bundled". This only fixes the crashing tho and there are still blocks that wont appear until clicked on in the game. The only fix I know of at the moment is not using lithium with BYG. Hope this helps.

THANK GOD FOR PEOPLE LIKE YOU <3

**Comment by doppeltrouble** [comment]
does it work by creating the world separately and then installing lithium?
or will it also crash then?

**Comment by IAmSneak** [comment]
I found a workaround, simply setting `mixin.ai.pathing=false` in the lithium config fixed the issue for me
