### ISSUE TITLE
[1.19][Crash]: Exception Ticking World ("byg:features/mushrooms/imparius/imparius_mushroom_canopy6" is not a valid tree part)

### ISSUE THREAD

**Issue by katubug** [CorgiTaco/BYG#1217]
### BYG Version

2.0.1.3

### Terrablender Version

2.0.1.136

### Mod Loader

Forge

### Mod Loader Version

43.2.8

### What happened?

SMP crashed, unfortunately I do not have any user reports of what could have caused the issue. I am unable to try reproducing the crash with BYG isolated because it's on a server. I reset my BYG configs when we updated the mod recently.

### crash-log

https://gist.github.com/katubug/99ae44273554c4662121b7c10de551f5

### latest.log

I THINK this is it? https://gist.github.com/katubug/f9fa0d8289eac018bb6a01912a0314da

### Did you isolate BYG?

I did not try BYG alone

### Did you read and understand the above agreement?

- [X] I agree.

**Comment by CorgiTaco** [comment]
This has already been fixed on the latest version/2.1.0.4

**Comment by katubug** [comment]
Ah, oops, sorry! Thank you so much!
