### ISSUE TITLE
[1.19][Bug]: Embur gel vines can't get correct render with shaders

### ISSUE THREAD

**Issue by KeWHs** [CorgiTaco/BYG#1218]
### BYG Version

2.0.1.3

### Terrablender Version

2.0.1.127

### Mod Loader

Fabric

### Mod Loader Version

1.19.2-0.14.19

### Bug Severity

Major

### What happened?

Ive tried to make the embur gel vines waving with ComplementaryShaders.
i changed block.properties:
block.9600=byg:embur_gel_vines byg:embur_gel_vines_plant
but it doesnt work.
i also check the namespace of it and there's no any problem.

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/11855579/latest.log)

### Did you isolate BYG?

I tried BYG alone

### Did you read and understand the above agreement?

- [X] I agree.

**Comment by CorgiTaco** [comment]
You didnt provide pictures giving me nothing to work with and addditionally your logs are so filled with errors I doubt this is a BYG error
