### ISSUE TITLE
[1.19][Bug]: Replaces the Curios API (forge) curios slot with the BYG book

### ISSUE THREAD

**Issue by Comet-Crusher** [CorgiTaco/BYG#1219]
### BYG Version

2.0.1.4

### Terrablender Version

2.0.1.136

### Mod Loader

Forge

### Mod Loader Version

43.2.0

### Bug Severity

Minor

### What happened?

HIIII So I'm playing the game with curious API installed and I can't access the curios slot! D:>

Whenever I click the hotkey or the button for it it makes the little blue book appear on my screen instead.

![image](https://github.com/AOCAWOL/BYG/assets/137745484/038eb8cc-fb1b-41c7-81c5-54aa936a9559)

![image](https://github.com/AOCAWOL/BYG/assets/137745484/650dfc94-76a7-4726-a999-d7fccb182586)

Thank you SOOOO much for looking into this if/when you do!! This is my first time reporting a bug for anything so I hope I did everything right! <3 Have a wonderful day you did a REALLY great job with your mod <3

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/11862821/latest.log)

### Did you isolate BYG?

I tried BYG alone

### Did you read and understand the above agreement?

- [X] I agree.

**Comment by CorgiTaco** [comment]
There's a config in `config/byg/client/biomepedia.json5` that has the ability to change the coordinates of the button. Using that you can move it out of the way
