### ISSUE TITLE
1.12.2 Source?

### ISSUE THREAD

**Issue by Angular-Angel** [CorgiTaco/BYG#122]
Is the source for the 1.12.2 version still available? I don;t see a branch for it. Would I just need to dig through the commits until I find the cutoff point?

**Comment by CorgiTaco** [comment]
1.12 was made in Mcreator so there's no github for it sorry :/

**Comment by SodiumZH** [comment]
> 1.12 was made in Mcreator so there's no github for it sorry :/

Is the archive of 1.12.2 MCreator file available? BYG is the best biome mod I know for my current mod list, but it's somewhat buggy... So I'd like to fix some bugs by myself
