### ISSUE TITLE
[1.19][Crash]: Updated to latest version for 1.19.2, crashes on event phase

### ISSUE THREAD

**Issue by RolledOverTurtle** [CorgiTaco/BYG#1220]
### BYG Version

2.0.1.4

### Terrablender Version

2.0.1.136

### Mod Loader

Forge

### Mod Loader Version

43.2.6

### What happened?

Crashes on event phase startup every time giving the same reason.
![image](https://github.com/AOCAWOL/BYG/assets/80377471/758774eb-da67-4e16-800f-322942bc19e4)

### crash-log

no crash log only latest.log

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/11870686/latest.log)

### Did you isolate BYG?

I did not try BYG alone

### Did you read and understand the above agreement?

- [X] I agree.

**Comment by CorgiTaco** [comment]
delete the `C:\Users\Lucy\Documents\curseforge\minecraft\Instances\1.19.2 Testing (2) (1) (2)\config\byg\trades.json5` file
