### ISSUE TITLE
[1.19][Bug]: Embur pedu missing wood forge tag?

### ISSUE THREAD

**Issue by RechercheRaptor** [CorgiTaco/BYG#1222]
### BYG Version

1.19.2

### Terrablender Version

2.0.1.136

### Mod Loader

Forge

### Mod Loader Version

43.2.0

### Bug Severity

Minor

### What happened?

I've been using the mod Every Compat - Wood Good so that I can make furniture from Another Furniture, Farmer's Delight, Dramatic Doors, and so forth with BYG wood types. It mostly works, but I've found that Embur wood can't be used to make any of these block types, and unlike other BYG wood types JEI doesn't register chairs/tables/cabinets/tall doors for Embur wood. Every Compat apparently works by grabbing textures from modded blocks with the forge tag for wood, so I was wondering if Embur pedu was missing this tag? If not I'll take the issue to the Every Compat people.

### latest.log

This isn't an error that would show in logs (no pun intended)

### Did you isolate BYG?

I did not try BYG alone

### Did you read and understand the above agreement?

- [X] I agree.

**Comment by JT122406** [comment]
There is no Forge wood tag are you referring to a specific tag?
