### ISSUE TITLE
[1.19][Bug]: Permanent pink sky tint & vignette from the windswept desert biome

### ISSUE THREAD

**Issue by abigailw540** [CorgiTaco/BYG#1223]
### BYG Version

1.19.2

### Terrablender Version

1.19.2

### Mod Loader

Forge

### Mod Loader Version

the newest version

### Bug Severity

Major

### What happened?

I spawned in a windswept desert biome which blurs the edges of your screen and tints everything a shade of pink. I since have left that biome and traveled far away and my screen tint and blur will not go away. I tried disconnecting, restarting the server, going into the nether, messing with all of my settings and nothing will make it back to normal. It's just really annoying that everything is pink and blurry. Its not caused by a shaderpack or a resource pack, and I have tried everything under the sun to fix it. For some reason spawning in the desert biome just permanently made the sky pink. It only does this on the multiplayer server I play on, not on singleplayer worlds.
![2023-06-30_20 12 01](https://github.com/AOCAWOL/BYG/assets/138265477/ab816763-9a38-4d20-8d72-0ebdb1afad68)

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/11923880/latest.log)

### Did you isolate BYG?

I did not try BYG alone

### Did you read and understand the above agreement?

- [X] I agree.

**Comment by AOCAWOL** [comment]
This is just due to the biome having a pink-tinted sky that is intended. How shaders utilize that isn't something we have control over and you are also able to datapack the sky color out as well.
