### ISSUE TITLE
[1.19][Crash]: BYG does not load correctly

### ISSUE THREAD

**Issue by ApertureScience9592** [CorgiTaco/BYG#1225]
### BYG Version

2.0.1.4

### Terrablender Version

2.0.1.166

### Mod Loader

Forge

### Mod Loader Version

43.2.14

### What happened?

I started the modpack and when it finished loading on the mojang screen, it said that BYG failed to load correctly and it gave a alot of random stuff I dont understand

### crash-log

[crash-2023-07-08_20.50.53-fml.txt](https://github.com/AOCAWOL/BYG/files/11992333/crash-2023-07-08_20.50.53-fml.txt)
Ik that create industry also failed to load but that is not important for this issue

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/11992336/latest.log)

### Did you isolate BYG?

I tried BYG alone

### Did you read and understand the above agreement?

- [x] I agree.

**Comment by tLJack** [comment]
I had this problem as well, but it went away if I deleted the byg config folder.  I think it's an issue with updating from an older version?

**Comment by miroslav-pavlov** [comment]
I just had the same bug after updating from an older version of the mod. The game cannot start and gives an error when reading files from /config/byg. I have gotten the error when playing the modpack Create: Mekanized and manualy updating the mods after gameplay.

**Comment by JT122406** [comment]
Just requires config to be regenned
