### ISSUE TITLE
[1.19][Bug]: Missing rose collect & biome explorer advancement titles & descriptions

### ISSUE THREAD

**Issue by Quinci135** [CorgiTaco/BYG#1228]
### BYG Version

2.0.1.4

### Terrablender Version

2.0.1.166

### Mod Loader

Forge

### Mod Loader Version

43.2.21

### Bug Severity

Minor

### What happened?

saw <https://old.reddit.com/r/feedthebeast/comments/151sb27/bygadvancementshusbandryrose_collectortitle/>
confirmed ingame rose collector & biome explorer advancements to be missing language keys (can't just pr, needs flavor text titles)
https://imgur.com/a/jNU3oy6
`rose_collector` (in main instead of generated resources?) <https://github.com/AOCAWOL/BYG/blob/1.19.X/Common/src/main/resources/data/byg/advancements/rose_collector.json#L64>
`oh_the_biomes_youll_go` <https://github.com/AOCAWOL/BYG/blob/1.19.X/Common/src/generated/resources/data/byg/advancements/adventure/oh_the_biomes_youll_go.json#L1201>
en_us lang <https://github.com/AOCAWOL/BYG/blob/1.19.X/Common/src/main/resources/assets/byg/lang/en_us_misc.json>

### latest.log

[trimmed latest.log](https://github.com/AOCAWOL/BYG/files/12074150/latest.log)

### Did you isolate BYG?

I did not try BYG alone

### Did you read and understand the above agreement?

- [X] I agree.

**Comment by deadnoises** [comment]
This is still an issue. 1.19.2 on BYG 2.0.1.6, both these achievements's text are broken.
