### ISSUE TITLE
[1.19][Bug]: Biomes ambiant sound are played underground and there is no way to turn them off

### ISSUE THREAD

**Issue by SigmaFlame** [CorgiTaco/BYG#1238]
### BYG Version

2.0.1.4

### Terrablender Version

2.0.1.166

### Mod Loader

Forge

### Mod Loader Version

43.2.21

### Bug Severity

Minor

### What happened?

Hello,

If I enter inside the biome skyris_vale, I heard bird ambiant sound.
But, this sound is also played underground.
I'm seeking for a way to disable it, but there is no config option to do that.

This sound is : ambiant_overworld_forest_loop:byg

### latest.log

It's about a feature of your mod, I don't think the latest.log is required here.

### Did you isolate BYG?

I tried BYG alone

### Did you read and understand the above agreement?

- [X] I agree.

**Comment by Bramblejack** [comment]
I temporarily fixed this by replacing the .ogg file responsible for this sound with silence.

**Comment by GitHubAccountPR** [comment]
![Minecraft_ 1 19 2 - Singleplayer 1_20_2024 9_51_06 AM](https://github.com/AOCAWOL/BYG/assets/71120668/90794d87-4c6a-4971-843a-3ae86b272e93)
I have this same issue, even beneath bedrock.
Edit: After some trial and error I found that overworld_forest.ogg was the issue, I did what the above commenter said but now my overworld is eerily devoid of any ambient sounds.
