### ISSUE TITLE
[1.19][Bug]: Some Logs can't make certain wooden items, i.e. Mahogany into chest

### ISSUE THREAD

**Issue by Mysticpasta1** [CorgiTaco/BYG#1243]
### BYG Version

1.19.2-2.0.1.4

### Terrablender Version

1.19.2-2.0.1.166

### Mod Loader

Forge

### Mod Loader Version

43.2.21

### Bug Severity

Minor

### What happened?

Some Logs can't make certain wooden items, i.e. Mahogany into chest

try to craft a chest from mahogany planks into a chest it won't work

### latest.log

No log needed due to there is no crash just the recipe is missing

### Did you isolate BYG?

I tried BYG alone

### Did you read and understand the above agreement?

- [X] I agree.

**Comment by JT122406** [comment]
I am unable to reproduce in 1.19.2: 
![image](https://github.com/AOCAWOL/BYG/assets/75751882/fa8f2b9d-ce1b-4fec-a83a-ffabcefc7248)
