### ISSUE TITLE
[1.19][Bug]: Sythian Wart - no tool and doesnt drop

### ISSUE THREAD

**Issue by Lovatic123** [CorgiTaco/BYG#1247]
### BYG Version

2.0.1.4

### Terrablender Version

2.0.1.162

### Mod Loader

Forge

### Mod Loader Version

43.2.21

### Bug Severity

Minor

### What happened?

Trying to mine and collect the sythian wart block, I tried using both pickaxe, axe, hoe, shovel and sword. All enchanted, and all except the sword had effeciency, though no change in speed. And the block didnt drop using any of the tools listed - even with silktouch.
![2023-09-07_20 52 01](https://github.com/AOCAWOL/BYG/assets/20798024/7920ff55-bd2d-401e-a33a-4595ccfa04f2)

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/12560850/latest.log)
Not sure this one will be of help, as Ive been doing other things since.

### Did you isolate BYG?

I did not try BYG alone

### Did you read and understand the above agreement?

- [X] I agree.

**Comment by JT122406** [comment]
You have to use Shears
