### ISSUE TITLE
[1.19][Bug]: crash server

### ISSUE THREAD

**Issue by GitJhopa** [CorgiTaco/BYG#1248]
### BYG Version

Oh_The_Biomes_You'll_Go-forge-1.19.2-2.0.1.4

### Terrablender Version

TerraBlender-forge-1.19.2-2.0.1.166

### Mod Loader

Forge

### Mod Loader Version

1.19.2-43.2.14

### Bug Severity

Major

### What happened?

crash 
[crash-2023-09-09_14.00.34-server.txt](https://github.com/AOCAWOL/BYG/files/12565906/crash-2023-09-09_14.00.34-server.txt)

### latest.log

[2023-09-09-2.log](https://github.com/AOCAWOL/BYG/files/12565908/2023-09-09-2.log)

### Did you isolate BYG?

I tried BYG alone

### Did you read and understand the above agreement?

- [X] I agree.

**Comment by JT122406** [comment]
Duplicate of #1269

**Comment by JT122406** [comment]
Closing this one as progress will be tracked on that issue
