### ISSUE TITLE
Signs for BYG Wood Types

### ISSUE THREAD

**Issue by Cooliosity** [CorgiTaco/BYG#125]
Signs that are made from BYG wood do not exist.

**Comment by K0-RR** [comment]
Well, I think this is a somewhat major issue.

**Comment by CorgiTaco** [comment]
Expect these in 1.17. For now 1.16 will default to vanilla wood signs

**Comment by CorgiTaco** [comment]
Will be added in 1.17 like I said before. This is on our todo so no point in keeping this issue open any longer
