### ISSUE TITLE
[1.19][Bug]: Palo Verde logs cannot be used as furnace fuel

### ISSUE THREAD

**Issue by saltyseadoggo** [CorgiTaco/BYG#1250]
### BYG Version

2.0.1.4

### Terrablender Version

2.0.1.166

### Mod Loader

Forge

### Mod Loader Version

43.2.8

### Bug Severity

Minor

### What happened?

Palo Verde logs cannot be used as furnace fuel, despite being flammable.

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/12573278/latest.log)

### Did you isolate BYG?

I tried BYG alone

### Did you read and understand the above agreement?

- [X] I agree.

**Comment by JT122406** [comment]
Can confirm but for the life of me cannot figure out why this is happening as it is registered as flammable and has the logs_that_burn tag so trying to figure this one out
