### ISSUE TITLE
[1.16][Bug]: Incompat with Explorer's Compass if subbiomes changed

### ISSUE THREAD

**Issue by NighthowlerStudios** [CorgiTaco/BYG#1252]
### BYG Version

1.3.6

### Mod Loader

Forge

### Mod Loader Version

36.2.39

### Bug Severity

Major

### What happened?

Explorer's Compass will refuse to show any structures in its GUI if the BiomeProvider returns a null whilst Explorer's Compass is trying to getStructureDimensions.  I don't know exactly how, but BiomeProvider only seems to have a problem if the subbiome configurations are misconfigured by simply "disabling" subbiomes from biomes (especially red rock).

Note the crash stops occurring if I reset the configs, but I kinda need some of the configs for other modpack balance fixes :/

Issue is shared with Explorer's Compass since 2021:
https://github.com/MattCzyr/ExplorersCompass/issues/8

### latest.log

[explo_issue.log](https://github.com/AOCAWOL/BYG/files/12640427/explo_issue.log)

### Did you isolate BYG?

I tried BYG alone and I also tried it with just this mod and Explorer's Compass

### Did you read and understand the above agreement?

- [X] I agree.

**Comment by NighthowlerStudios** [comment]
[byg.zip](https://github.com/AOCAWOL/BYG/files/12640439/byg.zip)
here's my config folder so we can nitpick exactly what is different.  you can reproduce this issue with BYG, Explorer's Compass, and simply using this config folder.

**Comment by JT122406** [comment]
1.16 isn't supported
