### ISSUE TITLE
[1.19][Bug]: Featureless Nether and End

### ISSUE THREAD

**Issue by ImpulsiveLass** [CorgiTaco/BYG#1259]
### BYG Version

1.19.4-4.0.0.2

### Terrablender Version

1.19.4-2.2.0.168

### Mod Loader

Fabric

### Mod Loader Version

fabric-loader-0.14.22-1.19.4

### Bug Severity

Major

### What happened?

The overworld is perfectly fine but the nether and end are featureless, while the biomes are evidently there as shown by journeymap and the /locate command, all that can be found in the nether is netherrack and lava; and all that can be found in the end is just the ground and chorus fruit.
![2023-10-09_15 26 44](https://github.com/AOCAWOL/BYG/assets/92990441/b68e0a63-6285-4f93-bb6f-9d473aa82ee4)
![2023-10-09_15 26 53](https://github.com/AOCAWOL/BYG/assets/92990441/7687c853-92f1-42e7-8081-8e4939b664b5)
![2023-10-09_15 27 31](https://github.com/AOCAWOL/BYG/assets/92990441/dfaae8a0-cff2-40b3-aa1b-398fdc3d041a)
![2023-10-09_15 31 51](https://github.com/AOCAWOL/BYG/assets/92990441/d804c57b-afa2-4cee-83b3-db7bae16a367)

*** The only other mods I have installed are corgilib, geckolib, journeymap, jei, and jade; the former 2 are dependencies while the ladder 3 have zero bearing on world generation as they are client side.

### latest.log

[2023-10-09-7.log.gz](https://github.com/AOCAWOL/BYG/files/12849793/2023-10-09-7.log.gz)

### Did you isolate BYG?

I tried BYG alone

### Did you read and understand the above agreement?

- [X] I agree.

**Comment by ImpulsiveLass** [comment]
Double triple quadruple checked several times after deleting EVERY config I had and redownloading the mods and dependencies and the issue still remains present.

**Comment by AwesomeDude091** [comment]
Was the world generated on a server instance, or a client instance?

**Comment by ImpulsiveLass** [comment]
Client, I even ran the current 1.20.1 fabric of this mod in intellij and this bug is very much so still in it and not from config or an incompatibility

**Comment by AwesomeDude091** [comment]
Yeah that where I first found the bug too, fortunately I think I know where the issue originates. To confirm could you tell me if everything gets generated properly if you generate it with a Server Instance? @ImpulsiveLad

**Comment by ImpulsiveLass** [comment]
I’ll try it later

**Comment by ImpulsiveLass** [comment]
Tried and tried again and again for a few hours and could not get a server to generate and then connect to it, I believe both corgilib and geckolib were crashing at a multitude of times and I that was built into the git

**Comment by Xonazeth** [comment]
I am also having this same issue in Forge 1.19.2, but strangely enough, the mod works perfectly for me in fabric on the same version.

**Comment by deividg231** [comment]
Hi, Im having issues opening the game and it says that Oh the biomes you'll go is causing trubble loading. Here I upload the logs
[logt.txt](https://github.com/AOCAWOL/BYG/files/13531123/logt.txt)

**Comment by deividg231** [comment]
> Hi, Im having issues opening the game and it says that Oh the biomes you'll go is causing trubble loading. Here I upload the logs [logt.txt](https://github.com/AOCAWOL/BYG/files/13531123/logt.txt)
Just solved it by deleting the Config folder and reloading the game.

**Comment by JT122406** [comment]
Nether will be redone in the future versions so I am closing this.
