### ISSUE TITLE
[1.19][Bug]: Witch Hazel Sapling doesn't grow.

### ISSUE THREAD

**Issue by JessePretendstoCode** [CorgiTaco/BYG#1264]
### BYG Version

2.0.1.2

### Terrablender Version

2.0.1.136

### Mod Loader

Forge

### Mod Loader Version

0.235.4.1

### Bug Severity

Minor

### What happened?

Witch Hazel Sapling doesn't grow.

### latest.log

[2023-10-16-2.log.gz](https://github.com/AOCAWOL/BYG/files/12968064/2023-10-16-2.log.gz)

### Did you isolate BYG?

I did not try BYG alone

### Did you read and understand the above agreement?

- [X] I agree.

**Comment by ImpulsiveLass** [comment]
Did you use the correct sapling requirement? It may need a 3x3 or star of saplings

**Comment by JessePretendstoCode** [comment]
Yes. I tried every way I could think of, including 2x2 and 3x3.  I also tried with different dirt/sand.

**Comment by bloody-shadow666** [comment]
I'm also having this issue. Even went into creative and tried bonemealing, tried a bunch of patterns and soils and I still can't get it to grow
