### ISSUE TITLE
[1.19][Crash]: Nether Crashes on first generation

### ISSUE THREAD

**Issue by sherpascott** [CorgiTaco/BYG#1269]
### BYG Version

2.0.1.4

### Terrablender Version

2.0.1.136

### Mod Loader

Forge

### Mod Loader Version

43.3.2

### What happened?

When entering the nether for the first time in my world, it freezes indefinitely until I hard quit. The weird thing is, it says error with byg:arisian_undergrowth, but that biome is disabled in the config. I tried enabling it and removing infernal expansion, but no luck. I suspect a mod conflict though. BYG works fine alone.

### crash-log

[crash-2023-10-20_14.54.27-server.txt](https://github.com/AOCAWOL/BYG/files/13058580/crash-2023-10-20_14.54.27-server.txt)

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/13058582/latest.log)

### Did you isolate BYG?

I tried BYG alone

### Did you read and understand the above agreement?

- [X] I agree.

**Comment by pandaninjas** [comment]
This might be an issue with a modpack you're using, see: https://misode.github.io/guides/feature-order-cycle/

**Comment by sherpascott** [comment]
Thx for the resource! I tried removing all other mods that affect the nether besides byg but it didn't work? Also it says it's related to arisian undergrowth, but that biome is completely disabled from generation.

**Comment by pandaninjas** [comment]
> Thx for the resource! I tried removing all other mods that affect the nether besides byg but it didn't work? Also it says it's related to arisian undergrowth, but that biome is completely disabled from generation.

Sorry, I misunderstood the document. I think it might have something to do with a datapack.
