### ISSUE TITLE
[1.19][Crash]: Embur Bog causing a lot of lag

### ISSUE THREAD

**Issue by SafeOfArsenal** [CorgiTaco/BYG#1271]
### BYG Version

2.0.1.4

### Terrablender Version

2.0.1.166

### Mod Loader

Forge

### Mod Loader Version

43.3.2

### What happened?

The biomes cause lots of particle lag in especially bigger modpacks 

### crash-log

none

### latest.log

none

### Did you isolate BYG?

I did not try BYG alone

### Did you read and understand the above agreement?

- [X] I agree.

**Comment by JT122406** [comment]
Try with just BYG, another mod might be adding particles
