### ISSUE TITLE
[1.19][Bug]: Hypogeal Imperium Stops Functioning at Max Upgrade of 12

### ISSUE THREAD

**Issue by spotenza2016** [CorgiTaco/BYG#1276]
### BYG Version

4.0.0.2

### Terrablender Version

3.0.0.64

### Mod Loader

Fabric

### Mod Loader Version

36.0.45

### Bug Severity

Minor

### What happened?

The hypogeal imperium stops accepting fuel when upgraded to level 12 with the crystals. Works at level 11 and all prior, but at 12 stops functioning.  I've identified the issue in the code to https://github.com/AOCAWOL/BYG/blob/c22936d8eb1a772547499e73f9d48825d864724c/src/main/java/corgiaoc/byg/common/entity/tileentities/HypogealImperiumTE.java#L256 where the add fuel if statement is contained within the <12 check. Should be a 2 second fix of moving it outside that if statement.

### latest.log

N/A (It's literally just a semantic code error).

### Did you isolate BYG?

I tried BYG alone

### Did you read and understand the above agreement?

- [X] I agree.

**Comment by JT122406** [comment]
The spot you pointed out is in 1.16.5

**Comment by JT122406** [comment]
this class and package no longer exist in 1.19
