### ISSUE TITLE
[1.19][Crash]: Crash loading launch

### ISSUE THREAD

**Issue by FelixHich** [CorgiTaco/BYG#1280]
### BYG Version

2.0.1.5

### Terrablender Version

2.0.1.166

### Mod Loader

Forge

### Mod Loader Version

43.3.0

### What happened?

I recently tried to start the game but it Crashes when loading BYG, before I had a Similar Crash with the Trades.json5 part but on the advice of another issue section, I deleted it and now I have this crash:

### crash-log

[crash-2023-11-01_18.18.44-fml.txt](https://github.com/AOCAWOL/BYG/files/13232870/crash-2023-11-01_18.18.44-fml.txt)

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/13232916/latest.log)

### Did you isolate BYG?

I did not try BYG alone

### Did you read and understand the above agreement?

- [ ] I agree.

**Comment by JT122406** [comment]
Regen the CorgiLib Config and try again

**Comment by FelixHich** [comment]
> Regen the CorgiLib Config and try again

how i did that?

**Comment by JT122406** [comment]
Delete the folder

**Comment by FelixHich** [comment]
> Delete the folder

It Worked! Thanks so much
