### ISSUE TITLE
[1.15.2 Forge] Create Compatability

### ISSUE THREAD

**Issue by Cyphon-dev** [CorgiTaco/BYG#129]
I've made a datapack for 1.15.2 that adds recipes for Create's Mechanical Saw for all the logs that BYG adds, plus adding the #minecraft:wooden_buttons tag to each of the buttons making them usable for cog recipes.
[bygcreatecompat.zip](https://github.com/CorgiTaco/BYG/files/5398569/bygcreatecompat.zip)

**Comment by CorgiTaco** [comment]
We no longer support this version and will not modify our recipes if they work in vanilla. Keep using the datapack you've been using
