### ISSUE TITLE
[1.19][Bug]: your nether is almost fully broken

### ISSUE THREAD

**Issue by SafeOfArsenal** [CorgiTaco/BYG#1290]
### BYG Version

2.0.1.5 and 2.0.1.6

### Terrablender Version

2.0.1.166

### Mod Loader

Forge

### Mod Loader Version

43.3.5

### Bug Severity

Major

### What happened?

all the nether structures are broken this includes stuff like trees and foliage like LITERALLY LOOK AT THE SYTHIAN TORRIDS AND YOULL KNOW WHAT I MEAN

### latest.log

e

### Did you isolate BYG?

I tried BYG alone

### Did you read and understand the above agreement?

- [X] I agree.

**Comment by ImpulsiveLass** [comment]
Just here as a nerd, they are features not structures, the biomes do exist but the features like trees, chains, etc don't appear. I haven't dug through the code much but to me it seems that the feature gen may have been deleted or is blocked by something else or was disabled? I haven't tried using /place with the features but maybe that may explain something

**Comment by JT122406** [comment]
Nether will be redone in the future versions so I am closing this.
