### ISSUE TITLE
[1.19][Crash]: Tall ether grass causes an exception

### ISSUE THREAD

**Issue by will-janz** [CorgiTaco/BYG#1291]
### BYG Version

2.0.1.2

### Terrablender Version

2.0.1.162

### Mod Loader

Forge

### Mod Loader Version

43.2.14

### What happened?

When idling in a world, the server will crash unexpectedly and randomly. Crash reports point towards "byg:ether_grass". There is no direct path to reproduction. I have tried resetting the configs, crash still occurs. Also crashes in 2.0.1.6.  

I noticed that when ether grass grows (on the server where it's crashing), I can destroy it without issue. I think the issue is when it tries to transition to a two block high version, but I don't know if that's what it does. I can't find docs on the mechanics, I've googled around and the wikis I've found don't say.

Playing single player with the mod isolated, I can place short ether grass down but nothing happens. I can't get reproduction steps because I don't know what's causing this. The crash logs mention multiple mods but Java is out of my wheelhouse. If it is a mod incompatibility, I can't tell.

### crash-log

[crash-2023-11-07_16.14.02-server.txt](https://github.com/AOCAWOL/BYG/files/13290047/crash-2023-11-07_16.14.02-server.txt)

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/13290049/latest.log)

### Did you isolate BYG?

I tried BYG alone

### Did you read and understand the above agreement?

- [X] I agree.

**Comment by JT122406** [comment]
Closed in latest commit
