### ISSUE TITLE
[1.19][Bug]: CLIENT SIDE CRASH WHEN YOU TRY TO ENTER THE SERVER

### ISSUE THREAD

**Issue by chocheger** [CorgiTaco/BYG#1292]
### BYG Version

1.19.2-2.0.1.6

### Terrablender Version

1.19.2-2.0.1.166

### Mod Loader

Forge

### Mod Loader Version

43.3.0

### Bug Severity

Major

### What happened?

Always when I trying to login in my server:
![image](https://github.com/AOCAWOL/BYG/assets/58642010/55e17a1d-a6a3-4402-a182-bf81d68c79a1)
![image](https://github.com/AOCAWOL/BYG/assets/58642010/ec52b222-8eaa-4e99-b8af-d19c32cdb626)

### latest.log

minecraft not create a log because game crash and need to force to close.
Server can run, no problems buy client side always crash

### Did you isolate BYG?

I tried BYG alone

### Did you read and understand the above agreement?

- [X] I agree.

**Comment by NerjalNosk** [comment]
Have you tried entering a singleplayer world? If so does it still crash?
Have you checked whether you have the same versions of the mod and of Terrablender on both the client and the server?
If there is no crash log, is there no issue either reported in the latest log file? Or have you tried using your launcher's log tracker?

**Comment by chocheger** [comment]
> Have you tried entering a singleplayer world? If so does it still crash? Have you checked whether you have the same versions of the mod and of Terrablender on both the client and the server? If there is no crash log, is there no issue either reported in the latest log file? Or have you tried using your launcher's log tracker?

Singleplayer world no problem, no crash and can play:
![image](https://github.com/AOCAWOL/BYG/assets/58642010/e4acbb1a-a595-44ef-bfcc-da96a1cbd77f)

same version of terrablender client and server side.

No logs when I try to enter to the server, just the error:
![image](https://github.com/AOCAWOL/BYG/assets/58642010/0e99d328-5084-44a4-a05f-da02f47e6e2b)

**Comment by AwesomeDude091** [comment]
Are the mod server version and the mod client version the same

**Comment by chocheger** [comment]
> Are the mod server version and the mod client version the same

Same 
![image](https://github.com/AOCAWOL/BYG/assets/58642010/2b539db7-1717-4135-917a-0a8407594650)
![image](https://github.com/AOCAWOL/BYG/assets/58642010/0dea6545-e59b-4a00-8cb7-2544feed4ed9)

**Comment by NerjalNosk** [comment]
Sounds like a network issue to me.
I cannot say for sure, but I do not think BYG does anything network-wise, so I'd advise trying to look into other mods, if trying to remove them solves anything.

**Comment by chocheger** [comment]
I will try to remove any mods that generate structures or modify the terrain, then add them one by one.
ModList:
![image](https://github.com/AOCAWOL/BYG/assets/58642010/8da7b746-ad94-4040-8f78-43f4f7e04386)

**Comment by chocheger** [comment]
Lastlog:
https://mclo.gs/RBJXzjk

**Comment by AwesomeDude091** [comment]
Remove all mods except for BYG and see if the issue persists. If it does it's a BYG bug, if it doesn't then it's either a compat issue or it has nothing to do with BYG

**Comment by chocheger** [comment]
I got a solution, back to this versions
![image](https://github.com/AOCAWOL/BYG/assets/58642010/2f392dbb-9b63-4886-9536-7b06a57712f5)
![image](https://github.com/AOCAWOL/BYG/assets/58642010/421b25f5-85d3-4873-82f5-058c1d0fea73)

![image](https://github.com/AOCAWOL/BYG/assets/58642010/f21e15e9-3305-4089-b281-11ee54dc0b1b)

**Comment by AwesomeDude091** [comment]
So you're no longer on 1.19.2-2.0.1.6 ?

**Comment by AwesomeDude091** [comment]
Try BYG 1.19.2-2.0.1.6 with that Terrablender version

**Comment by JT122406** [comment]
> Try BYG 1.19.2-2.0.1.6 with that Terrablender version

I was gonna say since terrablender has been having some issues

**Comment by JT122406** [comment]
@chocheger did the terrablender version fix the issue? And what version
