### ISSUE TITLE
[1.18][Bug]: Saplings of any kind do not grow at all in latest version 1.5.0

### ISSUE THREAD

**Issue by mother-bhirb** [CorgiTaco/BYG#1293]
### BYG Version

1.5.0

### Terrablender Version

1.1.0.102

### Mod Loader

Forge

### Mod Loader Version

40.2.4

### Bug Severity

Major

### What happened?

Saplings of any kind in any configuration do not grow regardless of using bonemeal, waiting over time, or space. I tried this with multiple different kinds of saplings, even though I only included 2 examples in the video. This is a pretty huge bug because it means that all BYG wood is non renewable, meaning that the only way to get more is to travel to that biome, which hugely disrupts gameplay.

https://github.com/AOCAWOL/BYG/assets/76850060/bfab1fa3-4517-4082-b7a2-e3868fd8ddae

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/13402279/latest.log)

### Did you isolate BYG?

I tried BYG alone

### Did you read and understand the above agreement?

- [X] I agree.

**Comment by mother-bhirb** [comment]
After some testing, I found that this issue occurs ONLY in version 1.5.0, and does not occur in 1.4.7. Hopefully this helps narrow down the issue.

**Comment by ghost** [comment]
I encountered the same problem, which prevented the game from continuing.

**Comment by tysondanby** [comment]
I can confirm that this is an issue in 1.5.0 but not in 1.4.7

**Comment by JT122406** [comment]
Yes bug is confirmed we know it is a config issue still working on finding a solution

**Comment by JT122406** [comment]
close in #1294

**Comment by Draghera** [comment]
I have the same problem, how can I change this ? :(

**Comment by JT122406** [comment]
Update to 1.5.1

> I have the same problem, how can I change this ? :(
