### ISSUE TITLE
[1.19][Crash]: 1.19.2 Crash On Boot. Possible causes: Mixin transformation of net.minecraft.class_922 failed

### ISSUE THREAD

**Issue by Lopolin-LP** [CorgiTaco/BYG#1295]
### BYG Version

2.0.1.6

### Terrablender Version

2.0.1.166

### Mod Loader

Fabric

### Mod Loader Version

Quilt 0.22.0

### What happened?

*Before you scream "Oh you're using Quilt!!1 so that's the issue", we tried BYG alone and it worked without issues on Quilt with RAT's Mischief (which includes requiem-lite, which causes a bunch of errors in the logs)*

A friend of ours booted the modpack we created, but crashes on boot. We verified that all Mods are exactly the same and on the same version and everything is configured correctly. However, it still crashes and we have no clue why. The only Idea we have is that it may be related to a missing dedicated GPU and that it's an Intel Processor instead of an AMD one (because the logs said something about the rendering thread), but other than that, no clue.

The Logs provided are from our friend.

### crash-log

[crash-2023-12-25_17.42.00-client.txt](https://github.com/AOCAWOL/BYG/files/13766850/crash-2023-12-25_17.42.00-client.txt)

### latest.log

[latest (6).log](https://github.com/AOCAWOL/BYG/files/13766851/latest.6.log)

### Did you isolate BYG?

I tried BYG alone

### Did you read and understand the above agreement?

- [X] I agree.

**Comment by JT122406** [comment]
Can you send the byg jar you are using

**Comment by JT122406** [comment]
This isn't from byg 
Caused by: java.lang.ClassNotFoundException: ladysnake.requiem.compat.ModMenuCompat

**Comment by JT122406** [comment]
[17:41:58] [Render thread/ERROR]: Mod requiem-lite provides a broken implementation of ModMenuApi
