### ISSUE TITLE
[compatibility]

### ISSUE THREAD

**Issue by Brickboss-tech** [CorgiTaco/BYG#13]
When I have the newest versions of Oh the biomes you’ll go, better nether, and cinderscapes, the biomes from better nether don’t spawn. I’ve already talked with paulevs and he says it’s probably a problem with byg. Do you think you could look into this.

Thank you

**Comment by AOCAWOL** [comment]
We're looking into this :)

**Comment by CorgiTaco** [comment]
https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go-fabric/files/2997209

LMK if it worked

**Comment by CorgiTaco** [comment]
Should work. Comment here if it doesnt
