### ISSUE TITLE
[1.19][Crash]: Game won't start. Errors 1.

### ISSUE THREAD

**Issue by EgorimM** [CorgiTaco/BYG#1300]
### BYG Version

Oh_The_Biomes_You'll_Go-forge-1.19.2-2.0.1.6

### Terrablender Version

TerraBlender-forge-1.19.2-2.0.1.166

### Mod Loader

Forge

### Mod Loader Version

43.3.0 "Recommended"

### What happened?

These mods are installed:
BetterPvP_23.9.3_Forge_1.19.2
geckolib-forge-1.19-3.1.40
Oh_The_Biomes_You'll_Go-forge-1.19.2-2.0.1.6
OptiFine_1.19.2_HD_U_I2
TerraBlender-forge-1.19.2-2.0.1.166
CorgiLib-forge-1.19.2-1.0.0.34

When I try to load the game, it gives error 1. Without Oh The Biomes You'll Go, the game launches completely.
I tried deleting all other mods and even Optifine but it didn't help. I tried another version of the forge (43.3.7) and it didn't help either. I tried the old version of the mod (2.0.1.5 and 2.0.1.4) but the game still does not start.
What am I doing wrong? Do i need to use an older version of forge?

### crash-log

N\A

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/13990711/latest.log)
[debug.log](https://github.com/AOCAWOL/BYG/files/13990713/debug.log)

### Did you isolate BYG?

I tried BYG alone

### Did you read and understand the above agreement?

- [x] I agree.

**Comment by EgorimM** [comment]
The error was caused by TerraBlender-forge-1.19.2-2.0.1.166. Use an older version of TerraBlender.

**Comment by Venia04** [comment]
Having the same issue, but using older 2.0.1.136 version of TerraBlender doesn't help

**Comment by Venia04** [comment]
Got it to work by installing CorgiLib and GeckoLib

**Comment by CorgiTaco** [comment]
Your crash says:

```
[net.minecraftforge.fml.loading.ModSorter/LOADING]: Missing or unsupported mandatory dependencies:
	Mod ID: 'corgilib', Requested by: 'byg', Expected range: '[1.0.0.34,)', Actual version: '[MISSING]'
```

Make sure you have corgilib in your mod folder.
