### ISSUE TITLE
1.20 support?

### ISSUE THREAD

**Issue by allanonmage** [CorgiTaco/BYG#1303]
### BYG Version

TBD

### Terrablender Version

TBD

### Mod Loader

Fabric

### Mod Loader Version

TBD

### What happened?

I don't have Trello, not Discord.  The latter refuses to allow me to use my 10 year old account, and that started when I signed up.

I saw a couple of commits regarding 1.20, but nothing on Trello nor Github indicating where support for this was.  The updates on Trello seem to be from 2 years ago, though I do see recent updates for 1.19.

Are you working on 1.20 and 1.21 support?  Or is the mod abandoned?

### crash-log

I don't have Trello, not Discord.  The latter refuses to allow me to use my 10 year old account, and that started when I signed up.

I saw a couple of commits regarding 1.20, but nothing on Trello nor Github indicating where support for this was.  The updates on Trello seem to be from 2 years ago, though I do see recent updates for 1.19.

Are you working on 1.20 and 1.21 support?  Or is the mod abandoned?

### latest.log

I don't have Trello, not Discord.  The latter refuses to allow me to use my 10 year old account, and that started when I signed up.

I saw a couple of commits regarding 1.20, but nothing on Trello nor Github indicating where support for this was.  The updates on Trello seem to be from 2 years ago, though I do see recent updates for 1.19.

Are you working on 1.20 and 1.21 support?  Or is the mod abandoned?

### Did you isolate BYG?

I tried BYG alone

### Did you read and understand the above agreement?

- [X] I agree.

**Comment by CorgiTaco** [comment]
It's done when it's done, please don't open redundant issues asking for updates or etas.

**Comment by allanonmage** [comment]
I didn't see any other issues asking about it, here or on the konban, which I clearly stated, which means it's **not** redundant.  Also, you closed this as "not planned", so 1.20 is not planned?

**Comment by JT122406** [comment]
https://github.com/Potion-Studios/BYG/discussions/1203#discussioncomment-8355714
