### ISSUE TITLE
[1.16][Bug]: config does not work

### ISSUE THREAD

**Issue by Deepfriedyag** [CorgiTaco/BYG#1304]
### BYG Version

1.3.6

### Mod Loader

Forge

### Mod Loader Version

36.2.39

### Bug Severity

Minor

### What happened?

in byg-world.toml I set "controlEnd = false" , "endBiomeSize = 0" and "voidBiomeSize = 0" but the BYG biomes still keep generating in the end no matter how many new worlds I create. How can I completely disable the end biome generation? (I am using biomes o plenty world type for context)

### latest.log

[latest.log](https://github.com/Potion-Studios/BYG/files/14391565/latest.log)

### Did you isolate BYG?

I did not try BYG alone

### Did you read and understand the above agreement?

- [X] I agree.

**Comment by JT122406** [comment]
1.16 is unsupported
