### ISSUE TITLE
[1.16.3] Dedicated server hard lock on player logging in. w/ MCP: VoxelShapeSpliterator.func_234878_a_() Yarn: BlockCollisionSpliterator.offerBlockShape Mojmap: CollisionSpliterator.collisionCheck

### ISSUE THREAD

**Issue by ProsperCraft** [CorgiTaco/BYG#132]
![image](https://user-images.githubusercontent.com/4427684/96400180-563f9300-118d-11eb-9330-65adc5ee1e58.png)

forge-1.16.3-34.1.23
byg-1.0.8
Modpack - TownCraft TWO

This is a shot in the dark, I am hoping you recognize something in this profile that can help find why the server had locked up a few times.

This started when logging in a player, other players were on the server, the server became 100% unresponsive ingame and on console, until that player quit his client, then it recovered.

net.minecraft.util.math.shapes.VoxelShapeSpliterator.func_234878_a_()70.21%70000ms

byg is the only biome mod in the modpack.

**Comment by CorgiTaco** [comment]
Not sure how this is pointing to be BYG issue. Have you tested BYG on its own?

**Comment by ProsperCraft** [comment]
We can't cleanly reproduce it, we can play for days then suddenly it locks hard on that VoxelShapeSpliterator, I was just hoping with Biome in the stacktrace you might recognize it.

**Comment by CorgiTaco** [comment]
Send me the file in this screenshot on google drive. Also Send a latest.log and a crashlog(if applicable) too.

**Comment by ProsperCraft** [comment]
It never crashed, it locked up hard, then recovered.

Here is a zip of the webpage with the warmroast profile.
[Warmroast-webpage.zip](https://github.com/CorgiTaco/BYG/files/5399097/Warmroast-webpage.zip)

[Logs.zip](https://github.com/CorgiTaco/BYG/files/5399107/Logs.zip)

**Comment by ProsperCraft** [comment]
Warmroast and sampler are the only two things I have found to help diagnose a lockup, unfortunately, sampler isn't updated yet.

**Comment by ProsperCraft** [comment]
It happened again -
![image](https://user-images.githubusercontent.com/4427684/96530271-551d6d00-1244-11eb-9990-9169f2baa304.png)

**Comment by CorgiTaco** [comment]
I've been asking around about this but no one cares enough to answer me. This most likely has to do with rendering of some sort.

**Comment by CorgiTaco** [comment]
@ProsperCraft I have an idea of what it might be.... There might be a mod in your modpack that has a block larger than the block space. I read through the code a bit more and it makes sense.... You need to find that mod in question and report to them...

**Comment by CorgiTaco** [comment]
Start with any mods in your pack that might have a piston like block

**Comment by CorgiTaco** [comment]
What I mean larger than the 1x1 block space is like a hitbox/voxel shape is larger than the 1x1 block space. Basically, an oversized block voxel shape/hitbox

**Comment by CorgiTaco** [comment]
Not sure if BYG's tall plants could be causing this... I'll check later today and make sure this isn't the case, bc we should be matching Vanilla's

**Comment by Gegy** [comment]
Could this potentially be related to the vanilla structuregen deadlock? Might be worth running with the watchdog enabled to catch the state of all threads when locked

**Comment by CorgiTaco** [comment]
@ProsperCraft Im assuming you've found a solution?

**Comment by ProsperCraft** [comment]
No, it still locks up.

**Comment by CorgiTaco** [comment]
We'll wait til 1.16.4 and see what happens then... like Gegy mentioned, could be related to the deadlock.

**Comment by CorgiTaco** [comment]
Could be related to the bug patched in 1.16.4: https://bugs.mojang.com/browse/MC-199487

**Comment by ProsperCraft** [comment]
We have not had this issue since wiping the nether and end, will re-open if it happens again.
