### ISSUE TITLE
[1.19][Crash]: Mod loading error has occurred

### ISSUE THREAD

**Issue by AngelMomma** [CorgiTaco/BYG#1321]
### BYG Version

2.0.1.6

### Terrablender Version

2.0.1.136

### Mod Loader

Forge

### Mod Loader Version

43.2.14

### What happened?

Error loading mods
1 error has occurred during loading
Oh The Biomes You'll Go (byg) encountered an error during the complete event phase
jaa.lang.IllegalArgumentException: Jankson file reading (mod file extension) failed due to the following error(s): Jankson file reading for (mod file extension) failed due to the following error(s): Unknown registry key in ResourceKey[minecraft:root / corgilib:villaager_trades_item_listing]: byg:items_for_emeralds; Unknown registry key in ResourceKey...... it continues repeating itself until it talks about xp and costs and max uses...

### crash-log

[crash-2024-06-13_19.40.15-fml.txt](https://github.com/user-attachments/files/15831048/crash-2024-06-13_19.40.15-fml.txt)

### latest.log

[latest.log](https://github.com/user-attachments/files/15831057/latest.log)

### Did you isolate BYG?

I did not try BYG alone

### Did you read and understand the above agreement?

- [X] I agree.

**Comment by CaosSaber616** [comment]
You need to delete the files inside the config folder and the problem should be done.
At least that worked for me and i had the exact same problem

**Comment by JT122406** [comment]
Can confirm do what is stated above
