### ISSUE TITLE
[1.18][Bug]: Single biome Mojave desert world is broken

### ISSUE THREAD

**Issue by Cenivell** [CorgiTaco/BYG#1323]
### BYG Version

1.5.1

### Terrablender Version

1.2.0.126

### Mod Loader

Forge

### Mod Loader Version

40.2.17

### Bug Severity

Major

### What happened?

When generating a single biome world type Mojave desert it looks broken
![image](https://github.com/Potion-Studios/BYG/assets/137086607/c12bf4bb-1749-4d01-9b84-fbbcaf2f6ca4)

### latest.log

The game doesn't crash

### Did you isolate BYG?

I tried BYG alone

### Did you read and understand the above agreement?

- [x] I agree.

**Comment by CorgiTaco** [comment]
Surface rules do not work in single biome world type.
