### ISSUE TITLE
[1.16][Bug]: nether and end biomes missing, some biomes missing from the overworld aswell

### ISSUE THREAD

**Issue by Pika2007** [CorgiTaco/BYG#1325]
### BYG Version

1.3.5

### Mod Loader

Forge

### Mod Loader Version

36.2.34

### Bug Severity

Major

### What happened?

In the nether no biomes generated, in the overworld some biomes are missing (used locatebiome command, said it cant be found within reasonable range) and in the end no biomes are generated either, this is on a server and the mod was added after the world was created, is this fixable? 
![image](https://github.com/Potion-Studios/BYG/assets/175343415/88b43114-902c-4df9-97cc-99bcb54fe8f2)
![image](https://github.com/Potion-Studios/BYG/assets/175343415/b852f255-4e66-4a0b-9a79-bbb13ae8484b)
![image](https://github.com/Potion-Studios/BYG/assets/175343415/5f3dc9bc-7535-48af-b60c-92c0fcbf3c49)

### latest.log

https://gist.github.com/Pika2007/8491c1677bb0d48d74dc8614858fd109

### Did you isolate BYG?

I tried BYG alone

### Did you read and understand the above agreement?

- [X] I agree.

**Comment by JT122406** [comment]
1.16 no longer has support
