### ISSUE TITLE
[1.19][Bug]: How can I disable the Biompedia book in my inventory? 

### ISSUE THREAD

**Issue by BarsikBeliy** [CorgiTaco/BYG#1326]
### BYG Version

1.19.2

### Terrablender Version

2.0.1.166

### Mod Loader

Forge

### Mod Loader Version

2.0.1.6

### Bug Severity

Minor

### What happened?

The icon of this book covers another icon from the Diet mod
![Безымянный](https://github.com/user-attachments/assets/915f4e1f-6955-4dd8-9684-2929a33c3d88)

### latest.log

[2024-08-11-7.log.gz](https://github.com/user-attachments/files/16571017/2024-08-11-7.log.gz)

### Did you isolate BYG?

I did not try BYG alone

### Did you read and understand the above agreement?

- [x] I agree.

**Comment by JT122406** [comment]
should be a config option
