### ISSUE TITLE
[1.20.1][Bug]: Incompatibility with Slayer's Beast

### ISSUE THREAD

**Issue by MonsterDream14** [CorgiTaco/BYG#1328]
### BYG Version

beta 1.0.1 and 1.1.0

### Terrablender Version

3.0.1.7

### Mod Loader

Forge

### Mod Loader Version

47.3.5

### Bug Severity

Major

### What happened?

I crashed when loading new chunks far away because of an incompatibility with slayer's beast 1.3.0 because of bamboo then I updated to the 1.1.0 version of BYG that said in the changelog that it resolved the incompatibility and it stilled crashed. I also crashed when generating new worlds. The game crashed whilst exception generating new chunk. This is the crash log : 

Error: java.lang.IllegalStateException: Feature order cycle found, involved sources: [Reference{ResourceKey[minecraft:worldgen/biome / slayersbeasts:eucalypt_woodland]=net.minecraft.world.level.biome.Biome@517f31f4}, Reference{ResourceKey[minecraft:worldgen/biome / biomeswevegone:coniferous_forest]=net.minecraft.world.level.biome.Biome@6d1d99b}]

exit code : -805306369

The link to the full crash log is included.

### latest.log

[<script src="https://gist.github.com/MonsterDream14/a99bf7ce023ff27a183b1c7d293ce8ae.js"></script>](https://gist.github.com/MonsterDream14/a99bf7ce023ff27a183b1c7d293ce8ae)

### Did you isolate BYG?

I tried BYG alone

### Did you read and understand the above agreement?

- [X] I agree.

**Comment by JT122406** [comment]
Wrong Mod 1.20.1 is BWG, also this is a known issue there: https://github.com/Potion-Studios/Oh-The-Biomes-Weve-Gone/issues/115
