### ISSUE TITLE
[1.16][Bug]: dedicated crash

### ISSUE THREAD

**Issue by mcmso** [CorgiTaco/BYG#1331]
### BYG Version

1.3.6

### Mod Loader

Forge

### Mod Loader Version

36.2.42

### Bug Severity

Major

### What happened?

gen end biome

### latest.log

https://paste.ubuntu.com/p/gYNwB8dWzJ/

### Did you isolate BYG?

I did not try BYG alone

### Did you read and understand the above agreement?

- [X] I agree.

**Comment by JT122406** [comment]
1.16 no longer has support
