### ISSUE TITLE
[Forge 1.16.3 BYG 1.1 Alpha] Report Alpha issues here!

### ISSUE THREAD

**Issue by CorgiTaco** [CorgiTaco/BYG#134]
Fixed: 
~-Viscal isles has been disabled, Shattered Viscal Isles are in its place.~

**Comment by CorgiTaco** [comment]
-Viscal isles has been disabled, Shattered Viscal Isles are in its place.
-Tree height is not modifiable atm via datapack. All other datapacks should work fine.
-Tree Floating fillers(especially for large trees like redwoods) seem to not work? I'm not sure why.
-Dirt is not placed under trees during world gen spawning.
-Sapling logic is a bit goofy, chance of it changing.
-Most if not all surface builders are hardcoded and basically impossible to datapack.
-Datapack biomes work but seem to send out an unknown biome id sometimes for BYG's end/nether, I've implemented an unknown biome id spam protection(should spam a max of 50 times) when a biome id is unknown, it defaults to an appropriate -biome(Nether Default is Nether Wastes, End's default is End Barrens/Void) so you shouldn't see any real issues.
-No Biome dictionary data is implemented for any biomes.

**Comment by CorgiTaco** [comment]
Trees do not break grass on the bottom trunk when spawning. https://media.discordapp.net/attachments/677613796369367050/767655101196140544/unknown.png?width=794&height=702

**Comment by CorgiTaco** [comment]
Missing all 1.0 patches

**Comment by Darkosto** [comment]
Hi!

I love your mod.

Could you please add the missing biomes (fresh water lake and Frozen Lake for example) to the config to allow adjusting of weights?

I love you,
Darkosto

P.S. Seriously, great mod!

**Comment by Demlou6** [comment]
<3

**Comment by CorgiTaco** [comment]
@Darkosto These biomes are sub biomes of main biomes. Uhm I can see what i can do but I may be limited in what I have the ability of doing unless I give the ability for these to be main biomes. I can probably do this temporarily but they'll be zeroed out in the config by default. But this means they'll generate like the "Great Lakes" Biome for example

**Comment by CorgiTaco** [comment]
/locate is busted in the end(nether probably aswell)

**Comment by ProsperCraft** [comment]
Stacktrace on starting a single player world -
https://gist.github.com/ProsperCraft/70f6a76c18672b0f809416328b5844f9

byg-1.1.0-ALPHA-v3
forge .23

Here is the full client log- it locked on generating 15%
https://gist.githubusercontent.com/ProsperCraft/87ace8c43e8eab41812c86e8b686b6e5/raw/6af7948ce62b05172e2634ff80d4e8093cc24147/gistfile1.txt

java.lang.NullPointerException: Exception generating new chunk
	at appeng.worldgen.meteorite.MeteoriteStructureStart.getFalloutFromBaseBlock

**Comment by CorgiTaco** [comment]
A mod in your list is using an outdated path

**Comment by CorgiTaco** [comment]
@ProsperCraft ^

**Comment by ProsperCraft** [comment]
To which part, the stacktrace from BYG or the AE locking up on chunk gen?
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/4785

**Comment by Gerflargle** [comment]
Mod Compatability issue with Polymorph. This issue was not present in byg-1.0.8, but is in all of the 1.1 alphas.  I'm not sure who's issue it is, but I thought I would start here. 
Forge: 34.1.23
Polymorph: polymorph-forge-1.16.3-0.15.jar

> -- MOD polymorph --
> 
> Details:
> 	Caused by 0: java.lang.NoClassDefFoundError: voronoiaoc/byg/client/gui/BYGWorkbenchContainer
> 		at top.theillusivec4.polymorph.common.integrations.byg.BygModule.setup(BygModule.java:12) ~[?:1.16.3-0.15] {re:classloading}
> 		at top.theillusivec4.polymorph.Polymorph$$Lambda$10554/1279184891.accept(Unknown Source) ~[?:?] {}
> 		at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_51] {re:computing_frames}
> 		at top.theillusivec4.polymorph.Polymorph.setup(Polymorph.java:87) ~[?:1.16.3-0.15] {re:classloading}
> 		at top.theillusivec4.polymorph.Polymorph$$Lambda$5191/64558751.accept(Unknown Source) ~[?:?] {}
> 		at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-3.0.3-service.jar:?] {}
> 		at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-3.0.3-service.jar:?] {}
> 		at net.minecraftforge.eventbus.EventBus$$Lambda$2949/965674262.invoke(Unknown Source) ~[?:?] {}
> 		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.3-service.jar:?] {}
> 		at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[?:34.1] {re:classloading}
> 		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:112) ~[?:?] {re:classloading}
> 		at net.minecraftforge.fml.ModContainer$$Lambda$3331/1405357782.run(Unknown Source) ~[?:?] {}
> 		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
> 		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
> 		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
> 		at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
> 		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {}
> 		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

**Comment by CorgiTaco** [comment]
@Gerflargle def mine

**Comment by ProsperCraft** [comment]
Did you comment on this? 
java.lang.ClassNotFoundException: voronoiaoc.byg.mixin.MixinConnector

https://gist.github.com/ProsperCraft/70f6a76c18672b0f809416328b5844f9

**Comment by CorgiTaco** [comment]
I genuinely have no clue what that bug could be, besides a mod clash @ProsperCraft

**Comment by CorgiTaco** [comment]
@Darkosto Ive taken into account your suggestion. Ive added it here: https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go/files/3088315

Example from the v4 config:
https://hatebin.com/wutjqtemkn

Bare in mind more options may be added so the config may or may not change, but i doubt it will. Modded dictionary types are also allowed.

**Comment by ProsperCraft** [comment]
One thing that would be amazing in the config is ocean percentage, BOP had it in 1.7 and it went missing.  It was so nice for large servers to be able to specify I only want 20% of the world to be ocean so the players had a lot of room to build.

**Comment by ProsperCraft** [comment]
Server crash on update to byg-1.1.0-ALPHA-v4

Single player loads, but server crashes-
https://gist.github.com/ProsperCraft/81ebeb516a7d51532464c2ff205b506e

forge-1.16.3-34.1.25

**Comment by CorgiTaco** [comment]
Turns out that's a client side method expect a patch here soon

**Comment by CorgiTaco** [comment]
@ProsperCraft https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go/files/3088995

**Comment by ProsperCraft** [comment]
![2020-10-21_17 27 04](https://user-images.githubusercontent.com/4427684/96800486-ae130f80-13c2-11eb-9828-e438dea914c7.png)
Seeing a lot of this after updating to Alpha, I am guessing the worldgen changed.
Also our world clock reset, picking up immersive engineering core samples say "this is from the future, are you a time traveler?" :)

**Comment by CorgiTaco** [comment]
It probably did...

**Comment by CorgiTaco** [comment]
Squared off end biome borders

**Comment by ProsperCraft** [comment]
https://gist.github.com/ProsperCraft/d8bd8cd973ddfa42805ca10f15e398ae
On client startup - forge-1.16.3-34.1.25
byg-1.1.0-ALPHA-v6

**Comment by ProsperCraft** [comment]
Is this you he is talking about?
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/4785

**Comment by ProsperCraft** [comment]
Is this normal for just having updated the mod?
`07:50:58.695
corgiaoc.byg.BYG
modloading-worker-16
Loading config: C:\Games\Twitch\Instances\TownCraft TWO\config\byg\byg-world.toml
07:50:58.696
net.minecraftforge.common.ForgeConfigSpec
modloading-worker-16
Configuration file C:\Games\Twitch\Instances\TownCraft TWO\config\byg\byg-world.toml is not correct. Correcting`

**Comment by CorgiTaco** [comment]
I genuinely have 0 clue about the mixin connector crash

**Comment by ProsperCraft** [comment]
Please decorate with white Tulips, Pink Tulips and Allium, I can't find them anywhere, and need them for Minecolonies to build with.
![image](https://user-images.githubusercontent.com/4427684/96943500-92c50480-1495-11eb-9ff5-96ad46b291b0.png)

**Comment by AOCAWOL** [comment]
> Please decorate with white Tulips, Pink Tulips and Allium, I can't find them anywhere, and need them for Minecolonies to build with.
> ![image](https://user-images.githubusercontent.com/4427684/96943500-92c50480-1495-11eb-9ff5-96ad46b291b0.png)

In 1.1 you will be able to datapack BYG biomes! You'll have free range to add these on your own to biomes you'd like to aid your gameplay

**Comment by CorgiTaco** [comment]
https://www.curseforge.com/minecraft/mc-mods/drp-global-datapack/files^

**Comment by ProsperCraft** [comment]
So far I have been able to avoid having to learn datapacks :P  But I know it will be required eventually.

**Comment by Dumdidldum** [comment]
I also have a bug to report
Forge version: 34.1.25
Mod Version: byg-1.1.0-ALPHA-v10

When you save a world, restart the game and load the same world again the biomes are reshuffled.
Vanilla biomes don't seem to be affected by this.

World directly after generating:
![2020-10-27_12 10 45](https://user-images.githubusercontent.com/40397971/97294697-a1713a00-184e-11eb-9dce-9d9ea0f75be5.png)

Same world, same position after saving and restarting the game.
![2020-10-27_12 12 52](https://user-images.githubusercontent.com/40397971/97294701-a33afd80-184e-11eb-8b1b-8a03da6ec8d5.png)

there are also no errors about biomes in the [log](https://github.com/CorgiTaco/BYG/files/5444887/noerror.txt)

**Comment by ProsperCraft** [comment]
Yes, and the gamerules reset, this has been all of the alphas.
We have keepinventory on, and it keeps resetting to default off.
