### ISSUE TITLE
Add tags for flowers

### ISSUE THREAD

**Issue by crabdancing** [CorgiTaco/BYG#138]
Would be super useful if mods could dynamically work with BYG flower items even if new ones were added.  A tag for flowers would be great.

**Comment by AOCAWOL** [comment]
BYG already utilized the vanilla Flower, Small Flower, Tall Flower block & item tags

**Comment by crabdancing** [comment]
@AOCAWOL oh cool! Can you point me at where those tags are set in the code? I looked at your data dir and I didn't see anything. Is it done programmatically?

**Comment by CorgiTaco** [comment]
@alxpettit https://github.com/CorgiTaco/BYG/blob/Forge-1.16.X-content/src/main/resources/data/minecraft/tags/blocks/small_flowers.json

https://github.com/CorgiTaco/BYG/blob/Forge-1.16.X-content/src/main/resources/data/minecraft/tags/blocks/tall_flowers.json
