### ISSUE TITLE
[1.16.3 fabric]Blue and Green Enchanted leaves work just like X-ray

### ISSUE THREAD

**Issue by MarinaMarissa** [CorgiTaco/BYG#139]
fabric-api-0.22.1+build.409-1.16
byg-1.0.14
optifabric-1.6.4
preview_OptiFine_1.16.3_HD_U_G4_pre2
screenshots:
![2020-10-25_13 39 23](https://user-images.githubusercontent.com/61768909/97099938-65f93300-16c9-11eb-8bc7-2eabd15c5b65.png)
![2020-10-25_13 39 25](https://user-images.githubusercontent.com/61768909/97099939-685b8d00-16c9-11eb-9301-b2190b20d188.png)
![2020-10-25_13 42 41](https://user-images.githubusercontent.com/61768909/97099941-6db8d780-16c9-11eb-99fc-75cfc1d4cb32.png)

**Comment by K0-RR** [comment]
https://github.com/CorgiTaco/BYG/issues/137

"In this file - BYG 1.0.14 - the issue is still present and now enchanted leaves work kinda like x-ray too (see screenshot below)
https://ibb.co/JrGMMhf"

**Comment by CorgiTaco** [comment]
Comment back here if the issue occurs in this file:  https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go-fabric/files/3096796
