### ISSUE TITLE
Current Active spawning 1.15.2 Biome List

### ISSUE THREAD

**Issue by Voronoiii** [CorgiTaco/BYG#14]
1. Allium Fields
2. Alps
3. Amaranth FIelds
4. Blue Giant Taiga
5. Blue Taiga
6. Deciduous Forest
7. Dunes
8. Grassland Plateau
9. Jacaranda Forest
10. Prairie
11. Red Desert
12. Red Dunes
13. Red Oak Forest
14. Seasonal Birch Forest
15. Seasonal Deciduous Forest
16. Seasonal Forest
17. Seasonal Giant Taiga
18. ShrubLands
19. Snowy Blue Giant Taiga
20. Snowy Giant Taiga
21. Boreal Forest

**Comment by CorgiTaco** [comment]
Never Updated. Closing this.
