### ISSUE TITLE
Forge 1.16 - biome registry names changed

### ISSUE THREAD

**Issue by bessiq** [CorgiTaco/BYG#14]
MC 1.16.1
Forge 32.0.47
byg-1.0.1

Hi,

I just updated to byg-1.0.1 and noticed many biome registry names have changed (underscores removed). This breaks the display name for them, which I am not too concerned about since it's just a cosmetic issue. I did want to see if the changes were intentional before I update other configs that reference those biomes, though.

Also, the new biome setup using the JSON file is working, but I was wondering if it has to use those exact seeds or if they are just placeholders.

(p.s. Embur Bog looks awesome.)

Thanks!

**Comment by CorgiTaco** [comment]
Unintentional ill fix it

**Comment by CorgiTaco** [comment]
Now ima have to leave this open bc i already know what's coming :| 

https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go/files/2997173
