### ISSUE TITLE
[1.16.3 / 1.0.8] Minecraft won´t load; Reason: Locked Registry

### ISSUE THREAD

**Issue by Nyx019** [CorgiTaco/BYG#143]
Whenever I add the mod to the mods folder, the game crashes upon launch because of a rendering issue with particles: "Failed to load description for particle [particle name]." 

When I ONLY have BYG installed and NO other mods AT ALL, minecraft fails to load with the following error message:
"Failure message: Oh The Biomes You'll Go (byg) encountered an error during the load_registries event phase java.lang.ExceptionInInitializerError: null
Mod Version: 1.0.8 
Exception message: java.lang.IllegalStateException: Can not register to a locked registry. Modder should use Forge Register methods."

I attached the full crashlog. With both the newest version of forge, and the newest version of BYG, it seems to be impossible to load Minecraft.

[crash-2020-10-28_19.15.41-fml.txt](https://github.com/CorgiTaco/BYG/files/5454086/crash-2020-10-28_19.15.41-fml.txt)

**Comment by CorgiTaco** [comment]
Downgrade forge to version .25
