### ISSUE TITLE
[Fabric 1.16.3] Crash/incompatibility on 1.1 beta

### ISSUE THREAD

**Issue by Zentheon** [CorgiTaco/BYG#144]
Got a crash after attempting to use the beta version uploaded recently. This is also coming from a set of mods that the 1.0.14 version has no issues with.
[crash-2020-10-28_20.47.35-server.txt](https://github.com/CorgiTaco/BYG/files/5455853/crash-2020-10-28_20.47.35-server.txt)

**Comment by Zentheon** [comment]
also my bad I didn't notice the dedicated page for these reports

**Comment by CorgiTaco** [comment]
All good. And this is weird......

**Comment by Zentheon** [comment]
I can test a bit more and attempt to isolate whatever's causing the issue if that helps

**Comment by CorgiTaco** [comment]
This might be an issue with the BYG jar itself. Bc these NoClassDefFoundError are inconsistent

**Comment by CorgiTaco** [comment]
Like several users are reporting this issue but it's happening with several class targets although they all exist

**Comment by Zentheon** [comment]
Ahh, huh. Well, I'll stay posted, good luck with it!

**Comment by CorgiTaco** [comment]
Patched: https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go-fabric/files/3095934
