### ISSUE TITLE
[BYG 1.1 Beta] Report Beta issues here!

### ISSUE THREAD

**Issue by CorgiTaco** [CorgiTaco/BYG#145]

**Comment by Silvrus** [comment]
Hello, I got a crash using just BYG with Forge 34.1.32. https://pastebin.com/u7QcSBMt

**Comment by CorgiTaco** [comment]
> Hello, I got a crash using just BYG with Forge 34.1.32. https://pastebin.com/u7QcSBMt

Update your forge version

**Comment by bessiq** [comment]
blue sage be like:

![image](https://user-images.githubusercontent.com/7315505/97714049-0a4af300-1a97-11eb-8f68-cc7478adcc7f.png)

Also, looks like `en_us.json` got left out of the jar. 😢 🗽

**Comment by CorgiTaco** [comment]
@bessiq what version fabric or forge?

**Comment by bessiq** [comment]
Oh yeah, sorry. 

Biomes You Go 1.1-BETA-v2 MCV: 1.16.3
Forge 34.1.25

**Comment by Asmidus** [comment]
on fabric's latest version nether quartz desert generates stuff above the bedrock. Not a huge issue but worth mentioning

**Comment by CorgiTaco** [comment]
[
![Jdk-8 0 272 10-hotspot Screenshot 2020 10 30 - 11 22 41 48](https://user-images.githubusercontent.com/66983020/97743023-4b94d000-1aa2-11eb-8174-eda86a779bbf.png)
](url)

@Asmidus I do not see what you're going on about?

**Comment by Asmidus** [comment]
Probably a different conflict then, I'll look more into it

**Comment by bessiq** [comment]
That reminded me - beta v2 on Forge .25  - Withering Woods generates trees on Nether roof.

Update: Weeping Mire does still also. And small mushrooms generate on the roof in pretty much every biome, but I don't think that is a BYG issue?

![image](https://user-images.githubusercontent.com/7315505/97743370-eb128c80-1abb-11eb-84ef-a9b313c9aa82.png)

**Comment by Asmidus** [comment]
I can't plant lament saplings on the blocks they generate on in the weeping_mire biome, same with withering oak saplings in the wailing garth and likely other trees in the new nether biomes.

**Comment by CorgiTaco** [comment]
Zelkova Boats crash games brrrrrrrrrrt
