### ISSUE TITLE
Suggestion: nether quartz ore variants

### ISSUE THREAD

**Issue by bessiq** [CorgiTaco/BYG#148]
I decided to try my hand at basic texture editing/creation, and have been making some ore variants for my own pack. They don't seem too shabby, so I thought I'd share in case you wanted to use them at some point. The provided zip file contains textures, loot tables, lang, tags, and recipes for `blue netherrack` and `brimstone` quartz ore.

I won't take offense if you're just not feeling it or it doesn't fit your design goals for those zones, but thought I'd offer since I made it anyway lol. I also don't care about attribution/acknowledgment, and you can of course modify it to your heart's content.

I'm also mashing up textures for many modded ores with BYG and Unearthed stone types - again, for my own purposes. But I can share those as well when they're further along if you'd like to take a look.

BYG is looking better every day. Keep up the good work!

[byg_quartz_ore_variants.zip](https://github.com/CorgiTaco/BYG/files/5465792/byg_quartz_ore_variants.zip)

![2020-10-29 (1)](https://user-images.githubusercontent.com/7315505/97720421-a5939680-1a9e-11eb-9aeb-88dfe85d5de9.png)
![2020-10-29](https://user-images.githubusercontent.com/7315505/97720423-a62c2d00-1a9e-11eb-83b8-ca565f1cef11.png)

**Comment by AOCAWOL** [comment]
will be available in the upcoming update
