### ISSUE TITLE
multiple incompatabilities with other mods

### ISSUE THREAD

**Issue by christomite** [CorgiTaco/BYG#149]
Here is my crash log when i remove byg everything works 
[crash-2020-10-30_14.06.45-client.txt](https://github.com/CorgiTaco/BYG/files/5467123/crash-2020-10-30_14.06.45-client.txt)
[2020-10-30-1.log.gz](https://github.com/CorgiTaco/BYG/files/5467128/2020-10-30-1.log.gz)

**Comment by CorgiTaco** [comment]
Downgrade your forge version or use our latest beta file
