### ISSUE TITLE
[1.16.1] Server World doesn't save "failed to save chunk" when structures are added from other mods in the BYG worldtype. Mojang Bug: MC-194811.

### ISSUE THREAD

**Issue by Gbergz** [CorgiTaco/BYG#15]
Title^
Works fine when the **world-type** is not BYG. (default)

Worlds auto saves once in awhile but you can trigger the errors in the console by typing "/save-all".

**BYG Version:** 1.0.6
**MC:** 1.16.1
**Forge:** 32.0.51

Logs: https://gist.github.com/Gbergz/672fa95722196e55ef1d7cc7df6d52ed
Debug Logs: https://gist.github.com/Gbergz/ddde4538ae10ca2c4d6b0ea61039ddb1

Any ideas?
- Gbergz

**Comment by CorgiTaco** [comment]
Alright to point something out, it seems to be searching for a nonexistent structure so you might have a mod doing that. Also, **have you made sure the byg alone and the world type by itself functions for you?** It seems there's a mod creating/having an unknown structure. Because all structures in 1.16 are broken, Any sort of structure mod will/is automatically assumed to be broken. Line 4955 in the first file(logs) I see a spam of unknown structure starts.

**Comment by Gbergz** [comment]
Tried removing Hunter Illager and it worked for awhile and I thought the issue was solved, it was not. The issue happened again later on.

Debug Log: https://gist.github.com/Gbergz/3e82e454e1f23f807ef720025dd6d9bf
Normal Log: https://gist.github.com/Gbergz/8139c183c341a9ff592bf53871a50477

Look far down on the logs

**Comment by CorgiTaco** [comment]
Again, have you used BYG by itself?

**Comment by Gbergz** [comment]
Oh yeah sorry. Yes I have it doesn't appear to happen when I do that.. 
But then again it doesn't seem happen always on my server. Just sometimes. It's weird. Could happen with your mod installed and if it does I haven't gotten it just yet.

**Comment by CorgiTaco** [comment]
I'm thinking a mod conflict. Most definitely isn't BYG's fault but I'm going to leave this open. If it does happen with BYG independently please lmk. Also, clean all those errors up in your log, it's a nightmare to read :/

**Comment by CorgiTaco** [comment]
Alright update on this, another user reported a similar issue in regards too this. So I am going to now assume this is my mod's fault. I'm going to see about receiving help in regards too this!

**Comment by Gbergz** [comment]
Update on this. 
I have now been removing mods 1 by 1 until the Chunk Saving issues were gone. And finally I atleast think I've found what mod does this. It's [End Reborn](https://www.curseforge.com/minecraft/mc-mods/end-reborn). I've tested alot and no Chunk Saving issues occur when this mod is removed. 

This issue was present when only this mod was installed. Removing it and also creating a new world solves it.
So previous worlds with this mod installed "corrupts" the world or something.

**Comment by Gbergz** [comment]
And now users have reported this still happening- but only sometimes.
Seems like the mod repurposed structures (fabric version) attempted to fix this issue and says there's an issue with this update in general(1.16.1) and blames mojang.

``A Mojang bug that breaks worlds and is caused by missing structures``

**Comment by CorgiTaco** [comment]
Mojang has received a bug report in regards to this: https://bugs.mojang.com/browse/MC-194811

**Comment by Gbergz** [comment]
Yes, saw this. Here's hoping 1.16.2 will fix this annoying issue..

**Comment by CorgiTaco** [comment]
Agreed. I'm going to leave this open if anyone else wants to come along and report it. But the issue has been renamed.

**Comment by CorgiTaco** [comment]
More info: https://github.com/FabricMC/fabric/issues/654

**Comment by Linguardium** [comment]
fabric: update on related news. It seems that null protection is offered for structures but not structure references. i5 found the code responsible for (at least one of) the NPE occurring when building the structure reference map during game load (and subsequently trying to reference the null entries during game save) and has a patch to fix it. Not sure what the status is but at least work is ongoing.

not sure how forge is going to handle it, but one would surmise a mixin could handle that on forge side (until either forge fixes it or mojang does)

**Comment by CorgiTaco** [comment]
Going to close this as this out of the scope of BYG and the worldtype is removed in 1.16.2
