### ISSUE TITLE
[1.16.3 Fabric] [BYG 1.1 MCV] red_rock_lowlands generating tall spikes

### ISSUE THREAD

**Issue by vedranskarica** [CorgiTaco/BYG#151]
I assume this wasn't the intended look of the red rock lowlands
![2020-10-31_17 33 07](https://user-images.githubusercontent.com/7735672/97785492-af53f180-1ba5-11eb-9741-4d6f9eb0a444.jpg)

Looks like something's off in the height distribution in RedRockLowlandsSB.

**Comment by CorgiTaco** [comment]
Intended behavior
