### ISSUE TITLE
[1.16.3] Forge 34.1.35 servers cannot start.

### ISSUE THREAD

**Issue by Cixon** [CorgiTaco/BYG#152]
### API/Modloader
Forge.

### Describe the bug
While attempting to load the latest BYG version and older (v1.0.8), the server throws error fail to start.

### To Reproduce
1.) Install latest 1.16.3 forge server (34.1.35)
2.) Add BYG forge.
3.) See log.

### Expected behavior
Server loading successfully, functional Forge 34.1.35 server.

Screenshot:
![Screenshot (451)](https://user-images.githubusercontent.com/69068153/97812134-f47b3080-1c44-11eb-80ff-7a85c6cd0b95.png)

**Context:** Yes I was using an older build of BYG in this screenshot but still applies to latest build.

### Logs
[crash-2020-11-01_13.19.07-fml.txt](https://github.com/CorgiTaco/BYG/files/5471594/crash-2020-11-01_13.19.07-fml.txt)
[debug.log](https://github.com/CorgiTaco/BYG/files/5471593/debug.log)
[latest.log](https://github.com/CorgiTaco/BYG/files/5471592/latest.log)

**Comment by Cixon** [comment]
?

**Comment by CorgiTaco** [comment]
Duplicate. We no longer support BYG versions under 1.1 please update! And this issue has been resolved in 1.1 aswell.

**Comment by CorgiTaco** [comment]
@Cixon https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go/files/3098350
