### ISSUE TITLE
[1.16.3][Fabric] Conflict with Packed Storage mod

### ISSUE THREAD

**Issue by Campbell314** [CorgiTaco/BYG#156]
![BYG Slab Issue](https://user-images.githubusercontent.com/46504188/98452628-fee67000-2105-11eb-961d-33331e5e1e8e.jpg)

I think this is due to Packed Storage mod removing the recipe for vanilla chests. Placing non-vanilla planks in the crafting table in any but very specific crafting slots, creates a vanilla chest (e.g. placing planks in the middle row is the only way to create slabs. Any other row creates a chest as shown in picture). Placing a single plank in any crafting slot except the center slot, creates a vanilla chest etc..

Removing the Packed Storage mod fixed the problem.

**Comment by CorgiTaco** [comment]
Looks like something you need to report to them not us. if byg works entirely fine on its own, then this isnt our bug
