### ISSUE TITLE
Block durability values (specifically for pickaxes)

### ISSUE THREAD

**Issue by Placeholder456** [CorgiTaco/BYG#157]
It seems like various blocks such as the soapstone, red rock, or scoria...or actually any block supposed to be mine by any pickaxe cannot be broken properly, with both vanilla tools and modded.

The block breaks as usual but the item does not drop. I am running a server with friends with BetterEnd which adds extra tools and those pickaxes dont work either.

This bug also runs through singleplayer

**Comment by K0-RR** [comment]
Everything works for me.

**Comment by CorgiTaco** [comment]
You need to be more clear about what you mean by this? @Placeholder456

**Comment by AOCAWOL** [comment]
closed because the user won't specify and this works fine for everyone else
