### ISSUE TITLE
[Fabric 1.16.3] Unable to create stripped Logs from BYG logs w/ Blockus

### ISSUE THREAD

**Issue by Ariselir** [CorgiTaco/BYG#158]
__**Describe the bug**__
What is the bug? Where/How does it occur? etc.
Simply put, it seems impossible to strip BYG logs.

__**To Reproduce**__
Provide step by step instructions
Just Right Click a BYG log with any Axe, Vanilla or BYG, and the log will not convert into i't's stripped form.

**Expected behavior**
It's expected to strip just like a normal log like Vanilla logs.

**Comment by CorgiTaco** [comment]
Seems to be a mod conflict where someone is wiping this list, so you need to figure that out and report the issue to them. But I've just tested it w/ byg on its own anddddd it works: https://i.imgur.com/BYHQyBu.mp4. (Im using the latest version off curseforge aswell).

**Comment by CorgiTaco** [comment]
@Ariselir Turns out the mod conflict is with blockus, you'll need to remove it for the time being until they get around to patching it.

**Comment by CorgiTaco** [comment]
Patched here: https://www.curseforge.com/minecraft/mc-mods/blockus/files/3110038
