### ISSUE TITLE
Add config ControlOverworld

### ISSUE THREAD

**Issue by xorinzor** [CorgiTaco/BYG#159]
**Is your feature request related to a problem? Please describe.**
Kind of, I'd like to use BYG to only generate the end, since it contains some nice diverse End biomes which other mods unfortunately do not have (at least not with Forge 1.16.3). But I don't want BYG influencing the generation of the Overworld and the Nether.

**Describe the solution you'd like**
Add a `ControlOverworld` config option, this already exists for the Nether and the End.

**Describe alternatives you've considered**
I tried editing the level.dat to edit the worldgen propery for just the End to the `byg` equivalent. Unfortunately this didn't work and it still influenced the overworld chunk generation.

**Comment by CorgiTaco** [comment]
You can mark the weight of all overworld biomes as 0 in the config.

**Comment by xorinzor** [comment]
Not quite as practical (also something that would've to be kept in mind with updates, as new biomes could be added to the config), but for now it does the trick. Thanks.

I'd still like to ask to reconsider adding a dedicated config option for this, given the reason I just gave.
