### ISSUE TITLE
[Fabric][1.16.1] Vanilla Nether biomes aren't generated with this mod installed

### ISSUE THREAD

**Issue by enzalito** [CorgiTaco/BYG#16]
I don't really know if this is a bug or if this is intended but it's a shame that it isn't possible to play with the new Nether biomes and the modded ones at the same time, it would be so cool. Currently, only the 3 modded biomes you added are generating so 90% of the content that was implemented in the Nether update is basically inaccessible in survival.

Mod version: 1.0.5

![2020-07-08_17 11 36](https://user-images.githubusercontent.com/52015993/86936366-30423580-c13e-11ea-8f22-0cec4f24ca19.png)

**Comment by CorgiTaco** [comment]
Patched: https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go-fabric/files/3001588

Lmk if it works
