### ISSUE TITLE
Cryptic Magma Block has no drops.

### ISSUE THREAD

**Issue by grundyboy34** [CorgiTaco/BYG#160]
__**API/Modloader**__
Forge 34.1.42
BYG: 1.1.2

__**Describe the bug**__
Cryptic Magma Blocks are simply destroyed with no drops, no matter which pickaxe is used to mine them. I've also tested using TNT, and they do not drop that way as well.

__**To Reproduce**__
1) Start new creative world
2) Place Cryptic Magma Blocks
3) Spawn different pickaxes
4) Change gamemode to survival
5) Try to mine the magma blocks with the different pickaxes
6) Notice the block never drops, it's only destroyed

**Expected behavior**
For magma blocks to drop when mined.

**Comment by AOCAWOL** [comment]
fixed
