### ISSUE TITLE
Make BYG stone variants generate is vanilla biomes and biomes from other mods like Terrestria./// Byg stones in Unaerthed.

### ISSUE THREAD

**Issue by K0-RR** [CorgiTaco/BYG#164]
Your stone variants are great and it's a shame they don't generate everywhere where stone is. Can you add them to Unearthed maybe?

**Comment by CorgiTaco** [comment]
I mean they do? https://github.com/CorgiTaco/BYG/blob/3f83426187fc2458790c07e1deb8395dbd7535ea/src/main/java/corgiaoc/byg/mixin/server/MixinMinecraftServer.java#L44

**Comment by CorgiTaco** [comment]
And you're missing a lot of information too like what version you're using. So for that, I'm out

**Comment by K0-RR** [comment]
Sorry, I think I was a little retarded yesterday...
