### ISSUE TITLE
Saplings and their growth do not act consistently

### ISSUE THREAD

**Issue by SatDog92** [CorgiTaco/BYG#171]
**Problems and features that lack here.**
While this mod adds a beautiful variety of plant structures, their behavior isn't really consistent and do not follow vanilla Minecraft's rules.
All the examples of the problem are listed below:

1- Certain saplings do not grow on dirt, only on grass: palo verde, ether saplings, lament saplings, nightshade saplings, palmtree saplings, withering oak.
These seem to not grow on ether soil/phylium and vermilion skulk either, the only blocks they will grow on is the vanilla grass block. Shouldn't they growon any kind of dirt type blocks (except mycelium blocks where you can only plant and grow red and brown mushrooms) as it happens with every other sapling (including vanilla ones)?
2- Mangrove trees generating floating one block above the ground after being grown from their respective saplings (this is more like a bug and not an intended feature).
3- None of the mod fungi can be placed on mycelium netherrack and vermilion skulk, as they act like ordinary vanilla fungi. But the Nether fungi should at least act like the Crimson and Warped ones, not like the ordinary pre-1.16 mushrooms.
4- Oddity bushes cannot be placed on the shulkren phylium and warped bush cannot be placed at all (do these act like dried bush, though? I admit i tested the features on Creative instead of directly going on survival).
5- It seems that saplings grow on ether phylium/soil (it's technically grass/dirt) and vermilion skulk (weird). I guess it's intended, though? Cause, as reported above, fungi cannot be planted on vermilion skulk.
6- Embur warts can oddly grow on ether phylium. Is this intended?
7- Sythian fungus grows on sythian netherrack (obviously), on overgrown netherrack,  and on ether phylium, but not on other types of grounds. Weirdly, cannot be bulk-grown like the vanilla fungi. Cannot be placed on dirt type blocks like the vanilla fungi.
8- Bulbis oddities can grow on every end grass blocks. They can be bulk-grown.
9- Shulkren fungus can grow on any end grass type block but cannot be bulk-grown (similar to vanilla red/brown mushrooms). Shouldn't they grow only on its respective block?
10- Blue and purple glowshroom can grow on ether phylium and overgrown netherrack, not in others. Cannot bulk grow (like red/brown mushroom) and cannot be placed on dirt type blocks.
11- Soul shroom, weeping milkaps, wood blewit and death cap seem to behave consistently for 1.16 standards, except they can't be placed on mycelium netherrack  and vermilion skulk.
12 - Embur Nylium grows correctly on Blue Netherrack when next to another Embur Nylium block, but the same doesn't apply to any other Nylium/Phylium types. Shouldn't they all act like Warped and Crimson Nylium?

**Possible solutions**
- The Overworld Mod mushrooms should act like red and brown vanilla ones: can be placed on nylium, phylium and mycelium blocks even if sky is exposed, can be placed on any stone and netherrack type. Mushrooms that do not appear in multiple dimensions shouln't grow on dimensions different from their origin, as it happens in vanilla. They should have also a corresponding nylium/phylium type and shouldn't grow on different type of grounds, similar to crimson and warped fungi (example: sythian warts shouldn't grow on ether phylium/soil, only on sythian nylium).
- Tree saplings should grow on any type of ground that isn't mycelium, nylium or phylium, but they can grow on overgrown netherrack. Not sure if special types found in the End should have their own grounds like the fungi, but it's weird that nightshade saplings cannot even be placed on nightshade phylium.
- Sythian warts should be bulk grown, but i feel like almost everyone of them should (even if you can't do that with red and brown mushrooms).
- Growing nylium and phylium on netherrack and end stone respectively should be implemented as vanilla did with crimson and warped nylium. Embur nylium with blue netherrack, in fact, does act like vanilla.

And that's it. I really like this content, but should be more consistent, at least i know i can grow plants and mushrooms on their corresponding soil as it happens with the vanilla game.

**Alternatives**
Not many, i believe

**Additional context**
There is no specific additional context, i guess.

**Comment by CorgiTaco** [comment]
Could you point out whether you're on fabric or forge please

**Comment by SatDog92** [comment]
My bad. These issues are present either on Forge and Fabric. 

Furthermore, on Fabric, doing further tests, you can't even place byg's saplings on byg ground-related blocks like meadow grass/dirt and overgrown dacite/netherrack, while you can on overgrown stone blocks (you can do that on Forge). Still on Fabric, regarding end saplings like ether and nightshade ones, they can't even be grown at all, as they cannot be planted on any phylium but only on grass where they won't grow. Mushrooms also act weird on Fabric: nether byg ones don't act like vanilla ones (crimson and warped fungi, which on turn, on both versions, can't be placed on end phylium in turn, even if they don't grow there i feel they should when), and the overworld byg ones can't even be put on stone and ground blocks if not exposed to sun. These Fabric issues are not present in Forge.

I wasn't sure if to put this under bugs or suggestions, i just felt like that these behavior are problematic on survival mode.

**Comment by CorgiTaco** [comment]
Alright this behemoth list of bugs should be patched(I think)
