### ISSUE TITLE
Shovel can't turn meadow grass block into grass path

### ISSUE THREAD

**Issue by toktoktheeo** [CorgiTaco/BYG#180]
Latest version (1.1.3) - Fabric

__**Describe the bug**__
Right clicking with a shovel on a meadow grass block doesn't turn it into a grass path block.

__**To Reproduce**__
Right click with any shovel on a meadow grass block, nothing happens.

**Expected behavior**
The meadow grass block should turn into a grass path block.

**Comment by CorgiTaco** [comment]
Patched

**Comment by Dagrik4923** [comment]
This issue still persist in Forge 1.16.5-36.2.35

Tested the same way as author.
