### ISSUE TITLE
[FABRIC 1.16.3] The vanilla bookshelf recipe overrides most BYG bookshelves

### ISSUE THREAD

**Issue by artisjoke** [CorgiTaco/BYG#182]
**Before filling out this issue: **
**1. We only support the latest version of BYG on for Minor Bugs.**
**2. Please test BYG on its own to confirm whether or not this is a mod conflict.**

__**Mod conflict? If so, please clarify which mod is conflicting!**__

__**API/Modloader**__
Forge/Fabric?
Fabric

__**Describe the bug**__
What is the bug? Where/How does it occur? etc.
While the recipe for all BYG bookshelves are present, most are overridden by the vanilla bookshelf when crafting.

__**To Reproduce**__
Provide step by step instructions
Only the following wood types produce their respective bookshelves:
Aspen, ether, fir, holly, jacaranda, maple, palm, rainbow eucalyptus, redwood, and witch hazel.

If you try to craft a bookshelf with any other BYG wood type, you get a vanilla bookshelf.

**Expected behavior**
I expected to create a bookcase of the same wood type as the planks.

![2020-12-02_12 06 08](https://user-images.githubusercontent.com/66725555/100864845-df3d3000-3496-11eb-9074-ddba70e87799.png)

**Comment by AOCAWOL** [comment]
unfortun. we do not support 1.16.3 and we also have not been able to replicate this issue.
