### ISSUE TITLE
Redwood Slabs don't Drop Item When Broken

### ISSUE THREAD

**Issue by desagas** [CorgiTaco/BYG#183]
Forge 35.1.4, BYG version BYG1.1.5

Redwood slabs do not drop an item when broken. This is true for both top and bottom slabs, as well as stacked slabs.

**Comment by andrewsf** [comment]
It was missing a loot table, but that loot table got added 11 days ago.

https://github.com/CorgiTaco/BYG/blob/Forge-1.16.X/src/main/resources/data/byg/loot_tables/blocks/redwood_slab.json

**Comment by desagas** [comment]
Added, but not yet released.

**Comment by CorgiTaco** [comment]
Patched
