### ISSUE TITLE
Different minor bugs regarding End structures, Vines, biome-specific Villagers and Frosted Magma)

### ISSUE THREAD

**Issue by SatDog92** [CorgiTaco/BYG#185]
__**Forge (v.35.1.0, latest recommended) and Fabric (Api v.0.27.1)**__
Below it is specified which versions are affected.

__**Bugs**__
1-End Cities are completely engulfed by big purpur block structures from Purpur Peaks, and partially by obsidian ones from Ivis Field. They can still be digged, but yikes! Happens on both versions.
2-Still in the End, the same big structures are generated completely cut off if bordered to another biome. Happens with every big rock structure like the ones from Ivis Field or Shattered Desert. Happens on both versions.
3-The tip of the Shulkren and Lament Vines won't let you climb up this type of vines and also slow you down more than other types of vine (intended?). Embur Gel Vines cannot be stacked as Weeping and Twisted vines. (intended too?). Hanging bones behave correctly but cannot be placed almost anywhere. (example: can be placed under bone blocks but not under quartz sand where they generate, and cannot be stacked as Weeping/Twisted vines). Happens on both versions.
4-More like an unintended behavior than a bug: Villagers and Zombie Villagers in custom biomes that areare always generated with their plain clothes (example: in swamp-related areas villagers are not generated in swamp clothes but with the "standard" ones). Happens on both versions.
5-Frosted Magma are displayed weirdly. When looked from inside walls while on spectaror they are displayed as "void cubes" instead of not being displayed when engulfed by solid blocks as it happens with every other block, as if they weren't connected to other solid blocks. In turn, they are also displayed incorrectly under lava/water, where their flow is overlapped on the block's texture. Only Forge is affected.

__**To Reproduce**__
1-For End Cities just create a single biome world with BYG end biomes that contains big structures (the problem is present in a normal world as well)
2-Just get to the End and look for biomes with large structures.
3-Find or place the described types of vines. Try to climb Shulkren and Lament Vines jumping from below starting from the tip with the player's upper box part (head and chest).
4-Use Villagers and Zombie Villager spawn eggs on BYG biomes that don't fall in the category of temperate climate.
5-Visit the "Subzero Hypogeal" biome or place some Frosted Magma blocks underwater or under lava or get inside walls to see them from inside.

**Expected behavior**
1-End Cities shouldn't be engulfed by other structures.
2-These big structures (i suppose they are generated with the new datapack custom biome-dimension generation from 1.16, right?)
3-They should at least be able to be climbed from below, as the tip of the vines won't allow me to climb them. The ones which can't be placed or stack should be able to be placed and stacked.
4-Villagers and Zombie Villagers should generate with biome-specific clothes in non-plains/forest biomes like Desert, Jungles, Taigas and Swamp types, as it happens in Vanilla Minecraft.
5-Their textures should be connected and shouldn't be displayed as "void cubes" inside solid blocks but act like the rest of the latters.

**Screenshots/Videos**
1-End Cities: [img1](https://i.imgur.com/MDTr2If.png), [img2](https://i.imgur.com/XaieF2a.png), [img3](https://i.imgur.com/kU8vBcp.png), [img4](https://i.imgur.com/5q1jVVx.png), [img5](https://i.imgur.com/TAjNXd5.png) are about Purpur Peaks biomes ([img6](https://i.imgur.com/nMU4Of9.png) has shader but this happens without shaders and Optifine as well, it was an older picture). Regarding Ivis Field: [img7](https://i.imgur.com/DoeRVKt.png), [img8](https://i.imgur.com/CikiSfo.png), [img9](https://i.imgur.com/AJ7M3bd.png).
2-Cutoff structures: Ivis Field exampls: [img1](https://i.imgur.com/dmobV0L.png), [img2](https://i.imgur.com/I8QF2Gm.png) and [img3](https://i.imgur.com/WwfQMln.png). Shattered Desert examples: [img1](https://i.imgur.com/uMTc54t.png) and [img2](https://i.imgur.com/OgD1Irq.png).
4-Villagers and Zombie Villagers: Bayou examples ([img1 ](https://i.imgur.com/ZwnnK7X.png)and [img2](https://i.imgur.com/gHhvgSM.png)), Blue Taiga example ([img3](https://i.imgur.com/f40bIps.png)) and Lush Tundra example ([img4](https://i.imgur.com/n0S3vcj.png)).
5-Frosted Magma: [img1](https://i.imgur.com/VrguZUt.png), [img2](https://i.imgur.com/YzCoXOc.png) and [img3](https://i.imgur.com/helcZ18.png).

**Mod Conflict**
None, no other mod was used.

**Additional context**
None

**Logs**
[byglogs.zip](https://github.com/CorgiTaco/BYG/files/5651764/byglogs.zip) for Forge,
[byglogfabric.log](https://github.com/CorgiTaco/BYG/files/5651938/byglogfabric.log) for Fabric,

Sorry for reporting multiple minor bugs in a single issue thread but didn't feel like posting five different issues one after one about minor bugs without looking like spammy.

**Comment by CorgiTaco** [comment]
1. We can't do anything about this as this is a vanilla issue with End City Placement, so I'ma say intentional behavior.
2. Intentional behavior
3. I'll check it out
4. Zombie villagers/villagers clothing is hardcoded in a way that's difficult to expand upon(I'll double check this but I doubt there's anything I can do)
5. This is getting patched

**Comment by SatDog92** [comment]
Regarding point 4, Biomes o' Plenty manages to implement this feature, so i thought this was possible (not that every mod has to be like Bo'P, it's just that if a feature like that was there it would be better) but it also might have to do with this one mod's code, and that's where i stop as my knowledges are limited from this point.

**Comment by CorgiTaco** [comment]
Alright 5 is patched. 4. is added
