### ISSUE TITLE
inconsistency in bonemealing saplings on different blocks

### ISSUE THREAD

**Issue by mschlin2** [CorgiTaco/BYG#186]
Environment--
BYG 1.1.5
Forge 35.0.18

__**API/Modloader**__
Forge 35.0.

__**Describe the bug**__
Certain saplings that are able to grow on minecraft:grass_block / byg:overgrown_netherrack (AKA any block that defines itself as grass) are unable to grow on normal minecraft:dirt.

In particular, Lament, Nightshade, Ether, Palm, Palo Verde, and Withering Oak saplings suffer from this problem. I tested growing every other (grass-growable) sapling on dirt and grass and they grow fine. It's just these few.

I also noticed that the bulbis saplings, while they can't be placed on grass/dirt, can be placed on any nylium block (both vanilla and BYG types), but can't be grown. AFAIK they can only be grown on the ether grass block, but correct me if i'm wrong. I don't know if this is intended behavior or not so I'm just noting it here.

ALSO-- I just found this, but the meadow grass block doesn't work either with these saplings.

__**To Reproduce**__
1.) Take any Lament, Nightshade, Ether, Palm, Palo Verde, and Withering Oak sapling and place it on dirt.
2.) Spam bonemeal on it for at least 30 seconds.
3.) It doesn't grow.
4.) Do the same thing but instead place them on grass. It grows.

**Expected behavior**
Lament, Nightshade, Ether, Palm, Palo Verde, and Withering Oak saplings are able to grow on both dirt and grass, just like every other sapling in BYG that can grow on grass.

**Comment by CorgiTaco** [comment]
Patched
