### ISSUE TITLE
Add tools & armor to the appropriate Fabric tool tags

### ISSUE THREAD

**Issue by K0-RR** [CorgiTaco/BYG#187]
Can You add support for [Tiered](https://www.curseforge.com/minecraft/mc-mods/tiered) mod? Mod [GitHub](https://github.com/Draylar/tiered).
This mod gives tools, armor, and weapons random qualities when they enter your inventory, inspired by Terraria tools. All the qualities, as well as the tools that can get them, are completely configurable.
![image](https://user-images.githubusercontent.com/43277609/101697272-ce348600-3a77-11eb-9bfa-03d5a2913954.png)

Seems like You would need to do this - "Mods need to add their tools to the respective tags inside the fabric namespace (fabric:pickaxes, fabric:chestplates, fabric:shovels, etc.)" - https://github.com/Draylar/tiered/issues/12

**Comment by AOCAWOL** [comment]
We can def. add our tools & armor to those tags :)
