### ISSUE TITLE
BYG entities in flowerpots crashes servers

### ISSUE THREAD

**Issue by IAhughes** [CorgiTaco/BYG#188]
**Before filling out this issue: **
**mod is 1.1.5
**2. Please test BYG on its own to confirm whether or not this is a mod conflict**
 It is the mod itself
__**API/Modloader**__
Forge

__**Describe the bug**__
When placing any of the BYG saplings into the minecraft flower pot it causes an untextured block to temporarily appear then immediately crashes the server

__**To Reproduce**__
take any BYG sapling and place into a minecraft flower pot

**Expected behavior**
an immediate crash occurs or on singleplayer an untextured block appears 

**Additional context**
not every sapling was tested but orchard sapling was definitely causing the issue 

**Logs**
Use: https://paste.ee/ and paste the links. if log is huge please upload those
Please provide:
Crashlog - https://paste.ee/p/0gICJ
Debug.log - 
[debug.log](https://github.com/CorgiTaco/BYG/files/5676332/debug.log)

Latest.log - 
[latest.log](https://github.com/CorgiTaco/BYG/files/5676336/latest.log)

**Comment by CorgiTaco** [comment]
You did not Isolate BYG and assure this is a mod conflict and by reading the very first line of your crashlog this is a crash caused by Dynmap not BYG

**Comment by CorgiTaco** [comment]
They have an issue open for this very error. https://github.com/webbukkit/dynmap/issues/3190
