### ISSUE TITLE
[1.16.4] Packed Black Ice should be crafted out of 9 Black Ice, for parity with normal Ice

### ISSUE THREAD

**Issue by aaronhowser1** [CorgiTaco/BYG#191]
__**API/Modloader**__
Forge

__**Describe the bug**__
Packed Black Ice has no crafting recipe

__**To Reproduce**__
Fail to craft Packed Black Ice

**Expected behavior**
9 Black Ice should craft Packed Black Ice

**Comment by CorgiTaco** [comment]
Patched
