### ISSUE TITLE
[Suggestion] Add compatibility for Inventory Tabs mod.

### ISSUE THREAD

**Issue by K0-RR** [CorgiTaco/BYG#192]
This mod adds tabs to the player inventory for **nearby** chests and other storages.
[Mod spotlight](https://youtu.be/WiGthregLwU?t=13)

If I understand correctly to add compatibility You would need to "Chest tabs are tabs belonging to chests that are able to double up along the horizontal axis. To **register your chest, pass the block reference to TabProviderRegistry#registerChest**. Chests that do not match vanilla chest behavior should not use this method." - https://github.com/cakewhip/inventorytabs#chest-tabs

**Comment by AOCAWOL** [comment]
BYG doesn't add Chests?

**Comment by CorgiTaco** [comment]
Not sure how this is relevant to BYG as we do not have chests of any kind

**Comment by K0-RR** [comment]
Yes, sorry for wasting Your time. The chests I was talking about come from BetterNether. I thought I deleted BetterNether because it isn't compatible with jellysquid3's Hydrogen mod but instead I removed Hydrogen. I should have checked twice.
Can I ask do You plan to add chests from your wood types?

**Comment by CorgiTaco** [comment]
At this time, we do not
