### ISSUE TITLE
[1.16.4]Pink sand is missing item tags

### ISSUE THREAD

**Issue by jinkhya** [CorgiTaco/BYG#196]
__**API/Modloader**__
Forge

__**Describe the bug**__
What is the bug? Where/How does it occur? etc.
Pink sand doesn't have the same tags as the other sands from byg. Some other mods use tags to allow cross compatibility like environmental tech 3. Result being the resource void miner from that mod can provide all the sands from byg (blue, purple, black, white) but not the pink one :) 

**Expected behavior**
The pink sand to have item tag forge:sand like the others

**Screenshots/Videos**
Purple Sand for example
https://i.imgur.com/g0syzSj.png
Pink Sand
https://i.imgur.com/9REQGxb.png

**Comment by AOCAWOL** [comment]
Fixed ^-^
