### ISSUE TITLE
[Bug][1.16.4][ModConflict?] Biomes shift after adding Vampirism to already generated world with modded biomes

### ISSUE THREAD

**Issue by drakray** [CorgiTaco/BYG#197]
see https://github.com/TeamLapen/Vampirism/issues/818 for more details

SUMMARY:
When adding Vampirism to my pack, if I start a world where the map is already generated, the modded Biomes shifts.
There is no crash, but the BYG.AlliumField become Vampirism.VampireForest, BYG.Bayou => BYG.AutumnalValley
BiomesOPlenty don't show this shift
Shift is not registered in level.dat BiomeRegistry

**Comment by CorgiTaco** [comment]
Let's say....
The biome mods I have installed are BYG(Numerical ID's are 100 - 125), BOP(126 - 155), and Prehistoric Fauna(156 - 207).
I create a new world. the biome at 0, 0 is a PHF Hell's Creek.
Only the Biome numerical ID is saved to the chunk so... PHF Hell's Creek in this case is 157.
So biome numerical ID 157 is stored at 0, 0.
Alright... BYG just got an update and they added 3 new biomes. So what happens? Well....
The biome mods I have installed are now BYG(Numerical ID's are 100 - 128), BOP(129 - 158), and Prehistoric Fauna(159 - 210).
So now the biome at 0, 0 still has the numerical ID 157 but.... the ID's have shifted, now the biome at 0, 0 is a Biomes O Plenty Alps Biome.

I recommend that you use the latest version of your modloader as the issue has been fixed for sure.
Forge: http://files.minecraftforge.net/ or if that doesn't work, https://www.curseforge.com/minecraft/mc-mods/chocolate-fix/files
Fabric: https://fabricmc.net/use/ & https://www.curseforge.com/minecraft/mc-mods/fabric-api/files
