### ISSUE TITLE
Freshwater lake spawns fish a bit too frequently

### ISSUE THREAD

**Issue by f-raZ0R** [CorgiTaco/BYG#20]
![2020-07-12_16 47 16](https://user-images.githubusercontent.com/30442287/87256571-e620c300-c461-11ea-85f3-e5c45e3d8b37.png)
(I USED THE EXPERIMENTAL WORLD TYPE)
My fps was at 4, and after killing all of them with /kill, it ended up killing over 6000 fish. And they spawned back in rapidly. No idea if this is a bug with BYG, or if it's a bug with forge... but since it happened in a BYG biome, i'm reporting it here.

**Comment by CorgiTaco** [comment]
What version 1.15.2? Fabric or forge? BYG Version?

**Comment by f-raZ0R** [comment]
1.16.1
forge. 
1.0.7

**Comment by f-raZ0R** [comment]
mod list:
yung's better caves
yung's better mineshafts
biomes you go
end reborn
janoeo
janoeo-arsenal
jei
lightest lamp
mekanism
mekanism generators
mekanism tools
pamhc2food
waystones

**Comment by f-raZ0R** [comment]
just have to wait for that to be put into an official release, and I can finally turn on the mobspawning gamerule and not have to worry about my game lagging from too many fish! Seriously they just kept spawning and wouldn't stop, my framerate was chugging until i killed them all and stopped them from spawning!

**Comment by CorgiTaco** [comment]
1.16 added a new spawn group and we didn't switch too it so rip FPS & Servers lol

**Comment by CorgiTaco** [comment]
*we didnt know about it*

**Comment by f-raZ0R** [comment]
oops all EntityClassification.WATER_AMBIENT

**Comment by CorgiTaco** [comment]
Patched here: https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go/files/3003305

Thnx for reporting =D

**Comment by CorgiTaco** [comment]
*it is under review smh*
