### ISSUE TITLE
Stone blocks missing standard crafting table and furnace recipes

### ISSUE THREAD

**Issue by FewerFlaws** [CorgiTaco/BYG#201]
**1. We only support the latest version of BYG on for Minor Bugs.**
Understood.

**2. Please test BYG on its own to confirm whether or not this is a mod conflict.**
Confirmed.  Tested with only BYG and its dependencies.

__**Mod conflict?
No.

__**API/Modloader**__
Fabric.

__**Describe the bug**__
What is the bug? Where/How does it occur? etc.
All stone items are missing crafting table recipes to create related blocks.  Stairs, slabs, and walls all have standard patterns.  Standard patterns exist for converting blocks into decorative versions.  Pillars are not standardized since PurPur uses slabs and quartz uses full blocks, but there should still be a crafting table recipe for every pillar in BYG.

__**To Reproduce**__
Provide step by step instructions

Place a crafting table.  Use six Dacite blocks to try to make Dacite stairs.  Observe that this does not work.  Repeat with any stone, trying to make stairs, slabs, walls, pillars, or decorative blocks.

**Expected behavior**
The following should function for Dacite, Dacite Bricks, Dacite Cobblestone, Dacite Tile, Mossy Stone, Red Rock, Red Rock Bricks, Mossy Red Rock Bricks, Chiseled Red Rock Bricks, Cracked Red Rock Bricks, Rocky Stone, Scoria Stone (with pillar), Scoria Cobblestone, Scoria Stonebricks, Soapstone (with pillar), Polished Soapstone, Soapstone Bricks, Soapstone Tile.

-Placing six stone blocks in the known pattern for stairs should produce a stack of four stairs.
-Placing three stone blocks in the known pattern for slabs should produce a stack of six slabs.
-Placing six stone blocks in the known pattern for walls should produce a stack of six walls.

The following should function for Dacite, Scoria, and Soapstone:
-Placing two (slabs or blocks) in the known pattern for pillars should produce a stack of (one or two) pillars.

The following should also work to produce decorative blocks:
2×1 Dacite Slab -> 6×Dacite Tile
2×2 Red Rock -> 4×Red Rock Bricks
2×1 Red Rock slabs -> 1×Chiseled Red Rock Brick
Red Rock Bricks in furnace -> Cracked Red Rock Bricks
2×2 Scoria Stone -> 4×Scoria Stonebricks
2×2 Soapstone -> 4×Polished soapstone
2×1 Soapstone Slab -> Soapstone Tile

**Comment by FewerFlaws** [comment]
Notably, Dacite Bricks and Soapstone Bricks are left off of this list.  I think it's best that they are accessible only through the stonecutter since vanilla bricks are made using a 2×2 pattern of bricks and there is no similiar ingredient for Dacite and Soapstone.

**Comment by FewerFlaws** [comment]
Oh, black, white, blue, purple, and pink sandstone crafting table recipes are also missing.  Stairs, slabs, and walls, chiseled, and cut recipes for each.

**Comment by CorgiTaco** [comment]
Works as intended. We wanted the stones to be unique to the stone cutter.

**Comment by AOCAWOL** [comment]
This isn't a bug, for gameplay intentions, we have made all stone recipes only use the StoneCutter.
