### ISSUE TITLE
Smooth sandstone should be a furnace recipe

### ISSUE THREAD

**Issue by FewerFlaws** [CorgiTaco/BYG#202]
__**API/Modloader**__
Fabric

__**Describe the bug**__
Black, white, blue, purple, and pink sandstone is converted to its smooth variant on a stonecutter table.  Vanilla sandstone is converted to its smooth variant in a furnace.   This is inconsistent.

__**To Reproduce**__
Put colored sandstone in a furnace.  Nothing happens.  Put vanilla sandstone on a stonecutter table.  The smooth variant does not appear.

**Expected behavior**
Black, white, blue, purple, and pink sandstone should smelt into its smooth variant using a furnace.  The smooth sandstone recipe should not be accessible through the stonecutter table at all.

**Comment by AOCAWOL** [comment]
Ty, we did not realize that this was how it was made, an inconsistency on our part that we will adjust in our upcoming patch :)
