### ISSUE TITLE
BYG crafting tables dont use fastworkbench recipe caching changes resulting in serverwide crafting lag

### ISSUE THREAD

**Issue by Peach774** [CorgiTaco/BYG#203]
__**API/Modloader**__
Forge

__**Describe the bug**__
If you use a BYG crafting table, it lags when shift-clicking stacks of items like vanilla crafting tables do. This is fixed in fastworkbench and many mods implement this fix. This needs to be implemented in BYG.
__**To Reproduce**__
Crafting a full stack of items on a server by shift-clicking.
**Expected behavior**
It should not lag, but it does.

**Additional context**
https://www.curseforge.com/minecraft/mc-mods/fastworkbench

You can see here the changes made and i believe the dev has a guide on how to implement the recipe caching to prevent

**Comment by CorgiTaco** [comment]
Read what you said "it lags when shift-clicking stacks of items like **vanilla crafting tables do**" we will respect vanilla behavior. Fast Workbench can support BYG if they'd like but we ourselves will not be making such changes at this time.
