### ISSUE TITLE
[Not BYG related] Any way to disable vanilla biomes?

### ISSUE THREAD

**Issue by K0-RR** [CorgiTaco/BYG#204]
I know this isn't a place for this but where else can I gain this information?

I have played mc for a long time, nearly all vanilla biomes are boring to me so I use biome mods. Still, vanilla biomes do generate but not so common. I would like to completely prohibit many of them from generating. I can't find a way to do it so is it even possible? Maybe via datapack?

**Comment by CorgiTaco** [comment]
This is the BYG issue tracker. Anyways, this would require a seperate mod to do so
