### ISSUE TITLE
No nether and end biomes 

### ISSUE THREAD

**Issue by DamienBrittan** [CorgiTaco/BYG#207]
edited. sorry for the first time.
**2. Please test BYG on its own to confirm whether or not this is a mod conflict.**
works fine by it's own
__**Mod conflict? If so, please clarify which mod is conflicting!**__
I'm not sure .. maybe biomesoplenty or betterend(forge) both last versions 

**Logs**
debug : too large , sorry 
latest : https://paste.ee/p/CsUNy

__**API/Modloader**__
Forge

__**Describe the bug**__
What is the bug? Where/How does it occur? etc.
No nether biomes

__**To Reproduce**__
Provide step by step instructions
Enter nether ./locatebiome 
**Expected behavior**
Spawn nether biomes
**Screenshots/Videos**
If applicable, add screenshots/video to help explain your problem.
https://imgur.com/a/KnDJVzQ

**Comment by CorgiTaco** [comment]
You didnt answer whether or not you have other mods present and it seems to me you didnt test byg in an isolated instance. Andddd you didnt give me any sort of logs. You've basically left me with 0 information. Provide more details and I'll consider this an issue. For now Im closing this

**Comment by DamienBrittan** [comment]
Updated ! Sorry again .

**Comment by DamienBrittan** [comment]
> You didnt answer whether or not you have other mods present and it seems to me you didnt test byg in an isolated instance. Andddd you didnt give me any sort of logs. You've basically left me with 0 information. Provide more details and I'll consider this an issue. For now Im closing this

Updated . Sorry for the first time .

**Comment by CaspianMacky** [comment]
This happens when you have BoP and BYG at the same time, make a BoP world, and don't use the datapack (pinned on the Discord) that adds BYG biomes to the other dimensions. Get the datapack and it should resolve the issue.

**Comment by DamienBrittan** [comment]
After deleting BOP biomes are spawning in nether and end again .

**Comment by kernegal** [comment]
The problem appears to occur with BOP world type. Tried it in a world with the default type but with BOP and it works fine. Also, it doesn't seem to spawn the hill biomes. I have not tested it with other sub-biomes
