### ISSUE TITLE
Vanilla crafting table recipe overrides unique wood crafting tables, making them uncraftable

### ISSUE THREAD

**Issue by f-raZ0R** [CorgiTaco/BYG#21]
Version affected: 1.16.1
mod version: 1.0.7 forge
note: i only tested this with willow so far, and noticed the recipe conflict, trying to craft the willow crafting table just gives you a vanilla crafting table.

**Comment by CorgiTaco** [comment]
Try using the recipe book. But this is really out of our control because of vanilla tags, it's more or less a roll of the dice whether it'll let you craft or not.

**Comment by f-raZ0R** [comment]
Ah... shame that you aren't able to adjust vanilla tags...
