### ISSUE TITLE
River Biome Issue

### ISSUE THREAD

**Issue by CaspianMacky** [CorgiTaco/BYG#211]
**Before filling out this issue: **
**1. We only support the latest version of BYG on for Minor Bugs.**
**2. Please test BYG on its own to confirm whether or not this is a mod conflict.**

I've only seen it once or twice, so I'm not sure if it's a conflict or not. The only other mods I had active both times were Optifine, Wyrmroost, Tetra, Better End, Enderite, and the Undergarden, none of which affect (overworld) terrain gen.

__**Mod conflict? If so, please clarify which mod is conflicting!**__

__**API/Modloader**__
Forge/Fabric?

Forge

__**Describe the bug**__
What is the bug? Where/How does it occur? etc.

Some biomes occur in long, windy strips along rivers. When this is red rock lowlands, it also usually has some weird pillars floating above the water- I don't know if this is the same bug or a different one.

__**To Reproduce**__
Provide step by step instructions

¯\_(ツ)_/¯
Sorry, I don't know what specific circumstances could cause it. I haven't found any in BYG-only worlds. The closest I have is seed 4534173154869774397, at the Crag Gardens around 2600, 2000. It's not quite the same as what I saw in the screenshots below, but it's close.

**Expected behavior**

**Screenshots/Videos**
If applicable, add screenshots/video to help explain your problem.

![2020-12-25_18 08 22](https://user-images.githubusercontent.com/54872198/103253447-d67d3400-4946-11eb-96af-b69cfb7cc34f.png)
![2020-12-28_17 21 31](https://user-images.githubusercontent.com/54872198/103253449-d8df8e00-4946-11eb-9551-7e090bc1cb61.png)

**Additional context**

**Logs**
Use: https://paste.ee/ and paste the links. if log is huge please upload those
Please provide:
Crashlog - 
Debug.log - 
Latest.log -

**Comment by CorgiTaco** [comment]
The river is an edge biome of the crag gardens, if you do not like this, see the "byg-biomes.json" config and remove it from the crag garden's assigned edge biome
