### ISSUE TITLE
Chunky Void Biomes

### ISSUE THREAD

**Issue by Syrikal** [CorgiTaco/BYG#212]
**Before filling out this issue: **
**1. We only support the latest version of BYG on for Minor Bugs.**
**2. Please test BYG on its own to confirm whether or not this is a mod conflict.**

Double-checked, and yes, it's present with only BYG. Some of my screenshots include Better End and Quark, but it's definitely not a conflict.

__**Mod conflict? If so, please clarify which mod is conflicting!**__

__**API/Modloader**__
Forge/Fabric?

Forge.

__**Describe the bug**__
What is the bug? Where/How does it occur? etc.

In the End there are occasional spots where Viscal Isles and End Barrens biomes spawn on large islands in a distinctive grid pattern. There's a little variation on the edges, but the biomes follow chunk borders very closely.

__**To Reproduce**__
Provide step by step instructions

-Go to the End
-Use /locatebiome to find Viscal Isles
-Look for Viscal blocks on nearby large islands
-if there's no example nearby, find another Viscal Isles biome and repeat

**Expected behavior**

**Screenshots/Videos**
If applicable, add screenshots/video to help explain your problem.

![2020-12-28_20 13 55](https://user-images.githubusercontent.com/76715986/103254528-45f52280-494b-11eb-8b5c-c43b458cb683.png)
![2020-12-28_18 08 20](https://user-images.githubusercontent.com/76715986/103254533-4e4d5d80-494b-11eb-8be2-2d8d3418b6ca.png)
![2020-12-28_18 10 59](https://user-images.githubusercontent.com/76715986/103254537-53aaa800-494b-11eb-9aba-e62101e8ebfd.png)
![2020-12-28_18 11 32](https://user-images.githubusercontent.com/76715986/103254538-54dbd500-494b-11eb-9eb1-3a67b19869f2.png)
![2020-12-28_18 21 26](https://user-images.githubusercontent.com/76715986/103254545-57d6c580-494b-11eb-8d40-18e9d4163510.png)
![2020-12-28_18 26 41](https://user-images.githubusercontent.com/76715986/103254549-5a391f80-494b-11eb-8870-cfdb68d70615.png)
![2020-12-28_20 13 55](https://user-images.githubusercontent.com/76715986/103254554-5c02e300-494b-11eb-8e3a-3510fbde04fc.png)
![2020-12-28_20 14 11](https://user-images.githubusercontent.com/76715986/103254556-5dcca680-494b-11eb-9f70-48ecee0fd852.png)
![2020-12-28_20 15 17](https://user-images.githubusercontent.com/76715986/103254560-5efdd380-494b-11eb-9d61-7d57a442bca8.png)
![2020-12-28_20 20 16](https://user-images.githubusercontent.com/76715986/103254562-602f0080-494b-11eb-8af0-753f0e56ce7a.png)

**Additional context**

**Logs**
Use: https://paste.ee/ and paste the links. if log is huge please upload those
Please provide:
Crashlog - 
Debug.log - 
Latest.log -

**Comment by CorgiTaco** [comment]
How vanilla End Biome Source noise works. So we will not be fixing it
