### ISSUE TITLE
Coloured sandstone should have slabs (regular, cut, smooth)

### ISSUE THREAD

**Issue by FewerFlaws** [CorgiTaco/BYG#215]
__**API/Modloader**__
Fabric

__**Describe the bug**__
Vanilla sandstone has slabs of the regular, cut, and smooth varieties.  Black, white, blue, purple, and pink sandstone have no slabs at all.

**Expected behavior**
Coloured sandstone should come in the same varieties as vanilla sandstone.

**Comment by CorgiTaco** [comment]
I believe this is the case in the current version
