### ISSUE TITLE
Coloured sandstone should have walls and stairs

### ISSUE THREAD

**Issue by FewerFlaws** [CorgiTaco/BYG#216]
__**API/Modloader**__
Fabric

__**Describe the bug**__
Vanilla sandstone has walls and stairs.  Black, white, blue, purple, and pink sandstone do not have stairs and walls.

**Expected behavior**
Coloured sandstone should have the same variants as vanilla sandstone.

**Comment by AOCAWOL** [comment]
will be added in the future patch

**Comment by CorgiTaco** [comment]
I believe this is the case in the current version
