### ISSUE TITLE
Biome generation errors

### ISSUE THREAD

**Issue by toktoktheeo** [CorgiTaco/BYG#217]
__**API/Modloader**__
Forge 35.1.28
Minecraft 1.16.4
BYG 1.1.5

__**Describe the bug**__
When I create a new world or load a world I got this in the console:

[18:11:32] [Netty Local Client IO #0/ERROR] [minecraft/BiomeGenerationSettings]: Feature: Not a JSON object: "minecraft:freeze_top_layer"

__**To Reproduce**__
Add the mod to the modlist and watch the console when creating or joining a world.

**Expected behavior**
To not have these errors.

**Additional context**
I got the same issue with the Fabric version.

**Logs**
https://pastebin.com/3fbWGPZH

**Comment by CorgiTaco** [comment]
Fix but not released, keep an eye out for it
