### ISSUE TITLE
Chiselled coloured sandstone crafting table recipes are missing

### ISSUE THREAD

**Issue by saltyseadoggo** [CorgiTaco/BYG#222]
__**API/Modloader**__
Fabric

__**Describe the bug**__
One cannot craft chiselled black, white, blue, purple or pink sandstone in the crafting table the way one can with vanilla regular and red sandstone.

**Expected behavior**
Arranging two coloured sandstone slabs, one above the other, in a crafting table would yield one chiselled sandstone of the same colour. See the vanilla recipe.

**Comment by CorgiTaco** [comment]
@saltyseadoggo I'd appreciate any sort of asset/data PRs to be merged into the forge branch from this point forward as we just overwrite all the fabric assets/data on the fabric branch when we port the forge branch to fabric from this point forward

**Comment by saltyseadoggo** [comment]
Got it. I was following the example of a previous asset PR by merging to Fabric branch.~

**Comment by AOCAWOL** [comment]
Slabs, Stairs, Walls, etc. have not been implemented for the BYG sandstones. Please use a Stonecutter to acquire the other sandstone blocks. These blocks will be coming in a future patch

**Comment by CorgiTaco** [comment]
I believe this is the case in the current version
