### ISSUE TITLE
Missing stone variant recipes

### ISSUE THREAD

**Issue by saltyseadoggo** [CorgiTaco/BYG#223]
__**API/Modloader**__
Fabric

__**Describe the bug**__
After creating my pull request to fix numerous crafting parity issues with red rock, I've learned that all of BYG's other stone types lack similar recipes. The specific missing recipes are as follows:
- Slabs, stairs and walls made of all stone variants except for red rock cannot be made in the crafting table with the vanilla slab/stair/wall recipe shapes.
- Dacite and Scoria cannot be made into Dacite Bricks and Scoria Bricks in the same manner that stone or end stone can be made into stone bricks or end stone bricks.
- Soapstone cannot be made into Polished Soapstone in the same manner that andesite, diorite, granite or blackstone can be made into their polished forms.
- Polished Soapstone cannot be made into Soapstone Bricks in the same manner that polished blackstone can be made into polished blackstone bricks.

**Expected behavior**
I would expect the above recipes to be present and usable. Whilst the stonecutter gets the job done in making these blocks obtainable, the crafting table is generally more useful for crafting large quantities of these blocks faster.
Pillars and tiles can either stay as stonecutter exclusives, or have recipes invented for them at your disclosure.

**Comment by Angular-Angel** [comment]
Also, the recipe for scoria cobblestone slabs in the stonecutter only gives one slab, instead of two as for vanilla cobblestone slabs.

**Comment by AOCAWOL** [comment]
So, this is intended. We at first wanted all stone-related things to be exclusive via stonecutter but a lot of users found it confusing. We will be working in a future patch to bring crafting recipes to all the stone & sandstones but for our current patch this is not a concern, for now, please use the stonecutter.
