### ISSUE TITLE
Bookshelf and Crafting table wood variants should be configurable

### ISSUE THREAD

**Issue by FewerFlaws** [CorgiTaco/BYG#224]
**Is your feature request related to a problem? Please describe.**
Vanilla crafting tables and bookshelves do not have variants.  Terrestria, biome makeover, and wild explorer all add new wood types but do not include crafting tables or bookshelves.  For consistency I would prefer to disable these variants in BYG.

**Describe the solution you'd like**
I would like an option in config that removes variant crafting tables and bookshelves from all wood types in the mod.  Disabling the recipes and using vanilla crafting tables and bookshelves in structures + loot tables would suffice for this.

**Describe alternatives you've considered**
I can overwrite recipes and loot tables manually then hide the item in REI, but I'm worried that these blocks will still appear as part of structures.  Adding crafting table and bookshelf variants for vanilla woods as well as those introduced by other mods would be better, but is not feasible for me while testing several components for a new high-quality mod pack.  Also, that change is outside the scope of BYG.

**Additional context**
I'm also concerned about whether the crafting tables here use the improvements made in [FastBench for Fabric](https://www.curseforge.com/minecraft/mc-mods/fastbench-for-fabric).  Variant wooden items beyond those matching vanilla may be part of an update to the mod pack after a first release, but they are too much work right now.

**Comment by CorgiTaco** [comment]
As cool as this is, this is basically impossible to do on forge, yes you play fabric but have to try and keep the differences between forge and fabric minimal. And anyways, you can make a datapack and remove recipes. And this also presents the issue that our datapack would break(no recipes, drops, etc) if someone disables them. It's just really complex and impossible to do this in a way that's clean.
