### ISSUE TITLE
[1.16.4]Forge (byg-1.1.5) - Campfires doesn't make smoke.

### ISSUE THREAD

**Issue by Raderg** [CorgiTaco/BYG#227]
![2021-01-03_17 42 29](https://user-images.githubusercontent.com/30061643/103483948-3e21fc00-4deb-11eb-9fdd-e184191a86ea.png)

**Comment by AOCAWOL** [comment]
this is intentional :)

**Comment by AOCAWOL** [comment]
for more explanation, we wanted users to have an option without the smoke since it can be quite annoying or laggy to some users. This just allows for more variety for players who want to utilize campfires without them creating a ton of particle lag.
