### ISSUE TITLE
Giving other turf blocks (meadow grass, nylium variants, etc.) support for optifine's better grass option.

### ISSUE THREAD

**Issue by Corvus20** [CorgiTaco/BYG#228]
I love to play with optifine's better grass option enabled, it makes hills less jarring by covering the side of turf-type blocks with their top texture, it makes them look smoother. I noticed, however, that many of the turf blocks from this mod don't do the same, and it makes landscapes look inconsistent, some biomes having smooth-looking hills, and some others don't.

Implementing support for optifine's better grass texture function would definitely increase the visual cohesiveness of BYG. Biomes O Plenty has done this with their turf blocks, so it is definitely possible. Or just adding a separate config option for "better turf textures" to change the textures to ones with all but the bottom side of the block with the top texture would work just fine too.

I have tried to think of other solutions to this issue, but the only ones really are playing with the better grass option off (it looks uglier, but is more cohesive), have better grass on and deal with the inconsistent textures between vanilla, BYG, and other mod biome's turf (what I am currently doing, and the main reason I made this post), or just removing BYG to preserve cohesion (I do not want to do this, the sheer amount of amazing biomes this mod adds is not something I am willing to part with)

I am unsure if this has already been asked, or if it is already implemented and I am not doing something right. Anyways, I still love this mod regardless of this small gripe I have. Keep up the good work, I can't wait to see what comes next!

**Comment by CorgiTaco** [comment]
I'm not sure how to do that and i quite frankly don't exactly care about supporting Optifine and that's probably impossible to do snyways. They probably have a config some where you can assign this but other than that, no thnx
