### ISSUE TITLE
Fabric 1.16.1 - duplicated nether biomes mixed noise points

### ISSUE THREAD

**Issue by Linguardium** [CorgiTaco/BYG#23]
[main/INFO]: [STDOUT]: WARNING: biome.byg.embur_bog and biome.byg.glowstone_gardens have the same mixed noise points! They won't generate properly!!!!

**Comment by CorgiTaco** [comment]
eh i mixin the biome provider so this shouldnt exactly matter :p

**Comment by Linguardium** [comment]
that only happens when smolder or better nether dont exist though, right?

**Comment by CorgiTaco** [comment]
https://github.com/CorgiTaco/BYG/blob/43f88c4d0f7087daf9e8cebaf045dfad0fc89b7e/src/main/java/voronoiaoc/byg/mixin/common/MixinDimensionType.java#L18

**Comment by Linguardium** [comment]
https://github.com/CorgiTaco/BYG/blob/43f88c4d0f7087daf9e8cebaf045dfad0fc89b7e/src/main/java/voronoiaoc/byg/mixin/common/MixinDimensionType.java#L19

**Comment by CorgiTaco** [comment]
Should be patched here:
https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go-fabric/files/3004842
LMK If it aint
