### ISSUE TITLE
Add Biome Keys

### ISSUE THREAD

**Issue by Noaaan** [CorgiTaco/BYG#230]
Hello! I am the developer of Mythic Metals, and I wanted to add support for my ores in your biomes. 

Some of my ores are biome specific, only spawning in specific types of biomes like in Jungle biomes or Ocean biomes. Since you are not using BiomeKeys I cannot use FabricAPI's `BiomeModifications` to implement this. I am able to use the `builtin` check for overworld/nether ores, but not for the biome specific ones.

Please consider adding it

**Comment by CorgiTaco** [comment]
`Registrykey.of(Registry.BIOME-KEY, BuiltinRegistries.BIOME.getId(<biome object target>));`

`Registrykey.of(Registry.BIOME-KEY, new Identifier("byg", <biomepath>));`

Either of those should work. But I will NOT be migrating to the usage of biome keys if my current implementation works fine. That'd be quite of bit of unnecessary work tbh

**Comment by Noaaan** [comment]
This seems to work. You would not have to migrate the entire registry code to use BiomeKeys in order for it to work, you would just need to register them, making many mods more compatible with BYG.
