### ISSUE TITLE
[Feature/compatibility fix] registering a world type so mods like Terraforged can detect the nether & end biomes to use them in world generation

### ISSUE THREAD

**Issue by Corvus20** [CorgiTaco/BYG#231]
I am finding it difficult to get BYG to work with Terraforged, as the biomes for the nether and end do not generate properly. leaving them vanilla, when there should be BYG biomes.

I chatted with one of the main devs of Terraforged, dags, when I was initially trying to figure out what was going on with the biomes not generating. Apparently, BYG needs to register a world type with forge in order to be detected by Terraforged (and likely other mods that use this same method). They provided me with a link to some forge info related to this, which they wanted me to pass on to you.: https://github.com/MinecraftForge/MinecraftForge/blob/1.16.x/src/main/java/net/minecraftforge/common/world/ForgeWorldType.java

Without this compatibility, BYG cannot be used with Terraforged and have Nether/End biomes generate. Sure, the overworld would still have BYG biomes, but it wouldn't be the full experience without the nether or end biomes. Alternatively, I could use another mod with similar biomes to this one, but I would rather not sacrifice this mod, there is so much I would miss from it.

I am by no means a member of the Terraforged team, I am a discord member, and I hardly know how modding works. If you are confused by anything I said, try talking with dags, they could probably relay this info far better than I could.

**Comment by CorgiTaco** [comment]
Nope this is wrong. Byg is picked up by terraforged as I play with it myself. We're not adding a worldtype to add to the  confusion

**Comment by CorgiTaco** [comment]
Hmm you need to title your issues better as I've actually read it on discord that this is about nether & end biomes

**Comment by CorgiTaco** [comment]
Fixed in latest beta
