### ISSUE TITLE
TerraForged Dimensional Support

### ISSUE THREAD

**Issue by Kowantify** [CorgiTaco/BYG#233]
I'm currently using terra forged and biomes you'll go works incredible with it! But, when going to Dimensions, BYG isn't registered as a exact dimension per say or something, it won't render those biomes and therefore missing out on the AMAZING biomes in the end and the nether, idk how to fix this and creating a new world, and then going into level.dat is a lil tedious for my modpack which having to make everyone do that when they play is a little tedious, but I 100% understand if it isn't in the vision of the mod, just a request is all, i appreciate the mod its truly amazing.

**Comment by CorgiTaco** [comment]
did it work?

**Comment by Kowantify** [comment]
Yes

**Comment by Koji-KAWAHARA** [comment]
Could you tell me how you fixed it? Im currently stuck at the same problem. No BYG biome shows up in the nether and the end. Did you change any code or dat file?

MC 1.16.4
Forge 35.1.13
BYG 1.1.6
TerraForged 1.16.4-0.2.0-RC-3

**Comment by CorgiTaco** [comment]
Fixed in the latest beta

**Comment by Koji-KAWAHARA** [comment]
Thanks a lot!
