### ISSUE TITLE
Jacaranda Forest Bamboo all broken, major lag

### ISSUE THREAD

**Issue by sinistrl** [CorgiTaco/BYG#236]
Hi! I'm noticing every Jacaranda Forest I run across is littered with broken bamboo and untextured bamboo variant blocks (when I pick block it puts bamboo in my hand). I think something is causing all the bamboo in this biome to break, which causes unplayable lag exclusively in this biome. Image in link below.

https://cdn.discordapp.com/attachments/316088791150493696/797235501961576478/2021-01-08_14.46.07.png

**Comment by CorgiTaco** [comment]
What version? Minecraft version? mod loader? You really should fill out the information that i provide in the template bc this gives me nothing to work with

**Comment by sinistrl** [comment]
I'm really sorry, I forgot to specify this is likely a mod conflict... I'm on 1.16.4 forge, and am noticing this only happening with the TerraForged mod.

**Comment by CorgiTaco** [comment]
I was playing today with terraforged and went into this biome and didnt seem to get the issue w/ the latest beta file. If the issue persists, feel free to reopen this issue. But it looks to me a lot of other problems are occurring in your game instance such as missing textures.
