### ISSUE TITLE
Shulkren Moss Blanket rendering issues

### ISSUE THREAD

**Issue by saltyseadoggo** [CorgiTaco/BYG#237]
__**API/Modloader**__
Fabric

__**Describe the bug**__
Shulkren Moss Blankets placed on top of Shulkren Phylium visibly show a darker colour in their texture at a certain consistent distance away from the player. This is most visible simply moving around in the Shulkren Forest biome, but it can be replicated by placing this block on top of Shulkren Phylium anywhere.

__**To Reproduce**__
- Create a new world.
- Run */setblock ~ ~ ~ end_portal* to teleport to the End.
- Run *locatebiome byg:shulkren_forest*, and then click on the coordinates to teleport there.
- Move around, keeping your eye on the ground ahead of your character. Notice how the shulkren moss blankets close to the player are largely invisible, but the ones far away are visibly darker.

**Expected behavior**
Shulkren moss blankets would consistently appear the same colour.

**Screenshots/Videos**
The Shulkren Moss Blankets in the distance are dark.
![2021-01-08_17 55 40](https://user-images.githubusercontent.com/69029346/104080722-a4898e80-51de-11eb-9c6c-4a3dc33c029a.png)
They appear to vanish as the player gets closer.
![2021-01-08_17 55 43](https://user-images.githubusercontent.com/69029346/104080724-a5babb80-51de-11eb-9b39-88bf38d7da39.png)

**Comment by CorgiTaco** [comment]
Intentional
