### ISSUE TITLE
Server Generation Settings Not Working

### ISSUE THREAD

**Issue by Kowantify** [CorgiTaco/BYG#238]
Server generates the overworld and everything fine with TerraForged world type, the issue is, I want to use Oh The Biomes You'll Go nether and end biomes which they just released a new update that allows TerraForged to see those options under the custom generator settings, I tried following this guide https://github.com/TerraForged/community/wiki/Forger-Server:-Advanced 
the issue is, there's legit no button anywhere to press that makes it the default generation setting or anything in that nature to copy and paste it into the folder in my server to allow my server to use those generator settings.

**Comment by CorgiTaco** [comment]
I followed the instructions that dags provided me

**Comment by CorgiTaco** [comment]
So this isnt a byg issue. This is between terraforged and you now? unless i missed something

**Comment by Kowantify** [comment]
Yes, I posted this issue in the wrong area... lmfao

**Comment by CorgiTaco** [comment]
LMAO
