### ISSUE TITLE
All BYG Boats Crash The Client

### ISSUE THREAD

**Issue by Kowantify** [CorgiTaco/BYG#239]
First off, let me apologize for even posting something that MAY be a BYG thing or not, idk what else to do my hands are a little tied, but I placed down what was called a "Cherry Oak Boat" in my server that I've put A LOT of time into, in placing that boat down the client side immediately crashed, and now I can't get back into my world at all, I tried removing some mods (I made a backup of the server and client but this was after the initial crash, and made sure the server and client both had the exact same mods except, except for client only mods) and now every time I try to join with and without Optifine it will always crash the client but not the server, but ever since the moment I placed down that boat it has never let me join back into the server since, every time I do I get this crash log https://pastebin.com/j1f8iRdh and I'm again VERY VERY sorry for posting this here if it's not a BYG thing. but any help is deeply appreciated! me and my GF are really having a good time so this was very very unexpected.

**Comment by CorgiTaco** [comment]
Isolate byg and see if this crash still occurs maybe?

**Comment by Kowantify** [comment]
okay, i am going to attempt this rn, aswell as moving the world from the server to the client side to see if i get a different log

**Comment by KowalskiXCIX** [comment]
https://pastebin.com/XcidebpR This is a way different crash long, and this was client side with the server world copied over, trying one more time, and then if it doesn't work im gonna try isolating BYG

**Comment by Kowantify** [comment]
I am unbelievably confused right now, i just relaunched client side, loaded the world in singleplayer (not running on my server) and now it let me in???? Im gonna copy the world that works in singleplayer back over to my server to see if it crashes again.

**Comment by Kowantify** [comment]
I figured it out!!!! IT IS THE CHERRY BOAT!!! I flew to the area i placed it down in singleplayer, (i spawned in a different area away from the boat) and it crashed AGAIN here is the crash log following it https://pastebin.com/EgNbVhg1
Now how do i remove that boat without messing up my biomes, i believe one of the biome mods I have added the boat, i don't wanna remove the biome mod and mess up my world

**Comment by CorgiTaco** [comment]
`at net.minecraft.client.renderer.entity.EntityRendererManager.func_229086_a_(EntityRendererManager.java:283) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default,re:mixin,pl:accesstransformer:B}`

This line makes me suspect Optifine is breaking things again

**Comment by CorgiTaco** [comment]
Update to latest optifine, and use the forge version that the optifine file says it works on

**Comment by Kowantify** [comment]
I removed optifine, updated to latest forge, tested it, it still crashed, and then i removed BYG, flew over to the area, and the crash no longer happens because in removing the mod it also removed the Cherry Oak boat that was causing the crash

**Comment by KowalskiXCIX** [comment]
imma try a multitude of stuff, and I ain't gonna keep ya awake on this, imma try some more stuff and i'll update ya when i believe ive done all i truly truly could

**Comment by Kowantify** [comment]
Just tried the world with BYG and Forge only, still crashed, heres the log https://pastebin.com/ei1ri6yb
I can zip up the world file because I did end up moving the world spawn to our new house which is incredibly close to the boat, I can send u a zipped variant of that world with your permission of course and you can fly to that area where that boat is yourself for testing :)

**Comment by Kowantify** [comment]
I tried atleast 50% of the BYG boats, every single one ended up crashing my client every single time, I think its safe to say it is not just the Cherry Boat D:
