### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by Ragotha** [CorgiTaco/BYG#243]
**Before filling out this issue: **
**1. For major bugs, we only support BYG's latest version on a per Minecraft version basis(i.e latest for 1.15 is 1.0 while latest for 1.16 is 1.1).**
**2. Please test BYG on its own to confirm whether or not this is a mod conflict**

__**Mod conflict? If so, please clarify which mod is conflicting, if not skip this.**__
(apologies if this is a result of a conflict, unable to reproduce often enough to confirm)

__**API/Modloader**__
Forge/Fabric?
Forge
__**Describe the bug**__
What is the bug? Where/How does it occur? etc.
Crash on startup occasionally
__**To Reproduce**__
Please provide step by step instructions

**Expected behavior**
Loading up normally
**Screenshots/Videos**
If applicable, add screenshots/video to help explain your problem.

**Additional context**

**Logs**
Use: https://paste.ee/ and paste the links. if log is huge please upload those
Please provide:
Crashlog - https://pastebin.com/cnXrMhZ8
Debug.log - 
Latest.log - 

**Heap Dumps**
*If performance, please provide a heap dump/some sort of profile of your game(I recommend: https://visualvm.github.io/download.html)*
Heap Dump/Profile -

**Comment by CorgiTaco** [comment]
Fixed in 1.1.7. I suggest downloading chocolate fix aswell & backing up any worlds

**Comment by CorgiTaco** [comment]
https://www.curseforge.com/minecraft/mc-mods/chocolate-fix

**Comment by Ragotha** [comment]
Thanks for the fast response! I'll go update and get chocolate fix.
