### ISSUE TITLE
Ametrine Ore only minable with netherite

### ISSUE THREAD

**Issue by heymanMC** [CorgiTaco/BYG#244]
Mod Version: BYG 1.1.3

__**Mod conflict? If so, please clarify which mod is conflicting!**__
No mod conflict, tested this on it's own.

__**API/Modloader**__
Fabric Modloader

__**Describe the bug**__
Ametrine Ore does not drop gems or block when mined with Diamond pick like the wiki suggests:
https://oh-the-biomes-youll-go.fandom.com/wiki/Ametrine

__**To Reproduce**__
1. Find Amertine Ore
2. Try to mine with Diamond pick (silk or not)
3. Block mines slower and does not drop gems.

Gems will only drop if mined with Netherite. Does not drop with Diamond or Pendorite.

**Expected behavior**
Gems should drop when mined with Diamond pick.

**Possible Fix** 
a) Gems should drop with a diamond pick _and_ Pendorite (since it is above Netherrite).
b) Wiki should be updated and Pendorite should be included.

**Logs**
Logs not applicable for this issue.

**Comment by CorgiTaco** [comment]
We do not maintain that wiki so. This is intentional

**Comment by CorgiTaco** [comment]
Well pendorite

**Comment by CorgiTaco** [comment]
Pendorite should be able too aswell

**Comment by heymanMC** [comment]
I updated the wiki to reflect netherrite+ needed. The mod itself should be updated to add Pendorite.

**Comment by CorgiTaco** [comment]
Should be fixed in latest beta i believe. Reopen this if it isnt
