### ISSUE TITLE
BYG latest dependency on Chocofix Reload Bug

### ISSUE THREAD

**Issue by Ragotha** [CorgiTaco/BYG#245]
**Before filling out this issue: **
**1. For major bugs, we only support BYG's latest version on a per Minecraft version basis(i.e latest for 1.15 is 1.0 while latest for 1.16 is 1.1).**
**2. Please test BYG on its own to confirm whether or not this is a mod conflict**

__**Mod conflict? If so, please clarify which mod is conflicting, if not skip this.**__
Chocofix

__**API/Modloader**__
Forge/Fabric?
Forge
__**Describe the bug**__
What is the bug? Where/How does it occur? etc.
Upon creating a world, everything is fine. Upon saving a leaving the world, then reloading, a problem prevents the world from being read in any way.
__**To Reproduce**__
Please provide step by step instructions
Create World
Save and Leave
Attempt to reload
**Expected behavior**
I'd expect the world to be loadable.
**Screenshots/Videos**
If applicable, add screenshots/video to help explain your problem.

**Additional context**
Sorted through the problem on the discord, uninstalling chocolatefix and loading back to 1.7v1 allows the world to load.
**Logs**
Use: https://paste.ee/ and paste the links. if log is huge please upload those
Please provide:
Crashlog - none
Debug.log - none
Latest.log - https://mclo.gs/yDPckqM

**Heap Dumps**
*If performance, please provide a heap dump/some sort of profile of your game(I recommend: https://visualvm.github.io/download.html)*
Heap Dump/Profile -

**Comment by CorgiTaco** [comment]
The log you sent is expired. So I don't have much info to work with. Please try the latest releases for BYG & Chocolate Fix. I will close the issue and mark it for more info. Comment back here if the issue continues to persist.
