### ISSUE TITLE
OVERALL WEIGHT

### ISSUE THREAD

**Issue by Camawama** [CorgiTaco/BYG#247]
**Is your feature request related to a problem? Please describe.**
BYG Weight overweighs other mods (Biomes o' Plenty, Atmoshperic)

**Describe the solution you'd like**
An option for overall mod weight
**Describe alternatives you've considered**
I tried looking for a config option for overall weight, but couldn't find anything

**Additional context**
Thank you for reading this

**Comment by CorgiTaco** [comment]
Dont be lazy and configure it manually

**Comment by Camawama** [comment]
ouch.
