### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by mani00132** [CorgiTaco/BYG#252]
Hey, I am getting the following error when starting the server, but i have no idea how to fix it...

---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 16/01/21 09:47
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:51) ~[forge:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:95) ~[?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_211] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_211] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_211] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_211] {}
	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {re:classloading}
	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge.jar:?] {}
	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge.jar:?] {}
	at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Stacktrace:
	at it.unimi.dsi.fastutil.objects.Object2FloatOpenHashMap.rehash(Object2FloatOpenHashMap.java:1118) ~[?:?] {re:classloading}
-- MOD byg --
Details:
	Mod File: byg-1.1.6.jar
	Failure message: Oh The Biomes You'll Go (byg) encountered an error during the complete event phase
		java.lang.ArrayIndexOutOfBoundsException: -1
	Mod Version: 1.1.6
	Mod Issue URL: https://github.com/CorgiTaco/BYG/issues
	Exception message: java.lang.ArrayIndexOutOfBoundsException: -1
Stacktrace:
	at it.unimi.dsi.fastutil.objects.Object2FloatOpenHashMap.rehash(Object2FloatOpenHashMap.java:1118) ~[?:?] {re:classloading}
	at it.unimi.dsi.fastutil.objects.Object2FloatOpenHashMap.insert(Object2FloatOpenHashMap.java:272) ~[?:?] {re:classloading}
	at it.unimi.dsi.fastutil.objects.Object2FloatOpenHashMap.put(Object2FloatOpenHashMap.java:280) ~[?:?] {re:classloading}
	at corgiaoc.byg.common.properties.vanilla.BYGCompostables.compostibleBlocks(BYGCompostables.java:10) ~[byg:1.1.6] {re:classloading}
	at corgiaoc.byg.common.properties.vanilla.BYGCompostables.compostablesBYG(BYGCompostables.java:17) ~[byg:1.1.6] {re:classloading}
	at corgiaoc.byg.BYG.loadComplete(BYG.java:97) ~[byg:1.1.6] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[forge:35.1] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[forge:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626) ~[?:1.8.0_211] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1618) ~[?:1.8.0_211] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_211] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_211] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_211] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_211] {}

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Linux (amd64) version 4.19.0-10-amd64
	Java Version: 1.8.0_211, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4983453208 bytes (4752 MB) / 6106906624 bytes (5824 MB) up to 6106906624 bytes (5824 MB)
	CPUs: 40
	JVM Flags: 2 total; -Xms6144M -Xmx6144M
	ModLauncher: 8.0.6+85+master.325de55
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-3.0.5-service.jar eventbus PLUGINSERVICE 
		/forge.jar object_holder_definalize PLUGINSERVICE 
		/forge.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge.jar capability_inject_definalize PLUGINSERVICE 
		/forge.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge.jar fml TRANSFORMATIONSERVICE 
	FML: 35.1
	Forge: net.minecraftforge:35.1.36
	FML Language Providers: 
		javafml@35.1
		minecraft@1
	Mod List: 
		rsrequestify-1.16.3-2.0.1.jar                     |RSRequestify                  |rsrequestify                  |2.0.1               |DONE      |NOSIGNATURE
		CyclopsCore-1.16.4-1.9.5.jar                      |Cyclops Core                  |cyclopscore                   |1.9.5               |DONE      |NOSIGNATURE
		aiotbotania-1.16.4-1.5.0.jar                      |AIOT Botania                  |aiotbotania                   |1.5.0               |DONE      |NOSIGNATURE
		curiousshulkerboxes-forge-1.16.3-4.0.0.1.jar      |Curious Shulker Boxes         |curiousshulkerboxes           |1.16.3-4.0.0.1      |DONE      |NOSIGNATURE
		refinedpipes-0.5.jar                              |Refined Pipes                 |refinedpipes                  |0.5                 |DONE      |NOSIGNATURE
		IntegratedTerminals-1.16.4-1.1.1.jar              |IntegratedTerminals           |integratedterminals           |1.1.1               |DONE      |NOSIGNATURE
		findme-1.16.3-2.1.0.0.jar                         |Find Me                       |findme                        |NONE                |DONE      |NOSIGNATURE
		TerraForged-1.16.4-0.2.0-BETA-8.jar               |TerraForged                   |terraforged                   |0.2.0-BETA-8        |DONE      |7b:73:d0:a2:c3:40:13:84:35:4f:c9:0e:2b:85:8c:08:ea:3c:3c:eb:f1:98:8b:5b:6e:ca:8a:a0:9a:cf:12:b3
		XaerosWorldMap_1.11.7_Forge_1.16.4.jar            |Xaero's World Map             |xaeroworldmap                 |1.11.7              |DONE      |NOSIGNATURE
		JRFTL [1.16.4]-1.2.jar                            |JRFTL                         |jrftl                         |1.2                 |DONE      |NOSIGNATURE
		Placebo-1.16.3-4.3.3.jar                          |Placebo                       |placebo                       |4.3.3               |DONE      |NOSIGNATURE
		citadel-1.5.3.jar                                 |Citadel                       |citadel                       |1.5.3               |DONE      |NOSIGNATURE
		alexsmobs-1.4.1.jar                               |Alex's Mobs                   |alexsmobs                     |1.4.1               |DONE      |NOSIGNATURE
		Bookshelf-1.16.4-9.3.24.jar                       |Bookshelf                     |bookshelf                     |9.3.24              |DONE      |eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		simpleplanes-1.16.3-3.2.0.3.jar                   |Simple Planes                 |simpleplanes                  |1.16.3-3.2.0.3      |DONE      |NOSIGNATURE
		DarkUtilities-1.16.4-7.0.7.jar                    |Dark Utilities                |darkutils                     |7.0.7               |DONE      |eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		mcw-doors-1.0.1fix-mc1.16.4.jar                   |Macaw's Doors                 |mcwdoors                      |1.0.1               |DONE      |NOSIGNATURE
		MekanismGenerators-1.16.4-10.0.18.445.jar         |Mekanism: Generators          |mekanismgenerators            |10.0.18             |DONE      |NOSIGNATURE
		SnowRealMagic-1.16.3-2.2.2.jar                    |Snow! Real Magic!             |snowrealmagic                 |2.2.2               |DONE      |NOSIGNATURE
		carryon-1.16.3-1.15.1.7.jar                       |Carry On                      |carryon                       |1.15.1.7            |DONE      |8c:03:ac:7d:21:62:65:e2:83:91:f3:22:57:99:ed:75:78:1e:db:de:03:99:ef:53:3b:59:95:18:01:bc:84:a9
		chat_heads_forge-0.2.0.jar                        |Chat Heads                    |chat_heads                    |0.2.0               |DONE      |NOSIGNATURE
		Paraglider-1.16.2-1.3.1.0.jar                     |Paraglider                    |paraglider                    |1.3.1.0             |DONE      |NOSIGNATURE
		dcintegration-2.0.9-1.16.jar                      |Discord Integration           |dcintegration                 |2.0.9               |DONE      |NOSIGNATURE
		refinedstorage-1.9.11.jar                         |Refined Storage               |refinedstorage                |1.9.11              |DONE      |NOSIGNATURE
		Upgraded Netherite 1.16.4 - 1.7.1.jar             |Upgraded Netherite            |upgradednetherite             |1.7.0               |DONE      |NOSIGNATURE
		w2w-1.16.1-0.0.5.1.jar                            |w2w                           |w2w                           |NONE                |DONE      |NOSIGNATURE
		structure_gel-1.16.4-1.7.3.jar                    |Structure Gel API             |structure_gel                 |1.7.3               |DONE      |NOSIGNATURE
		mcw-bridges-1.0.4-mc1.16.4.jar                    |Macaw's Bridges               |mcwbridges                    |1.0.4               |DONE      |NOSIGNATURE
		industrial-foregoing-1.16.4-3.2.8.1-f2c848c.jar   |Industrial Foregoing          |industrialforegoing           |3.2.8.1             |DONE      |NOSIGNATURE
		wishingforsunshine-1.16.4-0.0.1.4.jar             |Wishing for Sunshine          |wishingforsunshine            |1.16.4-0.0.1.4      |DONE      |NOSIGNATURE
		repurposed_structures-1.16.4-2.3.3.jar            |Repurposed Structures         |repurposed_structures         |1.16.4-2.3.3        |DONE      |NOSIGNATURE
		CommonCapabilities-1.16.4-2.5.5.jar               |CommonCapabilities            |commoncapabilities            |2.5.5               |DONE      |NOSIGNATURE
		MekanismAdditions-1.16.4-10.0.18.445.jar          |Mekanism: Additions           |mekanismadditions             |10.0.18             |DONE      |NOSIGNATURE
		valhelsia_structures-16.0.5.jar                   |Valhelsia Structures          |valhelsia_structures          |16.0.5              |DONE      |NOSIGNATURE
		dungeons-plus-1.16.4-1.1.0.jar                    |Dungeons Plus                 |dungeons_plus                 |1.1.0               |DONE      |NOSIGNATURE
		Botania-1.16.4-410.jar                            |Botania                       |botania                       |1.16.4-410          |DONE      |NOSIGNATURE
		curios-forge-1.16.4-4.0.3.4.jar                   |Curios API                    |curios                        |1.16.4-4.0.3.4      |DONE      |NOSIGNATURE
		eidolon-0.2.7.jar                                 |Eidolon                       |eidolon                       |0.2.7               |DONE      |NOSIGNATURE
		Patchouli-1.16.4-48.jar                           |Patchouli                     |patchouli                     |1.16.4-48           |DONE      |NOSIGNATURE
		angelring-1.16.3-1.3.3.jar                        |Angel Ring                    |angelring                     |1.3.3               |DONE      |NOSIGNATURE
		IntegratedTunnels-1.16.4-1.6.15.jar               |IntegratedTunnels             |integratedtunnels             |1.6.15              |DONE      |NOSIGNATURE
		xercapaint-1.16.4-1.0.jar                         |Joy of Painting               |xercapaint                    |1.16.4-1.0          |DONE      |NOSIGNATURE
		obfuscate-0.5.1-1.16.3.jar                        |Obfuscate                     |obfuscate                     |0.5.1               |DONE      |e1:59:1a:56:ec:97:b3:d0:b3:4b:25:06:1f:83:b0:f4:fd:0c:24:e3:6d:ea:94:b1:9f:22:b0:38:13:60:88:ea
		vehicle-mod-0.45.2-1.16.3.jar                     |MrCrayfish's Vehicle Mod      |vehicle                       |0.45.2              |DONE      |NOSIGNATURE
		Runelic-1.16.4-6.0.4.jar                          |Runelic                       |runelic                       |6.0.4               |DONE      |eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		TheAbyss 2.0.0 1.16.4.jar                         |TheAbyss                      |theabyss                      |2.0.0               |DONE      |NOSIGNATURE
		MekanismTools-1.16.4-10.0.18.445.jar              |Mekanism: Tools               |mekanismtools                 |10.0.18             |DONE      |NOSIGNATURE
		curiouselytra-forge-1.16.3-4.0.0.1.jar            |Curious Elytra                |curiouselytra                 |1.16.3-4.0.0.1      |DONE      |NOSIGNATURE
		cc-tweaked-1.16.4-1.95.1.jar                      |CC: Tweaked                   |computercraft                 |1.95.1              |DONE      |NOSIGNATURE
		RefinedStorage4ComputerCraft-1.16.4-1.1.0.jar     |RefinedStorage for ComputerCra|refinedstorage4computercraft  |1.1.0               |DONE      |NOSIGNATURE
		The_Undergarden-1.16.4-0.4.2.jar                  |The Undergarden               |undergarden                   |0.4.2               |DONE      |NOSIGNATURE
		the_bumblezone-1.16.4-2.2.8.jar                   |The Bumblezone                |the_bumblezone                |1.16.4-2.2.8        |DONE      |NOSIGNATURE
		FastLeafDecay-v25.jar                             |FastLeafDecay                 |fastleafdecay                 |v25                 |DONE      |NOSIGNATURE
		CodeChickenLib-1.16.4-3.5.0.401-universal.jar     |CodeChicken Lib               |codechickenlib                |3.5.0.401           |DONE      |31:e6:db:63:47:4a:6e:e0:0a:2c:11:d1:76:db:4e:82:ff:56:2d:29:93:d2:e5:02:bd:d3:bd:9d:27:47:a5:71
		BetterMineshafts-Forge-1.16.3-1.1.1.jar           |YUNG's Better Mineshafts      |bettermineshafts              |1.16.3-1.1.1        |DONE      |NOSIGNATURE
		QuantumStorage-1.16.4-5.3.0.jar                   |QuantumStorage                |quantumstorage                |5.3.0Alpha5         |DONE      |NOSIGNATURE
		Cyclic-1.16.4-1.1.1.jar                           |Cyclic                        |cyclic                        |1.16.4-1.1.1        |DONE      |1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
		Kiwi-1.16.3-3.4.1.jar                             |Kiwi                          |kiwi                          |3.4.1               |DONE      |NOSIGNATURE
		BotaniaAdditionsMC1.16.4-1.0.4.jar                |Botania Additions             |botaniaadditions              |1.0.4               |DONE      |NOSIGNATURE
		biggerreactors-1.16.4-0.4.3-beta.jar              |Bigger Reactors               |biggerreactors                |0.4.3               |DONE      |NOSIGNATURE
		Cucumber-1.16.4-4.1.5.jar                         |Cucumber Library              |cucumber                      |4.1.5               |DONE      |NOSIGNATURE
		jei-1.16.4-7.6.1.65.jar                           |Just Enough Items             |jei                           |7.6.1.65            |DONE      |NOSIGNATURE
		longfallboots-1.6.0a.jar                          |Long Fall Boots               |longfallboots                 |1.6.0a              |DONE      |NOSIGNATURE
		the-conjurer-1.16.4-1.0.13.jar                    |The Conjurer                  |conjurer_illager              |1.0.13              |DONE      |NOSIGNATURE
		abnormals_core-1.16.4-3.0.6.jar                   |Abnormals Core                |abnormals_core                |3.0.6               |DONE      |NOSIGNATURE
		buzzier_bees-1.16.4-3.0.0.jar                     |Buzzier Bees                  |buzzier_bees                  |3.0.0               |DONE      |NOSIGNATURE
		Mekanism-1.16.4-10.0.18.445.jar                   |Mekanism                      |mekanism                      |10.0.18             |DONE      |NOSIGNATURE
		caelus-forge-1.16.4-2.1.0.2.jar                   |Caelus API                    |caelus                        |1.16.4-2.1.0.2      |DONE      |NOSIGNATURE
		invtweaks-1.16.4-1.0.1.jar                        |Inventory Tweaks Renewed      |invtweaks                     |1.16.4-1.0.1        |DONE      |NOSIGNATURE
		extraboats-1.16.4-2.0.0.jar                       |Extra Boats                   |extraboats                    |2.0.0               |DONE      |NOSIGNATURE
		create-mc1.16.3_v0.3e.jar                         |Create                        |create                        |mc1.16.3_v0.3e      |DONE      |NOSIGNATURE
		Waystones_1.16.3-7.3.1.jar                        |Waystones                     |waystones                     |7.3.1               |DONE      |NOSIGNATURE
		jev-1.16.3-2.0.0.jar                              |Just Enough Vehicles          |jev                           |2.0.0               |DONE      |NOSIGNATURE
		NaturesCompass-1.16.4-1.8.6.jar                   |Nature's Compass              |naturescompass                |1.16.4-1.8.6        |DONE      |NOSIGNATURE
		Artifacts-1.16.4-2.7.5.jar                        |Artifacts                     |artifacts                     |1.16.4-2.7.5        |DONE      |NOSIGNATURE
		phosphophyllite-1.16.4-0.4.0-beta.jar             |Phosphophyllite               |phosphophyllite               |0.4.0               |DONE      |NOSIGNATURE
		snowundertrees-1.16.4-v1.1.3.jar                  |Snow Under Trees              |snowundertrees                |v1.1.3              |DONE      |NOSIGNATURE
		iceandfire-2.1.5-1.16.4.jar                       |Ice and Fire                  |iceandfire                    |2.1.5-1.16.4        |DONE      |NOSIGNATURE
		Toast-Control-1.16.3-4.3.0.jar                    |Toast Control                 |toastcontrol                  |4.3.0               |DONE      |NOSIGNATURE
		inventorypets-2.0.11.jar                          |Inventory Pets                |inventorypets                 |2.0.11              |DONE      |NOSIGNATURE
		EnderStorage-1.16.4-2.7.0.161-universal.jar       |EnderStorage                  |enderstorage                  |2.7.0.161           |DONE      |31:e6:db:63:47:4a:6e:e0:0a:2c:11:d1:76:db:4e:82:ff:56:2d:29:93:d2:e5:02:bd:d3:bd:9d:27:47:a5:71
		extradisks-1.16.4-1.3.4.jar                       |Extra Disks                   |extradisks                    |1.3.4               |DONE      |NOSIGNATURE
		colorfultools-1.16.4-1.11.jar                     |Colorful Tools                |colorfultools                 |1.11                |DONE      |NOSIGNATURE
		ImmersivePetroleum-1.16.4-3.1.0-2.jar             |Immersive Petroleum           |immersivepetroleum            |3.1.0-2             |DONE      |NOSIGNATURE
		forge-1.16.4-35.1.36-universal.jar                |Forge                         |forge                         |35.1.36             |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		psipherals-1.4.0.jar                              |Psionic Peripherals           |psipherals                    |version             |DONE      |NOSIGNATURE
		neapolitan-1.16.4-2.0.1.jar                       |Neapolitan                    |neapolitan                    |2.0.1               |DONE      |NOSIGNATURE
		DynamicSurroundings-1.16.4-4.0.3.3.jar            |§3Dynamic Surroundings        |dsurround                     |1.16.4-4.0.3.3      |DONE      |b4:98:14:b9:76:55:25:4f:e5:5f:4d:71:90:87:43:5b:f9:d5:3a:02:60:42:5e:da:1f:15:9c:ff:be:a9:7c:77
		MysticalAgriculture-1.16.4-4.1.4.jar              |Mystical Agriculture          |mysticalagriculture           |4.1.4               |DONE      |NOSIGNATURE
		MysticalAgradditions-1.16.4-4.1.3.jar             |Mystical Agradditions         |mysticalagradditions          |4.1.3               |DONE      |NOSIGNATURE
		ironchest-1.16.4-11.2.10.jar                      |Iron Chests                   |ironchest                     |1.16.4-11.2.10      |DONE      |NOSIGNATURE
		IntegratedCrafting-1.16.4-1.0.11.jar              |IntegratedCrafting            |integratedcrafting            |1.0.11              |DONE      |NOSIGNATURE
		forge-1.16.4-35.1.36-server.jar                   |Minecraft                     |minecraft                     |1.16.4              |DONE      |NOSIGNATURE
		upgrade_aquatic-1.16.4-3.0.0.jar                  |Upgrade Aquatic               |upgrade_aquatic               |3.0.0               |DONE      |NOSIGNATURE
		cofh_core-1.16.3-1.1.6.jar                        |CoFH Core                     |cofh_core                     |1.1.6               |DONE      |NOSIGNATURE
		thermal_foundation-1.16.3-1.1.6.jar               |Thermal Series                |thermal                       |1.1.6               |DONE      |NOSIGNATURE
		thermal_innovation-1.16.3-1.1.7.jar               |Thermal Innovation            |thermal_innovation            |1.1.7               |DONE      |NOSIGNATURE
		thermal_expansion-1.16.3-1.1.6.jar                |Thermal Expansion             |thermal_expansion             |1.1.6               |DONE      |NOSIGNATURE
		thermal_locomotion-1.16.3-1.1.6.jar               |Thermal Locomotion            |thermal_locomotion            |1.1.6               |DONE      |NOSIGNATURE
		endergetic-1.16.4-3.0.0.jar                       |The Endergetic Expansion      |endergetic                    |3.0.0               |DONE      |NOSIGNATURE
		pandoras_creatures-1.16.3-2.0.1.jar               |Pandoras Creatures            |pandoras_creatures            |1.16.3-2.0.1        |DONE      |NOSIGNATURE
		titanium-1.16.4-3.2.5.jar                         |Titanium                      |titanium                      |3.2.5               |DONE      |NOSIGNATURE
		Psi 1.16-89.jar                                   |Psi                           |psi                           |1.16-88             |DONE      |NOSIGNATURE
		ImmersiveEngineering-1.16.4-4.1.2-129.jar         |Immersive Engineering         |immersiveengineering          |1.16.4-4.1.2-129    |DONE      |44:39:94:cf:1d:8c:be:3c:7f:a9:ee:f4:1e:63:a5:ac:61:f9:c2:87:d5:5b:d9:d6:8c:b5:3e:96:5d:8e:3f:b7
		movingelevators-1.2.31a-mc1.16.4.jar              |Moving Elevators              |movingelevators               |1.2.31a             |DONE      |NOSIGNATURE
		towers_of_the_wild-1.16.4-2.0.1.jar               |Towers Of The Wild            |towers_of_the_wild            |1.16.4-2.0.1        |DONE      |NOSIGNATURE
		savageandravage-1.16.4-3.0.0.jar                  |Savage & Ravage               |savageandravage               |3.0.0               |DONE      |NOSIGNATURE
		Xaeros_Minimap_21.0.0_Forge_1.16.4.jar            |Xaero's Minimap               |xaerominimap                  |21.0.0              |DONE      |NOSIGNATURE
		IntegratedDynamics-1.16.4-1.2.0.jar               |IntegratedDynamics            |integrateddynamics            |1.2.0               |DONE      |NOSIGNATURE
		rats-7.0.4-1.16.3.jar                             |Rats                          |rats                          |7.0.4               |DONE      |NOSIGNATURE
		ratlantis-1.0.0-1.16.3.jar                        |Rats: Ratlantis               |ratlantis                     |1.0.0-1.16.3        |DONE      |NOSIGNATURE
		thermal_cultivation-1.16.3-1.1.6.jar              |Thermal Cultivation           |thermal_cultivation           |1.1.6               |DONE      |NOSIGNATURE
		AutoRegLib-1.6-47.jar                             |AutoRegLib                    |autoreglib                    |1.6-47              |DONE      |NOSIGNATURE
		Quark-r2.4-293.jar                                |Quark                         |quark                         |r2.4-293            |DONE      |NOSIGNATURE
		charm-forge-1.16.4-2.2.2.jar                      |Charm                         |charm                         |2.2.2               |DONE      |NOSIGNATURE
		[1.16.4] SecurityCraft v1.8.20.2.jar              |SecurityCraft                 |securitycraft                 |v1.8.20.2           |DONE      |NOSIGNATURE
		StorageDrawers-1.16.3-8.2.1.jar                   |Storage Drawers               |storagedrawers                |8.2.1               |DONE      |NOSIGNATURE
		FluxNetworks-1.16.4-6.1.5.10.jar                  |Flux Networks                 |fluxnetworks                  |1.16.4-6.1.5.10     |DONE      |NOSIGNATURE
		performant-1.16.2-4-3.30m.jar                     |Performant                    |performant                    |3.30m               |DONE      |NOSIGNATURE
		AppleSkin-mc1.16.2-forge-1.0.14.jar               |AppleSkin                     |appleskin                     |1.0.14              |DONE      |NOSIGNATURE
		byg-1.1.6.jar                                     |Oh The Biomes You'll Go       |byg                           |1.1.6               |ERROR     |NOSIGNATURE
		Aquaculture-1.16.4-2.1.12.jar                     |Aquaculture 2                 |aquaculture                   |1.16.4-2.1.12       |DONE      |NOSIGNATURE
		refinedstorageaddons-0.7.2.jar                    |Refined Storage Addons        |refinedstorageaddons          |0.7.2               |DONE      |NOSIGNATURE
		SoundFilters-0.14_for_1.16.2.jar                  |Sound Filters                 |soundfilters                  |0.14_for_1.16.2     |DONE      |NOSIGNATURE
		EnderMail-1.16.4-1.2.0.jar                        |Ender Mail                    |endermail                     |1.16.4-1.2.0        |DONE      |NOSIGNATURE
	Crash Report UUID: 448db1fa-ca59-464c-bdfa-fbacc2cab78a
	Kiwi Modules: 
		kiwi:contributors
		kiwi:data
		snowrealmagic:core
		snowrealmagic:world
	[Psi] Active spell: None

**Comment by CorgiTaco** [comment]
Fixed in latest beta
