### ISSUE TITLE
byg requries Fabric 0.24.3

### ISSUE THREAD

**Issue by RadioSaviour** [CorgiTaco/BYG#255]
Ugh, so when i'm loading byg 1.13 for 1.16.4 Fabric, it's saying literary what is written in the title. Well I didnt't found such version of Fabric, so I thought it might mean Fabric API, there was such version (frankly for 1.16.3), but when I put this in the mods folder, the game doesn't load these mods. What the hell is going on? 

Here's the report:
![obraz](https://user-images.githubusercontent.com/77624996/104930713-d0a6cb80-59a5-11eb-8f8b-45946b33908d.png)

**Comment by CorgiTaco** [comment]
USe latest fabric api & fabric loader
