### ISSUE TITLE
Problems With Modding Jacaranda Leaves

### ISSUE THREAD

**Issue by Procrastinogenic** [CorgiTaco/BYG#257]
Hello,   

Firstly, love everything! Just wanting to change the textures on the Jacaranda Tree leaves. And make them waving in the wind. I cannot figure out the pathing though. I have changed the Jacaranda_leaves.png in BYG and Biomes Oh Plenty, but the texture remains the same as always. Is there a third location? The trunks changed no problem by replacing the png in the mod, as well as the Rainbough Euc_leaves.png No problem. But these Jacaranda trees are proving to difficult for me lol. Any assistance, I would be grateful for. 
I wish also to write a properties file that allows them to wave in the wind.

Thank you :)

**Comment by CorgiTaco** [comment]
Did you figure it out? And the path(s) for the models/textures can be found here: https://github.com/CorgiTaco/BYG/tree/Forge-1.16.X/src/main/resources/assets/byg

Im going to close this now and assume you figured it out hopefully by now
