### ISSUE TITLE
[Fabric] BYG tools are not able to break modded blocks

### ISSUE THREAD

**Issue by Technici4n** [CorgiTaco/BYG#258]
It seems BYG tools are not able to break some modded blocks. You should add them to the `fabric:pickaxe` et al tool tags.
See the end of [the wiki page](https://fabricmc.net/wiki/tutorial:mining_levels#making_a_custom_tool).

Should fix TechReborn/TechReborn#2329.

__**API/Modloader**__
Fabric.

_**Steps to reproduce**_
Try to break TR ores with BYG tools (I think).

**Comment by CorgiTaco** [comment]
Im gonna say this is a duplicate of #187. So keep an eye on that
