### ISSUE TITLE
(Suggestion) Replace Piglin and Zombified Piglin spawning in some biomes

### ISSUE THREAD

**Issue by Brun333rp** [CorgiTaco/BYG#259]
**Is your feature request related to a problem? Please describe.**
 Hi, I think that some biomes don't fit very well with Piglins and Zombified Piglins. So I think that these mobs should be replaced by mobs that better fit these biomes.

**Describe the solution you'd like**

- Endermen in Warped Deserts;
- Skeletons in Quartz Deserts;
- Strays (maybe Skeletons as well) in Subzero Hypogeals;
- Endermen and Skeletons in Glowstone Gardens (these should not necessarily replace, but spawn alongside them);
- Endermen in Weeping Mire;
- Wither Skeletons in Withering Woods
- Blazes in Sythian Torrids (these should not necessarily replace, but spawn alongside them)

**Describe alternatives you've considered**
 I don't think that alternatives are needed

**Additional context**
 Well, I used some logic to make this suggestion:

- The Warped Desert is certainly connected with Warped Forests. So I think that Endermen spawning there makes sense;
- The Quartz Desert is a mainly white biome, and has Fossils and Hanging Bones scattered around. So it fits with Skeletons very whell;
- Subzero Hypogeals are icy biomes (despite of the Nether being a Hell-like dimension), and Strays in the Overworld spawn in snowy and icy biomes;
- Glowstone Gardens have caracteristics of both Warped Forests and Soul Sand Valleys, such as having Warped vegetation (Nylium, Sprouts and Vines) scattered around, and the Soul Shrooms, wich are presumably related to Souls just like Soul Sand and Soul Fire are. So I think that Endermen and Skeletons spawning there makes sense;
- The Weeping Mire is a mainly purple biome, and no other mobs fit with this biome very whell. Because of this, I think that Endermen are the best option.
- The Withering Woods is certainly connected with Wither Skeletons and The Wither. Just look at the biome's name.
- Sythian Torrids are mainly yellow biomes, and it's name has the word "torrid", wich means something oppressively hot. So it fits very whell with Blazes;

**Comment by CorgiTaco** [comment]
Achievable via datapacks

**Comment by Brun333rp** [comment]
but it being achievable with datapacks don't means it shouldn't be a actual feature. and datapacks are tedious to working with, because you need to manually put it in your world. so you should reconsider this

**Comment by Brun333rp** [comment]
> Achievable via datapacks

but it being achievable with datapacks don't means it shouldn't be a actual feature. and datapacks are tedious to working with, because you need to manually put it in your world. and I'm sure most people here (including me) don't have any knowledge about making datapacks. you should definetely reconsider this

**Comment by Brun333rp** [comment]
your profile pic sucks
