### ISSUE TITLE
[1.16.4] Watchdog Crash During End Exploration

### ISSUE THREAD

**Issue by NielsPilgaard** [CorgiTaco/BYG#260]
I have not tested this issue with BYG alone, as I have failed to reproduce it. I am awaiting more information from the original report.

__**API/Modloader**__
Forge

__**Describe the bug**__
During exploration of the End, the server starts to slow down and eventually crashes.

__**To Reproduce**__
I don't know sadly, I have not been able to reproduce it.
Edit: It seems to be caused by being in a Cryptic Wastes biome on a server? 
I can reproduce the error `BYG's End Layer: Unknown biome id: -1` in SP, but not the crash.

**Expected behavior**
No crash.

**Additional context**
Reported here: https://github.com/NillerMedDild/Enigmatica6/issues/964

**Logs**
Use: https://paste.ee/ and paste the links. if log is huge please upload those
Please provide:
Crashlog - https://paste.ee/p/WX8hU
Debug.log - [debug.log](https://github.com/NillerMedDild/Enigmatica6/files/5838693/debug.log)
Latest.log - https://paste.ee/p/qPTVp

**Comment by CorgiTaco** [comment]
Light engine issue that appears when entire sections of blocks are removed going to implement the fix now.
