### ISSUE TITLE
Ocean Monument, Village, and Shipwreck spawn rate tiny

### ISSUE THREAD

**Issue by mooseknuckleking** [CorgiTaco/BYG#261]
I am having an issue where in the world, all game mentioned structures are now spawning at an extremely low rate. especially the three mentioned in the title. Has anyone else had this problem?

**Comment by CorgiTaco** [comment]
Not sure how we'd be capable of doing that as we dont ever touch structures

**Comment by CorgiTaco** [comment]
Closing this as we're 98% sure that we arent at fault here

**Comment by mooseknuckleking** [comment]
I have confirmed that it's not a fault, it's more of just there are not as many structures in the BYG biomes as there are in default biomes. And shipwrecks were only because the seed didn't have very large oceans. Thank you.
