### ISSUE TITLE
Minimap appearance

### ISSUE THREAD

**Issue by Finnchen123** [CorgiTaco/BYG#263]
**Is your feature request related to a problem? Please describe.**
I don't know if this issue belongs to the mod, the default ftb map or some settings I have to change but the byg blocks (I tested it with Scoria and Soapstone) have the standard stone texture on the ftb standard mini map.

**Describe the solution you'd like**
I would like to have a visual representation of the blocks on the minimap.

**Describe alternatives you've considered**
Not rly an alternative but if this doesn't belong here I would like to know where I have to change or post sth.

**Additional context**
Screenshot with Scoria and some example vanilla blocks:
![screenshot](https://user-images.githubusercontent.com/77747454/105346503-f5898180-5be5-11eb-8543-4a68c40eff7b.png)

**Comment by CorgiTaco** [comment]
That's on them to fix not us, so make a report to them instead
