### ISSUE TITLE
ComposterBlock.CHANCES cause crash on startup

### ISSUE THREAD

**Issue by Nyx019** [CorgiTaco/BYG#265]
The way you add e.g. ASPEN_LEAVES to the Vanilla Composter Block is not safe and sometimes causes a crash on startup. 
A suggestion would be to fix this by doing it in FMLCommonSetupEvent and not in FMLLoadCompleteEvent

I attached the crash log so that you can read the error for yourselves
[crash-2021-01-22_10.55.13-fml.txt](https://github.com/CorgiTaco/BYG/files/5855659/crash-2021-01-22_10.55.13-fml.txt)

**Comment by CorgiTaco** [comment]
Fixed in latest beta.
