### ISSUE TITLE
Worldgen crash due to byg + minecraft village "bells"?

### ISSUE THREAD

**Issue by ghost** [CorgiTaco/BYG#268]
__**API/Modloader**__
Forge/Fabric?
Forge
__**Describe the bug**__
What is the bug? Where/How does it occur? etc.
Crashes in pregen of world, seems to be a feature generating near a bell?

**Logs**
Crashlog - https://pastebin.com/1qMrh72f
Debug.log - https://pastebin.com/VEdq8Gbp

I talked to terraforged they think the bug is due to something byg is generating around bells

**Comment by Won-Ton** [comment]
Fox context: this person posted ~3 lines of the crashlog in discord & our assessment of it was that the crash happened whilst generating a byg feature near a bell.

From the full stacktrace it looks like someone (supplementaries) is mixing into `BellBlock::updatePostPlacement` and doing an unsafe cast:
`at net.minecraft.block.BellBlock.handler$zbf000$updatePostPlacement(SourceFile:547) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:supplementaries.mixins.json:BellBlockMixin,pl:mixin:A}`

**Comment by ghost** [comment]
Sorry for blaming you guys for the blame of them - I will get in touch with supplementaries sir :)

**Comment by ghost** [comment]
I will close this as it is not related to either mods I mentioned

**Comment by MehVahdJukaar** [comment]
fixed it. sorry for the inconveniente
