### ISSUE TITLE
(Fabric) Can't place Item Frames or Paintings on the sides of most of the mushroom blocks/stems (Signs place ok)

### ISSUE THREAD

**Issue by Rayxanber** [CorgiTaco/BYG#272]
__**API/Modloader**__
Fabric

__**Describe the bug**__
(Fabric) Can't place Item Frames or Paintings on the sides of most of the mushroom blocks/stems (Signs place ok)

**Comment by AOCAWOL** [comment]
fixed in upcoming patch!
