### ISSUE TITLE
Guiana Shield Biomes hit Build Height on Amplified Worlds

### ISSUE THREAD

**Issue by Angular-Angel** [CorgiTaco/BYG#274]
__**API/Modloader**__
Forge known, but probably on Fabric too.

__**Describe the bug**__
In amplified worlds, the Guiana Shield biomes hit the max build height. Not just occasionally, but rather, the entire biome will generate right up against build height, such that it cannot even generate trees.

__**To Reproduce**__
Start an amplified world with BYG and find a Guiana Shield biome.

**Expected behavior**
The Guiana shield should generate more like how vanilla mountains do in amplified - tall, and maybe occasionally hitting build height, but not completely pressed up against it, and usually with room for trees to generate.

**Screenshots/Videos**
![2021-01-29_19 41 06](https://user-images.githubusercontent.com/938571/106345007-5827f080-626a-11eb-9ecc-43df347cb57b.png)

**Comment by AOCAWOL** [comment]
Unfortunately due to the Guiana Shield's standard height being a lot taller than base vanilla biomes, the amplified world type will just do this to this biome and biomes similar. To adjust this, simply datapack the Guiana Shield and change the height of the biome to be lower to your liking so that it works in your amplified world :)

**Comment by Angular-Angel** [comment]
I have no idea how to go about actually doing that. Is there a tutorial somewhere? And, can you make the mod do that automatically when it detects an amplified world? I feel like this bug should really be fixed on the mod side, not a patch that every person who wants to run the thing with amplified worlds needs to apply individually.

**Comment by CorgiTaco** [comment]
this is vanilla behavior tbh

**Comment by Angular-Angel** [comment]
Yeah but it sucks, and there aren't any vanilla biomes that actually present it.
