### ISSUE TITLE
Parsing error loading recipe.

### ISSUE THREAD

**Issue by K0-RR** [CorgiTaco/BYG#276]
Byg Fabric, build from the source.
[main/ERROR]: Parsing error loading recipe byg:chiseled_red_rock_bricks
com.google.gson.JsonSyntaxException: Unknown item 'byg:red_rock_bricks_slab'

**Comment by CorgiTaco** [comment]
Resolved on the forge side. Closing this, expect it in the fabric port of the latest forge patches
