### ISSUE TITLE
'Wailing' Grass, not 'Whaling' Grass

### ISSUE THREAD

**Issue by saltyseadoggo** [CorgiTaco/BYG#279]
__**API/Modloader**__
Fabric

__**Describe the bug**__
The purple coral fan things found in the Wailing Garth biome are called 'Whaling Grass' in en_us language. I doubt that this grass is hunting whales for their usable products, so I would presume that you meant 'Wailing Grass,' in reference to the biome name.

**Comment by CorgiTaco** [comment]
Expect this fixed in 1.17 as changing this now will ruin existing wailing grass lmao

**Comment by saltyseadoggo** [comment]
'Whaling' Vine also has this issue.
