### ISSUE TITLE
Description: Colliding entity with block

### ISSUE THREAD

**Issue by the-webguys** [CorgiTaco/BYG#28]
In the nether we have just started getting this error on our server. 

Any suggestions would be great.

Here is the crash reoprt from a single player game:
(Since i was trying to replicate the issue)

.

.

`---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 7/15/20 3:10 PM
Description: Colliding entity with block

java.lang.ClassCastException: voronoiaoc.byg.common.properties.BYGBlockProperties$BYGEmburGelBlock cannot be cast to net.minecraft.class_1297
	at net.minecraft.class_4622.constant$bid003$getGravity(class_4622.java:517)
	at net.minecraft.class_4622.method_23356(class_4622.java:113)
	at net.minecraft.class_4622.method_9548(class_4622.java:97)
	at net.minecraft.class_4970$class_4971.method_26178(class_4970.java:881)
	at net.minecraft.class_1297.method_5852(class_1297.java:957)
	at net.minecraft.class_1297.method_5784(class_1297.java:646)
	at net.minecraft.class_1542.method_5773(class_1542.java:122)
	at net.minecraft.class_3218.method_18762(class_3218.java:615)
	at net.minecraft.class_3218$$Lambda$8264/2045973207.accept(Unknown Source)
	at net.minecraft.class_1937.method_18472(class_1937.java:603)
	at net.minecraft.class_3218.method_18765(class_3218.java:405)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:873)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:813)
	at net.minecraft.class_1132.method_3748(class_1132.java:93)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:672)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:256)
	at net.minecraft.server.MinecraftServer$$Lambda$8059/165644660.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_4622.constant$bid003$getGravity(class_4622.java:517)
	at net.minecraft.class_4622.method_23356(class_4622.java:113)
	at net.minecraft.class_4622.method_9548(class_4622.java:97)
	at net.minecraft.class_4970$class_4971.method_26178(class_4970.java:881)

-- Block being collided with --
Details:
	Block: Block{byg:embur_gel_block}
	Block location: World: (-64,45,-892), Chunk: (at 0,2,4 in -4,-56; contains blocks -64,0,-896 to -49,255,-881), Region: (-1,-2; contains chunks -32,-64 to -1,-33, blocks -512,0,-1024 to -1,255,-513)
Stacktrace:
	at net.minecraft.class_1297.method_5852(class_1297.java:957)

-- Entity being checked for collision --
Details:
	Entity Type: minecraft:item (net.minecraft.class_1542)
	Entity ID: 5057
	Entity Name: Tall Embur Roots
	Entity's Exact location: -62.91, 44.99, -891.84
	Entity's Block location: World: (-63,44,-892), Chunk: (at 1,2,4 in -4,-56; contains blocks -64,0,-896 to -49,255,-881), Region: (-1,-2; contains chunks -32,-64 to -1,-33, blocks -512,0,-1024 to -1,255,-513)
	Entity's Momentum: -0.05, 0.07, -0.06
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.class_1297.method_5784(class_1297.java:646)
	at net.minecraft.class_1542.method_5773(class_1542.java:122)
	at net.minecraft.class_3218.method_18762(class_3218.java:615)
	at net.minecraft.class_3218$$Lambda$8264/2045973207.accept(Unknown Source)

-- Entity being ticked --
Details:
	Entity Type: minecraft:item (net.minecraft.class_1542)
	Entity ID: 5057
	Entity Name: Tall Embur Roots
	Entity's Exact location: -62.91, 44.99, -891.84
	Entity's Block location: World: (-63,44,-892), Chunk: (at 1,2,4 in -4,-56; contains blocks -64,0,-896 to -49,255,-881), Region: (-1,-2; contains chunks -32,-64 to -1,-33, blocks -512,0,-1024 to -1,255,-513)
	Entity's Momentum: -0.05, 0.07, -0.06
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:603)
	at net.minecraft.class_3218.method_18765(class_3218.java:405)

-- Affected level --
Details:
	All players: 1 total; [class_3222['dc_wan'/641, l='ServerLevel[CoffeeCoffeeCoffee]', x=-99.39, y=96.18, z=-485.34]]
	Chunk stats: ServerChunkCache: 7200
	Level dimension: minecraft:the_nether
	Derived: true
	Level spawn location: World: (-48,68,-144), Chunk: (at 0,4,0 in -3,-9; contains blocks -48,0,-144 to -33,255,-129), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 7114 game time, 7114 day time
	Level name: CoffeeCoffeeCoffee
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
	Level weather: Rain time: 56442 (now: false), thunder time: 140694 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:873)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:813)
	at net.minecraft.class_1132.method_3748(class_1132.java:93)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:672)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:256)
	at net.minecraft.server.MinecraftServer$$Lambda$8059/165644660.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1612440280 bytes (1537 MB) / 6174015488 bytes (5888 MB) up to 11453595648 bytes (10923 MB)
	CPUs: 6
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx12288m -Xms256m -XX:PermSize=256m
	Fabric Mods: 
		adabraniummod: Adabranium Mod 1.1.4.1
		adorn: Adorn 1.9.1+1.16.1
		adventurez: AdventureZ 1.0.4
		amecsapi: Amecs API 1.0.2+1.16-rc1
		aopalliance_aopalliance: aopalliance 1.0
		appleskin: AppleSkin 1.0.11
		artifice: Artifice 0.8.0+1.16-rc1
		artofalchemy: Art of Alchemy 1.0.0-rc2+1.16.1
		assetvalidator: Asset Validator 1.0.2
		astromine: Astromine 1.0.25
		autoconfig1u: Auto Config v1 Updated 3.2.0-unstable
		bambootweaks: Bamboo Tweaks unspecified
		better_wandering_trader: Better Wandering Trader 1.4.0
		blockus: Blockus 1.6.0.1
		blue_endless_jankson: jankson +
		boringbackgrounds: Boring Backgrounds 2.1.0-1.16.pre3
		bunch-o-trinkets: Bunch O' Trinkets 1.0.1
		byg: BYG 1.0.5
		campanion: Campanion 1.1.8+build.23
		cardinal-components: Cardinal Components API 2.4.1
		cardinal-components-base: Cardinal Components API (base) 2.4.1
		cardinal-components-block: Cardinal Components API (blocks) 2.4.1
		cardinal-components-chunk: Cardinal Components API (chunks) 2.4.1
		cardinal-components-entity: Cardinal Components API (entities) 2.4.1
		cardinal-components-item: Cardinal Components API (items) 2.4.1
		cardinal-components-level: Cardinal Components API (world saves) 2.4.1
		cardinal-components-util: Cardinal Components API (utilities) 2.4.1
		cardinal-components-world: Cardinal Components API (worlds) 2.4.1
		cartloaders: CartLoaders 0.0.2
		cavebiomes: Cave Biomes 0.2.3
		chainmail: Chainmail 0.3.0
		chunkactivator: Chunk Activator 2.1.0+mc1.16.1
		chunkpregen: Fabric Chunk Pregenerator 0.2.2
		cinderscapes: Cinderscapes 1.0.3+build.18
		cleancut: CleanCut mc1.16-2.1-fabric
		cloth-api: Cloth API 1.0.5
		cloth-armor-api-v1: Cloth Armor API v1 1.0.5
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.0.5
		cloth-common-events-v1: Cloth Common Events v1 1.0.5
		cloth-config2: Cloth Config v4 4.5.6
		cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.0.5
		cloth-scissors-api-v1: Cloth Scissors API v1 1.0.5
		cloth-utils-v1: Cloth Utils v1 1.0.5
		com_electronwill_night-config_core: core 3.6.0
		com_electronwill_night-config_toml: toml 3.6.0
		com_fasterxml_jackson_core_jackson-annotations: jackson-annotations 2.9.0
		com_fasterxml_jackson_core_jackson-core: jackson-core 2.9.0
		com_fasterxml_jackson_core_jackson-databind: jackson-databind 2.9.0
		com_fasterxml_jackson_dataformat_jackson-dataformat-yaml: jackson-dataformat-yaml 2.9.0
		com_fasterxml_jackson_module_jackson-module-kotlin: jackson-module-kotlin 2.9.0
		com_github_therandomlabs_trlutils-config: TRLUtils-Config master-SNAPSHOT
		com_github_therandomlabs_trlutils-fabric: TRLUtils-Fabric 1.16-SNAPSHOT
		com_google_inject_guice: guice 4.2.3
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		cotton: Cotton 1.0.5
		cotton-cauldron: Cotton Cauldron 1.0.4
		cotton-commons: Cotton Commons 1.0.4
		cotton-config: Cotton Config 1.0.0-rc.7
		cotton-datapack: Cotton Datapack 1.0.5
		cotton-logging: Cotton Logging 1.0.0-rc.4
		cotton-player-events: Cotton Player Events 1.0.2
		craftpresence: CraftPresence 1.6.6
		creativebuttonmover: Creative Button Mover 0.2.5
		crimsonmoon: Crimson Moon 1.1.0-1.16
		crusade: Crudade Mod 1.1.0
		dark-loading-screen: Dark Loading Screen 1.3.0
		diggusmaximus: Diggus Maximus 1.2.11-1.16
		dishes: Delicious Dishes 1.0.3
		economy: FabricEconomy 1.1
		ecotones: Ecotones 0.4.4
		essentials-base: Essentials 0.2.3+1.16.1
		exotic-art-core: Exotic Art Core Content Pack 1.0.341
		exotic-matter: Exotic Matter 2.4.343
		expandedstorage: ExpandedStorage 5.3.14
		experimentaway: ExperimentAway 1.0.0
		extraalchemy: Extra Alchemy 1.0.3
		fabric: Fabric API 0.14.0+build.371-1.16
		fabric-api-base: Fabric API Base 0.1.3+12a8474cb0
		fabric-biomes-v1: Fabric Biomes (v1) 0.2.7+059ea86602
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8902
		fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce5339802
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d3083602
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f02
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea86602
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d02
		fabric-diagonal-panes: Fabric Diagonal Panes 0.3.0
		fabric-dimensions-v1: fabric-dimensions-v1 1.0.0+a71b305302
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.3+7066030fb0
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b02
		fabric-furnaces: Fabric Furnaces 1.3.0-1.16.1
		fabric-item-api-v1: Fabric Item API (v1) 1.0.0+16acbe5b02
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f963602
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.0+e16a9774b0
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c5b0
		fabric-language-kotlin: Fabric Language Kotlin 1.3.72+build.1
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.0.0+b0993bc102
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.10+059ea86602
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9902
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d602
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b02
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f02
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.5.5+e00ecb5f02
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.6.0+da175ad602
		fabric-particles-v1: fabric-particles-v1 0.2.1+0a6f2a7002
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.3.8+7dba2d6c02
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.13+eae12eb802
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.3.2+4d66bed502
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a6002
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d02
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.8+b7084faa02
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+5341049002
		fabric-rendering-v1: Fabric Rendering (v1) 1.1.2+346247d702
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.2.5+059ea866b0
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.0.1+f362c86e02
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.2.7+a4c57d8e02
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb802
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.1.4+5794386e02
		fabriccontrolling: Fabric Controlling 1.0.1
		fabricloader: Fabric Loader 0.8.9+build.203
		facility: Facility 0.9.147
		fatxporbs: Fat Experience Orbs 0.0.7
		fermion: Fermion 2.1.191
		fermion-gui: Fermion GUI 2.1.191
		fermion-modkeys: Fermion Modifier Keys 1.8.180-snapshot
		fermion-orientation: Fermion Orientation 1.0.180-snapshot
		fermion-varia: Fermion Varia 2.1.191
		fiber: fiber 0.23.0-1
		flonters: Flonters 1.1.0+1.16.1
		flora-doubling: Flora Doubling 1.1.1
		fluidity: Fluidity 0.11.180
		fonthack: Font Hack 2.1.38
		gameinfo: GameInfo 1.5.4 1.16
		gamemodeoverhaul: GamemodeOverhaul 1.15.2-1.0.1.8
		givemehats: Give Me Hats! 1.0.0
		glassdoor: Glass Doors 1.4.4-1.16
		glassential: Glassential 1.16.1-1.1.4
		golemsgalore: Golems Galore 0.1.3+mc.1.16
		gottaclimbfast: Gotta Climb Fast! 1.0
		hard-hat-steve: Hard Hat Steve 1.1.1
		harvest: Harvest 1.2.12
		healthoverlay: Health Overlay 3.5.10
		herbocraft: Herbocraft dev
		hotm: Heart of the Machine 1.16.1-0.1.1
		identity: Identity 1.0.2-beta-1.16
		improved-stations: Improved Stations 2.0.2-unstable
		inmis: Inmis 1.0.2-1.16
		inventorysorter: Inventory Sorter 1.6.7-1.16
		iron-jetpacks: Iron Jetpacks 0.2.3
		jankson: Jankson 3.0.0+j1.2.0
		javax_inject_javax_inject: javax.inject 1
		jumploader: Jumploader 1.0.10
		jumpoverfences: JumpOverFences 1.16-0.0.3
		kibe: Kibe 1.1.3-BETA
		kyrptconfig: Kytpt Config 1.0.4-1.16
		layingbox: LayingBox 1.1.3
		leadvillagers: Lead Villagers 2.1.0+mc1.16.1
		libblockattributes: LibBlockAttributes 0.7.0
		libblockattributes_core: LibBlockAttributes (Core) 0.7.0
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.7.0
		libblockattributes_items: LibBlockAttributes (Items) 0.7.0
		libcd: LibCapableData 2.5.0+1.16.1
		libgamerule: LibGamerule ${version}
		libgui: LibGui 2.0.1+1.16.1
		libmultipart: LibMultiPart 0.4.0
		libmultipart_deps_container: LibMultiPart (Dependency Container) 0.4.0
		libnetworkstack: Lib Network Stack 0.4.0
		libstructure: Libstructure 1.3
		lightoverlay: Light Overlay 5.4.0
		linkart: Linkart unspecified
		linkedstorage: Linked Storage 1.3.2-1.16
		lithium: Lithium 0.5.0-rc1
		ltr: LilTaterReloaded 1.1.6+1.16.1
		lvmnt: SuperAxes 1.1.1
		minecraft: Minecraft 1.16.1
		mm: Manningham Mills 2.0
		mo_glass: Mo Glass 1.2-MC1.16-rc1
		modmenu: Mod Menu 1.12.2+build.17
		moreberries: More Berries 1.3.0
		morepaths: More Paths 0.0.2
		mostructures: Mo' Structures 1.0.0-pre2+mc.1.16
		mousewheelie: Mouse Wheelie 1.4.16+mc1.16-rc1
		mycommands: MyCommands Fabric 1.16.1-17
		mysql_mysql-connector-java: mysql-connector-java 5.1.46
		ninjaphenix-container-lib: NinjaPhenix's Container Library 1.1.4
		okzoomer: Ok Zoomer 4.0.0-alpha.3.1.16.pre5
		org_codehaus_groovy_groovy: groovy 3.0.3
		org_codehaus_groovy_groovy-jsr223: groovy-jsr223 3.0.3
		org_jetbrains_annotations: annotations 17.0.0
		org_jetbrains_exposed_exposed-core: exposed-core 0.23.1
		org_jetbrains_exposed_exposed-java-time: exposed-java-time 0.23.1
		org_jetbrains_exposed_exposed-jdbc: exposed-jdbc 0.23.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.3.72
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.3.72
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.3.72
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.3.72
		org_jetbrains_kotlinx_kotlinx-coroutines-core: kotlinx-coroutines-core 1.3.7
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.7
		org_postgresql_postgresql: postgresql 42.2.2
		org_slf4j_slf4j-api: slf4j-api 1.8.0-beta1
		org_xerial_sqlite-jdbc: sqlite-jdbc 3.28.0
		org_yaml_snakeyaml: snakeyaml 1.26
		packages: Packages 1.0
		parchment: Parchment 1.0.2+1.15.2
		patchouli: Patchouli 1.16-37-FABRIC
		phosphor: Phosphor 0.6.0+build.7
		piglintag: PiglinTag 1.0.0
		playerabilitylib: Pal 1.2.0
		polydungeons: PolyDungeons 1.0.3
		qcommon-croco: Croco 2.1.3
		quickshulker: Quick Shulker 1.1.5-1.16
		rare-ice: Rare Ice 0.1.3
		reach-entity-attributes: Reach Entity Attribute 1.0.1
		reborncore: Reborn Core 4.3.1+build.35
		respawnablepets: Respawnable Pets r2
		ring_of_miner: Ring Of Miner 1.0.13
		ringsofascension: Rings of Ascension 1.0.0
		riverredux: River Redux 0.1.4
		roughlyenoughitems: Roughly Enough Items 4.6.6
		sandwichable: Sandwichable 1.1.1-snapshot
		satin: Satin 1.4.0-nightly.1.16-pre5+build.1
		secretrooms: Secret Rooms 0.9.1+1.16.1
		shapes: Shapes 2.0.0+build.10
		shest: Shest unspecified
		shulkerboxtooltip: Shulker Box Tootip 2.1.0+1.16.1
		sign_editor: Better Signs & Frames mc-1.16.1-0.6.1
		simpledrawers: Simple Drawers 1.8.0-1.16.1
		simpleteleporters: Simple Teleporters 2.2.0
		simplevoidworld: Simple Void World 4.0.0
		simplexterrain: Simplex Terrain 0.6.4
		slight-gui-modifications: 'Slight' GUI Modifications 1.0.3
		slotlink: slotlink 0.2.2+minecraft-1.16.1
		soulbound: Soulbound 1.0.1
		special-circumstances: Special Circumstances 1.6.191
		spinnery: Spinnery 3.0.48
		staffofbuilding: Staff of Building 1.1.0-1.16
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		stonecutter-tweaks: Stonecutter Tweaks 1.1.0-1.16
		structurized: Structurized 1.0.0
		survivalisland: Survival Island 0.1.5
		tacocraft: TacoCraft 1.3.0+mc.1.16
		team_reborn_energy: Energy 0.1.0
		techreborn: Tech Reborn 3.4.2+build.48
		terraform: Terraform 2.1.6+build.30
		terrestria: Terrestria 2.0.2+build.29
		the_bumblezone: The Bumblezone - Fabric 1.16.1-2.0.1
		trapexpansion: Trap Expansion 1.3.2
		traverse: Traverse 2.2.11+build.23
		trinkets: Trinkets 2.6.1
		tweed: Tweed API 3.0.0-beta.9
		universalcomponents: Universal Components 0.7.2+1.16-pre2
		vanilla-hammers: Vanilla Hammers ${version}
		vanilladeathchest: VanillaDeathChest 1.16.1-1.11.0.2-fabric
		vanillaplusbiomes: Vanilla Plus Biomes 0.2.2
		villagerhats: Villager Hats fabric-1.16-rc1-1.0.0
		waila: Hwyla 1.9.22
		wands: Wands Mod 1.1
		whereisit: Where Is It 1.6
		whiplash: Whiplash: Magic Dungeons 1.0.0
		window_title_changer: Window Title Changer 2.0.0-1.16.1
		winged: Winged Mod 1.16-1.1.1
		wolveswitharmor: Wolves With Armor 1.2.0-1.16.1
		woods_and_mires: Woods and Mires 1.0.0+1.16.1
		xaerominimap: Xaero's Minimap 20.15.2
		xaeroworldmap: Xaero's World Map 1.7.2.1
	Patchouli open book context: n/a
	Player Count: 1 / 8; [class_3222['dc_wan'/641, l='ServerLevel[CoffeeCoffeeCoffee]', x=-99.39, y=96.18, z=-485.34]]
	Data Packs: vanilla, fabric/crusade, fabric/iron-jetpacks, fabric/kibe (incompatible), fabric/adventurez, fabric/chunkactivator, fabric/packages, fabric/astromine, fabric/villagerhats, fabric/mo_glass, fabric/polydungeons, fabric/bunch-o-trinkets, fabric/techreborn (incompatible), fabric/piglintag, fabric/morepaths, fabric/flora-doubling, fabric/mostructures, fabric/trapexpansion, fabric/adorn, fabric/golemsgalore, fabric/linkedstorage, fabric/terrestria, fabric/wolveswitharmor, fabric/linkart, fabric/ecotones, fabric/bambootweaks, fabric/woods_and_mires, fabric/cotton-commons, fabric/wands, fabric/winged, fabric/harvest, fabric/inmis, fabric/byg, fabric/cinderscapes, fabric/whiplash, fabric/lvmnt, fabric/staffofbuilding, fabric/glassential, fabric/adabraniummod (incompatible), fabric/improved-stations, fabric/simpledrawers, fabric/tacocraft, fabric/fabric-tool-attribute-api-v1, fabric/rare-ice, fabric/blockus, fabric/identity, fabric/ring_of_miner, fabric/hard-hat-steve (incompatible), fabric/expandedstorage, fabric/dishes, fabric/herbocraft, fabric/libcd, fabric/vanilla-hammers, fabric/simpleteleporters, fabric/simplevoidworld, fabric/flonters, fabric/shest, fabric/campanion, fabric/sandwichable, fabric/glassdoor, fabric/traverse, fabric/artofalchemy, fabric/moreberries, fabric/slotlink, fabric/fabric-furnaces, fabric/ltr, fabric/hotm, fabric/secretrooms, fabric/facility, fabric/layingbox, fabric/respawnablepets, fabric/the_bumblezone, linkedstorage:enderstorage, secretrooms:server_pack
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'`

**Comment by the-webguys** [comment]
I just noticed there is a new version. will that break anything on an existing server?

**Comment by CorgiTaco** [comment]
Here is your culprit: 
https://github.com/CorgiTaco/BYG/issues/19#issuecomment-657207356

And no.
