### ISSUE TITLE
Slab recipes in stonecutter are incorrect

### ISSUE THREAD

**Issue by jchilly8** [CorgiTaco/BYG#280]
The stonecutter recipes for slabs made of BYG stones only give one slab, when I assume they should give two.

**Comment by CorgiTaco** [comment]
Pls specify the mod loader

**Comment by jchilly8** [comment]
Forge, 1.16.4

**Comment by jchilly8** [comment]
It's just the dacite, soapstone, and scoria stone slabs. Sorry for not saying this at first, I hadn't realized
