### ISSUE TITLE
Changing World Type causes short pause with mod BetterNether

### ISSUE THREAD

**Issue by linzexin022** [CorgiTaco/BYG#283]
**Before filling out this issue: **
**1. For major bugs, we only support BYG's latest version on a per Minecraft version basis(i.e latest for 1.15 is 1.0 while latest for 1.16 is 1.1).**
**2. Please test BYG on its own to confirm whether or not this is a mod conflict**

__**Mod conflict? If so, please clarify which mod is conflicting, if not skip this.**__

BYG and BetterNether

__**API/Modloader**__

Fabric Loader 0.11.1

__**Describe the bug**__

With BYG and BetterNether installed, creating a new world (click the "Singleplayer" button) or changing World Type (click the "World Type" button) in single game causes short pause. 

__**To Reproduce**__

Install Fabric API 0.30.0, BYG 1.1.3, BetterNether 5.0.5; Start the game, create a new world and choose World Type, then this issue happens.

**Expected behavior**

No more short pause when creating a new world and changing World Types.

**Screenshots/Videos**

https://user-images.githubusercontent.com/59003232/106695141-f6bea380-6614-11eb-995a-47e083538e87.mp4

**Additional context**

**Logs**

`[main/ERROR]: Feature: Not a JSON object: "minecraft:freeze_top_layer"`

**Heap Dumps**
*If performance, please provide a heap dump/some sort of profile of your game(I recommend: https://visualvm.github.io/download.html)*
Heap Dump/Profile -

**Comment by CorgiTaco** [comment]
This is probably the built in registry being serialized tbh. Other than that it's a little hiccup on performance and that has no real solution other than getting a a better cpu.
