### ISSUE TITLE
A (sorta) issue or feature idk

### ISSUE THREAD

**Issue by HexBugOrion** [CorgiTaco/BYG#288]
PARTIAL PROBLEM: No it is not a problem other than a slight inconsistency.

SOLUTION: A fix of README.md that displays proper biome list.

ALTERNATIVES: Making a wiki for the biomes.

I hope I'm not being too annoying!

**Comment by CorgiTaco** [comment]
A wiki already exists: https://oh-the-biomes-youll-go.fandom.com/wiki/Oh_The_Biomes_You%27ll_Go_Wiki#About_Biomes_you.27ll_go

 And the readme matches the curseforge page.
