### ISSUE TITLE
BYG flowers and saplings can't be placed in flower pots

### ISSUE THREAD

**Issue by nadroj-h** [CorgiTaco/BYG#29]
(MC 1.15.2, Forge 31.2.0, BYG 1.0.9, many other mods)

As far as I can tell, vanilla and other mods' flowers/saplings/plants still work, it's just the BYG ones that can't be placed in flower pots.

**Comment by CorgiTaco** [comment]
Has been added and will be available OCT 31 in BYG 1.1
