### ISSUE TITLE
SUGGESTION: Config setting for tree density

### ISSUE THREAD

**Issue by Zothen1973** [CorgiTaco/BYG#292]
Many forest like biomes have such a high tree density, that no passive/neutral mobs are allowed to spawn, due to not being able to see the sky or a too dark light level.

Could you add a config value per biome to control the tree density , e.g. a percentage value for 100 being default.

Thanks for all the efforts you put into this mod.

**Comment by CorgiTaco** [comment]
Achieavable via datapacks. Watch the tutorial i made for this here: https://youtu.be/TF_p8OeB-hc
