### ISSUE TITLE
Compatibility with Cinderscapes

### ISSUE THREAD

**Issue by o-negai** [CorgiTaco/BYG#30]
When i downloaded BYG and started a new world, I used the /locatebiome command and found that none of the biomes from Cinderscapes would come up. They all came up as "Could not find a biome of type <Biome Name> within reasonable distance", meaning the biome ID's were valid yet could not be found. I removed BYG and loaded a new world and the biomes from Cinder loaded correctly. I am running Cinderscapes v1.0.4 for 1.16.1 and Biomes You Go 1.0.7 MCV: 1.16.1 on Fabric Loader 0.8.9+build 203-1.16.1.

**Comment by Linguardium** [comment]
It looks like the way ahead for this is to implement the same system as smolder (register existing and all future additions of NETHER category biomes). 
This would likely be best with a mixin plugin to conditionally load the mixin if Smolder does not exist or to require 0 on that one mixin to allow loading with a failed mixin in the event of smolder's overwrite. Without this, byg (or smolder) will fail to load.

**Comment by CorgiTaco** [comment]
I pull from the fabric api internal biome data for nether biomes, it's their duty to ensure that their biomes are added through the provided fabric api

**Comment by Linguardium** [comment]
how do you handle biomes added after your mod loads? if i read it right, you register a new biomelist with the contents that are currently in the list but never address additions after

**Comment by CorgiTaco** [comment]
It shouldn't necessarily matter since the BP is only ever called at world/dimension load?

**Comment by Linguardium** [comment]
but the static variables are initialized at class initialization, meaning at class load the list is set, not at world/dimension load

**Comment by CorgiTaco** [comment]
Oh true

**Comment by CorgiTaco** [comment]
Uhhhhhhhhh I'm not sure then

**Comment by CorgiTaco** [comment]
Should i create a custom event for this?

**Comment by Linguardium** [comment]
no, check out https://github.com/TerraformersMC/Smolder/blob/master/src/main/java/com/terraformersmc/smolder/Smolder.java

basically they add all nether biomes in the registry, then add a callback for any additional entries that are added later

we do need to test with smolder though to ensure the byg mixin wont cause minecraft to fail to load due to a failed mixin and with smolder doing an overwrite, it should cause conflict (or just add smolder to dependencies and remove the biome supplier completely )

**Comment by CorgiTaco** [comment]
Patched in #31 PR

**Comment by CorgiTaco** [comment]
Patched here: https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go-fabric/files

LMK if it doesn't work.
