### ISSUE TITLE
No Astral Sorcery shrines for thousands of chunks?

### ISSUE THREAD

**Issue by HaxtonSale1** [CorgiTaco/BYG#300]
**Is your feature request related to a problem? Please describe.**

I'm on a server with both BoP and BYG (Enigmatica 6), I looked for thousands of chunks looking for Astral Sorcery shrines but only found one small shrine and no large ones
![2021-02-13_12 03 43](https://user-images.githubusercontent.com/13237198/107840125-89202d80-6df3-11eb-8cee-e054f722cbc9.png)

**Describe the solution you'd like**
Tag the biomes so Astral Sorcery shrines can spawn, especially in Dunes biome

**Comment by CorgiTaco** [comment]
That's to be done in their config file, not by us
