### ISSUE TITLE
More block recipes, uses, and interactions.

### ISSUE THREAD

**Issue by Angular-Angel** [CorgiTaco/BYG#302]
**Is your feature request related to a problem? Please describe.**
So, I love the ancient forest biome, but it's a little disappointing that you can't do much with a lot of the cool stuff in it. Like, there's no way to grow most of the trees in it - you can plant saplings, but they grow into smaller, more normal trees, without the pollen blocks. In general, there's no way to make the pollen blocks, other than mining them with silk touch. You can't even combine the pollen items you get from breaking them back into pollen blocks, like with glowstone. You can't use the pollen for anything in general. Or, for the giant flowers, there's no way to grow those either. This problem alsoapplies to many of the interesting things found in other biomes throughout the mod.

**Describe the solution you'd like**
I'd like more recipes, uses, and interactions for block and items. Combining pollen back into pollen blocks, maybe using pollen on saplings to grow trees in the ancient forest style, or using it on leaves to turn them into pollen blocks? Maybe a bonemeal or fertilizer interaction for pollen blocks? Some method of growing the giant flowers? etc, etc.

**Comment by Angular-Angel** [comment]
Also, I feel like pollen blocks should be subject to the same decay rules as leaves are.

**Comment by AOCAWOL** [comment]
Hi! So currently BYG is going through 3 patches. Patch 1 is the End, Patch 2 is the Nether, Patch 3 is the Overworld. Each patch revamps and polishes the dimension's content. Pollen will be getting many new uses in Patch 3 such as Pollinated Bonemeal which can grow crystals from the BYG deposits such as therium, it can also "bonemeal" certain BYG flowers to grow into the big boy flowers found in biomes like the Ancient Forest. Patch 3 will also be taking a look at the biomes with vanilla leaves & logs and adjusting them to have custom leaves & saplings to make the spectacular trees we've designed to be more accessible to players :)  I'd suggest joining our discord to see upcoming features if you aren't in it already :D

**Comment by Angular-Angel** [comment]
Ah, okay! Alright, good to know! XD

**Comment by Angular-Angel** [comment]
Oh, the discord link is invalid for some reason, I don't know why. :/

**Comment by AOCAWOL** [comment]
https://discord.com/invite/zQA4eez2eS this one?

**Comment by Angular-Angel** [comment]
Yes, that one works!

**Comment by Angular-Angel** [comment]
When you guys get around to updating the overworld, you should make the ancient forest trees growable via using pollen on saplings, instead of giving them custom leaves and their own saplings. I dunno, I just think the idea is really cool now that I've thought of it. XD

Edit: I know it doesn't make a ton of sense, but I think it makes about as much sense as planting coca bean pods on jungle wood does, so it should fit right in.
