### ISSUE TITLE
Palo Verde sapling cannot be planted on red sand

### ISSUE THREAD

**Issue by saltyseadoggo** [CorgiTaco/BYG#304]
__**API/Modloader**__
Fabric

__**Describe the bug**__
Palo Verde saplings cannot be planted on red sand, despite Palo Verde growing on red sand in the Lush Red Desert biome. I didn't do further testing to see if they could or couldn't be planted on regular sand or BYG's coloured sands.

**Expected behavior**
Palo Verde saplings would be able to be planted on red sand, as they are found growing on red sand in the wild. If it can't be planted on regular sand or BYG's new coloured sands, I would definitely expect the former, and possibly the former, depending on what you feel is appropriate, since those sands occur in other environments, like white sand in the End, where the Palo Verde might not be able to grow? It's all up to you.~

**Comment by YaBoiChips** [comment]
they can now be planted on all sand types
