### ISSUE TITLE
Removed BYG now ores won't generate. 

### ISSUE THREAD

**Issue by morris2spears** [CorgiTaco/BYG#305]
Fabric?

__**Describe the bug**__
Had BYG installed on SMP server, it was causing errors with bookshelves and enchanting, So I removed it. As a consequence now ores will not generate in the overworld. 

__**To Reproduce**__
Install BYG with fabric, generate a world, and then remove byg. Ores will no longer generate in new chunks. 

**Expected behavior**
Ores should generate.

**Comment by CorgiTaco** [comment]
Not our issue after you remove byg
