### ISSUE TITLE
The distribution of biomes in the Nether changes everytime the game is loaded.

### ISSUE THREAD

**Issue by SatDog92** [CorgiTaco/BYG#309]
__**Versions: Minecraft 1.16.5, byg-1.1.10, Forge 36.0.15. EDIT: Also on Forge 36:0.42 **__
__**EDIT: Fabric is also affected: Fabric 0.11.1 (with Fabric API 0.30.3), byg-1.1.5 **__
__**EDIT2: This still happens on byg-1.1.11, Forge 36.0-58, LOL! **__

__**Describe the bug**__
The distribution of Nether biomes changes everytime the **GAME**, not the world, is loaded. This doesn't happen in the Overworld and in the End, as their biome distribution is determined by the seed as intended. This happens with no other mod installed. On Fabric, this is less erratic: for example, i noticed that on seed "-4984821034741306506", the spawn Nether biome can be either Glowstone Gardens or Subzero Hypogeal, while on Forge, the biome always changes.

__**To Reproduce**__
1. create a new world, go into the nether and quit the game (exiting the Nether doesn't make a difference).
2. open the game again, open the same world, travel to unloaded chunks in the Nether (or create a new world with the same seed), and witness the change to the distribution of the biomes.

Obviously, to make an example: i created different worlds in order to find a seed with a spawn that suited my preferences, and eventually found one with the witchhazel tree biomes and the Subzero Hypogeal one. When i went, recreated the world on Survival, and finally got access to the Nether, the biome was Magma Wastes instead. At first, i thought it was a problem of seed or mod conflict, but eventually found out that, in fact, the biome distribution changed everytime i deleted all the chunks i generated previously, even if no other mod (including optifine, so only the byg mod file in the mod folder) is installed. As seen in the screenshots, this is kind of game breaking and makes the Nether almost unexplorable.

**Expected behavior**
The biome distribution should be fixed and determined by the seed, as anyone would expect.

**Screenshots/Videos**
The screenshots below show the effect of this bug: basically, it's as if terrain was sliced through the horizontal axes.
[2021-02-17_22 50 25](https://user-images.githubusercontent.com/56725716/108275984-6ab18d80-7177-11eb-8ea3-da1ee42bf294.png)
[2021-02-17_22 51 01](https://user-images.githubusercontent.com/56725716/108275986-6c7b5100-7177-11eb-98db-9001c00358c7.png)
[2021-02-17_22 51 14](https://user-images.githubusercontent.com/56725716/108275990-6d13e780-7177-11eb-8011-7952a7eef9b8.png)
[2021-02-17_22 51 28](https://user-images.githubusercontent.com/56725716/108275992-6dac7e00-7177-11eb-927b-5f364865ec2a.png)
[2021-02-17_23 17 22](https://user-images.githubusercontent.com/56725716/108275994-6f764180-7177-11eb-822c-449d47e3d138.png)
[2021-02-17_23 17 37](https://user-images.githubusercontent.com/56725716/108275997-70a76e80-7177-11eb-87d1-9ca65066915d.png)
[2021-02-17_22 49 13](https://user-images.githubusercontent.com/56725716/108276001-71400500-7177-11eb-8ed4-6e49a13b4c20.png)
[2021-02-17_22 49 23](https://user-images.githubusercontent.com/56725716/108276003-71d89b80-7177-11eb-99df-03af8c0f6399.png)
[2021-02-17_22 50 17](https://user-images.githubusercontent.com/56725716/108276004-7309c880-7177-11eb-8099-cfcf5db17940.png)

**Additional context**
None

**Logs**
Forge:
Logs after entering the Nether with no chunks generated and closing the game afterwards.
[latest1.log](https://github.com/CorgiTaco/BYG/files/5998999/latest1.log)
[debug1.log](https://github.com/CorgiTaco/BYG/files/5999001/debug1.log)
EDIT: Recent Forge version log: 
[debug-2.log](https://github.com/CorgiTaco/BYG/files/6014749/debug-2.log)
[2021-02-20-2.log](https://github.com/CorgiTaco/BYG/files/6014750/2021-02-20-2.log)
**EDIT2** : Forge 36.0-58 log:
[before.log](https://github.com/CorgiTaco/BYG/files/6140513/before.log)

Logs after opening the game again, and travelling to ungenerated chunks in the Nether of the same world (or after creating a world with the same seed).
[latest2.log](https://github.com/CorgiTaco/BYG/files/5999000/latest2.log)
[debug2.log](https://github.com/CorgiTaco/BYG/files/5998998/debug2.log)
EDIT: Recent Forge version log:
[2021-02-20-1.log](https://github.com/CorgiTaco/BYG/files/6014754/2021-02-20-1.log)
[debug-1.log](https://github.com/CorgiTaco/BYG/files/6014755/debug-1.log)
**EDIT2** : Forge 36.0-58 log:
[after.log](https://github.com/CorgiTaco/BYG/files/6140514/after.log)

Fabric:
Logs after entering the Nether with no chunks generated and closing the game afterwards.
[latest1.log](https://github.com/CorgiTaco/BYG/files/6002933/latest1.log)

Logs after opening the game again, and travelling to ungenerated chunks in the Nether of the same world.
[latest2.log](https://github.com/CorgiTaco/BYG/files/6002934/latest2.log)

What a bummer, i just started a new world finally but i can't play this if the Nether changes biome distribution everytime i open the game.

**Comment by desagas** [comment]
Same happening on my end ... and, I was going to say how very much I love the music you have added to the nether, or, at least I am assuming it is you. WOW, very temple of Time esk! LOVE

Anyways, to add to the above, this happens on both dedicated server and single player worlds, with only byg 1.1.1.0, and forge 1.16.5-36.0.42.

**Comment by Redd56** [comment]
happening to me in fabric as well
fabric: 0.11.3
byg: 1.1.7

**Comment by Redd56** [comment]
nvm its soemthing else breaking somewere

**Comment by Khaeops** [comment]
Can also confirm this is happening to me too on Forge.

Forge: 35.1.37
BYG: 1.1.6

**Comment by TheSnowyChickens** [comment]
Same here, we have to reset the nether with every server restart. :(
