### ISSUE TITLE
Some mechanics regarding saplings and growth are still inconsistent/bugged (and few other issues).

### ISSUE THREAD

**Issue by SatDog92** [CorgiTaco/BYG#310]
__**Minecraft 1.16.5, byg-1.1.10.jar, Forge 36.0.15**__
__**EDIT: Fabric is also affected: Fabric 0.11.1 (with Fabric API 0.30.3), byg-1.1.5 ***__

__**The problems**__
A few saplings are still not working correctly. Palo Verde sapling can't grow on: meadow dirt/grass, overgrown stone/dacite/netherrack, podzol dacite, glowcelium block, peat, ether/shulkren/bulbis/nightshade phylium, ether soil, vermillon sculk. Also the Withering Oak sapling doesn't really grow on meadow grass block/dirt, but not sure about the latter. All the other saplings are fixed, though.
Related to Giant Spruces grown with the 2x2 setupf: how do they turn the modded grounds (the rocks as well) into vanilla podzol when they grow? No other podzol stone variants like the dacite one? Like podzol blocks for meadow and stone, for example?

Also noticed something: some grounds/grasses cannot have stuff placed on it if exposed to sky: these are Bulbis Phycelium, Ether Soil, Vermillon Sculk, Netherrack Mycelium (on a related note, all the vanilla fungi/mushrooms can be placed on these, it's the modded ones that don't work correctly). On Fabric you can't place stuff even if sky is not exposed, and regarding the mushroom similar to the vanilla brown/red ones like the deathcap and the glowshoorms, you can't even place them on dirt blocks and all the stone variants (examples: vanilla ore blocks, andesite and other modded stones). But the Soul Shroom, Sythian Shroom and Embur Wart can be placed on these even if the sky is exposed (also on Fabric). 

All the mushrooms/warts from both the Nether and the End should be allowed to be placed on every type of non-overworld ground (except from the podzols and the mycelium blocks from both vanilla and mod, as the vanilla Nether fungi can be placed on them), and all the overworld mushrooms should be allowed to be placed on every non-grass/stone ground if exposed to sky.

Since this mod allows a lot of freedom on where saplings, fungi and mushrooms can be planted, i would also unlock the vanilla ones (allow both vanilla and modded fungi/mushrooms to be placed and grown on every other type of modded phylium/nylium/mycelium), but that's more like a simple request to make mechanics a bit more consistent than a minor bug.

Another problem is how all the the types of nylium/phylium/mycelium grounds are not renewable or allowed to spread around the 9x9x9 radius like in the case of vanilla crimson/warped nylium (except from Blue Netherrack growing into Embur Nylium if adjacent to another Embur Nylium block, which work as intended).

Other minor issues:

-Bulbis anomaly doesn't make the levitation icon appear even if it works.
-Cryptic bramble and cryptic bramble branch have item/block.byg laber on it

And these are more like small suggestions which would improve the experience a bit (at least for me) and i'm writing these here now that i'm here, and i don't feel like opening a new issue for this:
-While some trees like baobab and witchhazel require 2x2 saplings, redwood and other VERY TALL trees only require one sapling? What about 2x2 or 3x3? Just a whim, though.
-Do withering oak sapling take so much bone meal to grow, as much as vanilla big oak trees (not the dark oak)? Intended?
-Blue and Yellow Nether bricks don't have slabs and stairs?
-Sythian Fungi can't grow near/adjacent to each other and overlap like the warped and crimson fungus and are limited to large space requirements (too much space is required even if they're mostly a 9x9 wide tree, whereas the warped/crimson fungus don't have this limit) I would remove the limit for the Embur Wart too, as it's more like a wood-like fungus like the warped/crimson one than a mushroom like the red/brown ones. ( [Example of how warped/crimson fungi can grow in Vanilla](https://user-images.githubusercontent.com/56725716/108282829-8bcbab80-7182-11eb-830f-99908b91b733.png)

**Logs**
Forge:
[latest.log](https://github.com/CorgiTaco/BYG/files/5999258/latest.log)
[debug.log](https://github.com/CorgiTaco/BYG/files/5999259/debug.log)

Fabric:
[byglogfabric.log](https://github.com/CorgiTaco/BYG/files/6002746/byglogfabric.log)
[latest.log](https://github.com/CorgiTaco/BYG/files/6002747/latest.log)

**Comment by Dakkaron** [comment]
Another one to add:
Orange Oak Saplings can be composted, while Red Oak Saplings cannot.

**Comment by faeandsugar** [comment]
Are these things still not going to be addressed?

**Comment by CorgiTaco** [comment]
@faeandsugar  They'll be addressed when I get to it.

**Comment by Razatop** [comment]
Can't get orchard saplings to grow up either, no matter bonemeal/time.

**Comment by camberp01** [comment]
Other major problem I found: you can't hoe lush dirt. Lush farmland exists, it's in the JEI and everything, but you can't use a hoe on it. Could we get that fixed?

**Comment by CorgiTaco** [comment]
@camberp01 if you're on 1.18+, this has been fixed internally
