### ISSUE TITLE
[1.16.5] IndexOutOfBoundsException: When flying fast on an I & F dragon

### ISSUE THREAD

**Issue by Cixon** [CorgiTaco/BYG#311]
__**Mod conflict? If so, please clarify which mod is conflicting, if not skip this.**__
This issue only occurs when I have my tamed Ice and Fire mod dragon on a chain lead to a bone wall.
When the dragon decides to fly around, I guess BYG chunks doesn't like this and has a issue
generating a chunk so it just kills the server.

__**API/Modloader**__
[1.16.5] Forge 36.0.21.

__**Describe the bug**__
Server crashes due to chunk not being able to generate by tamed dragon's free will flight.

__**To Reproduce**__
1.) Tame a ridable fire dragon via [Ice & Fire](https://www.curseforge.com/minecraft/mc-mods/ice-and-fire-dragons) mod.
2.) Tie to using chain on dragon wall and make a dragon forge.
3.) Dragon will try to fly around.
4.) See crash/logs.

**Expected Behavior**
Not the server crashing because the dragon wanted to fly around.

**Additional Context**
This happened on a server.

**Logs**
[crash-2021-02-18_10.23.12-server.txt](https://github.com/CorgiTaco/BYG/files/6002041/crash-2021-02-18_10.23.12-server.txt)
[debug.log](https://github.com/CorgiTaco/BYG/files/6002042/debug.log) Line 7206
[latest.log](https://github.com/CorgiTaco/BYG/files/6002043/latest.log) Line 1781

**Comment by Cixon** [comment]
Woo! Hey Corgi. :)
Can't wait to see this fixed!

**Comment by Cixon** [comment]
<comment below>

**Comment by CorgiTaco** [comment]
that's an unrelated issue probably from a separate mod as BYG has ZERO block entities
