### ISSUE TITLE
Vanilla bookshelf cannot be used to make a lectern when BYG is installed

### ISSUE THREAD

**Issue by saltyseadoggo** [CorgiTaco/BYG#312]
__**API/Modloader**__
Fabric

__**Describe the bug**__
BYG replaces the lectern recipe with one that uses the c:bookshelves tag, but doesn't add the vanilla bookshelf to said tag, so the vanilla bookshelf cannot be used in the recipe. The effective result is that the player needs to hunt down BYG wood types in order to make the lectern, which is needed for librarian villagers.

__**To Reproduce**__
- Attempt to craft a lectern using oak slabs and a vanilla bookshelf.
or
- With REI installed, check the lectern recipe. The vanilla bookshelf never appears in the cycling bookshelves.

**Expected behavior**
The vanilla bookshelf could be used to make a lectern, as it can be in vanilla.

**Comment by CorgiTaco** [comment]
FIxed in latest.

**Comment by Marshallcoolman** [comment]
Still having this issue
