### ISSUE TITLE
Palo verde, aspen, jacaranda, pink cherry, cika leaves drop apples

### ISSUE THREAD

**Issue by saltyseadoggo** [CorgiTaco/BYG#314]
__**API/Modloader**__
Fabric

__**Describe the bug**__
The leaves of the palo verde drop apples.

__**To Reproduce**__
Break a number of palo verde leaves in survival mode until one drops an apple.

**Expected behavior**
Assuming that this isn't intended, palo verde leaves would not drop apples.

**Screenshots/Videos**
If applicable, add screenshots/video to help explain your problem.

**Additional context**
The loot table (yeesh, it could use some spacing for legibility) for the palo verde leaves does indeed contain an entry for the apple, so fixing this should be as simple as removing it, assuming again that this is not intentional.

**Comment by saltyseadoggo** [comment]
This issue also applies to pink cherry leaves, aspen leaves and jacaranda leaves, and I would guess others.

**Comment by saltyseadoggo** [comment]
Also applies to cika leaves.

**Comment by YaBoiChips** [comment]
all leaves except the oak and orchard variants now don't drop leaves.
