### ISSUE TITLE
All BYG boats drop oak planks when broken by a long fall

### ISSUE THREAD

**Issue by saltyseadoggo** [CorgiTaco/BYG#316]
__**API/Modloader**__
Fabric

__**Describe the bug**__
When a BYG boat is dropped from a fair height, it breaks like vanilla boats, but drops oak planks and sticks instead of the planks that the boat was made out of.

__**To Reproduce**__
- Create a new world in Creative mode with cheats enabled.
- Go about ten or more blocks into the air, and run /summon byg:boat to summon an aspen boat.
- Watch it fall and then break into oak planks and sticks, as opposed to aspen planks and sticks.
- Optionally, use the command to summon other types of BYG boats, or pillar up and place them using their items. They all have the same result.

**Expected behavior**
BYG boats would drop their respective plank types when broken by fall damage.

**Comment by YaBoiChips** [comment]
this is already fixed
