### ISSUE TITLE
Issue with TerraForged + BYG

### ISSUE THREAD

**Issue by NaomiKuroi** [CorgiTaco/BYG#319]
**Before filling out this issue: **
**1. We only support the latest version of BYG on for Minor Bugs.**
**2. Please test BYG on its own to confirm whether or not this is a mod conflict.**

__**Mod conflict? If so, please clarify which mod is conflicting!**__
This is an issue with the terrain generation when using BYG with TerraForged.

__**API/Modloader**__
Forge

__**Describe the bug**__
Discovered some interesting terrain generation with lakes while using both TerraForged 0.2.7 and Oh The Biomes You'll Go 1.1.10. For clarification, these are supposed to be the lakes that generate at the start of rivers

__**To Reproduce**__
Just TerraForged and BYG together.

**Expected behavior**
Lakes are supposed to be lakes, but for some reason they're getting covered over.

**Screenshots/Videos**
![108764875-fc1e5800-7507-11eb-8ac7-467b96d154be](https://user-images.githubusercontent.com/47642944/109042812-758f8500-7685-11eb-84bf-144207d8c7a3.png)
![108764890-ff194880-7507-11eb-8422-3a4a15cd7055](https://user-images.githubusercontent.com/47642944/109042837-7f18ed00-7685-11eb-9408-66791f260dc8.png)

**Additional context**
Is there anything that can be done to prevent land from generating over the top of them? I noticed this doesn't happen with TerraForged and other biome mods, like BOP.

**Logs**
Use: https://paste.ee/ and paste the links. if log is huge please upload those
Please provide:
Crashlog - 
Debug.log - 
Latest.log -

**Comment by Corvus20** [comment]
I am having this issue too and it is driving me insane, idk what could be causing it.

**Comment by Koji-KAWAHARA** [comment]
Same here.  
MC 1.16.5
Forge 36.0.41
TF 0.2.8
BYG 1.1.10

**Comment by CorgiTaco** [comment]
it would be in your best interest removing this biome in their weight config for now. The way this surface builder works is that it assumes it is 1 block above sea level but since terraforged does NOT respect biome depth or scale, it'd be in your best interest to remove it by setting it to weight 0

**Comment by Koji-KAWAHARA** [comment]
Can I repost this issue to Terraforged issue tracker, with link to this page?

**Comment by NaomiKuroi** [comment]
I already did. They said the problem was with BYG. For now I’m just gonna use BOP, since I have yet to see any terrain generate on top of the lakes with that one

**Comment by Koji-KAWAHARA** [comment]
Nice.
