### ISSUE TITLE
Whenever I leave, I can't open up the world again.

### ISSUE THREAD

**Issue by NinjaNina123** [CorgiTaco/BYG#32]
So I've created many worlds with BYG and when I close them and try to open them again it just says, "Reading world data..." I've left this open for hours, but it doesn't change the screen. Is there a way to fix this?

**Comment by NinjaNina123** [comment]
I use 1.16.1 version btw

**Comment by CorgiTaco** [comment]
This is a mod conflict with BOP

**Comment by CorgiTaco** [comment]
And frankly idk how to solve it

**Comment by NinjaNina123** [comment]
Aw man

**Comment by CorgiTaco** [comment]
https://gist.github.com/CorgiTaco/254d8d5195cc65fd0bbaee0f98a232af

**Comment by CorgiTaco** [comment]
It'd be in your best interest to use these settings

**Comment by CorgiTaco** [comment]
Also join the discord if you'd like to speak further about this since ik it is confusing

**Comment by NinjaNina123** [comment]
Okay! Thank you very much! I'll try it right now!

**Comment by NinjaNina123** [comment]
Can you send a link/invite

**Comment by CorgiTaco** [comment]
https://discord.gg/U6Uzew

**Comment by NinjaNina123** [comment]
Ok I joined

**Comment by CorgiTaco** [comment]
Closing this as the world type is removed in 1.16.2
