### ISSUE TITLE
Quartzite sand has no effective tool

### ISSUE THREAD

**Issue by saltyseadoggo** [CorgiTaco/BYG#320]
__**API/Modloader**__
Fabric

__**Describe the bug**__
Quartzite sand cannot be mined faster with a shovel or even a pickaxe than it can be mined by hand.

__**To Reproduce**__
- Create a new world in Creative mode with cheats enabled.
- Place down three lines of about five quartzite sand.
- Give your character a Netherite shovel and pickaxe.
- Enter survival mode.
- Mine the first row of quartzite sand by hand. Note the speed at which you can do this.
- Mine the second row of quartzite sand with the shovel. Note that the mining speed does not increase.
- Mine the third row of quartzite sand with the pickaxe. Note that the mining speed still does not increase.

**Expected behavior**
Quartzite sand could be mined faster using a shovel, it being a sand type block.

**Comment by YaBoiChips** [comment]
fixed on forge side
