### ISSUE TITLE
Beige underside texture not used on Wailing Garth mushrooms

### ISSUE THREAD

**Issue by saltyseadoggo** [CorgiTaco/BYG#321]
__**API/Modloader**__
Fabric

__**Describe the bug**__
The red, brown and green mushrooms, the wood blewits, the death caps, the weeping milkcaps and the soul shrooms in the Wailing Garth biome, and likely other biomes that use them, use their outer texture on the inner parts of the mushroom, when vanilla large mushrooms use the beige inner texture there instead.

__**To Reproduce**__
- Create a new world.
- Travel to a Wailing Garth biome.
- Look underneath the mushrooms.

**Expected behavior**
The mushrooms in the Wailing Garth biome and other BYG Nether biomes would have the beige inner texture on their inside areas to match vanilla large mushrooms.

**Screenshots/Videos**
The issue demonstrated with a red and a brown mushroom.
Current:
![2021-02-24_22 01 10](https://user-images.githubusercontent.com/69029346/109236333-44e24500-7784-11eb-8432-8311da7c8999.png)
Expected:
![2021-02-24_22 01 48](https://user-images.githubusercontent.com/69029346/109236344-490e6280-7784-11eb-9a37-839f9f07daf5.png)

**Comment by CorgiTaco** [comment]
Intentional behavior unless youd like to rewrite our mushroom generating code :)
