### ISSUE TITLE
Sliding down Embur Gel blocks creates honey block particles

### ISSUE THREAD

**Issue by saltyseadoggo** [CorgiTaco/BYG#322]
__**API/Modloader**__
Fabric

__**Describe the bug**__
Entities sliding down the sides of Embur Gel blocks create honey block particles as they slide down.

__**To Reproduce**__
- Create a new world in creative mode with BYG and the Fabric API loaded.
- Assemble a tower of embur gel blocks, between five and ten blocks tall or so.
- Slide down the tower's side. Note the honey block particles.
- Use a spawn egg to spawn a mob such as a Piglin on the side of the tower, and push them closer to it so that they slide down it. Note the honey block particles still.

**Expected behavior**
Sliding down Embur Gel blocks would create Embur Gel particles.

**Screenshots/Videos**
![2021-02-25_16 18 54](https://user-images.githubusercontent.com/69029346/109236814-321c4000-7785-11eb-92f1-ee96e0e3f9ba.png)

**Comment by CorgiTaco** [comment]
Intentional behavior
