### ISSUE TITLE
[1.16.5] Another IndexOutofBoundsException: This time, I'm not sure what the issue is.

### ISSUE THREAD

**Issue by Cixon** [CorgiTaco/BYG#323]
**Context**
Now this bug is very similar to my previous ticket #311.
I have a comparison here -> [(1)](https://imgur.com/eEx5c85) and [(2)](https://imgur.com/9Z0SS43) to the #311 latest.log to this bug.
Just a fair warning, I'm not a modder and this could just be a duplicate ticket.

__**API/Modloader**__
I am now using a new forge compared to the #311 ticket.
[1.16.5] Forge 36.0.42
Same BYG version as before.

__**Describe the bug**__
I was just traveling around on my server on foot when I noticed chunks weren't loading anymore.
I go and check my server and see it's down.

__**To Reproduce**__
1.) Install a 1.16.5 Forge 36.0.42 server.
2.) Travel long distances in deserty/savanna biomes I guess? _(that's where I was when it happened.)_
3.) See crash/logs.

**Expected Behavior**
Not the server being murdered. Lol.

**Logs**
[latest.log](https://github.com/CorgiTaco/BYG/files/6053555/latest.log) **LINE 1641**
[debug.log](https://github.com/CorgiTaco/BYG/files/6053556/debug.log) **LINE 7307**

**Comment by CorgiTaco** [comment]
A work around for this crash atm is: 
Old:
```json
"hills": [
        {
          "name": "byg:fresh_water_lake",
          "weight": 5
        },
        {
          "name": "byg:red_oak_forest",
          "weight": 0
        }
      ]
```

New: 
```json
"hills": [
        {
          "name": "byg:fresh_water_lake",
          "weight": 5
        }
      ]
```
