### ISSUE TITLE
Nether/End biomes don't generate

### ISSUE THREAD

**Issue by dromedar17** [CorgiTaco/BYG#325]
I can't seem to get any of the nether and end biomes to generate.

__**API/Modloader**__
Forge 36.0.43

__**Describe the bug**__
Only the vanilla biomes generate in the nether and in the end.
\locatebiome also can't find any byg biomes in the nether or the end.

__**To Reproduce**__
Create new world, travel to the nether, use e.g. /locatebiome byg:embur_bog.
It can't find anything within a "reasonable distance".
The same with the other nether biomes.

**Expected behavior**
The command returns the coordinates of the nearest embur bog.

**Additional context**
Biomes in the overworld generate just fine.
When I install better end alongside byg, the end biomes appear to spawn correctly. The nether biomes are still missing though.

I have tested this without other mods installed, to make sure it's not a mod conflict.

**Comment by CorgiTaco** [comment]
sounds to me your config has it set to false

**Comment by dromedar17** [comment]
Everything is set to default values I think. Is there a config option besides ControlNether/ControlEnd that I am missing?
I was wondering if it's something like that.

**Comment by dromedar17** [comment]
~~nvm, deleting the config folder fixed it. I guess you can file this under PEBKAC.~~

Ah, I think I found the source of my stupid. I was creating a new world by clicking on "re-create" on an old world. I wasn't aware that this effects more than just the settings visible in the menu.
