### ISSUE TITLE
Certain stone type blocks only give one slab when used in a stonecutter

### ISSUE THREAD

**Issue by StarWolfQueen** [CorgiTaco/BYG#326]
**API/Modloader**
Fabric

**Describe the bug**
Specifically mossy stone and dacite tiles where the ones I noticed, but there may be others. The main issue is that, when put into a stonecutter, both only gave one slab.

**To Reproduce**
Place either mossy stone or dacite tiles into a stonecutter, then select the slab option.

**Expected behavior**
Expected to get two slabs, but only got one.

**Comment by AOCAWOL** [comment]
fixed
