### ISSUE TITLE
[1.16.4] biomes not loading trees or plants ?

### ISSUE THREAD

**Issue by cherriibomb** [CorgiTaco/BYG#327]
so basically i have version 1.1.6 of biomes you'll go and the world will load normally, but a good chunk of the biomes do not load any of the trees or plants that are meant to be there. i tried the 1.1.5 and a few of the 1.1.7 on curse forge but they all either crashed when i tried to load it or it did the same thing.
is anyone else having this issue???

this is my mod list 
<img width="556" alt="Screen Shot 2021-03-03 at 1 55 37 PM" src="https://user-images.githubusercontent.com/80001380/109856985-236fd600-7c28-11eb-9c6a-841950c7a7c8.png">

and here are a few screenshots of biomes without anything (as you see in the top left the biome name)
![2021-03-03_14 03 14](https://user-images.githubusercontent.com/80001380/109858064-5d8da780-7c29-11eb-86f5-80a09f81faa3.png)
![2021-03-03_13 10 40_2](https://user-images.githubusercontent.com/80001380/109858136-71390e00-7c29-11eb-9227-9e815535cbdf.png)

**Comment by CorgiTaco** [comment]
Update BYG, update optifine.

**Comment by cherriibomb** [comment]
since im on 1.16.4, the optifine version i have is the only available one, but what version do you suggest for BYG ??

**Comment by CorgiTaco** [comment]
All 1.16.4 mods basically work on 1.16.5. and i recommend BYG's latest

**Comment by cherriibomb** [comment]
okay !! ive tried 1.1.10, 1.1.9, and 1.1.8 now (both with and without other mods in the folder) and my game has crashed for all of them so far. should i try updating forge to 1.16.5 as well ? I'm just worried about losing world data :0
