### ISSUE TITLE
Make warped/oddity cactus respect Forgery/Fabrication's stable cactus tweak

### ISSUE THREAD

**Issue by saltyseadoggo** [CorgiTaco/BYG#329]
**Is your feature request related to a problem? Please describe.**
[Forgery and Fabrication](https://github.com/unascribed/Fabrication) are the Forge and Fabric versions of a vanilla tweaks type of mod. It does everything that it does without any new assets, instead using appropriate mixins and the like to achieve its changes.
One of the tweaks that it adds is [stable cacti](https://unascribed.com/fabrication/#fixes.stable_cacti), which allows cactus to generate in the world next to eachother, and prevents them from breaking when a block is placed next to them, while still allowing cactus farms to work by retaining vanilla behaviour for when they grow.
I had assumed that this would work automatically with BYG's two cactus variants, the warped cactus and the oddity cactus, through the power of class extensions or some such, but it does not.

**Describe the solution you'd like**
I would like BYG's warped and oddity cacti to respect Forgery/Fabrication's `stable_cacti` tweak when it is active, and both generate next to blocks/eachother in their respective biomes, and not break when blocks are placed next to them.

**Additional context**
For your reference:
The mixin for this tweak in Fabrication: [here](https://github.com/unascribed/Fabrication/blob/trunk/src/main/java/com/unascribed/fabrication/mixin/a_fixes/stable_cacti/MixinCactusBlock.java)

**Comment by CorgiTaco** [comment]
Unfortunately this is not possible via class extensions
