### ISSUE TITLE
BYG refactor causes biomes in old worlds to shuffle

### ISSUE THREAD

**Issue by Linguardium** [CorgiTaco/BYG#33]
not sure what there is to be done about this. I loaded a world started in 0.9.4 in 1.0.8 and biomes were shuffled (even had a nether biome in overworld programatically, generation had already happened so no nether blocks were visible)

actually, was likely an even earlier version

**Comment by Linguardium** [comment]
probably marginal testing needed, but it turns out there were about 3 biome mods that were updated along with the byg mod and another biome that changed in the ow was clearly not a byg biome. 
likely not a byg issue.

**Comment by CorgiTaco** [comment]
Is there anything I can for this? Seems like no...?

**Comment by Linguardium** [comment]
no i dont think so, doesnt seem like byg's fault after testing and the shift was from fairly old versions of several mods
