### ISSUE TITLE
Mobs Won't Spawn When Combined with Biomes O Plenty

### ISSUE THREAD

**Issue by InteJason** [CorgiTaco/BYG#330]
When used with biomes o plenty, mobs from dungeons mobs, dannys expansion and greek fantasy don't spawn even though they use biome dictionary to spawn mobs (or if they do, very rarely). Structures from valhesia structures, when dungeon arises and hunterillager spawn a lot less often as well.

__**API/Modloader**__
Forge

__**To Reproduce**__
Install the above mods, and turn the spawn rates of the structures and mobs to 10x more
Start a world
Fly around and check if mobs spawn

**Expected behavior**
mobs spawning, and structures spawning much more frequently

**Additional context**
1.16.4 Forge latest version 35.1.37
byg 1.1.8

**Comment by AOCAWOL** [comment]
This really seems like a BOP issue. We utilize the Forge Biome Dictionary on all of our biomes, if a structure or mob mod fails to utilize the biome dictionary we can't fix that for them.

**Comment by AOCAWOL** [comment]
Unless there is visible proof that it is BYG's fault this will remain closed.
