### ISSUE TITLE
UAD/BYG Nether Problems

### ISSUE THREAD

**Issue by connorgoober** [CorgiTaco/BYG#332]
**Before filling out this issue: **
**1. For major bugs, we only support BYG's latest version on a per Minecraft version basis(i.e latest for 1.15 is 1.0 while latest for 1.16 is 1.1).**
**2. Please test BYG on its own to confirm whether or not this is a mod conflict**

__**Mod conflict? If so, please clarify which mod is conflicting, if not skip this.**__
Conflict with Ultra Amplified Dimension (UAD)

__**API/Modloader**__
Forge 1.16.5

__**Describe the bug**__
When used with UAD, the nether biomes from that dimension spawn in the actual nether.

__**To Reproduce**__
Go into the nether with both BYG and UAD installed.

**Expected behavior**
BYG biomes will spawn like normal. However, vanilla biomes spawn along with their UAD counterparts, causing glitchy generation.

**Screenshots/Videos**
![2021-03-05_22 36 34](https://user-images.githubusercontent.com/68136120/110196722-a5682680-7e03-11eb-8055-6a02cbed30a4.png)
![2021-03-05_22 38 30](https://user-images.githubusercontent.com/68136120/110196723-a731ea00-7e03-11eb-9a06-a443abcb10d9.png)

**Additional context**
This doesn't happen with just UAD installed.

**Comment by TelepathicGrunt** [comment]
@connorgoober You should blacklist my mod's biomes from byg by using byg's configs. Byg is doing everything correctly and they pull in all nether category biomes. My mod's nether biomes are also categorized as nether which got them sucked into the BYG nether.

**Comment by CorgiTaco** [comment]
What he said^
