### ISSUE TITLE
[Fabric 1.16.5] Pendorite and Ametrine horse armor don't show up

### ISSUE THREAD

**Issue by DanEgbert** [CorgiTaco/BYG#333]
**Fabric version:** 0.11.1
**Mods:**
BYG 1.1.6
Fabric API 0.30.3
autoconfig1u 3.3.1
Mod menu 1.16.7

It's relatively self explanatory, I put on either horse armor, and the black and purple texture appears instead. I've tried it with both versions 1.1.4 and 1.1.6, as well as with only byg and fabric api.
![image](https://user-images.githubusercontent.com/32018435/110403290-7a1f4a80-8042-11eb-85f6-d3b98d1ef421.png)

**Comment by Chaotic-Shy** [comment]
Hi, Ive got the same issue in BYG v1.1.7

**Comment by AOCAWOL** [comment]
Issue resolved for 1.18.2
