### ISSUE TITLE
byg:dummy biomes are in my world

### ISSUE THREAD

**Issue by gglobensky** [CorgiTaco/BYG#334]
I am playing in a modpack with the latest version of BYG 1.1.10 with a world generated with Terraforged 0.2.3

Minecraft version 1.16.4 with FML 35.1.36. We play on a home grown server.

When I use F3, I see I have a byg:dummy biome near our town. It does not look like a weird biome but there does not seem to be much hostile mob spawn in there. I built a creeper farm and after an hour of afk, I had absolutely no drop. We have blood moons too and I can clearly see that hostile mobs spawn on the perimeter of the biome, just outside of it. There are horses in the biome though.

![image](https://user-images.githubusercontent.com/43460763/110456247-533f3380-8097-11eb-9029-41602339f234.png)

Mod list here : 

https://pastebin.com/wCM8dECW

**Comment by CorgiTaco** [comment]
If using terraforged, set the weight of it to 0

**Comment by gglobensky** [comment]
I get that, but is it normal that this biome seems to not be able to spawn any hostile mobs?

Thank you for the awesome mod btw.

**Comment by CorgiTaco** [comment]
that's normal
