### ISSUE TITLE
BYG stones cannot be mined with modded pickaxes

### ISSUE THREAD

**Issue by shouxd** [CorgiTaco/BYG#338]
If you mine Soapstone for example the block drops nothing with a modded pickaxe. Not even the Pendorite one works.

**Comment by CorgiTaco** [comment]
You didn't give me a mod loader and didn't fill out the template issue that answers basic questions

**Comment by shouxd** [comment]
Sorry! Its happening on latest fabric version. I asked on your discord and someone said: "it's probably that the pickaxes aren't in fabric api's pickaxe tag. I am guessing this because byg's stone blocks uses .breakByTool(FabricToolTags.PICKAXES) which means it is running fabric api's code to determine what pickaxes breaks what"

**Comment by AOCAWOL** [comment]
This issue is resolved because of 1.18.2's vanilla tags :)
