### ISSUE TITLE
Nourish Compatibility

### ISSUE THREAD

**Issue by jimmytrouser** [CorgiTaco/BYG#342]
For some reason I cannot add the fruit and berries from this mod to the nourish CFG files.

This is the cfg:

![nourish byg](https://user-images.githubusercontent.com/7896905/111102223-79574e80-8543-11eb-8d4d-04c72a70d37c.PNG)

Any ideas?

Thanks.

**Comment by CorgiTaco** [comment]
that's a question for them, not us
