### ISSUE TITLE
phyliums, sculk, and nylium wrong on maps

### ISSUE THREAD

**Issue by Redd56** [CorgiTaco/BYG#345]
Fabric: 0.11.3
byg: 1.1.7

nyliums phyliums and sculk all are set to materialColor.STONE
meaning that they show up as the color of stone on maps as apposed to a custom color

Expected: each one to show up as a color close to their in game texture.

**Comment by AOCAWOL** [comment]
fixed

**Comment by Redd56** [comment]
God i forgot this big existed XD
