### ISSUE TITLE
not really a feature but is it supposed to be bulbis phycelium? or was it meant to be bulbis phylium

### ISSUE THREAD

**Issue by Redd56** [CorgiTaco/BYG#347]
the title says it all, just wanted to ask since all the other end ones are phylium but bulbis is listed as phycelium.. kinda confusing but if its as intended fine by me

**Comment by AOCAWOL** [comment]
intended as it is more a Mycelium

**Comment by Redd56** [comment]
Huh, neat. Why didnt i just ask on the discord.....
