### ISSUE TITLE
Crash when loading byg:red_rock_

### ISSUE THREAD

**Issue by Alkiasan** [CorgiTaco/BYG#349]
Whenever I load a specific biome, the game seems to hang indefinitely and generate the crash report below
[crash-2021-03-18_00.30.00-server.txt](https://github.com/CorgiTaco/BYG/files/6160569/crash-2021-03-18_00.30.00-server.txt)

**Comment by gnamly** [comment]
Same here. Server Crashes immediately at generating
https://pastebin.com/iY32HNNf

**Comment by Alkiasan** [comment]
Blame report points towards a village being generated in red_rock_mountains
https://pastebin.com/6eDjWLZD

**Comment by CorgiTaco** [comment]
Fixed in latest
