### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by christomite** [CorgiTaco/BYG#35]
when i load any game i get a crash i assume its a world gen mod but im not sure 
[crash-2020-07-18_16.52.41-server.txt](https://github.com/CorgiTaco/BYG/files/4942727/crash-2020-07-18_16.52.41-server.txt)

**Comment by CorgiTaco** [comment]
Can you please https://hatebin.com/ it please. Im not going to download files

**Comment by christomite** [comment]
im not sure how to use it im sorry https://hatebin.com/zukzajtorc i hope thats right

**Comment by CorgiTaco** [comment]
Im not sure how exactly this Is BYG's issue, looks like a mod is using Mixin in world and it's corrupting fluid blocks?
"at net.minecraft.world.World.func_180501_a(World.java:177) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.stevekung's_lib.json:MixinWorld,pl:mixin:A}"

**Comment by CorgiTaco** [comment]
Doesn't seem to be a byg issue but rather a poorly done mixin. Open this issue again if the issue persists
