### ISSUE TITLE
ControlNether = false does not stop BYG Nether biomes from spawning

### ISSUE THREAD

**Issue by aaronhowser1** [CorgiTaco/BYG#350]
__**API/Modloader**__
Forge

__**Describe the bug**__
I set ControlNether to false then went into the Nether on a new world and it still made BYG biomes

**Expected behavior**
for it to not do that

**Screenshots/Videos**
![image](https://user-images.githubusercontent.com/15698722/111720038-232c2900-882b-11eb-917a-83dc10c272c3.png)

**Comment by CorgiTaco** [comment]
If an existing world follow the instructions provided here: https://wiki.griefed.de/SCP/edit-world

**Comment by CorgiTaco** [comment]
ahhhh i didnt read lmao you said a new world

**Comment by CorgiTaco** [comment]
Yea in this case, it's most likely another mod doing this

**Comment by genericbrain** [comment]
has this been solved ? i want the nether gen to go back to vanilla. do i have to do all that editing every time????

**Comment by CorgiTaco** [comment]
Edit level.dat for existing worlds, use any other nether mod's configs
