### ISSUE TITLE
Lignite cannot be used as fuel

### ISSUE THREAD

**Issue by saltyseadoggo** [CorgiTaco/BYG#352]
__**API/Modloader**__
Fabric

__**Describe the bug**__
Lignite (`byg:lignite`) and lignite block (`byg:lignite_block`) cannot be used as fuel in a furnace. 

__**To Reproduce**__
Start Minecraft with BYG and the Fabric API loaded. Attempt to place either lignite item into a furnace's fuel slot.

**Expected behavior**
Lignite and lignite block would be able to be used as fuel, like vanilla coal, coal block and charcoal, as well as BYG's anthracite.

**Comment by AOCAWOL** [comment]
No longer significant as its being removed
