### ISSUE TITLE
Sythian fungus should not be able to be placed on netherrack

### ISSUE THREAD

**Issue by saltyseadoggo** [CorgiTaco/BYG#353]
__**API/Modloader**__
Fabric

__**Describe the bug**__
Sythian fungus can be placed on netherrack. Vanilla fungi cannot be placed on netherrack.

__**To Reproduce**__
Start Minecraft with BYG loaded.
Start a new world in Creative mode.
Place netherrack.
Attempt to place crimson and warped fungi onto the netherrack. It doesn't work by vanilla design.
Attempt to place sythian fungus onto netherrack. It does work.

**Expected behavior**
Sythian fungus would not be able to be placed onto netherrack. It should only be placeable on nyliums, mycelium and podzol, like vanilla fungus.

**Comment by saltyseadoggo** [comment]
Also applies to embur wart, but I'm not sure if it's supposed to be like the fungi, or if it's its own thing.

**Comment by AOCAWOL** [comment]
fixed
