### ISSUE TITLE
Sythian fungus makes the wrong placing and breaking sounds

### ISSUE THREAD

**Issue by saltyseadoggo** [CorgiTaco/BYG#354]
__**API/Modloader**__
Fabric

__**Describe the bug**__
When the player places or breaks sythian fungus, instead of making the vanilla fungus placing and breaking sounds, it makes grass placing and breaking sounds.

__**To Reproduce**__
Start Minecraft with BYG loaded.
Create a new world in Creative mode.
Place any nylium type, mycelium or podzol.
Place either crimson or warped fungus onto the block. Note the unique placing sound.
Break the fungus. Note the unique breaking sound.
Place sythian fungus onto the block. Note the grass placing sound instead of the fungus placing sound.
Break the sythian fungus. Note the grass breaking sound instead of the fungus breaking sound.

**Expected behavior**
Sythian fungus would use crimson/warped fungus placing and breaking sounds.

**Comment by AOCAWOL** [comment]
fixed
