### ISSUE TITLE
Bulbis phycelium favours the shovel instead of the pickaxe

### ISSUE THREAD

**Issue by saltyseadoggo** [CorgiTaco/BYG#356]
__**API/Modloader**__
Fabric

__**Describe the bug**__
Bulbis phycelium's effective tool is the shovel, instead of the pickaxe, despite its End stone appearance and the behaviour of Ivis, Nightshade and Shulkren phylium.

__**To Reproduce**__
- Place a row of five or so bulbis phycelium.
- Obtain any shovel and pickaxe of the same tier.
- Enter survival mode.
- Dig some bulbis phycelium with the pickaxe. Note the mining speed.
- Dig some bulbis phycelium with the shovel. Note the faster mining speed.

**Expected behavior**
Bulbis phycelium's effective tool would be the pickaxe, as it is mostly made of End stone, whose effective tool is the pickaxe, and this would match the behaviour of ivis, nightshade and shulkren phylium.

**Comment by CorgiTaco** [comment]
Fixed
