### ISSUE TITLE
Bulbis phycelium makes nylium placing/breaking sounds, should be stone

### ISSUE THREAD

**Issue by saltyseadoggo** [CorgiTaco/BYG#357]
__**API/Modloader**__
Fabric

__**Describe the bug**__
Bulbis phycelium makes nylium placing and breaking sounds. It should make stone placing and breaking sounds, as it is made mostly of End stone, which makes those sounds, and it would also match the sounds of ivis, nightshade and shulkren phylium.

__**To Reproduce**__
- Place and break bulbis phycelium. Note the sounds.

**Expected behavior**
Bulbis phycelium would make stone placing and breaking sounds to match end stone and ivis, nightshade and shulkren phycelium.

**Comment by AOCAWOL** [comment]
fixed
