### ISSUE TITLE
1.16.5 BYG forge terraforge crash

### ISSUE THREAD

**Issue by MrKashew** [CorgiTaco/BYG#358]
[Log here](https://gist.github.com/MrKashew/97b7ae26d25ef4021a521d9981097860)

**Comment by brisingraerowing** [comment]
This happens without Terraforged as well. Identical crash.

**Comment by PoweredByPot** [comment]
I am also running into this issue when pre-generating chunks on ATM6 with some custom add-ins.

It keeps referencing the byg:red_rock

**Comment by brisingraerowing** [comment]
I disabled the Red Rock Mountains in the config as a workaround.

**Comment by MrKashew** [comment]
Seems there's a reference to "byg:red_rock_" with an underscore at the end, may be a typo?

**Comment by CorgiTaco** [comment]
Patched in latest
