### ISSUE TITLE
Ancient debris isn´t generated in Byg biomes

### ISSUE THREAD

**Issue by Kaloneun** [CorgiTaco/BYG#36]
fix it pls

**Comment by Linguardium** [comment]
fix on fabric suggestion: calling DefaultBiomeFeatures.addNetherMineables or just DefaultBiomeFeatures.addAncientDebris if only ancient debris is desired

**Comment by CorgiTaco** [comment]
Should be fixed later today

**Comment by CorgiTaco** [comment]
Fixed:
Fabric: https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go-fabric/files/3009929

Forge: https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go/files/3009912
