### ISSUE TITLE
The game loads up fine but crashes!

### ISSUE THREAD

**Issue by BluePlayz1** [CorgiTaco/BYG#361]
Crash Log

Mod File: byg-1.1.14.jar
	Failure message: Oh The Biomes You'll Go (byg) encountered an error during the common_setup event phase
		java.lang.NullPointerException: null
	Mod Version: 1.1.14
	Mod Issue URL: https://github.com/CorgiTaco/BYG/issues
	Exception message: java.lang.NullPointerException

**Comment by CorgiTaco** [comment]
reset your configs
