### ISSUE TITLE
Separate Config Files By Dimension (& Main, Sub Biomes)

### ISSUE THREAD

**Issue by HappyCuppy** [CorgiTaco/BYG#363]
Would you be willing to separate the config files by dimensions and main and sub-biomes for each dimension?

It's not really related to a **current** problem, but it from my experience as a software developer it could be a problem in the future, especially the more biomes that'll be added, and it's just for general comfort and ease of use. It's matter of modularization with all the problems it could have to solve - that's for later, and general pros - that's for both later and for now.

What I'd like is for the mod to use the following dimensional config hierarchy:
- `worldgen.config`
    - `overworld-biomes.config`
        - `overworld-sub-biomes.config`
    - `nether-biomes.config`
        - `nether-sub-biomes.config`
    - `end-biomes.config`
        - `end-sub-biomes.config`  

The current alternative is already implemented in the mod itself - the Nether and End biomes are configured in `worldgen.config` (according to you from a recen YouTube comment (I can link to it if it matters), as far as I understand), but like I said, I think my feature request would improve over it.

It'd also be useful to have a GUI for it, maybe even in-game, in the spirit of WorldEdit. I'd be happy to help with a PWA GUI, depending on the technology stack.

**Comment by CorgiTaco** [comment]
Sure. But when i get the nether stuff done

**Comment by HappyCuppy** [comment]
Hi, any updates on this?

**Comment by K0-RR** [comment]
Should probably be reposted to https://github.com/AOCAWOL/BYG-1

**Comment by CorgiTaco** [comment]
Going to close this as the format of config files has vastly changed
