### ISSUE TITLE
[Feature Request] Change to use standardized pluralized tags

### ISSUE THREAD

**Issue by Trikzon** [CorgiTaco/BYG#367]
**Is your feature request related to a problem? Please describe.**

I am adding my mod's blocks to tags and while looking at [Fabric's tag list](https://www.fabricmc.net/wiki/tutorial:tags), which includes byg's tags, I noticed that there are duplicates and inconsistencies because of byg.

For example, there is a `c:workbench` and a `c:workbenches` tag. The pluralized version matches vanilla's standard.

**Describe the solution you'd like**

Rename all byg tags to match the pluralized standard.

**Describe alternatives you've considered**

Create new byg tags that match the pluralized standard and include the old tags in them. That way you won't break any modpacks or configurations relying on the old names, but can switch to the new tags in 1.17.

**Additional context**

I also noticed that you use the tag `forge:workbench`. I have been informed by KnightMiner, the TiCon dev, that `forge:workbenches` is the standard that they will be using for TiCon recipes. I recommend you switch your forge tags to meet the standard too.

**Comment by Trikzon** [comment]
I would be happy to do the work and make a pull request for you if you want. Let me know what solution is best for the project.

**Comment by CorgiTaco** [comment]
This change will be done in 1.17, not 1.16
