### ISSUE TITLE
Tree Fertilizer from Create doesnt work on BYG saplings

### ISSUE THREAD

**Issue by Gowcu** [CorgiTaco/BYG#368]
**Before filling out this issue: **
**1. We only support the latest version of BYG on for Minor Bugs.**
**2. Please test BYG on its own to confirm whether or not this is a mod conflict.**

Says it in the title, I am playing on the Explorico mod pack and am going to post this on both mod's githubs. I am unable to use the Tree Fertlizer from Create on the "oh the biomes you'll go" saplings.

create-mc1.16.3_v0.3e.jar
byg-1.1.10.jar
forge-36.0.21

__**API/Modloader**__
forge-36.0.21

__**Describe the bug**__
Tree Fertilizer that forces a tree's growth in spite of growth conditions wont work at all on BYG saplings

__**To Reproduce**__
using Create Tree Fertilizer on BYG saplings

**Expected behavior**
the saplings should grow

**Screenshots/Videos**
If applicable, add screenshots/video to help explain your problem.

**Additional context**

**Logs**
Use: https://paste.ee/ and paste the links. if log is huge please upload those
Please provide:
Crashlog - 
Debug.log - 
Latest.log -

**Comment by CorgiTaco** [comment]
Not sure how this our issue if bonemeal works on our saplings. So for that reason, I'm closing this.
