### ISSUE TITLE
[1.16.5] Server Starting Event debug message shown in log

### ISSUE THREAD

**Issue by MarioSMB** [CorgiTaco/BYG#370]
__**Mod conflict? If so, please clarify which mod is conflicting!**__

__**API/Modloader**__
Forge

__**Describe the bug**__
During startup, the following message will be shown in the log:  
`[Server thread/INFO] [corgiaoc.byg.BYG/]: BYG: "Server Starting" Event Complete!`  
This seems like a debug message that should not be shown in the regular log, as it is redundant with the regular "Done" message printed by the server.

__**To Reproduce**__

**Expected behavior**

**Screenshots/Videos**

**Additional context**
Other mods tend to print some form of startup message further obscuring the log, I'll be addressing them next ;)

**Logs**

**Comment by CorgiTaco** [comment]
This is a logger relevant to us and any crash reports that may occur as it lets us know or anyone else know if our event managed to fire/finish. So we're keeping it
