### ISSUE TITLE
Can't launch - common_setup event phase

### ISSUE THREAD

**Issue by Mogily** [CorgiTaco/BYG#371]
**Before filling out this issue: **
**1. For major bugs, we only support BYG's latest version on a per Minecraft version basis(i.e latest for 1.15 is 1.0 while latest for 1.16 is 1.1).**
**2. Please test BYG on its own to confirm whether or not this is a mod conflict**
I tried this, still same error

![byg](https://user-images.githubusercontent.com/81725163/113233134-d4f13e00-929e-11eb-8280-0e6ad1f1c12b.png)

__**API/Modloader**__
Forge/Fabric?
Forge
__**Describe the bug**__
What is the bug? Where/How does it occur? etc.
Nomatter what I try, new versions of forge, old ones, no mods, with mods, I get this error
__**To Reproduce**__
Please provide step by step instructions

**Expected behavior**

**Screenshots/Videos**
If applicable, add screenshots/video to help explain your problem.
https://gyazo.com/0d0a72ee6ab465cfe8c60604f5b0adbe

**Additional context**
I tried searching places but couldnt find any solutions
**Logs**
Use: https://paste.ee/ and paste the links. if log is huge please upload those
Please provide:
Crashlog - 
[byglatest.txt](https://github.com/CorgiTaco/BYG/files/6240486/byglatest.txt)
[byglogs.txt](https://github.com/CorgiTaco/BYG/files/6240487/byglogs.txt)

Debug.log - 
Latest.log - 

**Heap Dumps**
*If performance, please provide a heap dump/some sort of profile of your game(I recommend: https://visualvm.github.io/download.html)*
Heap Dump/Profile -

**Comment by AkaiKubi** [comment]
I am having the same problem pls fix it
[crash-2021-04-01_10.02.28-fml.txt](https://github.com/CorgiTaco/BYG/files/6243766/crash-2021-04-01_10.02.28-fml.txt)

**Comment by LowlandFool** [comment]
Im having the same issue

**Comment by CorgiTaco** [comment]
Reset your configs
