### ISSUE TITLE
Tall crimson roots should work like tall grass

### ISSUE THREAD

**Issue by saltyseadoggo** [CorgiTaco/BYG#375]
**Is your feature request related to a problem? Please describe.**
Tall crimson roots do not behave like vanilla tall grass or ferns: they drop themselves instead of two of their smaller form, and they cannot be created by using bone meal on the smaller form, which makes then non-renewable as a side effect: players have to go out and gather large quantities of them if they want them for a build.

**Describe the solution you'd like**
- Tall crimson roots should be created when a player or dispenser uses bone meal on vanilla crimson roots.
- Tall crimson roots should drop two vanilla crimson roots when broken, instead of one tall crimson roots.

**Additional context**
The desired behaviours are patterned off of vanilla tall grass and tall ferns, with the shears breaking requirement removed to match vanilla crimson roots.

**Comment by saltyseadoggo** [comment]
This issue half-applies to Embur roots: they can be bonemealed into tall embur roots, but the tall embur roots drop themselves instead of two small embur roots. This makes both blocks non-renewable, since tall embur roots cannot be used as a catalyst to duplicate embur roots like vanilla tall grass/ferns.

**Comment by AOCAWOL** [comment]
Closing this as its a bit out-dated and these issues have been adressed
