### ISSUE TITLE
Some incorrect plants drop wheat seeds

### ISSUE THREAD

**Issue by saltyseadoggo** [CorgiTaco/BYG#376]
__**API/Modloader**__
Fabric

__**Describe the bug**__
The following plants drop wheat seeds, when I don't believe that they should for the reasons below:
- Scorched grass
- Ether grass
- Ether bush
- Water silk

__**To Reproduce**__
- Inspect the loot tables for those four blocks under `data/byg/loot_tables/blocks`.

**Expected behavior**
I don't believe these four plants should drop wheat seeds for the following reasons:
- Scorched grass is scorched and dead, and is also native to the Nether, where few overworld plants live. The seeds are also useless in a dimension where there is no dirt or water for them to grow.
- Likewise, the ether grass and bush are native to the alien realm of the End, where no overworld plants live.
- Water silk is not grass, and is an entirely different plant.
However, I do not have your creative vision, so I respect that you may want them to drop wheat seeds for reasons I do not know.

**Comment by AOCAWOL** [comment]
fixed
