### ISSUE TITLE
Glowstone/therium lamp makes shroomlight sounds

### ISSUE THREAD

**Issue by saltyseadoggo** [CorgiTaco/BYG#377]
__**API/Modloader**__
Fabric

__**Describe the bug**__
The glowstone lamp makes shroomlight placing and breaking sounds. It should make glass sounds, like the redstone lamp and glowstone, or perhaps lantern sounds, as it is made partly of iron and is constructed similarly to a lantern.

__**To Reproduce**__
- Place and break a glowstone lamp. Note the sounds.

**Expected behavior**
The glowstone lamp would make more sensible placing and breaking sounds, as the shroomlight sounds do not make sense for it.

**Comment by saltyseadoggo** [comment]
This also applies to the therium lamp.

**Comment by AOCAWOL** [comment]
fixed
