### ISSUE TITLE
Glowstone and therium lamps are larger but cheaper than glowstone and therium lanterns

### ISSUE THREAD

**Issue by saltyseadoggo** [CorgiTaco/BYG#379]
__**API/Modloader**__
Fabric

__**Describe the bug**__
Glowstone and therium lanterns are small lanterns, and require eight iron nuggets and one glowstone block/therium, matching vanilla lantern recipes. Glowstone and therium lamps are full blocks, but they cost half as many iron nuggets.

__**To Reproduce**__
- Inspect the recipes for the glowstone and therium lamps and lanterns in REI or the code.

**Expected behavior**
Glowstone and therium lamps would be more expensive than glowstone and therium lanterns due to being larger. I understand that many vanilla recipes aren't very consistent with how many materials go into one block, but this example, where the blocks and recipes are similar, is egregious. Some ideas for replacement recipes are as follows:
- Make therium/glowstone lanterns use glowstone dust/therium shard instead of glowstone block/therium crystal, since they are smaller and would use less of these substances, and then make the lamps use eight iron nuggets.
- Make therium/glowstone lamps use iron ingots instead of iron nuggets, and perhaps make it only require two ingots instead of four..
- Make therium/glowstone lamps use iron bars instead of iron nuggets, and perhaps make it only require two bars instead of four.

**Comment by MarioSMB** [comment]
The 8 nuggets portion of the recipe follows vanilla standards - however, I do agree that a single glowstone dust would make more sense in the glowstone lantern recipe.

**Comment by AOCAWOL** [comment]
fixed
