### ISSUE TITLE
[1.16.1-Forge] Alot of biomes name doesn't have working langs.

### ISSUE THREAD

**Issue by Gbergz** [CorgiTaco/BYG#38]
Title^

Screenshot: 
![image](https://user-images.githubusercontent.com/26634554/87881244-4f6f7b80-c9f8-11ea-9736-8f227bb57468.png)

**Minecraft:** 1.16.1
**Forge:** 32.0.70
**BYG Version:** 1.0.10

**Comment by CorgiTaco** [comment]
Already reported in #34. Expect the fix later today :)

**Comment by Gbergz** [comment]
Should've looked before reporting, was in a hurry.
And that's good to hear! Thanks :)
