### ISSUE TITLE
Minecrafts water is now corals? BeetRoot is Stairs?

### ISSUE THREAD

**Issue by JonnyBonBon** [CorgiTaco/BYG#381]
**Before filling out this issue: **
**1. For major bugs, we only support BYG's latest version on a per Minecraft version basis(i.e latest for 1.15 is 1.0 while latest for 1.16 is 1.1).**
**2. Please test BYG on its own to confirm whether or not this is a mod conflict**

__**Mod conflict? If so, please clarify which mod is conflicting, if not skip this.**__

__**API/Modloader**__
Forge/Fabric?

__**Describe the bug**__
What is the bug? Where/How does it occur? etc.

__**To Reproduce**__
Please provide step by step instructions

**Expected behavior**

**Screenshots/Videos**
If applicable, add screenshots/video to help explain your problem.

**Additional context**

**Logs**
Use: https://paste.ee/ and paste the links. if log is huge please upload those
Please provide:
Crashlog - 
Debug.log - 
Latest.log - 

**Heap Dumps**
*If performance, please provide a heap dump/some sort of profile of your game(I recommend: https://visualvm.github.io/download.html)*
Heap Dump/Profile -

**Comment by ObjektivC** [comment]
Sounds like a registry mismatch.
Your client and server probably have different mods installed, check to see if this is the case.

**Comment by CorgiTaco** [comment]
Most definitely a registry mismatch which is typically caused when the server and client are not using the same version of the mod.
