### ISSUE TITLE
Stone type integration and renewability

### ISSUE THREAD

**Issue by saltyseadoggo** [CorgiTaco/BYG#382]
**Is your feature request related to a problem? Please describe.**
- BYG's stone types are not renewable. Players who need loads of scoria, soapstone, rocky stone, dacite, red rock, mud or peat for builds don't have any options to obtain them other than manually excavating large areas, when they can use stonemason villagers or, hypothetically, Piglin bartering for quartz to obtain large amounts of andesite, diorite and granite.
- Because of the above, if someone were to play a modded skyblock with BYG, none of the stone types are obtainable in such an environment, when the above recipes let andesite, diorite and granite be obtained. (You know, if someone wants to run a biome mod in a world with no visible biomes.)
- BYG's stone types are not integrated into the Mason villager's trades where they would be appropriate. Given that BYG will soon be gaining custom villages, this feels like a missed opportunity.

**Describe the solution you'd like**
- Niche crafting recipes for stone types, mud and peat. Andesite, diorite and granite can all be crafted using combinations of quartz, cobblestone and themselves, making them all obtainable in skyblock playthroughs and farmable in a niche way.
BYG could add the following recipes for its stone types:
  - 2x2 checkerboard of two basalt and two andesite = four scoria (based on the composition of [real world scoria](https://en.wikipedia.org/wiki/Scoria))
  - One stone and one cobblestone, shapeless = two rocky stone (rocky stone is visually between these two)
  - One clay ball and one cobblestone, shapeless = two soapstone (loosely based on the composition of [real world soapstone](https://en.wikipedia.org/wiki/Soapstone), and assuming that soapstone isn't removed in 1.17 as per AOCAWOL's words on the Discord)
  - 2x2 checkerboard of two andesite and two quartz = two dacite (based on the composition of [real world dacite](https://en.wikipedia.org/wiki/Dacite))
  - 2x2 checkerboard of terracotta and cobblestone = four red rock (I don't actually know what type of rock red rock is supposed to be, so I based this on Minecraft pseudo-geology of badlands biomes being made of terracotta. This one could use a better recipe)
  - One water bucket surrounded by eight dirt = eight mud blocks
  - 2x2 checkerboard of two mud blocks and two coal or charcoal = four peat
- Mason villager trades. Mason villagers buy stone, andesite, diorite and granite from players who don't want them, and sell their polished variants.
BYG could add the following mason trades:
   - Apprentice: Mason buys 20 Dacite for one emerald
   - Apprentice: Mason buys 20 Red Rock for one emerald
   - Apprentice: Mason sells 4 Dacite Bricks,Tiles or Pillars for one emerald
   - Apprentice: Mason sells 4 Red Rock Bricks or Chiselled Red Rock Bricks for one emerald
   - Journeyman: Mason buys 16 Scoria Stone for one emerald
   - Journeyman: Mason buys 16 Soapstone for one emerald (barring its removal)
   - Journeyman: Mason sells 4 Scoria Stone Bricks or Scoria Stone Pillars for one emerald
   - Journeyman: Mason sells 4 Polished Soapstone, Soapstone Bricks, Tiles or Pillars for one emerald
These trades are patterned after the vanilla ones, seeing dacite and red rock, in their abundance in their respective biomes, as more like stone, and scoria stone and soapstone as more like andesite, diorite and granite. Masons do not sell vanilla stone bricks, but I included the brick, tile and pillar variants here anyways since BYG's stones cannot be farmed like cobblestone.

**Describe alternatives you've considered**
- Some of BYG's stone types could take the route of vanilla basalt and be able to be generated with some combination of lava, water and/or different blocks, making them renewable, but I have no idea what combinations of blocks and fluids would make sense to create them.

**Comment by AOCAWOL** [comment]
Added the recipes suggested from this post for the suggested blocks in the upcoming update :)
