### ISSUE TITLE
Where are the Embur lilies and wailing vines?

### ISSUE THREAD

**Issue by saltyseadoggo** [CorgiTaco/BYG#383]
__**API/Modloader**__
Fabric

__**Describe the bug**__
Embur lilies and wailing vines seem to be completely missing from the Embur bog and wailing garth, respectively. I can't find either anywhere in their biomes, and Roughly Enough Resources doesn't show them as generating in the Nether, or in any dimension, at all.

__**To Reproduce**__
In a new world, enter the Nether, `/locatebiome` an Embur bog or wailing garth, and look around it for embur lilies or wailing vines, respectively.

**Expected behavior**
Embur lilies would appear dotting the lava sea in the Embur bog biome, while wailing vines would appear somewhere in the Wailing Garth.

**Screenshots/Videos**
Bog of no Lilies
![2021-04-04_16 13 24](https://user-images.githubusercontent.com/69029346/113524035-da7dab00-9560-11eb-8dcb-ea08966fa636.png)
Garth of no Vines
![2021-04-04_16 14 12](https://user-images.githubusercontent.com/69029346/113524040-e23d4f80-9560-11eb-8bff-f22c8d8186b2.png)

**Additional context**
This bug was tested on the latest version of the All of Fabric 3 modpack. I can test it on its own if need be.

**Comment by AOCAWOL** [comment]
blocks that were "removed" which will be finalized in 1.17
