### ISSUE TITLE
Embur gel vines cannot be placed onto the ends of other Embur gel vines

### ISSUE THREAD

**Issue by saltyseadoggo** [CorgiTaco/BYG#384]
__**API/Modloader**__
Fabric

__**Describe the bug**__
Embur gel vines cannot be placed onto the ends of other Embur gel vines to manually build longer vines. This is possible with vanilla crimson vines and BYG's weeping roots and lament vines.

__**To Reproduce**__
- Place an embur gel block.
- Place an embur gel vine onto the bottom of it.
- Attempt to place an embur gel vine onto the bottom of the previous vine. This does not work.

**Expected behavior**
Embur gel vines could be placed under other Embur gel vines like vanilla weeping vines and BYG's weeping roots and lament vines.

**Comment by AOCAWOL** [comment]
fixed in next update
