### ISSUE TITLE
One of the Embur wart structures is partly cut off

### ISSUE THREAD

**Issue by saltyseadoggo** [CorgiTaco/BYG#386]
__**API/Modloader**__
Fabric

__**Describe the bug**__
The huge Embur wart structure in the screenshot below, which is one of the ones that can grow from saplings, has one of its caps missing some blocks on one side, as if it was cut off when it was saved.

__**To Reproduce**__
- Bonemeal Embur warts until you grow the huge Embur wart that looks like the one below and inspect it from the angle shown in the picture.

**Expected behavior**
This huge Embur wart structure would not be partly cut off, and would instead look like the one in the second picture.

**Screenshots/Videos**
The offending huge Embur wart structure. See the cut off cap in the lower left.
![2021-04-04_19 22 16](https://user-images.githubusercontent.com/69029346/113530740-9b108800-957b-11eb-982e-a2c4a6b24cd8.png)

The same structure with the missing blocks replaced by the player.
![2021-04-04_19 22 31](https://user-images.githubusercontent.com/69029346/113530760-ab286780-957b-11eb-83cb-a84fe7196761.png)

**Comment by AOCAWOL** [comment]
fixed in next update
