### ISSUE TITLE
Crash on Launch

### ISSUE THREAD

**Issue by LilligantIsBest** [CorgiTaco/BYG#388]
**Before filling out this issue: **
**1. For major bugs, we only support BYG's latest version on a per Minecraft version basis(i.e latest for 1.15 is 1.0 while latest for 1.16 is 1.1).**

**2. Please test BYG on its own to confirm whether or not this is a mod conflict**
Is not

__**API/Modloader**__
Forge

__**Describe the bug**__
Game does not launch after Mojang Screen, crashes.

__**To Reproduce**__
Unsure. The mod works fine for me, but for my friend who I'm submitting this for can only launch the game and is met immediately with a crash.

**Expected behavior**
The game to boot up normally as it did for me and several of my other friends.

**Screenshots/Videos**
_

**Additional context**
This is being submitted for a friend, as I'm helping him fix this issue. There is approximately 10 other people not including me that I know who are using the mod issue free, but this one case I'm not so sure of what's causing it to crash. We are using other mods, but when I instructed my friend to take out the other mods and just launch with BYG, it still crashed. The logs pasted are the most recent logs without any of the other mods installed.

**Logs**
Use: https://paste.ee/ and paste the links. if log is huge please upload those
Please provide:
Crashlog - https://paste.ee/p/FmzdF
Debug.log - https://paste.ee/p/CcRwt
Latest.log - https://paste.ee/p/wwHXs

**Comment by CorgiTaco** [comment]
oof, it seems the logs have expired, Im going to make an assumption and say to reset the BYG configs and let them regenerate
