### ISSUE TITLE
Vanilla Lectern recipe missing?

### ISSUE THREAD

**Issue by xevira** [CorgiTaco/BYG#389]
__**Mod conflict? If so, please clarify which mod is conflicting!**__
Only mods I see conflicting is between BYG and Fabric?  I'm not entirely sure where the breakdown is, but since I can only see BYG woods used in the recipe shown in REI.  Looking at the recipe inside the repo, I see c:bookshelves and don't know where that is populated exactly.

__**API/Modloader**__
BYG: v1.1.6
Fabric 0.11.3 + Fabric API 0.30.0

__**Describe the bug**__
Only BYG wooden slabs and bookshelves are allowed when crafting lecterns.

__**To Reproduce**__
Try to craft the Lectern using vanilla recipe (vanilla wooden slabs and vanilla bookshelf)

**Expected behavior**
I expect to be able to craft the lectern using vanilla materials.

**Screenshots/Videos**
N/A

**Additional context**
N/A

**Logs**
No logs

**Comment by xevira** [comment]
I found the issue:

BYG/src/main/resources/data/byg/tags/blocks/bookshelves.json is missing the "replace": false entry.  It is only a problem in the Fabric version.  The Forge tag list for bookshelves is correct.

**Comment by CorgiTaco** [comment]
Itll be fixed everything is moved over to fabric

**Comment by Redd56** [comment]
issue is back in fabric, im making a datapack in jar form to temp fix it for myself

**Comment by Redd56** [comment]
issues is because of [this](https://github.com/AOCAWOL/BYG/blob/1.18.X/Common/src/main/resources/data/c/tags/items/bookshelves.json), the vanilla bookshelf is missing

**Comment by Marshallcoolman** [comment]
still having this issue, was this ever fixed?

@Redd56 did you ever make that datapack fix?

**Comment by Redd56** [comment]
nope never did
