### ISSUE TITLE
Server lagging behind

### ISSUE THREAD

**Issue by Stanlijane** [CorgiTaco/BYG#391]
Server lags behind and "can't keep up" with only BYG installed. Had to take out every other mod we had and start from scratch, deleted world, and the server is still lagging with only BYG installed. The problem started with serious lag in the nether, making it unplayable. Overworld was okay, some lag from time to time but manageable.
Forge version: 1.16.5 - 36.1.0
BYG version: 1.1.14

7.04 20:12:37 [Server] Server thread/INFO [minecraft/DedicatedServer]: Stanlijane joined the game
07.04 20:12:40 [Server] Server thread/WARN [minecraft/MinecraftServer]: Can't keep up! Is the server overloaded? Running 2086ms or 41 ticks behind
07.04 20:12:54 [Server] Server thread/INFO [minecraft/DedicatedServer]: [Stanlijane: Set own game mode to Creative Mode]
07.04 20:13:13 [Server] Server thread/INFO [minecraft/DedicatedServer]: Stanlijane has made the advancement [Ice Bucket Challenge]
07.04 20:13:38 [Server] Server thread/INFO [minecraft/DedicatedServer]: Stanlijane has made the advancement [We Need to Go Deeper]
07.04 20:13:38 [Server] Server thread/WARN [minecraft/MinecraftServer]: Can't keep up! Is the server overloaded? Running 2686ms or 53 ticks behind
07.04 20:14:04 [Server] Server thread/WARN [minecraft/MinecraftServer]: Can't keep up! Is the server overloaded? Running 3822ms or 76 ticks behind
07.04 20:14:04 [Server] Server thread/WARN [minecraft/ServerPlayNetHandler]: Stanlijane moved too quickly! 0.383094137904763,0.0,-10.21758062377721

**Comment by CorgiTaco** [comment]
Any news in regards to this? 

What you've given me isnt much i can work with. You should probably install VisualVM(https://visualvm.github.io/download.html) and send both a sampler snapshot and heap dump

**Comment by MarioSMB** [comment]
You may also have some luck with the Spark mod (see Files for the Forge version): https://www.curseforge.com/minecraft/mc-mods/spark

It has extensive documentation that will allow you to perform a server profile and even heap dumps. The server profile will help track down early signs of the cause, it would help if you could post a link to it here.

**Comment by CorgiTaco** [comment]
Closing this since no response was received. Comment back here if the issue persists
