### ISSUE TITLE
[Suggestion] Make buried treasure generate in "beach" type sub-biome

### ISSUE THREAD

**Issue by Koji-KAWAHARA** [CorgiTaco/BYG#392]
**Is your feature request related to a problem? Please describe.**
In a BYG world, buried treasures and treasure maps in shipwrecks don't generate 
in "beach" type subbiomes in BYG(white beach, rainbow beach etc). 
This makes buried treasure pretty rare, hence makes it harder to find a heart of the sea.

**Describe the solution you'd like**
To make buried treasures and shipwrecks be generated in beach subbiomes in BYG.

**Describe alternatives you've considered**
If this behavior is an intended one, leave it as is.

**Additional context**
I checked that these structures don't generate in BYG beachs by running 
command "/locate buried_treasure" in single biome worlds. (Forge36.1.0, byg1.1.14)

Vanilla Minecraft generates buried treasures in beach and snowy beach (ie, beach type biomes with sand),
so I think following the way is a reasonable idea.

**Comment by Oasis951** [comment]
Still can't find the treasure on Rainbow Beaches. I'm playing 1.18.2 on Fabric 0.14.19. The mod version is 1.4.7
