### ISSUE TITLE
Several ores are missing tags

### ISSUE THREAD

**Issue by aaronhowser1** [CorgiTaco/BYG#393]
__**API/Modloader**__
Forge

__**Describe the bug**__
Some, like Ametrine, have block tags but no item tags. Some have none at all.

**Comment by MarioSMB** [comment]
It seems this may only partially be fixed now... I'll address this in another pull request if preferred.

**Comment by CorgiTaco** [comment]
@MarioSMB  Yeah if you could, that'd be appreciated
