### ISSUE TITLE
Bone meal is consumed erroneously when used on netherrack next to Embur nylium

### ISSUE THREAD

**Issue by saltyseadoggo** [CorgiTaco/BYG#398]
__**API/Modloader**__
Fabric

__**Describe the bug**__
When bone meal is used on netherrack that is next to Embur nylium, it is consumed, and green bone meal particles are created, despite nothing actually happening as a result.

__**To Reproduce**__
- Use bone meal on netherrack that is adjacent to Embur nylium in survival mode. The bone meal is consumed and green particles appear, but nothing happens.
- If you do this in creative mode, the use item hand animation still plays and the particles are still created, but the bone meal is not consumed, as the player is in creative mode.

**Expected behavior**
The player should not be able to use bone meal on netherrack next to Embur nylium whatsoever, much like when netherrack is next to any block that isn't crimson or warped nylium in vanilla, as Embur nylium is rooted in blue netherrack, a different block entirely, and, thus, it cannot spread to regular netherrack- unless you want to introduce "Overgrown Embur Netherrack," that is.

**Comment by CorgiTaco** [comment]
This is due to the NYLIUM tag, so this is unfortunately something we cant fix
