### ISSUE TITLE
[Fabric 1.16.x] BYG prevents trees from growing on vanilla dirt

### ISSUE THREAD

**Issue by coderbot16** [CorgiTaco/BYG#4]
Since [FeatureMixin](https://github.com/CorgiTaco/BYG/blob/Fabric-1.16.X/src/main/java/voronoiaoc/byg/mixin/common/FeatureMixin.java#L15) *always* sets the return value, this means that when `block == Blocks.DIRT`, isSoil will end up returning false. Instead, It should check if the block is an instance of a BYG dirt block, and if so, set the return value to true. This avoids inadvertently changing an existing return value of `true` to `false`.

```diff
@Mixin(Feature.class)
public class FeatureMixin {
    @Inject(at = @At("RETURN"), method = "isSoil(Lnet/minecraft/block/Block;)Z", cancellable = true)
    private static void isDirt(Block block, CallbackInfoReturnable<Boolean> cir) {
-       cir.setReturnValue(block == BYGBlockList.GLOWCELIUM || block == BYGBlockList.PEAT ||
+       if (block == BYGBlockList.GLOWCELIUM || block == BYGBlockList.PEAT ||
               block == BYGBlockList.MEADOW_GRASSBLOCK || block == BYGBlockList.OVERGROWN_DACITE || block == BYGBlockList.OVERGROWN_STONE ||
               block == BYGBlockList.PODZOL_DACITE || block == BYGBlockList.OVERGROWN_NETHERRACK || block == BYGBlockList.SYTHIAN_NYLIUM ||
-               block == BYGBlockList.IVIS_PHYLIUM);
+               block == BYGBlockList.IVIS_PHYLIUM) {
+               cir.setReturnValue(true);
+       }
    }
}
```

The effect of this is most notable with Terrestria installed:

![image](https://user-images.githubusercontent.com/22420959/86036071-2445cd80-b9f2-11ea-90a9-ef0625fa2b8f.png)

**Comment by coderbot16** [comment]
The same issue exists with https://github.com/CorgiTaco/BYG/blob/Fabric-1.16.X/src/main/java/voronoiaoc/byg/mixin/common/PlantBlockMixin.java

**Comment by CorgiTaco** [comment]
Haha yes my noob self has fixed/patched this :P https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go-fabric/files/2992185

**Comment by CorgiTaco** [comment]
https://i.imgur.com/bH6Buks.png

**Comment by coderbot16** [comment]
Ah good, thanks! I noticed that you committed the fix mere minutes before I finished my issue report :)
