### ISSUE TITLE
Vermillion sculk, sculk growth and sculk tendrils are non-renewable

### ISSUE THREAD

**Issue by saltyseadoggo** [CorgiTaco/BYG#400]
__**API/Modloader**__
Fabric

__**Describe the bug**__
Vermillion sculk, sculk growth and sculk tendrils are non-renewable: vermillion sculk cannot spread onto ether stone in any way, and the growths and tendrils cannot be created in any way either. This means that...
- You cannot 'heal' the bald spots in the terrain of viscal isles biomes created by removing the dead ether trees.
- If you want a lot of any of these blocks to build with, you need to destroy large swaths of viscal isles biomes to get them, and they are thus gone forever.

__**To Reproduce**__
Not really applicable.

**Expected behavior**
I don't really know what to expect for these blocks, as we will not know how vanilla sculk is going to grow and be obtained until it is added in the 1.17 snapshot cycle, so you can very well just leave this issue be until then. You could make using bone meal on ether stone that is next to vermillion sculk turn it into more vermillion sculk, like nyliums in the Nether, and then make using bone meal on vermillion sculk grow the tendrils and growths on nearby vermillion sculk blocks, like grass and nyliums, but it may be smarter to wait and see how vanilla sculk works.

**Comment by AOCAWOL** [comment]
fixed in next update
