### ISSUE TITLE
Tall ether grass should work like tall grass

### ISSUE THREAD

**Issue by saltyseadoggo** [CorgiTaco/BYG#403]
**Is your feature request related to a problem? Please describe.**
Tall ether grass does not behave like vanilla tall grass or ferns: it drops itself instead of two small ether grass, and it cannot be created by using bone meal on small ether grass. In addition, it doesn't require shears to yield items like vanilla tall grass or ferns.

**Describe the solution you'd like**
- Tall ether grass should be created when a player or dispenser uses bone meal on ether grass.
- Tall ether grass should drop two ether grass when broken with shears, instead of one tall ether grass when broken with anything.

**Additional context**
The desired behaviours are patterned off of vanilla tall grass and tall ferns.
This prose is largely copied from #375, as this is a similar, but not identical, issue.

**Comment by AOCAWOL** [comment]
fixed in next update
