### ISSUE TITLE
Bulbis oddities cannot be planted on bulbis phycelium

### ISSUE THREAD

**Issue by saltyseadoggo** [CorgiTaco/BYG#406]
__**API/Modloader**__
Fabric

__**Describe the bug**__
Bulbis oddities cannot be planted on bulbis phycelium.

__**To Reproduce**__
Attempt to place either bulbis oddity on bulbis phycelium.

**Expected behavior**
Bulbis oddities would be able to be placed on bulbis phycelium, as that is what they grow on in the bulbis gardens biomes.

**Comment by CorgiTaco** [comment]
Seems to work on forge, after these fixes are pushed to fabric and the issue persists, comment back here
