### ISSUE TITLE
LOGS DON'T BURN INTO CHARCOAL

### ISSUE THREAD

**Issue by CorgiTaco** [CorgiTaco/BYG#41]
AOCAWOL AHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH

**Comment by gamma-delta** [comment]
Hello,

I am also having this problem with Cika logs. It appears they're not part of the `minecraft:logs` tag. Other woods are, though (like Aspen.)
