### ISSUE TITLE
Make End 'grasses' renewable

### ISSUE THREAD

**Issue by MuteTiefling** [CorgiTaco/BYG#414]
**Is your feature request related to a problem? Please describe.**
Many ground cover blocks are non-renewable. It would be nice if they can be obtained in survival more reliably by allowing them to spread to other blocks. 

**Describe the solution you'd like**
The various 'grass' types in the end ought spread to the appropriate nearby block type as vanilla grass spreads to dirt.

Vermillion Skulk onto Ether Stone (byg)
Nightshade Phylium onto Ender Stone (byg)
Shulkren Phylium onto Ender Stone (byg)
Bulbis Phycelium onto Ender Stone (byg)
Ether Phylium onto Ether Soil (byg)
Imparius Phylium onto Ender Stone (byg)

Similarly the actual 'tall grass' type blocks should sprout when these things are bonemealed. Like Ether Grass from Ether Phylium.

**Describe alternatives you've considered**
We'll be making recipes for this stuff to grow in various machines, but base mod support for bonemeal would be fancy :D

**Additional context**
https://github.com/NillerMedDild/Enigmatica6/issues/1960

**Comment by MarioSMB** [comment]
Vanilla has a mechanic where nylium is spread by bonemealing it, that mechanic could be reused for these and the Nether groundcovers added by the mod.
