### ISSUE TITLE
Empty or none existent pool - Server timing out attempting to build village

### ISSUE THREAD

**Issue by arrisar** [CorgiTaco/BYG#415]
__**Mod conflict? If so, please clarify which mod is conflicting, if not skip this.**__
There is a likelihood this is a conflict, but all signs and blame point to BYG. I've attempted to locate any more info, but no luck so far. 

__**API/Modloader**__
Forge 36.1.4

__**Describe the bug**__
When loading new chunks in a modpack I'm developing, very rarely the logs get suddenly spammed with `Empty or none existent pool` and the server grinds to a halt, all entities freezing, and players timing out.

__**To Reproduce**__
The only reliable reproduction I have for this issue to teleport to specific coords in my world on my dedicated server.
If necessary I can supply coords along with either the world as a whole or the seed and modpack in hopes to reproduce.

**Expected behaviour**
Chunks to generate as normal. Or at least a crash/more descriptive indicator as to the cause.

**Screenshots/Videos**
This is the relevant part of the latest.log, at the very end.
![image](https://user-images.githubusercontent.com/846173/114324619-782f3680-9b6e-11eb-8bbb-df1653d5ee5d.png)

**Additional context**

**Logs**
Latest.log - https://gist.github.com/arrisar/4b9d7039106bc2f986ad976791b4e2fa

**Heap Dumps**
Heap Dump/Profile - Investigating recommended profiler

**Comment by TelepathicGrunt** [comment]
Missing villages pieces tends to not deadlock a server. I suspect something else is in play here. Can you share your modpack as is so I can run VisualVM on it and get a thread dump when it deadlocks to find the real cause?

**Comment by arrisar** [comment]
Sure thing. Thanks for stepping up to the plate!

Pack: https://www.curseforge.com/minecraft/modpacks/dragonheart-cpe
Seed: -3075103054395883639
Rough coords: -6887 104 -3447

**Comment by TelepathicGrunt** [comment]
I made a new world, went to the location, and I am not able to recreate the deadlock. I flown even more to a ton of other villages and travels a bit and no luck. Doesnt seem to be a worldgen issue

**Comment by TelepathicGrunt** [comment]
Upon trying to make a new world, the get deadlocked at 100% and a threaddump showed FastLeafDecay as the cause
https://paste.ee/p/9jiq3

@arrisar try removing that mod. Does it solve your deadlock?

**Comment by arrisar** [comment]
Thanks, I'll give that a try and report back.

**Comment by arrisar** [comment]
No luck, unfortunately. I'm going to try and find a way to reliably reproduce the issue.

So far the only proper thing I can verbally affirm is that `none existent pool` log spam has shown up with the same problem, but elsewhere.

I'm reasonably assuming that something I introduced in version 1.4.0 is causing a conflict, changelog below. I'll work my way through the list hopefully find the real issue wherever it is.

```
### Added
- 'Dustrial Decor
- AttributeFix
- Areas
- ChunkNoGoByeBye
- Cycle Paintings
- Dungeon Crawl
- Dungeons Plus
- Entity Culling
- Guide-API Village and Pillage
- Hand Over Your Items
- Inspirations
- KubeJS
- Login Shield
- Pandoras Creatures
- Performant
- PMMO Bridge
- Rain Be Gone Ritual
- Repurposed Structures
- Smooth Boot
- Stack Refill
- Supplementaries
- The Endergetic Expansion
- The Outer End
- Village Bell Recipe
- Villager Names

### Changed
- Various spawn rate config changes

### Fixed
- Nearest waystone and cosmetic armor icon collision
```

**Comment by arrisar** [comment]
Closing, with further testing, this absolutely is not a BYG issue, though I'm yet to find the real cause. Thanks again for the assistance!
