### ISSUE TITLE
[Suggestion] Chests for the wood types (Quark compatibility)

### ISSUE THREAD

**Issue by MarioSMB** [CorgiTaco/BYG#417]
**Is your feature request related to a problem? Please describe.**
There has been a long-standing incompatibility between this mod and Quark where BYG woods can't be used to make chests, and it would be preferable to not need user-facing workarounds for such popular mods and such a visible gameplay-affecting issue.

**Describe the solution you'd like**
It would be nice to see custom chests added for all the modded wood types added by this mod when Quark is present.

**Describe alternatives you've considered**
The alternative is of course waiting for Quark to fix their chest recipe override to account for mods that don't add chest types, or for them to manually exclude this mod, neither of which is guaranteed or ideal.

**Additional context**
I have recently attempted to resolve this myself with a data pack, but would still love to see the unique chest types that could be made with the woods this mod has to offer.

**Comment by saltyseadoggo** [comment]
On the fabric side, this can be seen as Charm compatibility, and would also make BYG's wood types have a closer list of offerings to the wood types in Better End, which is compatible with BYG, Better Nether, etc. You get the idea. Plus, colourful chests are just super lovely to have, especially when the vanilla one looks kinda gunky and doesn't go with many builds.

**Comment by CorgiTaco** [comment]
We will not be adding datapackable data explicitly for specific mods. Feel free to use this: https://www.curseforge.com/minecraft/mc-mods/drp-global-datapack

**Comment by CorgiTaco** [comment]
Let me clarify, since i closed these issues in a rapid fire manner. When Vanilla adds chests for their different woods, we'll add them!

**Comment by MarioSMB** [comment]
Arguably this is a Quark issue at present anyway, as they have chosen to break any mod that doesn't add its own chest types for them. Here's hoping a solution presents itself in the future.
