### ISSUE TITLE
[Suggestion] Allow magmatic stone to be crafted with TConstruct installed

### ISSUE THREAD

**Issue by MarioSMB** [CorgiTaco/BYG#418]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Magmatic stone is a rather nice block to build with, it would be nice to have a way to renew it. Tinker's Construct adds the perfect mechanism for doing so; casting molten magma cream into cobblestone in a casting basin could produce magmatic stone, like this: https://i.imgur.com/ni6EYgF.png

**Describe alternatives you've considered**
If a vanilla recipe is preferred, perhaps 4 magma cream around a block of cobblestone would work?

**Additional context**

**Comment by CorgiTaco** [comment]
We will not be adding datapackable data explicitly for specific mods. Feel free to use this: https://www.curseforge.com/minecraft/mc-mods/drp-global-datapack

**Comment by MarioSMB** [comment]
This is not something Tinker's Construct will handle, they have explicitly stated they will not be adding recipes for other mods' items. Please reconsider, as this would be a nice addition to your mod, and users should not be expected to create data packs to solve cross-compatibility issues.

**Comment by CorgiTaco** [comment]
As i said in another issue: 
> It is not our duty to explicitly support another mod's system. I am not being paid to implement this, It takes time to implement compatibility for other mods. Of course I may change my stance on this in the future, if say I personally use this mod. But I quite frankly at this time do not play this game

**Comment by MarioSMB** [comment]
As a FOSS developer you have no duty beyond those which you choose, however this is a project used by millions of people and Tinker's Construct is among the most used mods of all time. If anything can be done to improve compatibility and the experience between the two, it would be appreciated by many.  

That said, this is a rather minor addition, and it's understandable if the team chooses not to include it.

**Comment by CorgiTaco** [comment]
Since you're consistent, feel free to make a PR with the datapack info, and I'll be happy to merge it.

**Comment by MarioSMB** [comment]
Sure, I'll see what I can do.
