### ISSUE TITLE
Overworld has become the nether (not very cool) 

### ISSUE THREAD

**Issue by mightyjaffa12** [CorgiTaco/BYG#423]
Version
1.16.5  

Modloader
Forge 1.16.5

**Describe the bug**
All the Biome IDs have changed around, I am unsure of what happened or how to fix it but what should be a normal overworld biome has now turned into the Subzero Hypogeal biome from the nether, ghasts have begun spawning above my house, which is very unpleasant :(

__**To Reproduce**__
Please provide step by step instructions
Unsure of how to reproduce, I have upped the spawn weight for biomes in the configs but as far as I'm aware there is nowhere to change BYG IDs so no clue how it happened 
 
**Screenshot
![Base Profile Screenshot 2021 04 19 - 12 46 01 60](https://user-images.githubusercontent.com/48683279/115232810-0c6d4080-a10f-11eb-8247-c7044a39fc6a.png)

**Comment by Yourname942** [comment]
Did you remove any mods that add biomes/dimensions? Biome shifting happens to me as well. It can also happen if a mod changes their ids during an update. I highly recommend https://www.curseforge.com/minecraft/mc-mods/biome-id-fixer

**Comment by CorgiTaco** [comment]
what @Yourname942 said. This is a vanilla issue, upvote the biome shuffling bug: https://bugs.mojang.com/browse/MC-202036
