### ISSUE TITLE
[Suggestion] Mossy and blue netherrack brick variants with Quark installed

### ISSUE THREAD

**Issue by MarioSMB** [CorgiTaco/BYG#425]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Quark allows turning 1 cobblestone brick block and 3 netherrack into netherrack bricks, it would be cool to see this functionality extended to mossy netherrack and blue netherrack when it is installed

**Describe alternatives you've considered**

**Additional context**

**Comment by CorgiTaco** [comment]
We will not be adding datapackable data explicitly for specific mods. Feel free to use this: https://www.curseforge.com/minecraft/mc-mods/drp-global-datapack

**Comment by MarioSMB** [comment]
This is not something that can be made via data packs or by Quark itself, as it requires a new item to be included.

**Comment by CorgiTaco** [comment]
ah derp. Anyways, nah
