### ISSUE TITLE
[Suggestion] Meadow dirt to grass recipe (Create compat)

### ISSUE THREAD

**Issue by MarioSMB** [CorgiTaco/BYG#426]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Create allows spouting water onto dirt to turn it into a grass block, it would be nice to see this functionality extended to meadow dirt/grass.

**Describe alternatives you've considered**

**Additional context**

**Comment by CorgiTaco** [comment]
We will not be adding datapackable data explicitly for specific mods. Feel free to use this: https://www.curseforge.com/minecraft/mc-mods/drp-global-datapack

**Comment by MarioSMB** [comment]
That's a shame, I'll see if Create can handle this on their end.

P.S. Data packs are incredibly powerful, but they are not a supplement for developer negligence. Please don't suggest them as a primary means of solving compatibility issues.

**Comment by CorgiTaco** [comment]
It is not our duty to explicitly support another mod's system. I am not being paid to implement this, so it is not "a supplement for developer negligence". It takes time to implement compatibility for other mods. Of course I may change my stance on this in the future, if say I personally use this mod. But I quite frankly at this time do not play this game anyways

**Comment by MarioSMB** [comment]
Understandably, none of us are paid to work here, and cross-compatibility is a luxury a lot of people are getting used to in Forge's ecosystem. It also takes a lot of time to learn the tools and patch these cross-compatibilities as a user, something I have already done but have also chosen to take the time to make reports for each suggested change on the appropriate channels.  

If this is something that may possibly be revisited in the future, then I'd ask that you please leave it open until such a time, with just the workaround illustrated above for those who would like to fill in the blanks in the meantime.

**Comment by CorgiTaco** [comment]
Since I like your consistency, feel free to make a PR with the datapack info, and I'll be happy to merge it.
