### ISSUE TITLE
[Suggestion] Meadow path pressing (Create compat)

### ISSUE THREAD

**Issue by MarioSMB** [CorgiTaco/BYG#427]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Create allows dirt and grass blocks to be pressed to produce dirt paths, it would be nice to see this functionality extended to meadow dirt/grass.

**Describe alternatives you've considered**

**Additional context**

**Comment by CorgiTaco** [comment]
Not sure how to do this...?

**Comment by wchen1990** [comment]
Here's the relevant code Create uses to do this: https://github.com/Creators-of-Create/Create/blob/mc1.16/dev/src/main/java/com/simibubi/create/foundation/data/recipe/PressingRecipeGen.java

It looks like this is just the datapack recipe generation though. So this _might_ just be a simple datapack recipe.

------------

Edit: https://github.com/Creators-of-Create/Create/blob/mc1.16/dev/src/generated/resources/data/create/recipes/pressing/path.json

Yea, it's just a datapack recipe.

**Comment by CorgiTaco** [comment]
We will not be adding datapackable data explicitly for specific mods. Feel free to use this: https://www.curseforge.com/minecraft/mc-mods/drp-global-datapack

**Comment by MarioSMB** [comment]
That's a shame. I'll reach out to the Create team to see if cross-compatibility is something they can handle on their side.
