### ISSUE TITLE
Every single cave, stronghold, ravine, even the nether is filled with water and tube coral fan. any reason?

### ISSUE THREAD

**Issue by gamerdude7847458747580** [CorgiTaco/BYG#429]
**Before filling out this issue: **
**1. For major bugs, we only support BYG's latest version on a per Minecraft version basis(i.e latest for 1.15 is 1.0 while latest for 1.16 is 1.1).**
**2. Please test BYG on its own to confirm whether or not this is a mod conflict**

__**Mod conflict? If so, please clarify which mod is conflicting, if not skip this.**__

__**API/Modloader**__
Forge/Fabric?

__**Describe the bug**__
What is the bug? Where/How does it occur? etc.

__**To Reproduce**__
Please provide step by step instructions

**Expected behavior**

**Screenshots/Videos**
If applicable, add screenshots/video to help explain your problem.

**Additional context**

**Logs**
Use: https://paste.ee/ and paste the links. if log is huge please upload those
Please provide:
Crashlog - 
Debug.log - 
Latest.log - 

**Heap Dumps**
*If performance, please provide a heap dump/some sort of profile of your game(I recommend: https://visualvm.github.io/download.html)*
Heap Dump/Profile -

**Comment by CorgiTaco** [comment]
We don't mess with these structures so that's not our issue. And you failed to follow the instructions provided in this issue, therefore I am closing this

**Comment by gamerdude7847458747580** [comment]
Your so epic and amazing, thank you almighty Corgi Taco for making great mods!

**Comment by CorgiTaco** [comment]
Maybe you should provide details?

**Comment by CorgiTaco** [comment]
Anyways, sounds like registry mismatch

**Comment by K0-RR** [comment]
😂 I must say this edit is epic.

Anyway that was probably a forge user.
