### ISSUE TITLE
[Suggestion] Add a config option to make the World Type 'BYG' by default when creating new world.

### ISSUE THREAD

**Issue by Gbergz** [CorgiTaco/BYG#43]
Title^

For Forge Version:
https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go

Would be a nice feature!
- Gbergz

**Comment by CorgiTaco** [comment]
As much as I like it, the world type will be removed once the forge PR is merged for modded biomes. So I don't exactly see myself investing energy into it :/

**Comment by Gbergz** [comment]
Ah gotcha, no problem! :)

PR merge meaning that if i choose the standard worldtype BYG biomes will be in the world by default?

**Comment by CorgiTaco** [comment]
Yeah but this won't be until 1.16.2 most likely

**Comment by Gbergz** [comment]
> Yeah but this won't be until 1.16.2 most likely

Alright! Well thanks for the answers. ;)
