### ISSUE TITLE
Biomes Not Generating Properly

### ISSUE THREAD

**Issue by Yourname942** [CorgiTaco/BYG#430]
**Before filling out this issue: **
**1. For major bugs, we only support BYG's latest version on a per Minecraft version basis(i.e latest for 1.15 is 1.0 while latest for 1.16 is 1.1).**
**2. Please test BYG on its own to confirm whether or not this is a mod conflict**
Minecraft 1.16.5
Forge 36.1.2
Terraforged 0.2.10
Biomes You Go 1.2

__**Mod conflict? If so, please clarify which mod is conflicting, if not skip this.**__
potentially caused by Terraforged?

__**API/Modloader**__
Forge

__**Describe the bug**__
These biomes are not properly generating:
Polluted lake, sierra range, red rock lowlands, and fresh water lake

__**To Reproduce**__

1. Create a Single player world (you don't have to actually select create)
2. select terraforged generation type
3. Select Beautiful
4. Change some sliders
5. Save as default (and as a preset)
6. copy/paste the preset, located in client's config/terraforged/preset, and paste into the server config/terraforged/preset
7. set server properties' level-type=terraforged:terraforged
8. launch server
9. launch client
10. join world
11. fly around in creative

**Expected behavior**
I expect these biomes to generate properly with no extreme and odd distortions.

**Screenshots/Videos**
If applicable, add screenshots/video to help explain your problem.
![2021-04-30_14 37 38](https://user-images.githubusercontent.com/58750222/116761232-103d7480-a9e5-11eb-84ce-4ac9b8e1c121.jpg)

**Additional context**
I have Biomes O Plenty, Autumnity, Environmental, and several other mods which add biomes to the overworld.

Modlist: https://gist.github.com/Yourname942/6812b9b08c375e020d19fa32a6187c6f

**Logs**
Debug.log - https://gist.github.com/Yourname942/032fcc050f2d6d28659125698641f144
Latest.log - https://gist.github.com/Yourname942/10b7d745acc9e2a82778f7666fde0b1e

**Comment by TelepathicGrunt** [comment]
does the issue go away when you remove TerraForged? TerraForged takes complete control over where and how biomes spawn so I doubt BYG is the issue here. Rather it seems to be an issue with how TerraForged determines where the biomes spawn and how they are shaped

**Comment by CorgiTaco** [comment]
This is a problem to be resolved by Terraforged, their inability to respect vanilla objects basically makes this impossible for us to fix ourselves, sorry. This is entirely their fault and they openly show that here: https://github.com/TerraForged/tracker/issues/103
