### ISSUE TITLE
Potential mod compatibility issue with Endless Oceans

### ISSUE THREAD

**Issue by BrekiTomasson** [CorgiTaco/BYG#433]
Fabric 1.16.5, using BYG v1.1.7 and Endless Oceans v1.0.1.

During worldgen, I spot this warning in the log:

`Method overwrite conflict for isOcean in endlessoceans.mixins.json:server.MixinShoreLayer, previously written by corgiaoc.byg.mixin.common.world.layers.MixinShoreLayer. Skipping method.`

Looking at the code in BYG (i cannot find the source for Endless Oceans), this seems like a fairly simple method that just returns if the biome in question is one of Vanilla Minecraft's ocean biomes.

**Comment by CorgiTaco** [comment]
The law of mixin states: "Never use @Overwrite"
We clearly use an @Inject here: https://github.com/CorgiTaco/BYG/blob/Fabric-1.16.X/src/main/java/corgiaoc/byg/mixin/common/world/layers/MixinShoreLayer.java#L30-L44


So this is their fault not BYG's.
