### ISSUE TITLE
byg-1.2.1 not creating Dynamic Trees

### ISSUE THREAD

**Issue by Zygus42** [CorgiTaco/BYG#434]
From the update notes I thought this update added Dynamic Trees support ?  Doesn't seem to be the case.  See screenshot:
![2021-05-04_08 25 48](https://user-images.githubusercontent.com/20757445/116948658-95a97900-acb2-11eb-8232-4b7525fdcc15.png)

**Comment by CorgiTaco** [comment]
The update note was in relation to internal changes i made for Dynamic Trees BYG. If you wanna follow progress on the byg addon, you may see it here: https://github.com/supermassimo/DynamicTrees-BYG/projects/1
