### ISSUE TITLE
Boric Campfire

### ISSUE THREAD

**Issue by GiGDDragon** [CorgiTaco/BYG#435]
If the Vertical slabs version of this campfire is placed it crashes the server until the block is edited back out.
Also if you place a campfire on top of another campfire you have the same results.

**Comment by CorgiTaco** [comment]
idk what you mean by the "Vertical slabs version of this campfire" but that sounds like something to take up with them, not us.

**Comment by enduum** [comment]
This sounds like your issue: https://github.com/CJMinecraft01/DoubleSlabs/issues/182
DoubleSlabs has had a lot of issues with campfires recently, but it just updated so give the newest version a shot :)
