### ISSUE TITLE
Two tall flowers can't be planted.

### ISSUE THREAD

**Issue by ZeekDaGeek** [CorgiTaco/BYG#437]
**Before filling out this issue: **

__**Mod conflict? If so, please clarify which mod is conflicting!**__
No

__**API/Modloader**__
Forge

__**Describe the bug**__
Planting two tall flowers, for example `Azalea`, on blocks with the <tag:blocks:byg:ground_azalea> tag doesn't work. They instantly pop off.

__**To Reproduce**__
Plant on dirt, grass, overgrown stone or anything with the <tag:blocks:byg:ground_azalea> tag.

**Expected behavior**
Plant stays planted.

**Comment by CorgiTaco** [comment]
What version of BYG?

**Comment by ZeekDaGeek** [comment]
Sorry, the template has said not to submit a ticket unless it was the current version so I didn't include it.

v1.2.3, the problem only started after the dirt change the last 2 days.

**Comment by AOCAWOL** [comment]
Fixed
