### ISSUE TITLE
Fabric - Leaves do not have a favourite tool

### ISSUE THREAD

**Issue by Linguardium** [CorgiTaco/BYG#44]
Vanilla uses Hoe as a favourite tool of the leaf block.
Adding breakByTool(FabricToolTags.HOE,0) to the block settings _should_ fix it

**Comment by CorgiTaco** [comment]
Fixed here: https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go-fabric/files/3009929
