### ISSUE TITLE
Whaling Grass = Wailing Grass?

### ISSUE THREAD

**Issue by ribbonleaves** [CorgiTaco/BYG#442]
I assume the "whaling" in the whaling grass and vines from the Wailing Garth biome is supposed to be "wailing" to match the biome name, not the cetacean? Obviously, this is a tiny issue, but it's something I've noticed and thought I would point out.

BYG is a fantastic mod, by the way! Love it so much!

**Comment by YaBoiChips** [comment]
fixed in forge branch
