### ISSUE TITLE
[Suggestion] Coloured sand smelts into regular glass

### ISSUE THREAD

**Issue by MarioSMB** [CorgiTaco/BYG#443]
**Is your feature request related to a problem? Please describe.**
Mostly a consistency issue - red sand can be smelted into regular glass, and that makes sense; coloured glass is made by staining the glass with dyes, different types of sand have no effect on this process

**Describe the solution you'd like**
I believe it would make more sense to have black, blue, pink, white and purple sand smelt into regular glass rather than stained glass, fitting in line with vanilla recipes and with other mods that add coloured sand (BoP)

**Describe alternatives you've considered**

**Additional context**

**Comment by CorgiTaco** [comment]
We personally prefer it this way as it makes more sense to us
