### ISSUE TITLE
Placing block above meadow grass path turns it into dirt

### ISSUE THREAD

**Issue by saltyseadoggo** [CorgiTaco/BYG#446]
__**API/Modloader**__
Fabric

__**Describe the bug**__
Placing a solid block above a meadow grass path block turns it into vanilla dirt instead of meadow dirt.

__**To Reproduce**__
Place any solid block above a meadow grass path.

**Expected behavior**
Placing a solid block above a meadow grass path would turn it into meadow dirt.

**Screenshots/Videos**
![2021-05-07_15 39 24](https://user-images.githubusercontent.com/69029346/117515207-690f8e80-af4a-11eb-83f6-c349dc3186f9.png)

**Comment by CorgiTaco** [comment]
Fixed on latest forge. Changes to be on fabric soon

**Comment by AOCAWOL** [comment]
Fixed in latest BYG
