### ISSUE TITLE
Double tall flowers yield wrong number of dyes

### ISSUE THREAD

**Issue by saltyseadoggo** [CorgiTaco/BYG#450]
__**API/Modloader**__
Fabric

__**Describe the bug**__
All of BYG's two block flowers yield one dye instead of two in crafting:
- Tall Allium
- Tall Pink Allium
- Azalea
- Delphinium
- Foxglove

__**To Reproduce**__
View the dye recipes for these flowers in REI or the code.

**Expected behavior**
The dye recipes that use BYG's two block flowers would yield two dyes instead of one to match vanilla two block flowers.

**Comment by saltyseadoggo** [comment]
Also applies to
- Japanese Orchid

**Comment by AOCAWOL** [comment]
fixed in upcoming update
