### ISSUE TITLE
Farming mechanic: Grow giant flowers, craft giant petal blocks into dyes

### ISSUE THREAD

**Issue by saltyseadoggo** [CorgiTaco/BYG#452]
**Is your feature request related to a problem? Please describe.**
The giant petal blocks are completely useless outside of decoration at the moment. This and the stems being useless as well makes the giant flowers, while pretty, have no real function.

**Describe the solution you'd like**
You could let the giant flowers be grown somehow, and then let the petal blocks be crafted into dyes. Dye farms centered around the flowers would be more like tree farms, requiring TNT dispensing mechanisms and item collection funnels and such.
I think four or so dyes per petal could be a good yield. If the flowers are created with bone meal, then having them yield too much dye would completely demolish vanilla flower farms in viability: a few bone meal for over a stack or more of dye versus mush worse exchange rates on vanilla dye farms. Having them use the upcoming 'pollen fertilizer' to grow to give them an additional cost would be better in my opinion
If/when pollen gets its unique use, these farms would have a useful unique output in pollen as well, so their use would be incentivized outside of vanilla flower farms.

**Comment by CorgiTaco** [comment]
Since Giant flowers have been removed in the current version, I'm going to close this.
