### ISSUE TITLE
Add sythian stalk and scaffolding to `#minecraft:piglin_loved`

### ISSUE THREAD

**Issue by saltyseadoggo** [CorgiTaco/BYG#453]
**Is your feature request related to a problem? Please describe.**
Piglins couldn't care less about sythian stalks, despite them being infused with gold, nor sythian scaffolding, which is made of the former.

**Describe the solution you'd like**
- Sythian stalk and sythian scaffolding should be added to `#minecraft:piglin_loved` item tag

**Describe alternatives you've considered**
- The gold infusion in sythian stalks AOCAWOL described may not be 'pure' enough for Piglins to recognise it, in which case these tag additions wouldn't be correct.
- Sythian scaffolding could be added to `#minecraft:guarded_by_piglins` block tag so that Piglins get mad when it is broken, but they don't care about numerous smaller gold blocks, such as weighted pressure plates in vanilla; only the ores, gilded blackstone, block of gold and block of raw gold. They pick up some blocks that they don't protect, like the pressure plate, so having the scaffold be in the item tag still makes sense.
- Is there gold in other sythian blocks, and would the Piglins recognise them? That is for you two to determine.

**Comment by AOCAWOL** [comment]
added sythian stalk to piglin love & piglin guarded in next update. Scaffolding will not be added simply because it is something the player would want to use for aiding in building and being terrorized 24/7 for using it would be a bit annoying.
