### ISSUE TITLE
Redundant Tags

### ISSUE THREAD

**Issue by Dradon7** [CorgiTaco/BYG#457]
Minecraft 1.16.5
BYG 1.2.7

__**API/Modloader**__
Forge

__**Describe the bug**__
In the forge/tags data folder, there is the sand tag and the sand folder with colored sand tags inside, both of which are consistent with forge. However, there is also duplicate colored sand jsons outside of the sand folder. This happens for both item tags and block tags.

**Expected behavior**
There should be general sand tag, with every kind of sand, and a sand folder, with tags for each kind of sand.

**Additional context**
I'd do a PR, but I'm not sure if deleting those files would break anything

**Logs**
No logs, its just code cleanup, no crashes or anything.

**Comment by CorgiTaco** [comment]
hmm

**Comment by CorgiTaco** [comment]
These were added in a compatibility PR. But anyways, regardless if they're redundant or not, they're fine sitting there.
