### ISSUE TITLE
Possibly Redundent Village NBT files?

### ISSUE THREAD

**Issue by Dradon7** [CorgiTaco/BYG#459]
__**API/Modloader**__
BYG 1.2.7
Forge

**Is your feature request related to a problem? Please describe.**
In the data folder, the folder byg/structures/village/common seems redundant. As far as I can tell, similar NBT files for iron golems, animals, and well bottoms already exist in minecraft.

**Describe the solution you'd like**
 - You should use vanilla village/common nbt files. I can't tell if you're already using vanilla NBTs in villages, but if you aren't, you should definitely switch over. It really just makes mod compat and pack design easier.

**Describe alternatives you've considered**
 - Doing nothing. This is a pretty minor formatting issue, but it'll save people work down the line. The main reason to do nothing is if I'm completely wrong about these files being redundant. Maybe vanilla formatted theirs weird, and now its inconvenient to use their iron golem file in BYG villages. I don't know.

EDIT: spelling

**Comment by CorgiTaco** [comment]
I will remove these from the commit history soon
