### ISSUE TITLE
[1.16.1-Forge] Server World won't load when Mekanism is installed. (Stuck at Preparing Spawn Area spam.)

### ISSUE THREAD

**Issue by Gbergz** [CorgiTaco/BYG#46]
Title^

Weird issue I know but i've tried everything, either I remove BYG, then it loads. Or I keep BYG & Remove Mekanism then it will load again. If both are present server gets stuck at 'Preparing Spawn Area any%' and spam like this:
![image](https://user-images.githubusercontent.com/26634554/88231563-bef19f00-cc74-11ea-9d25-d7ad165f24e4.png)

And if it does load after like 2 years of preparing spawn area, it will crash because of ``A single server tick took 60.00 seconds (should be max 0.05)`` & ``Considering it to be crashed, server will forcibly shutdown.``

If you want I can provide the world that it's happening on and you can dig deeper. This is on a clean Server Instance by the way with only BYG, Mixin Bootstrap & Mekanism.

**BYG Version:** 1.0.12
**Mixin Bootstrap Version:** 1.0.3
**Mekanism Version:** 10.0.3.426

**Comment by CorgiTaco** [comment]
Forge version?

**Comment by CorgiTaco** [comment]
Seems to be similar to #15

**Comment by Gbergz** [comment]
**Forge Version:** 32.0.71

**Comment by Gbergz** [comment]
Also If i boots it crashes like before, but it spams this before the crash happens. ``Can't keep up! Is the server overloaded? Running 20305ms or 406 ticks behind``

**Comment by CorgiTaco** [comment]
Remove bootstrap and move to latest forge

**Comment by Gbergz** [comment]
Same issues are present with Latest Forge & the removal of Bootstrap.

**Comment by CorgiTaco** [comment]
Try a vanilla worldtype

**Comment by Gbergz** [comment]
Same issue sadly.

**Comment by CorgiTaco** [comment]
Remove BYG and check. Could be Mekanism itself

**Comment by Gbergz** [comment]
Issue is gone when BYG is removed, but then again. If I remove Mekanism and leave BYG the issue is gone aswell.

It's only happening when the 2 mods are together.

**Comment by Gbergz** [comment]
Standalone its fine.

**Comment by CorgiTaco** [comment]
Hrmmm. Copy paste the entirity of both your latest & debug logs https://hatebin.com/

**Comment by Gbergz** [comment]
**Latest Log:** https://hatebin.com/ggrllwvisn
**Latest Debug Log:** https://hatebin.com/kkosswcqfl

**Comment by Gbergz** [comment]
that didn't post the whole logs..
hm.. sec

**Comment by Gbergz** [comment]
[debug.log](https://github.com/CorgiTaco/BYG/files/4962962/debug.log)
[latest.log](https://github.com/CorgiTaco/BYG/files/4962964/latest.log)
 There!

**Comment by CorgiTaco** [comment]
Can you post the log with just the 2 mods? It's difficult reading 100k+ lines

**Comment by Gbergz** [comment]
[latest.log](https://github.com/CorgiTaco/BYG/files/4962985/latest.log)
[debug.log](https://github.com/CorgiTaco/BYG/files/4962986/debug.log)

there you go

**Comment by allaryin** [comment]
I've been running a 1.16 server for 6 weeks now with BYG and Mekanism (+tools and generator submods) both installed. Default configs. I don't think there's any inherent conflict between these mods.

Have been successful with latest versions of the mods against forge versions x.66, x.85, and x.106. I know that forge has introduced a lot of breaking changes during this time - for example, x.67 changed loading and mods had to be recompiled for it. I remember having a problem when upgrading Mekanism post x.424 against the forge version du jour.

**Comment by CorgiTaco** [comment]
Closing this as the issue seems to be resolved and 1.16.1 is no longer supported
