### ISSUE TITLE
Variant16x Mixin Conflict.

### ISSUE THREAD

**Issue by MickeyMouseYT** [CorgiTaco/BYG#460]
[latest.log](https://github.com/CorgiTaco/BYG/files/6445688/latest.log)
[debug.log](https://github.com/CorgiTaco/BYG/files/6445689/debug.log)

**Comment by CorgiTaco** [comment]
Looks like a mod conflict, somehow...

**Comment by Sajius** [comment]
![Image showing game, forge, and mod versions](https://user-images.githubusercontent.com/27030684/117575206-d5a39e00-b0ae-11eb-82de-f69d8c4f654f.png)

[latest.log](https://github.com/CorgiTaco/BYG/files/6447654/latest.log)
Minecraft: 1.16.5
Forge: forge-36.1.0
BYG: byg-1.2.7.jar
Variant16x: Variant16x-1.16.5-v0.21.4_beta_pre2.jar

I was having the same issue and narrowed it down to BYG + Variant16x seems to get me a crash every time.
[Variant16x](https://www.curseforge.com/minecraft/mc-mods/variant16x)

Note: This does not include the BYG patch mod for Variant16x. It still breaks with the patch mod, but also breaks with only the base mod.

BYG might break with other mods too, but I thought a narrower case might help.

**Comment by Sajius** [comment]
Update: Seems to be breaking specifically on the byg-1.2.6 update, not the 1.2.7

**Comment by CorgiTaco** [comment]
This is due to them using an @Overwrite which is the most dangerous thing you can do for mod compatibility. If it hasn't been done already, I'ma make an issue report to them to use an injection.

**Comment by CorgiTaco** [comment]
Reported: https://www.curseforge.com/minecraft/mc-mods/variant16x/issues/9

**Comment by MickeyMouseYT** [comment]
Thank you !
👍

**Comment by BKthousand** [comment]
Hello, I'm the author of Variant16x. Wanted to let you know here as well that a new build is up on CurseForge, fixing the mixin conflict. Sorry for the issue!
