### ISSUE TITLE
BYG config is unsafe and trash

### ISSUE THREAD

**Issue by CorgiTaco** [CorgiTaco/BYG#464]
Title

**Comment by zinerith** [comment]
I agree but your bug report is so vague and unhelpful it will inevitably be ignored and deleted. 

Please learn how to submit a proper bug report with literally any details at all. (I'm submitting a bug report on this issue but with details so the developers know how to fix the problem)

**Comment by CorgiTaco** [comment]
@zinerith but... but..... I am the developer

**Comment by zinerith** [comment]
Ok, that's pretty funny. I don't know how I didn't notice. Well, I put my suggestions in another ticket anyway. (to be fair, if you weren't the developer, my comment would have been well founded)

**Comment by zinerith** [comment]
@CorgiTaco sorry for the... mix up. It's been a long day

**Comment by bessiq** [comment]
why

**Comment by CorgiTaco** [comment]
bc like... it crashes all the time lmao

**Comment by bessiq** [comment]
idk it seems fine on forge, but it's one of the few configs i don't mess with a lot tbf lol. byg is just already SO GOOD out the box. 😍

**Comment by CorgiTaco** [comment]
Somewhat reimplemented in latest

**Comment by CorgiTaco** [comment]
Should be resolved in latest.
