### ISSUE TITLE
Ametrine not generating?

### ISSUE THREAD

**Issue by Honigmilch** [CorgiTaco/BYG#465]
__**Mod conflict?**__
No.

__**API/Modloader**__
Forge

__**Describe the bug**__
The is no ametrine ore generating in Guiana Shield, Stone Forest or Pointed Stone Forest. I started a fresh world to see if maybe it was one of my other mods coliding with the generation, but even a clean one with just BYG did not generate any. Pendorite ore however works perfectly fine. 

__**To Reproduce**__
Create a new world in 1.16.5 with byg 1.2.7.
Locate one of the 3 provided bioms from the wiki (Guiana Shield, Stone Forest or Pointed Stone Forest)
Try to find ametrine ore bewteen y 53 and y 0.

**Expected behavior**
I expected to find at least 1 vein of the ore per chunk.

**Comment by SpareUranium** [comment]
Check the end it was moved there

**Comment by CorgiTaco** [comment]
What spare said

**Comment by allanonmage** [comment]
So, is the ore an end-only ore now?  The various documentations are mismatched and unclear.
