### ISSUE TITLE
Comments for the blacklist/whitelist sections of "byg-world.json5" are vague and unhelpful for all but modders: Suggestions for much needed improvements

### ISSUE THREAD

**Issue by zinerith** [CorgiTaco/BYG#466]
**Is your feature request related to a problem? Please describe.**
As it stands, any attempt to whitelist or blacklist biomes in the End or Nether without searching through the source code and/or trial and error will cause a "malformed json exception" and crash the game when that dimension is loaded. 

**Describe the solution you'd like**
It is necessary to include the internal biome names "byg:[biome]" in the comments or at least somewhere in the config for the end and for the nether biome generation sections.

**Describe alternatives you've considered**
At least include the internal biome names "byg:[biome]" on the byg wiki. They are currently missing from all sources except the source code (which non coders wouldn't know how to look though. I know Java, though I haven't modded, and even I had to search and double back for 10 minutes to find it, and then it still took an attempt or two with malformed json exceptions till I got it right.)

**Additional context**
I do datapack development and have a private server that I've been setting up. It was frustrating since there was no help online for any of this, as when searching I only found other people complaining about the lack of documentation for this specific thing.

**Comment by CorgiTaco** [comment]
With Fabric on the backburner til 1.17, this issue has already been resolved on the forge front partially

**Comment by K0-RR** [comment]
> With Fabric on the backburner til 1.17, this issue has already been resolved on the forge front partially

Does this mean there won't be more releases for Fabric 1.16?

**Comment by CorgiTaco** [comment]
@RDKRACZ nope, I'm to overwhelmed with stuff as it stands and porting to fabric is taxing on me tbh. 

I've been focusing on squashing bugs on forge. By 1.17, it'll be much better and such.

**Comment by JT122406** [comment]
1.16 isn't supported
