### ISSUE TITLE
config file: "byg-world.json5" Nether and End biome generation should include option for byg to generate alongside other biomes (at least vanilla, but preferably all modded biomes)

### ISSUE THREAD

**Issue by zinerith** [CorgiTaco/BYG#467]
**Is your feature request related to a problem? Please describe.**
I was setting up this mod for my private server, but we only liked 2 of your Nether biomes and wanted to disable the rest. However, we found that the only options are to have byg control the nether and end dimensions entirely nor not generate in those dimensions at all. 

**Describe the solution you'd like**
Instead of just an option for byg to control each dimension, it should have 2 bools. one for disabling all biomes except byg in that dimension, and one for only inserting the byg biomes into the already existing biome list. 

**Describe alternatives you've considered**
There are none. This should have been a feature to begin with, considering there's a blacklist/whitelist option already. 

**Additional context**
I've only tested the nether generation, and am assuming the end generation will work the same. Additionally, I set "isblacklist" to false, meaning the 2 nether biomes we wanted were in the whitelist. If the other biomes would normally have generated alongside the byg biomes, then it seems that this is instead a bug with the whitelist controlling all biomes for the dimension instead of just the byg biomes as it should be doing.

**Comment by CorgiTaco** [comment]
You're probably using another mod that modifies the end generation, maybe use their config..?

**Comment by zinerith** [comment]
Do you mean the Nether? (from what I was saying in "Additional Context")
The only other mod that I'm using for the nether is Cinderscapes: https://www.curseforge.com/minecraft/mc-mods/cinderscapes and their config only can control their biomes. Vanilla biomes also spawn alongside them, so I know it's possible. Additionally, I tried out betternether (and removed it cause I didn't like the ores) and they all worked fine together. I'm only having this issue with byg Nether generation.

**Comment by CorgiTaco** [comment]
Vanilla biomes work alongside our biomes tho...

**Comment by AOCAWOL** [comment]
Closed without additional info
