### ISSUE TITLE
BYG trees growing through basically everything but dirt/grass (blocks)

### ISSUE THREAD

**Issue by ZoruaBit** [CorgiTaco/BYG#468]
__**API/Modloader**__
Forge/Fabric?
forge

__**Describe the bug**__
What is the bug? Where/How does it occur? etc.
the trees grow through basically everything but dirt. very minor but very annoying as it leaves holes everywhere.

__**To Reproduce**__
Provide step by step instructions
place a palm tree sapling on sand and let it grow. it grows through the sand and sandstone and to the normal stone. i think the byg dirt thing does it too. 
**Expected behavior**
it shouldn't replace the stuff underneath it. i rather have trees with stuff in between them then treese going under the ground.
**Screenshots/Videos**
If applicable, add screenshots/video to help explain your problem.
![image](https://user-images.githubusercontent.com/39221658/117761972-e3137200-b1ed-11eb-8657-7ed7c8b31510.png)

**Additional context**
the screenshot was tooken on a big custom made modpack however I have tested on just the mod alone and I found out it went through everything (I could see) other then dirt/grass)
**Logs**
Use: https://paste.ee/ and paste the links. if log is huge please upload those
Please provide:
Crashlog - n/a
Debug.log - n/a
Latest.log -n/a

**Comment by turtledev1** [comment]
This bug broke all my farms lol. Since the farm breaks all the log, it left my farm destroyed with no floor

**Comment by lincore81** [comment]
(Oak) trees even break the dirt beneath them. I have to remove this otherwise great mod from my pack until this is fixed.

**Comment by CorgiTaco** [comment]
should be fixed in latest
