### ISSUE TITLE
[1.16.1-Forge] Slimes rarely if ever spawn.

### ISSUE THREAD

**Issue by ShiiruGH** [CorgiTaco/BYG#47]
I've only seen slimes spawn in the minecraft:swamp biome and a single slime within a slime farm set up in a slime chunk in a BYG biome. I've waited several hours within various byg swamps and at the slime farm.

Using version 1.0.12 MCV: 1.16.1

**Comment by CorgiTaco** [comment]
I do nothing with slime chunks. This seems to be a matter of luck not a matter of BYG. BYG Swamps will not work either.

**Comment by Linguardium** [comment]
Slimes are hard coded to vanilla SWAMP biome. I dont know if forge offers a way to fix this.

This can be mixed in into SlimeEntity$canSpawn if one desired to change it to use swamp category vs hardcoded biome (or add another check for custom swamp biomes).
