### ISSUE TITLE
Missing item in Recipe for crafting minecraft:gray_dye

### ISSUE THREAD

**Issue by ghost** [CorgiTaco/BYG#470]
**Before filling out this issue: **
**1. We only support the latest version of BYG on for Minor Bugs.**
**2. Please test BYG on its own to confirm whether or not this is a mod conflict.**

__**Mod conflict? If so, please clarify which mod is conflicting!**__
I'll provide with as much as possible, since I have no idea.  (I am using the latest version of kanpeki modpack.)

__**API/Modloader**__
Forge/Fabric?
Fabric
__**Describe the bug**__
What is the bug? Where/How does it occur? etc.
Recipe ID: byg:gray_dye, for some reason there seems to be nothing that requires it.
__**To Reproduce**__
Provide step by step instructions
Crafting anything, a split second it'll show minecraft:gray_dye as the result. (tested on a multiplayer server, and this bug is apparent. Testing on single player with the mod by itself and with the modpack does not show the bug however it still shows the recipe in a singleplayer world with the modpack.)
**Expected behavior**
It'll show the result of minecraft:gray_dye for a split second. 
**Screenshots/Videos**
If applicable, add screenshots/video to help explain your problem.
![2021-05-11_15 00 07](https://user-images.githubusercontent.com/56524051/117870083-a5542f00-b269-11eb-8c69-e0f7f378679c.png)
^ Recipe ID.
https://user-images.githubusercontent.com/56524051/117869753-337be580-b269-11eb-897a-96b0e46e3291.mp4

**Additional context**

**Logs**
Use: https://paste.ee/ and paste the links. if log is huge please upload those
Please provide:
Crashlog - 
Debug.log - https://paste.ee/p/BwPzC
Latest.log - https://paste.ee/p/RGRmQ

**Comment by CorgiTaco** [comment]
uhhhh we dont have a gray dye item...

**Comment by ghost** [comment]
it's just vanilla minecraft gray dye. The ID of the recipe says "BYG:gray_dye" (not an actual item, the recipe ID.)
the recipe crafts "minecraft:gray_dye"
![2021-05-11_15 35 31](https://user-images.githubusercontent.com/56524051/117874085-91f79280-b26e-11eb-9d23-ab118459aa3e.png)

**Comment by MarioSMB** [comment]
This is actually quite strange; there's a tag attached to that recipe named `byg:gray_dye` with no contents. In Forge, this appears as a barrier block (the default fallback for an empty tag).

**Comment by MarioSMB** [comment]
This is fixed in the latest beta release.
