### ISSUE TITLE
Overgrown Blackstone can be spread onto Netherrack

### ISSUE THREAD

**Issue by asdasdasadg** [CorgiTaco/BYG#472]

**Comment by saltyseadoggo** [comment]
This could do with some more information. I listed out the expected behaviours for this under #374:
- Using bone meal on netherrack that is next to overgrown crimson blackstone should turn it into crimson nylium, and
- Using bone meal on blackstone that is next to overgrown crimson blackstone *or* crimson nylium should turn it into overgrown crimson blackstone.

This is based upon the logic that the plant life on both of these blocks is the same, just rooted in two different blocks.

Are you meaning to say that using bone meal on netherrack that is next to overgrown crimson blackstone is turning the netherrack into overgrown crimson blackstone, effectively transmogrifying it into blackstone?

**Comment by asdasdasadg** [comment]
Yes its turning the netherrack into blackstone.

**Comment by CorgiTaco** [comment]
Should be fixed in https://github.com/AOCAWOL/BYG/commit/9353fe84463af813ec563e0806cc7eda46559c82
