### ISSUE TITLE
java.lang.NullPointerException: null during "common_setup event phase

### ISSUE THREAD

**Issue by B3rInnit** [CorgiTaco/BYG#476]
**Before filling out this issue: **
**1. For major bugs, we only support BYG's latest version on a per Minecraft version basis(i.e latest for 1.15 is 1.0 while latest for 1.16 is 1.1).**
**2. Please test BYG on its own to confirm whether or not this is a mod conflict**

__**Mod conflict? If so, please clarify which mod is conflicting, if not skip this.**__

__**API/Modloader**__
Forge

__**Describe the bug**__
When I open the game it doesn't even let me into the main menu. It just gives me a message saying: Oh the biomes you'll go encountered an error during the common_setup event phase. java.lang.NullPointerException:  null

__**To Reproduce**__
1. First I downloaded forge (The version was; 1.16.5-36.1.17). 2. I then downloaded the most recent version of the mod (byg 1.2.7). 3. I started the game with the forge loader version, no other mods, and got the message above.

**Expected behavior**
Well, naturally I expected it to let me get to the menu and start playing. Not just give me a message so I had to close the game.

**Screenshots/Videos**
![2021-05-14_18 22 09](https://user-images.githubusercontent.com/84196143/118299679-57e1f700-b4e1-11eb-9c6f-ba2dfb5987b8.png)

**Additional context**
Well I dunno what else to say. It worked for my friend, and it also works for me when using the fabric version. But I wanted to use more mods from forge and when I tried the forge version of BYG it hit me with that message.

**Logs**
Use: https://paste.ee/ and paste the links. if log is huge please upload those
Please provide:
Crashlog - https://paste.ee/p/XPrlW
Debug.log - It doesn't say debug log anywhere? I need to know where it is. I'm not good with this type of stuff.
Latest.log - https://paste.ee/p/GZHBP

**Heap Dumps**
*If performance, please provide a heap dump/some sort of profile of your game(I recommend: https://visualvm.github.io/download.html)*
Heap Dump/Profile - Well uh, the profile was called: 1.16.5-forge-36.1.17

Please help!

**Comment by CorgiTaco** [comment]
Delete your configs

**Comment by B3rInnit** [comment]
Wait but how do I do that?

**Comment by B3rInnit** [comment]
nvm
