### ISSUE TITLE
Barrels with BYG woods

### ISSUE THREAD

**Issue by akochi** [CorgiTaco/BYG#477]
**Is your feature request related to a problem? Please describe.**
Using BYG with Blockus mod atm, and Blockus add a bunch of barrels with the standard game wood materials (e.g. oak barrel, birch barrel, jungle barrel, ...). It makes BYG woods not able to produce barrels (probably replaces the recipes from tag to item - but that would be fixable easily with a datapack I guess) and BYG woods don't have matching barrels.

**Describe the solution you'd like**
Have barrels matching woods used with BYG woods. Possibly behind and option or an add-on, for those who keep original, non-determined barrels, but have it available for any other person having a mod adding specific ones.

**Describe alternatives you've considered**
No alternative atm.

**Additional context**
Nothing to add atm.

**Comment by CorgiTaco** [comment]
When vanilla adds barrels, we will too. Anyone is free to make an addon, but we personally won't.
