### ISSUE TITLE
[1.15.2-Forge] Missing #BYG WorldType Settings in byg-world-common.toml

### ISSUE THREAD

**Issue by rckymtnrfc** [CorgiTaco/BYG#48]
I've noticed in BYG 1.0.10, the config file byg-world-common.toml, seems to be missing the #BYG WorldType Settings section, so you are unable to turn off vanilla biomes or adjust biomes, sizes.

**Comment by CorgiTaco** [comment]
BYG does not have a worldtype on 1.15. 1.16 is a special case bc forge currently does not have a hook for it. Sorry :/
