### ISSUE TITLE
Crash with Regrowth trying to do something on BYG grass

### ISSUE THREAD

**Issue by Jackiecrazy** [CorgiTaco/BYG#481]
__**Mod conflict? If so, please clarify which mod is conflicting, if not skip this.**__
Regrowth

__**API/Modloader**__
Forge

__**Describe the bug**__
The game will randomly crash. The crash appears to be related to regrowth attempting to retrieve some (null) data about BYG grass blocks. 

__**To Reproduce**__
1. Install Regrowth and BYG
2. Wait in a BYG biome with animals around

**Expected behavior**
The game should not crash.

Logs: https://paste.ee/p/MtQjd

Crossposting from mactso/Regrowth#12.

**Comment by Darkmega18** [comment]
oh! hey I just got this bug also.

Heres a log. https://pastebin.com/rjCkmJwx

**Comment by Lupicus** [comment]
You can see the exception in log file without regrowth by placing down an overgrown stone block and applying bonemeal to it.

**Comment by CorgiTaco** [comment]
Since im late, the log has since expired, please use github gists when pasting the log

**Comment by Darkmega18** [comment]
oh, I had set it to a month. that wasn't pastes fault. I think we had it "fixed" or bypassed from regrowths side :V but they're only bonemealing stone based grass that you use in the Guiana's etc. it causes a crash cause it doesn't know what to do about placing grass or something, cause it's technically a type of stone, or something of the sort.

**Comment by CorgiTaco** [comment]
Fixed by https://github.com/AOCAWOL/BYG/commit/c5cf6123f860615a69cb22ccadf56b92c3f17b59 in 1.18.
