### ISSUE TITLE
No chests for various wood types

### ISSUE THREAD

**Issue by klutzydrummer** [CorgiTaco/BYG#491]
__**API/Modloader**__
Forge

__**Describe the bug**__
No chests for wood types added by the mod

__**To Reproduce**__
Just no recipes for chests

**Expected behavior**
There should be chests

**Additional context**
Living in an Enchanted forest with only enchanted blue and green trees, and I can't make any chests

**Comment by CorgiTaco** [comment]
IF you're using quark they change the chest recipe
