### ISSUE TITLE
Various Warped Coral Fan Inconsistencies

### ISSUE THREAD

**Issue by hugeblank** [CorgiTaco/BYG#493]
__**API/Modloader**__
Fabric 1.16.5

__**Describe the bug**__
1. Warped Coral Fan drops the regular Warped Coral item when broken
2. When naturally generated, the Warped Coral Fans default state is with "waterlogged" set to true

**Expected behavior**
Warped Coral Fan drops itself as an item, and in block form is not waterlogged

**Screenshots/Videos**
REI shows the fan drops the wrong thing too:
![image](https://user-images.githubusercontent.com/16393543/119753484-b600c980-be53-11eb-94d7-53f01850b9aa.png)

Looking at a Warped Coral Fan in the nether:
![image](https://user-images.githubusercontent.com/16393543/119753763-29a2d680-be54-11eb-9c8a-c663241e6073.png)

**Comment by hugeblank** [comment]
@CorgiTaco It doesn't look like the loot table was updated? Is it deliberate that the warped coral fan doesn't drop itself?

Edit: my bad, I missed the `dropsLike` value being removed.

**Comment by CorgiTaco** [comment]
> 
> 
> @CorgiTaco It doesn't look like the loot table was updated? Is it deliberate that the warped coral fan doesn't drop itself?

the block was actually using the other block's loot table directly as argued here: https://github.com/CorgiTaco/BYG/commit/a8e764a589587e25be868e8d140e42a5a14876da#diff-ecc3fcc2639ddc0baa4c205c27e6e05f89677a8848ca39e8f54cbe1beecfa1ddL460
