### ISSUE TITLE
BYG creative tab's search bar prevents exiting creative menu with E

### ISSUE THREAD

**Issue by saltyseadoggo** [CorgiTaco/BYG#495]
__**API/Modloader**__
Forge

__**Describe the bug**__
The search bar in BYG's Creative tab is selected by default, and, to my knowledge, cannot be deselected, so, should the player try to press E to exit the menu, as they can in any vanilla creative tab except for the search tab, an E is input, and the menu doesn't close. This is inconvenient for those who don't have muscle memory to use ESC to close the creative menu instead.

__**To Reproduce**__
- Open creative menu in creative mode
- Click on BYG tab
- Attempt to exit creative menu by pressing E

**Expected behavior**
BYG's creative tab search bar should not be selected by default. The player should have to click on it to use it, so that it doesn't capture all E presses when the player is not trying to search.

**Comment by AOCAWOL** [comment]
The vanilla tab also does not close when pressing E so I just don't really understand the issue. It is very minor and I can't really find a solution I apologize for the inconvenience but you will just have to press esc.
