### ISSUE TITLE
Rivers the size of oceans

### ISSUE THREAD

**Issue by TheGriz** [CorgiTaco/BYG#5]
As reported on CurseForge comments world gen creates very large River biomes surrounding each landmass biome. Essentially creating large 1-2 biome islands each surround by water.  See attachment, all water areas are Minecraft:River biomes. 

<img width="656" alt="byg_river_oceans" src="https://user-images.githubusercontent.com/24501/86190332-b987b580-bb09-11ea-8b6e-39710a9f5208.png">

<img width="1819" alt="byg_river" src="https://user-images.githubusercontent.com/24501/86190909-4ed77980-bb0b-11ea-8041-80620b86329d.png">

Also any hope of a config file for Fabric? :)

Lovely biome work,
Thanks in advance

**Comment by CorgiTaco** [comment]
Have you ensured you're on the latest? I believe I've patched this issue

**Comment by TheGriz** [comment]
Ah, yes indeed. Now fixed in 0.9.3
I was using 0.9.2 release yesterday.

Thanks for the quick fix!

Any ETA on config options for Fabric? A list of biomes with enable/disable would be a nice start.
