### ISSUE TITLE
All BYG mushroom blocks make the wrong sounds

### ISSUE THREAD

**Issue by saltyseadoggo** [CorgiTaco/BYG#501]
__**API/Modloader**__
Forge

__**Describe the bug**__
The following BYG mushroom blocks make the same breaking sounds as crimson/warped stems:
- Death Cap Mushroom Block
- Green Mushroom Block
- Weeping Milkcap Mushroom Block
- Wood Blewit Mushroom Block
- Black Puff Mushroom Block
- White Mushroom Stem
- Brown Mushroom Stem
- Blue Glowshroom Block
- Purple Glowshroom Block
- Yellow Glowshrrom Stem
- Red Glowshroom Stem

__**To Reproduce**__
Place and break all of the above blocks.

**Expected behavior**
All of the above blocks belong to mushrooms that are more similar to the vanilla mushrooms than to the vanilla Nether fungus, so, to match vanilla behaviour, all of them should use wood block placing sounds.
If you prefer the honestly more appealing 1.16 sounds, however, I don't blame you. In this case, the non-stem blocks in the above list should use wart block placing and breaking sounds, since they are not stems, but caps.

**Comment by AOCAWOL** [comment]
this is intended.

**Comment by saltyseadoggo** [comment]
Might I ask why this is intended? It makes more sense to me for the cap blocks to make the wart block placing/breaking sounds instead of the stem ones, as they aren't stems, but instead the top parts of the mushroom, much like the wart blocks are for the Nether fungi.
I do get not wanting to have them use wood plank sounds like the overworld fungi, though, as they don't fit very well even in vanilla.
