### ISSUE TITLE
Withering oak log creates planks that look nothing like it

### ISSUE THREAD

**Issue by saltyseadoggo** [CorgiTaco/BYG#502]
__**API/Modloader**__
Forge

__**Describe the bug**__
The withering oak log is crafted into vanilla oak planks, which are bright tan, and look nothing like the grey, withered wood visible on the log block's cross section top texture.

__**To Reproduce**__
Check the recipes in JEI or the source code.

**Expected behavior**
- The withering oak log could have its log cross section more closely resemble the vanilla oak log cross section, so that the yielded planks make sense. A middle ground where the cross section has flecks of the oak wood colours in it could look interesting, and would clearly indicate how the tan oak planks are obtained from it.
- The withering oak log could lose its ability to make planks at all. Perhaps it could even be overhauled so that breaking one without silk touch just causes it to break into dust particles and yield nothing, since it is withered, and, if one uses silk touch, the log would simply have no use aside for decoration, like a mushroom stem.

**Comment by AOCAWOL** [comment]
this is intended for now.
