### ISSUE TITLE
'Withering' in the block names should be 'Withered'

### ISSUE THREAD

**Issue by saltyseadoggo** [CorgiTaco/BYG#503]
__**API/Modloader**__
Forge

__**Describe the bug**__
Withering saplings, logs, and leaves use the wrong verb tense.

__**To Reproduce**__
Read the item names?

**Expected behavior**
These blocks would be called 'Withered' sapling, log, leaves, etc., as this is the correct verb tense to indicate that they *have been* withered, whereas the current names would imply that they are undergoing the process of withering in the present.
This, of course, would be incorrect if you do mean to imply that they are undergoing a continuing withering process.

**Comment by AOCAWOL** [comment]
Hi! This is actually meant to be that thye are withering, hence why the inside of the withering oak log is still regular oak
