### ISSUE TITLE
Shipwrecks made from BYG wood types

### ISSUE THREAD

**Issue by saltyseadoggo** [CorgiTaco/BYG#504]
**Is your feature request related to a problem? Please describe.**
Biome mods often don't integrate their content into the world in many ways that vanilla does, making them feel more *external* to vanilla, rather than a part of it. I personally love finding modded items in loot tables, villager trades, world generation and the like, as it lets these aspects of the game see some new love too!
I already suggested wandering trader integration [here](https://github.com/CorgiTaco/BYG/issues/337), villager trade integration [here](https://github.com/CorgiTaco/BYG/issues/382) and Piglin integration [here](https://github.com/CorgiTaco/BYG/issues/385), and the latest updates have done a great job with adding new village types! This is another idea I came up with to further that ideal.

**Describe the solution you'd like**
BYG should let vanilla shipwrecks generate using its overworld wood types.
One potential point of concern is that some of BYG's brighter, bolder wood colours may create some clashing contrasts in shipwrecks when randomly paired with other wood types.  In vanilla Java edition, acacia and birch wood cannot be used in shipwrecks; I suspect this may be for this reason. As such, you may let only a selection of specifically chosen, more neutral BYG overworld woods be used in shipwrecks. Being able to configure this on the end user's end would be cool, too!

**Comment by CorgiTaco** [comment]
Enhancements are now to be posted in our discussions tab, it's been moved [here](https://github.com/AOCAWOL/BYG/discussions/1180)!
