### ISSUE TITLE
Large tree variants grow downwards and replace any blocks they touch.

### ISSUE THREAD

**Issue by mries92** [CorgiTaco/BYG#505]
__**API/Modloader**__
Forge 36.1.24

__**Describe the bug**__
When saplings grow, they do not correctly register "ground level" and grow directly into the ground, replacing any blocks they touch.

__**To Reproduce**__
Plant a sapling, either wait for it to grow or make it grow with bonemeal. When a large variant is produced, it will not treat the sapling location as ground level, and instead continue to grow downwards. I have confirmed this with oak and birch saplings.

**Expected behavior**
The sapling initial location should be treated as ground level, and the tree should only grow upwards.

**Screenshots/Videos**
![](https://i.imgur.com/Fi7SFa9.png) A screenshot of the issue. You can see the sapling growing through the floor its placed on (and it grew even futher down underground).

**Additional context**
Forge version 36.1.24
BYG version 1.2.7

**Logs**
Latest.log and Debug.log are located [here](https://paste.ee/p/UXjl1)

**Comment by CorgiTaco** [comment]
Is this the latest version, listing your byg verison would be appreciated...

**Comment by mries92** [comment]
Sorry about that. My BYG version is 1.2.7, minecraft version 1.16.5. I can't tell if it is the current version atm as curseforge appears to be down, but I will confirm as soon as it is back up.

Edit: Checked through the CurseForge app, I am indeed on the latest version.

**Comment by mries92** [comment]
I have been doing some digging and I think it might have something to do with the `isCliff` function called on line 552 of `common.world.feature.overworld.trees.util.BYGAbstractTreeFeature`. I have never worked with minecraft code before so I could be digging in the complete wrong area, figured I would share =]

**Comment by CorgiTaco** [comment]
Are you using the latest version?

**Comment by mries92** [comment]
I am on the current release version. Now that curseforge is back up I do see there is a beta 1.2.8, I will give that a go and see if it helps =]

**Comment by mries92** [comment]
Just tested with the 1.2.8 beta. It does seem that the trunks no longer burrow underground, however if the tree is grown on a raised platform (air underneath) it still grows downwards through it until it finds "ground level".

![](https://i.imgur.com/gXJydTz.png)

**Comment by CorgiTaco** [comment]
hmm

**Comment by mries92** [comment]
Commenting out the `isCliff` check that I mentioned definitely fixes it. I'm sure this check is important in some edge cases though lol so not really a solution, just trying to provide you with as much information as possible.

![](https://i.imgur.com/hDJbHwC.png)

Also just wanna say I really appreciate the great mod, its one of my must haves =]

**Comment by mries92** [comment]
Think I got it #506
