### ISSUE TITLE
The byg:chests/village/village_skyris_library loot table causes lag 

### ISSUE THREAD

**Issue by darkphan** [CorgiTaco/BYG#507]
__**API/Modloader**__
Forge 36.1.24
Minecraft: 1.16.5
BYG Version: 1.2.8

__**Describe the bug**__
When looting the Library chests at the top of the skyris village library, the game lags/pauses for a few seconds (this causes a server to do the same)

__**To Reproduce**__
Either loot the top chest in the Skyris Village Library. Or run "/loot give @s loot:byg:chests/village/village_skyris_library" 

**Expected behavior**
Not to cause lag.

**Comment by TelepathicGrunt** [comment]
This is actually normal behavior. The loot table gives a Exploration Map that targets Buried Treasure structure by default. If there is a Buried Treasure nearby, you will notice the loot is granted super fast. But if the structure is much further out from you or isn't within range at all, the game pauses as it searches a large number of chunks around looking for a Buried Treasure before giving up. That's what the lag is. (If no Buried Treasure is in range, the Explorer map turns into a regular map)

It's a vanilla thing. Not BYG's end. You can try using mods like Lithium on Fabric or this Forge Lithium port as both of these optimizes the locating of structures which will make all explorer maps in chests be loaded much faster. https://github.com/AeiouEnigma/lithium-forge
