### ISSUE TITLE
Nether ex and The Endergetic Expansion biomes don't spawn

### ISSUE THREAD

**Issue by raffycaccia** [CorgiTaco/BYG#51]
MINECRAFT 1.15.2
FORGE: 31.2.31

when the OH THE BIOMES YOU'LL GO is inserted in the modpack the biomes of these mods do not spawn, I tried to insert this:

biome.endergetic.end_midlands
biome.endergetic.end_highlands

in this config:

#Other Dimension Biomes
[Dimension_Settings]
#Add external Nether biomes by their registry names in a commented list.
ExternalNetherBiomes = ""
#Add external End biomes by their registry names in a commented list.
ExternalEndBiomes = ""
#Control the size of nether biomes.
#Range: 1 ~ 10
NetherBiomeSize = 2

but it didn't solve anything

**Comment by CorgiTaco** [comment]
ExternalEndBiomes = "endergetic:end_midlands,endergetic:end_highlands"

**Comment by CorgiTaco** [comment]
Netherex Is the same thing

**Comment by CorgiTaco** [comment]
I.e: ExternalNetherbiomes = "netherex:biomeregistry1,netherex:biomeregistry2"
