### ISSUE TITLE
Add stub methods for IMC Process handling

### ISSUE THREAD

**Issue by ampericus** [CorgiTaco/BYG#519]
This mod currently does not appear to have any provisions for handling IMC Messages. This may not be ideal, since other mod developers may choose to fork and subsequently submit a pull request to this repository in order to add compatibilities of this mod to their mods by using IMCs. I suggest adding a short "stub" type method for sending/handling incoming and/or outcoming IMC events in order to add a reference/baseline IMC implementation so no fork has to guess how an IMC method should look like.

**Comment by CorgiTaco** [comment]
Not sure how i'd go about adding this??

**Comment by CorgiTaco** [comment]
No response, closing
