### ISSUE TITLE
[1.15.2] BYG; Modded server crash log.

### ISSUE THREAD

**Issue by Cixon** [CorgiTaco/BYG#52]
[crash-2020-08-02_17.11.27-server.txt](https://github.com/CorgiTaco/BYG/files/5013074/crash-2020-08-02_17.11.27-server.txt)

**Comment by CorgiTaco** [comment]
Please send it here: https://hatebin.com/

**Comment by CorgiTaco** [comment]
Config related crash, resolved in DMs
