### ISSUE TITLE
java.lang.NullPointerException in BYG 1.2.9

### ISSUE THREAD

**Issue by Pinbap** [CorgiTaco/BYG#521]
**Before filling out this issue: **

**1. For major bugs, we only support BYG's latest version on a per Minecraft version basis(i.e latest for 1.15 is 1.0 while latest for 1.16 is 1.1).**

**2. Please test BYG on its own to confirm whether or not this is a mod conflict**
It is not a mod conflict

__**Mod conflict? If so, please clarify which mod is conflicting, if not skip this.**__

__**API/Modloader**__
Forge/Fabric?
Forge

__**Describe the bug**__
What is the bug? Where/How does it occur? etc.

__**To Reproduce**__
Please provide step by step instructions
BYG 1.2.9 in forge 36.1.31
**Expected behavior**
Minecraft would load up perfectly normally

**Screenshots/Videos**
If applicable, add screenshots/video to help explain your problem.

![HAHHAHAH](https://user-images.githubusercontent.com/85827235/122026692-ce8a5100-ce0d-11eb-9e2e-b2461a9ae15d.png)

**Additional context**

**Logs**
Use: https://paste.ee/ and paste the links. if log is huge please upload those
Please provide:
Crashlog -  
Debug.log - 
Latest.log - 

https://paste.ee/p/Z96ON

**Heap Dumps**
*If performance, please provide a heap dump/some sort of profile of your game(I recommend: https://visualvm.github.io/download.html)*
Heap Dump/Profile -

**Comment by Maltshakes** [comment]
Try deleting your BYG config file and run the game again to generate a new one.

**Comment by Pinbap** [comment]
> Try deleting your BYG config file and run the game again to generate a new one.
thx that worked for me
