### ISSUE TITLE
[Fabric 1.17] Vanilla Bookshelves have no texture

### ISSUE THREAD

**Issue by Fourmisain** [CorgiTaco/BYG#525]
![notexture](https://user-images.githubusercontent.com/8464472/123513174-eb374c00-d68b-11eb-82f8-03702dda11ec.png)

I'm using https://github.com/CorgiTaco/BYG/commit/5f5970f87801400f729e73fd64c6a0f1864de6f4 without any other mods.

Pressing F3+T to reload resources temporarily fixes the issue, until the game is restarted.

**Comment by AOCAWOL** [comment]
fabric 1.17 build was voided and will be re-evaluated at a later date.
