### ISSUE TITLE
1.12.2

### ISSUE THREAD

**Issue by lllMohandarlll** [CorgiTaco/BYG#53]
Biomes You Go loaded a new chunk [-20, 60] in dimension 0 (overworld) while populating chunk [-19, 59], causing cascading worldgen lag.
00:22:58.175
FML
Server thread
Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
00:23:00.592

https://pastebin.com/TCJ5wgQ6

**Comment by CorgiTaco** [comment]
This is 1.12 and we no longer support this version please update to our 1.15/1.16 versions :)

**Comment by Kasia1403** [comment]
Could someone renew support for MC 1.12.2 ?
