### ISSUE TITLE
Quartz Crystals get broken so fast they don't break server side and become invisible more often than not.

### ISSUE THREAD

**Issue by Darkmega18** [CorgiTaco/BYG#531]
__**API/Modloader**__
Forge. 36.1.62

__**Describe the bug**__
Quartz crystals are being broken too quickly even with simple tools like stone tool and equivalents, and so sometimes you mine them and they break but don't drop, leaving an invisible server side phantom of themselves and so you end up walking forward after clearing a path and stabbing yourself on them cause they didn't actually break.

Repeatedly breaking the quartz crystals also sometimes decides it doesn't actually want to break them unless you potentially veinmine/ore excavate them enmass or just up root them.

__**To Reproduce**__
just mine quarts crystals with a pickaxe potentially a little faster than stone (I had been using a paxel from another mod of stone equivalence in this case).

**Expected behavior**
That the quartz crystal breaks fine.

**Additional context**
Lots of other mods. But this is just breaking a terrain feature/object that we're talking about, so it shouldn't be doing much difference for anything.

**Logs**
No crashes etc, it's just an annoyance.

**Comment by CorgiTaco** [comment]
Sounds to me like lag on the client
