### ISSUE TITLE
encountered an error during common_setup phase

### ISSUE THREAD

**Issue by Shiffhead** [CorgiTaco/BYG#532]
**Before filling out this issue: **
**1. For major bugs, we only support BYG's latest version on a per Minecraft version basis(i.e latest for 1.15 is 1.0 while latest for 1.16 is 1.1).**
**2. Please test BYG on its own to confirm whether or not this is a mod conflict**

__**Mod conflict? If so, please clarify which mod is conflicting, if not skip this.**__

__**API/Modloader**__
Forge/Fabric?
forge 
__**Describe the bug**__
What is the bug? Where/How does it occur? etc.
as soon as i start game a error message occurs
__**To Reproduce**__
Please provide step by step instructions
i just start the game on 1.16.5 and it crashes
**Expected behavior**
For it to load and not crash 
**Screenshots/Videos**
If applicable, add screenshots/video to help explain your problem.
[https://imgur.com/a/dkMMIYX]

**Additional context**

**Logs**
Use: https://paste.ee/ and paste the links. if log is huge please upload those
Please provide:
Crashlog - 
Debug.log - 
Latest.log - 

**Heap Dumps**
*If performance, please provide a heap dump/some sort of profile of your game(I recommend: https://visualvm.github.io/download.html)*
Heap Dump/Profile -

**Comment by CorgiTaco** [comment]
you've given no logs or any information, so closing this
