### ISSUE TITLE
Horse Armor Bug

### ISSUE THREAD

**Issue by Ejuggle** [CorgiTaco/BYG#537]
__**API/Modloader**__
Fabric

__**Describe the bug**__
When using penderite and ametrine horse armor, it shows up as the purple and black unrecognizable item :(

![2021-08-09_18 57 57](https://user-images.githubusercontent.com/88695363/128797063-4d85b105-6e51-4a0e-afe2-3491e88f472a.png)

**Comment by CorgiTaco** [comment]
Foxed in latest
