### ISSUE TITLE
[1.15.2 Forge] Flying trees 

### ISSUE THREAD

**Issue by FuryOfFools** [CorgiTaco/BYG#54]
![image](https://user-images.githubusercontent.com/40697349/89305764-1a158f80-d680-11ea-9526-8798cfeb247a.png)

**Comment by CorgiTaco** [comment]
That's a vanilla bug aswell. Not our issue as we do all the correct steps to ensure and prevent that

**Comment by FuryOfFools** [comment]
@CorgiTaco 
In mods from the abnormals team or in biomes o' plenty, this problem was somehow avoided. In your mod, every autumn forest tries to find zen. Doesn't it really matter? I liked your mod, but it spoils the whole picture.
I apologize for the persistence
