### ISSUE TITLE
Some new ores don't have tags

### ISSUE THREAD

**Issue by shouta65** [CorgiTaco/BYG#543]
__**API/Modloader**__
Forge

__**Describe the bug**__
First I encountered that I cannot ore-doubling Brimstone Nether Quartz Ore on Mekanism and/or Elemental Craft.
I saw some codes and noticed that some recently added ores (I found Brimstone Nether Quartz Ore and Gold Ore) don't have correct tags. maybe it's an issue as same as #431.

**Comment by CorgiTaco** [comment]
you're going to need to be more specific as to what specific ore tag we should be using

**Comment by shouta65** [comment]
I would suggest tagging them with the following. I'm not familiar with modding so I hope this works properly

Byg Item ID|Tag
---|---
blue_nether_quartz_ore|forge:ores/quartz
blue_nether_gold_ore|forge:ores/gold or minecraft:gold_ores
brimstone_nether_quartz_ore|forge:ores/quartz
brimstone_nether_gold_ore|forge:ores/gold or minecraft:gold_ores

**Comment by shouta65** [comment]
A similar issue thread is opened: #562. it contains more suggestions for tagging

**Comment by AOCAWOL** [comment]
Forge no longer has tags for 1.18.2 but these have been added to the C Tags

**Comment by AOCAWOL** [comment]
I lied <3

**Comment by AOCAWOL** [comment]
this has been fixed
