### ISSUE TITLE
[1.16.5 ] BYG 1.3.2 - Stripping wood

### ISSUE THREAD

**Issue by ghost** [CorgiTaco/BYG#545]
Client crashed after strip the wood using axe. Any kind of byg wood and any axe in-game.
- its not mod conflict. I also test with and without Sodium.
- 
__**API/Modloader**__
Fabric

__**Reproduce**__
1. Get an axe;
2. Get a byg wood;
3. strip;
4. client crash.

**Expected behavior**

**Screenshots/Videos**
If applicable, add screenshots/video to help explain your problem.
0

**Additional context**

**Logs**
Use: https://paste.ee/ and paste the links. if log is huge please upload those
Please provide:
Crashlog - https://pastebin.com/RWwUePUJ
Debug.log - 
Latest.log - 

**Heap Dumps**
*If performance, please provide a heap dump/some sort of profile of your game(I recommend: https://visualvm.github.io/download.html)*
Heap Dump/Profile - nope

**Comment by MakkuMikan** [comment]
This issue also appears in the forge version, and if done on a server, only the client crashes.
