### ISSUE TITLE
BYG crashes the game on startup

### ISSUE THREAD

**Issue by Jook06** [CorgiTaco/BYG#546]
__**API/Modloader**__
Fabric

__**Describe the bug**__
When I press play from the Minecraft launcher, the game attempts to launch for maybe 30 seconds, and then crashes and comes back with a crash report

__**To Reproduce**__
My friends have done exactly what I've done and haven't had any issues, so I'm not sure how reproduceable it is, but this is exactly what I did 
1. Download version 1.3.2, also known as the most recent file on Curseforge, for 1.16.5
2. Place it in your mods folder
3. Open minecraft

Boom, crash.

**Expected behavior**
I expected the game to load without issue

**Screenshots/Videos**

![image](https://user-images.githubusercontent.com/89737209/131253663-7b170c6e-5994-430d-b141-b80c938aa821.png)

**Logs**
https://paste.ee/p/XMFvN

**Comment by CorgiTaco** [comment]
Reset your configs
