### ISSUE TITLE
BYG Log didn't like me stripping them naked

### ISSUE THREAD

**Issue by Klouver-github** [CorgiTaco/BYG#548]
### Mod Version

1.16.5

### Mod Loader

Forge

### Mod Loader Version

latest

### What happened?

I was building a house until I stripped the swamp tree log from BYG and it crashed my game. I don't think the wood liked me stripping them so they made Crash take me out and flee the scene, I even had House insurance too

### latest.log

78d2e4dc388a48b1aabb5329d50b9ab4

**Comment by CorgiTaco** [comment]
Duplicated of #545
