### ISSUE TITLE
[Bug]: Sheep don't eat overgrown stone, dacite or netherrack

### ISSUE THREAD

**Issue by saltyseadoggo** [CorgiTaco/BYG#549]
### Mod Version

1.3.2

### Mod Loader

Forge

### Mod Loader Version

36.1.18

### What happened?

Sheep do not eat the grass off of `byg:overgrown_stone`, `byg:overgrown_dacite` or `byg:overgrown_netherrack` the way they do with `minecraft:grass_block.`

![2021-08-30_14 41 03](https://user-images.githubusercontent.com/69029346/131409677-5e5b5d7b-e09c-4772-aaa6-a93f9df18f1e.png)

### latest.log

[latest.log](https://github.com/CorgiTaco/BYG/files/7079763/latest.log)

**Comment by CorgiTaco** [comment]
I think in this case, it makes sense
