### ISSUE TITLE
leaf particles and color itself?

### ISSUE THREAD

**Issue by qwpuwu** [CorgiTaco/BYG#55]
Well I don't know if they will understand but ...

my problem with the mod is that when I "break" a leaf the particles are white in gray, or when I look in the minimap the leaves are all gray in white, and it bothers me a little bit, it's probably a problem with the settings of the mod but I wanted to talk here (I still don't know how the site works properly) ... Well that's my problem

**Comment by Linguardium** [comment]
it sounds like the leaf block color provider is not being referenced correctly for the minimap or particles.  If the color works in main game, that is likely the issue. hope that helps them find the fix

**Comment by CorgiTaco** [comment]
Will be patched in 1.16.2

**Comment by AOCAWOL** [comment]
This bug cannot be replicated and has been tried in all 3 versions of BYG. All BYG Leaves do not have this issue in-game so this must be an issue on your end. I apologize for the inconvenience but you most likely have a mod incompat.
