### ISSUE TITLE
[Bug]: Ametrine clusters don't have collision

### ISSUE THREAD

**Issue by saltyseadoggo** [CorgiTaco/BYG#553]
### Mod Version

1.3.2

### Mod Loader

Forge

### Mod Loader Version

36.1.18

### What happened?

Entities do not collide with ametrine clusters. If this wasn't intentional, I figure they're supposed to behave like subzero crystal and vanilla amethyst clusters and have collision.

### latest.log

[latest.log](https://github.com/CorgiTaco/BYG/files/7079918/latest.log)

**Comment by saltyseadoggo** [comment]
Amethyst clusters actually do have collision. In that case, the ametrine clusters not having collision is the bug. Whoops!

**Comment by CorgiTaco** [comment]
Should be fixed, reopen if this isnt the case
