### ISSUE TITLE
[Bug]: There are two rocky stone recipes

### ISSUE THREAD

**Issue by saltyseadoggo** [CorgiTaco/BYG#554]
### Mod Version

1.3.2

### Mod Loader

Forge

### Mod Loader Version

36.1.18

### What happened?

There are two recipes for rocky stone: one shaped, one shapeless, with the same ingredients.
I suggest removing the shaped recipe.

![2021-08-30_15 33 50](https://user-images.githubusercontent.com/69029346/131414626-454a11a0-3789-44c7-b8e7-603d002e7c3c.png)

### latest.log

[latest.log](https://github.com/CorgiTaco/BYG/files/7079955/latest.log)

**Comment by CorgiTaco** [comment]
Closed by https://github.com/AOCAWOL/BYG/commit/2deafa042cbab5a4626b9a481df7f5e89e15667a
