### ISSUE TITLE
[Bug]: Peat recipes outputs scoria

### ISSUE THREAD

**Issue by saltyseadoggo** [CorgiTaco/BYG#555]
### Mod Version

1.3.2

### Mod Loader

Forge

### Mod Loader Version

36.1.18

### What happened?

The peat recipes yield scoria instead of peat. (the upper and lower recipes here; their ids reference peat.)

![2021-08-30_15 37 32](https://user-images.githubusercontent.com/69029346/131414747-6a1d740f-aa99-4a1f-9f23-dd49d534b6f6.png)

### latest.log

[latest.log](https://github.com/CorgiTaco/BYG/files/7079962/latest.log)

**Comment by CorgiTaco** [comment]
Should be fixed, reopen if it is not
