### ISSUE TITLE
[Bug]: There are two scoria recipes

### ISSUE THREAD

**Issue by saltyseadoggo** [CorgiTaco/BYG#556]
### Mod Version

1.3.2

### Mod Loader

Forge

### Mod Loader Version

36.1.18

### What happened?

There are two scoria recipes: one that uses two basalt and two andesite to produce four scoria, and one with half each of input and output that is shapeless.
I believe only one or the other is needed.

![2021-08-30_15 39 09](https://user-images.githubusercontent.com/69029346/131414911-10b0ff23-c916-42af-a197-8ca90dab67c6.png)
![2021-08-30_15 39 10](https://user-images.githubusercontent.com/69029346/131414913-cdf607d0-f34d-4d33-80ef-2d80fa85f17c.png)

### latest.log

[latest.log](https://github.com/CorgiTaco/BYG/files/7079967/latest.log)

**Comment by CorgiTaco** [comment]
Should be fixed, if issue persists reopen this issue
