### ISSUE TITLE
[Bug]: There are two soapstone recipes

### ISSUE THREAD

**Issue by saltyseadoggo** [CorgiTaco/BYG#557]
### Mod Version

1.3.2

### Mod Loader

Forge

### Mod Loader Version

36.1.18

### What happened?

There are two soapstone recipes. The first is shapeless, accepting one item from the `forge:cobblestone` tag and one clay, while the latter is shaped, accepting one `minecraft:cobblestone` and one clay. The former is erroneous because other cobblestones are different in composition and should not be usable here, like in the diorite recipe, while the latter is erroneous because it is not shapeless, like the andesite recipe is.

![2021-08-30_15 41 13](https://user-images.githubusercontent.com/69029346/131415173-a3736457-744c-4bf0-b658-e113bb09ec27.png)

### latest.log

[latest.log](https://github.com/CorgiTaco/BYG/files/7079979/latest.log)

**Comment by CorgiTaco** [comment]
Should be fixed, if the issue persists reopen this
