### ISSUE TITLE
[Bug]: There are two mud block recipes

### ISSUE THREAD

**Issue by saltyseadoggo** [CorgiTaco/BYG#558]
### Mod Version

1.3.2

### Mod Loader

Forge

### Mod Loader Version

36.1.18

### What happened?

More duplicate recipe fun. One accepts eight dirt blocks, the other only one.

![2021-08-30_15 45 06](https://user-images.githubusercontent.com/69029346/131415387-53ab102d-b9e0-4e24-b8e2-a5d1517a7bbc.png)

### latest.log

[latest.log](https://github.com/CorgiTaco/BYG/files/7079983/latest.log)

**Comment by CorgiTaco** [comment]
Should be fixed, if it isnt, reopen this issue
