### ISSUE TITLE
r

### ISSUE THREAD

**Issue by ghost** [CorgiTaco/BYG#559]
r

**Comment by ghost** [comment]
latest.log: [here](https://pastebin.com/Em3TadUR)

**Comment by CorgiTaco** [comment]
this is a mixin conflict with lithium

**Comment by SZUMASTER** [comment]
Thanks for the information ;)

**Comment by SZUMASTER** [comment]
> this is a mixin conflict with lithium

Without lithium, problem still exist. nothing changes, any idea?

**Comment by CorgiTaco** [comment]
send the new log then?

**Comment by SZUMASTER** [comment]
problem resolved :)

**Comment by CorgiTaco** [comment]
@SZUMASTER mind sharing how?

**Comment by SZUMASTER** [comment]
reset button :D

**Comment by SZUMASTER** [comment]
DONT PIN JUST FIX

**Comment by CorgiTaco** [comment]
@SZUMASTER you never said what the fix was...

And i looked at lithium's code... there's most definitely a conflict

**Comment by SZUMASTER** [comment]
i just motivate you ^^

**Comment by SZUMASTER** [comment]
Here's new logs, maybe help you;
[console](https://pastebin.com/UG3tAQcC)
[crashlog](https://pastebin.com/Xjpkb7SJ)

byg.mixins.json:common.MixinWalkNodeProcessor

**Comment by szumaster** [comment]
> @SZUMASTER you never said what the fix was...
> 
> And i looked at lithium's code... there's most definitely a conflict

so you find something?

**Comment by mhrazor1** [comment]
Any progress on this?

**Comment by ghost** [comment]
work for me

**Comment by NighthowlerStudios** [comment]
the version released that this was attempted is actually causing the nether and end to crash, which is found in many separate issues and something even roadrunner itself gets caught in.  something got messed up in the terrain generators, please document to us what you did to the code vanillavibe, as it is broken.

it is possible the immediate crash was fixed but something else on the codebase got accidentally merged alongside it

**Comment by NighthowlerStudios** [comment]
see here #601 #598 #594 #592 #579 

I am actively investigating mod collisions and will report what I find here

**Comment by NighthowlerStudios** [comment]
nope, no mod collisions.  the crash can happen with byg completely on its own

**Comment by NighthowlerStudios** [comment]
to reproduce, just enter the nether or end.

**Comment by Kaleidio** [comment]
last working version with roadrunner also installed is 1.2.9

**Comment by NighthowlerStudios** [comment]
okay, so here's what I found:

it is impossible to run the game without roadrunner installed at all
you MUST have roadrunner 1.3 installed, 1.4 has had chunk class changes and thus has been made incompatible all over again
you cannot run a version of byg lower than 1.3.5 to play.
