### ISSUE TITLE
Could not execute entrypoint stage 'main' due to errors

### ISSUE THREAD

**Issue by Akuji-OFF** [CorgiTaco/BYG#560]
### Mod Version

1.16.5

### Mod Loader

Fabric

### Mod Loader Version

0.11.6

### What happened?

Weird, every time i launch minecraft, it always crash and i receive the message : Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'byg'!

### latest.log

[latest.log](https://github.com/CorgiTaco/BYG/files/7080384/latest.log)
[crash-2021-08-31_09.55.40-client.txt](https://github.com/CorgiTaco/BYG/files/7080781/crash-2021-08-31_09.55.40-client.txt)

**Comment by Akuji-OFF** [comment]
I just updated my crash report.

**Comment by X-Niter** [comment]
+1 Identical issue with the Latest version of this mod, 1.16.5, and latest update of Fabric api

**Comment by ObjektivC** [comment]
Try resetting your configs.

**Comment by CorgiTaco** [comment]
Reset your configs
