### ISSUE TITLE
[Bug]: Floating wailing nylium in the garth

### ISSUE THREAD

**Issue by saltyseadoggo** [CorgiTaco/BYG#561]
### Mod Version

1.3.2

### Mod Loader

Forge

### Mod Loader Version

36.1.18

### What happened?

I found the environment in the image below in a world generated with seed `-2130216035544162063` at coordinates `-525 73 98`. It looks like wailing nylium is ignored by the cave carvers or something.

![2021-08-30_20 19 14](https://user-images.githubusercontent.com/69029346/131436532-2d6070e8-9e14-4546-9d3c-a71619b576e4.png)

### latest.log

[latest.log](https://github.com/CorgiTaco/BYG/files/7080898/latest.log)

**Comment by CorgiTaco** [comment]
this is the vanilla nether generator, we dont have much say here
