### ISSUE TITLE
[Bug]: Missing and/or erroneous 1.16 tags

### ISSUE THREAD

**Issue by saltyseadoggo** [CorgiTaco/BYG#562]
### Mod Version

1.3.2

### Mod Loader

Forge

### Mod Loader Version

36.1.18

### What happened?

As per Corgi's instructions, here are all of the vanilla block and item tags that BYG needs to make additions to, or changes to its existing additions.

Block tags:

`enderman_holdable`
- Remove `#minecraft:small_flowers`, which is in this tag by default.
- Remove mud bricks, since it's a manufactured block.
- Remove peat, meadow grass and meadow dirt in favour of adding them to `#minecraft:dirt`; see above.
- Add items that match what endermen can pick up in vanilla:
- - Mushrooms: Green mushroom, wood blewit, weeping milkcap, soul shroom, blue glowshroom, purple glowshroom and death cap.
- - Fungi: Sythian fungus, shulkren fungus, potentially bulbis oddities and embur warts.
- - Sand: Pink sand, purple sand, blue sand, black sand and white sand.
- - Cactus: Golden spined cactus, prickly pear cactus, mini cactus, warped cactus, oddity cactus
- In vanilla, endermen can pick up crimson and warped roots, but not nether sprouts, which seems arbitrary.
- - I suggest picking and choosing a couple ground foliage items from every nether and end biome and add them to the tag.
- In vanilla, endermen destroy warped forests by rearranging warped nylium, so maybe don't let them pick up yours.

`fence_gates` Add all fence gates.

`flower_pots` Add all of BYG's potted plant blocks.

`gold_ores` Add blue nether gold ore and brimstone nether gold ore.

`ice` Add black ice and packed black ice.

`infiniburn_overworld` Soul sand/soil aren't in this tag in vanilla, so I don't think you need brimstone or cryptic stone here.

`logs` Already includes `#minecraft:logs_that_burn`, so this should only contain non-flammable logs.

`non_flammable_wood` Should contain all of BYG's fireproof wood blocks- logs, fences, stairs, all of them.

`soul_fire_base_blocks` Why is brimstone in here if it has its own fire type, especially since cryptic stone is not?

`standing_signs` Add all BYG standing (placed on floor) signs.

`wall_signs` Add all BYG wall signs.

`wart_blocks` Add embur and shulkren wart blocks.

Item tags:

`gold_ores` Add blue nether gold ore and brimstone nether gold ore.

`logs` Already includes `#minecraft:logs_that_burn`, so this should only contain non-flammable logs.

`non_flammable_wood` Should contain all of BYG's fireproof wood blocks- logs, fences, stairs, all of them.

`signs` Add all BYG signs.

`soul_fire_base_blocks` Add nylium soul sand and soil if you want them to be usable in the soul campfire recipe.

`stone_bricks` Doesn't contain blackstone, nether brick, etc. in vanilla, so I think it's meant exclusively for plain stone bricks. I think this can be removed.

### latest.log

Not applicable.

**Comment by AOCAWOL** [comment]
that has been fixed
