### ISSUE TITLE
[Bug]: Setting BYG Biome weights in config causes chunk errors

### ISSUE THREAD

**Issue by vinesaucebeep** [CorgiTaco/BYG#564]
### Mod Version

1.16.5

### Mod Loader

Forge

### Mod Loader Version

36.2.2

### What happened?

When setting biome weights to 0 would cause massive chunk errors and leave half of the world to be missing.

### latest.log

N/A

**Comment by CorgiTaco** [comment]
you've given me no images/logs/visuals to work with, closing this until more information can be provided
