### ISSUE TITLE
Meadow grass becomes invisible

### ISSUE THREAD

**Issue by GQJIMU** [CorgiTaco/BYG#565]
### Mod Version

1.3.2

### Mod Loader

Forge

### Mod Loader Version

36.2.0

### What happened?

The meadow grass block becomes invisible,

### latest.log

There wasnt a log ithink

**Comment by Naigaru** [comment]
Adding on to this, the same grass blocks became invisible and let you see through the world, when I added quark to our server. So guess there is a compatibility issue between the two mods.
Edit: After updating 4 other mods seems to have fixed the issue anyway, even tho they weren't either of these 2 so I have no idea again xD lol

**Comment by LiskoSlayer63** [comment]
I have this problem too, one of my servers players encountered this today. I'll try to update all the mods when I have time and I'll report then if it worked or not.

**Comment by GothCartel** [comment]
I had the same issue with meadow grass, it only appears with generated land rather than placed blocks, turning off Emissive Texturing in Optifine fixes the issue

**Comment by Brycey92** [comment]
![image](https://user-images.githubusercontent.com/666399/142748763-cb08484f-4fec-45f0-9c7c-a8c422a900a6.png)
Here's a screenshot

**Comment by PitchRE** [comment]
up

**Comment by SollyW** [comment]
down

**Comment by superninjakiwi** [comment]
left

**Comment by CorgiTaco** [comment]
try 1.3.5, if the issue persists reopen.

**Comment by kil0byt3** [comment]
I'm having this still in Enigmatica 6 Expert, tried without Optifine and also reinstalled the pack, same issue. Attempted turning off Quark's Greener Grass feature, and reinstalling Optifine to turn off Emissive Textures as well. Can provide logs or w/e else you need.

**Comment by kil0byt3** [comment]
update: I had installed Dynamic Surroundings and Better Foliage. Removed them and meadow grass is now working.

I'll test later to nail down which of the two it is, but that's the issue here for sure.

**Comment by Voidion** [comment]
Found out the issue, it's Better Foliage's Connected Grass feature. The leaves also have an issue with the Blooming Witch Hazel leave blocks where it's a glitched expanded texture
