### ISSUE TITLE
Code suggestion: use my new biome api

### ISSUE THREAD

**Issue by Trinsdar** [CorgiTaco/BYG#566]
I recently took it upon myself to port fabric's biome api to forge 1.16, since the forge biome api on 1.16 is practically non existent. My hope is to at least get all the big biome mods using it, though if they don't it's fine too, it would just make my work 10 times harder.
Anyways here it is: https://github.com/Reforged-Mods/FabricBiomeApiReforged

**Comment by CorgiTaco** [comment]
Ty for the offer, but I'm going to pass
