### ISSUE TITLE
[Bug]: atm6 1.8.3 some players seeing crash on startup

### ISSUE THREAD

**Issue by radiomike** [CorgiTaco/BYG#570]
### Mod Version

1.3.4

### Mod Loader

Forge

### Mod Loader Version

36.2.4

### What happened?

Various players seeing the attached crash on client startup.

Saw the same crash myself on a testing version of the modpack. Changing my java version seemed to fix it at the time, was testing  java 16 and dropped down to 11. Since then I've returned to java 16 and not seeing the issue at the moment. Makes me think it's a mod interaction/race condition.

See also https://github.com/AOCAWOL/BYG-1/issues/24

### latest.log

[message.txt](https://github.com/CorgiTaco/BYG/files/7168478/message.txt)

**Comment by HeartlessAUS** [comment]
oddly enough, you can force this exact crash by adding 'smooth scrolling everywhere' on ATM6

edit: this issues also occurs from "industrial agriculture"

**Comment by HugeLol556** [comment]
Can confirm going from Java 11 to 16 caused consistent crashes. (ATM6 1.8.2)
[crash-2021-09-26_21.22.04-client.txt](https://github.com/CorgiTaco/BYG/files/7233448/crash-2021-09-26_21.22.04-client.txt)

**Comment by CorgiTaco** [comment]
> 
> 
> Can confirm going from Java 11 to 16 caused consistent crashes. (ATM6 1.8.2)
> [crash-2021-09-26_21.22.04-client.txt](https://github.com/CorgiTaco/BYG/files/7233448/crash-2021-09-26_21.22.04-client.txt)

i doubt java version has to do with anything here but please use java 8 for 1.16.5

**Comment by Sintinium** [comment]
I'm getting this issue in the monumental experience modpack as well. For me it happens after exactly 386 mods. No matter what mod I add at 387 it crashes with this error. I've tried this on ATM6 but I don't get the crash. The only mods I've added are Yung's extras, Yung's Dungeons, GameMenuModOptions, and Configured. Adding these to ATM6 has no effect though even after 386 mods.

**Comment by CorgiTaco** [comment]
Fixed in 1.18
