### ISSUE TITLE
[Fabric 1.17] BYG biomes are spawning only in MLClimate.COOL

### ISSUE THREAD

**Issue by StardustGear** [CorgiTaco/BYG#574]
All BYG biomes are spawning only in the 'cool' climate, regardless of configured climate value.

This should be an easy fix, it's just
`OverworldBiomes.addContinentalBiome(key, overworldPrimaryBiomeData.getClimate().getClimate(), overworldPrimaryBiomeData.getWeight());`
in core/world/BYGBiomes.java

I can't pull request this because I have major problems with creating a branch for Fabric-1.17.x in my fork.

**Comment by CorgiTaco** [comment]
There's no fabric 1.17 release so this is not an issue at this time.
