### ISSUE TITLE
[Bug]: Palm Saplings can't be planted

### ISSUE THREAD

**Issue by Umbreeunix** [CorgiTaco/BYG#578]
### Mod Version

1.16.5

### Mod Loader

Fabric

### Mod Loader Version

0.11.6

### What happened?

I've collected palm saplings in the hopes to harvest the wood at my farm, but they wont plant on dirt or sand blocks

### latest.log

[latest.log](https://github.com/CorgiTaco/BYG/files/7314028/latest.log)

**Comment by CorgiTaco** [comment]
Fixed in 1.18
