### ISSUE TITLE
[Bug]: Server crash on end generation

### ISSUE THREAD

**Issue by SirEndii** [CorgiTaco/BYG#579]
### Mod Version

1.3.5

### Mod Loader

Forge

### Mod Loader Version

36.2.5

### What happened?

When we try to join the end, the server does crash.
We need to delete the end and reset(Or set the dimension) the player data.

I tried to reset the configs. I also tried to disable the end generation in the byg-world.toml, but without success.
Is there a workaround until this gets fixed?

I can test if  this is a compatibility issue in the next days.

### latest.log

Crashlog - https://gist.github.com/Seniorendi/ed25056ae229c81697e8b7c4619f89b7
Latest.log - https://gist.github.com/Seniorendi/1ec264aa922340524aed0ccbba2663af

**Comment by Lylithrea** [comment]
I also have the same problem when trying to enter the end. Tried pre-generating chunks, but when rendering the chunk you'd spawn in, it crashes the game.

**Comment by K-3-V-1-N** [comment]
Same, but mine crashes loading the nether.

**Comment by Lylithrea** [comment]
Update: I've found that if i tp myself to another position in the end its fine, I can even normally load the chunk that was the problem, and see the obsidian platform, however if I tp inside the chunk it crashes. I'm using the mod waystones, and when placing a waystone within the end in the specific crashing chunk, and tp to there from the overworld it also crashes.

**Comment by SirEndii** [comment]
I fixed it on my server
1. Shut down the server
2. Delete the end dimension folder
3. Open the `level.dat` file of the world with the software NBTExplorer
4. Go to Data→WorldGenSettings→dimensions→minecraft:the_end
5. Delete `minecraft:the_end`

![image](https://user-images.githubusercontent.com/67484093/140314688-8c3a6aa7-237d-43c5-991e-12bd4baac875.png)

Your level.dat file should then look like this without `minecraft:the_end`

**Comment by NighthowlerStudios** [comment]
you must have roadrunner installed to play.  downgrade to roadrunner 1.3 to play.

**Comment by SirEndii** [comment]
Byg needs a lithium fork to work? What a weird thing.
I fixed this issue for my self(see last comment from me).

**Comment by NighthowlerStudios** [comment]
okay so what happened is that one of their non main devs coded a fix for roadrunner compat on the forge branch.  (see #559)

this in turn however, was not verified by the other devs and he did not explain what he did

so now somewhere in the carving code there is code that breaks if roadrunner is not present.  it's an accidental dependency on 1.16.5 that has yet to be fixed.  that dependency not only breaks if the mod is missing, but also breaks if the roadrunner mod is 1.4 instead of 1.3 as roadrunner 1.4 had changes
