### ISSUE TITLE
[1.16.1] Blueberry bush doesn't break with one punch like Vanilla Sweet Berries. Intentional or bug?

### ISSUE THREAD

**Issue by Gbergz** [CorgiTaco/BYG#58]
Title^

**Minecraft:** 1.16.1
**Forge:** 32.0.106
**Mod Version:** 1.0.15

**GIF Showing the issue:**
https://gyazo.com/f2b9d90a4eccb41a7486df0fd3f084b4

**-** Gbergz

**Comment by CorgiTaco** [comment]
THat is most definitely a bug, thnx for reporting it

**Comment by AOCAWOL** [comment]
this has been fixed in our latest builds for both forge and fabric

**Comment by Gbergz** [comment]
Seems to work, except now when you break the plant no berries drop from it at all.
Edit: Also the berry plant doesn't have the same break/place sound as the vanilla variant.

**Comment by AOCAWOL** [comment]
this has been fixed and will be in our next patch/update
