### ISSUE TITLE
[Bug]:  Canyon edge biome is fucked

### ISSUE THREAD

**Issue by Mr-Syntax** [CorgiTaco/BYG#580]
### Mod Version

1.16.5

### Mod Loader

Forge

### Mod Loader Version

36.2.0

### What happened?

![image](https://user-images.githubusercontent.com/59544236/136821310-74ba23e6-6166-4062-8e4a-bc4671b9b4b0.png)

in this pack

https://www.curseforge.com/minecraft/modpacks/chosencraft

### latest.log

I have none nothing is crashin
[crash-2021-10-11_04.13.36-server.txt](https://github.com/CorgiTaco/BYG/files/7323862/crash-2021-10-11_04.13.36-server.txt)
g

**Comment by Mr-Syntax** [comment]
![image](https://user-images.githubusercontent.com/59544236/136821931-e1b7672e-5b7e-404f-9ee3-61f243fda8a3.png)

**Comment by ObjektivC** [comment]
Canyon edge is an unimplemented biome and doesn't spawn normally. The modpack you mentioned does appear to contain terraforged, which is known to cause the biome to spawn unless you blacklist it.

**Comment by ObjektivC** [comment]
Please inform the modpack owner of this and ask them to blacklist the biome in terraforged's config.

**Comment by Mr-Syntax** [comment]
ahh okay well that makes sense :D

**Comment by Mr-Syntax** [comment]
thank you for the quick response
