### ISSUE TITLE
[Bug]: Crash to launcher when entering nether for the first time

### ISSUE THREAD

**Issue by dashkal16** [CorgiTaco/BYG#582]
### Mod Version

1.3.5

### Mod Loader

Forge

### Mod Loader Version

36.2.8

### What happened?

Single Player.  Crash to launcher when loading into the nether for the first time.

### latest.log

[latest.log](https://github.com/CorgiTaco/BYG/files/7349868/latest.log)

**Comment by dashkal16** [comment]
[byg-nether-biomes.json.txt](https://github.com/CorgiTaco/BYG/files/7349870/byg-nether-biomes.json.txt)

And after asking for that file, I have a strong hint as to what's happened.  I removed infernalexp early in testing.

So this bug report becomes a simple request for a better error message.

**Comment by CorgiTaco** [comment]
Old entries in config file. Resolved on discord
