### ISSUE TITLE
[Bug]: Everybiome spawns with byg:palm_wood

### ISSUE THREAD

**Issue by ghost** [CorgiTaco/BYG#583]
### Mod Version

1.3.5

### Mod Loader

Fabric

### Mod Loader Version

0.11.7

### What happened?

Dope D.O.D. became the illest.

Real issue: everybiome spawn with palm trees

### latest.log

clear.

**Comment by CorgiTaco** [comment]
you need to provide both a latest log and pictures in relation to your issue

**Comment by ghost** [comment]
![2021-10-16_23 07 18](https://user-images.githubusercontent.com/85596288/137629784-c4edf4d1-3ebe-4b47-a9c7-1f08533ebdad.png)
![2021-10-16_23 07 32](https://user-images.githubusercontent.com/85596288/137629785-fb2e49fc-2e73-4e1e-bd43-e89ad26e12e2.png)

**Comment by ghost** [comment]
![2021-10-18_11 43 50](https://user-images.githubusercontent.com/85596288/137707741-63c93ba5-be09-4c5f-8482-5a6c40cf4c0e.png)

**Comment by ghost** [comment]
Also same problem like in #578

**Comment by ghost** [comment]
![2021-10-18_12 46 03](https://user-images.githubusercontent.com/85596288/137716794-8f83f70e-afd2-4aa7-bda5-fc506c043099.png)

**Comment by ghost** [comment]
Chunks also load 5x slower.

**Comment by ghost** [comment]
![2021-10-18_16 30 56](https://user-images.githubusercontent.com/85596288/137751710-69f6a6af-12b2-4686-bac1-3c31c177c8c4.png)

**Comment by ghost** [comment]
I think I found the reason, no registered biomes, all biomes named; overworld

**Comment by CorgiTaco** [comment]
this is most likely a registry desunc

**Comment by ghost** [comment]
is it possible to fix it by yourself or do you need to patch an issue

**Comment by CorgiTaco** [comment]
you'll need to fix it

**Comment by CorgiTaco** [comment]
basically: the server + client have different mods/mod versions of x mod(s)

**Comment by ghost** [comment]
i'm playing only on singleplayer right now, but i think its my fault, because after update the launcher + frapi, i dont delete older release files

**Comment by ghost** [comment]
Oh, my mistake , i show dimension instead of biomes. all fine, load clean version without anything and problem still appears.

heres logs: https://paste.ee/p/V7eZZ

can you look into it in free time? I would be grateful

**Comment by ghost** [comment]
<html>
<body>
if anyone have the same problem on 1.16.5, just downgrade ferritecore 

from: ferritecore-2.1.0-fabric.jar | 107.33 KB | Oct 9, 2021 | 1.16.5+1 | |  
-- | -- | -- | -- | -- | --
to: ferritecore-2.0.7-fabric.jar | 100.76 KB | Aug 23, 2021 | 1.16.5+1 |  |  
</body>
</html>
