### ISSUE TITLE
[Request]: Add option to disable sythian stalk block in blast furnace to produce gold nuggets in config.

### ISSUE THREAD

**Issue by ArmageddonX430** [CorgiTaco/BYG#585]
### Mod Version

1.3.5

### Mod Loader

Forge

### Mod Loader Version

36.2.0

### What happened?

Would be nice to have the option to disable this right from the config.

### latest.log

Might already be in there, I could be blind.

**Comment by CorgiTaco** [comment]
Use datapacks to disable it. The file you're looking for it `gold_buggets_from_sythian_stalk.json` 

full datapack path to it is here: https://github.com/AOCAWOL/BYG/blob/49107f9b2e5f07f2d991ca8f3d058d63bba670e5/Common/src/main/resources/data/byg/recipes/gold_nuggets_from_sythian_stalk.json
