### ISSUE TITLE
[Bug]: nether biomes do not generate

### ISSUE THREAD

**Issue by PercyJames** [CorgiTaco/BYG#587]
### Mod Version

1.3.5

### Mod Loader

Forge

### Mod Loader Version

36.2.4

### What happened?

ok so, I went to the nether trying to find your biomes. I have two other biome mods that effect the nether. biomes o' plenty and nether expansion. neither the nether expansion biomes or your biomes generate. only BOP.

### latest.log

[latest.log](https://github.com/CorgiTaco/BYG/files/7403954/latest.log)

**Comment by LunardH** [comment]
Probably cuz BOP is the one mod taking control of the nether gen in your case and i dont think you can have both byg and bop generating its either one or the other

**Comment by ObjektivC** [comment]
Set the `use-bop-nether` value of BoP's config to `false`

**Comment by LunardH** [comment]
@C-Slash Sir, would you know why my nether is showing me a message "WAITING FOR SERVER"? Was just trying to stack a bunch of mods and when i was testing the pack had this error, already tried everything i could w/without optifine, byg, bop and some other performance mods

**Comment by ObjektivC** [comment]
> @C-Slash Sir, would you know why my nether is showing me a message "WAITING FOR SERVER"? Was just trying to stack a bunch of mods and when i was testing the pack had this error, already tried everything i could w/without optifine, byg, bop and some other performance mods

A log would be helpful for that, and also probably belongs somewhere other than this issue

**Comment by LunardH** [comment]
> > @C-Slash Sir, would you know why my nether is showing me a message "WAITING FOR SERVER"? Was just trying to stack a bunch of mods and when i was testing the pack had this error, already tried everything i could w/without optifine, byg, bop and some other performance mods
> 
> A log would be helpful for that, and also probably belongs somewhere other than this issue

Ye, IK and i didnt wait to see if this crash generates a log it just freezes my game and it stops ticking i just finalize the process in the task manager everytime my game freezes

**Comment by PercyJames** [comment]
> Set the `use-bop-nether` value of BoP's config to `false`

guess i'll generate all the BOP nether biomes a few times before switching over

**Comment by PercyJames** [comment]
just had an idea: is there a way to add the BOP biomes, the BYG biomes, and the biomes from a few mods into one list for the nether to use to generate its biomes or is that not how it works?
