### ISSUE TITLE
[Bug]: conflict with Railcraft

### ISSUE THREAD

**Issue by ym1025** [CorgiTaco/BYG#588]
### Mod Version

1.7.1

### Mod Loader

Forge

### Mod Loader Version

14.23.5.2855

### What happened?

When putting wooden gates on the inventory, the game was crashed and I couldn't join the world again.
Uninstalling Railcraft is way to solve this problem.
crash-report: [crash-2021-10-24_22.00.39-server.txt](https://github.com/CorgiTaco/BYG/files/7404680/crash-2021-10-24_22.00.39-server.txt)

### latest.log

[latest.log](https://github.com/CorgiTaco/BYG/files/7404684/latest.log)

**Comment by CorgiTaco** [comment]
BYG is made with MCreator in 1.12. As result of this, leaves don't decay, and other obvious and painful bugs exist. We recommend you use our latest version for the best experience!
