### ISSUE TITLE
[1.16.1 Forge] - growth aura near BYG nylium crashes game

### ISSUE THREAD

**Issue by bessiq** [CorgiTaco/BYG#59]
Forge: 32.0.107
BYG: 1.0.15
Crash log: https://hatebin.com/rendfbvgjb

Heyo,

So, a "loot bag" mod called Mystic Tools has the chance to drop shovels with a growth aura effect, and whenever one of these shovels are in a player's inventory, it intermittently ticks any growables nearby - e.g. crops, grass, vanilla nylium blocks. Whenever you have this aura and approach BYG nylium blocks (embur or sythian), the game crashes. I haven't tested any other BYG blocks like meadow grass or overgrown stone, but not sure if those can grow stuff.

This may be something I need to report to the Mystic Tools author, but since it doesn't crash near vanilla blocks (at least the ones I tested), I thought I'd report here first. Let me know if you want more info. Thanks!

**Comment by CorgiTaco** [comment]
It's a casting error

**Comment by CorgiTaco** [comment]
Gonna close this. if the issue persists in both mods in 1.16.2 I'll look into it but I do believe this is an issue on their end
