### ISSUE TITLE
How to disable BYG nether and BYG end ?

### ISSUE THREAD

**Issue by TheZironix** [CorgiTaco/BYG#591]
**Mod Version**
1.2.9

**Mod Loader**
Forge

**Mod Loader Version**
36.2.8

I am doing a modpack, and I have enough of those biomes that are already in the nether and in the end. I've tried many different ways to disable BYG end and BYG nether, but nothing works (at least with nether).
I am also using the addon "All The Biomes You'll Go" version 1.1.0

**Comment by CorgiTaco** [comment]
If our config doesnt work, another mod has taken control of the nether, use their config
