### ISSUE TITLE
[Bug]: Server crash on nether generation

### ISSUE THREAD

**Issue by TheYoloPanda** [CorgiTaco/BYG#592]
### Mod Version

1.3.5

### Mod Loader

Forge

### Mod Loader Version

36.2.8

### What happened?

Every time I try to join the nether the game crashes.

### latest.log

https://wklej.spigot.pl/#/bAC5QO29i2OOJk95Dkwu-bFjGvJKklhfwbyf8i_h9NCaJw

**Comment by NighthowlerStudios** [comment]
you must have roadrunner and forge 36.2.22 installed.  downgrade roadrunner to 1.3 to play
