### ISSUE TITLE
[Bug]: Travertine blocks don't have any recipes

### ISSUE THREAD

**Issue by CobaltRogue1998** [CorgiTaco/BYG#593]
### Mod Version

1.3.5

### Mod Loader

Forge

### Mod Loader Version

36.2.0

### What happened?

Travertine blocks don't have any recipes

### latest.log

https://gist.github.com/CobaltRogue1998/f472981dcf069648cf54f491a908eefd

**Comment by Toma400** [comment]
Same, it's kinda annoying to see no possibility to get chiseled travertine. It's so nice block :<

**Comment by empirebuilder1** [comment]
For the record this was never actually fixed in 1.16, the 1.3.6 release from curseforge (Oct 9, 2022) still contains no recipes for any travertine blocks.
