### ISSUE TITLE
[Bug]: Crash when using Roadrunner

### ISSUE THREAD

**Issue by Krampus69** [CorgiTaco/BYG#594]
### Mod Version

1.16.5

### Mod Loader

Forge

### Mod Loader Version

36.2.4

### What happened?

Hello,
Using Roadrunner with Forge ByG and loading chunks makes crashes happen.
[crash-2021-11-01_23.03.01-server.txt](https://github.com/CorgiTaco/BYG/files/7456396/crash-2021-11-01_23.03.01-server.txt)
[crash-2021-11-01_22.30.47-server.txt](https://github.com/CorgiTaco/BYG/files/7456397/crash-2021-11-01_22.30.47-server.txt)

### latest.log

[latest.log](https://github.com/CorgiTaco/BYG/files/7456401/latest.log)

**Comment by Krampus69** [comment]
Okay another crash occured but I had removed Roadrunner before so maybe it's something else then...

[crash-2021-11-01_23.57.54-server.txt](https://github.com/CorgiTaco/BYG/files/7456604/crash-2021-11-01_23.57.54-server.txt)

**Comment by NighthowlerStudios** [comment]
you must have roadrunner installed.  downgrade it to 1.3 to play
