### ISSUE TITLE
[Bug] Crash When Generating Nether Chunks on Server

### ISSUE THREAD

**Issue by Pyte66** [CorgiTaco/BYG#595]
**Mod Version**

1.3.5

**Mod Loader**

Forge

**Mod Loader Version**

36.2.0

**What happened?**

Ran into crashes when both generating the nether for the first time and when copying over a world with an already generated nether. The nether works fine in singleplayer; biomes load and immersive portals generate the nether when lit. When on the server though (8G allocated and watchdog extended to get an accurate crash report) the nether is unreachable either by pre-made portals in a copied-over singleplayer world or by lighting new portals on the server.

The same issue happens regardless of whether immersive portals is present, and due to the nether working in singleplayer with all the same mods i don't think it's a mod incompatibility.

Lastly I've had to switch to Java 15 (openjdk) and I often witch between 15 and 17 for my modded and vanilla 1.17 servers, so maybe it has something to do with Java version and I should be running the server on openjdk  8 or 9?

Have had success disabling the byg nether generation but the end also causes the same problems and one of the main reasons this mod was chosen for the server was the unique nether biomes.

**latest.log**
[latest.log](https://github.com/CorgiTaco/BYG/files/7465663/latest.log)

**Crash-Report**
[crash-2021-11-03_16.23.01-server.txt](https://github.com/CorgiTaco/BYG/files/7465680/crash-2021-11-03_16.23.01-server.txt)

**Comment by JustACoolDude** [comment]
Pretty much having the same problem with crashing upon nether generation, except I'm using Forge version 36.2.8.

**Comment by JustACoolDude** [comment]
Using Forge Version 36.2.9 now, the problem still exists.
Not sure if this helps, but I tried adding Terraforged; it's possible to go into the Nether without crashing using the Terraforged world type, but this results in the biomes BYG adds become seemingly nonexistent.

**Comment by Pyte66** [comment]
I've had some success using my singleplayer and the chunk pregenerator mod to pre-generate the nether and end. The only problem is loading new chunks still crashes. Also I had to sit through loading 96 squared chunks to get three whole region files filled out. Definitely not sustainable if we want to continue exploring on the server.

**Comment by JustACoolDude** [comment]
I had the Stalwart Dungeons mod installed, and disabling it seemed to fix the problem. Not sure if you've also got Stalwart Dungeons, but hopefully that might help.

**Comment by craftish37** [comment]
Hello sir, i know it's been a month and a half, but could you give us your modlist ? That can help other members of the community to try to find a solution to this problem (that I encounter too)

I'm pretty sure this is a mod conflict and so we can quickly solve it, so please answer the fastest you can (:

(Here is mine but it's kinda long x'D)
https://curseforge.com/minecraft/modpacks/chococraft

**Comment by Pyte66** [comment]
https://github.com/Pyte66/Modlist-1/blob/main/Witchery%20for%20Nic%20(No%20Chunk%20Pregenerator).zip Here's the curseforge profile that has a modlist.html, I take Chunk Pre-generator out when putting the world up on the server. We haven't played much as Christmas is approaching so I've no idea if updating the mods would solve the overload when loading new chunks in non-overworld dimensions.

**Comment by craftish37** [comment]
Welp, after maaaaaaaany tries, I used the binary search to find out that it's a mdo conflict, in my case it's with forbidden & arcanus

Because I think it's more a forbidden & arcanus bug, I'll report it on their github
Try by your side the binary search to find the problematic mod too :
![2951 1490520804](https://user-images.githubusercontent.com/63811617/147130499-29e61921-ddba-435c-afb1-3eeca304331f.gif)




https://github.com/stal111/Forbidden-Arcanus/issues/216#issue-1087032312

**Comment by Pyte66** [comment]
After updating the mods that needed updating (Architectuary API, Blood Magic, Caelus API, Chisel and Bits, CodeChicken Lib, Controlling, Corail Tombstone, Create, Cucumber Library, FastFurnace, Fast Workbench, Flywheel and GeckoLib) new chunks load fine in the nether and end so they are the most likely candidates for causing this (I don't think it was a mod conflict, per se, just that too many mods were trying to optimise the generation of nether and end chunks).
