### ISSUE TITLE
[Bug]: TerraForged and BYG

### ISSUE THREAD

**Issue by EvolBat** [CorgiTaco/BYG#599]
### Mod Version

1.3.5

### Mod Loader

Forge

### Mod Loader Version

36.2.8

### What happened?

TerraForged and BYG ,  Terrain generation bug . 

![image](https://user-images.githubusercontent.com/71535161/140910302-63857fd0-2fc3-422d-a29b-3ffd2e484216.png)

### latest.log

[Uploading latest.log…]()

**Comment by CorgiTaco** [comment]
disable canyon edge in the terraforged config
