### ISSUE TITLE
[Bug]: Crash loop when generating nether chunks

### ISSUE THREAD

**Issue by ghost** [CorgiTaco/BYG#601]
### Mod Version

1.3.5

### Mod Loader

Forge

### Mod Loader Version

36.2.20

### What happened?

Some chunks in the nether seem to cause a crash when generating. I am sometimes able to go to the nether, but encounter the crash after moving a bit and generating chunks. Some other times, the crash happens instantly when entering the nether. Coming back to the world is impossible as the crash happens again.

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/7709465/latest.log)

**Comment by NighthowlerStudios** [comment]
downgrade roadrunner to 1.3 in order to play.
