### ISSUE TITLE
[Enhancement] Biome Tags for Fabric

### ISSUE THREAD

**Issue by itsmeow** [CorgiTaco/BYG#604]
Fabric has no biome dictionary, however there are biome tags. If BYG could include biome tags in the `c` domain, that would allow other mods to hook into BYG biomes more easily for things such as entity spawning on Fabric.

For example, my mod, Better Animals Plus, makes extensive use of the forge BiomeDict to decide spawn biomes, but on Fabric simply guesses tags from a few attributes.

If BYG included biome tags named after forge's tags in the c domain, that would improve interoperability on Fabric greatly.

See `TagFactory` for biome tags on Fabric.

**Comment by CorgiTaco** [comment]
Feel free to PR these, but unfortunately we're not adding anything else on 1.16
