### ISSUE TITLE
[Bug]: Pendorite and Tamrlite hoes aren't crafted correctly

### ISSUE THREAD

**Issue by InfectedGriffon** [CorgiTaco/BYG#606]
### Mod Version

1.12.2

### Mod Loader

Fabric

### Mod Loader Version

14.23.5.2860

### What happened?

![2021-12-28_23 21 33](https://user-images.githubusercontent.com/79546684/147627174-1ced0245-5efd-4c3f-8525-04976c674a06.png)
![2021-12-28_23 21 30](https://user-images.githubusercontent.com/79546684/147627176-94392dc7-27a0-4477-bb37-10d803242f62.png)

These two hoes specifically are crafted in a square, unlike every other tool in this mod.

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/7787316/latest.log)

**Comment by CorgiTaco** [comment]
1.12 is unsupported

**Comment by uncertainluei** [comment]
why in the world is the version "fabric" if the only 1.12.2 version of byg is for forge?
