### ISSUE TITLE
[Bug]: BYG Transparency of certain blocks is broken

### ISSUE THREAD

**Issue by VIEWVIEWVIEW** [CorgiTaco/BYG#608]
### Mod Version

1.3.6

### Mod Loader

Forge

### Mod Loader Version

39.0.9

### What happened?

I'm using the [latest alpha](https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go/files/3590704) and so far all blocks seem to be working except certain transparent ones like trapdoors and plants. Other transparent blocks like leaves work as intended.

![https://i.imgur.com/wTMDgw8.png](https://i.imgur.com/wTMDgw8.png)  
![https://i.imgur.com/wTMDgw8.png](https://i.imgur.com/Qjf4b9R.png)
![https://i.imgur.com/Qe6isD0.png](https://i.imgur.com/Qe6isD0.png)

### latest.log

https://gist.github.com/VIEWVIEWVIEW/e34a67276453423417760a512727ae76

**Comment by VIEWVIEWVIEW** [comment]
Issue persists on byg-forge-1.18-1.3.7

**Comment by CorgiTaco** [comment]
Fixed
