### ISSUE TITLE
[Bug]: Startup Crash on 1.18.1 Forge

### ISSUE THREAD

**Issue by hypherionmc** [CorgiTaco/BYG#612]
### Mod Version

1.3.7

### Mod Loader

Forge

### Mod Loader Version

39.0.10

### What happened?

When launching the game it just crashes with an NPE

### latest.log

[crash-2022-01-05_21.18.20-client.txt](https://github.com/AOCAWOL/BYG/files/7817356/crash-2022-01-05_21.18.20-client.txt)

**Comment by IskallDoe** [comment]
I have the same problem in the same environment.

Crash report 
https://paste.ee/p/gxVQ5

**Comment by AdleyBro** [comment]
I solved it by updating Forge to 39.0.19

**Comment by MatrexsVigil** [comment]
I am also getting this error, despite updating to Forge 39.0.19 as well.  

https://pastebin.com/u6biaunj

**Comment by LunafeyLazuli** [comment]
Also having the same version with Forge 39.0.58 and mod version Oh The Biomes You'll Go-forge-1.18.1-1.3.5.6.jar

**Comment by mjiuyan** [comment]
I have same problem with Forge 39.0.55

**Comment by CorgiTaco** [comment]
Should be fixed in latest file for 1.18.1 or 1.18.2
