### ISSUE TITLE
[Bug]: 1.18 Startup Crash on Server & Client 

### ISSUE THREAD

**Issue by Toilet-Lord** [CorgiTaco/BYG#613]
### Mod Version

byg-fabric-1.18-1.3.7

### Mod Loader

Fabric

### Mod Loader Version

0.12.11

### What happened?

The Game crashes at startup

1. Installed mod in mods folder
2. Started Server/Client
3. Crashes with fabric log window

lmk if I can do anything <3

### latest.log

Here are both logs just in case

Server:
[latest.log](https://github.com/AOCAWOL/BYG/files/7819423/latest.log)

Client:
[latest.log](https://github.com/AOCAWOL/BYG/files/7819422/latest.log)

**Comment by ghost** [comment]
Same Issue

**Comment by inikishev** [comment]
also but I have different Error https://gist.github.com/idkman2021/572e30d658fb4d8e9498e0e658e04008

**Comment by CorgiTaco** [comment]
You are using a 1.16 BYG jar in 1.18 according to your log file. @Toilet-Man
