### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by codeRG7122** [CorgiTaco/BYG#615]
### Mod Version

1.18.1

### Mod Loader

Forge

### Mod Loader Version

39.0.10

### What happened?

the code is like falling apart like it keeps crashing and nothing is working tried deleting the mod and it worked
[2022-01-07-5.log.gz](https://github.com/AOCAWOL/BYG/files/7829027/2022-01-07-5.log.gz)

**Comment by codeRG7122** [comment]
idk

**Comment by CorgiTaco** [comment]
You are missing the dependency for another mod(godly vampirism) unrelated to byg.
```
net.minecraftforge.fml.ModLoadingException: Mod §egodly_vampirism§r requires §6vampirism§r §o1.8.0-alpha+20211221-2217 or above§r
§7Currently, §6vampirism§r§7 is §o1.8.0-alpha+20210102-1316
```
