### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by AdamByersDev** [CorgiTaco/BYG#616]
### Mod Version

1.7.1

### Mod Loader

Forge

### Mod Loader Version

14.23.5.2858

### What happened?

Leaves from this mod don't decay in any way. Not with fast leaf decay, or by natural decay. I need to manually break all of the leaves from the trees in this mod

Example:

tree with no logs![2022-01-08_00 59 22](https://user-images.githubusercontent.com/25088097/148633474-43ce843a-afc9-4e25-8041-7181c8f5ade6.png)

tree not decaying![2022-01-08_00 59 35](https://user-images.githubusercontent.com/25088097/148633475-6879b3ff-233e-4c7d-8e10-4c7b5d888c9d.png)

tree not decaying at 3000 randomtickspeed![2022-01-08_00 59 54](https://user-images.githubusercontent.com/25088097/148633476-d2a1aae8-e5f2-4996-850b-4a169a8ee08a.png)
.

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/7832641/latest.log)

**Comment by CorgiTaco** [comment]
1.12 is unsupported
