### ISSUE TITLE
[Enhancement] Add signs for each of the wood type

### ISSUE THREAD

**Issue by Kitteh6660** [CorgiTaco/BYG#619]
Currently, the mod is missing signs and I think it will be easy to implement. In fact, it actually is.

Since vanilla has signs for each of the wood type, it would make sense that BYG gets the signs.

You don't really need any fancy network packet stuff, as the block entities can extend the base signs.

For BYG sign BlockEntity class in 1.18.1, only need to override getType(): 
```Java
	@Override
	public BlockEntityType<?> getType() {
		return BYGBlockEntities.BYG_SIGN;
	}
```
(In 1.16.5, this is TileEntityType)

As for wall and standing signs, the class files only merely need to extend the base sign block classes, and override one function which is newBlockEntity. You can get by fine with only SignItem unless you plan to incorporate signs made from fireproof wood then in such case, you can make BYGSignItem.

Granted, assets for sign items and blocks will still need to be created alongside the recipe but it's not too difficult. You also should ensure that sign blocks are properly tagged in #minecraft:signs too.

You will do need renderer for the mod signs that will apply the mod wood type textures, however.

**Comment by CorgiTaco** [comment]
Done in 1.19.2 at the time of writing, option will be available in 1.18 soon
