### ISSUE TITLE
[Bug]: Some modded ores not generating in BYG biomes !

### ISSUE THREAD

**Issue by Chuunkyz** [CorgiTaco/BYG#623]
### Mod Version

1.18.1, 1.3.5.6

### Mod Loader

Fabric

### Mod Loader Version

0.12.12

### What happened?

Modded ores from Tech Reborn and Modern Industrialization are not generating in my BYG biomes
however ores from AE2, Industrial Revolution or Gobber2 are generating, and modded features in general like rocks and crystals seem to work as well.

### latest.log

nothing in the logs

**Comment by CorgiTaco** [comment]
That is the duty of said mods to add their ores, not BYG

**Comment by Chuunkyz** [comment]
okay, so every ore not using biome categories isn't generating in BYG biomes. this might be an issue with terrablender but you can't tell that to all these mods... because half of the mods that add ores are not compatible with byg now...

**Comment by superninjakiwi** [comment]
If it happens with other terrablender mods (e.g. BoP) it's a terrablender problem and should be reported to them, not here. If it doesn't happen to other terrablender mods, it's a BYG problem. Nobody involved should have to be special-casing their mod for others, though.

**Comment by Chuunkyz** [comment]
https://github.com/Glitchfiend/TerraBlender/issues/25
seems like it's an issue with byg (and the other mod using terrablender as well)
