### ISSUE TITLE
[Bug]: Bookshelf Untextured w/ Silent Gear

### ISSUE THREAD

**Issue by GamerGaven** [CorgiTaco/BYG#624]
### Mod Version

1.3.5.7

### Mod Loader

Forge

### Mod Loader Version

39.0.57

### What happened?

I updated the mod from 1.3.5.4 to the current release and saw that the bookshelf is untextured (this may be with other blocks as well but I haven't thoroughly tested that). What makes this odd is that it seems to be caused by something between this mod and Silent Gear. I tested this with multiple other versions of both mods and also different versions of forge and from what I can tell is that this started in 1.3.5.5 of this mod regardless of what version of Silent Gear and Forge I used. Not a major bug by the looks of it but thought I'd share it because it can be a bit jarring to look at. If this happens to be a bug on Silent Gears part I'll report it to their Github when I can.
![2022-01-23_01 27 52](https://user-images.githubusercontent.com/83141599/150672396-2049911c-dc78-450a-baa6-2c4d009213b7.png)

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/7920177/latest.log)

**Comment by CorgiTaco** [comment]
known issue in 1.16

**Comment by KatoNamus** [comment]
Getting the same issue but with farmland as well as bookshelves.

Minecraft 1.18.1
Forge 39.1.2
Oh The Biomes You'll Go-forge-1.18.1-1.3.5.13.jar
silent-gear-1.18.1-2.9.1.jar

**Comment by DiscoDude96** [comment]
this is kind of related exepct my bookshelves are invisible and when I try to place them using the /setblock command, the code seems to think it doesn't exist.

**Comment by JT122406** [comment]
1.16 isn't supported
