### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Klouver-github** [CorgiTaco/BYG#625]
### Mod Version

1.18.1-1.3.5.7

### Mod Loader

Forge

### Mod Loader Version

1.18.1-39.0.59

### What happened?

I tried making a new world then it crashed due to BYG wood tickled Minecraft then crashed? BYG kind of sus for tickling the crash report though, 

### latest.log

https://paste.gg/p/anonymous/9dc9a29aa4cd444a987b0f0e93924c48

**Comment by CorgiTaco** [comment]
Another mod adding world generation is doing this, I can't recreate this crash with byg alone find the culprit and report it to them
