### ISSUE TITLE
[Bug]: BYG Trees Won't Grow

### ISSUE THREAD

**Issue by morgansmnm** [CorgiTaco/BYG#626]
### Mod Version

1.18.1

### Mod Loader

Fabric

### Mod Loader Version

0.46.1

### What happened?

BYG trees will not grow from saplings. I have tried placing Pink Cherry, Jacaranda (Indigo and Normal), and Fir saplings in orders from 1x1 to 2x2 to even 3x3 in open plains to attempt to grow them. When this didn't work, I attempted to shower the trees in bonemeal in creative mode and the trees refused to grow. When I switched the trees out for vanilla ones, they grew fine.  I even attempted changing out the types of dirt the trees were growing on to see if that would make a difference. 

![image](https://user-images.githubusercontent.com/34687722/150700085-d19212b8-f791-4625-9f7b-c17eaf5c4421.png)

![image](https://user-images.githubusercontent.com/34687722/150700172-4724dd52-2459-44c9-b16f-23b2df0b0e09.png)

![image](https://user-images.githubusercontent.com/34687722/150700216-71effd6e-b63c-4638-a987-1e25e7ed594b.png)

I don't know if this bug has anything to do with the former, but only planks that look like Fir or Maple will make their corresponding crafting benches, with an exception for the Rainbow Planks. All other crafting items craft correctly with their specified woods.

![Screenshot 2022-01-23 171120](https://user-images.githubusercontent.com/34687722/150699964-4d226765-1f8d-4955-a309-739b09bfdb01.png)

![Screenshot 2022-01-23 171120](https://user-images.githubusercontent.com/34687722/150699999-237c135a-6fe8-4aba-a261-7ebc591a0b26.png)

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/7921557/latest.log)

**Comment by CorgiTaco** [comment]
Trees from saplings are not yet implemented in 1.18

**Comment by AndyMFA** [comment]
I hope this is implemented soon as this is a BIG miss. Loving this mod. Awesome. The trees make the vanilla ones look pathetic in comparison. 👍

**Comment by HakuTono** [comment]
Is this likely to be changed in the future?

**Comment by CorgiTaco** [comment]
next update

**Comment by AndyMFA** [comment]
> next update

Downloaded the update earlier on. THANK YOU. 
There is one little niggle though. So far on our game we are still unable to grow Cika and Cyprus saplings. Yet the Fir ones and several others do grow!?
Just thought I'd let you know. 
Keep up the great work!
LOVE IT.

**Comment by CorgiTaco** [comment]
> > next update
> 
> Downloaded the update earlier on. THANK YOU. 
> There is one little niggle though. So far on our game we are still unable to grow Cika and Cyprus saplings. Yet the Fir ones and several others do grow!?
> Just thought I'd let you know. 
> Keep up the great work!
> LOVE IT.

Saplings like baobabs, redwood, willows, use unique shapes not found in vanilla, to see those, like in the byg-sapling-patterns config, if you'd rather stick with the vanilla format for trees, you can change that in the config
