### ISSUE TITLE
[Bug]: BYG causes Amplified Nether to generate as vanilla nether.

### ISSUE THREAD

**Issue by TheRobberPanda** [CorgiTaco/BYG#628]
### Mod Version

1.3.5.6

### Mod Loader

Fabric

### Mod Loader Version

0.12.12-1.18.1

### What happened?

bug arises when BYG is installed together with Amplified nether, BYG somehow overrides amplified nether, then vanilla nether generates instead.

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/7946102/latest.log)
I doubt this will help, please contact me if you need more information regarding the issue.

**Comment by CorgiTaco** [comment]
byg does not touch nether related stuff in the current version
