### ISSUE TITLE
[Bug]: My server's console is spammed with BYG null entries

### ISSUE THREAD

**Issue by PJRamaglia** [CorgiTaco/BYG#629]
### Mod Version

Oh+The+Biomes+You'll+Go-forge-1.18.1-1.3.5.7

### Mod Loader

Forge

### Mod Loader Version

forge-1.18.1-39.0.63-installer

### What happened?

Whenever I launch my server, my console gets spammed with hundreds of "[modloading-worker-0/ERROR]: Block "byg:XXXXX" was null in the block registry. Using value from BYG's tracked registered blocks..." entries where XXXXX is a specific BYG block.

Please let me know if you need any other logs uploaded.

### latest.log

https://gist.github.com/PJRamaglia/94ff8888d906452269abaa4531a54ab5

**Comment by CorgiTaco** [comment]
Aware and fixed already (not yet released)

**Comment by PJRamaglia** [comment]
Ah, gotcha.  Thank you for the quick reply!  :)
