### ISSUE TITLE
[Bug]: BYG Mixin errors upon server launch

### ISSUE THREAD

**Issue by PJRamaglia** [CorgiTaco/BYG#630]
### Mod Version

Oh+The+Biomes+You'll+Go-forge-1.18.1-1.3.5.8

### Mod Loader

Forge

### Mod Loader Version

forge-1.18.1-39.0.63

### What happened?

Lines 42 - 53 of my server's latest.log show four "[main/FATAL]" messages and eight "[main/WARN]" messages.  It appears these BYG errors are referring to the below classes?

• byg.mixins.json:access.ClientLevelAccess
• byg.mixins.json:access.ItemBlockRenderTypeAccess
• byg.mixins.json:client.MixinBlockColors
• byg.mixins.json:client.MixinItemColors

### latest.log

https://gist.github.com/PJRamaglia/c6c85c118a8b34bab1615ac98440dee9

**Comment by CorgiTaco** [comment]
expect this fix in 1.3.5.9

**Comment by PJRamaglia** [comment]
I'll close this report out when I download and install 1.3.5.9, that is, if you don't beat me to it first, lol

**Comment by PJRamaglia** [comment]
lmao....nevermind xD
