### ISSUE TITLE
Using no other mods and Nether is not spawning your biomes on fabric 1.18.1

### ISSUE THREAD

**Issue by ThePetePandaPablo** [CorgiTaco/BYG#631]
__**Mod conflict? If so, please clarify which mod is conflicting, if not skip this.**__
no mods but this one

__**API/Modloader**__
Fabric

__**Describe the bug**__
Literally no biomes are spawning in nether 

__**To Reproduce**__
Go to the nether 

**Expected behavior**
the nether biomes

**Comment by SpareUranium** [comment]
Nether and end biomes aren't  in 1.18 yet this really isn't a bug

**Comment by ThePetePandaPablo** [comment]
Oh that explains it then.
