### ISSUE TITLE
Mod not recognized

### ISSUE THREAD

**Issue by Wachecheiro** [CorgiTaco/BYG#632]
Hello, version 1.1.8 works fine (for minecraft 1.16.5).
Version 1.1.9 to 1.3.5 simply minecraft does not recognize the mod, it is as if it was not placed in the mods folder, (it does not appear in the mod menu screen).

I tried to remove all the mods to rule out any incompatibility, just leave fabric api, mod menu and this

**Comment by CorgiTaco** [comment]
This is more than likely caused by some incorrect installation or the wrong file, make sure you're using the file found here: https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go-fabric/files/3484192
