### ISSUE TITLE
More diversity for the forgotten forest

### ISSUE THREAD

**Issue by StockiesLad** [CorgiTaco/BYG#635]
Can I just say, I love the forgotten forest? I LOVE IT! But it's too common for how cool it looks. I want it to be one of those things where it's really rare and you run in circles when you finally find it. But there's another problem...

Why are there only 2 colours? Imagine if there were a whole spectrum of colours. Orange tree, red tree, pink tree like the sakura ones.

These new variants could be split into different types of forgotten forests.  Fire Forest, for red, orange, and yellow. And normal forgotten forest for green, blue,  pink, and purple.

P.S: This is literally the best biome mod for the overworld. It's already amazing, I just think this will be cherry on top.

**Comment by CorgiTaco** [comment]
This biome will be undergoing a revamp, but adding more leaves/saplings just adds clutter and is unfortunately not on the menu
