### ISSUE TITLE
Trees Don't Grow

### ISSUE THREAD

**Issue by CeedyBoiii** [CorgiTaco/BYG#636]
__**API/Modloader**__
Forge

__**Describe the bug**__
Saplings do not grow at all. Bonemeal does not work either. All saplings in BYG alone are affected by this.

__**To Reproduce**__
Attempt to grow a tree using saplings and bonemeal, or waiting for it to naturally grow.

__**Expected behavior**__
The sapling was expected to grow into a tree, but it did not.

**Comment by CorgiTaco** [comment]
Ensure you are using the latest version of byg. Duplicate of #626

**Comment by CeedyBoiii** [comment]
I am for sure using the newest version, 1.3.5.9 for Forge version 1.18.1. (The rest of this mod is absolutely stellar, by the way.)

**Comment by CorgiTaco** [comment]
@CeedyBoiii what sapling r  u trying to do

**Comment by CeedyBoiii** [comment]
all of them, really. I have a world for charting out block pallets and foliage. I've tried all the sapling patterns as well

**Comment by CorgiTaco** [comment]
please join our discord: https://discord.gg/knpP4243

**Comment by CeedyBoiii** [comment]
Just joined! my user is Aszellem.
