### ISSUE TITLE
Config not being used when other mods are present [Forge 1.16.5]

### ISSUE THREAD

**Issue by iiDogez** [CorgiTaco/BYG#639]
When Loading BYG with mods like infernal expansion or better end the config refuses to work. When I try turning "controlNether" to false in byg-world.toml with infernal expansion installed, BYG biomes will still spawn in the nether, turning it to false only worked when infernal expansion was removed. This whole setup was also true with the end and the better end mod, BYG end biomes would spawn even when controlEnd was turned to false with better end currently installed.

**Comment by CorgiTaco** [comment]
Use their configs for the nether as our config loses control/becomes useless

**Comment by iiDogez** [comment]
the config for infernal expansion has nothing that relates to the spawning of its biome, so I have no clue how that would help, even if it did it shouldnt affect the spawning of a biome from another mod like that

**Comment by CorgiTaco** [comment]
Please join the discord: https://discord.gg/knpP4243

**Comment by iiDogez** [comment]
I just joined it. Would deleting the biomes I dont want spawning in the weight configs fix the problem?
