### ISSUE TITLE
Able to disable biome generation? (Suggestion)

### ISSUE THREAD

**Issue by Atenberus** [CorgiTaco/BYG#64]
Hello! I'm curious if there is a way to disable the spawning of the moded biomes per world? I love all the blocks that BYG adds, but when I'm attempting to do a creative build world, a lot of the biomes can easily get in the way of building. If not, i think it would be a neat thing to add if possible! (I'm sorry if this is akward its 3am and I'm running on root beer.)

**Comment by CorgiTaco** [comment]
Byg-weight config on both forge/fabric. Set the weight to 0 for each biome you want disabled
