### ISSUE TITLE
Game not started

### ISSUE THREAD

**Issue by imcasper** [CorgiTaco/BYG#641]
PS:
fabric-api-0.42.0+1.16.jar

__**Mod conflict? If so, please clarify which mod is conflicting, if not skip this.**__
byg-version: 1.3.5 (and 1.3.4 too)

__**API/Modloader**__
Fabric

__**Describe the bug**__
Exception after launch game client

__**To Reproduce**__
Launch game client.

**Expected behavior**
Game client launched.

**Logs**
Use: https://paste.ee/ and paste the links. if log is huge please upload those
Please provide:
[crash-2022-02-14_23.01.27-client.txt](https://github.com/AOCAWOL/BYG/files/8063601/crash-2022-02-14_23.01.27-client.txt)

**Comment by CorgiTaco** [comment]
reset your byg configs in `config/byg`
