### ISSUE TITLE
Error in currently selected data packs w/ Terrablender

### ISSUE THREAD

**Issue by trentosser** [CorgiTaco/BYG#642]
**2. Please test BYG on its own to confirm whether or not this is a mod conflict**
not a mod conflict 

__**API/Modloader**__
Forge
__**Describe the bug**__
When loading a world or creating a new world the game gives me the error "error in currently selected datapacks prevented the world from loading 

__**To Reproduce**__
Please provide step by step instructions
simply load a world or create a new world

**Expected behavior**

**Additional context**
The error doesnt seem to occur when using the old overworld-biomes.json 

**Logs**
Crashlog - 
Debug.log - 
Latest.log - https://paste.ee/p/7bzUy

**Comment by Sunconure11** [comment]
I'm encountering this too.

**Comment by Sunconure11** [comment]
https://pastebin.com/WDRKQ0pK @AOCAWOL

**Comment by CorgiTaco** [comment]
Caused by: https://github.com/Glitchfiend/TerraBlender/issues/38

**Comment by CorgiTaco** [comment]
Fixed by terrablendder https://github.com/Glitchfiend/TerraBlender/issues/38
