### ISSUE TITLE
Mod conflict with Terralith: Saplings don't grow in latest Alpha

### ISSUE THREAD

**Issue by jjac31415** [CorgiTaco/BYG#643]
**Before filling out this issue: **
**1. We only support the latest version of BYG on for Minor Bugs.**
**2. Please test BYG on its own to confirm whether or not this is a mod conflict.**

__**Mod conflict? If so, please clarify which mod is conflicting!**__
Terralith_v2.0.12_Fabric+Forge

__**API/Modloader**__
Fabric

__**Describe the bug**__
This is in the most recent 1.18.1 Alpha.
I was experimenting with the new sampling growth config.
If I run Terralith as well as BYG, Terralith interferes with the sapling growth in BYG.

I haven't tested all the saplings, but the only one I was able to grow was the small fir tree.

With only BYG installed, all saplings grow as expected.

__**To Reproduce**__
In creative, gave yourself saplings and bonemeal. Go to nearest plains biome to have plenty of space. Place the saplings down in the pattern designated by the config file for that sapling type. Spam with bonemeal.

**Expected behavior**
Saplings grow

**Screenshots/Videos**
NA

**Additional context**
Running the following config
Minecraft 1.18.1
fabric-loader-0.12.12-1.18.1
fabric-api-0.46.4+1.18
lithium-fabric-mc1.18.1-0.7.7
Oh+The+Biomes+You'll+Go-fabric-1.18.1-1.3.5.9
phosphor-fabric-mc1.18.x-0.8.1
sodium-fabric-mc1.18.1-0.4.0-alpha6+build.14
TerraBlender-fabric-1.18.1-1.1.0.73
Terralith_v2.0.12_Fabric+Forge

**Comment by CorgiTaco** [comment]
Terralith's fault

**Comment by jjac31415** [comment]
Okay. I just wanted to make you aware of the issue.

**Comment by CorgiTaco** [comment]
Keep it open so other users know :P

**Comment by catter1** [comment]
Terralith recently updated to 2.2.1, which removed its sapling regrow method. *IF* this happens to be the reason BYG saplings would not grow, they should now. Has not been tested, but telling people to update to 2.2.1 should fix this issue.

**Comment by Sunconure11** [comment]
Sorry to hijack this, but for both Terralith and Incendium, can you check for any incompatibility issues of any kind? I remember on 1.18.1 the mods acted really strange together.

Same deal with Better Nether and Better End, as they use their own dependency for applying biomes.

**Comment by pen-siv** [comment]
As someone who had the OP's issue, I can report that saplings grow after updating Terralith to v2.2.1a.

**Comment by rezzler** [comment]
does the v2.2.1a work on 1.18.1 tho? for me when i change the mod version i just dont get any terralith content anymore

**Comment by catter1** [comment]
No, Terralith 2.2.1a is for 1.18.2 only.
