### ISSUE TITLE
I need some help with building this from source

### ISSUE THREAD

**Issue by K0-RR** [CorgiTaco/BYG#644]
Hello, I wanted to test the latest changes but when I run `gradlew build` I got a failure. Next, I tried to build it via Github Actions to be sure it's not something with my environment but the error was the same. You can see it here:
https://github.com/RDKRACZ/BYG/runs/5249276298?check_suite_focus=true#step:4:428
If something more than the build command is needed in order to make the jar can you add the instructions?

Also, the readme says the mod requires Java 16 and it should be java 17.

**Comment by CorgiTaco** [comment]
in the relevant build.gradle's, add

```gradle
tasks.withType(Javadoc) {
    failOnError false
}
```
