### ISSUE TITLE
[Enhancement]: Configurable Vanilla Sapling Changes

### ISSUE THREAD

**Issue by Smibbix** [CorgiTaco/BYG#645]
It would be really nice if there was a way to disable the behavior that this mod adds to the vanilla Minecraft saplings where they often grow into extremely large variants of themselves or sometimes into a tree with a completely different leaf and sapling type. With this mod installed, vanilla saplings _constantly_ grow into extremely large and annoying to cut down trees and it can be very irritating to some players who just want to grow easily choppable trees for their wood, or just dislike that a mod is changing vanilla behavior. A config option that disabled this or allows the frequency of this occurring to be reduced would be very helpful.

**Comment by Yamato-Kazuki** [comment]
Just what I was looking for. I dug through all the configs in case it's already there, but had no luck. Really wanna +1 this, the weird/big tree shapes can get somewhat annoying and it would be awesome to have the option to turn it off.

**Comment by halvalla01** [comment]
Especially annoying on a skyblock, since it overrides blocks, so you end up with holes in your platform

**Comment by CorgiTaco** [comment]
Enhancements are now to be posted in our discussions tab, it's been moved [here](https://github.com/AOCAWOL/BYG/discussions/1179)!
