### ISSUE TITLE
[Bug]: End and Nether nylium blocks die when almost any block is placed on top

### ISSUE THREAD

**Issue by supermassimo** [CorgiTaco/BYG#646]
### Mod Version

1.3.5

### Mod Loader

Forge

### Mod Loader Version

36.2.23

### What happened?

Nylium blocks will die over time if any block is placed on them, even if they are not full blocks.
![image](https://user-images.githubusercontent.com/6750207/154869026-459110ec-57b5-468e-ba52-c1cd4bf796b2.png)

This is caused by the BYGNylium block class checking `canOcclude()` instead of checking the light transmittance level like vanilla nylium blocks.
Line of code responsable in `BYGNylium`:
```
        if (this.worldRegistryKey == World.END && world.getBlockState(pos.above()).canOcclude()) {
            world.setBlockAndUpdate(pos, this.dirtBlock.defaultBlockState());
        }
```
Line of code responsable for the correct behaviour in vanilla `NyliumBlock`:
```
      int i = LightEngine.getLightBlockInto(world, state, pos, blockstate, blockpos, Direction.UP, blockstate.getLightBlock(world, downPos));
      return i < world.getMaxLightLevel();
```

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/8105165/latest.log)

**Comment by CorgiTaco** [comment]
Fixed in 1.18.2
