### ISSUE TITLE
[Bug]: Server crashes when updating from 1.3.5.10 to 1.3.5.12 (1.18.1)

### ISSUE THREAD

**Issue by evhub** [CorgiTaco/BYG#649]
### Mod Version

1.3.5.12

### Mod Loader

Forge

### Mod Loader Version

39.0.85

### What happened?

When updating from 1.3.5.10 to 1.3.5.12, the server crashes when launching with the new version. See: https://gist.github.com/evhub/13fe6f773876e945017255277bfaf57e

### latest.log

https://gist.github.com/evhub/ef24bb6de44da393b712f6edd2051710

**Comment by CorgiTaco** [comment]
delete byg's end biomes config and relaunch the game
