### ISSUE TITLE
It seems from what i have seen online this mod is crashing my game

### ISSUE THREAD

**Issue by grandogarndo** [CorgiTaco/BYG#65]
https://pastebin.com/aFfDCMru

whenever I remove a mod it always ends up mentioning this one. I do have mekanism installed but when I remove it nothing changes.

**Comment by CorgiTaco** [comment]
Restart Your game as this is a forge sided issue. We no longer support 1.15.2.

**Comment by grandogarndo** [comment]
by restarting you mean... what? I installed the newest version of forge and reopened the launcher and nothing happened. do you know the problem or is it just not in your field?

**Comment by grandogarndo** [comment]
nevermind it seems the biome mod voyage was the problem
