### ISSUE TITLE
[Error]: byg crashing minecraft launcher

### ISSUE THREAD

**Issue by cvsmiz** [CorgiTaco/BYG#651]
### Mod Version

1.18.1

### Mod Loader

Fabric

### Mod Loader Version

0.13.3

### What happened?

When launching Minecraft launcher to play an error comes up saying the game crashed.

The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entry point stage 'main' due to errors, provided by 'byg'!
Exit Code: -1

not too sure what to do, any help would be appreciated 

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/8146003/latest.log)

**Comment by CorgiTaco** [comment]
this tells me nothing

**Comment by CorgiTaco** [comment]
submit the latest.log file in your game dir

**Comment by cvsmiz** [comment]
> submit the latest.log file in your game dir

ah my bad i removed the wrong thing, ill do that now

**Comment by CorgiTaco** [comment]
Reset your config files, if that doesn't work, update terrablender, else reinstall fabric loader/entire game instance
