### ISSUE TITLE
[Bug]: Crashing when creating new world

### ISSUE THREAD

**Issue by LuigiTP** [CorgiTaco/BYG#653]
### Mod Version

-forge-1.18.1-1.3.5.12.jar

### Mod Loader

Forge

### Mod Loader Version

39.0.88

### What happened?

I did isolate the mod (so only terrablender and Byg installed) and when i clicked singleplayer it crashed the game

[crash-2022-02-26_21.53.38-client.txt](https://github.com/AOCAWOL/BYG/files/8147591/crash-2022-02-26_21.53.38-client.txt)

i

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/8147587/latest.log)

**Comment by WordStormRose** [comment]
This also happens when trying to enter a previously-created world.

**Comment by trgted** [comment]
I have the same problem in 1.3.5.12 mod version and 39.1.0 forge version.

Versions 1.3.5.1 and 1.3.5.2 do not cause the problem

**Comment by cris2800** [comment]
Also happening to me. The game flashes to a "saving world..." screen and crashes as soon as I hit the create new world button.
(Using forge mod version 1.18.1-1.3.5.12 and forge loader version 1.18.1-forge-39.0.88)

**Comment by CorgiTaco** [comment]
Update terrablender or reset your end biome config and let it regenerate
