### ISSUE TITLE
[Bug]: the game crashes when entering map selection

### ISSUE THREAD

**Issue by PunkPun** [CorgiTaco/BYG#654]
### Mod Version

1.18.1-1.3.5.12

### Mod Loader

Forge

### Mod Loader Version

latest

### What happened?

When entering map selection with no maps made the game crashes. If there's at least 1 map the mod runs fine

### latest.log

[crash-2022-02-27_13.20.07-client.txt](https://github.com/AOCAWOL/BYG/files/8148558/crash-2022-02-27_13.20.07-client.txt)

**Comment by CorgiTaco** [comment]
Update terrablender
