### ISSUE TITLE
[Bug]: Game crashes in startup

### ISSUE THREAD

**Issue by Crazycatnya** [CorgiTaco/BYG#655]
### Mod Version

1.18.1-1.3.5.12

### Mod Loader

Fabric

### Mod Loader Version

0.13.3-1.18.1

### What happened?

added the mod (and its dependencies) and it crashes 

### latest.log

[crash-2022-02-27_16.50.22-client.txt](https://github.com/AOCAWOL/BYG/files/8149806/crash-2022-02-27_16.50.22-client.txt)

**Comment by CorgiTaco** [comment]
ddelete your end biomes config and let it regenerate
