### ISSUE TITLE
[Bug]: Incompatible with BetterEnd/BCLib for 1.18 so far

### ISSUE THREAD

**Issue by weegeeluigi** [CorgiTaco/BYG#657]
### Mod Version

1.3.5.12

### Mod Loader

Fabric

### Mod Loader Version

0.13.3

### What happened?

Using BetterEnd 1.0.2.1 and BCLib 1.3.4, and BYG is ignored and throws the warning the generator isn't being used despite being configured to be.  Also have nullscape 1.1 installed which works fine with better end, removed it to test and doesn't make a difference, only better end biomes load.  Been fiddling with NBT explorer to see if I can force something to happen and if it's a conflict problem, but can't get it to work.  The latest version of betterend/bclib uses a new generator so I'm not sure if the problem is their side with BCLib or better end.  No sure if it's a config problem, or which side has the issue.  BetterEnd is also not fully released for 1.18 yet, so I figured I bring this up now to iron the kinks out since both mods have been compatible for a while.  Maybe someone already knows the answer or it's being worked on, but I haven't found a post about it yet.

### latest.log

https://gist.github.com/weegeeluigi/eef1ef7b6447a54554686aa387990a75

**Comment by CorgiTaco** [comment]
You need to turn off Bclib's biome source fix config Option I imagine

**Comment by Chuunkyz** [comment]
no, you need tu turn off BYG's biome source and add the biomes into the bclib one

**Comment by weegeeluigi** [comment]
> no, you need tu turn off BYG's biome source and add the biomes into the bclib one

Already added the biomes into bclib's biome file and it didn't seem to matter.  Did you get it to work, what config options did you change?

EDIT: Seems I didn't do the bclib config properly, now it all generated.  It's a bit funky and sparse, but it worked but I suspect nullscape's shattering is doing that.  Just going to keep playing around with it.  Thanks for the help, my one regret is not finding BYG sooner.

**Comment by weegeeluigi** [comment]
Ok so anyone else who wants to fiddle around with both mods this early, you need to add all BYG end biomes to the bclib biomes config setup to make them available, then in the bclib generator config you need to enable addEndBiomesByCategory and set it to true.  Without enabling this it won't include the BYG biomes you put in the biomes config.

**Comment by megamindcult** [comment]
hi this might sound a bit stupid but i am new to servers and was setting up a 1.18.2 better end/BYG server as well but i don't exactly understand how to config or what the bclib generator is and all that stuff. how exactly do you go about config setup? sorry if i was meant to ask on a separate thing but i figured i would ask here since you seemed to have figured it out. any advice or direction would be much appreciated- again, sorry if i sound dumb asking lol i just cant find much information anywhere else

**Comment by Chuunkyz** [comment]
you have to add the byg biomes in the bclib config, and disable the byg source
you'll get more help on the bclib mods discord

**Comment by weegeeluigi** [comment]
BetterX team made it so bclib already has BYG compatibility in the latest versions, you only need to tell BYG to not be the source biome in it's configs.  Their discord has a FAQ on how to handle this, I would recommend you read it, get it working and then fiddle with the nether config in test worlds as I find the two together out of the box to be heavy on some biome types and my config is customized.
