### ISSUE TITLE
[Bug]: byg IllegalAccessError

### ISSUE THREAD

**Issue by SJY051** [CorgiTaco/BYG#658]
### Mod Version

1.18.1

### Mod Loader

Forge

### Mod Loader Version

Forge 39.0.88

### What happened?

try to enter singleplayer mode with no world present, the game crashes and the Minecraft launcher shows a log stating that some part of byg raised an IllegalAccessError. I am using a translator. Therefore, the description of the situation may not be accurate, so I will attach a screenshot.
![image](https://user-images.githubusercontent.com/68188784/156316970-16ec25c3-2ed7-4493-a762-aee6715c9b3b.png)

### latest.log

latest.log : [latest.log](https://github.com/AOCAWOL/BYG/files/8167625/latest.log)
crash log : [crash-2022-03-02_16.38.35-client.txt](https://github.com/AOCAWOL/BYG/files/8167630/crash-2022-03-02_16.38.35-client.txt)

**Comment by CorgiTaco** [comment]
upddate terrablender
