### ISSUE TITLE
[Bug]: java.lang.IllegalAccessError on server startup

### ISSUE THREAD

**Issue by Hell0HighDefo** [CorgiTaco/BYG#659]
### Mod Version

1.3.5.13

### Mod Loader

Fabric

### Mod Loader Version

0.1.3.2

### What happened?

When loading up the server, the server crashes with a java.lang.IllegalAccessError.
I assume this is due to an error with BCLib as right before it has the error, it mentions BCLib, but I don't know how to fix it.
Can I get some help?

### latest.log

Log: [latest.log](https://github.com/AOCAWOL/BYG/files/8178613/latest.log)
Crash Report: [crash-2022-03-03_08.21.10-server.txt](https://github.com/AOCAWOL/BYG/files/8178616/crash-2022-03-03_08.21.10-server.txt)

**Comment by TheSofas** [comment]
Seems to be an incompatibility between latest version and BCLib. Tried fixing this myself by disabling End and Nether Biomes in config and various other things, but nothing worked. Only managed to get it by reverting to 1.3.5.12, which has End biomes, but not the Nether. Corgi mentioned on discord that the 1.18.1 version will not be updated anymore, so this is unlikely to be fixed, unless someone finds a workaround.

**Comment by weegeeluigi** [comment]
Is the idea shifting to 1.18.2 or are things staying frozen until 1.19 drops?

**Comment by TheSofas** [comment]
From Corgi on discord: "I'd like to say that further development of 1.18.1 is stopped(the last file for 1.18.1 will be alpha) and we will be moving forward to 1.18.2."  However, the main issue with 1.18.2 is it breaks a ton of stuff, and Terrablender needs to update first before major progress can be made.

**Comment by CorgiTaco** [comment]
Fixed in 1.18.2
