### ISSUE TITLE
[Bug]: error when starting up 

### ISSUE THREAD

**Issue by Fintris** [CorgiTaco/BYG#660]
### Mod Version

1.18,1

### Mod Loader

Fabric

### Mod Loader Version

0.13.3

### What happened?

when adding byg and terrablender to mods folder, I am faced with an error and this crash report

### latest.log

[crash-2022-03-05_22.15.21-client.txt](https://github.com/AOCAWOL/BYG/files/8191893/crash-2022-03-05_22.15.21-client.txt)

**Comment by CorgiTaco** [comment]
this is an issue with sodium it seems, bot byg or terrablender
