### ISSUE TITLE
[Bug]: New versions of BYG will not load

### ISSUE THREAD

**Issue by LegoWoof** [CorgiTaco/BYG#662]
### Mod Version

1.3.5

### Mod Loader

Fabric

### Mod Loader Version

0.13.3

### What happened?

I created a server with BYG a while back and it worked fine. Upon reinstalling the mods in an attempt to fix a problem (unrelated to byg) with the server, I was met with this message. 
![Le Problem Has Arrived](https://user-images.githubusercontent.com/87788626/157119292-74f5e495-ba2c-43ed-bf7e-31bcad3015c5.PNG)

I tried downgrading to the version I used previously (1.1.8) and was met with the same message-- so I'm not entirely sure if the problem is version-based. It should be noted I also used an older version of the mod loader before this issue began to arise. 

I thought it might be a problem with the server, so I downloaded the world and reloaded it in singleplayer. Upon doing so, an entire biome I was in (along with any structures built with materials from the mod) had disappeared.
![2022-03-07_13 15 51](https://user-images.githubusercontent.com/87788626/157119241-b273585d-121a-4710-9b56-804316b919cc.png)

I have a backup of the world, so I wont need to worry about losing anything, but it's still concerning nonetheless.

There were other mods installed along with this and if I will list them if need be. I can confirm that the byg mod WAS installed though.
![image](https://user-images.githubusercontent.com/87788626/157119587-10a19fdf-c05f-43cf-9b9e-0aa5f8668850.png)

Any and all help is appreciated. Thank you.

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/8200942/latest.log)

**Comment by Boolobo** [comment]
SMALL UPDATE: Upon loading the world with all of the old mods I used previously in singleplayer, it loaded fine. So I loaded the world again with my current mods and the old BYG but it did not load properly. It leads me to believe something is causing BYG not to work.

**Comment by Boolobo** [comment]
This probl

**Comment by Boolobo** [comment]
This problem is a lot more elaborate than I thought, I'm looking more into it and I may have found the solution-- sorry for all of the troubles.

**Comment by LegoWoof** [comment]
I was totally wrong but I found what the issue is..sort of.
The mod just wont load. The old version i downloaded months ago works, but no new version that I install loads up. And because the server uses a newer version that simply wont load, I can't really access it.

Sorry for spamming the discord with this lmao

**Comment by CorgiTaco** [comment]
your byg jar isnt loading oddly, did you download the jar from https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go-fabric?

**Comment by LegoWoof** [comment]
Oh my god.

I can't believe I didn't realize I need to install it from refabricated. This is embarrassing lol.

I can close this issue now, I'm sorry for opening it and reclosing it so many times-- I'm not super familiar with github. Thank you for letting me know to use refabricated.
