### ISSUE TITLE
[Bug]: Ametrine Ore is now common

### ISSUE THREAD

**Issue by JaboyKoral** [CorgiTaco/BYG#664]
### Mod Version

1.18.1-1.3.5.13

### Mod Loader

Forge

### Mod Loader Version

39.0.58

### What happened?

Ametrine Ore is now super common in the End Viscal Isles in both budding and regular forms. I couldn't find anything in the config files to adjust ore generation, and it seemed really strange to me given that it's meant to be an end-game material.

This might not be helpful to me since I'm making a modpack that only supports 1.18.1 right now and I know dev has moved on to 1.18.2, but wanted to bring it up.

![2022-03-09_13 15 10](https://user-images.githubusercontent.com/4743892/157511938-18e3e3f4-bccf-4756-bf7b-66f0c59dfdc6.png)

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/8217389/latest.log)

**Comment by CorgiTaco** [comment]
By our design we think this is fine, if you want to lower the frequency, you may do so via datapack by editing the `floating_island1-4` files in the configured_feature folder. To get the datapack use `/worldgenexport false`.
