### ISSUE TITLE
Link in FAQ to weebly wiki is broken

### ISSUE THREAD

**Issue by shaneknysh** [CorgiTaco/BYG#666]
Q: Does BYG have a wiki? Yes, https://bygmc.weebly.com/(currently incomplete but has all biomes)

Link is to 
`https://bygmc.weebly.com/(currently` instead of `https://bygmc.weebly.com/`

**Comment by CorgiTaco** [comment]
Fixed, now uses: https://oh-the-biomes-youll-go.fandom.com/wiki/Oh_The_Biomes_You%27ll_Go_Wiki instead
