### ISSUE TITLE
Boric, Cryptic, Therium Lantern textures don't flicker

### ISSUE THREAD

**Issue by asdasdasadg** [CorgiTaco/BYG#667]

**Comment by CorgiTaco** [comment]
It is, look closer

**Comment by asdasdasadg** [comment]
> It is, look closer

Therium lanterns do flicker but they're not noticeable at all, though Boric and Cryptic lanterns don't flicker and I've even looked at the textures to make sure

**Comment by CorgiTaco** [comment]
![image](https://user-images.githubusercontent.com/66983020/158486739-2aa4e84e-e82f-40b5-8749-9835dbbe971d.png)

**Comment by asdasdasadg** [comment]
> ![image](https://user-images.githubusercontent.com/66983020/158486739-2aa4e84e-e82f-40b5-8749-9835dbbe971d.png)

Yes but Boric and Cryptics colors don't change for each frame

**Comment by AOCAWOL** [comment]
This is intentional, I as the artist do not enjoy the vanilla flicker effect and chose to leave it out. You are welcome to resource pack it yourself. Thank you, have a good day :)

**Comment by asdasdasadg** [comment]
> This is intentional, I as the artist do not enjoy the vanilla flicker effect and chose to leave it out. You are welcome to resource pack it yourself. Thank you, have a good day :)

Oh alright thank you ^^
