### ISSUE TITLE
Wailing Nylium can be spread onto Netherrack

### ISSUE THREAD

**Issue by asdasdasadg** [CorgiTaco/BYG#668]

**Comment by CorgiTaco** [comment]
Fixed in https://github.com/AOCAWOL/BYG/commit/efd15f5fa1d5f0f33620a0811c29e09f13c538d6

Can be downloaded here: https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go/files/3694811 or https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go-fabric/files/3694799
