### ISSUE TITLE
[Request]: Look How They Massacred my Zelkova.

### ISSUE THREAD

**Issue by PestoPosta** [CorgiTaco/BYG#675]
### Mod Version

1.18.1

### Mod Loader

Forge

### Mod Loader Version

Forge 39.100

### What happened?

Ok, its not as dramatic as the title would make it sound,
I quite like the new texture, but I am begging you
for a crafting recipe for the original bark texture.
Possibly make it the stripped version of Zelkova.
The original is, if not my favorite, then its easily the top three.

PS I do apologizes for posting this here, if this is not the right location to make requests.

### latest.log

No log to be had, just a very humble request.

**Comment by SpareUranium** [comment]
My guy texture packs exist for a reason

**Comment by CorgiTaco** [comment]
Texture packs exist for a reason
