### ISSUE TITLE
Nether Biomes won't generate, End biomes have no issues (1.18.1)

### ISSUE THREAD

**Issue by EternallyBright** [CorgiTaco/BYG#676]
### Mod Version
1.18.1-1.3.5.13
### Mod Loader
Fabric
### Mod Loader Version
0.45.0
### What Happened?
I'm currently trying to implement OTB into my mulitplayer server, so was testing my new modpack in singleplayer. In starting new worlds, the Overworld and End biomes generate perfectly fine with no hassle, but the Nether comes up with this:
<img width="492" alt="Screen Shot 2022-03-16 at 3 16 57 PM" src="https://user-images.githubusercontent.com/97761196/158670791-f4434e34-0074-46e2-acd6-6c297cd829d9.png">

I did look at [this guide from y'all](https://github.com/AOCAWOL/BYG/wiki/Nether-&-End-Biomes-FAQ#enabling-byg-nether--end-biomes-in-existing-worlds), but I am on a Macbook unfortunately, so I can't use NBTExplorer.

Not sure if you could use the logs (it didn't crash or anything, nether biomes just... don't work.) But if you do need them I can provide.

**Comment by EternallyBright** [comment]
For the record, there are no other biome-related mods in this pack- they are all related to Origins, crafting recipes, or UI.

**Comment by EternallyBright** [comment]
Is there some additional information I could provide for a response? I really want to help my friends to explore this interesting mod, but if I don't get a response soon I'm probably just going to go back to BetterX.
Regardless, I'd like to say I enjoy this mod a lot and am a proud patron!

**Comment by CorgiTaco** [comment]
the instructions are listed perfectly there?

**Comment by EternallyBright** [comment]
Thank you for the response!
The terrablender link (middle one) doesn't work when I click it, and also seemed like it wasn't what I'm looking for- I _do_ want the nether to be replaced, by the BYG biomes. If I misunderstood and turning that off would allow the BYG biomes, though, then my bad! I'll try it tonight.
As for the existing world fix, I am on an Apple product. NBT appears to be windows only, otherwise I would have tried that. ^-^'

**Comment by CorgiTaco** [comment]
send your level.dat

**Comment by K0-RR** [comment]
> NBT appears to be windows only, otherwise I would have tried that

Here is a web version - https://irath96.github.io/webNBT/

**Comment by EternallyBright** [comment]
Oh excellent thank you! I'll try it on my end with the web version to save you the trouble Corgi- thank you all for the help! Here's hoping

**Comment by EternallyBright** [comment]
![image](https://user-images.githubusercontent.com/97761196/159555429-44d52fbb-aebd-41bb-9476-eb0fa0b524f7.png)
VICTORY!
