### ISSUE TITLE
[Bug]: BYG Froze Registry 

### ISSUE THREAD

**Issue by Klouver-github** [CorgiTaco/BYG#677]
### Mod Version

1.18.2-1.4-ALPHA-RC.3

### Mod Loader

Forge

### Mod Loader Version

1.18.2-40.0.18

### What happened?

I open the launcher then press launch, waited then show crashed report as well it did this 3 times this morning, I am trying enjoy some minecraft with the nice relaxing BYG but no, it said "no calm morning for you", if the crash report not good enough I can give the debug.log

### latest.log

https://paste.gg/p/anonymous/fcdb0e2203f2419bbae5c0aaff9f637f

**Comment by Klouver-github** [comment]
Forge team helped me resolved the problem. sorry Potion Studios

**Comment by Xplodin** [comment]
> Forge team helped me resolved the problem. sorry Potion Studios

how?

**Comment by Gavin456b** [comment]
Yes how? Please advise. Having the same problem here
