### ISSUE TITLE
[Bug]: 1.18.1 - BYG 1.18.1-1.3.5.13 - Crash when entering dimension [ ServerHangWatchdog detected that a single server tick took 60.00 seconds]

### ISSUE THREAD

**Issue by Marc-Harony** [CorgiTaco/BYG#678]
### Mod Version

1.18.1-1.3.5.13

### Mod Loader

Forge

### Mod Loader Version

39.1.2

### What happened?

Crash while entering a dimension. Single tick takes 60 secs.
How to configure BYG so that it does not interfere with the generation of a dimension?

### latest.log

https://pastebin.com/6499M5Sx

**Comment by CorgiTaco** [comment]
1.18.1 is not supported, please use 1.18.2
