### ISSUE TITLE
[Bug]: Tiny lilypads and water silk generating one block underwater and on ground

### ISSUE THREAD

**Issue by LoofScared** [CorgiTaco/BYG#680]
### Mod Version

1.18.2-1.4-RC-4

### Mod Loader

Forge

### Mod Loader Version

40.0.19

### What happened?

Tiny lilypads and water silk generate a single block underwater and on ground, as well as a block underground, causing water holes and ground holes to appear and lots of items to clutter the landscape until despawn.

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/8310388/latest.log)

**Comment by AOCAWOL** [comment]
This issue has been fixed and will be available in the next BYG Beta :D
