### ISSUE TITLE
[Enchancement]: Add FarmingForBlockheads's market compatibility

### ISSUE THREAD

**Issue by Niketats** [CorgiTaco/BYG#681]
There is a Market block in FarmingForBlockheads wjere player can buy saplings and crops.
![image](https://user-images.githubusercontent.com/68917520/159381842-b9aa6a2b-6771-4ddc-a576-cdbcdfb60941.png)

**Comment by Chuunkyz** [comment]
this mod is intended to be configured, you're intended to that yourself (or if you're playing a modpack the modpacks devs are intended to do that)

**Comment by AOCAWOL** [comment]
Closing this as what @Chuunkyz  said applies.
