### ISSUE TITLE
[Bug]: Crashing with the latest update (1.4-RC-5)

### ISSUE THREAD

**Issue by tajemniktv** [CorgiTaco/BYG#682]
### Mod Version

1.4-RC-5

### Mod Loader

Fabric

### Mod Loader Version

0.13.3

### What happened?

Updating from RC 4 to RC 5 causes a game to crash on start up. 

### latest.log

https://gist.github.com/tajemniktv/fbb713277eeb2c40bd6c0cd31d99b3c3

**Comment by CorgiTaco** [comment]
Fixed in latest.
