### ISSUE TITLE
just questions not an issue

### ISSUE THREAD

**Issue by fuyaku** [CorgiTaco/BYG#683]
Hi guys im really sorry for asking in the wrong place but i don't know where else to go. but ive just started playing mc for the first time and wanted to make a custom world with worldedit. i was wondering if: 1. its possible for oh the biomes you'll go to regenerate trees in the custom plains i made in worldpainter? 2. if i add some custom trees in worldpainter, will it regenerate the same model? 3. is there any biome id i can get to put in worldpainter? i watched tutorials and there's no ids in the config

im also sorry for the unrelated questions to byg mod but i'm desperate to know, everything seems complicated and don't know where else to ask! thanks so much!

**Comment by CorgiTaco** [comment]
I'm sorry but you're on your own with this as we dont know world painter ourselves.
