### ISSUE TITLE
Guiana Shield not raised

### ISSUE THREAD

**Issue by kingcavespider1** [CorgiTaco/BYG#684]
I was testing the 1.18.2 version of the mod(forge-1.18.2-1.4-RC-5-all) and noticed that the guiana shield does not appear like the image on the wiki. I used natures compass to find several of them and they seem to be somewhat high in y level but tend to not have topographic prominence compared to surrounding biomes which are mostly rainforest and wooded badlands. I am unclear if is intended behavior, the biome appears intended to be much more mountainous.

**Comment by CorgiTaco** [comment]
biomes have no say over the terrain in 1.18, they are "painted" on now
