### ISSUE TITLE
[Bug]: (Crash Registry Already Frozen)

### ISSUE THREAD

**Issue by Gavin456b** [CorgiTaco/BYG#685]
### Mod Version

1.18.2-1.4-RC-5-all

### Mod Loader

Forge

### Mod Loader Version

40.0.20

### What happened?

Game crashes on startup

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/8342957/latest.log)
[crash-2022-03-24_15.10.51-client.txt](https://github.com/AOCAWOL/BYG/files/8342959/crash-2022-03-24_15.10.51-client.txt)

**Comment by CorgiTaco** [comment]
you need to bisect search through your mods and figure which mod is causing this, it is most definitely not byg though

**Comment by Gavin456b** [comment]
The problem goes away as soon as I remove BYG. And it's the mod that's throwing an error in the crash log. So I don't know what else it could be

**Comment by CorgiTaco** [comment]
I am aware of that, as i said, you need to bisect search, I can guarantee that BYG will work fine by itself, another mod is most definitely provoking the crash

**Comment by CorgiTaco** [comment]
@Gavin456b Also to point out, your latest.log is cutoff

**Comment by CorgiTaco** [comment]
For example i just got the same error in my own little modpack: https://gist.github.com/CorgiTaco/e9e06144a3fb4e77df56dd41c3ee9524

and if you scroll down in the gist, the latest.log says Repurposed structures need to be updated

**Comment by Gavin456b** [comment]
Yeah my latest.log cuts off there because thats when the game exits. But I have an update. So I loaded BYG by itself with terrablender and it loaded. Then I placed all other mods back in and now the game launches. So it seems like for some reason BYG needs to launch solo before other mods are added.
