### ISSUE TITLE
[Bug]: Nothing can be planted on tilled lush dirt

### ISSUE THREAD

**Issue by LadyEclipse3** [CorgiTaco/BYG#686]
I've tried all different crops, modded and vanilla but nothing will plant. I've made sure there's water near by as well

**Comment by CorgiTaco** [comment]
works for me on forge, what mod loader r u using?

**Comment by LadyEclipse3** [comment]
I'm using fabric, the mod pack I'm playing is All of Fabric 5

**Comment by CorgiTaco** [comment]
Works for BYG fabric RC-6 at least on its own: https://i.imgur.com/il4ykqx.mp4

May want to report this to all of fabric and link this issue

**Comment by devRookie** [comment]
Any update on this?
