### ISSUE TITLE
[Bug]: Crash on initializing game

### ISSUE THREAD

**Issue by Lozf** [CorgiTaco/BYG#687]
### Mod Version

1.18.2

### Mod Loader

Fabric

### Mod Loader Version

0.13.3

### What happened?

When initializing the game, it crashed.

### latest.log

https://gist.github.com/Lozf/d1373d4e472877d3de791c3ec6e69753

**Comment by CorgiTaco** [comment]
You'll need to bisect search through your mods by removing half of the mods and half of those while keeping byg, fabric API, and terrablender as the constant mods. When you find the mod responsible, please comment here

**Comment by Lozf** [comment]
It turns out it is betteranimalsplus - it loads with everything else just fine.

**Comment by CorgiTaco** [comment]
@Lozf could you send the logs for this please?

**Comment by Lozf** [comment]
I did load up the game with just architectuary first to make sure it wasn't causing it, as it's required for betteranimals plus.  Those two are the only mods besides the original three you requested to be kept for testing.  

https://gist.github.com/Lozf/eb2135b78b67a877bd305769ef031941

**Comment by CorgiTaco** [comment]
Reported to better Animals Plus https://github.com/itsmeow/betteranimalsplus/issues/321
