### ISSUE TITLE
[Bug]: BYG seems to think the server is the client and crashes on startup

### ISSUE THREAD

**Issue by Icebelly** [CorgiTaco/BYG#688]
### Mod Version

1.18.2-1.4-RC-6-all

### Mod Loader

Forge

### Mod Loader Version

forge server 1.18.2-40.0.31

### What happened?

Like the title says, seems to be an issue exclusively to trying to run the mod on a private server I'm hosting with a friend, client manages the entire pack just fine but the moment it's thrown on the server it crashes during startup. Ended up testing this out with just BYG, still getting the same problem where it crashes while trying to load up BYG.

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/8347681/latest.log)

**Comment by Phlosioneer** [comment]
Fixed by ed57f46
