### ISSUE TITLE
[Bug]: Overworld biomes spawning in Aether

### ISSUE THREAD

**Issue by Niketats** [CorgiTaco/BYG#689]
### Mod Version

1.4-RC-7

### Mod Loader

Fabric

### Mod Loader Version

0.13.3

### What happened?

Overwirld bioms for some reason spwning in Aether dimension from Paradise Lost mod.

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/8353679/latest.log)

**Comment by CorgiTaco** [comment]
Fixed in latest terrablender

**Comment by Niketats** [comment]
nope
