### ISSUE TITLE
[Bug]: repairbiomesource NETHER does not work with the Incendium mod

### ISSUE THREAD

**Issue by tan-x-dx** [CorgiTaco/BYG#690]
### Mod Version

Oh_The_Biomes_Youll_Go-forge-1.18.2-1.4-RC-7-all.jar

### Mod Loader

Forge

### Mod Loader Version

40.0.31

### What happened?

I created a new installation of forge, with Biomes O' Plenty, BYG, TerraBlender, Terralith (Starmute) and Incendium (Starmute) as the only mods. All mods are the most recent forge releases.

I created a new world, and the overworld generated as normal. Overworld biomes from default minecraft and all mods were present and generating normally.

I entered the nether, and ran /locatebiome byg:sythian_torrids, and /locatebiome byg:wailing_garth. No such biomes were located. All default biomes as well as BOP and Incendium generated as normal, including the various Incendium structures. No BYG biomes were generating in an approx 1000x1000 block area.

I ran the command /byg repairbiomesource NETHER, being prompted twice to create backups. I did not create any backups. I kept running the command until I was "kicked from the server", with a message saying the biome source had been updated to BYG.

I was left at the multiplayer screen, despite this being a singleplayer world.

Afterwards the savefile had a yellow warning triangle, which displayed the standard "This world uses experimental settings" message. I reloaded the world, and ran the above locate biome commands again. No BYG biomes could be located. I /tp'd to 10000 ~ 10000 and ran the locatebiome commands again. As before, no BYG biomes could be located.
I repeated this test at various other coordinates, and also flew around in spectator mode to manually search for them. I found none.

I then closed down minecraft. No crashes or errors had occurred at any point.
In the forge config for this profile, I disabled the Incendium mod. I also completely deleted all configs.

After starting minecraft again, I created a new world with the same seed. The overworld was identical as previously. In the nether, both BOP and BYG biomes, as well as default biomes generated as normal.

I closed minecraft again, and re-enabled the Incendium mod. I deleted the configs again. I repeated the steps as above, and the result was the same as in the first test run.

### latest.log

https://gist.github.com/tan-x-dx/3c4fe8378c8dc1b92b4ef7b0d5bf754b

**Comment by CorgiTaco** [comment]
send your world's level.dat

**Comment by tan-x-dx** [comment]
[LevelDataFromBothAttempts.zip](https://github.com/AOCAWOL/BYG/files/8353784/LevelDataFromBothAttempts.zip)

**Comment by Niketats** [comment]
As I know from Incendium devs - BYG incompatible with Incendium

**Comment by CorgiTaco** [comment]
Incendium functions as long as they don't use their biome source in the nether @Niketats

**Comment by CorgiTaco** [comment]
I guess I'm gonna have to iterate through the datapack folder and nuke all nether files probably? Not sure

**Comment by BugmanBugman** [comment]
BOP's nether biomes seem to work with incendium, maybe they have a workaround that makes things easier that could be used for BYG as well

**Comment by CorgiTaco** [comment]
@BugmanBugman bop uses the vanilla biome source, we've chosen not to
