### ISSUE TITLE
[Crash]: Game crashes in nether without Biomes O' Plenty installed

### ISSUE THREAD

**Issue by DarkYuan** [CorgiTaco/BYG#692]
### Minecraft Version

1.16.5

### BYG Versions

1.3.5

### Terrablender

N/A

### Mod Loader

Forge

### Mod Loader Version

36.2.33

### What happened?

Running a very simple set of mods to try and deduce what the issue is here.
- BiomesOPlenty-1.16.5-13.1.0.485-universal
- byg-1.3.5
- jei-1.16.5-7.7.1.152

Both times ran with the default world type. BYG config set to allow byg to control the nether and end biomes, confirmed in the level.dat here: [level_dat_with_and_without_bop.zip](https://github.com/AOCAWOL/BYG/files/8356771/level.dat.with.and.without.bop.zip)
 

### crash-log

Crash without BOP: [crash-2022-03-27_00.32.58-server](https://gist.github.com/DarkYuan/d71cb419c716e259de706705c60355ee)

### latest.log

Log with BOP: [latest.log](https://gist.github.com/DarkYuan/14233a37062022f916663244d50b2f59)
Log without BOP: [latest.log](https://gist.github.com/DarkYuan/501a8a394771afc64a6e51950faf7bd9)

**Comment by CorgiTaco** [comment]
make sure you remove entries with a weight of 0 in your config, i need to fix this, i'd suggest VScode to validate/verify your json syntax: https://code.visualstudio.com/

**Comment by DarkYuan** [comment]
I didn't see anything with a tag of `"weight": 0` but if I had an entry that didn't have a weight tag I should add one? Like I found this one;
```
"byg:canyons": {
  "hills": [],
  "edge": "byg:canyon_edge",
  "beach": "byg:canyon_edge",
  "river": "byg:canyons",
  "climate": "WARM",
  "dictionary": [
    "OVERWORLD",
    "MOUNTAIN",
    "PLATEAU"
  ]
}
```

**Comment by DarkYuan** [comment]
I found the problem and now I feel dumb! At some point I must've been testing with BOP installed, because there were BOP biomes in the config, so it was still trying to generate those biomes that no longer existed >_<
