### ISSUE TITLE
[Crash]: Ticking entity  java.lang.IllegalArgumentException: Cannot set property EnumProperty{name=half, clazz=class net.minecraft.world.level.block.state.properties.DoubleBlockHalf, values=[upper, lower]} as it does not exist in Block{byg:prairie_grass}

### ISSUE THREAD

**Issue by Panderine** [CorgiTaco/BYG#698]
### Minecraft Version

1.18.1

### BYG Versions

1.18.1-1.3.5.13

### Terrablender

1.18.1-1.1.0.77

### Mod Loader

Forge

### Mod Loader Version

39.1.2

### What happened?

Server crashed

### crash-log

[crash-2022-04-01_19.05.55-server.txt](https://github.com/AOCAWOL/BYG/files/8401253/crash-2022-04-01_19.05.55-server.txt)

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/8401256/latest.log)

**Comment by CorgiTaco** [comment]
1.18.1 is not supported, please update to 1.18.2 as this issue most likely fixed.

**Comment by MattB70** [comment]
This issue has not been fixed in 1.18.2. I believe you are aware of it though.
