### ISSUE TITLE
[Crash]: [1.16.5] Dispenser Applying Bone Meal on Overgrown Stone causes Crash

### ISSUE THREAD

**Issue by 1keponchem** [CorgiTaco/BYG#700]
### Minecraft Version

1.16.5

### BYG Versions

1.3.5

### Terrablender

N/A

### Mod Loader

Forge

### Mod Loader Version

36.2.33

### What happened?

Activating Dispenser with Bone Meal inside, facing Overgrown Stone causes Crash.
I tested this with the setup down below.
![2022-04-02_14 00 51](https://user-images.githubusercontent.com/88263340/161367113-4e58e335-5d3f-4fa6-ae71-c941f71bf74a.png)
I think this relates to #602.

### crash-log

[crash-2022-04-02_14.00.53-server.txt](https://github.com/AOCAWOL/BYG/files/8401866/crash-2022-04-02_14.00.53-server.txt)

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/8401867/latest.log)

**Comment by 1keponchem** [comment]
While waiting, I also tested other similar blocks such as Overgrown Dacite, Overgrown Netherrack and Overgrown Crimson Blackstone, using exact same setup minus tested blocks.
Dacite and Crimson Blackstone variant caused crash, but Netherrack one didn't.
I'll send newly made crash logs as well, but it seems Crimson Blackstone one is almost identical to the original one.

Overgrown Dacite:
[crash-2022-04-02_15.29.36-server.txt](https://github.com/AOCAWOL/BYG/files/8401977/crash-2022-04-02_15.29.36-server.txt)
Overgrown Crimson Blackstone:
[crash-2022-04-02_15.31.00-server.txt](https://github.com/AOCAWOL/BYG/files/8401978/crash-2022-04-02_15.31.00-server.txt)

p.s. Sorry if my grammer is broken. I'm not a native English speaker.

Edit: To be clear, I tested those with BYG and no other mods are installed.

**Comment by 1keponchem** [comment]
I became curious so I tested other grass-like blocks as well.
All of newly tested blocks did not cause crash.
more specifically,
-byg:wailing_nylium
-byg:vermilion_sculk
-byg:glowcelium_block
-byg:shulkren_phylium
-byg:bulbis_phycelium
-byg:imparius_phylium
-byg:nightshade_phylium
-byg:ivis_phylium
-byg:sythian_nylium
-byg:mycelium_netherrack
-byg:embur_nylium

I hope this helps.

**Comment by 1keponchem** [comment]
I couldn't reproduce the crashes in 1.18 latest release terrablender(1.1.0.94)/BYG(1.4-RC-7-all).
I think it's because, as #602's thread says, the fix of that problem was already applied on 1.18 BYG.
also, It seems this crash is always triggered when bonemeal effect is applied on said blocks,no matter the way makes the effect(as long as it's not Player's R-click with Bone Meal).
(for example, Are Nouveau's grow spell, etc. actually for this reason my community's 1.16.5 server is currently unoperatable)

**Comment by 1keponchem** [comment]
I read the FAQ, and resetted the config by deleting byg folder in config file.
No obvious change.
just in case, I'll post latest.log and crash log.
[crash-2022-04-02_17.50.08-server.txt](https://github.com/AOCAWOL/BYG/files/8402164/crash-2022-04-02_17.50.08-server.txt)
[latest.log](https://github.com/AOCAWOL/BYG/files/8402165/latest.log)

Edit: This time I activated the first setup, using Overgrown Stone.

**Comment by tyler489** [comment]
Also applies to using Ars growth spells on stone with the following crash
https://crash.sverd.eu/e6e/crash-2022-05-01_16.15.25-server.txt

**Comment by JT122406** [comment]
1.16 isn't supported
