### ISSUE TITLE
[Bug]: Oasis generation bug

### ISSUE THREAD

**Issue by masonclomid** [CorgiTaco/BYG#702]
### Minecraft Version

1.16.5

### BYG Versions

1.3.5

### Terrablender

N/A

### Mod Loader

Forge

### Mod Loader Version

36.2.2 and 36.2.9 both 

### Bug Severity

Minor

### What happened?

It has been confirmed that if I load BYG and Terraforged together，the biome Oasis can be damaged and generation bug，actually it should be a lake.
![IMG_20220404_011856](https://user-images.githubusercontent.com/101992860/161440973-a3b7c1b9-2b29-4c6e-bc64-d1b4d2c60220.png)

### latest.log

N/A

**Comment by CorgiTaco** [comment]
This is caused bc terraforged does not handle depth for biomes and rather paints then on. So no, we will not be fixing this is, it'll be in your best interest to disable it
