### ISSUE TITLE
[Bug]: Ametrine Clusters don't drop anything when broken

### ISSUE THREAD

**Issue by milay** [CorgiTaco/BYG#705]
### Minecraft Version

1.18.2

### BYG Versions

1.4-RC-7

### Terrablender

1.1.0.99

### Mod Loader

Fabric

### Mod Loader Version

0.48.0

### Bug Severity

Minor

### What happened?

The Ametrine Clusters break when mined, but drop nothing, no matter what tools are used. They also break very slowly, seemingly unaffected by Efficiency.

Tools that were tested are:
- a netherite pickaxe with Silk Touch and a mix of modded and vanilla enchantments
- a modded material pickaxe (gilded netherite) with a mix of modded and vanilla enchantments
- a diamond pickaxe with vanilla enchantments (silk touch, unbreaking)
- a diamond pickaxe with vanilla enchantment (unbreaking)
- a diamond hoe with a mix of modded and vanilla enchantments
- a netherite axe with a mix of modded and vanilla enchantments

### latest.log

https://gist.github.com/milay/02abd7931e52e76421ba7a2c964a845b

**Comment by AOCAWOL** [comment]
This issue has been fixed and available in our next 1.18.2 Beta :D
