### ISSUE TITLE
[Bug]: No biome size config for over world? want larger forests.

### ISSUE THREAD

**Issue by xRogueDragonx** [CorgiTaco/BYG#706]
### Minecraft Version

1.18.2

### BYG Versions

1.18.2

### Terrablender

none

### Mod Loader

Fabric

### Mod Loader Version

0.13.3

### Bug Severity

Minor

### What happened?

Searching through the config for biome generation and I am unable to find the JSON for the over world. The end and Nether are there but not overworld.

### latest.log

![image](https://user-images.githubusercontent.com/98437590/162633824-e7a3d225-923e-41bd-adae-42a6ce35e69d.png)

**Comment by CorgiTaco** [comment]
biome sizes are by region, not by biome in 1.18+. And look in the `overworld` folder at the top to edit overworld related stuff


This is how the system works:
![image](https://user-images.githubusercontent.com/66983020/162634687-4c631b08-3e41-41cc-99ce-f3764abeec2f.png)
