### ISSUE TITLE
[Feature Request]: Cave Biomes

### ISSUE THREAD

**Issue by ilovehorrorcats** [CorgiTaco/BYG#707]
### Minecraft Version

1.18.2

### BYG Versions

1.4 RC 7-7

### Terrablender

1.1.0.99

### Mod Loader

Forge

### Mod Loader Version

40.0.36

### Bug Severity

Minor

### What happened?

I would like to see cave biomes

### latest.log

there is no log

**Comment by CorgiTaco** [comment]
if we make anything, we'll add those here: https://www.curseforge.com/minecraft/mc-mods/caves-and-critters

**Comment by ilovehorrorcats** [comment]
that sounds great. thx
