### ISSUE TITLE
[Bug]: Lush Dirt not plantable block

### ISSUE THREAD

**Issue by devRookie** [CorgiTaco/BYG#708]
### Minecraft Version

1.18.2

### BYG Versions

1.4-RC-7

### Terrablender

1.1.0.99

### Mod Loader

Fabric

### Mod Loader Version

0.13.3

### Bug Severity

Minor

### What happened?

Unable to tilt on lush farmland. Picture below. My guess is that the block is not listed as plantable? I dont know anything about coding, I am just comparing the two - Minecraft Dirt Farmland and Lush Farmland.

[https://ibb.co/1srffcn](url)

### latest.log

![2022-04-11_16 50 13](https://user-images.githubusercontent.com/8508007/162851872-30387cdb-6194-4447-bd2a-6e422f42a292.png)

**Comment by AOCAWOL** [comment]
This has been added and will be available in our next Beta :D

**Comment by Chrispytoast** [comment]
This issue was not fixed in the latest update. It is still missing the #c: farmland tag.
