### ISSUE TITLE
[Bug]: Can't plant cattail sprout on any surface

### ISSUE THREAD

**Issue by Rayxanber** [CorgiTaco/BYG#709]
### Minecraft Version

1.18.2

### BYG Versions

1.4-RC-7

### Terrablender

1.1.0.99

### Mod Loader

Fabric

### Mod Loader Version

0.13.3

### Bug Severity

Minor

### What happened?

Unable to plant cattail sprout plants anywhere, not even right where it was picked from

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/8477477/latest.log)

**Comment by CorgiTaco** [comment]
already fixed in: https://github.com/AOCAWOL/BYG/commit/f2097045299e21947f2fbbbf324b6b42ab355329
