### ISSUE TITLE
New biome: Volcanoes 

### ISSUE THREAD

**Issue by MeeniMc** [CorgiTaco/BYG#71]
Volcanic island (as seen for example in Terrestria) are especially stunning. I did not find any biome looking quite the same in BYG. 

Large volcanoes, blue sea, palm trees and black sand. 

I suppose one could extend the concept to cold-biome volcanoes too.

**Comment by CorgiTaco** [comment]
I've actually attempted this but I've had no luck. if someone's willing pull request such a feature I'd absolutely merge it but for my experience atm it is rather difficult for me to implement such a feature. I could be cheap and do a subbiome/biome but that's just not worth it at all

**Comment by OGitsBoondock** [comment]
I have no trouble running BoP and this mod.  I think BoP has that biome already?  Anyway I love the config files for both mods which allows me to minimize too many biomes.

**Comment by CorgiTaco** [comment]
Looks like your wish is coming true in 1.1 ;)
