### ISSUE TITLE
[Bug]: No dunes biome

### ISSUE THREAD

**Issue by kittech0** [CorgiTaco/BYG#710]
### Minecraft Version

1.18.2

### BYG Versions

1.4-RC-8

### Terrablender

1.1.0.99

### Mod Loader

Fabric

### Mod Loader Version

latest

### Bug Severity

Minor

### What happened?

There is no drune biome in locatebiome command (`/locatebiome byg:drune`) so im assuming that there is no drune biome at all but wiki tells that there exist drune biome
https://oh-the-biomes-youll-go.fandom.com/wiki/Dunes

### latest.log

.

**Comment by kittech0** [comment]
i can't find red sand desert too

**Comment by kittech0** [comment]
i reliased that for 1.18 there is no many biomes from byg...

**Comment by CorgiTaco** [comment]
Yup, not all 1.16 content was ported to 1.18
