### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by linkgames** [CorgiTaco/BYG#711]
### Minecraft Version

1.16.5

### BYG Versions

1.3.5

### Terrablender

N/A

### Mod Loader

Forge

### Mod Loader Version

36.2.40 forge 1 16.5 

### Bug Severity

Major

### What happened?

Hello I encounter that the biomes from other mods like betterend,endergetic expansion and outer end don't spawn at all if I have byg in modpack when I removed from the mods folder everything work 

### latest.log

![107045967-6922b580-67c6-11eb-8267-6e16b13bc3cd](https://user-images.githubusercontent.com/30554046/163434007-f60f8271-0ab7-4d11-94a2-e9f235ba1187.png)

**Comment by AOCAWOL** [comment]
Unfortun. our 1.16.5 builds are no longer developed and we cannot fix any issues regarding this version. We only update and work on the latest MC versions.
