### ISSUE TITLE
[Bug]: I Can't Disable BYG Nether Biomes, Even When BYG is the Only Mod

### ISSUE THREAD

**Issue by CacheTellsStories** [CorgiTaco/BYG#712]
### Minecraft Version

1.16.5

### BYG Versions

1.3.5

### Terrablender

N/A

### Mod Loader

Forge

### Mod Loader Version

36.2.20

### Bug Severity

Minor

### What happened?

I've been trying to disable the BYG Nether Biomes for a while (so I can use Better Nether Reforged instead), but nothing I do works. None of the config file changes I  have made disable the Nether biomes of BYG. I've set the biome weight to 0. Nothing. Set the biome weight to -1. Nothing. Deleted the section in the config dedicated to the biome. Still nothing. I've removed all of my other mods and done the above again. Norhing. 

### latest.log

[2022-04-02-2.log.gz](https://github.com/AOCAWOL/BYG/files/8492374/2022-04-02-2.log.gz)

**Comment by CorgiTaco** [comment]
https://github.com/AOCAWOL/BYG/wiki/Nether-&-End-Biomes-FAQ

**Comment by ghost** [comment]
Apologies for "bumping" this issue however the link you posted is to *enable* BYG biomes in the end/nether while the question is how to *disable* them. I too would like to know if it is possible to disable nether generation and default to vanilla, assuming it is possible.

There's currently a bug in fabric that prevents modded biomes appearing/working with BYG. It's been mostly fixed however the pull request has not been merged yet and that still doesn't fix compatibility with some data packs (like Incendium for example).

https://github.com/FabricMC/fabric/pull/2321 - Bug being referenced.

**Comment by emoace** [comment]
Yeah it seems I can't do this either.  I try to disable the End Biome "byg:cryptic_wastes" by setting the weight to 0 but my game keeps crashing with the logs saying something like :
`java.lang.NullPointerException: Cannot read field "context" because "x0" is null`

&

> `As JSON LOADED ELEMENT:
> NOT AVAILABLE BECAUSE JSONELEMENT WAS NULL
> 
>  at potionstudios.byg.BYG.commonLoad(BYG.java:51) ~[Oh_The_Biomes_You'll_Go-fabric-1.19-2.0.0.7.jar:?]
> 	at potionstudios.byg.BYGFabric.afterRegistriesFreeze(BYGFabric.java:65) ~[Oh_The_Biomes_You'll_Go-fabric-1.19-2.0.0.7.jar:?]
> 	at net.minecraft.class_2378.handler$zbk000$byg_afterRegistriesFreeze(class_2378.java:1127) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_2378.method_40292(class_2378.java:406) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_310.handler$zho001$onStart(class_310.java:5403) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_310.method_1514(class_310.java:713) ~[client-intermediary.jar:?]
> 	at net.minecraft.client.main.Main.main(Main.java:237) [client-intermediary.jar:?]
> 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.8.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.8.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.8.jar:?]
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
> 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
> 	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
> 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:214) [NewLaunch.jar:?]
> 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:249) [NewLaunch.jar:?]
> 	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
> 	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
> [21:19:19] [Render thread/INFO]: Stopping!
> [21:19:20] [Render thread/ERROR]: Shutdown failure!
> java.util.ConcurrentModificationException: null
> 	at java.util.HashMap.forEach(HashMap.java:1423) ~[?:?]
> 	at net.minecraft.class_1060.close(class_1060.java:173) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_310.close(class_310.java:1058) [client-intermediary.jar:?]
> 	at net.minecraft.class_310.method_1490(class_310.java:1034) [client-intermediary.jar:?]
> 	at net.minecraft.client.main.Main.main(Main.java:253) [client-intermediary.jar:?]
> 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.8.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.8.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.8.jar:?]
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
> 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
> 	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
> 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:214) [NewLaunch.jar:?]
> 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:249) [NewLaunch.jar:?]
> 	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
> 	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]

**Comment by ghost** [comment]
Have you found a way to disable the biomes in the Nether and End in 1.16.5?

**Comment by ghost** [comment]
No. I dropped this mod.
