### ISSUE TITLE
[Crash]: Rendering crash when loading game

### ISSUE THREAD

**Issue by RogueZombieDog** [CorgiTaco/BYG#713]
### Minecraft Version

1.18.2

### BYG Versions

1.4-RC-8-all

### Terrablender

1.1.0.9.9

### Mod Loader

Forge

### Mod Loader Version

40.0.49

### What happened?

loaded up my modpack with oh the biomes youll go, and it crashed
loaded up the modpack without it and it was fine so i have deduced that this mod is causing a crash of sorts

### crash-log

[crash-2022-04-15_21.24.17-client.txt](https://github.com/AOCAWOL/BYG/files/8498116/crash-2022-04-15_21.24.17-client.txt)

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/8498119/latest.log)

**Comment by CorgiTaco** [comment]
not byg, scroll up in the latest.log and address the issues there.

**Comment by RogueZombieDog** [comment]
scroll up from where? also the pack runs fine without byg how can it not be?

**Comment by CorgiTaco** [comment]
the error is not caused by byg. As i said, look above the error and address the metric loads of other errors including mixin related ones.

**Comment by DerCommander323** [comment]
FYI, Apparently Krypton is causing this. Idk how it even manages to make it blame BYG in the log, but im having the exact same errors and removing krypton fixed it
