### ISSUE TITLE
[Bug]: Flowers and saplings unable to be potted

### ISSUE THREAD

**Issue by championhestu** [CorgiTaco/BYG#714]
### Minecraft Version

1.18.2

### BYG Versions

1.18.2

### Terrablender

1.1.0.99

### Mod Loader

Forge

### Mod Loader Version

40.0.52

### Bug Severity

Minor

### What happened?

BYG flowers (the small ones, not the 2-block tall ones) and saplings cannot be placed in flower pots (or Supplementaries' planters) like vanilla flowers and saplings can.

### latest.log

[https://pastebin.com/FEuBxujy](https://pastebin.com/FEuBxujy)

**Comment by CorgiTaco** [comment]
Fixed in: https://github.com/AOCAWOL/BYG/commit/c0bba2a09cc07718f7a5c91c5b6705b5eda753ff
