### ISSUE TITLE
[Bug]: Animals wont spawn in BYG forest biomes

### ISSUE THREAD

**Issue by iiDogez** [CorgiTaco/BYG#716]
### Minecraft Version

1.16.5

### BYG Versions

1.3.5

### Terrablender

N/A

### Mod Loader

Forge

### Mod Loader Version

36.2.34

### Bug Severity

Major

### What happened?

When BYG is loaded on its own, vanilla animals wont spawn in BYG forest biomes. I can find animals spawning in biomes like the Guiana clearing, but in the Guiana shield animals wont spawn. 

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/8500597/latest.log)

**Comment by CorgiTaco** [comment]
Can confirm mobs spawn in latest 1.16 version
