### ISSUE TITLE
[Bug]: byg:nether is overwriting bclib's world gen settings every time I save.  Please respect my manual changes

### ISSUE THREAD

**Issue by begriefed** [CorgiTaco/BYG#717]
### Minecraft Version

1.18.2

### BYG Versions

1.4-RC-8

### Terrablender

1.1.0.99

### Mod Loader

Fabric

### Mod Loader Version

0.13.3

### Bug Severity

Major

### What happened?

Every time I save my game, level.dat/WorldGenSettings/dimensions/minecraft:the_nether/generator/biome_source/type:bclib:nether_biome_source is changed to type:byg:nether

I manually change it and it is changed back the next time I play and save.  If I don't manually change it back, I allow bclib to change it back with its save fixer program thingy.  Either way, the next time I save, it reverts back to byg's setting.  I have added all byg nether biomes to the force-add option in better nether.  Everything generates correctly only when it is set to bclib:nether_biome_source.  My new chunks are not created correctly when you revert my world gen settings.  Please stop reverting my manual changes to my level.dat.

P.S. If I missed something in the changelog, I'm sorry.  There could be a setting or config that I missed.  Please let me know if I'm just careless.  If I didn't miss anything and this was intentional, please create a toggle setting to disable this action.

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/8501036/latest.log)

**Comment by CorgiTaco** [comment]
in our `nether-biomes.json5` config, set `	"forceBYGNetherBiomeSource":,` to `false`.

Itll look something like this once you change it:
`	"forceBYGNetherBiomeSource": false,`

**Comment by begriefed** [comment]
My apologies.  I changed that setting about a week ago when reintegrating better nether (and promptly forgot it existed among the other 50 config file edits that I did).  BYG's last update (6 days ago?) must have reset my config file, then?

**Comment by CorgiTaco** [comment]
idk, just in the relevant file i mentioned you change the setting
