### ISSUE TITLE
[Crash]: 

### ISSUE THREAD

**Issue by axtrough** [CorgiTaco/BYG#718]
### Minecraft Version

1.18.2

### BYG Versions

Oh_The_Biomes_You'll_Go-forge-1.18.2-1.4-RC-8-all.jar

### Terrablender

TerraBlender-forge-1.18.2-1.1.0.99.jar

### Mod Loader

Forge

### Mod Loader Version

40.0.52

### What happened?

So I have this modpack with BYG mod downloaded on it and everytime I try to launch it this is what the crash log and latest log says.

### crash-log

https://pastebin.com/taX880Cf

### latest.log

https://pastebin.com/0y2g6k0P

**Comment by CorgiTaco** [comment]
BYG does not work with krypton, remove it.
