### ISSUE TITLE
Feature: pure biome version

### ISSUE THREAD

**Issue by MeeniMc** [CorgiTaco/BYG#72]
I saw that  there are a number of new armors/items in the mod. 

I'd like to keep the game as vanilla as possible. Ideally, there would be only saplings as new items, and wood/leaf items, if vanilla leaves cannot be colored/shaped to achieve the desired look.

Having planks/doors/etc. is acceptable, if not ideal (i.e., I'd prefer have this as an additional pack). 

Having new armors and many different items is definitely a detriment in my book, and should definitely be in a separate, companion pack.

**Comment by AOCAWOL** [comment]
Well for versions such as 1.15.2 there is a config that lets you turn off the ore spawns. However, if you do not like the modded/unique features of the mod unfortunately this isn't really the mod for you. This mod just isn't built around that and overall isn't our vision for it.
