### ISSUE TITLE
[Bug]: BYG generation overrides Paradise Lost's Aether dimension biomes

### ISSUE THREAD

**Issue by kevbot-git** [CorgiTaco/BYG#722]
### Minecraft Version

1.18.2

### BYG Versions

v1.4 RC 7

### Terrablender

1.1.0.99

### Mod Loader

Fabric

### Mod Loader Version

0.13.3

### Bug Severity

Major

### What happened?

When using BYG in conjunction with [Paradise Lost (Aether Reborn)](https://www.curseforge.com/minecraft/mc-mods/paradise-lost) in the context of [Better Minecraft (Fabric)](https://www.curseforge.com/minecraft/modpacks/better-minecraft-fabric), the Aether biomes are completely overridden by BYG generation. Strangely, holystone and the island formations are still generated, but none of the Aether's trees, mobs or ores seem to generate.

### latest.log

-

**Comment by CorgiTaco** [comment]
https://github.com/devs-immortal/Paradise-Lost/issues/630
