### ISSUE TITLE
[Bug]: Invalid implementation of the `BoneMealable` interface for the BYGPrairieGrassBlock class.

### ISSUE THREAD

**Issue by 0xJoeMama** [CorgiTaco/BYG#723]
### Minecraft Version

1.18.2

### BYG Versions

1.4-RC-9

### Terrablender

1.1.0.99

### Mod Loader

Fabric

### Mod Loader Version

0.13.3

### Bug Severity

Major

### What happened?

We recently received a bug report from @TheButterbrotMan about a crash that occurred in his modpack instance.

According to the report, our `BumbleLlamaEntity` crashed his game. Looking at the crashlog, it was obvious to me that this check was what was causing the issue: https://github.com/LlamaramaTeam/Llamarama/blob/45bf71be480819e43a140c7c2a0c0231218232ef/src/main/java/io/github/llamarama/team/common/entity/bumbllama/BumbleLlamaEntity.java#L132

This bug was reported to us in the past. It turned out to be our not making sure all checks from the `Fertilizable` interface were done. However, I personally fixed this issue a little while after that report and wrapped everything up into a release.

Getting the same issue again, made me want to see what may be causing it. After investigating your mod, I found out that the bug is probably in your implementation of the `BYGPrairieGrassBlock`. To be more accurate in this line: https://github.com/AOCAWOL/BYG/blob/fef8d4c483fe4904646f81226ee4abb9401ee4aa/Common/src/main/java/potionstudios/byg/common/block/BYGPrairieGrassBlock.java#L12

To be more accurate, you are extending a class with properties. however you are not passing said properties to your own instance of the block. You would need to override the `appendProperties` method(in yarn, in mojang maps it would be `createBlockStateDefinition`) and then you would need to figure out what you want to do yourself. For more information check out the issue mentioned here: https://github.com/LlamaramaTeam/Llamarama/issues/23

We would love it, if you could fix this issue as quickly as possible and if need be, we could also provide help.
Thank you for your time!

### latest.log

https://bytebin.lucko.me/svs8P3HahL

**Comment by Reshy** [comment]
I think it's causing a crash with any mod that tries to force a growth stage from Prairie Grass.  I think it also occurs with the other plants in the mod that has "tall" versions, like Allium bushes.

**Comment by 0xJoeMama** [comment]
Well yeah obviously anyone calling the `grow` method will instantly crash. The way I handled this case is by catching the exception and reporting the issue to the user. However, to be safe *this* would need to be fixed.

**Comment by 0xJoeMama** [comment]
Also, do you happen to know the status of the mod author? Because I don't see any activity in the issue tab and that concerns me, considering the amount of issues that I see popping up. Again, thanks for your time!

**Comment by CorgiTaco** [comment]
@0xJoeMama im busy at the moment with BYG's documentation, and when I fix issues I typically do dozens at once. As for when this issue is fixed, is when I get around to it like all the other issues.

**Comment by CorgiTaco** [comment]
And yes I do take Pull requests

**Comment by 0xJoeMama** [comment]
> im busy at the moment 

Okay, I can understand that. Especially considering I have the same issue because of exams. Thank you for your time and if I find the time I may create a pull request fixing this issue. Again, thank you!

**Comment by CorgiTaco** [comment]
tbh the blocks in this mod are messily implemented, im fixing those now tho

**Comment by CorgiTaco** [comment]
This should be fixed as of: https://github.com/AOCAWOL/BYG/commit/ea80191d3405ea77f8e81fd2a430e2da2f686b6b

**Comment by Reshy** [comment]
This still seems to be happening with Ether Bushes, Ether Grass, and Embur Roots.
