### ISSUE TITLE
[Crash]: Even when only using BYG and Terrablender, the game still crash even before the game actually started

### ISSUE THREAD

**Issue by adamking2580** [CorgiTaco/BYG#724]
### Minecraft Version

1.18.2

### BYG Versions

1.4-RC-10

### Terrablender

1.1.0.99

### Mod Loader

Forge

### Mod Loader Version

40.1.0

### What happened?

![image](https://user-images.githubusercontent.com/33510840/164750858-27cb9f58-5d0a-4120-9249-43cd151557e9.png)

Although I only adding BYG and Terrablender, the game still crashed even before the window of game popped out.

### crash-log

[debug.log](https://github.com/AOCAWOL/BYG/files/8542328/debug.log)

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/8542324/latest.log)

**Comment by CorgiTaco** [comment]
You logs give me no info of any sort, i am going to say this is a config issue andd that you should delete your configs and let them regen.
