### ISSUE TITLE
[Crash]: game crash

### ISSUE THREAD

**Issue by last903347** [CorgiTaco/BYG#725]
### Minecraft Version

1.18.2

### BYG Versions

Oh_The_Biomes_You'll_Go-forge-1.18.2-1.4-RC-10-all

### Terrablender

TerraBlender-forge-1.18.2-1.1.0.99

### Mod Loader

Forge

### Mod Loader Version

40.1.10

### What happened?

when I install byg, game failed to boot up. It looks like caused by this mod but I'm not sure

### crash-log

[crash-2022-04-23_12.52.33-client.txt](https://github.com/AOCAWOL/BYG/files/8546222/crash-2022-04-23_12.52.33-client.txt)

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/8546223/latest.log)

**Comment by wolflord212312** [comment]
[latest.log](https://github.com/AOCAWOL/BYG/files/8558425/latest.log)
Same

**Comment by CorgiTaco** [comment]
@last903347 Your issue looks to me to be supplementaries

**Comment by CorgiTaco** [comment]
```
net.minecraftforge.fml.ModLoadingException: Mod §ekubejs§r requires §6rhino§r §o1801.1.9-build.133 or above§r
§7Currently, §6rhino§r§7 is §o1801.1.8-build.102
	at net.minecraftforge.fml.ModLoadingException.lambda$fromEarlyException$0(ModLoadingException.java:50) ~[fmlcore-1.18.2-40.1.0.jar%23119!/:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
```

Update the mod `rhino`
