### ISSUE TITLE
[Bug]: Can't plant any of BYG's flowers on moss

### ISSUE THREAD

**Issue by goosewoman** [CorgiTaco/BYG#728]
### Minecraft Version

1.18.2

### BYG Versions

1.4-RC-10

### Terrablender

1.1.0.99

### Mod Loader

Fabric

### Mod Loader Version

0.10.2

### Bug Severity

Minor

### What happened?

Can't plant any of BYG's flowers on moss even though all vanilla flowers are capable of being planted on moss.

### latest.log

N/A

**Comment by CorgiTaco** [comment]
Fixed in: https://github.com/AOCAWOL/BYG/commit/adb1262d764c675250e00517186971ab60bd5b82
