### ISSUE TITLE
[Crash]: Render Overlay 

### ISSUE THREAD

**Issue by Sarriaman** [CorgiTaco/BYG#729]
### Minecraft Version

1.18.2

### BYG Versions

1.18.2 RC-10 

### Terrablender

1.1.0.99

### Mod Loader

Forge

### Mod Loader Version

40.1.0

### What happened?

I started mc and game crashed, i posted this here because i only see BYG render overlay error so i dont know

### crash-log

https://gist.github.com/Sarriaman/df1f645385925d3e54a2facd17cecb88

### latest.log

https://gist.github.com/Sarriaman/e0ae90b6830a9f393b02a549bff0c814

**Comment by REDcraftingdude** [comment]
Got the same message

**Comment by CorgiTaco** [comment]
your issue is: 
```
[27abr.2022 14:50:05.658] [Render thread/FATAL] [net.minecraftforge.fml.ModLoader/CORE]: Error during pre-loading phase
net.minecraftforge.fml.ModLoadingException: Mod �esurvive�r only supports �3sereneseasons�r �o1.18.2-7.0.0.14 or above�r
�7Currently, �3sereneseasons�r�7 is �o1.18.2-7.0.0.13
```



Update [Serene Seasons](https://www.curseforge.com/minecraft/mc-mods/serene-seasons)
