### ISSUE TITLE
Bug(?): bonemeal biomes with custom flowers produce only grass

### ISSUE THREAD

**Issue by MeeniMc** [CorgiTaco/BYG#73]
I tried to bonemeal the soil in many of the biomes with custom flowers, but only grass is produced. 

That would mean that custom flowers are completely non-renewable. That sounds like an erroneous behavior to me.

MC1.16.2 Fabric; BYG 1.0.2

**Comment by OGitsBoondock** [comment]
erroneous behaviour?  why on earth would they want to help someone who says something like that on an early version of a mod release.  This is something I would love to see fixed as well, but it may be intended to drive exploration.  Learn not to be rude

**Comment by AOCAWOL** [comment]
While we value the report we currently don't have the knowledge to add this feature in hence why we have marked help wanted. If we discover the knowledge to implement this we will :)

**Comment by MeeniMc** [comment]
> erroneous behaviour? why on earth would they want to help someone who says something like that on an early version of a mod release. This is something I would love to see fixed as well, but it may be intended to drive exploration. Learn not to be rude

You got this backward. Although I am not a long term user of the mod, I could appreciate the effort put into this very well made mod with just a quick test run. I made this report essentially to help the mod authors, as I assume they would value reports of erroneous behavior (as in, not intentional) so that it can be fixed. No rudeness intended.

**Comment by CorgiTaco** [comment]
Has been patched and will be available on OCT 31!
