### ISSUE TITLE
[Crash]:  Dragon Survival/Ars Nouveau and BYG Conflict over growing plants

### ISSUE THREAD

**Issue by Reshy** [CorgiTaco/BYG#730]
### Minecraft Version

1.18.2

### BYG Versions

Oh_The_Biomes_You'll_Go-forge-1.18.2-1.4-RC-10-all.jar

### Terrablender

TerraBlender-forge-1.18.2-1.1.0.99.jar

### Mod Loader

Forge

### Mod Loader Version

4.1.0

### What happened?

There is a crash with the mod DragonSurvival_DragonEditor-1.18.2-0.11.2_beta.jar and 
ars_nouveau-1.18.2-2.4.0.jar involving an interaction between the "growth" effect that other mods have.

EDIT:  Also occurs with other mods involving growing plants like Ars Nouveau.
EDIT 2:  Also occurs with other types of plants that have a "tall" version, like the Purple/Pink Allium, Embur Roots, Ether Grass/Bush, the small versions seem to crash when attempting to grow the "tall" version.

Specifically, this part:
DS
java.lang.IllegalArgumentException: Cannot set property EnumProperty{name=half, clazz=class net.minecraft.world.level.block.state.properties.DoubleBlockHalf, values=[upper, lower]} as it does not exist in Block{byg:prairie_grass}
AN
java.lang.IllegalArgumentException: Cannot set property EnumProperty{name=half, clazz=class net.minecraft.world.level.block.state.properties.DoubleBlockHalf, values=[upper, lower]} as it does not exist in Block{byg:prairie_grass}

Allium Crash:
java.lang.IllegalArgumentException: Cannot set property EnumProperty{name=half, clazz=class net.minecraft.world.level.block.state.properties.DoubleBlockHalf, values=[upper, lower]} as it does not exist in Block{byg:allium_flower_bush}

Ether Bush:
java.lang.IllegalArgumentException: Cannot set property EnumProperty{name=half, clazz=class net.minecraft.world.level.block.state.properties.DoubleBlockHalf, values=[upper, lower]} as it does not exist in Block{byg:ether_bush}

Ether Grass:
java.lang.IllegalArgumentException: Cannot set property EnumProperty{name=half, clazz=class net.minecraft.world.level.block.state.properties.DoubleBlockHalf, values=[upper, lower]} as it does not exist in Block{byg:ether_grass}

Embur Roots:
java.lang.IllegalArgumentException: Cannot set property EnumProperty{name=half, clazz=class net.minecraft.world.level.block.state.properties.DoubleBlockHalf, values=[upper, lower]} as it does not exist in Block{byg:embur_roots}

### crash-log

Dragon Survival:
https://pastebin.com/gaRHZRiT

Ars Nouvaeu:
https://pastebin.com/CqPCKBMm

Dragon Survival Crash /w Allium:
https://pastebin.com/tDKWbWrp

### latest.log

https://pastebin.com/RfQc5NuF

**Comment by tyler489** [comment]
Also occurs with Ars in 1.16.5

**Comment by MattB70** [comment]
I have this same crash but without either Dragon Survival or Ars Nouveau. My mod list is long, so it's most likely a conflict with another world gen mod such as Biomes O Plenty.

Is "clazz" expected? I know some people still use this syntax while others dont, so I've encountered conflicts because of it before.

**Comment by CorgiTaco** [comment]
This should be fixed as of: https://github.com/AOCAWOL/BYG/commit/ea80191d3405ea77f8e81fd2a430e2da2f686b6b
