### ISSUE TITLE
[Crash]: Incompatible with Trader NPCs

### ISSUE THREAD

**Issue by Sunconure11** [CorgiTaco/BYG#731]
### Minecraft Version

1.18.2

### BYG Versions

 Oh_The_Biomes_You'll_Go-fabric-1.18.2-1.4-RC-10.jar

### Terrablender

1.1.0.99

### Mod Loader

Fabric

### Mod Loader Version

0.14.2

### What happened?

Compat issue with this mod and Trader NPCs

https://www.curseforge.com/minecraft/mc-mods/tradernpcs

### crash-log

https://pastebin.com/ZpKKUDVd

### latest.log

https://pastebin.com/mB7Qed31

**Comment by CorgiTaco** [comment]
Reset your trades config.
