### ISSUE TITLE
[Bug]: End Biomes Tagged As Nether Wastes Biomes

### ISSUE THREAD

**Issue by GoatRammaHamma70** [CorgiTaco/BYG#733]
### Minecraft Version

1.18.2

### BYG Versions

1.4-RC-10

### Terrablender

1.1.0.99

### Mod Loader

Forge

### Mod Loader Version

40.1.0

### Bug Severity

Major

### What happened?

When traveling to the end in Better Minecraft Plus, it is apparent that Repurposed structures' nether wastes structures generate in your end biomes. some examples are below

![image](https://user-images.githubusercontent.com/94216350/166124636-1d50f104-2d7e-49c9-8bf9-37aa76ae439f.png)
nether pyramid 

![image](https://user-images.githubusercontent.com/94216350/166124645-3a382409-dfbe-45cc-a935-44f0b146252f.png)
nether end city

many other nether structures from the mod also generate

### latest.log

N/A

**Comment by CorgiTaco** [comment]
Fixed in latest: https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go/files/3775362

you'll have to wait for curseforge to approve it

**Comment by GoatRammaHamma70** [comment]
thank you
