### ISSUE TITLE
[Crash]: The game cashes when loading configs(server side only)

### ISSUE THREAD

**Issue by zrll12** [CorgiTaco/BYG#734]
### Minecraft Version

1.18.2

### BYG Versions

1.18.2-1.4-RC-11

### Terrablender

1.1.0.99

### Mod Loader

Fabric

### Mod Loader Version

0.13.3

### What happened?

The game crashed when loading server, but not when loading client

### crash-log

[crash-2022-05-01_10.55.24-server.txt](https://github.com/AOCAWOL/BYG/files/8598185/crash-2022-05-01_10.55.24-server.txt)

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/8598184/latest.log)

**Comment by CorgiTaco** [comment]
@zrll12 your level.dat is scuffed for whatever reason

The game is saying the nether doesnt exist

**Comment by zrll12** [comment]
This save is from 1.16.5, so it should be upgrade?

**Comment by CorgiTaco** [comment]
yeah so you should make a new world, so much breaks if you update across mc versions, and we unfortunately do not support that, sorry
