### ISSUE TITLE
[Bug]: Forager Zombie Villager is missing textures

### ISSUE THREAD

**Issue by SatDog92** [CorgiTaco/BYG#736]
### Minecraft Version

1.18.2

### BYG Versions

fabric-1.18.2-1.4-RC-11

### Terrablender

1.1.0.99

### Mod Loader

Fabric

### Mod Loader Version

0.13.3

### Bug Severity

Minor

### What happened?

Literally what the title says. First noticed this when i saw zombie villagers with missing textures, and then when i looked in the mod files i realized that there isn't even a folder for the zombie variant. Therefore, the texture for the entity gests the pink-black missing texture graphics.

### latest.log

https://gist.github.com/SatDog92/27ecc3c918fc5565b19c58b7a278f22f

**Comment by Reshy** [comment]
Getting a similar problem as well:
https://pastebin.com/9Mz7Ad61

**Comment by Redd56** [comment]
![image](https://user-images.githubusercontent.com/12189828/167326902-55ecb459-9fc9-40a0-ac38-31a753aa0d42.png)
same here, hehe missing texture villager go brrt
