### ISSUE TITLE
[Bug]: Embur Wart not able to be bonemealed, Dissapears on use.

### ISSUE THREAD

**Issue by AllThatJazz139** [CorgiTaco/BYG#740]
### Minecraft Version

1.18.2

### BYG Versions

Oh_The_Biomes_You'll_Go-fabric-1.18.2-1.4-RC-10.jar

### Terrablender

TerraBlender-fabric-1.18.2-1.1.0.99.jar

### Mod Loader

Fabric

### Mod Loader Version

0.13.3

### Bug Severity

Minor

### What happened?

Attempting to bonemeal a Embur Wart makes the wart dissapear instead of growing into a larger version. Even playing without all other mods this issue occurs.

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/8635881/latest.log) (With Other Mods)
[latest.log](https://github.com/AOCAWOL/BYG/files/8635979/latest.log) (With only BYG Terrablender and Fabric API)

**Comment by CorgiTaco** [comment]
Mushroom growth in 1.18 is borken atm

**Comment by AllThatJazz139** [comment]
Thanks, Didn't see it as a known issue anywhere so I wanted to make sure.
