### ISSUE TITLE
[Crash]: Ticking Entity error caused by flower

### ISSUE THREAD

**Issue by LocoPineapples** [CorgiTaco/BYG#741]
### Minecraft Version

1.18.2

### BYG Versions

1.18.2-1.4-RC-11-all

### Terrablender

1.1.0.99

### Mod Loader

Forge

### Mod Loader Version

40.1.16

### What happened?

Not entirely sure. While editing craft tweaker/JEI, I spawned in a new world. Everything is okay for a moment, and then I'm hit with a crash. I assume it has something to do with the double block alliums, but I didn't see any nearby.

### crash-log

[crash-2022-05-07_07.49.09-server.txt](https://github.com/AOCAWOL/BYG/files/8645060/crash-2022-05-07_07.49.09-server.txt)

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/8645061/latest.log)

**Comment by Darkfiend009** [comment]
It looks like it does have to do with the double alliums. However, it looks like the crash is actually due to an interaction between the alliums and the Regrowth mod.

**Comment by CorgiTaco** [comment]
This ***should*** be fixed on my side.
