### ISSUE TITLE
[Bug]: Crash error demanded GPU updates

### ISSUE THREAD

**Issue by TheIrishStud** [CorgiTaco/BYG#742]
### Minecraft Version

1.18.2

### BYG Versions

1.4-RC-11

### Terrablender

1.1.0.99

### Mod Loader

Fabric

### Mod Loader Version

0.14.4

### Bug Severity

Minor

### What happened?

Got a fatal crash error upon removing some resource packs that didn't work. Looked up the error and discovered that a previous bug in the past caused the options txt file to become corrupt. Creating this error until you delete the options txt file in your .minecraft folder. After deleting the options txt Minecraft proceeded to begin playing as normal as it did before I discovered the fact that BYG corrupted the options txt file in the .minecraft folder. Apologies if this is what you meant by resetting the configs. It didn't corrupt the entire options txt file... just something important that has to do with BYG... because Minecraft loaded just fine when BYG was removed. I thought it was a mod incompatibility until I removed those most recently added and reloaded BYG before searching up what kind of error would ask for GPU driver updates.

### latest.log

Apologies for not providing the latest log file... upon discovering what kind of error it was I just deleted the the options txt file in the .minecraft folder and went about my day testing mod\data pack\resource pack compatibility with no crashes.

**Comment by CorgiTaco** [comment]
BYG does not touch the options file at all
