### ISSUE TITLE
[Bug]: Os biomas do The End não aparecem [BR/PT]

### ISSUE THREAD

**Issue by PhantonIV** [CorgiTaco/BYG#744]
### Minecraft Version

1.16.5

### BYG Versions

1.3.5

### Terrablender

*

### Mod Loader

Forge

### Mod Loader Version

*

### Bug Severity

Minor

### What happened?

Quando eu entro no The End os biomas do byg não são gerados. Os biomas do Nether funcionaram perfeitamente mas os do The End nem se quer aparecem. Quando eu inicio um mundo novo eles aparecem normalmente.

### latest.log

*

**Comment by CorgiTaco** [comment]
https://github.com/AOCAWOL/BYG/wiki/Nether-&-End-Biomes-FAQ
