### ISSUE TITLE
[Bug]: Most flowers cannot be planted on modded dirts

### ISSUE THREAD

**Issue by Reshy** [CorgiTaco/BYG#747]
### Minecraft Version

1.18.2

### BYG Versions

 Oh_The_Biomes_You'll_Go-forge-1.18.2-1.4-RC-11-all.jar

### Terrablender

 TerraBlender-forge-1.18.2-1.1.0.99.jar

### Mod Loader

Forge

### Mod Loader Version

4.1.15

### Bug Severity

Minor

### What happened?

You cannot plant most of the plants from the BYG mod on non-vanilla dirts.  Saplings are fine, but about 3/4ths of all of the flowers and grasses have this issue.  Top row is standard dirt, bottom row is a sample dirt from a mod.
![2022-05-09_07 37 03](https://user-images.githubusercontent.com/2096384/167444734-a80def2b-7f36-46a1-9a06-74caaadbaff5.png)
![2022-05-09_07 37 00](https://user-images.githubusercontent.com/2096384/167444746-ad40091d-b039-443d-829c-be754b566aa6.png)
![2022-05-09_07 36 55](https://user-images.githubusercontent.com/2096384/167444760-f56cf44f-c04f-41c2-bd1b-467a3b97bd99.png)
![2022-05-09_07 36 50](https://user-images.githubusercontent.com/2096384/167444775-b62a9cc6-7b24-409c-bd62-58e5d875ca71.png)

### latest.log

None.

**Comment by CorgiTaco** [comment]
Should be fixed in https://github.com/AOCAWOL/BYG/commit/adb1262d764c675250e00517186971ab60bd5b82
