### ISSUE TITLE
[Crash]: World crashing durring loading after adding BYG. 

### ISSUE THREAD

**Issue by CsillaAria** [CorgiTaco/BYG#748]
### Minecraft Version

1.18.2

### BYG Versions

1.4-RC-11

### Terrablender

1.1.0.99

### Mod Loader

Forge

### Mod Loader Version

40.1.19

### What happened?

Yesterday I was having an issue where the game would crash when I ate after adding Terrablender, and BYG. I removed the mods, and the game worked fine. Today I decided to see if it was Terrablender or BYG that was part of the issue, so I could report it. Terrablender alone caused no problems but after adding BYG now causes the game to crash while the world is loading. Resetting the config does not help. BYG does not have any issues on its own, so there is a compatibility issue with another mod. 

If it helps I get this error message, sorry about the picture I can't figure out how to screenshot that.
![IMG_0238](https://user-images.githubusercontent.com/77200112/167625487-4d483922-4442-4d16-9bd5-57a6bb258273.JPG)

### crash-log

https://gist.github.com/CsillaAria/51cc4cda211d4bedf204a793163b42d3

### latest.log

https://gist.github.com/CsillaAria/3437497fad3553474ab81697cc6f2b25

**Comment by CorgiTaco** [comment]
The nether dimension doesn't exist in your world, fix this issue. If you updated your game from 1.18.1, your level.dat more than likely broke, please either make a new world or fix the world you're attempting to load's level.dat

**Comment by CsillaAria** [comment]
That's weird. Thank you.
