### ISSUE TITLE
[Bug]: Palms in cold biomes

### ISSUE THREAD

**Issue by dmkenza** [CorgiTaco/BYG#749]
### Minecraft Version

1.18.2

### BYG Versions

1.4-RC-11

### Terrablender

1.1.0.99

### Mod Loader

Fabric

### Mod Loader Version

0.13.3

### Bug Severity

Minor

### What happened?

In winter biomes you can see palms.

You can see this with the seed  2098041230611531402

![2022-05-10_16 08 00](https://user-images.githubusercontent.com/66675746/167636321-0100c776-65de-4407-9e27-eaee856ef974.png)

### latest.log

[crash-2022-05-10_16.03.11-client.txt](https://github.com/AOCAWOL/BYG/files/8661814/crash-2022-05-10_16.03.11-client.txt)

**Comment by CorgiTaco** [comment]
Palms trees use the is_beach biome tag, if you feel it shouldn't spawn in this biome, make a new biome tag and edit the palm tree's placement via datapacks and call your biome tag instead

**Comment by dmkenza** [comment]
> Palms trees use the is_beach biome tag, if you feel it shouldn't spawn in this biome, make a new biome tag and edit the palm tree's placement via datapacks and call your biome tag instead

I want see palms in the beach, but with snow on top it seams weird. 
Is it possible to spawn palms only if temperature is warm enough?

**Comment by CorgiTaco** [comment]
There is no temperature placement in Minecraft, use my suggestion of using datapacks to pick what biomes do and don't work for spawning.
