### ISSUE TITLE
Great Lakes Mud- severe performance problems (crash)

### ISSUE THREAD

**Issue by mactso** [CorgiTaco/BYG#75]
Using oh the biomes you'll go and biome's o plenty 
Minecraft: 1.16.1
Forge: 32.0.88
seed: -7574297424947320682
Position: -2300 70 500
Biome: Great Lakes

Severe performance issues with increasing ms tick length which will crash server if not addressed or players leave the area.

Improved the ms from 87.02ms / 6tps and falling up to 13.8ms / 20tps 
by using.

/fill ~-20 ~ ~-20 ~20 ~-5 ~20 gravel replace byg:mud_block
 
Appears something is wrong with byg: mud_block.  Most of the benefit was reached by replacing mud exposed to water.  That dropped it from about 87ms to 39ms.

Is there a way to disable this block temporarily until there is a fix?

Next release of our pack in a few days will try to get to 1.16.1 32.0.108 if all the mods are updated.  Then hopefully 1.16.2 in about 20 days.

**Comment by CorgiTaco** [comment]
We're aware of this. Best you can do is disable the biome in the weight config for 1.16.1. We no longer support 1.16.1.
