### ISSUE TITLE
[Crash]: Game crash on startup

### ISSUE THREAD

**Issue by MichaelJackson23** [CorgiTaco/BYG#750]
### Minecraft Version

1.18.2

### BYG Versions

Oh_The_Biomes_You'll_Go-fabric-1.18.2-1.4-RC-11

### Terrablender

TerraBlender-fabric-1.18.2-1.1.0.99

### Mod Loader

Fabric

### Mod Loader Version

0.14.5

### What happened?

Loaded up the game a few times and it worked fine, it started crashing randomly, whenever I delete the config it works for a little bit and then keeps crashing again 

### crash-log

[crash-2022-05-10_17.05.12-client.txt](https://github.com/AOCAWOL/BYG/files/8665293/crash-2022-05-10_17.05.12-client.txt)

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/8665295/latest.log)

**Comment by CorgiTaco** [comment]
delete your trades config and let it regenerate.
