### ISSUE TITLE
[Crash]:  Made it so my server would not load up out of nowhere

### ISSUE THREAD

**Issue by RAIMBOWFISH** [CorgiTaco/BYG#752]
### Minecraft Version

1.18.2

### BYG Versions

1.18.2-1.4

### Terrablender

1.1.0.99

### Mod Loader

Forge

### Mod Loader Version

40.1.19

### What happened?

I dont' know if this is my side or the mod, but it was working for a couple days, then it started cuasing the crash out of nowhere, by itself with terrablender, on my server hosting site (witherhosting). took me a while to figure out this was the mod causing it. It was the same file the whole time, and I even redownloaded it and the issue still happened, so overall very weird.

### crash-log

[crash-2022-05-11_21.17.08-server - oh the biomes youll go.txt](https://github.com/AOCAWOL/BYG/files/8673590/crash-2022-05-11_21.17.08-server.-.oh.the.biomes.youll.go.txt)

### latest.log

[2022-05-11-9.log - oh the biomes you'll go.gz](https://github.com/AOCAWOL/BYG/files/8673614/2022-05-11-9.log.-.oh.the.biomes.you.ll.go.gz)

**Comment by RAIMBOWFISH** [comment]
It still works without issue on my single-player world*

**Comment by CorgiTaco** [comment]
delete your trades config and let it regenerate.
