### ISSUE TITLE
[Bug]: Lava not fill cauldron from dripstone

### ISSUE THREAD

**Issue by uhloin** [CorgiTaco/BYG#757]
### Minecraft Version

1.18.2

### BYG Versions

Oh_The_Biomes_You'll_Go-forge-1.18.2-1.4-RC-11-all.jar

### Terrablender

TerraBlender-forge-1.18.2-1.1.0.99.jar

### Mod Loader

Forge

### Mod Loader Version

40.1.19

### Bug Severity

Major

### What happened?

Lava farm does not work.
Scheme:
Lava source
Dripstone
Pointer dripstone
Cauldron
Lava does not fill cauldron after long time.
Checked: previous version "Oh_The_Biomes_You'll_Go-forge-1.18.2-1.4-RC-10-all.jar" has not such a problem.

### latest.log

-

**Comment by CorgiTaco** [comment]
Not released, fixed internally: https://github.com/AOCAWOL/BYG/commit/576a4fe83dcf0a0424c3669c0481c0fb7a4cbbf7
