### ISSUE TITLE
[Bug]: issues with logs and sticks not working as fuel in furnaces, Is there anyway to fix this? if its a config, Please let me know Thank you

### ISSUE THREAD

**Issue by GhostlyGaming** [CorgiTaco/BYG#758]
### Minecraft Version

1.18.2

### BYG Version

1.4 RC 12

### Terrablender Version

1.1.0.99

### Mod Loader

Forge

### Mod Loader Version

40.1.16

### Bug Severity

Minor

### What happened?

The logs do not burn in a furnace after adding the mod, Is there anyway to fix this? if its a config, Please let me know Thank you

### latest.log

a

**Comment by Reisanji** [comment]
I've got the same problem with coal. I can't even put them in the furnace/smoker or anything that accepts fuel.

**Comment by GhostlyGaming** [comment]
I also have an issue with coal, charcoal, all wood types/logs planks and lava buckets. Nothing works in the furnace

**Comment by Reisanji** [comment]
So I'm guessing something got borked with the fuel tag maybe.

**Comment by GhostlyGaming** [comment]
So if its fixed do i fix the code by finding the file or redownload the mod?

**Comment by CorgiTaco** [comment]
@GhostlyGaming @Reisanji Fixed: https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go/files/3793566 (when approved)

**Comment by GhostlyGaming** [comment]
@CorgiTaco it says not found when i click on the link

**Comment by CorgiTaco** [comment]
@GhostlyGaming As i said **when approved**

**Comment by Reisanji** [comment]
Cool bean, It's working now. Thanks!
