### ISSUE TITLE
[Bug]: Visual bug while byg is present. 

### ISSUE THREAD

**Issue by frikinjay** [CorgiTaco/BYG#759]
### Minecraft Version

1.18.2

### BYG Version

1.18.2-1.4-RC-11

### Terrablender Version

1.18.2-1.1.0.99

### Mod Loader

Quilt

### Mod Loader Version

0.16.0

### Bug Severity

Major

### What happened?

Quilt (thats all TacoCorgi said to type)

Before the mod:
![2022-05-17_08 02 26](https://user-images.githubusercontent.com/88995340/168719225-dff674d5-02eb-457a-9829-d85f0a4aaf91.png)

After including the mod:
![2022-05-17_08 04 38](https://user-images.githubusercontent.com/88995340/168719263-fa14b75b-8460-4021-97d4-fcbadc1989be.png)

### latest.log

You can try it, I believe the results will be the same.

**Comment by CorgiTaco** [comment]
This should no longer be an issue, if you still get this issue please comment/reopen this issue. Ensure you're using the latest versions of BYG & Quilt!
