### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by GothCartel** [CorgiTaco/BYG#760]
### Minecraft Version

1.18.2

### BYG Version

Oh_The_Biomes_You'll_Go-forge-1.18.2-1.4-RC-15-all.jar

### Terrablender Version

TerraBlender-forge-1.18.2-1.1.0.99.jar

### Mod Loader

Forge

### Mod Loader Version

40.1.20

### Bug Severity

Major

### What happened?

Lush_stacks biome is spawning way too often in my world, included is a map which covers an area of 1000x1700 as an example

![map](https://user-images.githubusercontent.com/17881804/168856761-b2650677-eb1f-4b0a-80fc-a54c86f10a55.png)
d

### latest.log

No crash occurs so there isn't a log file

**Comment by MattB70** [comment]
Experiencing this as well, comically I had taken a few screenshots talking about how amazing this biome looks a couple days ago. The magic genie must have misinterpreted me. Seems like an RC15 bug, hopefully it gets tweaked for the next one 👍
