### ISSUE TITLE
[Bug]: Weeping Mire grass color doesn't look right

### ISSUE THREAD

**Issue by saltyseadoggo** [CorgiTaco/BYG#765]
### Minecraft Version

1.18.2

### BYG Version

1.4 RC 15

### Terrablender Version

1.1.0.99

### Mod Loader

Fabric

### Mod Loader Version

0.14.5

### Bug Severity

Minor

### What happened?

The Weeping Mire biome's grass is the usual yellow-green color found throughout the Nether. I figured, and think I remember from 1.16, it's supposed to be a primrose color to match the foliage on the trees. Please correct me if I'm wrong.

![2022-05-18_18 12 58](https://user-images.githubusercontent.com/69029346/169181433-d12f51f2-8c14-416a-b6d3-b64c64bc8ff4.png)

### latest.log

N/A

**Comment by CorgiTaco** [comment]
Intentional
