### ISSUE TITLE
[Bug]: Endermites in the Ethereal Islands aggro all nearby Endermen

### ISSUE THREAD

**Issue by saltyseadoggo** [CorgiTaco/BYG#766]
### Minecraft Version

1.18.2

### BYG Version

1.4 RC 15

### Terrablender Version

1.1.0.99

### Mod Loader

Fabric

### Mod Loader Version

0.14.5

### Bug Severity

Minor

### What happened?

I noticed as I was passing through an ethereal isles biome all of the Endermen rushing towards a point before stopping. It seems like this biome spawns endermites, which aggro all of the nearby endermen, causing all of them in a wide range to pursue it until one kills it. This looks a bit unusual when it happens, though I don't know if it's unintended behavior.

### latest.log

N/A

**Comment by CorgiTaco** [comment]
Intentional behavior, use data packs to remove their spawn
