### ISSUE TITLE
[Bug]: Forager villager is too hard to level up

### ISSUE THREAD

**Issue by saltyseadoggo** [CorgiTaco/BYG#769]
### Minecraft Version

1.18.2

### BYG Version

1.4 RC 15

### Terrablender Version

1.1.0.99

### Mod Loader

Fabric

### Mod Loader Version

0.14.5

### Bug Severity

Minor

### What happened?

The forager villager profession is much, much harder to level up than vanilla villagers because of how little experience it gets from players completing its apprentice and onward trades. I can sell up to the restock limit of puffball caps or warped fungi or whatever and not get them to advance past journeyman, while, with vanilla villagers, doing their most recent two trades up to the restock cap is generally enough to level them up.

I suggest increasing the experience foragers receive from the player completing their apprentice and onwards trades to match vanilla villagers.

### latest.log

N/A

**Comment by AOCAWOL** [comment]
I have adjusted the experience you earn for the trades, hopefully, this makes these trades more viable and further adjustment and tuning may be needed. this will be available in the next BYG beta :)
