### ISSUE TITLE
A crash report I received.

### ISSUE THREAD

**Issue by Atomic998xz0** [CorgiTaco/BYG#77]
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 8/29/20 1:06 PM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'byg'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
	at net.minecraft.class_310.<init>(class_310.java:423)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: java.lang.UnsupportedOperationException
	at com.google.common.collect.ImmutableCollection.add(ImmutableCollection.java:218)
	at voronoiaoc.byg.common.world.feature.biomefeatures.BYGFeaturesInVanilla.addFeatureToBiome(BYGFeaturesInVanilla.java:92)
	at voronoiaoc.byg.common.world.feature.biomefeatures.BYGFeaturesInVanilla.addFeatures(BYGFeaturesInVanilla.java:23)
	at voronoiaoc.byg.BYG.onInitialize(BYG.java:50)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient$$Lambda$2272/996414823.accept(Unknown Source)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	... 11 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
	at net.minecraft.class_310.<init>(class_310.java:423)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.16.2
	Minecraft Version ID: 1.16.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1145365752 bytes (1092 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		autoconfig1u: Auto Config v1 Updated 3.2.2
		better_wandering_trader: Better Wandering Trader 1.5.0
		blockshifter: Blockshifter 1.0.8+1.16.2
		byg: BYG 1.0.4
		cardinal-components: Cardinal Components API 2.5.2
		cardinal-components-base: Cardinal Components API (base) 2.5.2
		cardinal-components-block: Cardinal Components API (blocks) 2.5.2
		cardinal-components-chunk: Cardinal Components API (chunks) 2.5.2
		cardinal-components-entity: Cardinal Components API (entities) 2.5.2
		cardinal-components-item: Cardinal Components API (items) 2.5.2
		cardinal-components-level: Cardinal Components API (world saves) 2.5.2
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 2.5.2
		cardinal-components-util: Cardinal Components API (utilities) 2.5.2
		cardinal-components-world: Cardinal Components API (worlds) 2.5.2
		cloth-api: Cloth API 1.4.5
		cloth-armor-api-v1: Cloth Armor API v1 1.4.5
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.4.5
		cloth-common-events-v1: Cloth Common Events v1 1.4.5
		cloth-config2: Cloth Config v4 4.8.1
		cloth-datagen-api-v1: Cloth Datagen v1 1.4.5
		cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.4.5
		cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.4.5
		cloth-scissors-api-v1: Cloth Scissors API v1 1.4.5
		cloth-utils-v1: Cloth Utils v1 1.4.5
		couplings: Couplings 1.3.1
		curios: Curios API 0.0.6-1.16.2
		dynamicsoundfilters: Dynamic Sound Filters 1.1.3+1.16.2
		earthtojavamobs: Earth2Java 1.2.0+1.16.2
		enderitemod: Enderite Mod 1.2.2
		exotic-art-core: Exotic Art Core Content Pack 1.0.358
		exotic-matter: Exotic Matter 2.10.358
		fabric: Fabric API 0.19.0+build.398-1.16
		fabric-api-base: Fabric API Base 0.1.3+12a8474cfa
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea894e
		fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce533984e
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d308364e
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f4e
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea8664e
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d4e
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.0+e2e6cdad4e
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b4e
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.1+91555cd14e
		fabric-item-api-v1: Fabric Item API (v1) 1.1.0+29679fd64e
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f96364e
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c64e
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c54e
		fabric-language-kotlin: Fabric Language Kotlin 1.3.72+build.1
		fabric-language-scala: Fabric Language Scala 0.3.2.12
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+74cc3b204e
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.0+fac8f3664e
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce994e
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d64e
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b4e
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f4e
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.6.0+e81ec80b4e
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.6.1+ba4afa574e
		fabric-particles-v1: fabric-particles-v1 0.2.1+0a6f2a704e
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.4.3+e5d3217f4e
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.13+eae12eb84e
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.3.4+5d32f5834e
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.1.0+e2862de64e
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d4e
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.10+e5d3217f4e
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+534104904e
		fabric-rendering-v1: Fabric Rendering (v1) 1.2.0+fc24ff244e
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.2.9+e5d3217f4e
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+872498414e
		fabric-structure-api-v1: Fabric Structure API (v1) 1.0.0+516ece7c4e
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.0.3+ac8e8c594e
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb84e
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.2+ccce563e4e
		fabricloader: Fabric Loader 0.9.2+build.206
		fallflyinglib: FallFlyingLib 1.1.0
		fermion: Fermion 2.5.201
		fermion-gui: Fermion GUI 2.4.201
		fermion-modkeys: Fermion Modifier Keys 1.9.201
		fermion-orientation: Fermion Orientation 1.1.201
		fermion-simulator: Fermion Simulator 1.7.201
		fermion-varia: Fermion Varia 2.3.201
		firstperson: FirstpersonModel 1.3.0
		jankson: Jankson 3.0.1+j1.2.0
		library_of_exile: Library of Exile 1.0.2
		minecraft: Minecraft 1.16.2
		missingnetherblocks: Missing Nether Blocks 2.0.0
		mmorpg: Age of Exile 1.1.3
		mo_glass: Mo Glass 1.4-MC1.16.2
		modmenu: Mod Menu 1.14.6+build.31
		moenchantments: Mo'Enchantments 1.13.6
		morepaths: More Paths 0.0.3
		netheritehorsearmor: Netherite Horse Armor 0.4.2-1.16.2
		onsoulfire: On Soul Fire 6
		org_jetbrains_annotations: annotations 17.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.3.72
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.3.72
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.3.72
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.3.72
		org_jetbrains_kotlinx_kotlinx-coroutines-core: kotlinx-coroutines-core 1.3.7
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.7
		origins: Origins 1.16.2-0.3.7
		playerabilitylib: Pal 1.2.1
		portaltags: Portal Tags 2.0.0+1.16.2
		pumice: Pumice 0.0.2
		reach-entity-attributes: Reach Entity Attribute 1.0.1
		roughlyenoughitems: Roughly Enough Items 5.2.9
		roughlyenoughitems-api: REI (API) 5.2.9
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.2.9
		roughlyenoughitems-runtime: REI (Runtime) 5.2.9
		soulsoilfarmland: Soul Soil Farmland 0.0.2
		special-circumstances: Special Circumstances 1.7.201
		tk_valoeghese_zoesteriaconfig: ZoesteriaConfig 1.3.2
		torridvision: Torrid Vision 0.0.3
		waila: Hwyla 1.9.22
		winged: Winged Mod 1.16.2-1.4.0
		woodsplus: Woods Plus 0.0.2
		xb: Exotic Blocks 1.6.149
	Launched Version: fabric-loader-0.9.2+build.206-1.16.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>

**Comment by CorgiTaco** [comment]
Should be fixed here: https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go-fabric/files/3045127
