### ISSUE TITLE
[Bug]: You cannot bone meal any 2 tall flower of the mod.

### ISSUE THREAD

**Issue by BartzV** [CorgiTaco/BYG#771]
### Minecraft Version

1.18.2

### BYG Version

1.4

### Terrablender Version

1.1.0.99

### Mod Loader

Fabric

### Mod Loader Version

0.13.3

### Bug Severity

Minor

### What happened?

As the title says, if you bone meal tall flowers you do not get any flower and the bone meal is consumed.
Edit, my wrong. You cannot bone meal at the top block of the flower. The bottom part spreads their little variant.

### latest.log

????

**Comment by AOCAWOL** [comment]
I am closing this as in the latest BYG this is not an issue. All Tall Flowers proceeded to pop their respective flower when bonemealed via the top or bottom part of the plant. Make sure you aren't experiencing a mod compact. issue :)
