### ISSUE TITLE
[Crash]: Setting `forceBYGEndBiomeSource` to `false` crashes game

### ISSUE THREAD

**Issue by saltyseadoggo** [CorgiTaco/BYG#772]
### Minecraft Version

1.18.2

### BYG Version

1.4 RC 15

### Terrablender Version

1.1.0.99

### Mod Loader

Fabric

### Mod Loader Version

0.14.5

### What happened?

Changing `"forceBYGEndBiomeSource": true,` to `"forceBYGEndBiomeSource": false,` in `end-biomes.json5` causes the game to crash on startup.

### crash-log

[crash-2022-05-20_16.05.08-client.txt](https://github.com/AOCAWOL/BYG/files/8744923/crash-2022-05-20_16.05.08-client.txt)

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/8744925/latest.log)

**Comment by CorgiTaco** [comment]
send your config file, seems to have gotten corrupted @saltyseadoggo

**Comment by saltyseadoggo** [comment]
> send your config file, seems to have gotten corrupted @saltyseadoggo

https://gist.github.com/saltyseadoggo/1b7ddba0bef9cf7b2a5db248b8439a94
This config file comes from deleting `config/byg` folder entirely, running the game to let it regenerate, exiting the game, opening the file in gedit, changing the one setting, and saving it.

**Comment by saltyseadoggo** [comment]
I also just had this happen when setting the weight of the subzero hypogeal biome on a fresh config from 0 to 2. It looked like the same crash text.

**Comment by CorgiTaco** [comment]
@saltyseadoggo im under the impression the program you're saving the file with is causing issues, try a different one maybe?

**Comment by saltyseadoggo** [comment]
I opened the nether biome config file in IntelliJ and set the hypogeal's rarity there, and no crash. I guess gedit does something funky with .json5 files. It might be related to how it seemed to think they were written in C?

So that's issue resolved, I guess.
While I have you here, why are some of the Nether biomes disabled? Are they going to have breaking changes or something? Asking before I enable them in case doing so will cause issues down the line

**Comment by CorgiTaco** [comment]
@saltyseadoggo disabled? they were probably not added back, and a good place to ask in the future is discord, please keep them issues related to issues

**Comment by aarchangel64** [comment]
I'm also getting this exact same crash, when changing any setting. I've tried editing the file in both vim and emacs with no special modes or anything fancy enabled. I'm using a Linux system, if that makes a difference.

This is likely a bug with BYG and not vim or emacs, because no other mod has any issues when changing configs, and I haven't run into any file corruption issues before using these editors.

**Comment by CorgiTaco** [comment]
@Cosmic-Goat send your crash then

**Comment by aarchangel64** [comment]
[latest.log](https://github.com/AOCAWOL/BYG/files/8783369/latest.log)
[Crash Report](https://github.com/AOCAWOL/BYG/files/8783371/crash-2022-05-26_22.03.30-client.txt)

I've also cloned the repo and I'll try debugging it to see if I can find what's causing the issue on my end.

**Comment by aarchangel64** [comment]
As far as I can tell, Jankson freaks out about something when trying to read the config [here](https://github.com/AOCAWOL/BYG/blob/0e51630bac32ad881c13463ffc876b7e96e686fb/Common/src/main/java/potionstudios/byg/common/world/biome/nether/NetherBiomesConfig.java#L122) (when editing nether-biomes.json5, for example). I can also confirm that editing the file in IntelliJ works fine for some reason. This is a really strange bug, sorry to bring it up! 

Maybe file an issue with Jankson?

**Comment by CorgiTaco** [comment]
@Cosmic-Goat some file editors save JSON5 as corrupted files for whatever reason, try changing it
