### ISSUE TITLE
[Bug]: Travertine and red rock recipes conflict

### ISSUE THREAD

**Issue by saltyseadoggo** [CorgiTaco/BYG#773]
### Minecraft Version

1.18.2

### BYG Version

1.4 RC 17

### Terrablender Version

1.1.0.99

### Mod Loader

Fabric

### Mod Loader Version

0.14.5

### Bug Severity

Minor

### What happened?

Travertine and red rock have the exact same crafting recipes, so I am unable to craft travertine in my survival world because the recipes only make red rock.
I would like the travertine recipe(s) to be changed so they no longer conflict, allowing me to craft travertine.

![2022-05-20_21 42 52](https://user-images.githubusercontent.com/69029346/169635795-4dc76337-1293-47cb-a665-4d9d7963ba25.png)
![2022-05-20_21 43 01](https://user-images.githubusercontent.com/69029346/169635796-04fc64f7-9d75-41ef-93ea-3741ed16dd1f.png)

### latest.log

N/A

**Comment by AOCAWOL** [comment]
This has been fixed and will be in the next BYG beta :D
