### ISSUE TITLE
[Bug]: Ether stone can't be placed on x or z axes like deepslate

### ISSUE THREAD

**Issue by saltyseadoggo** [CorgiTaco/BYG#774]
### Minecraft Version

1.18.2

### BYG Version

1.4 RC 17

### Terrablender Version

1.1.0.99

### Mod Loader

Fabric

### Mod Loader Version

0.14.5

### Bug Severity

Minor

### What happened?

Given that ether stone is a recolor of deepslate, I figured I could place ether stone on the x and z axes like deepslate, but I cannot. I think this feature would make sense to add.

### latest.log

N/A

**Comment by AOCAWOL** [comment]
This is intended, we don't want Ether-stone being exactly like Deepslate :)
