### ISSUE TITLE
[Crash]: Client Crash on startup

### ISSUE THREAD

**Issue by A5ho9999** [CorgiTaco/BYG#775]
### Minecraft Version

1.18.2

### BYG Version

1.18.2-1.4-RC-17

### Terrablender Version

1.18.2-1.1.0.99

### Mod Loader

Fabric

### Mod Loader Version

0.14.6-1.18.2

### What happened?

Multiple Crashes when attempting the launch game, different results each time

### crash-log

https://gist.github.com/A5ho9999/4d6e6f26e70f9167d23f3f4f9dc69079

### latest.log

https://gist.github.com/A5ho9999/7ff5e246553b726d2ec8c36343e3fb21

**Comment by CorgiTaco** [comment]
@A5ho9999 i suggest you bisect search andd find the culprit

**Comment by FreeFull** [comment]
~~It seems like currently BYG is incompatible with Immersive Weathering in some way~~ Nevermind, I tried using immersive weathering again and it's working fine for me now, it must be some other mod.

**Comment by CorgiTaco** [comment]
Should no longer be an issue, if the issue persists please reopen this issue/comment/make a new issue!
