### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Windyxelor** [CorgiTaco/BYG#776]
### Minecraft Version

1.18.2

### BYG Version

1.4-RC-17

### Terrablender Version

1.1.0.101

### Mod Loader

Fabric

### Mod Loader Version

0.14.5

### Bug Severity

Minor

### What happened?

Some crafting tables are not able to be crafted. I've attached some examples of recipes that don't exist, but there are probably many more.

![image](https://user-images.githubusercontent.com/82713802/169691454-0a295c30-b478-42db-af40-478e3d9c396f.png)
![image](https://user-images.githubusercontent.com/82713802/169691459-56235a32-8748-4637-9432-181791e38721.png)
![image](https://user-images.githubusercontent.com/82713802/169691473-6f063413-1bd2-448e-acc5-5c7dbe935af5.png)
![image](https://user-images.githubusercontent.com/82713802/169691526-0cc74be1-a4ac-4e7e-81a0-d0c4b0039ea2.png)

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/8749243/latest.log)

**Comment by CorgiTaco** [comment]
Use polymorph
