### ISSUE TITLE
[Crash]: No such method: double WorldgenRandom.nextDouble(double)

### ISSUE THREAD

**Issue by Neolyum** [CorgiTaco/BYG#777]
### Minecraft Version

1.18.2

### BYG Version

1.18.2-1.4-RC-19

### Terrablender Version

1.1.0.99

### Mod Loader

Forge

### Mod Loader Version

40.1.20

### What happened?

When exploring new chunks, a java.lang.NoSuchMethodException occurs, crashing the server.
The full exception is
    ```java.lang.NoSuchMethodError: 'double net.minecraft.world.level.levelgen.WorldgenRandom.nextDouble(double)'
at potionstudios.byg.common.world.structure.arch.ArchStructure.generatePieces(ArchStructure.java:41) ~[Oh_The_Biomes_You'll_Go-forge-1.18.2-1.4-RC-19.jar%23243!/:1.4-RC-19] {re:classloading}```

This happens every time one of the players starts to explore the world and generates new chunks.
If the server is restarted and the player reconnects, the server crashes instantly.

This is the latest ATM7 (at this time 0.4.2), tested with RC-11 and RC-19.

Sorry I couldn't test with no other active mods.

### crash-log

https://gist.github.com/Neolyum/1362eceea02d431d5303cdaea43c74d0
Both crash and latest are here

### latest.log

https://gist.github.com/Neolyum/1362eceea02d431d5303cdaea43c74d0

**Comment by CorgiTaco** [comment]
Try the latest jar, if the issue persists reopen this issue

**Comment by Neolyum** [comment]
Tried with RC-21, same issue :(
And it seems I can't reopen by myself, so please reopen, if necessary.

**Comment by Neolyum** [comment]
@CorgiTaco this is still an issue, could you reopen it please?
It crashes the server frequently, especially if someone is in the affected chunk, who then cannot play anymore without using a world backup.

**Comment by PABessero** [comment]
It doesnt appear to have been fixed in latest release, however you can login without having to rollback the whole server by modifying the player coordinates in player.dat

**Comment by CorgiTaco** [comment]
This should no longer be an issue, if you still get this crash please comment/reopen this issue. Ensure you're using the latest versions of all mods relating to world generation, Forge and Terrablender!
