### ISSUE TITLE
[Bug]: saplings don't work

### ISSUE THREAD

**Issue by Yupoman** [CorgiTaco/BYG#778]
### Minecraft Version

1.18.2

### BYG Version

1.4-RC-19

### Terrablender Version

1.1.0.101

### Mod Loader

Forge

### Mod Loader Version

40.1.19

### Bug Severity

Major

### What happened?

Sapling never grow naturally or with bone meal

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/8750082/latest.log)

**Comment by CorgiTaco** [comment]
Hold shift on the sapling in your inventory and it'll tell you how to grow it
