### ISSUE TITLE
[Crash]: BYG encountered an error during the complete event phase

### ISSUE THREAD

**Issue by PsychoPeanut** [CorgiTaco/BYG#779]
### Minecraft Version

1.18.2

### BYG Version

Forge 1.4 RC-21

### Terrablender Version

1.1.0.101

### Mod Loader

Forge

### Mod Loader Version

40.1.23

### What happened?

Minecraft loads normally at first but won't go through to the main menu due to an error with the BYG mod. I get the failure message: "Oh The Biomes You'll Go (byg) encountered an error during the complete event phase."

I have tried to run Minecraft with only the mods Optifine, BYG and Terrablender, and I still get the same message, so it's not a mod conflict.

![Minecraft error message](https://user-images.githubusercontent.com/106163573/170048820-1fad76ce-269c-44bd-a94c-d9b14f93a71e.PNG)

### crash-log

[crash-2022-05-24_15.21.37-fml.txt](https://github.com/AOCAWOL/BYG/files/8763167/crash-2022-05-24_15.21.37-fml.txt)

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/8763231/latest.log)

**Comment by CorgiTaco** [comment]
Delete your configs and let them regenerate!
