### ISSUE TITLE
[Bug]: Unable to Generate Biomes

### ISSUE THREAD

**Issue by SoloLevelingKirk1667** [CorgiTaco/BYG#780]
### Minecraft Version

1.18.2

### BYG Version

1.4-RC-21

### Terrablender Version

1.1.0.101

### Mod Loader

Forge

### Mod Loader Version

Forge 40.1.0

### Bug Severity

Major

### What happened?

Upon generating a world I flew around for a bit and was unable to find any BYG biomes. I could not find any biomes whatsoever. Even using the /locatebiomes command, didn't show any BYG biomes. Just vanilla ones. I have no idea if I am doing something wrong and everyone else seems to be able to generate just fine.
![IMG_0121](https://user-images.githubusercontent.com/79057648/170719970-f9b9a05a-081f-473b-bebc-1a2ce6a8c7a1.jpeg)

### latest.log

Here is the latest log.
![IMG_0120](https://user-images.githubusercontent.com/79057648/170719843-654de4b5-a284-4ad7-9e27-3ea6c93934fe.jpeg)

**Comment by SoloLevelingKirk1667** [comment]
Just discovered that apparently I can't place any BYG sapling. I try to place it and the model is there for a millisecond but then glitches out and disappears as if I can't do anything. Furthermore, non-vanilla spawn eggs do not work or spawn anything.

**Comment by CorgiTaco** [comment]
Send the files not pictures of your logs

**Comment by CorgiTaco** [comment]
This should no longer be an issue, if you still get this issue please comment/reopen this issue. Ensure you're using the latest versions of all mods relating to world generation and Terrablender!
