### ISSUE TITLE
[Crash]: 

### ISSUE THREAD

**Issue by Diababloss** [CorgiTaco/BYG#781]
### Minecraft Version

1.16.5

### BYG Version

1.3.5

### Terrablender Version

N/A

### Mod Loader

Forge

### Mod Loader Version

36.2.34

### What happened?

What i've done:

Built a nether portal... And immediately unable to reach the nether. "server internal error"

So i went to the faq to deal with the nbtexplorer and level.dat... Not working on the first try with server files... But it worked on a solo world... :) I then copy/paste that nether dimension to the server folder and... It worked! I was able to reach the nether.

But now, after i step into the nether, i get kicked for a "ticking server" stuff....

### crash-log

[crash-2022-05-27_22.47.54-server.txt](https://github.com/AOCAWOL/BYG/files/8789684/crash-2022-05-27_22.47.54-server.txt)

### latest.log

[2022-05-27-1.log.gz](https://github.com/AOCAWOL/BYG/files/8789687/2022-05-27-1.log.gz)

Oh and yeah sry here's a mod list too:

[mid mad mod.ods](https://github.com/AOCAWOL/BYG/files/8790036/mid.mad.mod.ods)

**Comment by supermassimo** [comment]
This is a crash with Dynamic Trees - BYG
I am currently looking into it, will update as soon as possible

**Comment by supermassimo** [comment]
Should be fixed on [1.0.1](https://www.curseforge.com/minecraft/mc-mods/dynamic-trees-byg/files/3808090)
