### ISSUE TITLE
Hundreds of textures are getting loaded and its crashing myself and friends.[Bug]: 

### ISSUE THREAD

**Issue by animekin12** [CorgiTaco/BYG#785]
### Minecraft Version

1.16.5

### BYG Version

1.3.5

### Terrablender Version

N/A

### Mod Loader

Forge

### Mod Loader Version

36.2.35

### Bug Severity

Major

### What happened?

So this has been going on for a week and a half. I talked to support from Apex Hosting which is the provider of the server and after looking at the logs they told me everyone was crashing due to oh the biomes you'll go loading hundreds of textures. I tested biomes of plenty as well and the issue remained. We can't even stay on the server for more than 5 mins. When I removed the mod all the issues vanished and everything worked perfectly. I really Love the mod and would like to keep it so if there are any suggestions to fix this I'm open to listening.

### latest.log

https://mclo.gs/6BvKrGK

https://mclo.gs/Sp1rXG2

**Comment by CorgiTaco** [comment]
please provide pictures of what you mean

**Comment by animekin12** [comment]
> please provide pictures of what you mean

How am I supposed to take a picture of something like that?

**Comment by CorgiTaco** [comment]
Looking at the logs, this issue seems to stem from numerous other issues in mods not related to BYG.

## Highlights in your logs
### Chisel:
```
[30May2022 11:05:14.574] [main/ERROR] [Chisel/]: java.lang.NullPointerException
```
### Agricraft:
```
 Found a broken recipe: AgriCraft agricraft:tank class com.infinityraider.infinitylib.crafting.dynamictexture.ShapedDynamicTextureRecipe
```
### AOA3
```
[30May2022 10:40:38.818] [main/ERROR] [net.minecraft.loot.LootTableManager/]: Couldn't parse loot table aoa3:entities/amphibior
```
