### ISSUE TITLE
[Bug]: Biomepedia Gift

### ISSUE THREAD

**Issue by AFKafe** [CorgiTaco/BYG#788]
### Minecraft Version

1.18.2

### BYG Version

1.4-RC-23

### Terrablender Version

1.1.0.101

### Mod Loader

Forge

### Mod Loader Version

40.1.25

### Bug Severity

Minor

### What happened?

Greetings

I would like to be able to remove the biomepedia donation on first login. I can't find a config to do this. I've disabled everything but it keeps popping up so I feel like there's no way to not get it on the first login.

Would it be possible to add this possibility in a config file please.

Thanks for your mod

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/8823751/latest.log)

**Comment by AFKafe** [comment]
I can go through a datapack (which I will do) but I think it can be nice to add a config file to modify this option

**Comment by CorgiTaco** [comment]
Unfortunately a datapack is the only way for this. Edit this file: https://github.com/AllTheMods/ATM-7/commit/414165d2a1d9373874d2ca1e513ce77f8c085f48

**Comment by Gamerbolts** [comment]
I need some help. I want to remove the book from spawning as well. I created the resource pack I have the pack.mcmeta and the path is data/byg/advancements/biomepedia_gift.json I got the file from the link above. I don't understand where I need to edit it to stop the book from spawning? I tried the file as is and the book still spawns. Please help.
