### ISSUE TITLE
[Bug]: Red Oak Saplings do not show growth patterns

### ISSUE THREAD

**Issue by Angular-Angel** [CorgiTaco/BYG#789]
### Minecraft Version

1.18.2

### BYG Version

1.4-rc23

### Terrablender Version

Latest

### Mod Loader

Forge

### Mod Loader Version

Latest

### Bug Severity

Minor

### What happened?

Red oak saplings do not show what pattern they need to be planted in when you mouse over them.

### latest.log

Not needed.

**Comment by CorgiTaco** [comment]
Closed by: https://github.com/AOCAWOL/BYG/commit/05cbc956923192c848f00024607c42dff8130f32
