### ISSUE TITLE
Log Spam

### ISSUE THREAD

**Issue by Afrocntrik** [CorgiTaco/BYG#79]
![image](https://user-images.githubusercontent.com/11052983/91954279-988d3d80-eccf-11ea-85c7-35c6ae9ce241.png)
![image](https://user-images.githubusercontent.com/11052983/91954515-e5711400-eccf-11ea-9403-4061ede406ff.png)

Unsure of the root cause, however I know it happens constantly

![image](https://user-images.githubusercontent.com/11052983/91954687-2537fb80-ecd0-11ea-995f-0cf7497b47d5.png)

**Comment by CorgiTaco** [comment]
What version and modloader?

**Comment by Afrocntrik** [comment]
byg-1.0.6 checked just now
fabric 0.9.2+build.206

**Comment by Afrocntrik** [comment]
Nevermind, it was the Bumblezone
