### ISSUE TITLE
[Crash]: New Versions Crashing

### ISSUE THREAD

**Issue by Stally3** [CorgiTaco/BYG#792]
### Minecraft Version

1.18.2

### BYG Version

1.4-RC-24

### Terrablender Version

1.1.0.102

### Mod Loader

Forge

### Mod Loader Version

40.1.0

### What happened?

Playing the new updates from 5/31 6/1 6/2 crashes from failing to load a boat I guess? Error: java.lang.IllegalArgumentException: Failed to create model for byg:boat

### crash-log

[crash-2022-06-03_23.10.05-client.txt](https://github.com/AOCAWOL/BYG/files/8836910/crash-2022-06-03_23.10.05-client.txt)

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/8836908/latest.log)

**Comment by CorgiTaco** [comment]
Delete your trade's config and let it regen
