### ISSUE TITLE
[Crash]: Crashing on Startup

### ISSUE THREAD

**Issue by AnxiousWizardry** [CorgiTaco/BYG#793]
### Minecraft Version

1.18.2

### BYG Version

1.18.2-1.4-RC-24

### Terrablender Version

1.18.2-1.1.0.102

### Mod Loader

Fabric

### Mod Loader Version

fabric-loader-0.14.6-1.18.2

### What happened?

My friends and I are trying to update the server we play on that has a few mods on them. For some reason, BYG keeps crashing, and I have tested it with every mod we have, and then by itself. I've tried terrablender versions .99-.102 with no change, and a few of the slightly older BYG versions (18, 17, 15, 14, 12), and of course the most current version (24). We just updated all of the mods we use, to make sure nothing is out of date. I have included screenshots of all the mods that we're using, and I did make sure to go through them, so I'm not sure what's happening, or how to fix it, so I'd appreciate the help. Please and thank you.
![mods part 1](https://user-images.githubusercontent.com/106869855/171997685-b8d1ea98-5dc5-42d0-b9d9-bda694ca0e7b.png)
![mods part 2](https://user-images.githubusercontent.com/106869855/171997689-9277c0e6-5969-4a51-bcf2-5f9f58847033.png)

### crash-log

[crash-2022-06-04_07.34.34-client.txt](https://github.com/AOCAWOL/BYG/files/8837603/crash-2022-06-04_07.34.34-client.txt)

### latest.log

[2022-06-04-7.log](https://github.com/AOCAWOL/BYG/files/8837618/2022-06-04-7.log)

**Comment by CorgiTaco** [comment]
Delete your config folder
