### ISSUE TITLE
[Bug]: Village Generation 

### ISSUE THREAD

**Issue by Stally3** [CorgiTaco/BYG#794]
### Minecraft Version

1.18.2

### BYG Version

1.4-RC-24

### Terrablender Version

1.1.0.102

### Mod Loader

Forge

### Mod Loader Version

40.1.0

### Bug Severity

Minor

### What happened?

Fix the villages either getting spawned next to other mod structures or either having it spawn under each other or entirely underground. Also, this isn't compatible with the waystones mod, and trees or biome generation gets inside the village homes.
![2022-06-04_11 22 23](https://user-images.githubusercontent.com/106846782/172013094-4464a66e-12af-45f4-bba6-2c3046314cdc.png)
![2022-06-04_11 24 23](https://user-images.githubusercontent.com/106846782/172013095-459d0cc3-c4de-4efb-8ca2-e4af5771044c.png)
![2022-06-04_11 24 56](https://user-images.githubusercontent.com/106846782/172013096-10e1f574-5043-404b-87b1-3d7369b0ce63.png)
![2022-06-04_11 27 26](https://user-images.githubusercontent.com/106846782/172013097-1315e6fc-3210-42c6-8968-c3b1a6a70a51.png)
![2022-06-04_11 27 34](https://user-images.githubusercontent.com/106846782/172013098-7cda6cc7-5963-4874-97a8-c73dcfb8c9d4.png)
![2022-06-04_11 28 47](https://user-images.githubusercontent.com/106846782/172013099-60a4b3a7-868e-4189-8491-b97d6e92f81c.png)
![2022-06-04_11 29 05](https://user-images.githubusercontent.com/106846782/172013101-0c83e292-9918-48c5-81bc-a3c414d8a443.png)
![2022-06-03_18 21 53](https://user-images.githubusercontent.com/106846782/172013102-260d7225-335b-4ce0-95c8-5fec9a605e4a.png)

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/8838158/latest.log)

**Comment by CorgiTaco** [comment]
A few points:
- if you're worried about the structures spawning near other structures, you'll need to make structure sets via datapacks to ensure they never spawn near each other, and BYG will not be adding support for every single mod on its own, that's for the user to do.
- Way stones mod should add support for modded villages, that's on them if they don't add a way to do so, not our issue to deal with.

My question is, are you using the vanilla chunk generator? Or are you using a modded one like terraforged or terralith?

**Comment by Stally3** [comment]
No, I don't use terraforged or terralith I just use the biome mods or those extra dungeons mods. The only thing I have that might be modded is the chunk renderer for better fps.

**Comment by CorgiTaco** [comment]
Yeah, I don't think this an issue ultimately, just the quirks of vanilla world gen
