### ISSUE TITLE
[RESOLVED]: Leaves decaying causing major performance issues

### ISSUE THREAD

**Issue by RS785** [CorgiTaco/BYG#796]
### Minecraft Version

1.18.2

### BYG Version

Oh_The_Biomes_You'll_Go-fabric-1.18.2-1.4-RC-24

### Terrablender Version

TerraBlender-fabric-1.18.2-1.1.0.102

### Mod Loader

Fabric

### Mod Loader Version

fabric-api-0.55.1+1.18.2 (&) fabric-loader 0.14.6

### Bug Severity

Major

### What happened?

When generating chunks, leaves from BYG's trees slowly start decaying and drop items.
**It easily ramps up to over 5k items causing major performance issues.**

### latest.log

LATEST LOG: https://gist.github.com/RS785/39ee30ae7521193573f763ce8c8011d

![2022-06-05_18 23 03](https://user-images.githubusercontent.com/77481854/172060378-a6006dbb-09a5-45f3-b33a-8223ddd68079.png)

**Comment by CorgiTaco** [comment]
Your latest log link doesn't work buts it's been reported that this issue is caused by wilder world, so remove that.

**Comment by RS785** [comment]
Thank you very much!
