### ISSUE TITLE
[Bug]: Cannot till Lush Grass or Lush Dirt into Lush Farmland.

### ISSUE THREAD

**Issue by Angular-Angel** [CorgiTaco/BYG#797]
### Minecraft Version

1.18.2

### BYG Version

1.4-rc24

### Terrablender Version

1.1.0.99

### Mod Loader

Forge

### Mod Loader Version

40.1.22

### Bug Severity

Minor

### What happened?

Right clicking on lush grass and lush dirt with a hoe to make farmland does not work. It works normally on normal dirt, however.

### latest.log

None.

**Comment by magsum** [comment]
Still not fixed as of today.

**Comment by moon-st0ne** [comment]
still untouched

**Comment by unweeked** [comment]
Still not fixed :/

**Comment by kedamono** [comment]
Same problem in 1.19.2. Cannot till Lush Grass or Lush Dirt into Lush Farmland. You can use a shovel and turn it into a path however.

**Comment by thompson8964** [comment]
i still have this problem

**Comment by Suiwelmaan** [comment]
this still sucks

**Comment by NielsPilgaard** [comment]
This hasn't been fixed in 1.18.2 yet sadly, any chance the fix could be backported?
