### ISSUE TITLE
[Crash]: BYG cannot work on the Mohist(1.18.2-40.1.47-56) Server

### ISSUE THREAD

**Issue by Acerie** [CorgiTaco/BYG#799]
### Minecraft Version

1.18.2

### BYG Version

1.18.2-1.4-Release&RC24

### Terrablender Version

1.1.0.102&101

### Mod Loader

Forge

### Mod Loader Version

forge-1.18.2-40.1.47

### What happened?

When I want to add BYG to server Mohist(1.18.2-40.1.47-56), the server cannot start properly and reported this error:
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Invalid descriptor on byg.mixins.json
The reported error is too long. For details, see the debug.log(crash-log) and latest.log below.

I tried rolling back BYG to an older version, but the error still exists.

### crash-log

https://bytebin.lucko.me/EruRSEX8G7

### latest.log

https://bytebin.lucko.me/JWbyH5Oiqi

**Comment by CorgiTaco** [comment]
@Acerie can you recreate this issue with 11.14(latest) BYG?

**Comment by Acerie** [comment]
> 

Yes, I used the latest version(curseforge: 2022/6/6_11:50PM) of BYG and the error still exists

**Comment by Acerie** [comment]
@CorgiTaco Yes, I used the latest version(curseforge: 2022/6/6_11:50PM) of BYG and the error still exists

**Comment by CorgiTaco** [comment]
@Acerie could you verify on a normal forge server this is also the case?

**Comment by Acerie** [comment]
@CorgiTaco After verifying, on a normal forge server, BYG works

**Comment by CorgiTaco** [comment]
@Acerie this tells me this is a Mohist conflict, and that means BYG doesn't support Mohist then unfortunately, sorry about that :/

**Comment by CorgiTaco** [comment]
Mohist as I've heard does have a tendency to conflict with mods using mixin and BYG unfortunately has too
