### ISSUE TITLE
1.15.2 crash upon entering the Nether

### ISSUE THREAD

**Issue by katubug** [CorgiTaco/BYG#8]
Hi! Just got a crash upon attempting to enter the Nether in a test world in a modpack I'm working on.

Here's the crash: https://pastebin.com/MjK4mxN1

Here are my versions:
MC: 1.15.2
Forge: 31.2.30
BYG: 1.0.2
MixinBootstrap: 1.0.3

Here's an excerpt from the stacktrace for googling purposes: `The game crashed whilst biome decoration
Error: java.lang.ClassCastException: net.minecraft.world.gen.feature.ReplaceBlockConfig cannot be cast to net.minecraft.world.gen.feature.DecoratedFeatureConfig`

In an existing world, I made a Nether portal in creative and stepped into it. The game crashed to desktop shortly thereafter. When I loaded my game back up, I was still in the overworld standing next to the portal. I tried removing OptiFine/OptiForge in case that was the issue, but that did not fix it. I also removed The Abyss Project just in case that was the issue, but that wasn't it either.

I'm currently attempting with a completely reset config folder, will report back if I find anything interesting. For now, I'm posting this in case there's something obvious that I've missed.

Edit: No dice on the config reset. Downgrading forge to .28 to see if that helps.

Edit 2: Nope. Same crash. I'm gonna join your discord. xD

**Comment by CorgiTaco** [comment]
Fix:
http://www.mediafire.com/file/7xrnqegyvanqnqw/byg-1.0.3.jar/file

Going to leave the issue open for anyone else until I upload the file to curse.

**Comment by CorgiTaco** [comment]
This issue has been resolved
