### ISSUE TITLE
[Bug]: Holly Berry leaves drop sweet berries, instead of Holly Berries.

### ISSUE THREAD

**Issue by Angular-Angel** [CorgiTaco/BYG#802]
### Minecraft Version

1.18.2

### BYG Version

1.4

### Terrablender Version

1.1.0.99

### Mod Loader

Forge

### Mod Loader Version

40.1.22

### Bug Severity

Minor

### What happened?

When you chop down a holly tree, the berry leaves drop sweet berries, instead of holly berries. Given that holly berries are still in the game, I assume this is unintentional?

### latest.log

None

**Comment by CorgiTaco** [comment]
Intentional, we felt holly berries were pointless due to the similarities of sweet berries

**Comment by Angular-Angel** [comment]
Ah, and holly berries are still in the game for backwards compatibility purposes?

**Comment by CorgiTaco** [comment]
probably?

**Comment by Angular-Angel** [comment]
Mmm, I see! XD
