### ISSUE TITLE
[Crash]: Oh The Biomes You'll Go (byg) encountered an error during thr common_setup event phase

### ISSUE THREAD

**Issue by PurpleRose44** [CorgiTaco/BYG#803]
### Minecraft Version

1.18.2

### BYG Version

1.18.2-1.4.jar

### Terrablender Version

1.18.2-1.1.0.102

### Mod Loader

Forge

### Mod Loader Version

1.18.2

### What happened?

Just doesnt work, byg has worked before but has now just randomly stopped which upsets me cause most of the cool looking areas around my base have now gone into vanilla D: (sorry if this is the wrong place to report this)

### crash-log

Oh The Biomes You'll Go (byg) encountered an error during thr common_setup event phase
java.lang.IllegalStateException: config errors were found:

### latest.log

Oh The Biomes You'll Go (byg) encountered an error during thr common_setup event phase
java.lang.IllegalStateException: config errors were found:

**Comment by Matyrobbrt** [comment]
Please share the logs.

**Comment by Orgamorsh** [comment]
Allow me to put my logs here because I have the same error.

1.18.2 Forge 40.1.41

Crash Log: https://pastebin.com/eiAc4RB0

Latest Log: https://pastebin.com/s2K4WLjZ

**Comment by Orgamorsh** [comment]
Ok, Fixed my issues. I had outdated configs. Just deleted the config folder for BYG

**Comment by PurpleRose44** [comment]
> Ok, Fixed my issues. I had outdated configs. Just deleted the config folder for BYG

Thank you very much, this worked for me as well!

**Comment by iAmNoobAtMinecraft** [comment]
I deleted the config files, but instead of working, it just crashes the game without even opening minecraft.
my friend has the same mod, but he has no problems and can join the server without crashing.
can someone tell me why?

**Comment by iAmNoobAtMinecraft** [comment]
also i forgot but this is the crash log
crash log: [crash-2022-06-10_14.43.02-fml.txt](https://github.com/AOCAWOL/BYG/files/8878893/crash-2022-06-10_14.43.02-fml.txt)
latest log: [latest.log](https://github.com/AOCAWOL/BYG/files/8878930/latest.log)
so if anyone helps me i'd be happy since i wanna play this mod.
and to delete the config i went on potionstudios\byg\config and i deleted config and it gave me exit code -1
then i went on potionstudios\byg\config\json and i deleted json and it gave me exit code -1
i really dont know what to do, this thing makes no sense.

**Comment by BelgianSalamander** [comment]
The issue seems to be with config/byg/overworld-biomes.json. Specifically it appears to be missing a "shattered_biomes"section. Have you tried deleting that file?

**Comment by iAmNoobAtMinecraft** [comment]
sorry man i deleted it long ago, i forgot to write that, im just dumb, thanks anyways.

**Comment by THFOL** [comment]
I have the same problem, please let me leave my crash lo
[latest.log](https://github.com/AOCAWOL/BYG/files/8965348/latest.log)
[crash-2022-06-23_16.13.53-fml.txt](https://github.com/AOCAWOL/BYG/files/8965351/crash-2022-06-23_16.13.53-fml.txt)
g

**Comment by THFOL** [comment]
Can you help me with my problem
[latest.log](https://github.com/AOCAWOL/BYG/files/8973370/latest.log)
[crash-2022-06-23_16.13.53-fml.txt](https://github.com/AOCAWOL/BYG/files/8973372/crash-2022-06-23_16.13.53-fml.txt)
?

**Comment by VistorFertil** [comment]
can you help me plis?
[crash-2022-07-26_21.02.26-fml.txt](https://github.com/AOCAWOL/BYG/files/9194247/crash-2022-07-26_21.02.26-fml.txt)

**Comment by CorgiTaco** [comment]
Reset your configs!
