### ISSUE TITLE
[Bug]: Lament Saplings Vanishing

### ISSUE THREAD

**Issue by Idefkftt** [CorgiTaco/BYG#806]
### Minecraft Version

1.18.2

### BYG Version

1.4

### Terrablender Version

N/A

### Mod Loader

Fabric

### Mod Loader Version

0.55.1

### Bug Severity

Minor

### What happened?

Wandering trader selling both Ether Saplings and Lament Saplings, on placing, Ether Saplings respond as expected to bonemeal and grow into trees.  Lament Saplings, however, simply despawn with no tree afterwards.

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/8869948/latest.log)

**Comment by dusty-blue** [comment]
I ran into the same issue running MC 1.19.2, Fabric Loader 0.14.21, Fabric API 0.76.0, BYG  2.0.1.4, Terra Blender 2.0.1.130 (running an older version for compatibility with Nullscape).  
Looking at this bug report [https://github.com/EnigmaticaModpacks/Enigmatica6/issues/5042](url) I thought it might be height related. Tested it on mycelium and it will only grow below or at y=100 in the overworld.
