### ISSUE TITLE
Recipe Book [Bug]: 

### ISSUE THREAD

**Issue by ricardo-jn** [CorgiTaco/BYG#809]
### Minecraft Version

1.18.2

### BYG Version

Oh_The_Biomes_You'll_Go-forge-1.18.2-1.4-RC-24

### Terrablender Version

TerraBlender-forge-1.18.2-1.1.0.102

### Mod Loader

Forge

### Mod Loader Version

forge-1.18.2-40.1.0-installer

### Bug Severity

Major

### What happened?

The minecraft recipe book has been replaced by the biome mod book. When I press the "E" key to open my inventory, the recipe book is the one from the mod and not the one from minecraft. And the minecraft recipe book has disappeared when using a crafting table.

### latest.log

https://mclo.gs/jLc0Ttt

**Comment by CorgiTaco** [comment]
We don't replace the recipe book and please use the latest version of BYG. Also use the biomepedia config in the `byg/client` to change the button position
