### ISSUE TITLE
[Crash]: Placed Maple Sign, then Crashed

### ISSUE THREAD

**Issue by GrimWolf47** [CorgiTaco/BYG#810]
### Minecraft Version

1.18.2

### BYG Version

1.4.1

### Terrablender Version

1.1.0.102

### Mod Loader

Forge

### Mod Loader Version

40,1,31

### What happened?

Seems to be a mod incompatibility, but I was just building a greenhouse in my smp, then when I placed a Maple Sign on some leaves it crashed me, but not the server, so I tried to have my friend break it, and then it crashed him as well, neither of us can join back now as we instantly crash when within 100 blocks of the sign

### crash-log

[crash-2022-06-11_01.04.51-client.txt](https://github.com/AOCAWOL/BYG/files/8883382/crash-2022-06-11_01.04.51-client.txt)

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/8883391/latest.log)

**Comment by CorgiTaco** [comment]
I cannot replicate this issue, you'd need to figure out this mod incompatibility yourself i think

**Comment by QNHaming159** [comment]
**Minecraft Version**
1.18.2
**BYG Version**
1.14.1
**Terrablender Version**
1.1.0.102
**Mod Loader**
1.18.2-forge-40.1.51

I have a same inssue, when I placed **byg:cherry_sign** then it crashed my game but not server.
To join my own server, I use **NBTExplorer** to change my position far away from the sign. But got crash again when I go straight to the sign.
I use command to *delete* that sign, and everything go normal again.

**Server-log** (appear when re-join then get crash again):
[Netty Server IO #19/ERROR] [minecraft/ArgumentTypes]: Could not serialize io.github.apace100.apoli.command.PowerSourceArgumentType@769dadd1 (class io.github.apace100.apoli.command.PowerSourceArgumentType) - will not be sent to client!

**Crash-log, client-side**
[crash-2022-06-13_21.45.51-client.txt](https://github.com/AOCAWOL/BYG/files/8892162/crash-2022-06-13_21.45.51-client.txt)

**Comment by Sakreton** [comment]
Minecraft Version
1.18.2
BYG Version
1.14.1
Terrablender Version
1.1.0.102
Mod Loader


1.18.2-forge-40.1.51

Same Issue, placed a Cherry sign and had to load a backup since i crashed instantly, again client side, server was fine, everyone who loaded the chunk with the sign crashed as well

[crash-2022-06-13_21.53.30-client.txt](https://github.com/AOCAWOL/BYG/files/8897618/crash-2022-06-13_21.53.30-client.txt)

**Comment by Sakreton** [comment]
The list of mods i use, maybe the other two crashes can post theirs as well so we can search for similarities. 
I renamed the file from html to txt since github does not allow html files here.

[modlist.txt](https://github.com/AOCAWOL/BYG/files/8897631/modlist.txt)

**Comment by GrimWolf47** [comment]
> The list of mods i use, maybe the other two crashes can post theirs as well so we can search for similarities. I renamed the file from html to txt since github does not allow html files here.
> 
> [modlist.txt](https://github.com/AOCAWOL/BYG/files/8897631/modlist.txt)

I'll post my modlist here in a sec

**Comment by GrimWolf47** [comment]
> The list of mods i use, maybe the other two crashes can post theirs as well so we can search for similarities. I renamed the file from html to txt since github does not allow html files here.
> 
> [modlist.txt](https://github.com/AOCAWOL/BYG/files/8897631/modlist.txt)
Here's the Mods I use, 

[Modlist.txt](https://github.com/AOCAWOL/BYG/files/8904493/Modlist.txt)

**Comment by CorruptData404** [comment]
I also am experiencing this same bug. Modlist is also in crash report.
[crash-2022-06-14_22.26.49-client.txt](https://github.com/AOCAWOL/BYG/files/8905985/crash-2022-06-14_22.26.49-client.txt)
 
 Also interestingly another player was using the maple signs just fine beforehand. This issue started with the rainbow eucalyptus for me.

**Comment by Legagit** [comment]
Same here. With a cherry wood sign.
[modlist.txt](https://github.com/AOCAWOL/BYG/files/8911035/modlist.txt)

To fix, I did as an above user mentioned and changed my player's position via NBTExplorer (thanks for that) but using a command to remove the block didn't seem to work, so I used an rf tools builder to remove a 10x10 area where the sign was placed. You can get about 100 blocks away and said builder has a max offset of 512 blocks so it should be reproducible for anyone with the mod.

**Comment by GrimWolf47** [comment]
> Same here. With a cherry wood sign. [modlist.txt](https://github.com/AOCAWOL/BYG/files/8911035/modlist.txt)
> 
> To fix, I did as an above user mentioned and changed my player's position via NBTExplorer (thanks for that) but using a command to remove the block didn't seem to work, so I used an rf tools builder to remove a 10x10 area where the sign was placed. You can get about 100 blocks away and said builder has a max offset of 512 blocks so it should be reproducible for anyone with the mod.

We have several of the same mods, not sure how or why some would cause the crash but the common mods are, Supplementaries, Sophisticated Backpacks, Tinkers Construct, Appleskin, Artifacts, Carryon, Cosmetic Armor, Polymorph, Dark Paintings, Mekanism and its addons, Mystical Agriculture and Agraditions, Repurposed Structures, Waystones, Quark, and Yungs better dungeons

**Comment by zoogl-e** [comment]
From Fabric. Got an issue where two of my friends placed a cherry sign and rendering it caused the client to crash. Used worldedit to remove the block. The crash log specifically mentioned it was "byg:cherry_wall_sign" that made it crash.

**Comment by zoogl-e** [comment]
Ebony signs did the same.

**Comment by 03amaldo83** [comment]
> Supplementaries, Sophisticated Backpacks, Tinkers Construct, Appleskin, Artifacts, Carryon, Cosmetic Armor, Polymorph, Dark Paintings, Mekanism and its addons, Mystical Agriculture and Agraditions, Repurposed Structures, Waystones, Quark, and Yungs better dungeons

Just tried making a pack with said mods and with rubidium and oculus and it worked fine placing signs.  However my modpack still crashes.
Mod list here:
[modlist.txt](https://github.com/AOCAWOL/BYG/files/8935710/modlist.txt)

**Comment by MattB70** [comment]
I have a very similar modlist with the same issue. I **do not** have:
- Carryon
- Mekanism
- Mystical Agriculture
- Waystones

**Comment by getBoolean** [comment]
I also encountered this crash

[Crash report](https://crashy.net/x5ABC9mv7DFXDcWNVm1y)

[Mod list](https://gist.github.com/getBoolean/31845e82e6ae366f3cc31783793702fa)

To rescue the player, I teleported them out by editing their playerdata file with [NbtStudio](https://github.com/tryashtar/nbt-studio). Then I removed the block in the region file using [Amulet](https://www.amuletmc.com/). If your world save is too big to download from a server, identify which region file the sign is in using the crash report and download only that and paste it into a new world on your computer. Open that world with Amulet, delete the sign, then reupload that region file to the server. It'll have a missing texture for modded blocks but you know the exact coords from the crash report

I then banned all BYG signs just to be safe using [Item Banning](https://www.curseforge.com/minecraft/mc-mods/item-banning) and removed recipes using [Craft Tweaker](https://www.curseforge.com/minecraft/mc-mods/crafttweaker). Script: `craftingTable.removeByRegex(".*byg:.*sign");`

**Comment by nmurphy101** [comment]
I've also experienced this same bug in a multi-modded server. Placing any of this mod's signs into the world triggers a error on render for anybody that can see it. Followed @getBoolean 's solution of just editing the world with Amulet and that allowed me to delete the sign.

**Comment by BiskaWolf** [comment]
Ah, not just me then. We're having the same issue with the Signs from this modpack. If anyone walks up close to them, they crash (server does not).

**Comment by Raven1050** [comment]
I am having the same issue in Fabric.
[Crash report](https://crashy.net/H5YjAOCyFQerzeEX8X1U)
[Mod list](https://pastebin.com/RCnDwb4K)
The game appears to crash every time a player loads a chunk with any sign from BYG. The weird thing to me is that both Forge and Fabric clients experience these crashes.

**Comment by opalfire** [comment]
I also have this bug in Fabric.
For now seems like the best fix is to just ban the signs using the Item Banning mod.

**Comment by Raven1050** [comment]
> For now seems like the best fix is to just ban the signs using the Item Banning mod.

The mod is not ported to Fabric

**Comment by MattB70** [comment]
With repeating command blocks you can use the /clear command to achieve the same effect, but of course that will only help on a server.

**Comment by purejosh** [comment]
[crash-2022-06-26_19.47.32-client.txt](https://github.com/AOCAWOL/BYG/files/8988085/crash-2022-06-26_19.47.32-client.txt)

Mods list: 
Terrablender
Terralith
FabricAPI
FabricProxyLite
BYG

https://user-images.githubusercontent.com/70633949/175845622-5d2862d9-5591-41fa-83d8-98a3b0938e0c.mp4

@AOCAWOL 
In my world, I place a baobab sign down, and instantly get kicked.

**Comment by purejosh** [comment]
I loaded these mods only, and it crashed. 

TerraBlender-fabric-1.18.2-1.1.0.102
Oh_The_Biomes_You'll_Go-fabric-1.18.2-1.4.1
fabric-api-0.56.0+1.18.2

New world, baobab sign crashed it. However, reloading with only those mods on the client side as well makes it work just fine... I think there's a client side issue with the baobab sign. 

Will do more mod elimination.

**Comment by GrimWolf47** [comment]
> I loaded these mods only, and it crashed.
> 
> TerraBlender-fabric-1.18.2-1.1.0.102 Oh_The_Biomes_You'll_Go-fabric-1.18.2-1.4.1 fabric-api-0.56.0+1.18.2
> 
> New world, baobab sign crashed it. However, reloading with only those mods on the client side as well makes it work just fine... I think there's a client side issue with the baobab sign.
> 
> Will do more mod elimination.

alright, I'm pretty sure its just Biomes you'll go's signs are having issues, seems in your video you had terralith installed as well, could possibly be the issue but I somehow doubt its that so I wish you luck with your mod eliminating I might do some testing myself here soon

**Comment by purejosh** [comment]
Found the mod combo that screws it up. (for me, at least)

biomemakeover-FABRIC-1.18.2-1.4.24 on the client (Not even loaded on the server at this moment)
+ 
Oh_The_Biomes_You'll_Go-fabric-1.18.2-1.4.1 on the server

Running this combo causes a crash.

**Comment by purejosh** [comment]
I see other users without biomemakeover having this same crash, and not even on fabric, so there has to be something with the byg mod that's conflicting with something that these other mods use.

**Comment by purejosh** [comment]
[crash-2022-06-26_21.02.06-client.txt](https://github.com/AOCAWOL/BYG/files/8988376/crash-2022-06-26_21.02.06-client.txt)

Client: 
![image](https://user-images.githubusercontent.com/70633949/175852287-5eb48d70-be1d-4930-bc86-1fec650acd46.png)

Server: 
![image](https://user-images.githubusercontent.com/70633949/175852325-b25cede0-fad4-4219-85d3-dc4dcadb4405.png)

**Comment by purejosh** [comment]
I ran that last test without sodium, to see if it was an issue there somewhere, but it looks like it's not. It's gotta be between biomemakeover on the client and byg on the server.

**Comment by MattB70** [comment]
On Forge, this happens without Biomemaker. Perhaps its an Architectury issue?

**Comment by purejosh** [comment]
> On Forge, this happens without Biomemaker. Perhaps its an Architectury issue?

Very, very good chance! I can try running the same tests without biomemakeover, and keep architectury installed, but I'm not even sure it'll init due to no dependents.

**Comment by purejosh** [comment]
Yeah, architectury on both client and server, sign places fine. Unsure if it's being loaded, to be honest, in my case. What's another fabric mod that depends on architectury? I'll install it on both and retest.

**Comment by purejosh** [comment]
Nah, REI uses architectury, and I've got REI on client and server. It's not that, at least, not the way that REI is using the API.
