### ISSUE TITLE
[Crash]: recreating world results in a one-time crash 

### ISSUE THREAD

**Issue by Shibva** [CorgiTaco/BYG#813]
### Minecraft Version

1.18.2

### BYG Version

1.4.1

### Terrablender Version

1.0.102

### Mod Loader

Forge

### Mod Loader Version

40.1.51

### What happened?

The title should be self-explanatory, but this happens when I recreate one of my worlds. the crash doesn't happen again as far as I know it happens once during the world recreation stage.

### crash-log

https://gist.github.com/SteamDoge9000/8b21f11cd1774bf3970f4a70d2fc1718

### latest.log

[2022-06-14-1.log](https://github.com/AOCAWOL/BYG/files/8900379/2022-06-14-1.log)

### Did you isolate BYG?

I did not try BYG alone

**Comment by CorgiTaco** [comment]
This should no longer be an issue, if you still get this crash please comment/reopen this issue. Ensure you're using the latest versions of all mods relating to world generation and Terrablender!
