### ISSUE TITLE
[Bug]: Incompatibility with immersive portals

### ISSUE THREAD

**Issue by NobleDraconian** [CorgiTaco/BYG#815]
### Minecraft Version

1.18.2

### BYG Version

1.4.1

### Terrablender Version

1.1.0.102

### Mod Loader

Fabric

### Mod Loader Version

0.14.7

### Bug Severity

Major

### What happened?

I created a new world using the "dimension stack" feature from [immersive portals](https://www.curseforge.com/minecraft/mc-mods/immersive-portals-mod) with the following dimensions:
```
Skylands 1
Void
Overworld
Nether
```

Upon starting generation for the new world, the game simply crashes. This crash **only** happens if BYG is running.
These are the only mods I have running:
```
BYG
Immersive portals
Fabric API
TerraBlender
Cloth Config v6
```

### latest.log

https://mclo.gs/rn4msvk

### Did you isolate BYG?

I tried BYG alone

**Comment by NobleDraconian** [comment]
Could be related to the issue with datapacks mentioned here in #801 : https://github.com/AOCAWOL/BYG/issues/801#issuecomment-1156471093

**Comment by CorgiTaco** [comment]
This should no longer be an issue, if you still get this crash please comment/reopen this issue. Ensure you're using the latest versions of all mods relating to world generation and Terrablender!
