### ISSUE TITLE
[Crash]: Creating New world Due to New Deep Dark Generation

### ISSUE THREAD

**Issue by ThunderStorm159** [CorgiTaco/BYG#817]
### Minecraft Version

1.19

### BYG Version

2.0.0.4

### Terrablender Version

2.0.0.112

### Mod Loader

Fabric

### Mod Loader Version

0.14.8

### What happened?

It crashes when trying to create a new world file and the issue is the new 1.19 worldgen of the new deep dark.

### crash-log

[crash-2022-06-21_01.04.53-server.txt](https://github.com/AOCAWOL/BYG/files/8944906/crash-2022-06-21_01.04.53-server.txt)

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/8944913/latest.log)

### Did you isolate BYG?

I tried BYG alone

**Comment by CorgiTaco** [comment]
This should no longer be an issue, if you still get this crash please comment/reopen this issue. Ensure you're using the latest versions of all mods relating to world generation.
