### ISSUE TITLE
[Bug]: Pickaxes no longer effective tool for stone types/ores with Excavated Variants

### ISSUE THREAD

**Issue by Baggytrousers27** [CorgiTaco/BYG#818]
### Minecraft Version

1.19

### BYG Version

1.19-2.0.0.4

### Terrablender Version

1.19-2.0.0.113

### Mod Loader

Forge

### Mod Loader Version

41.0.45

### Bug Severity

Major

### What happened?

Ores and stone types are no longer harvestable with pickaxes with Excavated Variants installed. 

With excavated variants (Jade used to show harvestability)
![2022-06-21_21 03 18](https://user-images.githubusercontent.com/15883796/174784819-711f5f72-d96c-44d2-a3d8-c99a9caea82c.png)

![2022-06-21_21 09 09](https://user-images.githubusercontent.com/15883796/174785827-7dc276e4-79a3-491f-aafb-61510abfab1b.png)

Without Excavated Variants
![2022-06-21_21 06 02](https://user-images.githubusercontent.com/15883796/174785343-48c1440a-e2ec-4ffe-8438-7e2886e52da0.png)

### latest.log

[debug.log](https://github.com/AOCAWOL/BYG/files/8948307/debug.log)
[latest.log](https://github.com/AOCAWOL/BYG/files/8948308/latest.log)

### Did you isolate BYG?

I tried BYG alone

**Comment by CorgiTaco** [comment]
Sounds like an issue on their end and not at all BYG's fault. Make sure to use the latest versions of all your mods, it may have been fixed by now!
