### ISSUE TITLE
[Bug]: Empty Tag for Sand Recipes

### ISSUE THREAD

**Issue by Aprucot** [CorgiTaco/BYG#819]
### Minecraft Version

1.19

### BYG Version

1.19-2.0.0.4

### Terrablender Version

1.19-2.0.0.112

### Mod Loader

Forge

### Mod Loader Version

41.0.38

### Bug Severity

Minor

### What happened?

When trying to craft the modded sandstones from sands using the standard 2x2 square in your crafting table no result is given.
The first time I ran this test I had the jei mod installed and it said that there was an "empty tag" in the crafting recipes. I then created a new profile with just byg and terrablender and the crafting recipes still showed nothing. I tried this with all the modded sands provided by byg, none of them worked.

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/8952272/latest.log)

### Did you isolate BYG?

I tried BYG alone

**Comment by Aprucot** [comment]
This is what it looks like

![2022-06-22_09 32 44](https://user-images.githubusercontent.com/107954600/175089314-b18c3814-77ae-49cc-a5e9-ebff5911650e.png)

![2022-06-22_09 33 36](https://user-images.githubusercontent.com/107954600/175089339-d21419b7-9952-4f2e-bb8a-65379288143b.png)

It is like this for all the modded sands except the "windswept sand" which doesn't even give the option to craft ANY of the recipes(sandstone, cut sandstone, chiseled sandstone, stairs, etc.)

**Comment by Jokinha23** [comment]
You need to open the /data/byg/recipes folder (inside the mod file) and search for white_sandstone.json file.
replace {"tag":"c:white_sand"} with {"tag":"byg:white_sand"}

Do this in the other color files inside recipes folder (like purple_sandstone or blue_sandstone)

Don't forget to save before closing.

**Comment by jammin07** [comment]
I have the same issue and cannot find the correct folder to modify the recipes.

**Comment by CorgiTaco** [comment]
Fixed in: https://github.com/AOCAWOL/BYG/pull/1016
