### ISSUE TITLE
Some biomes generating incorrectly with Terralith mod [Bug]: 

### ISSUE THREAD

**Issue by 03amaldo83** [CorgiTaco/BYG#821]
### Minecraft Version

1.18.2

### BYG Version

1.4.1

### Terrablender Version

1.1.0.102

### Mod Loader

Forge

### Mod Loader Version

40.1.51

### Bug Severity

Minor

### What happened?

MOD INCOMPATIBILITY WITH TERRALITH
When making a world with only Terralith and BYG ( + Terrablender) some biomes like the mojave desert and rainbow beach do not generate correctly, only containing grass.  Without Terralith it works normally.  I am also using this as a bug form for Terralith creators Stardust Labs as they do not have a place to submit issues.

### latest.log

https://gist.github.com/03amaldo83/219c1a7743ac2ecb90dfafb7bc3caa5f

### Did you isolate BYG?

I tried BYG alone

**Comment by 03amaldo83** [comment]
![2022-06-22_15 51 34](https://user-images.githubusercontent.com/92743740/175128554-a830c200-1cb6-4787-9913-06072bd65ded.png)
![2022-06-22_15 52 12](https://user-images.githubusercontent.com/92743740/175128560-4a926a19-5e5c-46a8-ac84-5e66ac5a00c5.png)
![2022-06-22_15 59 00](https://user-images.githubusercontent.com/92743740/175128563-deac1304-d733-49f9-a268-76c6e4c60f6f.png)
![2022-06-22_16 09 11](https://user-images.githubusercontent.com/92743740/175128571-6e6480b7-9a1f-4593-8722-e8cd4f775e15.png)

**Comment by rudisec** [comment]
Both are incredible biomes mod, it would be great if they fix this issue in the next update.

**Comment by delpiero224** [comment]
Another issue is that some of the biomes are incredibly small. But it's probably more a Terralith issue rather than one with BYG

**Comment by CorgiTaco** [comment]
Should be fixed in newest terrablender for your MC version
