### ISSUE TITLE
[Crash]: Crashes on bootup, no crash log made

### ISSUE THREAD

**Issue by LordOfTheWeebs** [CorgiTaco/BYG#822]
### Minecraft Version

1.19

### BYG Version

2.0.0.4, 2.0.0.3, 2.0.0.2

### Terrablender Version

2.0.0.113

### Mod Loader

Fabric

### Mod Loader Version

0.14.8-1.19

### What happened?

When attempting to boot up Minecraft with BYG, the Minecraft window just closes. After the launcher closes, about 10-20 seconds pass before the main Minecraft client window appears. When it does, it only appears for about 5 seconds and then immediately closes. The launcher does not return with a crash report, re-opening the launcher doesn't trigger a crash report, and looking in the crash reports folder shows no new crash report.

### crash-log

There is not a crash report generated with any of the versions of BYG mentioned above.

### latest.log

[latest(2.0.0.2).log](https://github.com/AOCAWOL/BYG/files/8966592/latest.2.0.0.2.log)
[latest(2.0.0.3).log](https://github.com/AOCAWOL/BYG/files/8966594/latest.2.0.0.3.log)
[latest(2.0.0.4).log](https://github.com/AOCAWOL/BYG/files/8966595/latest.2.0.0.4.log)

### Did you isolate BYG?

I tried BYG alone

**Comment by CorgiTaco** [comment]
```
java.lang.IllegalArgumentException: Jankson file reading for "/home/dylan/.minecraft/config/byg/trades.json5" failed due to the following error(s):
"byg:mangrove_sapling" is not a valid id in registry: Registry[ResourceKey[minecraft:root / minecraft:item] (Experimental)].
Current Registry Values:
```

Delete your config folder and let it regen.
