### ISSUE TITLE
[Crash]: Crashes on bootup

### ISSUE THREAD

**Issue by LordOfTheWeebs** [CorgiTaco/BYG#823]
### Minecraft Version

1.19

### BYG Version

2.0.0.1

### Terrablender Version

2.0.0.113, 2.0.0.112, 2.0.0.111, 2.0.0.110, 2.0.0.109, 2.0.0.108

### Mod Loader

Fabric

### Mod Loader Version

0.14.8-1.19

### What happened?

When attempting to boot up Minecraft with BYG, the Minecraft window just closes. After the launcher closes, about 5-10 seconds pass before the main Minecraft client window appears. When it does, it only appears for about 5 seconds and then immediately closes. The crash reports are the same regardless of Terrablender version.

I just posted another crash report issue, however due to the actual generation of a crash report and the bootup times being different, I felt it would be best to separate these two issues.

### crash-log

[Uploading crash-2022-06-23_06.56.41-client.txt…]()

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/8966655/latest.log)

### Did you isolate BYG?

I tried BYG alone

**Comment by CorgiTaco** [comment]
The crash log you linked is a link to this issue, latest.log has no mention of any exceptions. 

Try:
1. Delete your config folder
2. Newest BYG
3. Newest Terrablender
