### ISSUE TITLE
[Bug]: Enchanting no longer works with minecraft:bookshelf item

### ISSUE THREAD

**Issue by Aprucot** [CorgiTaco/BYG#824]
### Minecraft Version

1.19

### BYG Version

1.19-2.0.0.4

### Terrablender Version

1.19-2.0.0.112

### Mod Loader

Forge

### Mod Loader Version

41.0.38

### Bug Severity

Major

### What happened?

Tried enchanting a pickaxe at an enchanting table using "regular bookshelves" but for some reason the enchanting table doesn't apply the increased level enchantments. It works fine for the modded bookshelves but it doesn't work with standard ones. There also seems to be a weird rendering bug when placing regular bookshelves that occurs for a few seconds. Basically, Regular Bookshelves are glitchy ;_;

![2022-06-23_13 08 38](https://user-images.githubusercontent.com/107954600/175389027-9d8e5991-d6de-4189-9154-4819fc04b60b.png)

![2022-06-23_13 09 05](https://user-images.githubusercontent.com/107954600/175389071-5b739b7a-a8a3-498a-8990-ce0d8ad67e94.png)

Regular Bookshelf
![2022-06-23_13 08 46](https://user-images.githubusercontent.com/107954600/175389123-3f670c66-5f99-4743-8f0e-0cdc81b261eb.png)

Fir bookshelf
![2022-06-23_13 08 56](https://user-images.githubusercontent.com/107954600/175389156-72d889b9-1204-4898-bdd9-ea3352e38688.png)

Rendering Bug
![2022-06-23_13 11 42](https://user-images.githubusercontent.com/107954600/175390076-0b7f33b9-6b87-4e7b-9713-087a8eef0db2.png)
.

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/8970556/latest.log)

### Did you isolate BYG?

I tried BYG alone

**Comment by gousisme** [comment]
Same issue here, but in survival, you only need 1 to place it endlessly

**Comment by Dak-Darklighter** [comment]
Still experiencing the issues above and players on my server sometimes will place the bookshelves but they will be invisible has there been any updates to this as I’d hate to have to remove this mod from my server as it’s an awesome mod.

**Comment by XJack2X** [comment]
Same issue here, in survival alone and in my dedicated server with my friends.
We can duplicate the bookshelf block endlessly so get infinite books. As you show in your last screenshot, first the block doesnt have any textures but whem braking adyacent block the texture appears. 
The bookshelves doesn´t work for leveling in the enchanting table.
I´ve seen this issue on tiket #317

**Comment by IndolentKheper** [comment]
Oh so THIS mod is the one causing that problem. >:(
