### ISSUE TITLE
[Conflict? Bug?]: Unable to join server with BYG & Every Compat 

### ISSUE THREAD

**Issue by aking4125** [CorgiTaco/BYG#825]
### Minecraft Version

1.18.2

### BYG Version

1.4.1

### Terrablender Version

1.1.0.102

### Mod Loader

Forge

### Mod Loader Version

40.1.52

### Bug Severity

Minor

### What happened?

Hello,
Upon having both this mod and [Every Compat](https://www.curseforge.com/minecraft/mc-mods/every-compat) installed on the server and client. The client disconnects with the following message:

![Capture](https://user-images.githubusercontent.com/11141831/175766261-175d0187-8dc5-4b38-936b-c682485b86c1.PNG)

Should be noted the first number changes around. There is no crash on either side. Disabling either BYG or Every Compat fixes the problem. Config files were entirely reset on both sides. Disabling all BYG entries on the Every Compat config doesn't help at all, either mod needs to be disabled.
I've reported this issue on Every Compats end as well. The mod [Connectivity](https://www.curseforge.com/minecraft/mc-mods/connectivity) gives a bit more insight into the problem possibly.

There could be a 3rd mod conflicting here but so far these two are the prime suspects.

Any ideas?

### latest.log

Here are the log files if anything [Their too large to upload to pastebin or Gist sadly:
Server: [https://www.mediafire.com/file/p9ei1st31fsn2w5/debug.log/file](https://www.curseforge.com/linkout?remoteUrl=https%3a%2f%2fwww.mediafire.com%2ffile%2fp9ei1st31fsn2w5%2fdebug.log%2ffile)
Client [Not much info]: : [https://www.mediafire.com/file/5nh32eqmdnya6x4/debug(2).log/file](https://www.curseforge.com/linkout?remoteUrl=https%3a%2f%2fwww.mediafire.com%2ffile%2f5nh32eqmdnya6x4%2fdebug(2).log%2ffile)

### Did you isolate BYG?

I did not try BYG alone

**Comment by Tempest-5ky** [comment]
Could you please upload the log files to https://mclo.gs/

**Comment by CorgiTaco** [comment]
Yeah what tempest said, feel free to reopen this issue once you do so. I do not trust downloading files from media fire. Try latest BYG & Terrablender versions
