### ISSUE TITLE
[Bug]: Embur Wart doesn't appear when bonemealing Nylium

### ISSUE THREAD

**Issue by ambientNexus** [CorgiTaco/BYG#826]
### Minecraft Version

1.18.2

### BYG Version

1.4.1

### Terrablender Version

1.1.0.102

### Mod Loader

Forge

### Mod Loader Version

40.1.47

### Bug Severity

Minor

### What happened?

No matter how many times I bonemeal Embur Nylium, only Embur Sprouts will appear.

### latest.log

.

### Did you isolate BYG?

I tried BYG alone

**Comment by Greg-J** [comment]
Confirmed this bug is present in the current Fabric version as well, 6 months later. Embur is not renewable.

**Comment by AOCAWOL** [comment]
Patched and will be in our next update!

**Comment by Greg-J** [comment]
When's the next update?
