### ISSUE TITLE
[Bug]: error on starting up

### ISSUE THREAD

**Issue by w1sh1ngwellz** [CorgiTaco/BYG#827]
### Minecraft Version

1.19

### BYG Version

1.19.-2.0.0.4

### Terrablender Version

1.19-2.0.0.112

### Mod Loader

Forge

### Mod Loader Version

1.19

### Bug Severity

Major

### What happened?

Tried to start up forge minecraft, gave error message shown below. tried closing mc and opening again, same thing.
![image](https://user-images.githubusercontent.com/108203054/175796109-aecc86b4-a95e-4f14-8dee-6cf5cf845340.png)

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/8985834/latest.log)

### Did you isolate BYG?

I tried BYG alone

**Comment by CorgiTaco** [comment]
reset your trade config
