### ISSUE TITLE
[Crash]: Crash on startup with BYG 1.19 2.0.0.5

### ISSUE THREAD

**Issue by Baggytrousers27** [CorgiTaco/BYG#828]
### Minecraft Version

1.19

### BYG Version

1.19 2.0.0.5

### Terrablender Version

1.19 2.0.0.113

### Mod Loader

Forge

### Mod Loader Version

41.0.45

### What happened?

The game crashed whilst rendering overlay
Error: java.lang.NullPointerException: Registry Object not present: minecraft:empty
Exit Code: -1

### crash-log

[crash-2022-06-26_13.36.15-client.txt](https://github.com/AOCAWOL/BYG/files/8985933/crash-2022-06-26_13.36.15-client.txt)

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/8985934/latest.log)
[debug.log](https://github.com/AOCAWOL/BYG/files/8985935/debug.log)

### Did you isolate BYG?

I tried BYG alone

**Comment by JKaiya** [comment]
Same problem, seems to be a problem with the newest BYG file for 1.19, so I went back to the old version

**Comment by Aprucot** [comment]
same here, suggest you just go back to the last working version.

**Comment by CorgiTaco** [comment]
Should be fixed in latest BYG & Terrablender
