### ISSUE TITLE
[Bug]: Orange Amaranth cannot be composted

### ISSUE THREAD

**Issue by uhloin** [CorgiTaco/BYG#829]
### Minecraft Version

1.18.2

### BYG Version

1.4.1

### Terrablender Version

1.1.0.102

### Mod Loader

Forge

### Mod Loader Version

40.1.51

### Bug Severity

Minor

### What happened?

Orange Amaranth cannot be composted but purple one can.

### latest.log

-

### Did you isolate BYG?

I did not try BYG alone

**Comment by CorgiTaco** [comment]
This should be fixed by now
