### ISSUE TITLE
[Crash]: Crashes on creating a world

### ISSUE THREAD

**Issue by ToldUBoutStairs** [CorgiTaco/BYG#832]
### Minecraft Version

1.18.2

### BYG Version

1.18.2-1.4.1

### Terrablender Version

1.18.2- 1.1.0.101

### Mod Loader

Forge

### Mod Loader Version

40.1.25 (1.18.2)

### What happened?

Crashed to desktop when creating a new world in Minecolonies: Exploration Edition ver. 1.4.

### crash-log

https://gist.github.com/ToldUBoutStairs/e47e1a210117c3ac63e1e2fa181b0aa7

### latest.log

https://gist.github.com/ToldUBoutStairs/bd483ba94468ee4d86530a777a4cbdf6

### Did you isolate BYG?

I did not try BYG alone

**Comment by CorgiTaco** [comment]
Use terrablender .99
