### ISSUE TITLE
[Bug]: BYG Boat-With-Chest drops a standard BYG Boat when destroyed

### ISSUE THREAD

**Issue by Sylxeria** [CorgiTaco/BYG#833]
### Minecraft Version

1.19

### BYG Version

2.0.0.5

### Terrablender Version

2.0.0.112

### Mod Loader

Fabric

### Mod Loader Version

0.14.8

### Bug Severity

Minor

### What happened?

When breaking a BYG Boat With Chest,  the resulting drop is a standard BYG Boat. The chest disappears, but the contents of it drop.

Example:  Crafted a Mahogany Boat, then using that to make a Mahogany Boat with Chest.  When attacked it only drops a Mahogany Boat and the Chest is lost entirely.   When testing with vanilla Oak Boat With Chest, it drops itself as an item.

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/9024875/latest.log)

### Did you isolate BYG?

I tried BYG alone

**Comment by CorgiTaco** [comment]
Should be fixed in latest
