### ISSUE TITLE
[Bug]: Embur Warts does not appear when bone mealing Embur nilium. Blue nether rack does not turn into Embur nilium when bonemealed next to Ember Nilium

### ISSUE THREAD

**Issue by codejedi-ai** [CorgiTaco/BYG#834]
### Minecraft Version

1.18.2

### BYG Version

bygonenether-1.1.2-1.18.2.jar

### Terrablender Version

TerraBlender-forge-1.18.2-1.1.0.101.jar

### Mod Loader

Forge

### Mod Loader Version

40.1.25

### Bug Severity

Major

### What happened?

I vary enjoy the embur stems and the gels so I tried to make an Embur Farm just to find the warts to be non-renewable. I tried bonemealing Nilium for embur warts. Also Embur Nilium is non renewable as adjacent blue nether rack does not turn into Embur Nilium when bonemealed

### latest.log

N/a

### Did you isolate BYG?

I did not try BYG alone

**Comment by AOCAWOL** [comment]
Fixed and will be in our next update!

**Comment by Gamemassa** [comment]
> Fixed and will be in our next update!

Hey I know you closed this as completed, but I had reported this as happening in 1.19.x as well. Is it fixed there too?

**Comment by AOCAWOL** [comment]
Yes it will be :)
