### ISSUE TITLE
[Bug]: When I try and log into my friend's server, I get this wall of text

### ISSUE THREAD

**Issue by Cypher380** [CorgiTaco/BYG#835]
### Minecraft Version

1.18.2

### BYG Version

Oh_The_Biomes_You'll_Go-fabric-1.18.2-1.4.1.jar

### Terrablender Version

TerraBlender-fabric-1.18.2-1.1.0.102.jar

### Mod Loader

Fabric

### Mod Loader Version

fabric-api-0.57.0+1.18.2.jar

### Bug Severity

Major

### What happened?

<img width="959" alt="bug" src="https://user-images.githubusercontent.com/74074142/176979768-b58e93ca-d723-4fde-afd5-57d6057fc24d.png">

### latest.log

No log

### Did you isolate BYG?

I tried BYG alone

**Comment by Tempest-5ky** [comment]
That's not an issue with BYG, it means you're missing some mods. Make sure that all the mods that add blocks/items/mobs that are on the server are also on the client.

**Comment by CorgiTaco** [comment]
What Tempest said
