### ISSUE TITLE
[Crash]: [1.19] Crash with Ars Nouveau

### ISSUE THREAD

**Issue by Baggytrousers27** [CorgiTaco/BYG#837]
### Minecraft Version

1.19

### BYG Version

Oh_The_Biomes_You'll_Go-forge-1.19-2.0.0.5

### Terrablender Version

TerraBlender-forge-1.19-2.0.0.118

### Mod Loader

Forge

### Mod Loader Version

41.0.63

### What happened?

ars_nouveau-1.19.0-3.0.3
ars_elemental-1.19-0.5.0.10
ars_instrumentum-1.19.0-3.0.1
curios-forge-1.19-5.1.0.1
geckolib-forge-1.19-3.1.7
Patchouli-1.19-73

Crash to desktop whilst loading a new world (This seed to be specific: 237359222014397027) and displaying this error

> The game crashed whilst exception generating new chunk
Error: java.lang.IllegalStateException: Feature order cycle found, involved sources: [Reference{ResourceKey[minecraft:worldgen/biome / minecraft:deep_dark]=net.minecraft.world.level.biome.Biome@1882d998}, Reference{ResourceKey[minecraft:worldgen/biome / ars_nouveau:archwood_forest]=net.minecraft.world.level.biome.Biome@7f145f22}, Reference{ResourceKey[minecraft:worldgen/biome / byg:coconino_meadow]=net.minecraft.world.level.biome.Biome@339c7bc8}]
Exit Code: -1

### crash-log

[crash-2022-07-04_23.17.03-server.txt](https://github.com/AOCAWOL/BYG/files/9040147/crash-2022-07-04_23.17.03-server.txt)

### latest.log

[debug.log](https://github.com/AOCAWOL/BYG/files/9040152/debug.log)

### Did you isolate BYG?

I tried BYG alone

**Comment by CorgiTaco** [comment]
This should no longer be an issue, if you still get this crash please comment/reopen this issue. Ensure you're using the latest versions of all mods relating to world generation.
