### ISSUE TITLE
[Bug]: The texture for Purple Bulbis Anomaly is all messed up

### ISSUE THREAD

**Issue by purejosh** [CorgiTaco/BYG#838]
### Minecraft Version

1.18.2

### BYG Version

unimportant

### Terrablender Version

unimportant

### Mod Loader

Fabric

### Mod Loader Version

unimportant

### Bug Severity

Minor

### What happened?

The animation frame for the top is exactly opposite of the bottom, so it doesn't float up and down, it compresses and expands.

https://user-images.githubusercontent.com/70633949/177253661-6934e253-abca-4311-a817-9303543cbca4.mp4

### latest.log

unimportant

### Did you isolate BYG?

I did not try BYG alone

**Comment by purejosh** [comment]
A server restart shows the textures right, but when you break and place it, the texture gets all wonky. lmk if you can't repro this and I'll dig deeper.

**Comment by AOCAWOL** [comment]
I am unfortunately not been able to replicate this bug so I will be closing it for now
