### ISSUE TITLE
[Crash]: I keep crashing when i go to the nether

### ISSUE THREAD

**Issue by PeteyPeashooter** [CorgiTaco/BYG#840]
### Minecraft Version

1.16.5

### BYG Version

1.3.5

### Terrablender Version

N/A

### Mod Loader

Forge

### Mod Loader Version

36.2.34

### What happened?

I keep crashing every time i go through a nether portal. My friend said its caused by this mod and im not sure because if i remove the mod im not sure if my world would break or not.

### crash-log

First Crash: https://paste.ee/p/YBkPQ
Second Crash: https://paste.ee/p/3waVd

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/9059563/latest.log)

### Did you isolate BYG?

I did not try BYG alone

**Comment by PeteyPeashooter** [comment]
I have not tried alone because im afraid my world would probably break because of all the mods im using

**Comment by Dak-Darklighter** [comment]
This also happens on my server as well according to console log it appears the embur biome had issues loading crashing the entire server. This happens almost everytime a player opens a nether portal for the first time then the biome will load the second time without crashing it’s very strange.

**Comment by CursedWarrior10HD** [comment]
This is happening inside the Crazy Craft Updated Modpack as well

**Comment by SirOMGitsYOU** [comment]
Also experiencing the same issue

**Comment by CorgiTaco** [comment]
Resolved in:

Forge: https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go/files/4024011
Fabric: https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go-fabric/files/4024006
