### ISSUE TITLE
[Crash]: Visiting Rainbow Beach

### ISSUE THREAD

**Issue by TLiG98** [CorgiTaco/BYG#841]
### Minecraft Version

1.19

### BYG Version

2.0.0.5

### Terrablender Version

2.0.0.117

### Mod Loader

Fabric

### Mod Loader Version

0.14.8

### What happened?

One player on my server goes in to a biome and then the whole server crashes.

The message in the console is:

> [ERROR] Error executing task on Chunk source main thread executor for minecraft:overworld
> 
> net.minecraft.class_148: Feature placement
> 
> at net.minecraft.class_3898.method_39934(class_3898.java:692) ~[server-intermediary.jar:?]
> 
> at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[server-intermediary.jar:?]
> 
> at net.minecraft.class_3215$class_4212.method_18859(class_3215.java:557) ~[server-intermediary.jar:?]
> 
> at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[server-intermediary.jar:?]
> 
> at net.minecraft.class_3215$class_4212.method_16075(class_3215.java:566) ~[server-intermediary.jar:?]
> 
> at net.minecraft.class_3215.method_19492(class_3215.java:279) ~[server-intermediary.jar:?]
> 
> at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764) ~[server-intermediary.jar:?]
> 
> at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752) ~[server-intermediary.jar:?]
> 
> at net.minecraft.class_1255.method_18857(class_1255.java:140) ~[server-intermediary.jar:?]
> 
> at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:737) ~[server-intermediary.jar:?]
> 
> at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:669) ~[server-intermediary.jar:?]
> 
> at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:258) ~[server-intermediary.jar:?]
> 
> at java.lang.Thread.run(Thread.java:833) [?:?]
> 
> Caused by: java.lang.NullPointerException: No chunk exists at [-274, 72]
> 
> at net.minecraft.class_3233.method_8392(class_3233.java:1098) ~[server-intermediary.jar:?]
> 
> at net.minecraft.class_3233.method_8624(class_3233.java:408) ~[server-intermediary.jar:?]
> 
> at net.minecraft.class_3415$class_3416.method_14931(class_3415.java:127) ~[server-intermediary.jar:?]
> 
> at net.minecraft.class_3449.method_14974(class_3449.java:99) ~[server-intermediary.jar:?]
> 
> at net.minecraft.class_2794.method_38265(class_2794.java:427) ~[server-intermediary.jar:?]
> 
> at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.0.1-jre.jar:?]
> 
> at net.minecraft.class_2794.method_12102(class_2794.java:426) ~[server-intermediary.jar:?]
> 
> at net.minecraft.class_2806.method_20613(class_2806.java:145) ~[server-intermediary.jar:?]
> 
> at net.minecraft.class_2806.mdba8442$lambda$injectLightmapSetup$1$4(class_2806.java:546) ~[server-intermediary.jar:?]
> 
> at net.minecraft.class_2806.method_12154(class_2806.java:292) ~[server-intermediary.jar:?]
> 
> at net.minecraft.class_3898.method_17225(class_3898.java:678) ~[server-intermediary.jar:?]
> 
> at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-5.0.28.jar:?]
> 
> at net.minecraft.class_3898.method_17224(class_3898.java:672) ~[server-intermediary.jar:?]
> 
> at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
> 
> at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
> 
> at net.minecraft.class_3900.method_17634(class_3900.java:62) ~[server-intermediary.jar:?]
> 
> at net.minecraft.class_3846.method_16907(class_3846.java:91) ~[server-intermediary.jar:?]
> 
> at net.minecraft.class_3846.method_16900(class_3846.java:146) ~[server-intermediary.jar:?]
> 
> at net.minecraft.class_3846.run(class_3846.java:102) ~[server-intermediary.jar:?]
> 
> at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?]
> 
> at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
> 
> at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
> 
> at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
> 
> at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
> 
> at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
> 
> [ERROR] Encountered an unexpected exception
> 
> net.minecraft.class_148: Feature placement
> 
> at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879) ~[server-intermediary.jar:?]
> 
> at net.minecraft.class_3176.method_3813(class_3176.java:289) ~[server-intermediary.jar:?]
> 
> at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819) ~[server-intermediary.jar:?]
> 
> at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665) ~[server-intermediary.jar:?]
> 
> at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:258) ~[server-intermediary.jar:?]
> 
> at java.lang.Thread.run(Thread.java:833) [?:?]
> 
> Caused by: java.lang.NullPointerException: No chunk exists at [-274, 72]
> 
> at net.minecraft.class_3233.method_8392(class_3233.java:1098) ~[server-intermediary.jar:?]
> 
> at net.minecraft.class_3233.method_8624(class_3233.java:408) ~[server-intermediary.jar:?]
> 
> at net.minecraft.class_3415$class_3416.method_14931(class_3415.java:127) ~[server-intermediary.jar:?]
> 
> at net.minecraft.class_3449.method_14974(class_3449.java:99) ~[server-intermediary.jar:?]
> 
> at net.minecraft.class_2794.method_38265(class_2794.java:427) ~[server-intermediary.jar:?]
> 
> at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.0.1-jre.jar:?]
> 
> at net.minecraft.class_2794.method_12102(class_2794.java:426) ~[server-intermediary.jar:?]
> 
> at net.minecraft.class_2806.method_20613(class_2806.java:145) ~[server-intermediary.jar:?]
> 
> at net.minecraft.class_2806.mdba8442$lambda$injectLightmapSetup$1$4(class_2806.java:546) ~[server-intermediary.jar:?]
> 
> at net.minecraft.class_2806.method_12154(class_2806.java:292) ~[server-intermediary.jar:?]
> 
> at net.minecraft.class_3898.method_17225(class_3898.java:678) ~[server-intermediary.jar:?]
> 
> at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-5.0.28.jar:?]
> 
> at net.minecraft.class_3898.method_17224(class_3898.java:672) ~[server-intermediary.jar:?]
> 
> at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
> 
> at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
> 
> at net.minecraft.class_3900.method_17634(class_3900.java:62) ~[server-intermediary.jar:?]
> 
> at net.minecraft.class_3846.method_16907(class_3846.java:91) ~[server-intermediary.jar:?]
> 
> at net.minecraft.class_3846.method_16900(class_3846.java:146) ~[server-intermediary.jar:?]
> 
> at net.minecraft.class_3846.run(class_3846.java:102) ~[server-intermediary.jar:?]
> 
> at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?]
> 
> at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
> 
> at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
> 
> at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
> 
> at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
> 
> at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
> 
> [ERROR] This crash report has been saved to: /home/gs-41474/./crash-reports/crash-2022-07-07_22.30.15-server.txt
> 
> [INFO] Stopping server
> 
> [INFO] Saving players
> 
> [INFO] Saving worlds
> 
> [ERROR] Exception stopping the server
> 
> java.util.concurrent.CompletionException: net.minecraft.class_148: Feature placement
> 
> at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
> 
> at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
> 
> at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1159) ~[?:?]
> 
> at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
> 
> at net.minecraft.class_3900.method_17634(class_3900.java:62) ~[server-intermediary.jar:?]
> 
> at net.minecraft.class_3846.method_16907(class_3846.java:91) ~[server-intermediary.jar:?]
> 
> at net.minecraft.class_3846.method_16900(class_3846.java:146) ~[server-intermediary.jar:?]
> 
> at net.minecraft.class_3846.run(class_3846.java:102) ~[server-intermediary.jar:?]
> 
> at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?]
> 
> at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
> 
> at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
> 
> at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
> 
> at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
> 
> at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
> 
> Caused by: net.minecraft.class_148: Feature placement
> 
> at net.minecraft.class_3898.method_17225(class_3898.java:694) ~[server-intermediary.jar:?]
> 
> at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-5.0.28.jar:?]
> 
> at net.minecraft.class_3898.method_17224(class_3898.java:672) ~[server-intermediary.jar:?]
> 
> at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
> 
> ... 11 more
> 
> Caused by: java.lang.NullPointerException: No chunk exists at [-274, 72]
> 
> at net.minecraft.class_3233.method_8392(class_3233.java:1098) ~[server-intermediary.jar:?]
> 
> at net.minecraft.class_3233.method_8624(class_3233.java:408) ~[server-intermediary.jar:?]
> 
> at net.minecraft.class_3415$class_3416.method_14931(class_3415.java:127) ~[server-intermediary.jar:?]
> 
> at net.minecraft.class_3449.method_14974(class_3449.java:99) ~[server-intermediary.jar:?]
> 
> at net.minecraft.class_2794.method_38265(class_2794.java:427) ~[server-intermediary.jar:?]
> 
> at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.0.1-jre.jar:?]
> 
> at net.minecraft.class_2794.method_12102(class_2794.java:426) ~[server-intermediary.jar:?]
> 
> at net.minecraft.class_2806.method_20613(class_2806.java:145) ~[server-intermediary.jar:?]
> 
> at net.minecraft.class_2806.mdba8442$lambda$injectLightmapSetup$1$4(class_2806.java:546) ~[server-intermediary.jar:?]
> 
> at net.minecraft.class_2806.method_12154(class_2806.java:292) ~[server-intermediary.jar:?]
> 
> at net.minecraft.class_3898.method_17225(class_3898.java:678) ~[server-intermediary.jar:?]
> 
> at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-5.0.28.jar:?]
> 
> at net.minecraft.class_3898.method_17224(class_3898.java:672) ~[server-intermediary.jar:?]
> 
> at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
> 
> ... 11 more
> 
> [INFO] Thread Query Listener stopped

### crash-log

[crash-2022-07-07_22.38.08-server.txt](https://github.com/AOCAWOL/BYG/files/9067214/crash-2022-07-07_22.38.08-server.txt)

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/9067213/latest.log)

### Did you isolate BYG?

I did not try BYG alone

**Comment by CorgiTaco** [comment]
This a crash inside of Shipwreck Pieces, BYG does not touch this feature in any way.
