### ISSUE TITLE
[Bug]: Better Nether biomes don't generate properly when world is reloaded(modpack specific bug)

### ISSUE THREAD

**Issue by Laff70** [CorgiTaco/BYG#842]
### Minecraft Version

1.18.2

### BYG Version

Oh_The_Biomes_You'll_Go-fabric-1.18.2-1.4.1

### Terrablender Version

TerraBlender-fabric-1.18.2-1.1.0.102

### Mod Loader

Fabric

### Mod Loader Version

0.14.7

### Bug Severity

Major

### What happened?

If a world is created, left, another world is entered(may not be necessary? Restarting Minecraft works too.) and left, and the recently created world is reentered, no new Better Nether biomes properly generate and the world generation is similar to the nether wastes of vanilla Minecraft. This corruption is permanent. I think this is a config issue which could be resolved by editing the config of the modpack(Another Quality Modpack 2 v1.3.3), I have no idea how to properly do this though, and neither does the modpack's creator it seems. I didn't exactly submit the best bug report though... I got really confused often. The original bug report can be found here: itsdinkd/AQM2/issues/66

Everything works fine if the mod BYG is removed. I also tried an instance with just Better Nether, BYG, and their dependencies, and it worked fine.

### latest.log

[2022-07-07-1.log](https://github.com/itsdinkd/AQM2/files/9067442/2022-07-07-1.log)

### Did you isolate BYG?

I did not try BYG alone

**Comment by TheButterbrotMan** [comment]
https://github.com/quiqueck/BetterNether/issues/34

**Comment by CorgiTaco** [comment]
@Laff70 send your nether biomes config please along with your level.dat file

**Comment by mactso** [comment]
On a related note, we have no Emeraldite or Pendorite generating in the wailing garth or embur bog biomes in the nether.
This was proven out with /fill ~32 ~ ~32 ~-32 ~4 ~-32 byg:pendorite replace byg:pendorite and teleporting up 2 steps at a time.  This was done to cover a total of 64x64 (16 chunks) over the entire vertical area including the biome.

There are not other terrain generators.   The Doom mod is loaded which generates some structures.

We also noted no ancient debris was generating in these biomes.

**Comment by JackGlobetrotter** [comment]
> On a related note, we have no Emeraldite or Pendorite generating in the wailing garth or embur bog biomes in the nether. This was proven out with /fill ~32 ~ ~32 ~-32 ~4 ~-32 byg:pendorite replace byg:pendorite and teleporting up 2 steps at a time. This was done to cover a total of 64x64 (16 chunks) over the entire vertical area including the biome.
> 
> There are not other terrain generators. The Doom mod is loaded which generates some structures.
> 
> We also noted no ancient debris was generating in these biomes.

The problem does not seem to come from Emeraldite not generating, but from Scoria stone not generating which is necessary for Emeraldite. Investigating.

**Comment by CorgiTaco** [comment]
Solution provided in https://github.com/quiqueck/BetterNether/issues/34
