### ISSUE TITLE
[Bug]: Zombified piglins wont pathfind towards turtle eggs

### ISSUE THREAD

**Issue by Oberjean** [CorgiTaco/BYG#844]
### Minecraft Version

1.18.2

### BYG Version

1.4

### Terrablender Version

1.1.0.102

### Mod Loader

Forge

### Mod Loader Version

40.1.48

### Bug Severity

Minor

### What happened?

Zombified piglins wont pathfind towards turtle eggs. Tested for 1.18 and 1.19. Isolated for only BYG.

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/9077503/latest.log)

### Did you isolate BYG?

I tried BYG alone

**Comment by TelepathicGrunt** [comment]
Have you tried without byg to see if this is a forge patch issue?

**Comment by Oberjean** [comment]
@TelepathicGrunt Yeah i just tested it with a clean install of only forge. When you load the farm that was created in Vanilla it works but if you build it with BYG the piglins ignore the turtle eggs

**Comment by TelepathicGrunt** [comment]
@Oberjean are you sure? Because it turns out that several other people had the issue and not with byg on. It's a forge bug. Nothing to do with byg
https://github.com/MinecraftForge/MinecraftForge/issues/8853

**Comment by warjort** [comment]
It will depend upon the coordinates of the farm whether you hit the bug.
If you have a mod that can force load 0,0 it should fix it.

**Comment by Hsandin7** [comment]
@warjort Hey I managed to make it work with this command: /forceload add 0 0
Thaks for all the help :)
