### ISSUE TITLE
Some of my biomes are not what they are supposed to be. For example, my "Embur Bog" biome is just like a regular nether biome with lava lakes and some nether lily pads, no blue netherack, or pendorite. I also do not have the embur trees.[Bug]: 

### ISSUE THREAD

**Issue by AkemiDryzz** [CorgiTaco/BYG#848]
### Minecraft Version

1.19

### BYG Version

2.0.0.5

### Terrablender Version

2.0.0.117

### Mod Loader

Fabric

### Mod Loader Version

0.11.0

### Bug Severity

Major

### What happened?

My worlds and servers are missing many blocks, as all of the nether biomes from this mod are completely different from what the screen shots show. They are like the basic nether biome, but with different names. 

I have tried to use the mod alone, and it worked this time, so it's incompatible with another mod I guess, but I don't know which one (I don't have any mod that modifies the nether, other than repurposed structures)

I don't know yet if my End will have the same problem.
![2022-07-11_23 19 57](https://user-images.githubusercontent.com/61516061/178360477-59443f7a-df7c-41a8-9e66-c954aa1e437c.png)

### latest.log

https://gist.github.com/

### Did you isolate BYG?

I tried BYG alone

**Comment by CorgiTaco** [comment]
This should be fixed in the latest version of Terrablender!
