### ISSUE TITLE
Can't place blocks on short grass

### ISSUE THREAD

**Issue by coiledmocha** [CorgiTaco/BYG#85]
If a block is placed on grass, the grass usually disappears and the block is placed where the grass was. Somehow doesn't happen with short grass from BYG.

Sorry if bad explained, no native.

**Comment by copygirl** [comment]
Can the issue be resolved by setting the material to `Material.REPLACEABLE_PLANT`?

**Comment by CorgiTaco** [comment]
Latest alpha has this fixed.
