### ISSUE TITLE
[KNOWN Bug]: 1.18.x BYG dirt and grass to become tillable and converted to dirt

### ISSUE THREAD

**Issue by ZephyrWindSpirit** [CorgiTaco/BYG#852]
### Minecraft Version

1.18.2

### BYG Version

1.4.2

### Terrablender Version

1.1.0.99

### Mod Loader

Forge

### Mod Loader Version

40.1.60

### Bug Severity

Major

### What happened?

The short story: BYG dirt and grasses are untillable, and can't be converted into dirt. 
This is a known bug, and has gone on long enough being unresolved. 
I would love to see it fixed; I'm in a cocorino meadow and have to swap out a lot of dirt to make my wheat fields. More of an inconvenience then anything else, but others agree and don't say. 

Happy July and thank you for an excellent mod.

### latest.log

NO

### Did you isolate BYG?

I did not try BYG alone

**Comment by unweeked** [comment]
I feel like they're not fixing the 1.18.x versions anymore

**Comment by CorgiTaco** [comment]
@unweeked we're very busy now that we all have jobs now

**Comment by unweeked** [comment]
@CorgiTaco sorry, didn't take that into consideration and I appreciate your voluntary work!
Just thought that you didn't want to work on the 1.18 version anymore, now that 1.19 is out :)

**Comment by Suiwelmaan** [comment]
> @CorgiTaco sorry, didn't take that into consideration and I appreciate your voluntary work! Just thought that you didn't want to work on the 1.18 version anymore, now that 1.19 is out :)

well this isn't fixed in 1.19 either so probably not concerned at all either way

**Comment by AOCAWOL** [comment]
Hi everyone! this has actually been properly fixed in our upcoming 1.19 update and we will be working to backport the fix to 1.18 as well! thankyou for your patience <3
