### ISSUE TITLE
[Bug]: Bookshelves from BYG show up at vanilla when crafted, and become glitched.

### ISSUE THREAD

**Issue by bernardthebard** [CorgiTaco/BYG#855]
### Minecraft Version

1.19

### BYG Version

2.0.0.7

### Terrablender Version

2.0.0.117

### Mod Loader

Forge

### Mod Loader Version

41.0.98

### Bug Severity

Minor

### What happened?

Whenever I craft bookshelves with the BYG planks, they always shows up as the vanilla bookshelves, and when I place them, they are invisible, but will still drop books when broken. If multiple of these bookshelves are placed beside each other and one is broken, they all become visible (but when they are placed, the amount of bookshelves in my hotbar doesn't change). They have no effect on enchanting tables. I've tried updating forge, the mods, restarting the game, but I don't know what's causing the problem.

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/9116439/latest.log)

### Did you isolate BYG?

I tried BYG alone

**Comment by bernardthebard** [comment]
Edit: I just found out it only happens with some of the planks. The following planks are the only ones affected; Aspen, Bulbis, Cherry, Cypress, Green Enchanted, Holly, Maple, Nightshade, Palm, Rainbow Eucalyptus, Redwood, Skyris, Sythian, and Embur. And even if I equip and place the vanilla bookshelf in creative mode, the same effect occurs as said above.

**Comment by CorgiTaco** [comment]
Sounds like you need: https://www.curseforge.com/minecraft/mc-mods/polymorph
