### ISSUE TITLE
[Bug]: Biomes not showing up on fabric server

### ISSUE THREAD

**Issue by SolarReflect** [CorgiTaco/BYG#856]
### Minecraft Version

1.19

### BYG Version

1.19

### Terrablender Version

Lastest

### Mod Loader

Fabric

### Mod Loader Version

lastest

### Bug Severity

Major

### What happened?

no new biomes but works in single player

### latest.log

..

### Did you isolate BYG?

I tried BYG alone

**Comment by CorgiTaco** [comment]
You've provided no information(like latest.log) to help you. Feel free to open a new issue with details if your issue persists
