### ISSUE TITLE
[Crash]: 

### ISSUE THREAD

**Issue by 3dguru** [CorgiTaco/BYG#859]
### Minecraft Version

1.19

### BYG Version

2.0.0.7

### Terrablender Version

2.0.0.120

### Mod Loader

Fabric

### Mod Loader Version

0.14.8

### What happened?

world loads fine but when access BYG items in REI minecraft client crashes 

### crash-log

https://pastebin.com/SwvKzBeP

### latest.log

https://pastebin.com/SwvKzBeP

### Did you isolate BYG?

I did not try BYG alone

**Comment by CorgiTaco** [comment]
I cannot recreate this crash, if the issue persists feel free to reopen the issue
