### ISSUE TITLE
Entity Spawning Overcrowding

### ISSUE THREAD

**Issue by OGitsBoondock** [CorgiTaco/BYG#86]
in the plains type biome I encountered a huge amount if cows, not sure if this is intentional but It was a ton!

**Comment by CorgiTaco** [comment]
It isnt intentional and tbf idk why it occurs :/

**Comment by OGitsBoondock** [comment]
No worries who doesn't want a bunch of leather early game =)

**Comment by Caridmum** [comment]
![2020-09-10_00 16 51](https://user-images.githubusercontent.com/11216708/92693931-259d4b80-f2fb-11ea-90ff-714c41be9dc7.png)

Just happened in an Embur Bog, filled with blazes and pigmen around me on my AoF 3 server

**Comment by CorgiTaco** [comment]
> 
> ![2020-09-10_00 16 51](https://user-images.githubusercontent.com/11216708/92693931-259d4b80-f2fb-11ea-90ff-714c41be9dc7.png)
> 
> Just happened in an Embur Bog, filled with blazes and pigmen around me on my AoF 3 server

how many did you count?

**Comment by CorgiTaco** [comment]
Should be resolved by now. Please comment back here if the issue persists
