### ISSUE TITLE
[Bug]: Mod Support Banner and Boat Container Mods

### ISSUE THREAD

**Issue by ardissaps** [CorgiTaco/BYG#861]
### Minecraft Version

1.18.2

### BYG Version

1.4.2

### Terrablender Version

1.1.0.102

### Mod Loader

Fabric

### Mod Loader Version

0.14.8

### Bug Severity

Major

### What happened?
Issue :
- https://github.com/KxmischesDomi/MoreBannerFeatures/issues/18
- https://github.com/KxmischesDomi/BoatContainer/issues/28

Mods : 
- [MoreBannerFeatures](https://www.curseforge.com/minecraft/mc-mods/more-banner-features)
- [BoatContainer](https://www.curseforge.com/minecraft/mc-mods/boat-container)

### latest.log

.

### Did you isolate BYG?

I did not try BYG alone

**Comment by CorgiTaco** [comment]
Our entity extends boat entity and overrides the required methods in order to function. This at the end of the day Mojang's fault. If I do rewrite this... it *may* be possible to mixin in additional values to the vanilla enum but such a hack is not recommended.
