### ISSUE TITLE
[Bug]: Console spam - "7578 biome parameter points were mapped for BYG region: byg:region_0"

### ISSUE THREAD

**Issue by tachometer74** [CorgiTaco/BYG#863]
### Minecraft Version

1.18.2

### BYG Version

1.4.2

### Terrablender Version

1.1.0.102

### Mod Loader

Forge

### Mod Loader Version

40.1.60

### Bug Severity

Minor

### What happened?

Every 5 minutes I get these messages on the console:

7578 biome parameter points were mapped for BYG region: byg:region_0
7578 biome parameter points were mapped for BYG region: byg:region_1
7578 biome parameter points were mapped for BYG region: byg:region_2
7578 biome parameter points were mapped for BYG region: byg:region_3

It's totally minor, like not a big deal at all.  Mainly I'm curious what's causing it :)  I haven't done any testing of this, like running BYG solo.

This is running on an AMP server.

### latest.log

Link to [latest.log](https://gist.github.com/tachometer74/e9d60f6c4575a4e6865df11d1d702506)

### Did you isolate BYG?

I did not try BYG alone

**Comment by CorgiTaco** [comment]
Information logging only, not an issue. And this is due to Byg regions being created and lets us devs know if byg biomes are actually being used or not
