### ISSUE TITLE
[Crash]:invisible bookshelf 

### ISSUE THREAD

**Issue by papillo12** [CorgiTaco/BYG#864]
### Minecraft Version

1.19

### BYG Version

Oh_The_Biomes_You'll_Go-forge-1.19-2.0.0.7.jar

### Terrablender Version

TerraBlender-forge-1.19-2.0.0.120.jar

### Mod Loader

Forge

### Mod Loader Version

 41.0.100

### What happened?

 In the latest version for 1.19 when you put an bookshelf is inivisible and can crash the game if you break them or put several

### crash-log

[crash-2022-07-19_10.20.27-server.txt](https://github.com/AOCAWOL/BYG/files/9143154/crash-2022-07-19_10.20.27-server.txt)

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/9143160/latest.log)

### Did you isolate BYG?

I tried BYG alone

**Comment by papillo12** [comment]
before I knew it was byg I had to disable each mod to see which one was causing the error, first I thought it was some performance mod but it was byg.

**Comment by papillo12** [comment]
![Uploading 2022-07-19_10.48.49.png…]()

**Comment by papillo12** [comment]
![2022-07-19_10 48 49](https://user-images.githubusercontent.com/80440525/179807544-91fb1f9f-b453-4c8b-9dfd-b4a19674df5d.png)

**Comment by maxopax** [comment]
happens the same to me, Has someone found a way to solve this?

**Comment by papillo12** [comment]
> happens the same to me, Has someone found a way to solve this?

I guess in the next patch

**Comment by Haiwei1027** [comment]
happened to me too
