### ISSUE TITLE
[Crash]: It has a error duaring loading

### ISSUE THREAD

**Issue by Mattyaice14** [CorgiTaco/BYG#865]
### Minecraft Version

1.18.2

### BYG Version

1.4.2

### Terrablender Version

1.1.0.102

### Mod Loader

Forge

### Mod Loader Version

40.1.0

### What happened?

Minecraft can't load byg mod.
When I bootup Minecraft, this message is appeared durng loading.

![無題80](https://user-images.githubusercontent.com/109708721/180118115-17799313-9980-4c99-815d-6165496bcaf9.png)

### crash-log

[crash-2022-07-21_11.29.07-fml.txt](https://github.com/AOCAWOL/BYG/files/9155735/crash-2022-07-21_11.29.07-fml.txt)

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/9155742/latest.log)

### Did you isolate BYG?

I tried BYG alone

**Comment by ThatWeirdWoman** [comment]
Having this same issue, no idea why yet. I'm currently troubleshooting, so if I figure it out I'll let you know!

**Comment by Mattyaice14** [comment]
Thank you.
I'm wating for your news :)

**Comment by aaclau** [comment]
Hi! Have you found any solution? I have this same problem :(

**Comment by Mattyaice14** [comment]
> Hi! Have you found any solution? I have this same problem :(

No, I've found nothing...

**Comment by CorgiTaco** [comment]
Delete your BYG Configs and let them regenerate.
