### ISSUE TITLE
[Crash]: Minecraft keeps on crashing when I try to load it up.

### ISSUE THREAD

**Issue by UniverseisaPixel** [CorgiTaco/BYG#867]
### Minecraft Version

1.18.2

### BYG Version

1.4.2

### Terrablender Version

1.1.0.102

### Mod Loader

Forge

### Mod Loader Version

40.1.68

### What happened?

I wanted to switch my laptop world to my main computer so I used MediaFile, and I got the world on just fine, but when I put the mods on, it started crashing. I tried reinstalling both TerraBlender and BYG, but to no avail. It worked perfectly on the laptop, although the laptop had an earlier version, I installed the earlier version and it still crashed. Don't know what is causing this. Because I used at least one thing from every non-library mod, I cant simply just remove it.

### crash-log

https://gist.github.com/UniverseisaPixel/ede40e9238b79692fdc3105ccab4168c

### latest.log

https://gist.github.com/UniverseisaPixel/abc20117cb5f401f86a90c8066d9ad12

### Did you isolate BYG?

I tried BYG alone

**Comment by CorgiTaco** [comment]
Delete your config folder and let it regenerate
