### ISSUE TITLE
[Bug]: 1.18.2 Incompatibility with Terralith causes Windswept Desert to be made of dirt/grass

### ISSUE THREAD

**Issue by jlaine3333** [CorgiTaco/BYG#868]
### Minecraft Version

1.18.2

### BYG Version

1.4.2

### Terrablender Version

1.1.0.102

### Mod Loader

Forge

### Mod Loader Version

40.1.68

### Bug Severity

Minor

### What happened?

Windswept Desert's terrain generation causes it to be made of dirt instead of pink sand, and is not spawning any biome-specific mobs, after installing Terralith. Not sure which mod's side it's on, but I'm reporting here nonetheless.

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/9162674/latest.log)

### Did you isolate BYG?

I did not try BYG alone

**Comment by puppygruel** [comment]
issue seems to also occur with William Wyther's Overhauled Overworld

**Comment by CorgiTaco** [comment]
Should be fixed in newest terrablender for your MC version
