### ISSUE TITLE
[Bug]: Compatibility with BCLib's Config

### ISSUE THREAD

**Issue by xVanquishx** [CorgiTaco/BYG#869]
### Minecraft Version

1.19

### BYG Version

2.0.0.7

### Terrablender Version

2.0.0.120

### Mod Loader

Quilt

### Mod Loader Version

0.17.1-beta6

### Bug Severity

Minor

### What happened?

BYG's biomes don't appear BCLib's generated config. Changing weighting of biomes in BYG's config does noticeably change the world(Mainly tested Nether). However, a weighting of zero does not make biomes not generate. BCLib's Generator config also effects world gen.

### latest.log

n/a

### Did you isolate BYG?

I did not try BYG alone

**Comment by CorgiTaco** [comment]
Yeah they'll need to figure something out on their end. And it's likely BYG's config is the one you'd need to use
