### ISSUE TITLE
[Crash]: 

### ISSUE THREAD

**Issue by Eduardo-Saenz** [CorgiTaco/BYG#871]
### Minecraft Version

1.18.2

### BYG Version

1.4.2

### Terrablender Version

1.1.0.102

### Mod Loader

Forge

### Mod Loader Version

40.1.68

### What happened?

I start the game and it says an error occured. when I checked the crash log it says "byg:white_mangrove_sapling" is not a valid id in registry

I tried looking for it where it says "Current Registry Values" but didn't find it. Its the only mod that doesn't let me start the game.
If you need it I'll leave a list of the oters mods that I use.

- Alex's mobs
- Ambient Sounds v5
- AppleSkin
- CarryOn
- Citadel
- Balm
- Creative Core
- Curios API
- Hexerei
- Inventory HUD
- Jade
- JEI
- JourneyMap
- Oculus
- Rubidium
- Selene
- Sophisticated Backpacks
- Sophisticated Core
- BYG
- TerraBlender
- Supplementaries
- Trashslot
- Configured

### crash-log

[crash-2022-07-22_18.08.38-fml.txt](https://github.com/AOCAWOL/BYG/files/9172805/crash-2022-07-22_18.08.38-fml.txt)

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/9172809/latest.log)

### Did you isolate BYG?

I did not try BYG alone

**Comment by UniverseisaPixel** [comment]
Try to isolate or remove one mod at a time to see what is happening. Try re-installing the mod if to no avail.

**Comment by CorgiTaco** [comment]
Delete your trades config and let it regenerate.
