### ISSUE TITLE
[Bug]: When I start my mohist 1.18.2 server with this mod it crashes

### ISSUE THREAD

**Issue by Joche777** [CorgiTaco/BYG#876]
### Minecraft Version

1.18.2

### BYG Version

1.4.2

### Terrablender Version

1.1.0.102

### Mod Loader

Forge

### Mod Loader Version

40.1.51

### Bug Severity

Major

### What happened?

When I start my mohist 1.18.2 server with this mod it crashes

### latest.log

[archive-2022-07-26T043323Z.tar.gz](https://github.com/AOCAWOL/BYG/files/9186553/archive-2022-07-26T043323Z.tar.gz)

### Did you isolate BYG?

I tried BYG alone

**Comment by CorgiTaco** [comment]
BYG is incompatible with Mohist

**Comment by Joche777** [comment]
oh thanks

**Comment by Joche777** [comment]
is there any way to play with it on a mohist server
