### ISSUE TITLE
Crash server

### ISSUE THREAD

**Issue by Minemobs** [CorgiTaco/BYG#88]
# Hello, when i launch my server it crash after loading some other mods
[Logs](https://gist.github.com/Minemobs/56d2dc0c48fe8732d316daf22c680390)

**Comment by CorgiTaco** [comment]
Test byg itself

**Comment by Minemobs** [comment]
Oh it work without other mods
So now i need to know what mod do that 🤔

**Comment by CorgiTaco** [comment]
Yup and this issue is not our issue and this is an outdated version we no longer support.
