### ISSUE TITLE
[Crash]: Crash at world creation after validating datapacks

### ISSUE THREAD

**Issue by Gronglegrowth** [CorgiTaco/BYG#880]
### Minecraft Version

1.18.2

### BYG Version

1.4.2

### Terrablender Version

1.1.0.102

### Mod Loader

Forge

### Mod Loader Version

40.1.51

### What happened?

When creating a new world, if one enters the datapacks screen and leaves it (so it shows "validating currently selected datapacks"), upon generating the world, the game will crash. Without any other mods, this works fine, but with the rest of our mods, it doesn't, and we cannot tell what mods are at fault, so I thought reporting here was a good idea.

### crash-log

[crash-2022-07-28_21.46.59-server.txt](https://github.com/AOCAWOL/BYG/files/9216061/crash-2022-07-28_21.46.59-server.txt)

### latest.log

[latest (1).log](https://github.com/AOCAWOL/BYG/files/9216063/latest.1.log)

### Did you isolate BYG?

I tried BYG alone

**Comment by CorgiTaco** [comment]
Dowgrade terrablender to .99
