### ISSUE TITLE
[Crash]:  everytime i try to open the biomepedia my game crashes

### ISSUE THREAD

**Issue by pickleman1233** [CorgiTaco/BYG#881]
### Minecraft Version

1.19

### BYG Version

1.19-2.0.0.7

### Terrablender Version

1.19-2.0.0.120

### Mod Loader

Forge

### Mod Loader Version

1.19.1(42.0.1)

### What happened?

try to open the biomepedia book and the game crashes.

### crash-log

The game crashed whilst rendering screen
Error: java.lang.NoSuchMethodError: 'void potionstudios.byg.client.gui.screen.BYGContainerObjectSelectionList.m_93451_(com.mojang.blaze3d.vertex.PoseStack, int, int, int, int, float)'
Exit Code: -1

### latest.log

The game crashed whilst rendering screen
Error: java.lang.NoSuchMethodError: 'void potionstudios.byg.client.gui.screen.BYGContainerObjectSelectionList.m_93451_(com.mojang.blaze3d.vertex.PoseStack, int, int, int, int, float)'
Exit Code: -1

### Did you isolate BYG?

I tried BYG alone

**Comment by WreckItRa1ph** [comment]
I am having the same issue but I'm on 1.19.1

**Comment by netcore10** [comment]
same here for 1.19.1

**Comment by CorgiTaco** [comment]
Use BYG's latest jar for 1.19.2
