### ISSUE TITLE
[Crash]: Crash when loading game with BYG refabricated

### ISSUE THREAD

**Issue by RogueZombieDog** [CorgiTaco/BYG#882]
### Minecraft Version

1.19

### BYG Version

2.0.0.7

### Terrablender Version

2.0.0.117

### Mod Loader

Fabric

### Mod Loader Version

0.14.8

### What happened?

tried loading with my modpack and it crashed

### crash-log

[crash-2022-07-30_12.47.30-client.txt](https://github.com/AOCAWOL/BYG/files/9226251/crash-2022-07-30_12.47.30-client.txt)

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/9226252/latest.log)

### Did you isolate BYG?

I tried BYG alone

**Comment by CorgiTaco** [comment]
Either update to 1.19.2, update charm, or remove Charm are the only suggestions I can provide because charm is throwing a Mixin error which is entirely unrelated to BYG and it is therefore wrongfully blaming byg
