### ISSUE TITLE
[Bug]:  Bookshelfs dont enhance the Enchanting Table

### ISSUE THREAD

**Issue by xanthian** [CorgiTaco/BYG#885]
### Minecraft Version

1.18.2

### BYG Version

1.4.2

### Terrablender Version

1.1.0.102

### Mod Loader

Fabric

### Mod Loader Version

0.14.8

### Bug Severity

Minor

### What happened?

As title.

Put appropriate amount of bookshelves around the enchanting table, no level 30 enchant available.
Repeat process with vanilla bookshelf, level 30 enchant shown

### latest.log

nr

### Did you isolate BYG?

I did not try BYG alone

**Comment by KyrDerz** [comment]
Same here. Tho it was on forge. I wonder was it some combination with other mod?

**Comment by CDAGaming** [comment]
Was also able to reproduce this in Forge with just BYG and TerraBlender (1.19.2)

**Comment by CorgiTaco** [comment]
Works for me on the latest version of BYG: 

https://user-images.githubusercontent.com/66983020/194811084-3e3598d8-d550-4bfc-ad7c-b1ce9be037e4.mp4
