### ISSUE TITLE
[Bug]: "byg" dependent on "roadrunner"

### ISSUE THREAD

**Issue by ShonaEV** [CorgiTaco/BYG#889]
### Minecraft Version

1.16.5

### BYG Version

1.3.5

### Terrablender Version

0

### Mod Loader

Forge

### Mod Loader Version

36.2.34

### Bug Severity

Minor

### What happened?

If it wasn't a bother, could you tell me in which version of "byg" 1.16.5 is not dependent on roadrunner? since the latter brings me many incompatibilities and, furthermore, I would like to know if they will fix this dependency in future versions or if it will remain the same, since there are better mods in terms of optimization and compatibility than the roadrunner. PD: thank you very much

### latest.log

I already deleted all the crash reports, sorry xd

### Did you isolate BYG?

I tried BYG alone

**Comment by CorgiTaco** [comment]
Byg 1.16 is not dependent on road runner in any way.
