### ISSUE TITLE
[Crash]: Fabric 1.19 BYG and Terralith incompatible. (Crash while creating world)

### ISSUE THREAD

**Issue by SJY051** [CorgiTaco/BYG#890]
### Minecraft Version

1.19

### BYG Version

2.0.0.7

### Terrablender Version

2.0.0.120

### Mod Loader

Fabric

### Mod Loader Version

Fabric 0.14.8

### What happened?

While creating a world with BYG and Terralith, the world creation screen stuck at 0%-1% for a long time and eventually crashed.
\+ I also had the same problem with wwoo & BYG mod configuration.

Main error: 
```java.lang.IllegalStateException: Feature order cycle found, involved sources: [Reference{ResourceKey[minecraft:worldgen/biome / minecraft:old_growth_birch_forest]=net.minecraft.class_1959@58de017e}, Reference{ResourceKey[minecraft:worldgen/biome / terralith:blooming_plateau]=net.minecraft.class_1959@26fccaa9}, Reference{ResourceKey[minecraft:worldgen/biome / terralith:blooming_valley]=net.minecraft.class_1959@3065fd31}, Reference{ResourceKey[minecraft:worldgen/biome / byg:ebony_woods]=net.minecraft.class_1959@45b00ac6}]```

### crash-log

[Github Gist](https://gist.github.com/Kyanite0029/4c55277a579f6bf73570dd232bedebd0)

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/9252197/latest.log)

### Did you isolate BYG?

I did not try BYG alone

**Comment by CorgiTaco** [comment]
Install this and send your crash report then: https://www.curseforge.com/minecraft/mc-mods/cyanide-fabric

**Comment by MattB70** [comment]
I may have had a similar crash on forge, my issue is here (separate issue since it's a different loader and I suspect mod conflict): https://github.com/AOCAWOL/BYG/issues/947

**Comment by CorgiTaco** [comment]
This should no longer be an issue, if you still get this issue please comment/reopen this issue. Ensure you're using the latest versions of all mods relating to world generation and Terrablender!
