### ISSUE TITLE
[Crash]: BYG doesnt find "terrablender" mod when its already installed (aternos)

### ISSUE THREAD

**Issue by BlockyMaster** [CorgiTaco/BYG#893]
### Minecraft Version

1.19

### BYG Version

2.0.0.7

### Terrablender Version

2.0.0.111

### Mod Loader

Forge

### Mod Loader Version

41.1.0

### What happened?

![image](https://user-images.githubusercontent.com/110687306/183122907-09561c72-18d4-4954-8f99-1226493e47a9.png)
It says BYG cant find terrablender
but I already installed terrablender

### crash-log

<html>
<body>

[05Aug2022 18:30:07.458] [main/FATAL] [net.minecraftforge.fml.ModLoader/CORE]: Error during pre-loading phase
--
16 | net.minecraftforge.fml.ModLoadingException: Mod §ebyg§r requires §6terrablender§r §o2.0.0.111 or above§r
17 | §7Currently, §6terrablender§r§7 is §o§nnot installed
18 | at net.minecraftforge.fml.ModLoadingException.lambda$fromEarlyException$0(ModLoadingException.java:50) ~[fmlcore-1.19-41.1.0.jar%23102!/:?]

</body>
</html>

### latest.log

.

### Did you isolate BYG?

I did not try BYG alone

**Comment by CorgiTaco** [comment]
My suggestion is do not use aternos, their servers are not the best.
