### ISSUE TITLE
[Bug]: Breaks enchantment

### ISSUE THREAD

**Issue by KyrDerz** [CorgiTaco/BYG#895]
### Minecraft Version

1.19

### BYG Version

2.0.0.7

### Terrablender Version

2.0.0.120

### Mod Loader

Forge

### Mod Loader Version

41.1.0

### Bug Severity

Major

### What happened?

Bookshelf glitch that allows duping bookshelf and renders them invisible until block update. Bookshelfs are ineffective and don't raise levels.

### latest.log

I don't have it.

### Did you isolate BYG?

I tried BYG alone

**Comment by KyrDerz** [comment]
![image](https://user-images.githubusercontent.com/110685473/183542387-7cd61b11-e20f-477b-b0b6-b0d9bbb3007b.png)
The space is after I've put the shelve block.

**Comment by KyrDerz** [comment]
![image](https://user-images.githubusercontent.com/110685473/183542448-79a53afc-baa0-4e67-bd32-1a97c58bc424.png)
You can see it stays the same level

**Comment by RedBeast1959** [comment]
Same problem in 1.19.2 version(Oh_The_Biomes_You'll_Go-forge-1.19.2-2.0.0.7.jar).
Currently, normal bookshelf can't increase enchant power. Only BYG wooden bookshelves and other modded bookshelves do.
