### ISSUE TITLE
How to replace nether ceiling with obsidian - Immersive Portals DimensionStack compatibility

### ISSUE THREAD

**Issue by solarblindfull** [CorgiTaco/BYG#9]
Hello !

Thank for this very good mod ! Unfortunately BYG seem to break the Immersive Portals mod capability to replace nether ceiling with obsidian blocks, make it impossible to reach in survival with DimensionStack. Can you add an option in config for the Nether to replace bedrock ceiling with obsidian or another block please ? Thank very much.

Have a nice day !

**Comment by CorgiTaco** [comment]
What version? Forge or Fabric API?

**Comment by solarblindfull** [comment]
Thank for your very quick reply !
Sorry for my omission. I'm on Forge 31.2.30 in Minecraft 1.15.2.

**Comment by CorgiTaco** [comment]
alright ill drop  a patch here in 5

**Comment by solarblindfull** [comment]
Wow ! You're the first one to patch a mod as fast after one of my comment ! Thank !

**Comment by CorgiTaco** [comment]
https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go/files/2996276

**Comment by CorgiTaco** [comment]
Lmk if it works

**Comment by solarblindfull** [comment]
I tested and your fix doesn't work sorry.

EDIT : I use a TerraForged Worldgen with both Biome O'Plenty and BYG and an Immersive Portals Dimension Stack with nether. The issue occurs only when I put your mod in the mod folder.

**Comment by CorgiTaco** [comment]
hmmmmmmmmmmm

**Comment by CorgiTaco** [comment]
http://www.mediafire.com/file/6k7jktjtrsy2u6j/byg-1.0.4.jar/file

**Comment by CorgiTaco** [comment]
try now

**Comment by solarblindfull** [comment]
That's work perfectly !!! Thank very much  !
