### ISSUE TITLE
[Bug]: Lilypads and water silk's "water hole" caused by Incompatibility with Biome Makeover

### ISSUE THREAD

**Issue by RedBeast1959** [CorgiTaco/BYG#900]
### Minecraft Version

1.19

### BYG Version

Oh_The_Biomes_You'll_Go-forge-1.19.2-2.0.0.7.jar

### Terrablender Version

TerraBlender-forge-1.19.2-2.0.1.125.jar

### Mod Loader

Forge

### Mod Loader Version

43.0.7

### Bug Severity

Minor

### What happened?

![2022-08-10_22 04 56](https://user-images.githubusercontent.com/100399264/183910836-c48ccf07-c2db-41cc-9749-a0359b9f2c2d.png)
![2022-08-10_22 05 08](https://user-images.githubusercontent.com/100399264/183910884-98095449-823e-4e8f-8e94-935b0a91d429.png)

There were many one block deep "water hole" in Bayou and White Mangrove Swamp caused by tiny lilypad and water silk. After several tries to isolating mods, I found minor mod incompability with Biome Makeover(biomemakeover-FORGE-1.19.1-1.5.11). I'm not still sure this is from Terrablender problem or BYG problem or Biome Makeover problem.

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/9300566/latest.log)

### Did you isolate BYG?

I did not try BYG alone

**Comment by LoofScared** [comment]
Tested this myself and I'd like to confirm and add that ender lilies within the Imparius Grove seem to be doing this as well with Biome Overhaul (Forge) installed, despite the mod not adding anything to the End far as I'm aware.
