### ISSUE TITLE
[Crash]: Common_Setup Event Phase Error on Startup

### ISSUE THREAD

**Issue by Gamemassa** [CorgiTaco/BYG#902]
### Minecraft Version

1.19

### BYG Version

2.0.0.7

### Terrablender Version

1.19.2-2.0.1.125

### Mod Loader

Forge

### Mod Loader Version

43.0.8

### What happened?

The game failed to initialize, and returned an error regarding byg:lush_grass_block . When isolated with Terrablender, the game loaded successfully.

### crash-log

[crash-2022-08-11_10.30.36-client.txt](https://github.com/AOCAWOL/BYG/files/9309504/crash-2022-08-11_10.30.36-client.txt)

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/9309507/latest.log)

### Did you isolate BYG?

I tried BYG alone

**Comment by Gamemassa** [comment]
Upon further investigation, the issue may be a conflict between BYG and the latest version of MineColonies.

**Comment by CorgiTaco** [comment]
This is an issue with Minecolonies not BYG: 

```
java.lang.NoClassDefFoundError: com/ldtteam/structurize/blocks/interfaces/IBlueprintDataProvider
```

Ensure you are using the right version of minecolonies for the correct MC version as well as any required dependencies(ie Structurize)
