### ISSUE TITLE
Black Sandstone recipe broken/missing

### ISSUE THREAD

**Issue by StrangeTaniwha** [CorgiTaco/BYG#906]
### Minecraft Version

1.19

### BYG Version

2.0.0.7

### Terrablender Version

2.0.0.117

### Mod Loader

Forge

### Mod Loader Version

41.0.100

### Bug Severity

Minor

### What happened?

The recipe for black sandstone seems to be broken, in-game and in Just Enough Items. Where I'm assuming black sand is supposed to be, it's replaced with a barrier block that's labeled "Error Tag c:black_sand"
![image](https://user-images.githubusercontent.com/67819174/184476693-4265e763-8787-4c13-95ad-92306f5738bd.png)
![image](https://user-images.githubusercontent.com/67819174/184476703-3d878ab8-b5b5-45b9-979b-e3d13a8d2801.png)
Mod List (if needed, I'm not sure)
![image](https://user-images.githubusercontent.com/67819174/184476937-992ab6cb-a123-4793-b0a0-e11ff5e1a630.png)

### latest.log

N/A

### Did you isolate BYG?

I did not try BYG alone

**Comment by MuteTiefling** [comment]
I've tried BYG by itself and can confirm that all colors of Sandstone have a similar broken recipe. 

BYG: 1.19.2-2.0.0.11
Terrablender: 1.19.2-2.0.1.127

Windswept sandstone (every block type) also has no recipes at all.

**Comment by Jokinha23** [comment]
You need to open the /data/byg/recipes folder (inside the mod file) and search for black_sandstone.json file.
replace {"tag":"c:black_sand"} with {"tag":"byg:black_sand"}

Do this in the other color files inside recipes folder (like purple_sandstone or blue_sandstone)

Don't forget to save before closing.

**Comment by CorgiTaco** [comment]
Works for me on latest along with all the other sands. 

https://user-images.githubusercontent.com/66983020/194808272-8fe7676b-44d9-472d-b40d-014b32a80ca1.mp4

**Comment by MuteTiefling** [comment]
I don't understand what I'm missing then... 

![image](https://user-images.githubusercontent.com/9543430/194950956-6ee02431-7778-49d7-a13f-125ce4dbfa8a.png)
![image](https://user-images.githubusercontent.com/9543430/194950992-3931d570-e93a-460b-81e8-2404f080a735.png)

Only mods installed:
![image](https://user-images.githubusercontent.com/9543430/194951251-12622449-de90-4753-973e-c567ffa14056.png)

Forge: 43.1.34

The recipe is set to use `#c:black_sand` but that tag is empty? Is there another mod that should be installed?

**Comment by CorgiTaco** [comment]
hmmmm
