### ISSUE TITLE
Crafting Recipe : : Ebony wood stairs are crafted by ebony wood stairs? 

### ISSUE THREAD

**Issue by window-png** [CorgiTaco/BYG#91]
![2020-09-13_19 50 10](https://user-images.githubusercontent.com/67073031/93024953-639bb780-f5fa-11ea-8846-da2d696e7af4.png)

**Comment by Rover656** [comment]
Can confirm, present in both 1.16.1 and 1.16.3.

**Comment by CorgiTaco** [comment]
Patched: https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go/files/3082737
