### ISSUE TITLE
[Crash]: Feature order cycle found, involved biomes: [Reference{ResourceKey[minecraft:worldgen/biome

### ISSUE THREAD

**Issue by Theisgood** [CorgiTaco/BYG#915]
### Minecraft Version

1.18.2

### BYG Version

1.4.2

### Terrablender Version

1.1.0.102

### Mod Loader

Forge

### Mod Loader Version

40.1.57

### What happened?

Crash On World Load. 

Yeah I know I have lots of texture issues lol but that has nothing to do with the crash 

I just had a lot of resource packs that I edited.

I see two other users have this same crash this is the first time I got it.

### crash-log

[crash-2022-08-17_02.27.14-server.txt](https://github.com/AOCAWOL/BYG/files/9357113/crash-2022-08-17_02.27.14-server.txt)

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/9357151/latest.log)

### Did you isolate BYG?

I tried BYG alone

**Comment by CorgiTaco** [comment]
Terrablender issue, update
