### ISSUE TITLE
[Crash]: Nylium NPE when Astral Sorcery "Spreading Growth" tries to "bonemeal" it

### ISSUE THREAD

**Issue by andrewsf** [CorgiTaco/BYG#917]
### Minecraft Version

1.16.5

### BYG Version

1.3.5

### Terrablender Version

N/A

### Mod Loader

Forge

### Mod Loader Version

36.2.39

### What happened?

Flying around in the Nether. Suddenly a freeze -> crash, a `NullPointerException` while ticking the player.

Astral Sorcery's "Spreading Growth" perk tries to randomly grow nearby blocks and may [target the Nylium block for bonemealing](https://github.com/HellFirePvP/AstralSorcery/blob/5e34d885b12a759c5b061444271da6b1fd745048/src/main/java/hellfirepvp/astralsorcery/common/auxiliary/CropHelper.java#L462) (since it is a `NyliumBlock` and therefore an `IGrowable`).

Root cause is most likely the same as #481 & #602, which were [fixed in 1.18](https://github.com/AOCAWOL/BYG/commit/c5cf6123f860615a69cb22ccadf56b92c3f17b59) but [never backported to the 1.16 branch](https://github.com/AOCAWOL/BYG/blob/Forge-1.16.X/src/main/java/corgiaoc/byg/common/properties/blocks/BYGGrassBlock.java#L55).
But I'm filing a new report just in case & to help future bug searchers until this gets a fix.

### crash-log

[crash-2022-08-17_21.13.49-server.txt](https://github.com/AOCAWOL/BYG/files/9367745/crash-2022-08-17_21.13.49-server.txt)

### latest.log

-

### Did you isolate BYG?

I did not try BYG alone

**Comment by andrewsf** [comment]
My quick workaround was:

- Open `serverconfig\astralsorcery.toml` in the game save directory
- Locate the line with `chanceToBonemeal =`
- `#comment out that line`
- Add `chanceToBonemeal = 0.0` instead

Then I can actually load the world again. At that point, the player's longer-term workaround is to disable the "Spreading Growth" perk (which is not trivial).

**Comment by JT122406** [comment]
1.16 isn't supported
