### ISSUE TITLE
[Crash]: Ash stairs [1.19]

### ISSUE THREAD

**Issue by Wysam96** [CorgiTaco/BYG#918]
### Minecraft Version

1.19

### BYG Version

2.0.0.7

### Terrablender Version

2.0.0.120

### Mod Loader

Forge

### Mod Loader Version

41.1.0

### What happened?

The game crashes when you place some ash ladders

### crash-log

[crash-2022-08-18_18.18.34-client.txt](https://github.com/AOCAWOL/BYG/files/9375746/crash-2022-08-18_18.18.34-client.txt)

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/9375741/latest.log)

### Did you isolate BYG?

I tried BYG alone

**Comment by CorgiTaco** [comment]
Ash Ladders & Stairs do not exist. Going to need a video describing what you mean. For now, this issue is closed, feel free to comment with a video and from there I will decide whether or not the issue is BYG's.
