### ISSUE TITLE
[Forge 1.16.2] End-wold-generation  

### ISSUE THREAD

**Issue by window-png** [CorgiTaco/BYG#92]
![2020-09-13_20 00 36](https://user-images.githubusercontent.com/67073031/93025174-1ddfee80-f5fc-11ea-8251-542f77faf38c.png)

On: 33.0.61Forge 1.16.2 (on Twitch-Laucher)
Dedicated Server

- Biom looking rather plain. (no Ivis Root /-Sprouts)
- No end citys are generating in the entire End-Dimension. (Tested with locate-command)

**Comment by CorgiTaco** [comment]
Test byg alone and see if that fixes it

**Comment by window-png** [comment]
> Test byg alone and see if that fixes it

Tested in 1.16.2 (single player) with byg as the only mode installed, the same problem/-s.

**Comment by CorgiTaco** [comment]
This patch will be available October 31st!
