### ISSUE TITLE
[Bug]: Forge Terralith and WWOO incompatibility

### ISSUE THREAD

**Issue by Atlantispy** [CorgiTaco/BYG#922]
### Minecraft Version

1.18.2

### BYG Version

1.4.2

### Terrablender Version

1.1.0.102

### Mod Loader

Forge

### Mod Loader Version

40.1.73

### Bug Severity

Major

### What happened?

In multiple biomes such as windswept desert and red rock valley the wrong material gets used for the majority of the ground cover.

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/9388702/latest.log)

### Did you isolate BYG?

I tried BYG alone - is fine on its own

**Comment by puppygruel** [comment]
i was having this issue but i fixed it, it was an issue with terrablender. tb has a beta release version for 1.18.2 that fixes the issue, to use that version just go to the terrablender page on forge from your modpack youre using, go to versions, and use TerraBlender-forge-1.18.2-1.2.0.126. it is a beta though, but i haven't had any other problems.

**Comment by CorgiTaco** [comment]
Im going by the last comment and going to assume this issue is fixed.
