### ISSUE TITLE
[Bug]: Tree logs from this mod cannot be stripped

### ISSUE THREAD

**Issue by SatDog92** [CorgiTaco/BYG#925]
### Minecraft Version

1.19.2

### BYG Version

2.0.0.8

### Terrablender Version

0.0.117

### Mod Loader

Quilt

### Mod Loader Version

0.17.3

### Bug Severity

Minor

### What happened?

What the title says: on Quilt, tree log for this mod cannot be stripped at all. At first i though it was some mod conflict (even if other logs from other few mods worked properly), but i tried BYG alone and it appears it's just with Quilt. On Fabric it works fine, but since Quilt can be selected from this bug report guide, i thought it was appropriate reporting this.

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/9389844/latest.log)

### Did you isolate BYG?

I tried BYG alone

EDIT: updated version, as it happens in 2.0.0.8 as well.

**Comment by LambdAurora** [comment]
To anyone looking into fixing this mod, and as one of the developers working on QSL here's why this bug happens:

Quilt has an API called Registry Entry Attachments, which allows to attach arbitrary objects to a registry entry, this API allows this to also be data-driven. This API is used for strippable logs as you can see [here](https://github.com/QuiltMC/quilt-standard-libraries/blob/1.19/library/block/block_content_registry/src/main/java/org/quiltmc/qsl/block/content/registry/impl/BlockContentRegistriesInitializer.java#L99).  
This means the unstripped -> stripped map is cleared at each data pack reload and it's happening after QSL initialization which means existing values are not caught and put into the REA.

Here's some possible fixes to consider:
 - abstract the implementation to allow to call Fabric API's strippable registry, which would fix this issue entirely
 - use the data-driven variant for Quilt ([example](https://github.com/QuiltMC/quilt-standard-libraries/blob/1.19/library/block/block_content_registry/src/testmod/resources/data/quilt_block_content_registry/attachments/minecraft/block/strippable_block.json).
 
In the mean time, as a mitigation of the issue, a custom data-pack could be created to re-add the missing entries.

**Comment by goosewoman** [comment]
I'm still experiencing this problem, but only on multiplayer. It works fine on singleplayer.

Using:
Minecraft 1.19.2
Quilt Loader 1.17.8
QFAPI 4.0.0-beta.26 and QSL 3.0.0-beta.25 
Terrablender 20.0.1.136
BYG 2.0.0.13

When I strip a log on a server it will momentarily look stripped (clientside stripping) and then instantly go back to unstripped. (server rejecting) 

The server only has QFAPI, BYG, TerraBlender and Geckolib installed. As does the client. Configs are also identical between client and server.
