### ISSUE TITLE
[Bug] Sheep won't eat meadow grass

### ISSUE THREAD

**Issue by mcmanustfj** [CorgiTaco/BYG#93]
Sheep will not eat meadow grass, which is necessary for them to regain their wool after shearing.

**Comment by Brun333rp** [comment]
also affects Overgrown Stone, Overgrown Netherrack and Overgrown Dacite

**Comment by TheDerpyPotato** [comment]
This is still the case, added the mod to the DW20 1.16 pack and sheep still wont eat grass. Really sucks as i live in a meadow and the grasses look different.

**Comment by CorgiTaco** [comment]
> 
> 
> also affects Overgrown Stone, Overgrown Netherrack and Overgrown Dacite

Since listed blocks are either from the nether/higher elevation biomes, this would NOT make sense. Meadow Grass is the only block that makes sense for this fix
