### ISSUE TITLE
[Bug]: Bookshelf crafting issues

### ISSUE THREAD

**Issue by ghost** [CorgiTaco/BYG#938]
### Minecraft Version

1.19.2

### BYG Version

2.0.0.7

### Terrablender Version

2.0.1.125

### Mod Loader

Forge

### Mod Loader Version

43.1.1

### Bug Severity

Minor

### What happened?

As someone briefly mentioned in a comment, bookshelves don't give progress towards the enchanting table. The modded ones do add towards it, however at least half of those can't be crafted (neither the bookshelf, nor the crafting table) and just give the regular versions. Besides, regular bookshelves don't get used when placed and have only their hitbox visible, until you break one, or place a block that isn't a bookshelf (but they still drop books, making an easy book, and thus, emerald farm). It's a bit of a mess with lots of exploring before you can enchant, which would be a good concept, considering how op enchanting is, but not like this man.

### latest.log

[2022-08-23-22.log.gz](https://github.com/AOCAWOL/BYG/files/9410897/2022-08-23-22.log.gz)

### Did you isolate BYG?

I tried BYG alone

**Comment by CorgiTaco** [comment]
Use Polymorph!

Forge: https://www.curseforge.com/minecraft/mc-mods/polymorph
Fabric: https://www.curseforge.com/minecraft/mc-mods/polymorph-fabric
