### ISSUE TITLE
[Bug/Enhancement]: Backup does not exclude the whole backup directory

### ISSUE THREAD

**Issue by jeremiahwinsley** [CorgiTaco/BYG#939]
### Minecraft Version

1.18.2

### BYG Version

1.4.2

### Terrablender Version

1.1.0.102

### Mod Loader

Forge

### Mod Loader Version

40.1.68

### Bug Severity

Minor

### What happened?

The backup process does not exclude the backup directory, but only the exact output name. This leads to compounding backup size when files get duplicated - which isn't really BYG's fault but it does end up much worse.
![2022-08-23 19_36_08-zip_file](https://user-images.githubusercontent.com/7946299/186285110-c89e1fd4-7989-49e1-a2dd-20ef99a03079.png)
![2022-08-23 19_35_22-backups](https://user-images.githubusercontent.com/7946299/186285133-c91bade9-a6e2-4a46-b9f6-a5c2f63e5106.png)
 

### latest.log

N/A

### Did you isolate BYG?

I did not try BYG alone

**Comment by CorgiTaco** [comment]
i see
