### ISSUE TITLE
In, fabric.mod.json, BYG requires 1.16.2

### ISSUE THREAD

**Issue by YTG1234** [CorgiTaco/BYG#94]
1.16.3 doesn't have any changes related to... well... anything. The only changes were in Piglin/Brute AI.
So in theory, BYG should work fine on 1.16.3

**Comment by YTG1234** [comment]
@CorgiTaco

**Comment by CorgiTaco** [comment]
No need to @ me as I'm bound to see this. And yes I'll patch it tomorrow.

**Comment by YTG1234** [comment]
Yup, sorry for the `@`. Thank you

**Comment by CorgiTaco** [comment]
It has been patched
