### ISSUE TITLE
[Bug]: Unable to generate superflat world. World generation type ignored.

### ISSUE THREAD

**Issue by mjevans** [CorgiTaco/BYG#940]
### Minecraft Version

1.18.2

### BYG Version

1.4.2

### Terrablender Version

1.0.102

### Mod Loader

Forge

### Mod Loader Version

40.1.73

### Bug Severity

Minor

### What happened?

I'm trying to setup a creative test world in the new Beta version of the Eigmatica 8 modpack (2.2.0).

New Single Player World: Allow Cheats: ON + World Type: Superflat

This SHOULD generate a standard, shallow, superflat world... instead it generates OTBYG biomes.

### latest.log

https://gist.github.com/mjevans/7ac0841c33c79fa94b50e28fe456b404

### Did you isolate BYG?

I did not try BYG alone

**Comment by NielsPilgaard** [comment]
From the linked issue:

> I've done some testing and it turns out Terralith is responsible for this, not BYG. Disabling it fixes superflat generation.
