### ISSUE TITLE
[Crash]: while loging my mc new world

### ISSUE THREAD

**Issue by esthancial** [CorgiTaco/BYG#941]
### Minecraft Version

1.18.2

### BYG Version

1.4.2

### Terrablender Version

1.1.0.102

### Mod Loader

Forge

### Mod Loader Version

40.1.73

### What happened?

idk what happen, can someone told me please ? ): when i create my world, everything crash while charging ![Capture d’écran 2022-08-25 195233](https://user-images.githubusercontent.com/112047670/186736589-81af070c-a6da-4ad6-907c-196f12e41fe8.jpg)

### crash-log

[crash-2022-08-25_19.38.49-server.txt](https://github.com/AOCAWOL/BYG/files/9427222/crash-2022-08-25_19.38.49-server.txt)

### latest.log

[2022-08-25-1.log](https://github.com/AOCAWOL/BYG/files/9427254/2022-08-25-1.log)

### Did you isolate BYG?

I tried BYG alone

**Comment by CorgiTaco** [comment]
Use terrablender .99
