### ISSUE TITLE
[Crash]: 

### ISSUE THREAD

**Issue by DoubleO713** [CorgiTaco/BYG#942]
### Minecraft Version

1.19.2

### BYG Version

2.0.0.8

### Terrablender Version

2.0.1.125

### Mod Loader

Fabric

### Mod Loader Version

0.14.9

### What happened?

I downloaded about 50 mods in my modpack on curse Forge. I added oh the biomes you'll go and clicked play. The Minecraft launcher opens so I click play like normal. It boots up Minecraft for a few seconds, then closes immediately with no crash report at all. I don't know why it keeps doing it.

### crash-log

no crash report.

### latest.log

none

### Did you isolate BYG?

I tried BYG alone

**Comment by CorgiTaco** [comment]
There's most definitely a latest.log or crash report, if there's not you're probably using the wrong java version
