### ISSUE TITLE
[Crash]: Generating a New World with Yung's Feature Mods.

### ISSUE THREAD

**Issue by MattB70** [CorgiTaco/BYG#947]
### Minecraft Version

1.18.2

### BYG Version

1.4.4

### Terrablender Version

1.1.0.102

### Mod Loader

Forge

### Mod Loader Version

40.1.73

### What happened?

Generating a new world will crash the game due to a conflict between BYG and multiple Yung's structure mods. The provided crash-log is a case where Yung's Better Mineshafts and BYG seem to fight over removing the vanilla stronghold feature, though I've had this crash while relating to Yung's Better Strongholds as well.

The latest.log contains a few startup errors that are unrelated including a well known quark biome error, it can be ignored.

This does not seem to happen when the mod and its dependencies are isolated, though Yung's mods have not been updated since this bug appeared in BYG 1.4.4.

### crash-log

https://gist.github.com/MattB70/f0b0acdfe2c37fecccb818edbc9548c4

### latest.log

https://gist.github.com/MattB70/9bd63b281b665d65d47b9d130d09ba1b

### Did you isolate BYG?

I tried BYG alone

**Comment by CorgiTaco** [comment]
This should no longer be an issue, if you still get this issue please comment/reopen this issue. Ensure you're using the latest versions of all mods relating to world generation and Terrablender!
