### ISSUE TITLE
[Bug]: Biomes are not generating after delete chunks with mca selector.

### ISSUE THREAD

**Issue by CristianMG** [CorgiTaco/BYG#948]
### Minecraft Version

1.18.2

### BYG Version

1.18.2-1.4.4

### Terrablender Version

1.18.2-1.2.0.126

### Mod Loader

Forge

### Mod Loader Version

1.18.2

### Bug Severity

Major

### What happened?

Hi guys.

We have a problem in our server with the generating of biomes, we had a server pefectly running, but we wanted to regenerate all world except a region where people have their items and houses, a little town, we remove chunks with the program mca selector, and it seems worked properly, but unfortunately the biomes are not generating now, and all biomes are vanilla, If someone have any suggestion can help me will be very appreciately.

Thanks.

### latest.log

https://mclo.gs/4Y3chCA

### Did you isolate BYG?

I did not try BYG alone

**Comment by linkhidalgogato** [comment]
the problem seems to be an incompatibility with blueprint or atleast thats what it is for me and i can see blueprint is installed from the logs

**Comment by CristianMG** [comment]
Terraforge  version was guilty, downgrade version of terraforge fixed the problem
