### ISSUE TITLE
meadow grass broken

### ISSUE THREAD

**Issue by milkev** [CorgiTaco/BYG#95]
a few things about meadow grass, i havent tested the other custom dirt-type blocks.
1; meadow grass does not spread at all
2; sheep will not eat meadow grass to regrow wool
3; it turns back into regular dirt when hoe'd. this one isnt that big of a deal but still annoying
4; most saplings, even ones from byg, cannot be placed on meadow grass/dirt
5; it does not revert to dirt when a block is ontop of it. even the logs for the shrubs that generate on the meadow have a grass block under them
on the latest version of byg, fabric, fabric api and 1.16.3

**Comment by CorgiTaco** [comment]
This will be fixed on OCT 31
