### ISSUE TITLE
[Crash]: C2ME

### ISSUE THREAD

**Issue by Momfie** [CorgiTaco/BYG#951]
### Minecraft Version

1.16.5

### BYG Version

1.3.5/1.1.8

### Terrablender Version

N/A

### Mod Loader

Fabric

### Mod Loader Version

0.14.9

### What happened?

making a modpack with heavy optimization, the server will crash when using any 1.16.5 C2ME fabric release

server will also crash with version byg 1.3.5 without mods apart from fabric api and no old configs present

version byg 1.1.8 works fine in modpack without C2ME 

included logs have custom modpack mods present

support for C2ME would be nice but it would not be a necessity if 1.16.5 is not being supported anymore

### crash-log

[crash-2022-09-05_12.39.33-server.txt](https://github.com/AOCAWOL/BYG/files/9489174/crash-2022-09-05_12.39.33-server.txt)

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/9489178/latest.log)

### Did you isolate BYG?

I tried BYG alone

**Comment by StockiesLad** [comment]
C2ME and BYG are both unsupported for 1.16.5

**Comment by CorgiTaco** [comment]
C2ME is a huge hack, we won't support it.
