### ISSUE TITLE
[Crash]:  world creation exit code -805306369

### ISSUE THREAD

**Issue by Gnobolin** [CorgiTaco/BYG#952]
### Minecraft Version

1.19.2

### BYG Version

1.18.2-1.4.4 

### Terrablender Version

 1.19.2-2.0.1.127

### Mod Loader

Forge

### Mod Loader Version

1.19.2-Forge-43.1.16 

### What happened?

When creating a new world, the loading screen into the world creation loads longer than normally
![crash 1](https://user-images.githubusercontent.com/106928967/188493069-88b1cab7-6098-4aa1-a16a-9d4678a3a80b.PNG)
When clicking "create world" the normal map loading screen doesn't appear, leaving me with a blank dirt screen
![crash 2](https://user-images.githubusercontent.com/106928967/188493156-ba2847e7-86c8-460d-b476-ecdea202edb9.PNG)
After that the game stops responding, and it shows the "stopped responding" pop up.
![crash 3](https://user-images.githubusercontent.com/106928967/188493708-ee71b0bc-326c-401a-84b9-dc42d1268125.PNG)
When clicking the "close the program" button, the game closes, opens the launcher and shows the exit code.
![crash 4](https://user-images.githubusercontent.com/106928967/188493934-d3aac57e-2a98-4176-98fc-82aa3a5326f4.PNG)

### crash-log

no crash log, but when the game closes i get the exit code -805306369

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/9491415/latest.log)

### Did you isolate BYG?

I tried BYG alone

**Comment by CorgiTaco** [comment]
You are using a 1.18.2 version of BYG on 1.19...? 

1.19: https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go/files/3956500

**Comment by CorgiTaco** [comment]
Make sure to also reset your configs.
