### ISSUE TITLE
[1.15.2 Forge] Drop your 1.15.2 bugs here and we'll tackle them(or maybe not) in the future.

### ISSUE THREAD

**Issue by CorgiTaco** [CorgiTaco/BYG#96]
Post your 1.15.2 issues here as this version is no longer supported but we may consider coming back to it later down the road!

**Comment by Tyrius1** [comment]
Minecraft 1.15.2
Forge 31.2.36
Biomes You Go 1.0.11 MCV: 1.15.2

i really cant confirm that its byg or even isolate any specific conditions in game that cause it
but when i remove byg it doesnt appear to happen anymore
when exploring the world on occasion the world gen will just stop

https://pastebin.com/0Y2Agp1q


Here is what i've tweaked in the config if that might help to narrow it down
https://pastebin.com/1gF542ew

**Comment by Tyrius1** [comment]
When breaking white cherry foliage it drops pink cherry foliage

**Comment by tlitookilakin** [comment]
I am also having issues with the server hanging during worldgen, and it appears to happen both in the nether and overworld. It also seems to be local to specific areas, as in testing those areas will always cause it to hang. Server log is silent, as there is no crash, it just gets stuck. I'll see about getting a good seed to demonstrate the issue and edit this comment then.

**Comment by CorgiTaco** [comment]
> I am also having issues with the server hanging during worldgen, and it appears to happen both in the nether and overworld. It also seems to be local to specific areas, as in testing those areas will always cause it to hang. Server log is silent, as there is no crash, it just gets stuck. I'll see about getting a good seed to demonstrate the issue and edit this comment then.

Also ensure that byg is entirely independent too

**Comment by Mysteriaa** [comment]
The Palo Verde trees seem to be having some weird issues. Most leaves keep decaying, even when connected to one another, and I can't plant their saplings on red sand blocks. Using the latest version of BYG for 1.15.2.

Edit: Should also add that there seems to be an issue with Holly trees producing WAY too many Holly Berries. Seems to be stemming from the same leaf decay issue as well.

![image](https://user-images.githubusercontent.com/67705660/94619279-98567280-027a-11eb-99c1-59b9eada5933.png)
![image](https://user-images.githubusercontent.com/67705660/94619548-1450ba80-027b-11eb-91b0-6db04af36b73.png)
![image](https://user-images.githubusercontent.com/67705660/94619703-537f0b80-027b-11eb-947f-608b1fdeb3ae.png)

**Comment by tlitookilakin** [comment]
Update: I think the hanging problem is not related to BYG, or was a conflict with another mod that has been fixed. After updating some mods, the problem no longer occurs in new areas, although the old locations that would break the server in the past still do. Maybe some kind of entity problem or a corrupted chunk.

**Comment by EightBlade** [comment]
Cika logs don't function right, you can't use them to make charcoal or keep the furnace lit. You also can't make them into campfires.

**Comment by CorgiTaco** [comment]
With how much of a task 1.16 is to maintain, its impossible to even find time to patch 1.15 bugs. I will be closing the issue, but anyone may feel free to add more 1.15 bugs here!
