### ISSUE TITLE
[Bug]: "'byg:mangrove_sapling' is not a valid id in registry"

### ISSUE THREAD

**Issue by MattSugui** [CorgiTaco/BYG#960]
### Minecraft Version

1.19.2

### BYG Version

2.0.0.11

### Terrablender Version

2.0.1.125

### Mod Loader

Forge

### Mod Loader Version

43.1.16

### Bug Severity

Major

### What happened?

![image](https://user-images.githubusercontent.com/69552216/189510047-27dc2d89-00e4-4912-badf-83b103b427b6.png)

The mod loading process fails because it fails to look for the mangrove sapling item under this mod's namespace

I think that because there is now officially mangrove in vanilla MC you decided to remove the mangrove items from this game, but must've forgot about the villager trades files

### latest.log

[https://gist.github.com/MattSugui/06463a62c89ca1cbfa5f9e2a37417727](https://gist.github.com/MattSugui/06463a62c89ca1cbfa5f9e2a37417727)

### Did you isolate BYG?

I tried BYG alone

**Comment by CorgiTaco** [comment]
Reset your trades config

**Comment by MattSugui** [comment]
how do i do that though

edit: n vm found it

**Comment by Blake4Uchiha** [comment]
Hey I also have the exact same problem but idk how to reset the config could you explain me how you did that?

**Comment by justliliandev** [comment]
Go to the config folder, go into the byg folder and delete the trades.json5 file
