### ISSUE TITLE
[Bug]: Mahogany Boat has no model texture

### ISSUE THREAD

**Issue by NielsPilgaard** [CorgiTaco/BYG#964]
### Minecraft Version

1.18.2

### BYG Version

Oh_The_Biomes_You'll_Go-forge-1.18.2-1.4.4

### Terrablender Version

TerraBlender-forge-1.18.2-1.2.0.126

### Mod Loader

Forge

### Mod Loader Version

40.1.80

### Bug Severity

Minor

### What happened?

The Mahogany Boat from BYG has no model texture:

![image](https://user-images.githubusercontent.com/21295394/189736132-912ab480-4118-42f1-8a4f-47c30a77d8b2.png)

### latest.log

Seems redundant in this case. I will happily provide it if needed however.

### Did you isolate BYG?

I did not try BYG alone

**Comment by CorgiTaco** [comment]
Fixed in https://github.com/AOCAWOL/BYG/commit/de2fd23ef48302e6818270271390c11318d3db2b
