### ISSUE TITLE
[Crash]: Crashing when generating a new chunk

### ISSUE THREAD

**Issue by Axolochiz** [CorgiTaco/BYG#965]
### Minecraft Version

1.19.2

### BYG Version

Oh_The_Biomes_You'll_Go-fabric-1.19-2.0.0.7

### Terrablender Version

TerraBlender-fabric-1.19-2.0.0.120

### Mod Loader

Fabric

### Mod Loader Version

fabric-loader-0.14.8-1.19

### What happened?

I'm tryna continue playing the Better Minecraft Fabric v5 but whenever I get close to a new chunk it immediately crashes and the crash log says its crashing while trying to generate a temperate rainforest

### crash-log

[crash-2022-09-12_15.33.12-server.txt](https://github.com/AOCAWOL/BYG/files/9551242/crash-2022-09-12_15.33.12-server.txt)

### latest.log

[rei-issues.log](https://github.com/AOCAWOL/BYG/files/9551246/rei-issues.log)

### Did you isolate BYG?

I tried BYG alone

**Comment by CorgiTaco** [comment]
This should no longer be an issue, if you still get this issue please comment/reopen this issue. Ensure you're using the latest versions of all mods relating to world generation and Terrablender!
