### ISSUE TITLE
[1.16.3] Spamming log with "Unkown Biome ID", broken features in world generation when Optifine is loaded.

### ISSUE THREAD

**Issue by Excederus** [CorgiTaco/BYG#97]
The mod literally spams about 150-200 *thousand* lines of "Unkown Biome ID" while preparing the spawn area.
Probably significantly slowing down initial world generation. Also note I did not change anything in the config of the mod.

Forge: 34.0.9

UPDATE: Just tested byg alone and it doesnt throw those errors. I'm gonna try to find which mod interaction causes this.
UPDATE2: It's an interaction with OptiFine. Maybe you can investigate if it's something on your end and if not just close it or something. I also opened an issue on the Optifine issue tracker.

The mods I am using (I tested without byg and it doesn't throw those errors then):
![2020-09-22 18_53_30-Window](https://user-images.githubusercontent.com/29584262/93913215-0ba13700-fd05-11ea-8edb-c2f2113a3588.png)

The log is 20MB because of the stupid amount of lines.
[latest.log](https://github.com/CorgiTaco/BYG/files/5262918/latest.log)

**Comment by CorgiTaco** [comment]
Mod Interaction: Ore generation gets completely disabled when paired with Optifine (how does that even happen)

Only used BYG and Optifine this time. It does work with BYG alone.

**Comment by CorgiTaco** [comment]
Then again this issue has been known for awhile now hence why the big red letters on the BYG Curse page

**Comment by Excederus** [comment]
Oh damn my bad. I actually overread that somehow.

**Comment by Gbergz** [comment]
Alright so for me the problem went away straight away when removing the mod '[CraftPresence](https://www.curseforge.com/minecraft/mc-mods/craftpresence)'.
Biomes now generate & no more unknown biome id spam. Can create worlds without any issues now.
If anyone has this issue and has that mod, try removing it.

**Comment by CorgiTaco** [comment]
Relevant: https://github.com/sp614x/optifine/issues/4880

**Comment by CorgiTaco** [comment]
Modded biomes are no longer broken in OptiFine HD U G5 for 1.16.4
