### ISSUE TITLE
[Bug]: biomes not generating in the nether/end

### ISSUE THREAD

**Issue by anniefaye** [CorgiTaco/BYG#970]
### Minecraft Version

1.16.5

### BYG Version

1.3.4

### Terrablender Version

N/A

### Mod Loader

Fabric

### Mod Loader Version

0.11.6

### Bug Severity

Minor

### What happened?

installed on an apex hosting server, nether/end biomes wont generate 

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/9568329/latest.log)

### Did you isolate BYG?

I tried BYG alone

**Comment by CorgiTaco** [comment]
Follow the steps here: https://github.com/AOCAWOL/BYG/wiki/Nether-&-End-Biomes-FAQ
