### ISSUE TITLE
[Crash]: Feature Order crash when ran with Traverse, Terrestria, and Cinderscape.

### ISSUE THREAD

**Issue by BosterJowls** [CorgiTaco/BYG#971]
### Minecraft Version

1.19.2

### BYG Version

2.0.0.11

### Terrablender Version

2.0.1.127

### Mod Loader

Fabric

### Mod Loader Version

0.14.9

### What happened?

World Generation crashes when OBYG is ran with Traverse, Terrestria, and Cinderscape.

Running BYG alone, or just the other three removes the crashing

### crash-log

[crash-2022-09-15_19.53.48-server.txt](https://github.com/AOCAWOL/BYG/files/9574930/crash-2022-09-15_19.53.48-server.txt)

### latest.log

[2022-09-15-7.log.gz](https://github.com/AOCAWOL/BYG/files/9574933/2022-09-15-7.log.gz)

### Did you isolate BYG?

I tried BYG alone

**Comment by BosterJowls** [comment]
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2022-09-15 19:53:48
Description: Exception generating new chunk

java.lang.IllegalStateException: Feature order cycle found, involved sources: [Reference{ResourceKey[minecraft:worldgen/biome / byg:firecracker_shrubland]=net.minecraft.class_1959@400543ef}, Reference{ResourceKey[minecraft:worldgen/biome / terrestria:outback]=net.minecraft.class_1959@441d212f}]
	at net.minecraft.class_7510.method_44210(class_7510.java:100)
	at net.minecraft.class_2794.md87899f$lambda$updateFeaturesPerStep$1$0(class_2794.java:2854)
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183)
	at net.minecraft.class_2794.method_12102(class_2794.java:397)
	at net.minecraft.class_2806.method_20613(class_2806.java:145)
	at net.minecraft.class_2806.method_12154(class_2806.java:292)
	at net.minecraft.class_3898.method_17225(class_3898.java:679)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.class_3898.method_17224(class_3898.java:673)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_3900.method_17634(class_3900.java:62) 
	at net.minecraft.class_3846.method_16907(class_3846.java:91)
	at net.minecraft.class_3846.method_16900(class_3846.java:146)
	at net.minecraft.class_3846.run(class_3846.java:102)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_7510.method_44210(class_7510.java:100)
	at net.minecraft.class_2794.md87899f$lambda$updateFeaturesPerStep$1$0(class_2794.java:2854)
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183)
	at net.minecraft.class_2794.method_12102(class_2794.java:397)
	at net.minecraft.class_2806.method_20613(class_2806.java:145)
	at net.minecraft.class_2806.method_12154(class_2806.java:292)
	at net.minecraft.class_3898.method_17225(class_3898.java:679)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.class_3898.method_17224(class_3898.java:673)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_3900.method_17634(class_3900.java:62)
	at net.minecraft.class_3846.method_16907(class_3846.java:91)
	at net.minecraft.class_3846.method_16900(class_3846.java:146)
	at net.minecraft.class_3846.run(class_3846.java:102)

-- Chunk to be generated --
Details:
	Location: 2,29
	Position hash: 124554051586
	Generator: net.minecraft.class_3754@45bd5eca
Stacktrace:
	at net.minecraft.class_3898.method_17225(class_3898.java:679)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.class_3898.method_17224(class_3898.java:673)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_3900.method_17634(class_3900.java:62)
	at net.minecraft.class_3846.method_16907(class_3846.java:91)
	at net.minecraft.class_3846.method_16900(class_3846.java:146)
	at net.minecraft.class_3846.run(class_3846.java:102)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: 625
	Level dimension: minecraft:overworld
	Level spawn location: World: (56,64,488), Section: (at 8,0,8 in 3,4,30; chunk contains blocks 48,-64,480 to 63,319,495), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 0 game time, 0 day time
	Level name: Test
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3786(MinecraftServer.java:367)
	at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:315)
	at net.minecraft.class_1132.method_3823(class_1132.java:68)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1112966208 bytes (1061 MiB) / 3087007744 bytes (2944 MiB) up to 17179869184 bytes (16384 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: 12th Gen Intel(R) Core(TM) i5-12600K
	Identifier: Intel64 Family 6 Model 151 Stepping 2
	Microarchitecture: unknown
	Frequency (GHz): 3.69
	Number of physical packages: 1
	Number of physical CPUs: 10
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 3080
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2216
	Graphics card #0 versionInfo: DriverVersion=31.0.15.1694
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 4.80
	Memory slot #0 type: Unknown
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 4.80
	Memory slot #1 type: Unknown
	Virtual memory max (MB): 37373.30
	Virtual memory used (MB): 16777.24
	Swap memory total (MB): 4864.00
	Swap memory used (MB): 103.55
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx16G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		advancednetherite: Advanced Netherite 1.6.4-1.19.2
		amecs: Amecs 1.3.8+mc.1.19-rc2
			amecsapi: Amecs API 1.3.6+mc22w17a
		antighost: AntiGhost 1.19.1-fabric0.58.5-1.1.5
			crowdin-translate: CrowdinTranslate 1.4+1.19
		appleskin: AppleSkin 2.4.1+mc1.19
		architectury: Architectury 6.2.43
		auditory: Auditory 0.0.3-1.19.x
		backslot: BackSlot 1.2.9
		badpackets: Bad Packets 0.2.0
		basicshields: Basic Shields [Fabric] 1.4.0-pre1-1.19.2
		bclib: BCLib 2.1.0
		betteranimalsplus: Better Animals Plus 1.19-11.0.7
		betterend: Better End 2.1.0
		betterf3: BetterF3 1.3.2
		betternether: Better Nether 7.1.0
		biomemakeover: Biome Makeover 1.19.2-1.5.12
		bookshelf: Bookshelf 16.1.5
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.4.2-1.19
			maelstrom_library: Maelstrom Library 1.3-1.19-pre1
			multipart_entities: MultipartEntities 1.2-1.19-pre1
		byg: Oh The Biomes You'll Go 2.0.0.11
		capybara: Capybara 1.0.6
		cardinal-components: Cardinal Components API 5.0.1
			cardinal-components-base: Cardinal Components API (base) 5.0.1
			cardinal-components-block: Cardinal Components API (blocks) 5.0.1
			cardinal-components-chunk: Cardinal Components API (chunks) 5.0.1
			cardinal-components-entity: Cardinal Components API (entities) 5.0.1
			cardinal-components-item: Cardinal Components API (items) 5.0.1
			cardinal-components-level: Cardinal Components API (world saves) 5.0.1
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.0.1
			cardinal-components-world: Cardinal Components API (worlds) 5.0.1
		cem: Custom Entity Models 0.7.1
		chubby_stuff: Chubby Stuff 2.1.0+1.19.2
		cinderscapes: Cinderscapes 3.0.0-beta.1
			cinderscapes-client: Cinderscapes: Client 3.0.0-beta.1
			cinderscapes-common: Cinderscapes: Common 3.0.0-beta.1
			cinderscapes-worldgen: Cinderscapes: World Generation 3.0.0-beta.1
			terraform-biome-remapper-api-v1: Terraform Biome Remapper API (v1) 4.1.1
			terraform-shapes-api-v1: Terraform Shapes API (v1) 4.1.1
			terraform-wood-api-v1: Terraform Wood API (v1) 4.1.1
		citresewn: CIT Resewn 1.1.2+1.19.2
			citresewn-defaults: CIT Resewn: Defaults 1.1.2+1.19.2
		cloth-config: Cloth Config v8 8.2.88
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 9.0.0+11
		completeconfig: CompleteConfig 2.0.0
			coat: Coat 1.0.0-beta.17+mc22w17a
			completeconfig-base: completeconfig-base 2.0.0
			completeconfig-gui-cloth: completeconfig-gui-cloth 2.0.0
			completeconfig-gui-coat: completeconfig-gui-coat 2.0.0
		continuity: Continuity 2.0.1+1.19
		creaturesofthesnow: Creatures Of The Snow 3.0.0+1.19.2
		cullleaves: Cull Leaves 2.3.4
		darkpaintings: DarkPaintings 13.1.2
		deeperdarker: Deeper And Darker 1.0.2b-fabric
			customportalapi: Custom Portal Api 0.0.1-beta52-1.19
		detailab: Detail Armor Bar 2.6.2+1.19-fabric
		diggusmaximus: Diggus Maximus 1.5.8-1.19
			kyrptconfig: Kyrpt Config 1.4.14-1.19
		disable_custom_worlds_advice: Disable Custom Worlds Advice 3.0
		dyeable_shulkers: Dyeable Shulkers 1.0.2
		ecologics: Ecologics 2.1.10
		edenring: EdenRing 0.6.4
		enchdesc: EnchantmentDescriptions 13.0.1
		entity_texture_features: Entity Texture Features 4.0.2
		explorerscompass: Explorer's Compass 1.19.2-2.1.2-fabric
		fabric-api: Fabric API 0.60.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.11+e62f51a390
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.9+9ff28f4090
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.17+aeb40ebe90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.20+aeb40ebe90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.1+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.11+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.1.7+0c17ea9690
			fabric-commands-v0: Fabric Commands (v0) 0.2.28+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.34+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.2.3+aeb40ebe90
			fabric-convention-tags-v1: Fabric Convention Tags 1.1.1+7cd20a1490
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.5+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.1.8+a680b9b490
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.30+aeb40ebe90
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.18+9ff28f4090
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.28+aeb40ebe90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.28+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.21+aeb40ebe90
			fabric-item-api-v1: Fabric Item API (v1) 1.5.7+35a03c4390
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.28+aeb40ebe90
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.20+aeb40ebe90
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.18+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.2+aeb40ebe90
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.3+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.6+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.3+176380a290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.14+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.17+aeb40ebe90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.4+5eb68ef290
			fabric-networking-v0: Fabric Networking (v0) 0.3.21+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.11+aeb40ebe90
			fabric-particles-v1: Fabric Particles (v1) 1.0.10+aeb40ebe90
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.24+aeb40ebe90
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.10+aeb40ebe90
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.12+aeb40ebe90
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.20+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.14+aeb40ebe90
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.7+aeb40ebe90
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.22+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.16+aeb40ebe90
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.11+e62f51a390
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.6.1+aeb40ebe90
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.26+f05effaf90
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.13+9ff28f4090
			fabric-textures-v0: Fabric Textures (v0) 1.0.20+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.0.11+83a8659290
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.0+42d99c3290
		fabric-language-kotlin: Fabric Language Kotlin 1.8.3+kotlin.1.7.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.3
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.0
		fabricloader: Fabric Loader 0.14.9
		fabricshieldlib: Fabric Shield Lib 1.6.0-1.19
			mm: Manningham Mills 2.3
		fallingtree: FallingTree 3.10.0
		farmersdelight: Farmer's Delight 1.19-1.3.3
		ferritecore: FerriteCore 4.2.1
		galosphere: Galosphere 1.19.1-1.1.2
		geckolib3: Geckolib 3.1.18
			com_eliotlash_mclib_mclib: mclib 18
			com_eliotlash_molang_molang: molang 18
		geodes: More Geodes 1.5.1
		goodall: Goodall 1.1.1
		indium: Indium 1.0.9+mc1.19.2
		iris: Iris 1.3.1
			org_anarres_jcpp: jcpp 1.4.14
		java: OpenJDK 64-Bit Server VM 17
		lambdabettergrass: LambdaBetterGrass 1.3.0+1.19
			spruceui: SpruceUI 4.0.0+1.19
		lambdynlights: LambDynamicLights 2.1.2+1.19
			pride: Pride Lib 1.1.2+1.19
		lazydfu: LazyDFU 0.1.3
		lithium: Lithium 0.8.3
		lod: Distant Horizons 1.6.9a
		mavm: More Axolotl Variants Mod 1.1.0
		midnightlib: MidnightLib 0.6.0
		minecraft: Minecraft 1.19.2
		modmenu: Mod Menu 4.0.6
		moocow: Moobloom 1.19.2-1.0
		more-axolotls: More Axolotls 1.0.2
		morefrogs: More Frogs 1.19.x-1.2.2-fabric
		naturalist: Naturalist 2.1.1
		naturescompass: Nature's Compass 1.19.2-2.0.4-fabric
		npcvariety: NPC Variety 2.2.2
		patchouli: Patchouli 1.19.2-76-FABRIC
			fiber: fiber 0.23.0-2
		puzzle: Puzzle 1.4.0-1.19
			puzzle-base: Puzzle Base 1.4.0-1.19
			puzzle-gui: Puzzle GUI 1.4.0-1.19
			puzzle-models: Puzzle Models 1.4.0-1.19
			puzzle-splashscreen: Puzzle Splash Screen 1.4.0-1.19
		reeses-sodium-options: Reese's Sodium Options 1.4.7+mc1.19.2-build.59
		reinfchest: Reinforced Chests 2.1.2+1.19
			reinfcore: Reinforced Core 3.0.2+1.19
		roughlyenoughitems: Roughly Enough Items 9.1.530
			error_notifier: Error Notifier 1.0.9
		sodium: Sodium 0.4.4+build.18
			org_joml_joml: joml 1.10.4
		sodium-extra: Sodium Extra 0.4.10+mc1.19.2-build.64
			caffeineconfig: CaffeineConfig 1.0.0+1.17
		sound_physics_remastered: Sound Physics Remastered 1.19.2-1.0.12
		stacker: Stacker 3.0.2-1.19.x
			stacc: Stacc 1.3.4
		starlight: Starlight 1.1.1+fabric.ae22326
		steves_vanilla: Steves Vanilla 1.19.2+2.0.1
		stoneholm: Stoneholm 1.4.4
		t_and_t: Towns and Towers - Structure Add-on 1.8.2
		terrablender: TerraBlender 2.0.1.127
			com_electronwill_night-config_core: core 3.6.4
			com_electronwill_night-config_toml: toml 3.6.4
		terrestria: Terrestria 5.0.0
			terraform-config-api-v1: Terraform Config API (v1) 4.1.1
			terraform-dirt-api-v1: Terraform Dirt API (v1) 4.1.1
			terraform-surfaces-api-v1: Terraform Surfaces API (v1) 4.1.1
			terraform-tree-api-v1: Terraform Tree API (v1) 4.1.1
			terrestria-client: Terrestria: Client 5.0.0
			terrestria-common: Terrestria: Common 5.0.0
			terrestria-worldgen: Terrestria: World Generation 5.0.0
		travelersbackpack: Traveler's Backpack 1.19.2-8.2.1
		traverse: Traverse 6.0.1
			traverse-client: Traverse: Client 6.0.1
			traverse-common: Traverse: Common 6.0.1
			traverse-worldgen: Traverse: World Generation 6.0.1
		unstructured: Unstructured 0.5.2+1.19.2
		visuality: Visuality 0.5.1
		wthit: wthit 5.12.0
		xaerominimapfair: Xaero's Minimap 22.14.1
		xaeroworldmap: Xaero's World Map 1.27.0
	Loaded Shaderpack: BSL_v8.1.03.zip
		Profile: HIGH (+0 options changed by user)
	Server Running: true
	Player Count: 0 / 8; []
	Data Packs: vanilla, Fabric Mods, file/VanillaTweaks (Crafting Tweaks).zip, file/armored elytra v1.0.6.zip, file/double shulker shells v1.3.3.zip, file/dragon drops v1.3.3.zip, file/fast leaf decay v2.0.6.zip, file/larger phantoms v1.2.4.zip, file/more mob heads v2.10.1.zip
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: fabric-loader-0.14.9-1.19.2

**Comment by CorgiTaco** [comment]
I believe this is resolved.
