### ISSUE TITLE
[Bug]: no quest book

### ISSUE THREAD

**Issue by ruth123456788** [CorgiTaco/BYG#973]
### Minecraft Version

1.19.2

### BYG Version

?

### Terrablender Version

?

### Mod Loader

Fabric

### Mod Loader Version

?

### Bug Severity

Major

### What happened?

There is no quest book. very disappointing. 

### latest.log

quest book

### Did you isolate BYG?

I did not try BYG alone

**Comment by CorgiTaco** [comment]
You provided no information such as byg version or latest.log. Please make a new issue report with information
