### ISSUE TITLE
[Crash]: Installation

### ISSUE THREAD

**Issue by Horux1** [CorgiTaco/BYG#974]
### Minecraft Version

1.18.2

### BYG Version

Oh_The_Biomes_You'll_Go-forge-1.18.2-1.4.4

### Terrablender Version

TerraBlender-forge-1.18.2-1.2.0.126

### Mod Loader

Forge

### Mod Loader Version

forge-1.18.2-40.1.80

### What happened?

when I install byg, game failed to boot up. It looks like caused by this mod but I'm not sure

### crash-log

[crash-2022-09-16_12.09.44-fml.txt](https://github.com/AOCAWOL/BYG/files/9585984/crash-2022-09-16_12.09.44-fml.txt)

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/9585988/latest.log)

### Did you isolate BYG?

I did not try BYG alone

**Comment by CorgiTaco** [comment]
Delete configs and let em regen
