### ISSUE TITLE
[Bug]: Sythian stalks grow infinitely in Overworld

### ISSUE THREAD

**Issue by SodiumZH** [CorgiTaco/BYG#975]
### Minecraft Version

1.18.2

### BYG Version

1.4.3

### Terrablender Version

1.1.0.102

### Mod Loader

Forge

### Mod Loader Version

40.1.68

### Bug Severity

Minor

### What happened?

When sythian stalks are planted in the overworld, they will grow infinitely until they arrive the world height limitation. All stalk blocks have the age 1.
![Uploading 2022-09-17_01.21.15.png…]()

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/9586011/latest.log)

### Did you isolate BYG?

I did not try BYG alone

**Comment by SodiumZH** [comment]
![2022-09-17_01 21 15](https://user-images.githubusercontent.com/46860829/190696105-7174ddb6-ebdf-4285-b377-1e742477f5ca.png)

**Comment by Gamemassa** [comment]
How is this a bug? This sounds amazingly efficient if you're farming them.

**Comment by SodiumZH** [comment]
> How is this a bug? This sounds amazingly efficient if you're farming them.

Yes it's very productive, but perhaps not the authors' intended behavior. The Sythian Stalk seems to be designed as the Nether version of Bamboo. So I'd like to ask if the infinite growth is really an intended behavior.

**Comment by SodiumZH** [comment]
> How is this a bug? This sounds amazingly efficient if you're farming them.

Also Sythian Stalk blocks have a parameter "age", suggesting it's growth should perhaps be controlled by this parameter. So I tend to consider this as a bug.
