### ISSUE TITLE
[Bug]: Possible bug with natural generation of Brown/Red Birch trees on Fabric

### ISSUE THREAD

**Issue by Gamemassa** [CorgiTaco/BYG#976]
### Minecraft Version

1.19.2

### BYG Version

2.0.0.11

### Terrablender Version

2.0.1.127

### Mod Loader

Fabric

### Mod Loader Version

0.14.9

### Bug Severity

Minor

### What happened?

Is anyone else having trouble finding Brown/Red Birch trees? According to the BYG wiki, they grow in Autumnal Forests, but I've checked several of those and found no Brown/Red Birch.

### latest.log

N/A

### Did you isolate BYG?

I tried BYG alone

**Comment by CorgiTaco** [comment]
This is a question for the discord, not the issue tracker
