### ISSUE TITLE
[Crash]: Game crashes literally every time i enter the nether

### ISSUE THREAD

**Issue by JosYc24** [CorgiTaco/BYG#977]
### Minecraft Version

1.16.5

### BYG Version

1.3.5

### Terrablender Version

N/A

### Mod Loader

Forge

### Mod Loader Version

36.2.39

### What happened?

Game crashes literally every time i enter the nether, i just cant open the nether and probably the end too. The game just instantly crashes, it doesnt generate the terrain.

### crash-log

https://gist.github.com/JosYc24/e4ab13485e2b4f468dd754f684f54230#file-gistfile1-txt

### latest.log

i dont know how

### Did you isolate BYG?

I did not try BYG alone

**Comment by FudgeBot47** [comment]
I have isolated BYG, and yes, it crashes EVERY time on version 1.3.5. Sometimes you get a glimpse of the nether before it crashes, sometimes it crashes before any chunks are even loaded. This is very annoying as someone who's playing modded 1.16.5.
Edit: If it's important, I'm running Forge 36.2.39

**Comment by CorgiTaco** [comment]
Resolved in:

Forge: https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go/files/4024011
Fabric: https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go-fabric/files/4024006

**Comment by FudgeBot47** [comment]
So it's mostly fixed. If you attempt to load Nether chunks that already existed before the bug was fixed, the game will still crash. I tried deleting all the Nether files in DIM-1, but it still crashes.
Basically I can use the Nether in an already existing worlds by traveling out many blocks so I don't load those problematic chunks. I can live with that, it's just a little inconvenient.
Are there other world files I could possibly delete to remedy this? 
Thanks for all the hard work guys, this mod is amazing.

**Comment by CorgiTaco** [comment]
@FudgeBot47 please send the new crash log!

**Comment by FudgeBot47** [comment]
[crash-2022-10-10_18.05.46-server.txt](https://github.com/AOCAWOL/BYG/files/9749510/crash-2022-10-10_18.05.46-server.txt)

**Comment by CorgiTaco** [comment]
Seems to be an incompat with Terra

**Comment by CorgiTaco** [comment]
try terra alone

**Comment by FudgeBot47** [comment]
Terra by itself loads the Nether just fine. Deleting the Terra mod, then removing the existing Nether files does not fix the crashing issue on BYG.
Like I said before, new worlds load the Nether just fine with BYG, but worlds where a portal has already been traveled through crash.

[crash-2022-10-10_18.31.42-server.txt](https://github.com/AOCAWOL/BYG/files/9749620/crash-2022-10-10_18.31.42-server.txt)

**Comment by CorgiTaco** [comment]
Yeah i dont know then...

**Comment by OakLoaf** [comment]
> Resolved in:
> 
> Forge: https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go/files/4024011 Fabric: https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go-fabric/files/4024006

The Forge version is labelled as Fabric and so is not appearing in the CurseForge launcher btw.

After updating it appears as though I am also having this crashing issue that appears the same as what the original poster had.
Let me send the log:
[crash-2022-10-15_16.21.13-server.txt](https://github.com/AOCAWOL/BYG/files/9792464/crash-2022-10-15_16.21.13-server.txt)

**Comment by CorgiTaco** [comment]
Fixed the label

**Comment by OakLoaf** [comment]
> Fixed the label

Awesome news, let me know if there is anything I can help test with the error!

**Comment by OakLoaf** [comment]
Any update on this? Could this issue be reopened until it's actually fixed?
