### ISSUE TITLE
[Bug]: BYG's lament woods are flammable

### ISSUE THREAD

**Issue by RedBeast1959** [CorgiTaco/BYG#979]
### Minecraft Version

1.19.2

### BYG Version

Oh_The_Biomes_You'll_Go-forge-1.19.2-2.0.0.11.jar

### Terrablender Version

TerraBlender-forge-1.19.2-2.0.1.127.jar

### Mod Loader

Forge

### Mod Loader Version

43.1.30

### Bug Severity

Major

### What happened?

![2022-09-28_20 11 43](https://user-images.githubusercontent.com/100399264/192765820-8b244619-1ab9-4dbf-9aae-f307cbdc3666.png)

Current 1.19.2 version, BYG's nether lament wooden log and leave are flammable unlike other nether variants wood(crimson/warped). This problem makes whole lament forest burn and turn into nothing.

### latest.log

.

### Did you isolate BYG?

I tried BYG alone

**Comment by CorgiTaco** [comment]
*Should be fixed* on latest, comment back here if the issue persists
