### ISSUE TITLE
[1.16.3] Ore generation gets disabled

### ISSUE THREAD

**Issue by Excederus** [CorgiTaco/BYG#98]
Mod Interaction: Ore generation gets completely disabled when paired with Optifine (how does that even happen)

Only used BYG and Optifine this time. It does work with BYG alone.

Log should be the same as the one from #97

**Comment by CorgiTaco** [comment]
Please comment on the previous issue as this is clearly and incompatibility with opti and byg. And properly title issues when doing so as this is a very dramatic title.
