### ISSUE TITLE
[Bug]: Incompatibility with BYG replace BoP nether biome's blocks and flora into netherrack(1.19.2)

### ISSUE THREAD

**Issue by RedBeast1959** [CorgiTaco/BYG#980]
### Minecraft Version

1.19.2

### BYG Version

Oh_The_Biomes_You'll_Go-forge-1.19.2-2.0.0.11.jar

### Terrablender Version

TerraBlender-forge-1.19.2-2.0.1.127.jar

### Mod Loader

Forge

### Mod Loader Version

43.1.30

### Bug Severity

Major

### What happened?

With BYG, BoP nether biome's basic blocks(ex: vanilla blackstone in Withered Abyss), unique blocks(ex: flesh block in Visceral Heap) and flora(ex: hair in Visceral Heap) are replace with normal netherrack. Consequently, this incompatibility deletes every BoP nether biomes existed.

BoP Modder suspects that this incompatibility may cause by BYG's TerraBlender’s Nether generation change.

TerraBlender-forge-1.19.2-2.0.1.127.jar
BiomesOPlenty-1.19.2-17.1.1.152.jar
Oh_The_Biomes_You'll_Go-forge-1.19.2-2.0.0.11.jar

### latest.log

.

### Did you isolate BYG?

I did not try BYG alone

**Comment by CorgiTaco** [comment]
Fixed in 1.19: https://github.com/AOCAWOL/BYG/commit/93d13cd9b0d44e0d16e196aa5c560e4f6a2307cf
Fixed in 1.18: https://github.com/AOCAWOL/BYG/commit/31a8c143166a5a7f1220440ae445d17b94de0394
