### ISSUE TITLE
[Bug]: 1.18.2 - Blue Netherrack does not behave as Netherrack in some important ways.

### ISSUE THREAD

**Issue by Inglonias** [CorgiTaco/BYG#981]
### Minecraft Version

1.18.2

### BYG Version

1.4.4

### Terrablender Version

1.2.0.126

### Mod Loader

Forge

### Mod Loader Version

40.1.73

### Bug Severity

Minor

### What happened?

Blue Netherrack cannot be used in recipes that call for netherrack, nor does it generate ancient debris pockets. In my current world, this is a problem, since I kind of want Netherite and can't get it easily. Embur Bog's are pretty dominant in my area of the Nether, and mostly contain blue netherrack. I also can't melt it in a Thermal Series Magma Crucible, but that's less important - I have plenty of red netherrack to melt for my power needs.

### latest.log

N/A. Not a crash.

### Did you isolate BYG?

I tried BYG alone

**Comment by CorgiTaco** [comment]
I suggest making a data pack to change the recipes you want to work with netherrack & blue netherrack. More on those here: https://minecraft.fandom.com/wiki/Recipe

And we do add blue netherrack to the required tags for Ancient Debris to spawn inside of it: https://github.com/AOCAWOL/BYG/blob/1.18.X/Common/src/main/resources/data/minecraft/tags/blocks/base_stone_nether.json
