### ISSUE TITLE
[1.18][Bug]: Sapling not growing 

### ISSUE THREAD

**Issue by elyse-ium** [CorgiTaco/BYG#985]
### BYG Version

1.4.4

### Terrablender Version

1.1.0.99

### Mod Loader

Forge

### Mod Loader Version

40.1.0

### Bug Severity

Minor

### What happened?

I can't grow a tree. I was putting bonemeal on a sapling in hopes of creating a tree but it's not growing.

### latest.log

It only crashes when the mod is isolated with terra blender.

### Did you isolate BYG?

I tried BYG alone

**Comment by CorgiTaco** [comment]
This issue should not be an issue on the latest version of byg. Which at the time of writing is 1.4.5

**Comment by elyse-ium** [comment]
> This issue should not be an issue on the latest version of byg. Which at the time of writing is 1.4.5

I'm on 1.4.5 now and it is still not working. Does it have something to do with my configurations?
