### ISSUE TITLE
[1.18][Bug]: sapling still not growing with bonemeal after update

### ISSUE THREAD

**Issue by elyse-ium** [CorgiTaco/BYG#988]
### BYG Version

1.4.6

### Terrablender Version

1.2.0.126

### Mod Loader

Forge

### Mod Loader Version

40.1.0

### Bug Severity

Minor

### What happened?

Sapling not growing when bonemealed.

### latest.log

No crash

### Did you isolate BYG?

I tried BYG alone

**Comment by CorgiTaco** [comment]
Have you looked at the tooltip on the item that shows the sapling pattern?
![image](https://user-images.githubusercontent.com/66983020/195946404-228ae733-67ea-4787-9006-96034b968771.png)

And when i hold shift it shows:
![image](https://user-images.githubusercontent.com/66983020/195946445-c75b0c37-c24f-4597-a445-28830b82721f.png)

And it grows like this: 

https://user-images.githubusercontent.com/66983020/195946731-10dd9f25-b972-47bd-ae83-c1f9e15b97ea.mp4

**Comment by elyse-ium** [comment]
> Have you looked at the tooltip on the item that shows the sapling pattern? ![image](https://user-images.githubusercontent.com/66983020/195946404-228ae733-67ea-4787-9006-96034b968771.png)
> 
> And when i hold shift it shows: ![image](https://user-images.githubusercontent.com/66983020/195946445-c75b0c37-c24f-4597-a445-28830b82721f.png)
> 
> And it grows like this:
> 
>  2022-10-14.14-26-46.mp4

Yes, I was trying to grow the zelkova tree and it's just one block but it's still not growing
