### ISSUE TITLE
[1.18][Bug]: sorry for bugging, sapling is still not growing (w/ video)

### ISSUE THREAD

**Issue by elyse-ium** [CorgiTaco/BYG#990]
### BYG Version

1.4.6

### Terrablender Version

1.2.0.126

### Mod Loader

Forge

### Mod Loader Version

40.1.0

### Bug Severity

Minor

### What happened?

Sapling not growing 

here is a video of me trying to grow the cypress tree:
https://user-images.githubusercontent.com/115489137/195964890-489d25dd-df50-4e0b-84fb-6a8ad08707fd.mp4

### latest.log

No crash

### Did you isolate BYG?

I tried BYG alone

**Comment by CorgiTaco** [comment]
hmm

**Comment by CorgiTaco** [comment]
could join our discord? https://discord.gg/2rtSAwzy

**Comment by CorgiTaco** [comment]
Tried on latest version of 1.18.2 BYG by itself and it works for me: 
![ezgif-2-790642684e](https://github.com/AOCAWOL/BYG/assets/66983020/1662be3d-01d5-4af1-99bd-8d680866eab0)

I'd suggest deleting your saplings config and letting it regen.
