### ISSUE TITLE
[1.19][Bug]: Sandstone recipes have incorrect tag ingredients

### ISSUE THREAD

**Issue by enigmaquip** [CorgiTaco/BYG#993]
### BYG Version

2.0.0.13

### Terrablender Version

2.0.1.128

### Mod Loader

Forge

### Mod Loader Version

43.1.43

### Bug Severity

Minor

### What happened?

sandstone crafting has fabric style c tags, but none of the sand have their respective tags

### latest.log

N/A

### Did you isolate BYG?

I did not try BYG alone

**Comment by ftheriachab** [comment]
Can confirm this is still a problem with the 2.0.0.13 version

**Comment by CorgiTaco** [comment]
Fixed in: https://github.com/AOCAWOL/BYG/pull/1016
