### ISSUE TITLE
[1.19][Bug]: Missing CurseForge dependency

### ISSUE THREAD

**Issue by wendall911** [CorgiTaco/BYG#994]
### BYG Version

2.0.0.13

### Terrablender Version

2.0.1.127

### Mod Loader

Fabric

### Mod Loader Version

0.14.10

### Bug Severity

Minor

### What happened?

geckolib is required in the current build. Game will crash if it is not installed.

### latest.log

[crash-2022-10-21_09.11.53-client.txt](https://github.com/AOCAWOL/BYG/files/9840754/crash-2022-10-21_09.11.53-client.txt)

### Did you isolate BYG?

I tried BYG alone

**Comment by CorgiTaco** [comment]
This BYG file was released a bit earlier than anticipated bc of a flaw on my end and has since been deleted. Use the latest 1.19 file present on curseforge
