### ISSUE TITLE
[1.19][Bug]: 

### ISSUE THREAD

**Issue by BosterJowls** [CorgiTaco/BYG#995]
### BYG Version

2.0.0.13

### Terrablender Version

2.0.1.127

### Mod Loader

Fabric

### Mod Loader Version

0.14.9

### Bug Severity

Major

### What happened?

Are Jacarinas Trees supposed to be growing really really tall?

![image](https://user-images.githubusercontent.com/113603837/197242738-a93d4852-65ca-4ae3-b97e-40f0775d6be9.png)

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/9840774/latest.log)

### Did you isolate BYG?

I tried BYG alone

**Comment by CorgiTaco** [comment]
This content was accidentally released, but yes they will in a future release
