### ISSUE TITLE
[1.19][Bug]: Ender lilies breaking causing fps drop

### ISSUE THREAD

**Issue by Artheow** [CorgiTaco/BYG#996]
### BYG Version

2.0.0.13

### Terrablender Version

2.0.1.128

### Mod Loader

Forge

### Mod Loader Version

43.1.43

### Bug Severity

Major

### What happened?

Upon entering the imparius grove biome, thousands of ender lilies breaks causing severe fps drops due to the sheer number of items in the water

### latest.log

N/A

### Did you isolate BYG?

I did not try BYG alone

**Comment by CorgiTaco** [comment]
Should no longer be an issue as of: https://github.com/AOCAWOL/BYG/commit/6a9cc86b1e96caa7ae0f48e307d5403a0264e959
