### ISSUE TITLE
[1.19][Crash]: Problem with the common_setup event phase

### ISSUE THREAD

**Issue by msg150308** [CorgiTaco/BYG#997]
### BYG Version

1.19.2

### Terrablender Version

2.0.1.128

### Mod Loader

Forge

### Mod Loader Version

43.1.43

### What happened?

I tried to start minecraft as i always do with this mod and other mods and it crashed saying something about the common_setup event phase. I tried the mod alone and in other versions and it kept crashing. When i tried to play without it every other mod worked. I don't know what's the problem.

### crash-log

https://gist.github.com/msg150308/a3100d11443db624c07445337a81cb51

### latest.log

https://gist.github.com/msg150308/101ac26e319e2a76bc4eb04e29280f63

### Did you isolate BYG?

I tried BYG alone

**Comment by blueacousticmusic** [comment]
Same problem here, even with an earlier Mod Loader Version (43.1.1) & BYG Version (1.19.2 - 2.0.0.11)

**Comment by ItsMaddieNow** [comment]
Did you use that profile prior to Minecraft 1.19 with BYG installed?

**Comment by ItsMaddieNow** [comment]
have you played BYG on minecraft 1.18 on this profile before?

**Comment by chibranche** [comment]
I did update forge and BYG from 1.18 (did not play in a while) and had the same bug

Edit : I deleted all mod configurations and it resolved the issue

**Comment by ItsMaddieNow** [comment]
Thats what I was getting at, it had a reference to "byg:mangrove_sapling" which was renamed to "byg:white_mangrove_sapling" in the update to 1.19 to differentiate it from regular mangroves.

**Comment by CorgiTaco** [comment]
Deelte your configs and let em regen
