### ISSUE TITLE
[1.19][Bug]: Flowering Tiny Lily Pads place Tiny Lily Pads, not flowering version

### ISSUE THREAD

**Issue by VinceKezel** [CorgiTaco/BYG#999]
### BYG Version

2.0.0.11

### Terrablender Version

2.0.1.127

### Mod Loader

Forge

### Mod Loader Version

43.1.32

### Bug Severity

Minor

### What happened?

When I break a "Tiny Flowering Lily Pad" items, it drops itself, and is held in inventory/hand as such. When placing, the item actually placed is a "Tiny Lily Pad" ... expected the Flowering version to be placed instead.

In the White Mangrove Marshes biome, both flowering and non-flowering types of lily pads are generated in.

### latest.log

N/A

### Did you isolate BYG?

I did not try BYG alone

**Comment by YaBoiChips** [comment]
fixed in next update
